In [2]:
import pandas as pd
import numpy as np

In [3]:
%cd /content/Walmart_sales_forecasting
save_file = "data/processed/sales_data_preprocessed.csv"

df_sales = pd.read_csv(save_file, parse_dates=['Date'])
df_sales

/content/Walmart_sales_forecasting

,Store,Dept,Date,Weekly_Sales,IsHoliday_x,Type,Size,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,IsHoliday_y
0,1,1,2010-02-05,24924.50,False,A,151315,42.31,2.572,0.00,0.00,0.00,0.00,0.00,211.096358,8.106,False
1,1,1,2010-02-12,46039.49,True,A,151315,38.51,2.548,0.00,0.00,0.00,0.00,0.00,211.242170,8.106,True
2,1,1,2010-02-19,41595.55,False,A,151315,39.93,2.514,0.00,0.00,0.00,0.00,0.00,211.289143,8.106,False
3,1,1,2010-02-26,19403.54,False,A,151315,46.63,2.561,0.00,0.00,0.00,0.00,0.00,211.319643,8.106,False
4,1,1,2010-03-05,21827.90,False,A,151315,46.50,2.625,0.00,0.00,0.00,0.00,0.00,211.350143,8.106,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
421565,45,98,2012-09-28,508.37,False,B,118221,64.88,3.997,4556.61,20.64,1.50,1601.01,3288.25,192.013558,8.684,False
421566,45,98,2012-10-05,628.10,False,B,118221,64.89,3.985,5046.74,0.00,18.82,2253.43,2340.01,192.170412,8.667,False
421567,45,98,2012-10-12,1061.02,False,B,118221,54.47,4.000,1956.28,0.00,7.89,599.32,3990.54,192.327265,8.667,False
421568,45,98,2012-10-19,760.01,False,B,118221,56.47,3.969,2004.02,0.00,3.18,437.73,1537.49,192.330854,8.667,False
421569,45,98,2012-10-26,1076.80,False,B,118221,58.85,3.882,4018.91,58.08,100.00,211.94,858.33,192.308899,8.667,False

In [4]:
df_feature = df_sales.copy()

In [5]:
test_split = pd.Timestamp("2012-08-05")
print(f'Test split day: {test_split}')
df_feature['is_test'] = df_feature['Date'] >= test_split
print(f'Num of test: {df_feature['is_test'].sum()}')
print(f'Num of train: {(~df_feature['is_test']).sum()}')

Test split day: 2012-08-05 00:00:00
Num of test: 35563
Num of train: 386007

In [6]:
temp_bins = [-np.inf, 18, 25, 32, np.inf]
temp_label = ['Cold', 'Cool', 'Warm', 'Hot']
df_feature['temp_category'] = pd.cut(df_feature['Temperature'], bins=temp_bins, labels=temp_label)
df_feature

,Store,Dept,Date,Weekly_Sales,IsHoliday_x,Type,Size,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,IsHoliday_y,is_test,temp_category
0,1,1,2010-02-05,24924.50,False,A,151315,42.31,2.572,0.00,0.00,0.00,0.00,0.00,211.096358,8.106,False,False,Hot
1,1,1,2010-02-12,46039.49,True,A,151315,38.51,2.548,0.00,0.00,0.00,0.00,0.00,211.242170,8.106,True,False,Hot
2,1,1,2010-02-19,41595.55,False,A,151315,39.93,2.514,0.00,0.00,0.00,0.00,0.00,211.289143,8.106,False,False,Hot
3,1,1,2010-02-26,19403.54,False,A,151315,46.63,2.561,0.00,0.00,0.00,0.00,0.00,211.319643,8.106,False,False,Hot
4,1,1,2010-03-05,21827.90,False,A,151315,46.50,2.625,0.00,0.00,0.00,0.00,0.00,211.350143,8.106,False,False,Hot
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
421565,45,98,2012-09-28,508.37,False,B,118221,64.88,3.997,4556.61,20.64,1.50,1601.01,3288.25,192.013558,8.684,False,True,Hot
421566,45,98,2012-10-05,628.10,False,B,118221,64.89,3.985,5046.74,0.00,18.82,2253.43,2340.01,192.170412,8.667,False,True,Hot
421567,45,98,2012-10-12,1061.02,False,B,118221,54.47,4.000,1956.28,0.00,7.89,599.32,3990.54,192.327265,8.667,False,True,Hot
421568,45,98,2012-10-19,760.01,False,B,118221,56.47,3.969,2004.02,0.00,3.18,437.73,1537.49,192.330854,8.667,False,True,Hot
421569,45,98,2012-10-26,1076.80,False,B,118221,58.85,3.882,4018.91,58.08,100.00,211.94,858.33,192.308899,8.667,False,True,Hot

In [7]:
df_feature = pd.get_dummies(df_feature, columns=['IsHoliday_y', 'temp_category'], drop_first=True)
df_feature

,Store,Dept,Date,Weekly_Sales,IsHoliday_x,Type,Size,Temperature,Fuel_Price,MarkDown1,...,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,is_test,IsHoliday_y_True,temp_category_Cool,temp_category_Warm,temp_category_Hot
0,1,1,2010-02-05,24924.50,False,A,151315,42.31,2.572,0.00,...,0.00,0.00,0.00,211.096358,8.106,False,False,False,False,True
1,1,1,2010-02-12,46039.49,True,A,151315,38.51,2.548,0.00,...,0.00,0.00,0.00,211.242170,8.106,False,True,False,False,True
2,1,1,2010-02-19,41595.55,False,A,151315,39.93,2.514,0.00,...,0.00,0.00,0.00,211.289143,8.106,False,False,False,False,True
3,1,1,2010-02-26,19403.54,False,A,151315,46.63,2.561,0.00,...,0.00,0.00,0.00,211.319643,8.106,False,False,False,False,True
4,1,1,2010-03-05,21827.90,False,A,151315,46.50,2.625,0.00,...,0.00,0.00,0.00,211.350143,8.106,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
421565,45,98,2012-09-28,508.37,False,B,118221,64.88,3.997,4556.61,...,1.50,1601.01,3288.25,192.013558,8.684,True,False,False,False,True
421566,45,98,2012-10-05,628.10,False,B,118221,64.89,3.985,5046.74,...,18.82,2253.43,2340.01,192.170412,8.667,True,False,False,False,True
421567,45,98,2012-10-12,1061.02,False,B,118221,54.47,4.000,1956.28,...,7.89,599.32,3990.54,192.327265,8.667,True,False,False,False,True
421568,45,98,2012-10-19,760.01,False,B,118221,56.47,3.969,2004.02,...,3.18,437.73,1537.49,192.330854,8.667,True,False,False,False,True
421569,45,98,2012-10-26,1076.80,False,B,118221,58.85,3.882,4018.91,...,100.00,211.94,858.33,192.308899,8.667,True,False,False,False,True

In [8]:
df_feature = df_feature.sort_values(['Date', 'Store', 'Dept'])
df_feature['store_dept'] = ' store_' + df_feature['Store'].astype(str) + '_' + 'dept_' + df_feature['Dept'].astype(str)
df_feature

,Store,Dept,Date,Weekly_Sales,IsHoliday_x,Type,Size,Temperature,Fuel_Price,MarkDown1,...,MarkDown4,MarkDown5,CPI,Unemployment,is_test,IsHoliday_y_True,temp_category_Cool,temp_category_Warm,temp_category_Hot,store_dept
0,1,1,2010-02-05,24924.50,False,A,151315,42.31,2.572,0.00,...,0.00,0.00,211.096358,8.106,False,False,False,False,True,store_1_dept_1
143,1,2,2010-02-05,50605.27,False,A,151315,42.31,2.572,0.00,...,0.00,0.00,211.096358,8.106,False,False,False,False,True,store_1_dept_2
286,1,3,2010-02-05,13740.12,False,A,151315,42.31,2.572,0.00,...,0.00,0.00,211.096358,8.106,False,False,False,False,True,store_1_dept_3
429,1,4,2010-02-05,39954.04,False,A,151315,42.31,2.572,0.00,...,0.00,0.00,211.096358,8.106,False,False,False,False,True,store_1_dept_4
572,1,5,2010-02-05,32229.38,False,A,151315,42.31,2.572,0.00,...,0.00,0.00,211.096358,8.106,False,False,False,False,True,store_1_dept_5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
421012,45,93,2012-10-26,2487.80,False,B,118221,58.85,3.882,4018.91,...,211.94,858.33,192.308899,8.667,True,False,False,False,True,store_45_dept_93
421146,45,94,2012-10-26,5203.31,False,B,118221,58.85,3.882,4018.91,...,211.94,858.33,192.308899,8.667,True,False,False,False,True,store_45_dept_94
421289,45,95,2012-10-26,56017.47,False,B,118221,58.85,3.882,4018.91,...,211.94,858.33,192.308899,8.667,True,False,False,False,True,store_45_dept_95
421434,45,97,2012-10-26,6817.48,False,B,118221,58.85,3.882,4018.91,...,211.94,858.33,192.308899,8.667,True,False,False,False,True,store_45_dept_97
421569,45,98,2012-10-26,1076.80,False,B,118221,58.85,3.882,4018.91,...,211.94,858.33,192.308899,8.667,True,False,False,False,True,store_45_dept_98

In [9]:
lags = [1, 2, 3]
for i in lags:
    df_feature[f'lags_{i}'] = df_feature.groupby('store_dept')['Weekly_Sales'].transform(lambda x : x.shift(i))
df_feature

,Store,Dept,Date,Weekly_Sales,IsHoliday_x,Type,Size,Temperature,Fuel_Price,MarkDown1,...,Unemployment,is_test,IsHoliday_y_True,temp_category_Cool,temp_category_Warm,temp_category_Hot,store_dept,lags_1,lags_2,lags_3
0,1,1,2010-02-05,24924.50,False,A,151315,42.31,2.572,0.00,...,8.106,False,False,False,False,True,store_1_dept_1,NaN,NaN,NaN
143,1,2,2010-02-05,50605.27,False,A,151315,42.31,2.572,0.00,...,8.106,False,False,False,False,True,store_1_dept_2,NaN,NaN,NaN
286,1,3,2010-02-05,13740.12,False,A,151315,42.31,2.572,0.00,...,8.106,False,False,False,False,True,store_1_dept_3,NaN,NaN,NaN
429,1,4,2010-02-05,39954.04,False,A,151315,42.31,2.572,0.00,...,8.106,False,False,False,False,True,store_1_dept_4,NaN,NaN,NaN
572,1,5,2010-02-05,32229.38,False,A,151315,42.31,2.572,0.00,...,8.106,False,False,False,False,True,store_1_dept_5,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
421012,45,93,2012-10-26,2487.80,False,B,118221,58.85,3.882,4018.91,...,8.667,True,False,False,False,True,store_45_dept_93,2270.50,2644.24,2807.14
421146,45,94,2012-10-26,5203.31,False,B,118221,58.85,3.882,4018.91,...,8.667,True,False,False,False,True,store_45_dept_94,4655.65,4041.28,3917.96
421289,45,95,2012-10-26,56017.47,False,B,118221,58.85,3.882,4018.91,...,8.667,True,False,False,False,True,store_45_dept_95,48434.97,49334.77,50241.01
421434,45,97,2012-10-26,6817.48,False,B,118221,58.85,3.882,4018.91,...,8.667,True,False,False,False,True,store_45_dept_97,5575.90,6463.32,6573.18
421569,45,98,2012-10-26,1076.80,False,B,118221,58.85,3.882,4018.91,...,8.667,True,False,False,False,True,store_45_dept_98,760.01,1061.02,628.10

In [12]:
df_feature['lags_1'].isna().sum()
print(f'percent of nan value: {(df_feature['lags_1'].isna().sum()) / df_feature['lags_1'].count()}' )

percent of nan value: 0.007964345744897057

therefore we will choose to drop nan rows

In [13]:
lags = [1, 2, 3]
df_feature = df_feature.dropna(subset=[f'lags_{i}' for i in lags])
df_feature

,Store,Dept,Date,Weekly_Sales,IsHoliday_x,Type,Size,Temperature,Fuel_Price,MarkDown1,...,Unemployment,is_test,IsHoliday_y_True,temp_category_Cool,temp_category_Warm,temp_category_Hot,store_dept,lags_1,lags_2,lags_3
3,1,1,2010-02-26,19403.54,False,A,151315,46.63,2.561,0.00,...,8.106,False,False,False,False,True,store_1_dept_1,41595.55,46039.49,24924.50
146,1,2,2010-02-26,44292.87,False,A,151315,46.63,2.561,0.00,...,8.106,False,False,False,False,True,store_1_dept_2,47928.89,44682.74,50605.27
289,1,3,2010-02-26,11135.17,False,A,151315,46.63,2.561,0.00,...,8.106,False,False,False,False,True,store_1_dept_3,11523.47,10887.84,13740.12
432,1,4,2010-02-26,34660.16,False,A,151315,46.63,2.561,0.00,...,8.106,False,False,False,False,True,store_1_dept_4,36826.95,35351.21,39954.04
575,1,5,2010-02-26,24101.89,False,A,151315,46.63,2.561,0.00,...,8.106,False,False,False,False,True,store_1_dept_5,26468.27,29620.81,32229.38
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
421012,45,93,2012-10-26,2487.80,False,B,118221,58.85,3.882,4018.91,...,8.667,True,False,False,False,True,store_45_dept_93,2270.50,2644.24,2807.14
421146,45,94,2012-10-26,5203.31,False,B,118221,58.85,3.882,4018.91,...,8.667,True,False,False,False,True,store_45_dept_94,4655.65,4041.28,3917.96
421289,45,95,2012-10-26,56017.47,False,B,118221,58.85,3.882,4018.91,...,8.667,True,False,False,False,True,store_45_dept_95,48434.97,49334.77,50241.01
421434,45,97,2012-10-26,6817.48,False,B,118221,58.85,3.882,4018.91,...,8.667,True,False,False,False,True,store_45_dept_97,5575.90,6463.32,6573.18
421569,45,98,2012-10-26,1076.80,False,B,118221,58.85,3.882,4018.91,...,8.667,True,False,False,False,True,store_45_dept_98,760.01,1061.02,628.10