In [1]:
!apt-get update && apt-get install -y build-essential

!pip install torchmetrics
!pip install cmdstanpy==1.2.5
!pip install prophet

Hit:1 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Hit:2 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease
Hit:3 https://cli.github.com/packages stable InRelease
Hit:4 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:5 https://r2u.stat.illinois.edu/ubuntu jammy InRelease
Hit:6 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:7 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:8 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:9 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:10 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Hit:11 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
build-essential is already the newest version (12.9ubuntu3).
0 upgraded, 0 newly installed, 0 to remove and 169 not upgraded.
Requirement already satisfied: torchmetrics in /usr/local/lib/python3.12/dist-packages (1.9.0)
Requirement already satisfied: numpy>1.20.0 in /usr/local/lib/python3.12/dist-packages (from torchmetrics) (2.0.2)
Requirement already satisfied: packaging>17.1 in /usr/local/lib/python3.12/dist-packages (from torchmetrics) (26.2)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from torchmetrics) (2.11.0+cu128)
Requirement already satisfied: lightning-utilities>=0.15.3 in /usr/local/lib/python3.12/dist-packages (from torchmetrics) (0.15.3)
Requirement already satisfied: typing_extensions in /usr/local/lib/python3.12/dist-packages (from lightning-utilities>=0.15.3->torchmetrics) (4.16.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->torchmetrics) (3.29.7)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->torchmetrics) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->torchmetrics) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->torchmetrics) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->torchmetrics) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->torchmetrics) (2025.3.0)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->torchmetrics) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->torchmetrics) (12.9.7)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->torchmetrics) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->torchmetrics) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->torchmetrics) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->torchmetrics) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->torchmetrics) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->torchmetrics) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->torchmetrics) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->torchmetrics) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->torchmetrics) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->torchmetrics) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->torchmetrics) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->torchmetrics) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->torchmetrics) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->torchmetrics) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->torchmetrics) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->torchmetrics) (12.8.90)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings<13,>=12.9.4->torch>=2.0.0->torchmetrics) (1.5.6)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.0.0->torchmetrics) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.0.0->torchmetrics) (3.0.3)
Requirement already satisfied: cmdstanpy==1.2.5 in /usr/local/lib/python3.12/dist-packages (1.2.5)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from cmdstanpy==1.2.5) (2.2.2)
Requirement already satisfied: numpy>=1.21 in /usr/local/lib/python3.12/dist-packages (from cmdstanpy==1.2.5) (2.0.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from cmdstanpy==1.2.5) (4.67.3)
Requirement already satisfied: stanio<2.0.0,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from cmdstanpy==1.2.5) (0.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->cmdstanpy==1.2.5) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->cmdstanpy==1.2.5) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->cmdstanpy==1.2.5) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->cmdstanpy==1.2.5) (1.17.0)
Requirement already satisfied: prophet in /usr/local/lib/python3.12/dist-packages (1.1.4)
Requirement already satisfied: cmdstanpy>=1.0.4 in /usr/local/lib/python3.12/dist-packages (from prophet) (1.2.5)
Requirement already satisfied: numpy>=1.15.4 in /usr/local/lib/python3.12/dist-packages (from prophet) (2.0.2)
Requirement already satisfied: matplotlib>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from prophet) (3.10.0)
Requirement already satisfied: pandas>=1.0.4 in /usr/local/lib/python3.12/dist-packages (from prophet) (2.2.2)
Requirement already satisfied: LunarCalendar>=0.0.9 in /usr/local/lib/python3.12/dist-packages (from prophet) (0.0.9)
Requirement already satisfied: convertdate>=2.1.2 in /usr/local/lib/python3.12/dist-packages (from prophet) (2.4.1)
Requirement already satisfied: holidays>=0.25 in /usr/local/lib/python3.12/dist-packages (from prophet) (0.100)
Requirement already satisfied: python-dateutil>=2.8.0 in /usr/local/lib/python3.12/dist-packages (from prophet) (2.9.0.post0)
Requirement already satisfied: tqdm>=4.36.1 in /usr/local/lib/python3.12/dist-packages (from prophet) (4.67.3)
Requirement already satisfied: importlib-resources in /usr/local/lib/python3.12/dist-packages (from prophet) (7.1.0)
Requirement already satisfied: stanio<2.0.0,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from cmdstanpy>=1.0.4->prophet) (0.5.1)
Requirement already satisfied: pymeeus<=1,>=0.3.13 in /usr/local/lib/python3.12/dist-packages (from convertdate>=2.1.2->prophet) (0.5.12)
Requirement already satisfied: ephem>=3.7.5.3 in /usr/local/lib/python3.12/dist-packages (from LunarCalendar>=0.0.9->prophet) (4.2.1)
Requirement already satisfied: pytz in /usr/local/lib/python3.12/dist-packages (from LunarCalendar>=0.0.9->prophet) (2025.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=2.0.0->prophet) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=2.0.0->prophet) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=2.0.0->prophet) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=2.0.0->prophet) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=2.0.0->prophet) (26.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=2.0.0->prophet) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=2.0.0->prophet) (3.3.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.4->prophet) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.0->prophet) (1.17.0)

In [2]:
!pip install --upgrade prophet

Requirement already satisfied: prophet in /usr/local/lib/python3.12/dist-packages (1.1.4)
Collecting prophet
  Downloading prophet-1.3.0-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (3.5 kB)
Requirement already satisfied: cmdstanpy>=1.0.4 in /usr/local/lib/python3.12/dist-packages (from prophet) (1.2.5)
Requirement already satisfied: numpy>=1.15.4 in /usr/local/lib/python3.12/dist-packages (from prophet) (2.0.2)
Requirement already satisfied: matplotlib>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from prophet) (3.10.0)
Requirement already satisfied: pandas>=1.0.4 in /usr/local/lib/python3.12/dist-packages (from prophet) (2.2.2)
Requirement already satisfied: holidays<1,>=0.25 in /usr/local/lib/python3.12/dist-packages (from prophet) (0.100)
Requirement already satisfied: tqdm>=4.36.1 in /usr/local/lib/python3.12/dist-packages (from prophet) (4.67.3)
Requirement already satisfied: importlib_resources in /usr/local/lib/python3.12/dist-packages (from prophet) (7.1.0)
Requirement already satisfied: stanio<2.0.0,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from cmdstanpy>=1.0.4->prophet) (0.5.1)
Requirement already satisfied: python-dateutil<3,>=2.9.0.post0 in /usr/local/lib/python3.12/dist-packages (from holidays<1,>=0.25->prophet) (2.9.0.post0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=2.0.0->prophet) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=2.0.0->prophet) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=2.0.0->prophet) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=2.0.0->prophet) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=2.0.0->prophet) (26.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=2.0.0->prophet) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=2.0.0->prophet) (3.3.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.4->prophet) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.4->prophet) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil<3,>=2.9.0.post0->holidays<1,>=0.25->prophet) (1.17.0)
Downloading prophet-1.3.0-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (12.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.1/12.1 MB 105.6 MB/s eta 0:00:0000:01:01
Installing collected packages: prophet
  Attempting uninstall: prophet
    Found existing installation: prophet 1.1.4
    Uninstalling prophet-1.1.4:
      Successfully uninstalled prophet-1.1.4
Successfully installed prophet-1.3.0

In [3]:
import pandas as pd
import numpy as np
import torch
from prophet import Prophet
from torchmetrics import WeightedMeanAbsolutePercentageError
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [4]:
%cd /content/Walmart_sales_forecasting
data_dir = 'data/processed/feature_engineering.feather'
df_feature = pd.read_feather(data_dir)
df_feature

/content/Walmart_sales_forecasting

,Store,Dept,Date,Weekly_Sales,Type,Size,Temperature,Fuel_Price,MarkDown1,MarkDown2,...,mean_sales_last_6_week,max_sales_last_6_week,min_sales_last_6_week,std_sales_last_6_week,emw_sales_0.5,emw_sales_0.75,sum_store_1_week,mean_store_1_week,sum_dept_1_week,mean_dept_1_week
6,1,1,2010-03-19,22136.64,A,151315,54.58,2.720,0.00,0.00,...,30360.018333,63593.12,7612.03,26384.953473,20940.430630,15246.700822,1242589.35,17258.185417,846686.47,18815.254889
149,1,2,2010-03-19,43615.49,A,151315,54.58,2.720,0.00,0.00,...,32780.786667,63593.12,7612.03,24477.831239,21538.535315,20414.155206,1242589.35,17258.185417,1742919.72,38731.549333
292,1,3,2010-03-19,9001.37,A,151315,54.58,2.720,0.00,0.00,...,29451.181667,61326.35,7612.03,20480.695326,32577.012657,37815.156301,1242589.35,17258.185417,371295.10,8251.002222
435,1,4,2010-03-19,34118.11,A,151315,54.58,2.720,0.00,0.00,...,20730.351667,43615.49,7612.03,14443.999382,20789.191329,16204.816575,1242589.35,17258.185417,1064848.12,23663.291556
578,1,5,2010-03-19,22632.57,A,151315,54.58,2.720,0.00,0.00,...,25148.031667,43615.49,9001.37,13661.565950,27453.650664,29639.786644,1242589.35,17258.185417,1063601.82,24734.926047
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
421012,45,93,2012-10-26,2487.80,B,118221,58.85,3.882,4018.91,58.08,...,17814.415000,54608.75,717.82,20287.128190,35354.118359,45312.322469,760281.43,11347.484030,1049693.34,24992.698571
421146,45,94,2012-10-26,5203.31,B,118221,58.85,3.882,4018.91,58.08,...,18109.411667,54608.75,1689.10,19999.636394,18920.959180,13193.930617,760281.43,11347.484030,1291378.41,29349.509318
421289,45,95,2012-10-26,56017.47,B,118221,58.85,3.882,4018.91,58.08,...,18695.113333,54608.75,2487.80,19466.945450,12062.134590,7200.965154,760281.43,11347.484030,1709432.51,37987.389111
421434,45,97,2012-10-26,6817.48,B,118221,58.85,3.882,4018.91,58.08,...,26666.748333,56017.47,2487.80,23647.747335,34039.802295,43813.343789,760281.43,11347.484030,596563.70,13558.265909
421569,45,98,2012-10-26,1076.80,B,118221,58.85,3.882,4018.91,58.08,...,23577.608333,56017.47,2487.80,25024.343292,20428.641147,16066.445947,760281.43,11347.484030,302469.28,7201.649524

In [5]:
df_feature.info()

<class 'pandas.core.frame.DataFrame'>
Index: 401996 entries, 6 to 421569
Data columns (total 46 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Store                   401996 non-null  int64
 1   Dept                    401996 non-null  int64
 2   Date                    401996 non-null  datetime64[ns]
 3   Weekly_Sales            401996 non-null  float64
 4   Type                    401996 non-null  object
 5   Size                    401996 non-null  int64
 6   Temperature             401996 non-null  float64
 7   Fuel_Price              401996 non-null  float64
 8   MarkDown1               401996 non-null  float64
 9   MarkDown2               401996 non-null  float64
 10  MarkDown3               401996 non-null  float64
 11  MarkDown4               401996 non-null  float64
 12  MarkDown5               401996 non-null  float64
 13  CPI                     401996 non-null  float64
 14  Unemployment            401996 non-null  float64
 15  is_test                 401996 non-null  bool
 16  total_markdown          401996 non-null  float64
 17  avg_markdown            401996 non-null  float64
 18  max_markdown            401996 non-null  float64
 19  IsHoliday_True          401996 non-null  bool
 20  temp_category_Cool      401996 non-null  bool
 21  temp_category_Warm      401996 non-null  bool
 22  temp_category_Hot       401996 non-null  bool
 23  Type_encoded            401996 non-null  int64
 24  store_dept              401996 non-null  object
 25  lags_2                  401996 non-null  float64
 26  lags_4                  401996 non-null  float64
 27  lags_6                  401996 non-null  float64
 28  mean_sales_last_2_week  401996 non-null  float64
 29  max_sales_last_2_week   401996 non-null  float64
 30  min_sales_last_2_week   401996 non-null  float64
 31  std_sales_last_2_week   401996 non-null  float64
 32  mean_sales_last_4_week  401996 non-null  float64
 33  max_sales_last_4_week   401996 non-null  float64
 34  min_sales_last_4_week   401996 non-null  float64
 35  std_sales_last_4_week   401996 non-null  float64
 36  mean_sales_last_6_week  401996 non-null  float64
 37  max_sales_last_6_week   401996 non-null  float64
 38  min_sales_last_6_week   401996 non-null  float64
 39  std_sales_last_6_week   401996 non-null  float64
 40  emw_sales_0.5           401996 non-null  float64
 41  emw_sales_0.75          401996 non-null  float64
 42  sum_store_1_week        401996 non-null  float64
 43  mean_store_1_week       401996 non-null  float64
 44  sum_dept_1_week         401996 non-null  float64
 45  mean_dept_1_week        401996 non-null  float64
dtypes: bool(5), datetime64[ns](1), float64(34), int64(4), object(2)
memory usage: 130.7+ MB

In [6]:
from sklearn.preprocessing import StandardScaler

reg_cols = ['Size', 'Temperature', 'Fuel_Price', 'total_markdown', 'avg_markdown', 'max_markdown']
scaler = StandardScaler()
df_feature[reg_cols] = scaler.fit_transform(df_feature[reg_cols])

In [7]:
test = df_feature[df_feature['is_test']]
train = df_feature[~df_feature['is_test']]

prophet_data = df_feature.groupby(['Date', 'store_dept']).agg(
    {
        'Weekly_Sales' : 'sum',
        'Size' : 'first',
        'Type_encoded' : 'first',
        'IsHoliday_True' : 'first',
        'Temperature': 'first',
        'Fuel_Price' : 'first',
        "total_markdown": "first",   
        "avg_markdown": "first",      
        "max_markdown": "first",
    }
).reset_index()

prophet_data

,Date,store_dept,Weekly_Sales,Size,Type_encoded,IsHoliday_True,Temperature,Fuel_Price,total_markdown,avg_markdown,max_markdown
0,2010-03-19,store_10_dept_1,38252.33,-0.169368,2,False,0.023575,-0.753511,-0.465845,-0.465845,-0.410875
1,2010-03-19,store_10_dept_10,49479.06,-0.169368,2,False,0.023575,-0.753511,-0.465845,-0.465845,-0.410875
2,2010-03-19,store_10_dept_11,30518.98,-0.169368,2,False,0.023575,-0.753511,-0.465845,-0.465845,-0.410875
3,2010-03-19,store_10_dept_12,11762.04,-0.169368,2,False,0.023575,-0.753511,-0.465845,-0.465845,-0.410875
4,2010-03-19,store_10_dept_13,65575.03,-0.169368,2,False,0.023575,-0.753511,-0.465845,-0.465845,-0.410875
...,...,...,...,...,...,...,...,...,...,...,...
401991,2012-10-26,store_9_dept_91,914.84,-0.180510,2,False,0.468290,0.259173,-0.319910,-0.319910,-0.245004
401992,2012-10-26,store_9_dept_92,18310.28,-0.180510,2,False,0.468290,0.259173,-0.319910,-0.319910,-0.245004
401993,2012-10-26,store_9_dept_94,233.02,-0.180510,2,False,0.468290,0.259173,-0.319910,-0.319910,-0.245004
401994,2012-10-26,store_9_dept_95,32382.05,-0.180510,2,False,0.468290,0.259173,-0.319910,-0.319910,-0.245004
401995,2012-10-26,store_9_dept_96,4752.25,-0.180510,2,False,0.468290,0.259173,-0.319910,-0.319910,-0.245004

In [8]:
def build_prophet_model(prophet_data,  test_data):
    min_test_time = test_data['Date'].min()
    max_test_time = test_data['Date'].max()
    
    prophet_model = {}
    prophet_predictions = {}
    prophet_metrics = pd.DataFrame(columns=['combo', 'mae', 'rmae', 'wape'])
    all_real = []
    all_predict = [] 
    
    
    for combination in prophet_data['store_dept'].unique():
        print(f'Build prophet model for {combination}')
        
        combo = prophet_data[prophet_data['store_dept'] == combination]
        combo = combo.rename(columns={'Date':'ds', 'Weekly_Sales' : 'y'}) #prophen require ds and y
        
        combo_train = combo[combo['ds'] < min_test_time]
        combo_test = combo[(combo['ds'] >= min_test_time) & (combo['ds'] <= max_test_time)]
        if combo_train.empty or combo_test.empty:
            print(f'Skip {combination} due to lack of data')
            continue
        
        model = Prophet(daily_seasonality=False,weekly_seasonality=True, yearly_seasonality=True, seasonality_mode='multiplicative', changepoint_prior_scale=0.5)
        
        for reg in [ 'IsHoliday_True', 'Temperature', 'Fuel_Price', 'total_markdown']:
            model.add_regressor(reg)
        
        try:
            model.fit(combo_train)
        except Exception as e:
            print(f'Fail to train {combination} : {e}')
            continue
        
        # test
        future = combo_test[['ds', 'Size', 'Type_encoded', 'IsHoliday_True', 'Temperature', 'Fuel_Price', 'total_markdown', 'avg_markdown', 'max_markdown']]
        forecast = model.predict(future)
        
        forecast = forecast[['ds', 'yhat', 'yhat_upper', 'yhat_lower']].merge(combo_test[['ds', 'y']], on=['ds'])
        
        prophet_model[combination] = model
        prophet_predictions[combination] = forecast
        
        # evaluate
        mae = mean_absolute_error(forecast['y'], forecast['yhat'])
        rmse = np.sqrt(mean_squared_error(forecast['y'], forecast['yhat']))
        wampe_metrics = WeightedMeanAbsolutePercentageError()
        y_pred = torch.tensor(forecast['yhat'].to_numpy(), dtype=torch.float32)
        y = torch.tensor(forecast['y'].to_numpy(), dtype=torch.float32)
        wampe = wampe_metrics(y_pred, y).item()
        
        prophet_metrics[len(prophet_metrics)] = [combo, mae, rmse, wampe]
        
        #overall evaluation
        all_real.extend(forecast['y'])
        all_predict.extend(forecast['yhat'])
        
    
    mean_mae = np.mean(prophet_metrics['mae'])
    mean_rmse = np.mean(prophet_metrics['rmse'])
    ovr_wampe = WeightedMeanAbsolutePercentageError(torch.from_numpy(np.array(all_real)), torch.from_numpy(np.array(all_predict)))
    
    return prophet_model, prophet_predictions, (mean_mae, mean_rmse, ovr_wampe)


prophet_model, prophet_predictions, (mean_mae, mean_rmse, ovr_wampe) = build_prophet_model(prophet_data,  test)

Build prophet model for  store_10_dept_1

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mmfu_5_x.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9nwv7cut.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=39989', 'data', 'file=/tmp/tmpjd45me00/mmfu_5_x.json', 'init=/tmp/tmpjd45me00/9nwv7cut.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modela2um5_fw/prophet_model-20260803144353.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:43:53 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:43:53 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/yuvu_zkt.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6jzb2rb5.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=28565', 'data', 'file=/tmp/tmpjd45me00/yuvu_zkt.json', 'init=/tmp/tmpjd45me00/6jzb2rb5.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelnnxi0png/prophet_model-20260803144353.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:43:53 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:43:53 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zs26hacr.json

Build prophet model for  store_10_dept_10
Build prophet model for  store_10_dept_11

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7k_i0su8.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=19565', 'data', 'file=/tmp/tmpjd45me00/zs26hacr.json', 'init=/tmp/tmpjd45me00/7k_i0su8.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelyli_xb7u/prophet_model-20260803144353.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:43:53 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:43:53 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/f8hay345.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vo5brz16.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=25108', 'data', 'file=/tmp/tmpjd45me00/f8hay345.json', 'init=/tmp/tmpjd45me00/vo5brz16.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelkex_eic5/prophet_model-20260803144353.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:43:53 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:43:53 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/crlqdti1.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/yoekf_vc.json

Build prophet model for  store_10_dept_12
Build prophet model for  store_10_dept_13

DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=22300', 'data', 'file=/tmp/tmpjd45me00/crlqdti1.json', 'init=/tmp/tmpjd45me00/yoekf_vc.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeldb7ipceu/prophet_model-20260803144353.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:43:53 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:43:53 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6ck0vkp3.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/k1vrh_ym.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=84971', 'data', 'file=/tmp/tmpjd45me00/6ck0vkp3.json', 'init=/tmp/tmpjd45me00/k1vrh_ym.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelk3kzhp49/prophet_model-20260803144353.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:43:53 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:43:53 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pxwaxggo.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/utlbaeu1.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=63502', 'data', 'file=/tmp/tmpjd45me00/pxwaxggo.json', 'init=/tmp/tmpjd45me00/utlbaeu1.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model9z2yakhy/prophet_model-20260803144354.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:43:54 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_10_dept_14
Build prophet model for  store_10_dept_16

14:43:54 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qhdfyjsz.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/a9uhcsol.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=69631', 'data', 'file=/tmp/tmpjd45me00/qhdfyjsz.json', 'init=/tmp/tmpjd45me00/a9uhcsol.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelgswnrmmu/prophet_model-20260803144354.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:43:54 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:43:54 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6tbh8jm2.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/sq14tpbg.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=63665', 'data', 'file=/tmp/tmpjd45me00/6tbh8jm2.json', 'init=/tmp/tmpjd45me00/sq14tpbg.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelwih68b2f/prophet_model-20260803144354.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:43:54 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_10_dept_17
Build prophet model for  store_10_dept_18

14:43:56 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/s5fbwxv3.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/n6ppn4sx.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=81886', 'data', 'file=/tmp/tmpjd45me00/s5fbwxv3.json', 'init=/tmp/tmpjd45me00/n6ppn4sx.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelxoza2u4l/prophet_model-20260803144356.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:43:56 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_10_dept_19

14:43:56 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_10_dept_2
Build prophet model for  store_10_dept_20

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zqrz35yj.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_jg8a7d_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=81388', 'data', 'file=/tmp/tmpjd45me00/zqrz35yj.json', 'init=/tmp/tmpjd45me00/_jg8a7d_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelldl7twqg/prophet_model-20260803144356.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:43:56 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:43:56 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/eciee_t1.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/933maux9.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=70196', 'data', 'file=/tmp/tmpjd45me00/eciee_t1.json', 'init=/tmp/tmpjd45me00/933maux9.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelzpll9mbm/prophet_model-20260803144357.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:43:57 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:43:57 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_10_dept_21

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/j_w_td60.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3bh83ypf.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=96157', 'data', 'file=/tmp/tmpjd45me00/j_w_td60.json', 'init=/tmp/tmpjd45me00/3bh83ypf.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelk4dsfs6a/prophet_model-20260803144357.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:43:57 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:43:57 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_10_dept_22
Build prophet model for  store_10_dept_23

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fhsyvebk.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1iadh_ts.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=78772', 'data', 'file=/tmp/tmpjd45me00/fhsyvebk.json', 'init=/tmp/tmpjd45me00/1iadh_ts.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelr73tjiz7/prophet_model-20260803144357.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:43:57 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:43:57 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jrh31_rm.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wvulfj1e.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=19729', 'data', 'file=/tmp/tmpjd45me00/jrh31_rm.json', 'init=/tmp/tmpjd45me00/wvulfj1e.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelgi3tp43l/prophet_model-20260803144357.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:43:57 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:43:57 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_10_dept_24

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1xm9qa11.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9_sbvrkd.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=61803', 'data', 'file=/tmp/tmpjd45me00/1xm9qa11.json', 'init=/tmp/tmpjd45me00/9_sbvrkd.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelab8twrt4/prophet_model-20260803144358.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:43:58 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:43:58 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/npu3q_29.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/h3joojew.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=69998', 'data', 'file=/tmp/tmpjd45me00/npu3q_29.json', 'init=/tmp/tmpjd45me00/h3joojew.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelwv2o8pfv/prophet_model-20260803144358.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']

Build prophet model for  store_10_dept_25
Build prophet model for  store_10_dept_26

14:43:58 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:43:58 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/o3bjt8yy.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fvu7m01d.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=94556', 'data', 'file=/tmp/tmpjd45me00/o3bjt8yy.json', 'init=/tmp/tmpjd45me00/fvu7m01d.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeltz6i8hc3/prophet_model-20260803144358.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:43:58 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:43:58 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5sgssoer.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5mmmnn92.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=62546', 'data', 'file=/tmp/tmpjd45me00/5sgssoer.json', 'init=/tmp/tmpjd45me00/5mmmnn92.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelma_pksy9/prophet_model-20260803144358.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:43:58 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_10_dept_27
Build prophet model for  store_10_dept_28

14:43:58 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/njg9vyut.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vhec6uga.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=69401', 'data', 'file=/tmp/tmpjd45me00/njg9vyut.json', 'init=/tmp/tmpjd45me00/vhec6uga.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelyoet34wr/prophet_model-20260803144358.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:43:58 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:43:58 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wo3t8kh1.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/uch1tsa_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=46380', 'data', 'file=/tmp/tmpjd45me00/wo3t8kh1.json', 'init=/tmp/tmpjd45me00/uch1tsa_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeltff9etwi/prophet_model-20260803144358.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:43:58 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_10_dept_29
Build prophet model for  store_10_dept_3

14:43:59 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/apz79lgs.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vwg_am5y.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=60514', 'data', 'file=/tmp/tmpjd45me00/apz79lgs.json', 'init=/tmp/tmpjd45me00/vwg_am5y.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelbsp29xyz/prophet_model-20260803144359.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:43:59 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:43:59 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_10_dept_30
Build prophet model for  store_10_dept_31

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/s2b56nf_.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/eaxcvucn.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=8370', 'data', 'file=/tmp/tmpjd45me00/s2b56nf_.json', 'init=/tmp/tmpjd45me00/eaxcvucn.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelvlazn96z/prophet_model-20260803144359.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:43:59 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:43:59 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/r5s91l8b.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/prb5gbfs.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=70188', 'data', 'file=/tmp/tmpjd45me00/r5s91l8b.json', 'init=/tmp/tmpjd45me00/prb5gbfs.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelb8lh_aby/prophet_model-20260803144359.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:43:59 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:43:59 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_10_dept_32

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ltd7p1or.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/58kj88a9.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=77338', 'data', 'file=/tmp/tmpjd45me00/ltd7p1or.json', 'init=/tmp/tmpjd45me00/58kj88a9.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelrd50kbgu/prophet_model-20260803144400.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:00 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:00 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dt52no0o.json

Build prophet model for  store_10_dept_33
Build prophet model for  store_10_dept_34

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/j1z7r2mk.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=24773', 'data', 'file=/tmp/tmpjd45me00/dt52no0o.json', 'init=/tmp/tmpjd45me00/j1z7r2mk.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model6cl_fskt/prophet_model-20260803144400.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:00 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:00 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zzwjg3mf.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/krykzngd.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=61435', 'data', 'file=/tmp/tmpjd45me00/zzwjg3mf.json', 'init=/tmp/tmpjd45me00/krykzngd.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model60ja46qy/prophet_model-20260803144400.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:00 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_10_dept_35

14:44:00 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qt_ud09m.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bob53s4w.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=47180', 'data', 'file=/tmp/tmpjd45me00/qt_ud09m.json', 'init=/tmp/tmpjd45me00/bob53s4w.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model4ez12ti9/prophet_model-20260803144400.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:00 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_10_dept_36

14:44:01 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1jdbctnh.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/h9dxgu71.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=86086', 'data', 'file=/tmp/tmpjd45me00/1jdbctnh.json', 'init=/tmp/tmpjd45me00/h9dxgu71.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model8e_7wxah/prophet_model-20260803144401.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:01 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:01 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/u3dqxue_.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/j4fh48q3.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=54040', 'data', 'file=/tmp/tmpjd45me00/u3dqxue_.json', 'init=/tmp/tmpjd45me00/j4fh48q3.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model72ls5i4t/prophet_model-20260803144401.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:01 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_10_dept_37
Build prophet model for  store_10_dept_38

14:44:01 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/c5kmjecg.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/94oh5fgk.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=90370', 'data', 'file=/tmp/tmpjd45me00/c5kmjecg.json', 'init=/tmp/tmpjd45me00/94oh5fgk.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelyr8gq2nd/prophet_model-20260803144401.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:01 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:01 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_10_dept_4
Build prophet model for  store_10_dept_40

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9dgxr70t.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gah9wrqu.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=53804', 'data', 'file=/tmp/tmpjd45me00/9dgxr70t.json', 'init=/tmp/tmpjd45me00/gah9wrqu.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelrvznqh6i/prophet_model-20260803144401.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:01 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:01 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_10_dept_41
Build prophet model for  store_10_dept_42

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5sr6e3td.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zs5v9hc2.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=75156', 'data', 'file=/tmp/tmpjd45me00/5sr6e3td.json', 'init=/tmp/tmpjd45me00/zs5v9hc2.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelk9fwb061/prophet_model-20260803144401.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:01 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:01 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/o_u2gsh6.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dhdim9ij.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=84155', 'data', 'file=/tmp/tmpjd45me00/o_u2gsh6.json', 'init=/tmp/tmpjd45me00/dhdim9ij.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modellw5tpx9j/prophet_model-20260803144402.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:02 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:02 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/tym377m5.json

Build prophet model for  store_10_dept_44
Build prophet model for  store_10_dept_45

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/eg_8f8je.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=60301', 'data', 'file=/tmp/tmpjd45me00/tym377m5.json', 'init=/tmp/tmpjd45me00/eg_8f8je.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelrrqhhjfs/prophet_model-20260803144402.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:44:02 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:03 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/iemd2f7h.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/sxdhqruj.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=25084', 'data', 'file=/tmp/tmpjd45me00/iemd2f7h.json', 'init=/tmp/tmpjd45me00/sxdhqruj.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelg_gcbpi9/prophet_model-20260803144403.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:03 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:03 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/syjdri34.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fjw6ng2e.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=19409', 'data', 'file=/tmp/tmpjd45me00/syjdri34.json', 'init=/tmp/tmpjd45me00/fjw6ng2e.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelnr3ytrxm/prophet_model-20260803144403.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:03 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_10_dept_46
Build prophet model for  store_10_dept_48

14:44:03 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/exx3rxje.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/81qewsse.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=78439', 'data', 'file=/tmp/tmpjd45me00/exx3rxje.json', 'init=/tmp/tmpjd45me00/81qewsse.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelw4d2ni3d/prophet_model-20260803144403.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:03 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:03 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/f2hvy0c6.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0g87x7v_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=38650', 'data', 'file=/tmp/tmpjd45me00/f2hvy0c6.json', 'init=/tmp/tmpjd45me00/0g87x7v_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelrncbgouw/prophet_model-20260803144403.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:03 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:03 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_10_dept_49
Build prophet model for  store_10_dept_5

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/h6mhfz_b.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_krx0t2g.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=42419', 'data', 'file=/tmp/tmpjd45me00/h6mhfz_b.json', 'init=/tmp/tmpjd45me00/_krx0t2g.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelhzn8eqg6/prophet_model-20260803144403.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:03 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:03 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_10_dept_50
Build prophet model for  store_10_dept_51
Skip  store_10_dept_51 due to lack of data
Build prophet model for  store_10_dept_52

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jlpu2c8w.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/o3k0_wsr.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=67753', 'data', 'file=/tmp/tmpjd45me00/jlpu2c8w.json', 'init=/tmp/tmpjd45me00/o3k0_wsr.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelj78gahtk/prophet_model-20260803144404.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:04 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:04 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jlkjveuc.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1vtx5act.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=66590', 'data', 'file=/tmp/tmpjd45me00/jlkjveuc.json', 'init=/tmp/tmpjd45me00/1vtx5act.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelddr7wnwu/prophet_model-20260803144404.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:04 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:04 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/u1x_imf6.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/kcsncg9z.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None

Build prophet model for  store_10_dept_54
Build prophet model for  store_10_dept_55

DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=18443', 'data', 'file=/tmp/tmpjd45me00/u1x_imf6.json', 'init=/tmp/tmpjd45me00/kcsncg9z.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelnkl_zsu7/prophet_model-20260803144404.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:04 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:04 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/klyzq2q4.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/eodhgh3k.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=40664', 'data', 'file=/tmp/tmpjd45me00/klyzq2q4.json', 'init=/tmp/tmpjd45me00/eodhgh3k.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model45t7qm1x/prophet_model-20260803144404.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:04 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:04 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fbh_r9x2.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/of4jgkmf.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=82575', 'data', 'file=/tmp/tmpjd45me00/fbh_r9x2.json', 'init=/tmp/tmpjd45me00/of4jgkmf.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelpfiaowqo/prophet_model-20260803144404.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:04 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_10_dept_56
Build prophet model for  store_10_dept_58

14:44:04 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/masispwe.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/evr4q8t6.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=12210', 'data', 'file=/tmp/tmpjd45me00/masispwe.json', 'init=/tmp/tmpjd45me00/evr4q8t6.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model0_jun4zh/prophet_model-20260803144404.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:04 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_10_dept_59

14:44:05 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xqpypxin.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/g0w8ebdr.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=64365', 'data', 'file=/tmp/tmpjd45me00/xqpypxin.json', 'init=/tmp/tmpjd45me00/g0w8ebdr.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model367div59/prophet_model-20260803144405.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:05 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:05 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_10_dept_6
Build prophet model for  store_10_dept_60

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mqv1x4rt.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gz5ktobi.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=90930', 'data', 'file=/tmp/tmpjd45me00/mqv1x4rt.json', 'init=/tmp/tmpjd45me00/gz5ktobi.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelrb1jlq1t/prophet_model-20260803144405.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:05 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:05 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/t2lq0vh8.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/e1u6_fdw.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=23654', 'data', 'file=/tmp/tmpjd45me00/t2lq0vh8.json', 'init=/tmp/tmpjd45me00/e1u6_fdw.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeleo9jpnxo/prophet_model-20260803144405.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:05 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:05 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0eeiv6lz.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vds2bevo.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=14844', 'data', 'file=/tmp/tmpjd45me00/0eeiv6lz.json', 'init=/tmp/tmpjd45me00/vds2bevo.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelxm5osog5/prophet_model-20260803144405.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:05 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_10_dept_67
Build prophet model for  store_10_dept_7

14:44:06 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ikedjmmi.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/n05wtf50.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=9688', 'data', 'file=/tmp/tmpjd45me00/ikedjmmi.json', 'init=/tmp/tmpjd45me00/n05wtf50.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model31uxdrdg/prophet_model-20260803144406.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:06 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:06 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_10_dept_71
Build prophet model for  store_10_dept_72

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7fk1xho5.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vhmfrihy.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=77188', 'data', 'file=/tmp/tmpjd45me00/7fk1xho5.json', 'init=/tmp/tmpjd45me00/vhmfrihy.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model8e018rn4/prophet_model-20260803144406.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:06 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:06 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mfwkabtq.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hsjq4l1v.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=36676', 'data', 'file=/tmp/tmpjd45me00/mfwkabtq.json', 'init=/tmp/tmpjd45me00/hsjq4l1v.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelfhamg40d/prophet_model-20260803144406.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:06 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_10_dept_74
Build prophet model for  store_10_dept_79

14:44:06 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/yh4ny88m.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/tp9ot3cd.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=50561', 'data', 'file=/tmp/tmpjd45me00/yh4ny88m.json', 'init=/tmp/tmpjd45me00/tp9ot3cd.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model2fd844tl/prophet_model-20260803144406.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:06 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:06 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4f_txw1x.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/lr8g19h8.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=9716', 'data', 'file=/tmp/tmpjd45me00/4f_txw1x.json', 'init=/tmp/tmpjd45me00/lr8g19h8.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeluvwi45um/prophet_model-20260803144407.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:07 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_10_dept_8
Build prophet model for  store_10_dept_80

14:44:07 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jaumr7cb.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/h9j1u3wu.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=17893', 'data', 'file=/tmp/tmpjd45me00/jaumr7cb.json', 'init=/tmp/tmpjd45me00/h9j1u3wu.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelk2aos7e0/prophet_model-20260803144407.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:07 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_10_dept_81

14:44:07 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0_6nnxg2.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jsrkcwzx.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=21215', 'data', 'file=/tmp/tmpjd45me00/0_6nnxg2.json', 'init=/tmp/tmpjd45me00/jsrkcwzx.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelvv7dhwtj/prophet_model-20260803144407.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:07 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:07 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jlrpa8dc.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/n2wzelan.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=65105', 'data', 'file=/tmp/tmpjd45me00/jlrpa8dc.json', 'init=/tmp/tmpjd45me00/n2wzelan.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelchvn9osq/prophet_model-20260803144407.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:07 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_10_dept_82
Build prophet model for  store_10_dept_83

14:44:08 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/sujgk2tg.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/05b429y4.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=70428', 'data', 'file=/tmp/tmpjd45me00/sujgk2tg.json', 'init=/tmp/tmpjd45me00/05b429y4.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modele5elrb18/prophet_model-20260803144408.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:08 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_10_dept_85

14:44:08 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/n1s02l6w.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vm9uz3y3.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=12270', 'data', 'file=/tmp/tmpjd45me00/n1s02l6w.json', 'init=/tmp/tmpjd45me00/vm9uz3y3.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelm814ym0r/prophet_model-20260803144408.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:08 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:08 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_10_dept_87

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/oh4z3zhi.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jfl9jcec.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=3878', 'data', 'file=/tmp/tmpjd45me00/oh4z3zhi.json', 'init=/tmp/tmpjd45me00/jfl9jcec.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modell22rjpvq/prophet_model-20260803144409.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:09 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:09 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_10_dept_9
Build prophet model for  store_10_dept_90

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7iwhbney.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3kwoxb5h.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=421', 'data', 'file=/tmp/tmpjd45me00/7iwhbney.json', 'init=/tmp/tmpjd45me00/3kwoxb5h.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelqn6crl7q/prophet_model-20260803144409.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:09 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:09 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dtezbrwh.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/s1z5i7kd.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=30760', 'data', 'file=/tmp/tmpjd45me00/dtezbrwh.json', 'init=/tmp/tmpjd45me00/s1z5i7kd.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeligry2qi4/prophet_model-20260803144409.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:09 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:09 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_10_dept_91

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1w5v5ruz.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ol013ckz.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=88813', 'data', 'file=/tmp/tmpjd45me00/1w5v5ruz.json', 'init=/tmp/tmpjd45me00/ol013ckz.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelpzya_0mj/prophet_model-20260803144410.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:10 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_10_dept_92

14:44:10 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jmremih5.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mmzk3fce.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=80268', 'data', 'file=/tmp/tmpjd45me00/jmremih5.json', 'init=/tmp/tmpjd45me00/mmzk3fce.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelddjc_6lb/prophet_model-20260803144410.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:10 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_10_dept_93

14:44:10 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3rmy31iv.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bzeny2gk.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=51706', 'data', 'file=/tmp/tmpjd45me00/3rmy31iv.json', 'init=/tmp/tmpjd45me00/bzeny2gk.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelt3wdfsal/prophet_model-20260803144410.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:44:10 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_10_dept_94

14:44:12 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/nc8jmrrz.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/p8jsk3ki.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=38942', 'data', 'file=/tmp/tmpjd45me00/nc8jmrrz.json', 'init=/tmp/tmpjd45me00/p8jsk3ki.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelgiujyypr/prophet_model-20260803144412.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:12 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:12 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_10_dept_95
Build prophet model for  store_10_dept_96

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/i3t4ckz7.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1ymic320.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=85749', 'data', 'file=/tmp/tmpjd45me00/i3t4ckz7.json', 'init=/tmp/tmpjd45me00/1ymic320.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeltiy1j6il/prophet_model-20260803144412.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:12 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:13 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5h0ukydu.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fiqo6xyu.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=72770', 'data', 'file=/tmp/tmpjd45me00/5h0ukydu.json', 'init=/tmp/tmpjd45me00/fiqo6xyu.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelxmauzv7_/prophet_model-20260803144413.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:13 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:13 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/sgdywb93.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zm8l8432.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=48006', 'data', 'file=/tmp/tmpjd45me00/sgdywb93.json', 'init=/tmp/tmpjd45me00/zm8l8432.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelmog2w249/prophet_model-20260803144413.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:44:13 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_10_dept_97
Build prophet model for  store_10_dept_98

14:44:14 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8_1ufycn.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7ecojp_y.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=77529', 'data', 'file=/tmp/tmpjd45me00/8_1ufycn.json', 'init=/tmp/tmpjd45me00/7ecojp_y.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model7a5iv8q9/prophet_model-20260803144414.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:15 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:15 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_11_dept_1
Build prophet model for  store_11_dept_10

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/n4sz7f33.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/oub42zfh.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=90302', 'data', 'file=/tmp/tmpjd45me00/n4sz7f33.json', 'init=/tmp/tmpjd45me00/oub42zfh.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model28qh60ve/prophet_model-20260803144415.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:15 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:15 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/e9z6x4kc.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/nl2349n5.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=97274', 'data', 'file=/tmp/tmpjd45me00/e9z6x4kc.json', 'init=/tmp/tmpjd45me00/nl2349n5.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeljql2eu11/prophet_model-20260803144415.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:15 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:15 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0wre2ks3.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/migjtknd.json
DEBUG:cmdstanpy:idx 0

Build prophet model for  store_11_dept_11
Build prophet model for  store_11_dept_12

DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=13862', 'data', 'file=/tmp/tmpjd45me00/0wre2ks3.json', 'init=/tmp/tmpjd45me00/migjtknd.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model8f09mm54/prophet_model-20260803144415.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:15 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:15 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bxmjrrlr.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4rcnss8f.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=84943', 'data', 'file=/tmp/tmpjd45me00/bxmjrrlr.json', 'init=/tmp/tmpjd45me00/4rcnss8f.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelng7sk0ud/prophet_model-20260803144415.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:15 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:15 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_11_dept_13
Build prophet model for  store_11_dept_14

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1z9zp_jl.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8azx8w_7.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=79276', 'data', 'file=/tmp/tmpjd45me00/1z9zp_jl.json', 'init=/tmp/tmpjd45me00/8azx8w_7.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeldg3lrxai/prophet_model-20260803144415.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:15 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:15 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fin70a7x.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/475zeb1e.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=44215', 'data', 'file=/tmp/tmpjd45me00/fin70a7x.json', 'init=/tmp/tmpjd45me00/475zeb1e.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model4t5gn3tl/prophet_model-20260803144416.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:16 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:16 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hgw9ctjj.json

Build prophet model for  store_11_dept_16
Build prophet model for  store_11_dept_17

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/a1g12wfn.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=55403', 'data', 'file=/tmp/tmpjd45me00/hgw9ctjj.json', 'init=/tmp/tmpjd45me00/a1g12wfn.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modellpqdiu65/prophet_model-20260803144416.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:16 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:16 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jd8q4cde.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pum0ejfg.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=73258', 'data', 'file=/tmp/tmpjd45me00/jd8q4cde.json', 'init=/tmp/tmpjd45me00/pum0ejfg.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model4kx8kjb_/prophet_model-20260803144416.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:16 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:16 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7baeulet.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/lqvrrqj5.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=44401', 'data', 'file=/tmp/tmpjd45me00/7baeulet.json', 'init=/tmp/tmpjd45me00/lqvrrqj5.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeliom6ilsd/prophet_model-20260803144416.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:16 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_11_dept_18
Build prophet model for  store_11_dept_2

14:44:16 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1jh41th9.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4z4gsftq.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=71494', 'data', 'file=/tmp/tmpjd45me00/1jh41th9.json', 'init=/tmp/tmpjd45me00/4z4gsftq.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelau6_0kcf/prophet_model-20260803144416.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:16 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:16 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4wtbhty2.json

Build prophet model for  store_11_dept_20
Build prophet model for  store_11_dept_21

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_e3906ut.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=83623', 'data', 'file=/tmp/tmpjd45me00/4wtbhty2.json', 'init=/tmp/tmpjd45me00/_e3906ut.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelydx0k_bj/prophet_model-20260803144416.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:16 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:16 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/yb61hfzo.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8e8pg9ik.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=89487', 'data', 'file=/tmp/tmpjd45me00/yb61hfzo.json', 'init=/tmp/tmpjd45me00/8e8pg9ik.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeluitz4ykm/prophet_model-20260803144417.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:17 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:17 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/g84g70xz.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/y3vscg7_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=49605', 'data', 'file=/tmp/tmpjd45me00/g84g70xz.json', 'init=/tmp/tmpjd45me00/y3vscg7_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelgq0cxzl5/prophet_model-20260803144417.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:17 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_11_dept_22
Build prophet model for  store_11_dept_23

14:44:17 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mba7erfw.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/j3jzl70u.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=19607', 'data', 'file=/tmp/tmpjd45me00/mba7erfw.json', 'init=/tmp/tmpjd45me00/j3jzl70u.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeldn9xnmof/prophet_model-20260803144417.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:17 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:17 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dwudlm60.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ssr5gah1.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=69368', 'data', 'file=/tmp/tmpjd45me00/dwudlm60.json', 'init=/tmp/tmpjd45me00/ssr5gah1.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelrnjfe6u8/prophet_model-20260803144417.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:17 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_11_dept_24
Build prophet model for  store_11_dept_25

14:44:17 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/24as7ac0.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/g1lc_c2q.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=16185', 'data', 'file=/tmp/tmpjd45me00/24as7ac0.json', 'init=/tmp/tmpjd45me00/g1lc_c2q.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelvm99y6y7/prophet_model-20260803144417.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:17 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:17 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/z4i_qygq.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/y_y0gvqu.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=12458', 'data', 'file=/tmp/tmpjd45me00/z4i_qygq.json', 'init=/tmp/tmpjd45me00/y_y0gvqu.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model4i3kvi5t/prophet_model-20260803144417.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:17 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_11_dept_26
Build prophet model for  store_11_dept_27

14:44:17 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/menrtu4c.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dggv0gl2.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=28391', 'data', 'file=/tmp/tmpjd45me00/menrtu4c.json', 'init=/tmp/tmpjd45me00/dggv0gl2.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model8mcyik2l/prophet_model-20260803144418.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:18 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:18 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ntx1xh60.json

Build prophet model for  store_11_dept_28
Build prophet model for  store_11_dept_29

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hnqyrapy.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=48730', 'data', 'file=/tmp/tmpjd45me00/ntx1xh60.json', 'init=/tmp/tmpjd45me00/hnqyrapy.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelql7dyde0/prophet_model-20260803144418.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:18 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:18 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rrg_vqag.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gsi63_5y.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=18672', 'data', 'file=/tmp/tmpjd45me00/rrg_vqag.json', 'init=/tmp/tmpjd45me00/gsi63_5y.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model3hb7biev/prophet_model-20260803144418.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:18 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:18 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6kdj6vto.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/biy3t3rl.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=62252', 'data', 'file=/tmp/tmpjd45me00/6kdj6vto.json', 'init=/tmp/tmpjd45me00/biy3t3rl.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelj_h8up0i/prophet_model-20260803144418.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:18 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_11_dept_3
Build prophet model for  store_11_dept_30

14:44:18 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/g7n3qvnq.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ctpbcsgb.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=81113', 'data', 'file=/tmp/tmpjd45me00/g7n3qvnq.json', 'init=/tmp/tmpjd45me00/ctpbcsgb.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model9ed46woa/prophet_model-20260803144419.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:19 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:19 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1g9b_sfl.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vq9xrlys.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=91528', 'data', 'file=/tmp/tmpjd45me00/1g9b_sfl.json', 'init=/tmp/tmpjd45me00/vq9xrlys.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelhjj1svu9/prophet_model-20260803144419.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:19 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_11_dept_31
Build prophet model for  store_11_dept_32

14:44:19 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/w51xj9n7.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/b8xgm7cg.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=56568', 'data', 'file=/tmp/tmpjd45me00/w51xj9n7.json', 'init=/tmp/tmpjd45me00/b8xgm7cg.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelk5ypt_2x/prophet_model-20260803144419.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:19 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:19 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/df_ufbyu.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/l25u_of6.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=38102', 'data', 'file=/tmp/tmpjd45me00/df_ufbyu.json', 'init=/tmp/tmpjd45me00/l25u_of6.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelftpaxian/prophet_model-20260803144419.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:19 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_11_dept_33
Build prophet model for  store_11_dept_34

14:44:19 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/djqynkqk.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4z120pzf.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=55746', 'data', 'file=/tmp/tmpjd45me00/djqynkqk.json', 'init=/tmp/tmpjd45me00/4z120pzf.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model0uday1g1/prophet_model-20260803144419.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:19 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:19 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_11_dept_35

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/uhunym4h.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9q52g7vf.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=35328', 'data', 'file=/tmp/tmpjd45me00/uhunym4h.json', 'init=/tmp/tmpjd45me00/9q52g7vf.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelcleb6n4t/prophet_model-20260803144419.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:19 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:20 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_11_dept_36
Build prophet model for  store_11_dept_37

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/yqc662u1.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ffpwilm6.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=79801', 'data', 'file=/tmp/tmpjd45me00/yqc662u1.json', 'init=/tmp/tmpjd45me00/ffpwilm6.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model81_hj2ua/prophet_model-20260803144420.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:20 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:20 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/80axp6s_.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zex4sip8.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=87884', 'data', 'file=/tmp/tmpjd45me00/80axp6s_.json', 'init=/tmp/tmpjd45me00/zex4sip8.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model9ki5uovx/prophet_model-20260803144420.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:20 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:20 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2g5n2kn8.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/x0hrigxu.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=95629', 'data', 'file=/tmp/tmpjd45me00/2g5n2kn8.json', 'init=/tmp/tmpjd45me00/x0hrigxu.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelc6_u5y3t/prophet_model-20260803144420.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:20 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_11_dept_38
Build prophet model for  store_11_dept_4

14:44:20 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/at7a8e8u.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0gbtdk3h.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=50346', 'data', 'file=/tmp/tmpjd45me00/at7a8e8u.json', 'init=/tmp/tmpjd45me00/0gbtdk3h.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelb8pupqn3/prophet_model-20260803144420.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:20 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:20 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_11_dept_40

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/c0afz5vh.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/v4y2zgkz.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=1635', 'data', 'file=/tmp/tmpjd45me00/c0afz5vh.json', 'init=/tmp/tmpjd45me00/v4y2zgkz.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelao2pse_v/prophet_model-20260803144421.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:21 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_11_dept_41

14:44:21 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dl3o5i0b.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/41ge06mo.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=29880', 'data', 'file=/tmp/tmpjd45me00/dl3o5i0b.json', 'init=/tmp/tmpjd45me00/41ge06mo.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model7xf7pw4i/prophet_model-20260803144421.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:21 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:21 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_11_dept_42
Build prophet model for  store_11_dept_44

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8r2rk14u.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0pik75bs.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=24265', 'data', 'file=/tmp/tmpjd45me00/8r2rk14u.json', 'init=/tmp/tmpjd45me00/0pik75bs.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelpca7pfwq/prophet_model-20260803144421.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:21 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:22 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/yqaqqvjw.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/n1_crp9_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=11713', 'data', 'file=/tmp/tmpjd45me00/yqaqqvjw.json', 'init=/tmp/tmpjd45me00/n1_crp9_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_s8rh50r/prophet_model-20260803144422.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:22 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:22 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_11_dept_46

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8agqgy1r.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gv64i89h.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=66040', 'data', 'file=/tmp/tmpjd45me00/8agqgy1r.json', 'init=/tmp/tmpjd45me00/gv64i89h.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelwn0b6v6f/prophet_model-20260803144422.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:22 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:22 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_11_dept_49

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7ahwzwva.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/uw9e1e0w.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=11299', 'data', 'file=/tmp/tmpjd45me00/7ahwzwva.json', 'init=/tmp/tmpjd45me00/uw9e1e0w.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeloghzfc00/prophet_model-20260803144422.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:22 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:22 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_11_dept_5

INFO:prophet:n_changepoints greater than number of observations. Using 17.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/w7kpic01.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4_v4nbox.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=91168', 'data', 'file=/tmp/tmpjd45me00/w7kpic01.json', 'init=/tmp/tmpjd45me00/4_v4nbox.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modellyapzy76/prophet_model-20260803144423.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:44:23 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_11_dept_51

14:44:23 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0c0zzv7h.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/nr1yape1.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=50291', 'data', 'file=/tmp/tmpjd45me00/0c0zzv7h.json', 'init=/tmp/tmpjd45me00/nr1yape1.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelfk1vjhj6/prophet_model-20260803144424.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:24 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_11_dept_52

14:44:24 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_gd5ncz6.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/yt5ho6np.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=93535', 'data', 'file=/tmp/tmpjd45me00/_gd5ncz6.json', 'init=/tmp/tmpjd45me00/yt5ho6np.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelcffn1hcl/prophet_model-20260803144424.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:24 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:24 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_11_dept_54

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/x5v8z1fw.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/aa5cx6j8.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=12817', 'data', 'file=/tmp/tmpjd45me00/x5v8z1fw.json', 'init=/tmp/tmpjd45me00/aa5cx6j8.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelo80kx04e/prophet_model-20260803144424.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:24 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:24 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fszv1mog.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/sws41s1s.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=80404', 'data', 'file=/tmp/tmpjd45me00/fszv1mog.json', 'init=/tmp/tmpjd45me00/sws41s1s.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model2__6ifgg/prophet_model-20260803144424.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:24 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_11_dept_55
Build prophet model for  store_11_dept_56

14:44:24 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2sn6r6mf.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/57pdljif.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=4088', 'data', 'file=/tmp/tmpjd45me00/2sn6r6mf.json', 'init=/tmp/tmpjd45me00/57pdljif.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model837e8gsn/prophet_model-20260803144425.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:25 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:25 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_11_dept_58

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/br3qrtvv.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/z_0glbb_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=28692', 'data', 'file=/tmp/tmpjd45me00/br3qrtvv.json', 'init=/tmp/tmpjd45me00/z_0glbb_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelxkwkrsdp/prophet_model-20260803144425.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:25 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_11_dept_59

14:44:25 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ljcje6gb.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1ha_jwzs.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=58318', 'data', 'file=/tmp/tmpjd45me00/ljcje6gb.json', 'init=/tmp/tmpjd45me00/1ha_jwzs.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model2ljpgyk2/prophet_model-20260803144425.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:25 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_11_dept_6

14:44:25 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/a3r_v0g8.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6ddtx4m3.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=82127', 'data', 'file=/tmp/tmpjd45me00/a3r_v0g8.json', 'init=/tmp/tmpjd45me00/6ddtx4m3.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelu21fd0js/prophet_model-20260803144425.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:25 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:25 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/w63mspdc.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ybe0btws.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=84244', 'data', 'file=/tmp/tmpjd45me00/w63mspdc.json', 'init=/tmp/tmpjd45me00/ybe0btws.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modellazqxtbu/prophet_model-20260803144426.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:26 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_11_dept_67
Build prophet model for  store_11_dept_7

14:44:26 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_scujp2n.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/86isqa2w.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=35445', 'data', 'file=/tmp/tmpjd45me00/_scujp2n.json', 'init=/tmp/tmpjd45me00/86isqa2w.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model58bdq7k9/prophet_model-20260803144426.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:26 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:26 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_11_dept_71
Build prophet model for  store_11_dept_72

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_uu0hnly.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jnbssgfi.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=42755', 'data', 'file=/tmp/tmpjd45me00/_uu0hnly.json', 'init=/tmp/tmpjd45me00/jnbssgfi.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model882hng3w/prophet_model-20260803144426.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:26 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:26 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4978um4_.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jz7hf8hg.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=54638', 'data', 'file=/tmp/tmpjd45me00/4978um4_.json', 'init=/tmp/tmpjd45me00/jz7hf8hg.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelesez0h3z/prophet_model-20260803144426.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:26 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:26 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/tuko83fn.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/njriqq1g.json

Build prophet model for  store_11_dept_74
Build prophet model for  store_11_dept_79

DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=44376', 'data', 'file=/tmp/tmpjd45me00/tuko83fn.json', 'init=/tmp/tmpjd45me00/njriqq1g.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model9kza6cgn/prophet_model-20260803144426.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:26 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:26 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/o6zryluf.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/yo17vo4s.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=88622', 'data', 'file=/tmp/tmpjd45me00/o6zryluf.json', 'init=/tmp/tmpjd45me00/yo17vo4s.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model8njlwuik/prophet_model-20260803144426.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:26 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:26 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2mheqla8.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/le9zqs9s.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=84639', 'data', 'file=/tmp/tmpjd45me00/2mheqla8.json', 'init=/tmp/tmpjd45me00/le9zqs9s.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelz2ocuq_3/prophet_model-20260803144427.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:27 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_11_dept_8
Build prophet model for  store_11_dept_80

14:44:27 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/yod7vdgh.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/kaitmwa4.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=95850', 'data', 'file=/tmp/tmpjd45me00/yod7vdgh.json', 'init=/tmp/tmpjd45me00/kaitmwa4.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model8i_yphcu/prophet_model-20260803144427.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:27 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:27 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/a9z7movi.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/v380g7rb.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=66042', 'data', 'file=/tmp/tmpjd45me00/a9z7movi.json', 'init=/tmp/tmpjd45me00/v380g7rb.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modellau3u72h/prophet_model-20260803144427.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:27 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:27 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_11_dept_81
Build prophet model for  store_11_dept_82

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/n8mjnq5_.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0h6mi874.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=15846', 'data', 'file=/tmp/tmpjd45me00/n8mjnq5_.json', 'init=/tmp/tmpjd45me00/0h6mi874.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model1r0admi_/prophet_model-20260803144427.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:27 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:27 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/77kig1hg.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2l115l7p.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=87875', 'data', 'file=/tmp/tmpjd45me00/77kig1hg.json', 'init=/tmp/tmpjd45me00/2l115l7p.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model2y9aj9ou/prophet_model-20260803144427.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:27 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_11_dept_83
Build prophet model for  store_11_dept_85

14:44:27 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6d1wt4uh.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/h_2p5hs6.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=35856', 'data', 'file=/tmp/tmpjd45me00/6d1wt4uh.json', 'init=/tmp/tmpjd45me00/h_2p5hs6.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelkpshmjzw/prophet_model-20260803144427.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:27 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:28 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ddwpa_cr.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/353fwa51.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=74465', 'data', 'file=/tmp/tmpjd45me00/ddwpa_cr.json', 'init=/tmp/tmpjd45me00/353fwa51.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelzu20cee_/prophet_model-20260803144428.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:28 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_11_dept_87
Build prophet model for  store_11_dept_9

14:44:28 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/odoj94kc.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/z7z3cvj3.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=96766', 'data', 'file=/tmp/tmpjd45me00/odoj94kc.json', 'init=/tmp/tmpjd45me00/z7z3cvj3.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model06gmwsff/prophet_model-20260803144428.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:28 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:28 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/liacyxzy.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/j4q1x_qp.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=89258', 'data', 'file=/tmp/tmpjd45me00/liacyxzy.json', 'init=/tmp/tmpjd45me00/j4q1x_qp.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeldhhpa4ni/prophet_model-20260803144428.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:28 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_11_dept_90
Build prophet model for  store_11_dept_91

14:44:28 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/upgdw64k.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/drmuwxo9.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=58654', 'data', 'file=/tmp/tmpjd45me00/upgdw64k.json', 'init=/tmp/tmpjd45me00/drmuwxo9.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model9cwrtboy/prophet_model-20260803144428.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:28 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:28 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9ijouod8.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vj_t1c32.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=27033', 'data', 'file=/tmp/tmpjd45me00/9ijouod8.json', 'init=/tmp/tmpjd45me00/vj_t1c32.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelzxt0m47x/prophet_model-20260803144429.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:29 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_11_dept_92
Build prophet model for  store_11_dept_93

14:44:29 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/revnhh4k.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/asgn4kw7.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=78725', 'data', 'file=/tmp/tmpjd45me00/revnhh4k.json', 'init=/tmp/tmpjd45me00/asgn4kw7.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelw4jw_9_8/prophet_model-20260803144429.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:29 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:29 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_11_dept_94
Build prophet model for  store_11_dept_95

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/osc1vncv.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mnt3cbs6.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=98741', 'data', 'file=/tmp/tmpjd45me00/osc1vncv.json', 'init=/tmp/tmpjd45me00/mnt3cbs6.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model4xrzwy2m/prophet_model-20260803144429.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:29 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:29 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fg6t556g.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/um5jxf5d.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=21105', 'data', 'file=/tmp/tmpjd45me00/fg6t556g.json', 'init=/tmp/tmpjd45me00/um5jxf5d.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelnvdvihue/prophet_model-20260803144429.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:29 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:29 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/b_05g60i.json

Build prophet model for  store_11_dept_96
Build prophet model for  store_11_dept_97

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5r86kmua.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=47919', 'data', 'file=/tmp/tmpjd45me00/b_05g60i.json', 'init=/tmp/tmpjd45me00/5r86kmua.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model7rzbxca0/prophet_model-20260803144429.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:29 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:29 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ve5xz4of.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zxrd5pwv.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=36142', 'data', 'file=/tmp/tmpjd45me00/ve5xz4of.json', 'init=/tmp/tmpjd45me00/zxrd5pwv.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelaup2hzoy/prophet_model-20260803144429.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:29 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:29 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/whx5i9hq.json

Build prophet model for  store_11_dept_98
Build prophet model for  store_12_dept_1

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2c91yu1s.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=8085', 'data', 'file=/tmp/tmpjd45me00/whx5i9hq.json', 'init=/tmp/tmpjd45me00/2c91yu1s.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelve5sekyr/prophet_model-20260803144430.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:30 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:30 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/20yb3fzo.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ilvypaxk.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=1225', 'data', 'file=/tmp/tmpjd45me00/20yb3fzo.json', 'init=/tmp/tmpjd45me00/ilvypaxk.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model5mv35au7/prophet_model-20260803144430.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:30 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:30 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4ymgjk4v.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8lhivm6n.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=24522', 'data', 'file=/tmp/tmpjd45me00/4ymgjk4v.json', 'init=/tmp/tmpjd45me00/8lhivm6n.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelmit_5r67/prophet_model-20260803144430.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:30 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_12_dept_10
Build prophet model for  store_12_dept_11

14:44:30 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8auxnnwh.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/s2o3c7ju.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=12481', 'data', 'file=/tmp/tmpjd45me00/8auxnnwh.json', 'init=/tmp/tmpjd45me00/s2o3c7ju.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelnrh92lps/prophet_model-20260803144430.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:30 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:30 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/65n3cjlz.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/cw8qjp5z.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=21208', 'data', 'file=/tmp/tmpjd45me00/65n3cjlz.json', 'init=/tmp/tmpjd45me00/cw8qjp5z.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeln3424eys/prophet_model-20260803144430.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:30 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_12_dept_12
Build prophet model for  store_12_dept_13

14:44:30 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/v36r82_6.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jsu4buby.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=67813', 'data', 'file=/tmp/tmpjd45me00/v36r82_6.json', 'init=/tmp/tmpjd45me00/jsu4buby.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_5nnz0gc/prophet_model-20260803144430.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:30 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:30 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/u40kx1ws.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wwut9w04.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=29501', 'data', 'file=/tmp/tmpjd45me00/u40kx1ws.json', 'init=/tmp/tmpjd45me00/wwut9w04.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeldlf02h3p/prophet_model-20260803144431.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:31 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_12_dept_14
Build prophet model for  store_12_dept_16

14:44:31 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/sndu98_g.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fik4y712.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=84435', 'data', 'file=/tmp/tmpjd45me00/sndu98_g.json', 'init=/tmp/tmpjd45me00/fik4y712.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelak80hwf7/prophet_model-20260803144431.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:31 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:31 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_12_dept_17

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/tr6oo4mb.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/33rbra4j.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=26732', 'data', 'file=/tmp/tmpjd45me00/tr6oo4mb.json', 'init=/tmp/tmpjd45me00/33rbra4j.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model7xva86m1/prophet_model-20260803144431.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:44:31 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_12_dept_18

14:44:32 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qtwioeir.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/up1qm83w.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=80099', 'data', 'file=/tmp/tmpjd45me00/qtwioeir.json', 'init=/tmp/tmpjd45me00/up1qm83w.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelr52eb3g1/prophet_model-20260803144432.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:32 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:32 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_12_dept_19
Build prophet model for  store_12_dept_2

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hiju27gx.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3fm41c7v.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=45992', 'data', 'file=/tmp/tmpjd45me00/hiju27gx.json', 'init=/tmp/tmpjd45me00/3fm41c7v.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelkkxcmclf/prophet_model-20260803144433.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:33 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:33 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3cltom2y.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/cfns0lhs.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=96243', 'data', 'file=/tmp/tmpjd45me00/3cltom2y.json', 'init=/tmp/tmpjd45me00/cfns0lhs.json', 'output', 'file=/tmp/tmpjd45me00/prophet_models08n18hz/prophet_model-20260803144433.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:33 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:33 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_12_dept_20
Build prophet model for  store_12_dept_21

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wek7vltt.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/q6tfzqgw.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=49263', 'data', 'file=/tmp/tmpjd45me00/wek7vltt.json', 'init=/tmp/tmpjd45me00/q6tfzqgw.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelefo3oxj_/prophet_model-20260803144433.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:33 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:33 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dtaqu1mv.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2nocb8c2.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=69861', 'data', 'file=/tmp/tmpjd45me00/dtaqu1mv.json', 'init=/tmp/tmpjd45me00/2nocb8c2.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelank0whn7/prophet_model-20260803144433.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:33 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:33 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/sibgc3w5.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/o7evi993.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=9231', 'data', 'file=/tmp/tmpjd45me00/sibgc3w5.json', 'init=/tmp/tmpjd45me00/o7evi993.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeljzu03cxw/prophet_model-20260803144433.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:33 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_12_dept_22
Build prophet model for  store_12_dept_23

14:44:33 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ie85ymxv.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/lbtk5yvz.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=26220', 'data', 'file=/tmp/tmpjd45me00/ie85ymxv.json', 'init=/tmp/tmpjd45me00/lbtk5yvz.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelsiw3cakl/prophet_model-20260803144434.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:34 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:34 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_12_dept_24
Build prophet model for  store_12_dept_25

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8uhk_tsu.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/uw0xj4rz.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=15091', 'data', 'file=/tmp/tmpjd45me00/8uhk_tsu.json', 'init=/tmp/tmpjd45me00/uw0xj4rz.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model447gkzf6/prophet_model-20260803144434.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:34 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:34 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3xzfoure.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ncs9rkjb.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=53425', 'data', 'file=/tmp/tmpjd45me00/3xzfoure.json', 'init=/tmp/tmpjd45me00/ncs9rkjb.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model1vsgss0x/prophet_model-20260803144434.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:34 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:34 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_12_dept_26

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8p97gsxl.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dhsic6wr.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=76646', 'data', 'file=/tmp/tmpjd45me00/8p97gsxl.json', 'init=/tmp/tmpjd45me00/dhsic6wr.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelicfhl6oq/prophet_model-20260803144434.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:34 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:34 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_12_dept_27

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/d1fza2rv.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/h7r8zud4.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=25736', 'data', 'file=/tmp/tmpjd45me00/d1fza2rv.json', 'init=/tmp/tmpjd45me00/h7r8zud4.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_wsk26e2/prophet_model-20260803144435.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:35 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_12_dept_28

14:44:35 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xxnid3no.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pms4zlg8.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=39182', 'data', 'file=/tmp/tmpjd45me00/xxnid3no.json', 'init=/tmp/tmpjd45me00/pms4zlg8.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelklmxeyjo/prophet_model-20260803144435.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:35 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_12_dept_29

14:44:35 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_pi5qn5r.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/f9yn0j99.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=19552', 'data', 'file=/tmp/tmpjd45me00/_pi5qn5r.json', 'init=/tmp/tmpjd45me00/f9yn0j99.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelqpkpx2t1/prophet_model-20260803144435.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:35 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:36 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_12_dept_3
Build prophet model for  store_12_dept_30

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ex4otfh_.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6shq8di4.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=30650', 'data', 'file=/tmp/tmpjd45me00/ex4otfh_.json', 'init=/tmp/tmpjd45me00/6shq8di4.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelpoz4qqdi/prophet_model-20260803144436.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:36 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:36 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/de47u6v1.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/p4zjxtpe.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=42308', 'data', 'file=/tmp/tmpjd45me00/de47u6v1.json', 'init=/tmp/tmpjd45me00/p4zjxtpe.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelrimfp48p/prophet_model-20260803144436.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:36 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_12_dept_31

14:44:37 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qzortrqm.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qwu2fnqu.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=44483', 'data', 'file=/tmp/tmpjd45me00/qzortrqm.json', 'init=/tmp/tmpjd45me00/qwu2fnqu.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelyiiipi1x/prophet_model-20260803144437.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:37 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:37 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ypgx0vmy.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/a745mxjr.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=72672', 'data', 'file=/tmp/tmpjd45me00/ypgx0vmy.json', 'init=/tmp/tmpjd45me00/a745mxjr.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model7r2asbz0/prophet_model-20260803144437.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:37 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_12_dept_32
Build prophet model for  store_12_dept_33

14:44:37 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/myuaouc2.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mqpgbmfj.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=47518', 'data', 'file=/tmp/tmpjd45me00/myuaouc2.json', 'init=/tmp/tmpjd45me00/mqpgbmfj.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modellayyxm5u/prophet_model-20260803144437.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:37 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:37 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_12_dept_34
Build prophet model for  store_12_dept_35

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/z27vavtg.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xiw1zgrg.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=13265', 'data', 'file=/tmp/tmpjd45me00/z27vavtg.json', 'init=/tmp/tmpjd45me00/xiw1zgrg.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelj_w0oj7g/prophet_model-20260803144437.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:37 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:37 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/d1jv5fzm.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9v5c8_ns.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=1331', 'data', 'file=/tmp/tmpjd45me00/d1jv5fzm.json', 'init=/tmp/tmpjd45me00/9v5c8_ns.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeljor26ppn/prophet_model-20260803144437.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:37 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:38 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_12_dept_36

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ckzslwr3.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zlz58a4f.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=33336', 'data', 'file=/tmp/tmpjd45me00/ckzslwr3.json', 'init=/tmp/tmpjd45me00/zlz58a4f.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model5v7qvfq_/prophet_model-20260803144438.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:38 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:38 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/a6c402ko.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1vtxjprg.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=65984', 'data', 'file=/tmp/tmpjd45me00/a6c402ko.json', 'init=/tmp/tmpjd45me00/1vtxjprg.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeltowtoduu/prophet_model-20260803144438.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:38 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_12_dept_38
Build prophet model for  store_12_dept_4

14:44:38 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1y14kz88.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/nx9o6qei.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=66758', 'data', 'file=/tmp/tmpjd45me00/1y14kz88.json', 'init=/tmp/tmpjd45me00/nx9o6qei.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelrbtthkye/prophet_model-20260803144438.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:38 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:38 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_12_dept_40

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/i7d5uo50.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/31mo208w.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=93359', 'data', 'file=/tmp/tmpjd45me00/i7d5uo50.json', 'init=/tmp/tmpjd45me00/31mo208w.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelt8y4m48t/prophet_model-20260803144438.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:38 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:38 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_12_dept_41

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1rts8270.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/884mvrku.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=7339', 'data', 'file=/tmp/tmpjd45me00/1rts8270.json', 'init=/tmp/tmpjd45me00/884mvrku.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model2rla84v1/prophet_model-20260803144438.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:38 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:39 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_12_dept_42

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dlraq2de.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/l3f0mqy0.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=83336', 'data', 'file=/tmp/tmpjd45me00/dlraq2de.json', 'init=/tmp/tmpjd45me00/l3f0mqy0.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelx8yy044q/prophet_model-20260803144439.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:39 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:39 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_12_dept_44
Build prophet model for  store_12_dept_45

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zeg74gi4.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/j08fef93.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=24514', 'data', 'file=/tmp/tmpjd45me00/zeg74gi4.json', 'init=/tmp/tmpjd45me00/j08fef93.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelwl0tp0tn/prophet_model-20260803144439.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:44:39 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:40 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/y6j5ofam.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/q2dum4_j.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=77812', 'data', 'file=/tmp/tmpjd45me00/y6j5ofam.json', 'init=/tmp/tmpjd45me00/q2dum4_j.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model4id3mcst/prophet_model-20260803144440.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:40 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:40 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_12_dept_46
Build prophet model for  store_12_dept_5

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/86pcfapq.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6sdn_rej.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=66084', 'data', 'file=/tmp/tmpjd45me00/86pcfapq.json', 'init=/tmp/tmpjd45me00/6sdn_rej.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelvbxegt3z/prophet_model-20260803144441.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:41 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:41 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zc51x1de.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qfklq0ck.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=96903', 'data', 'file=/tmp/tmpjd45me00/zc51x1de.json', 'init=/tmp/tmpjd45me00/qfklq0ck.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeldictqnhj/prophet_model-20260803144441.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:41 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:41 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ibtzhuy_.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2hw7p1e2.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=87959', 'data', 'file=/tmp/tmpjd45me00/ibtzhuy_.json', 'init=/tmp/tmpjd45me00/2hw7p1e2.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelj_ydv2t2/prophet_model-20260803144441.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:41 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_12_dept_52
Build prophet model for  store_12_dept_54

14:44:41 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1hcl627h.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/h3luott2.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=7422', 'data', 'file=/tmp/tmpjd45me00/1hcl627h.json', 'init=/tmp/tmpjd45me00/h3luott2.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeln6b4dcdo/prophet_model-20260803144441.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:41 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:41 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ekw6z4ua.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/30kr_g99.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=2840', 'data', 'file=/tmp/tmpjd45me00/ekw6z4ua.json', 'init=/tmp/tmpjd45me00/30kr_g99.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelxaq3rxb1/prophet_model-20260803144441.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:41 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_12_dept_55
Build prophet model for  store_12_dept_56

14:44:41 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/r0hn5xa8.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7615src8.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=77316', 'data', 'file=/tmp/tmpjd45me00/r0hn5xa8.json', 'init=/tmp/tmpjd45me00/7615src8.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelrzcl1k8_/prophet_model-20260803144441.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:41 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:41 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_12_dept_58
Build prophet model for  store_12_dept_59

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ndf3q2le.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/h1yinvb7.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=94717', 'data', 'file=/tmp/tmpjd45me00/ndf3q2le.json', 'init=/tmp/tmpjd45me00/h1yinvb7.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelfd8whzor/prophet_model-20260803144441.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:41 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:42 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2oiseum8.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vo9llqqy.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=73149', 'data', 'file=/tmp/tmpjd45me00/2oiseum8.json', 'init=/tmp/tmpjd45me00/vo9llqqy.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_c_8fwm4/prophet_model-20260803144442.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:42 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:42 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/s68mhp60.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dvdzn37m.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=83871', 'data', 'file=/tmp/tmpjd45me00/s68mhp60.json', 'init=/tmp/tmpjd45me00/dvdzn37m.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model9pccibla/prophet_model-20260803144442.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:42 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_12_dept_6
Build prophet model for  store_12_dept_60

14:44:42 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/uv11vmvn.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/cbaqq7jy.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=35857', 'data', 'file=/tmp/tmpjd45me00/uv11vmvn.json', 'init=/tmp/tmpjd45me00/cbaqq7jy.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelusd3hpke/prophet_model-20260803144442.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:42 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:42 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/epmy974m.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vkhyr7t6.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None

Build prophet model for  store_12_dept_67
Build prophet model for  store_12_dept_7

DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=57856', 'data', 'file=/tmp/tmpjd45me00/epmy974m.json', 'init=/tmp/tmpjd45me00/vkhyr7t6.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model21tb176e/prophet_model-20260803144442.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:42 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:42 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/q6lbomcb.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gorlgm5w.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=33687', 'data', 'file=/tmp/tmpjd45me00/q6lbomcb.json', 'init=/tmp/tmpjd45me00/gorlgm5w.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelr25sptj6/prophet_model-20260803144442.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:42 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_12_dept_71

14:44:43 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/x_9q9_m0.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/n0jza54z.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=65385', 'data', 'file=/tmp/tmpjd45me00/x_9q9_m0.json', 'init=/tmp/tmpjd45me00/n0jza54z.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model2hy6ps92/prophet_model-20260803144443.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:43 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:43 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/a5rbmm4i.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zs22i2u8.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=79347', 'data', 'file=/tmp/tmpjd45me00/a5rbmm4i.json', 'init=/tmp/tmpjd45me00/zs22i2u8.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model309f0e33/prophet_model-20260803144443.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:43 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_12_dept_72
Build prophet model for  store_12_dept_74

14:44:43 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/79rifzte.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jt_6_l2k.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=91189', 'data', 'file=/tmp/tmpjd45me00/79rifzte.json', 'init=/tmp/tmpjd45me00/jt_6_l2k.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelssg1m3qa/prophet_model-20260803144443.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:43 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:43 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_12_dept_79
Build prophet model for  store_12_dept_8

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/sli_2iw2.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4pr2f0he.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=96909', 'data', 'file=/tmp/tmpjd45me00/sli_2iw2.json', 'init=/tmp/tmpjd45me00/4pr2f0he.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelvkg8o7gd/prophet_model-20260803144443.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:43 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:44 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/nnaim_fq.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/k32lumnf.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=14545', 'data', 'file=/tmp/tmpjd45me00/nnaim_fq.json', 'init=/tmp/tmpjd45me00/k32lumnf.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelvqjig4jt/prophet_model-20260803144444.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:44 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_12_dept_81

14:44:44 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dhgbpsun.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/nqyz8odi.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=14090', 'data', 'file=/tmp/tmpjd45me00/dhgbpsun.json', 'init=/tmp/tmpjd45me00/nqyz8odi.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelws1giy8i/prophet_model-20260803144444.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:44 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:44 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/yhio8c4e.json

Build prophet model for  store_12_dept_82
Build prophet model for  store_12_dept_83

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/c8pi5x2b.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=38783', 'data', 'file=/tmp/tmpjd45me00/yhio8c4e.json', 'init=/tmp/tmpjd45me00/c8pi5x2b.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model6xxcet5m/prophet_model-20260803144444.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:44 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:44 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3cle3x6m.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9tkr1jf8.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=34808', 'data', 'file=/tmp/tmpjd45me00/3cle3x6m.json', 'init=/tmp/tmpjd45me00/9tkr1jf8.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model3sq269ae/prophet_model-20260803144445.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:45 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:45 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pvhah1ca.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/s18z3w4s.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=15132', 'data', 'file=/tmp/tmpjd45me00/pvhah1ca.json', 'init=/tmp/tmpjd45me00/s18z3w4s.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelwjex3zuq/prophet_model-20260803144445.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:45 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_12_dept_85
Build prophet model for  store_12_dept_87

14:44:45 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/51q0e7ns.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/kpycg4op.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=95897', 'data', 'file=/tmp/tmpjd45me00/51q0e7ns.json', 'init=/tmp/tmpjd45me00/kpycg4op.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model4pmuchjt/prophet_model-20260803144445.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:45 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:45 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_12_dept_9
Build prophet model for  store_12_dept_90

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_4du0l9r.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/l5tqpk47.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=71122', 'data', 'file=/tmp/tmpjd45me00/_4du0l9r.json', 'init=/tmp/tmpjd45me00/l5tqpk47.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelzw21akm7/prophet_model-20260803144445.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:45 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:45 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9zixe89t.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1amaeezm.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=75937', 'data', 'file=/tmp/tmpjd45me00/9zixe89t.json', 'init=/tmp/tmpjd45me00/1amaeezm.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model8_c2yoiy/prophet_model-20260803144445.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:45 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:46 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_12_dept_91
Build prophet model for  store_12_dept_92

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qralmd9r.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/w9ii6yp4.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=38959', 'data', 'file=/tmp/tmpjd45me00/qralmd9r.json', 'init=/tmp/tmpjd45me00/w9ii6yp4.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modellriazbmv/prophet_model-20260803144446.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:46 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:46 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/tphu3odg.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6zpkt5wm.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=89208', 'data', 'file=/tmp/tmpjd45me00/tphu3odg.json', 'init=/tmp/tmpjd45me00/6zpkt5wm.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelbujtc22i/prophet_model-20260803144446.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:46 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:46 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_12_dept_93
Build prophet model for  store_12_dept_94

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wo3bbdbv.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rltkhdml.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=2246', 'data', 'file=/tmp/tmpjd45me00/wo3bbdbv.json', 'init=/tmp/tmpjd45me00/rltkhdml.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model8ahdr674/prophet_model-20260803144446.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:44:46 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:48 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2ai1fli8.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ohclseck.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=33009', 'data', 'file=/tmp/tmpjd45me00/2ai1fli8.json', 'init=/tmp/tmpjd45me00/ohclseck.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelidqu34da/prophet_model-20260803144448.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:48 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_12_dept_95

14:44:48 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/caukdgwu.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/p5jbdg8h.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=54894', 'data', 'file=/tmp/tmpjd45me00/caukdgwu.json', 'init=/tmp/tmpjd45me00/p5jbdg8h.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model8cj4x15b/prophet_model-20260803144448.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:48 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:48 - cmdstanpy - INFO - Chain [1] done processing

Build prophet model for  store_12_dept_97

INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/akwqxb0w.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/axgi9j_l.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=60036', 'data', 'file=/tmp/tmpjd45me00/akwqxb0w.json', 'init=/tmp/tmpjd45me00/axgi9j_l.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelkd21z6xa/prophet_model-20260803144449.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:49 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_12_dept_98

14:44:49 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/y1oytz_2.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3itayplc.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=20802', 'data', 'file=/tmp/tmpjd45me00/y1oytz_2.json', 'init=/tmp/tmpjd45me00/3itayplc.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeltuuli20u/prophet_model-20260803144449.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:49 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:49 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_13_dept_1

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/d3u80ypx.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/botjv5fn.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=4954', 'data', 'file=/tmp/tmpjd45me00/d3u80ypx.json', 'init=/tmp/tmpjd45me00/botjv5fn.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeljprzi2vw/prophet_model-20260803144449.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:49 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:50 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_13_dept_10

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/i_hfjpj4.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/adi6b37l.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=82902', 'data', 'file=/tmp/tmpjd45me00/i_hfjpj4.json', 'init=/tmp/tmpjd45me00/adi6b37l.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modellbq_s23f/prophet_model-20260803144450.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:50 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_13_dept_11

14:44:50 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/l3stqve6.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8z5d7a9g.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=39823', 'data', 'file=/tmp/tmpjd45me00/l3stqve6.json', 'init=/tmp/tmpjd45me00/8z5d7a9g.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model4hayv7jm/prophet_model-20260803144450.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:50 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:50 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_13_dept_12
Build prophet model for  store_13_dept_13

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/iwt23pr2.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/e0wckp7u.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=91335', 'data', 'file=/tmp/tmpjd45me00/iwt23pr2.json', 'init=/tmp/tmpjd45me00/e0wckp7u.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelsby8ly51/prophet_model-20260803144450.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:50 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:50 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/c7xwbbig.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mzommeql.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=4329', 'data', 'file=/tmp/tmpjd45me00/c7xwbbig.json', 'init=/tmp/tmpjd45me00/mzommeql.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelcqdg915v/prophet_model-20260803144450.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:50 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:50 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/btx1cfbu.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/e8qs1m1y.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=12803', 'data', 'file=/tmp/tmpjd45me00/btx1cfbu.json', 'init=/tmp/tmpjd45me00/e8qs1m1y.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelg7klgvj8/prophet_model-20260803144451.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:51 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_13_dept_14
Build prophet model for  store_13_dept_16

14:44:51 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jszxa6d7.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/45pch982.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=85395', 'data', 'file=/tmp/tmpjd45me00/jszxa6d7.json', 'init=/tmp/tmpjd45me00/45pch982.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeljxpsf4so/prophet_model-20260803144451.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:51 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:51 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hme4oue2.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_l1o7585.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=39801', 'data', 'file=/tmp/tmpjd45me00/hme4oue2.json', 'init=/tmp/tmpjd45me00/_l1o7585.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model8vxu6401/prophet_model-20260803144451.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:51 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_13_dept_17
Build prophet model for  store_13_dept_18

14:44:51 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gpox0miw.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/owkz2cme.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=36623', 'data', 'file=/tmp/tmpjd45me00/gpox0miw.json', 'init=/tmp/tmpjd45me00/owkz2cme.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelrzp4gqkw/prophet_model-20260803144451.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:51 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_13_dept_19

14:44:52 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/sc1ui_2s.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4zxnxw1o.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=54936', 'data', 'file=/tmp/tmpjd45me00/sc1ui_2s.json', 'init=/tmp/tmpjd45me00/4zxnxw1o.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelfik1ry8f/prophet_model-20260803144452.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:52 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_13_dept_2

14:44:52 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6bpnl5uj.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zmjup4td.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=15860', 'data', 'file=/tmp/tmpjd45me00/6bpnl5uj.json', 'init=/tmp/tmpjd45me00/zmjup4td.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelydvyzglw/prophet_model-20260803144452.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:52 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:52 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_13_dept_20
Build prophet model for  store_13_dept_21

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/uloa1y_x.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/r04bq8yq.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=87705', 'data', 'file=/tmp/tmpjd45me00/uloa1y_x.json', 'init=/tmp/tmpjd45me00/r04bq8yq.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelf792515q/prophet_model-20260803144452.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:52 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:52 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pk3_7sg4.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bkjvsdzv.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=47725', 'data', 'file=/tmp/tmpjd45me00/pk3_7sg4.json', 'init=/tmp/tmpjd45me00/bkjvsdzv.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeloq9zeuz8/prophet_model-20260803144453.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:53 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:53 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/nk53i95b.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wxfxhgjh.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=42027', 'data', 'file=/tmp/tmpjd45me00/nk53i95b.json', 'init=/tmp/tmpjd45me00/wxfxhgjh.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelbvhxqgk9/prophet_model-20260803144453.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:53 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_13_dept_22
Build prophet model for  store_13_dept_23

14:44:53 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vkwyypcg.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3smff_kq.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=77116', 'data', 'file=/tmp/tmpjd45me00/vkwyypcg.json', 'init=/tmp/tmpjd45me00/3smff_kq.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model7yo9rr4t/prophet_model-20260803144453.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:53 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:53 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/srx4xv1p.json

Build prophet model for  store_13_dept_24
Build prophet model for  store_13_dept_25

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/icx9ulct.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=500', 'data', 'file=/tmp/tmpjd45me00/srx4xv1p.json', 'init=/tmp/tmpjd45me00/icx9ulct.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelc_7j584_/prophet_model-20260803144453.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:53 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:53 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/u1kyadyo.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jmbi3wkm.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=87718', 'data', 'file=/tmp/tmpjd45me00/u1kyadyo.json', 'init=/tmp/tmpjd45me00/jmbi3wkm.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model6zbk2kc6/prophet_model-20260803144453.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:53 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:53 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dutajvq6.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5ba2eh1i.json

Build prophet model for  store_13_dept_26
Build prophet model for  store_13_dept_27

DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=55863', 'data', 'file=/tmp/tmpjd45me00/dutajvq6.json', 'init=/tmp/tmpjd45me00/5ba2eh1i.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelihe34_w0/prophet_model-20260803144453.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:53 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:53 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gyfwatev.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/s2rkqzol.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=61965', 'data', 'file=/tmp/tmpjd45me00/gyfwatev.json', 'init=/tmp/tmpjd45me00/s2rkqzol.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeldq0wg22j/prophet_model-20260803144454.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:54 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:54 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2q000bh9.json

Build prophet model for  store_13_dept_28
Build prophet model for  store_13_dept_29

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/40tiyrgt.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=62745', 'data', 'file=/tmp/tmpjd45me00/2q000bh9.json', 'init=/tmp/tmpjd45me00/40tiyrgt.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelg3in_zc2/prophet_model-20260803144454.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:54 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:54 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pun5wo4d.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/tkvczv9p.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=10587', 'data', 'file=/tmp/tmpjd45me00/pun5wo4d.json', 'init=/tmp/tmpjd45me00/tkvczv9p.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeldy_xns8_/prophet_model-20260803144454.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:54 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:54 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jufpvk4z.json

Build prophet model for  store_13_dept_3
Build prophet model for  store_13_dept_30

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hm9st8_n.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=1711', 'data', 'file=/tmp/tmpjd45me00/jufpvk4z.json', 'init=/tmp/tmpjd45me00/hm9st8_n.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelwrpqwkbg/prophet_model-20260803144454.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:54 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:54 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/aex5nfny.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6s2ji9bi.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=22160', 'data', 'file=/tmp/tmpjd45me00/aex5nfny.json', 'init=/tmp/tmpjd45me00/6s2ji9bi.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelfkewcjhn/prophet_model-20260803144454.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:54 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:54 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7dyvo14w.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/o7an1c7h.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=80286', 'data', 'file=/tmp/tmpjd45me00/7dyvo14w.json', 'init=/tmp/tmpjd45me00/o7an1c7h.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeli0q0z50c/prophet_model-20260803144455.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:55 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_13_dept_31
Build prophet model for  store_13_dept_32

14:44:55 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4q3exj7v.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2qwcl8l9.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=53573', 'data', 'file=/tmp/tmpjd45me00/4q3exj7v.json', 'init=/tmp/tmpjd45me00/2qwcl8l9.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelebkizipp/prophet_model-20260803144455.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:55 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:55 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/eojqfchq.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jvbr8ch3.json

Build prophet model for  store_13_dept_33
Build prophet model for  store_13_dept_34

DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=5018', 'data', 'file=/tmp/tmpjd45me00/eojqfchq.json', 'init=/tmp/tmpjd45me00/jvbr8ch3.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelsuao9vnc/prophet_model-20260803144455.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:55 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:55 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5_zrtw80.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/15hkij22.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=66299', 'data', 'file=/tmp/tmpjd45me00/5_zrtw80.json', 'init=/tmp/tmpjd45me00/15hkij22.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model1cwe_ttx/prophet_model-20260803144455.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:55 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:55 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_13_dept_35
Build prophet model for  store_13_dept_36

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/f7l1fvlf.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2c3kozvl.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=72190', 'data', 'file=/tmp/tmpjd45me00/f7l1fvlf.json', 'init=/tmp/tmpjd45me00/2c3kozvl.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelrhnggt29/prophet_model-20260803144455.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:55 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:56 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/s0r2nnj3.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/k9dpxgau.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=58873', 'data', 'file=/tmp/tmpjd45me00/s0r2nnj3.json', 'init=/tmp/tmpjd45me00/k9dpxgau.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelnhr73fhs/prophet_model-20260803144456.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:56 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:56 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_13_dept_37
Build prophet model for  store_13_dept_38

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hq4_gob8.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/d3x5g3z_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=83181', 'data', 'file=/tmp/tmpjd45me00/hq4_gob8.json', 'init=/tmp/tmpjd45me00/d3x5g3z_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model692nwafd/prophet_model-20260803144456.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:56 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:56 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/t8t3olur.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/likvyxwi.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=91288', 'data', 'file=/tmp/tmpjd45me00/t8t3olur.json', 'init=/tmp/tmpjd45me00/likvyxwi.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelp5qotlal/prophet_model-20260803144456.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:56 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:56 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/sa3e5um9.json

Build prophet model for  store_13_dept_4
Build prophet model for  store_13_dept_40

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mis_wssu.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=65914', 'data', 'file=/tmp/tmpjd45me00/sa3e5um9.json', 'init=/tmp/tmpjd45me00/mis_wssu.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeltzw8a3do/prophet_model-20260803144456.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:56 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:56 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ym5atukg.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/kashvyg7.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=17860', 'data', 'file=/tmp/tmpjd45me00/ym5atukg.json', 'init=/tmp/tmpjd45me00/kashvyg7.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeltdmf0x0l/prophet_model-20260803144456.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:56 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_13_dept_41

14:44:57 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/olw9flwl.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/l6xb_9h8.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=24302', 'data', 'file=/tmp/tmpjd45me00/olw9flwl.json', 'init=/tmp/tmpjd45me00/l6xb_9h8.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeli7576a72/prophet_model-20260803144457.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:57 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:57 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/v2ftfvyg.json

Build prophet model for  store_13_dept_42
Build prophet model for  store_13_dept_44

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/scn8ykne.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=74251', 'data', 'file=/tmp/tmpjd45me00/v2ftfvyg.json', 'init=/tmp/tmpjd45me00/scn8ykne.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelqviu7pby/prophet_model-20260803144457.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:57 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:57 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/26pgognq.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ywent9yc.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=8901', 'data', 'file=/tmp/tmpjd45me00/26pgognq.json', 'init=/tmp/tmpjd45me00/ywent9yc.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeljg2ozlal/prophet_model-20260803144457.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:44:57 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_13_dept_45

14:44:59 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/haxu3kdj.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gb7ufw8l.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=46029', 'data', 'file=/tmp/tmpjd45me00/haxu3kdj.json', 'init=/tmp/tmpjd45me00/gb7ufw8l.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modellutli14s/prophet_model-20260803144459.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:59 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:59 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/yhnmiwbx.json

Build prophet model for  store_13_dept_46
Build prophet model for  store_13_dept_48

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xtmf4ok9.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=33455', 'data', 'file=/tmp/tmpjd45me00/yhnmiwbx.json', 'init=/tmp/tmpjd45me00/xtmf4ok9.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model1cu66bxb/prophet_model-20260803144459.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:59 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:59 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wdjjskgv.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5fy1d7b0.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=12224', 'data', 'file=/tmp/tmpjd45me00/wdjjskgv.json', 'init=/tmp/tmpjd45me00/5fy1d7b0.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelr6ujnvx5/prophet_model-20260803144459.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:59 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:59 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_13_dept_49
Build prophet model for  store_13_dept_5

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2ygvr76o.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ws4cvozo.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=54919', 'data', 'file=/tmp/tmpjd45me00/2ygvr76o.json', 'init=/tmp/tmpjd45me00/ws4cvozo.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelcctjnxf9/prophet_model-20260803144459.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:59 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:59 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mkhosf1f.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6jf6xodz.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=21048', 'data', 'file=/tmp/tmpjd45me00/mkhosf1f.json', 'init=/tmp/tmpjd45me00/6jf6xodz.json', 'output', 'file=/tmp/tmpjd45me00/prophet_models2jstuf6/prophet_model-20260803144459.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:44:59 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:44:59 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_13_dept_50
Build prophet model for  store_13_dept_51
Skip  store_13_dept_51 due to lack of data
Build prophet model for  store_13_dept_52

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ny46yp5c.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dp_sx4m9.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=77836', 'data', 'file=/tmp/tmpjd45me00/ny46yp5c.json', 'init=/tmp/tmpjd45me00/dp_sx4m9.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modell67g50vr/prophet_model-20260803144500.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:00 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:00 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6ef69n2c.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7ouco7yh.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=29984', 'data', 'file=/tmp/tmpjd45me00/6ef69n2c.json', 'init=/tmp/tmpjd45me00/7ouco7yh.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelleoatnmi/prophet_model-20260803144500.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:00 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:00 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_13_dept_54
Build prophet model for  store_13_dept_55

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/t64xe_fo.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ga81b39o.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=61538', 'data', 'file=/tmp/tmpjd45me00/t64xe_fo.json', 'init=/tmp/tmpjd45me00/ga81b39o.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelzog158im/prophet_model-20260803144500.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:00 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:00 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/cp2d4j4c.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/yeprtb0i.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=37835', 'data', 'file=/tmp/tmpjd45me00/cp2d4j4c.json', 'init=/tmp/tmpjd45me00/yeprtb0i.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelkke74p0r/prophet_model-20260803144500.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:00 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_13_dept_56

14:45:00 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_h1qz02a.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ihq9asbs.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=60497', 'data', 'file=/tmp/tmpjd45me00/_h1qz02a.json', 'init=/tmp/tmpjd45me00/ihq9asbs.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelb_6c4rvv/prophet_model-20260803144501.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:01 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:01 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_13_dept_58

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vxe66_f9.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/44dnqk1x.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=2092', 'data', 'file=/tmp/tmpjd45me00/vxe66_f9.json', 'init=/tmp/tmpjd45me00/44dnqk1x.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelhvp6xkyn/prophet_model-20260803144501.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:01 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_13_dept_59

14:45:01 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5eb3vt45.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9wbzf0jb.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=68105', 'data', 'file=/tmp/tmpjd45me00/5eb3vt45.json', 'init=/tmp/tmpjd45me00/9wbzf0jb.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model1b55v123/prophet_model-20260803144502.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:02 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:02 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_13_dept_6

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/v0tmx4u4.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2zbou59j.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=57567', 'data', 'file=/tmp/tmpjd45me00/v0tmx4u4.json', 'init=/tmp/tmpjd45me00/2zbou59j.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeltdc5bf9i/prophet_model-20260803144502.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:02 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:02 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_13_dept_60
Build prophet model for  store_13_dept_67

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gbux8i2m.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/m2k8tv5b.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=24304', 'data', 'file=/tmp/tmpjd45me00/gbux8i2m.json', 'init=/tmp/tmpjd45me00/m2k8tv5b.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeloinuhhjs/prophet_model-20260803144502.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:02 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:02 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dkfbqhgh.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/69gloedm.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=97006', 'data', 'file=/tmp/tmpjd45me00/dkfbqhgh.json', 'init=/tmp/tmpjd45me00/69gloedm.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model9_e76msk/prophet_model-20260803144502.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:02 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:02 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_13_dept_7

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ogxaq8p5.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/g_ot7q1v.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=61869', 'data', 'file=/tmp/tmpjd45me00/ogxaq8p5.json', 'init=/tmp/tmpjd45me00/g_ot7q1v.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelrtc4bv8_/prophet_model-20260803144503.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:03 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:03 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_13_dept_71
Build prophet model for  store_13_dept_72

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qtrbjz5h.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zasz449e.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=41086', 'data', 'file=/tmp/tmpjd45me00/qtrbjz5h.json', 'init=/tmp/tmpjd45me00/zasz449e.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modell7wpg667/prophet_model-20260803144503.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:03 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:03 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/582kk9e3.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/b3n1rq95.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=57380', 'data', 'file=/tmp/tmpjd45me00/582kk9e3.json', 'init=/tmp/tmpjd45me00/b3n1rq95.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeljxuc5493/prophet_model-20260803144503.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:03 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:03 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_13_dept_74

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/i33c27y7.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fg1n2nxb.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=55738', 'data', 'file=/tmp/tmpjd45me00/i33c27y7.json', 'init=/tmp/tmpjd45me00/fg1n2nxb.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelbp69lfzl/prophet_model-20260803144503.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:03 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:03 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_13_dept_79
Build prophet model for  store_13_dept_8

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/w6b90d7o.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/b7kktiun.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=40104', 'data', 'file=/tmp/tmpjd45me00/w6b90d7o.json', 'init=/tmp/tmpjd45me00/b7kktiun.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model5hie1cc2/prophet_model-20260803144504.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:04 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:04 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/h6onniy4.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/00fmegs4.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=79257', 'data', 'file=/tmp/tmpjd45me00/h6onniy4.json', 'init=/tmp/tmpjd45me00/00fmegs4.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model2nzgfkbu/prophet_model-20260803144504.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:04 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:04 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ft7tiddw.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/a9fx8qi3.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=29754', 'data', 'file=/tmp/tmpjd45me00/ft7tiddw.json', 'init=/tmp/tmpjd45me00/a9fx8qi3.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelgvn56bz1/prophet_model-20260803144504.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:04 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_13_dept_80
Build prophet model for  store_13_dept_81

14:45:04 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/q1yh1bvr.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/i9uibogi.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=68360', 'data', 'file=/tmp/tmpjd45me00/q1yh1bvr.json', 'init=/tmp/tmpjd45me00/i9uibogi.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelhz1us8wl/prophet_model-20260803144504.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:04 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:04 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vj3jyf2q.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xyql1udt.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=82883', 'data', 'file=/tmp/tmpjd45me00/vj3jyf2q.json', 'init=/tmp/tmpjd45me00/xyql1udt.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model17jv_012/prophet_model-20260803144504.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:04 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_13_dept_82
Build prophet model for  store_13_dept_83

14:45:04 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1up0554i.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/leujkfo5.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=79773', 'data', 'file=/tmp/tmpjd45me00/1up0554i.json', 'init=/tmp/tmpjd45me00/leujkfo5.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelhzb6m9dj/prophet_model-20260803144504.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:04 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_13_dept_85

14:45:05 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/yxw_yecu.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ymb23o5b.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=61427', 'data', 'file=/tmp/tmpjd45me00/yxw_yecu.json', 'init=/tmp/tmpjd45me00/ymb23o5b.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model81zyldl9/prophet_model-20260803144505.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:05 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:05 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_13_dept_87
Build prophet model for  store_13_dept_9

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/45q7po70.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/10u_hc3w.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=23981', 'data', 'file=/tmp/tmpjd45me00/45q7po70.json', 'init=/tmp/tmpjd45me00/10u_hc3w.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modellhpu0dsp/prophet_model-20260803144505.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:05 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:05 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/uuxezc9z.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/srbniztc.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=28856', 'data', 'file=/tmp/tmpjd45me00/uuxezc9z.json', 'init=/tmp/tmpjd45me00/srbniztc.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeloq5i9gym/prophet_model-20260803144505.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:05 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:05 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_13_dept_90
Build prophet model for  store_13_dept_91

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4sfm_ixc.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rh13vy42.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=30514', 'data', 'file=/tmp/tmpjd45me00/4sfm_ixc.json', 'init=/tmp/tmpjd45me00/rh13vy42.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelz989u6er/prophet_model-20260803144506.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:06 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:06 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_13_dept_92
Build prophet model for  store_13_dept_93

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dti4mcbm.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/uv2h8bln.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=46874', 'data', 'file=/tmp/tmpjd45me00/dti4mcbm.json', 'init=/tmp/tmpjd45me00/uv2h8bln.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelv9680eig/prophet_model-20260803144506.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:06 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:06 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_13_dept_94
Build prophet model for  store_13_dept_95

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qiendfjr.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/13ahl1t9.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=444', 'data', 'file=/tmp/tmpjd45me00/qiendfjr.json', 'init=/tmp/tmpjd45me00/13ahl1t9.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model8jffen7d/prophet_model-20260803144506.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:06 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:06 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_13_dept_96
Build prophet model for  store_13_dept_97

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4a0n0mf2.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/d27ad5hx.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=1304', 'data', 'file=/tmp/tmpjd45me00/4a0n0mf2.json', 'init=/tmp/tmpjd45me00/d27ad5hx.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model1b1m7anj/prophet_model-20260803144506.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:06 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:06 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/d_62ul5v.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1dg4cr9x.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=18980', 'data', 'file=/tmp/tmpjd45me00/d_62ul5v.json', 'init=/tmp/tmpjd45me00/1dg4cr9x.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelmn2jhlu0/prophet_model-20260803144506.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:06 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:06 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/o4mxprfn.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pzyo68x6.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=20176', 'data', 'file=/tmp/tmpjd45me00/o4mxprfn.json', 'init=/tmp/tmpjd45me00/pzyo68x6.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelhjulcs28/prophet_model-20260803144506.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:07 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_13_dept_98
Build prophet model for  store_14_dept_1

14:45:07 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/36eosj2w.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/lod3gc_i.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=85376', 'data', 'file=/tmp/tmpjd45me00/36eosj2w.json', 'init=/tmp/tmpjd45me00/lod3gc_i.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model18cw0jjc/prophet_model-20260803144507.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:07 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_14_dept_10

14:45:07 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/j1spd58n.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7wywrg3a.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=96396', 'data', 'file=/tmp/tmpjd45me00/j1spd58n.json', 'init=/tmp/tmpjd45me00/7wywrg3a.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelzmt080e2/prophet_model-20260803144507.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:07 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:07 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/s303t0dr.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zz1wqftr.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=83750', 'data', 'file=/tmp/tmpjd45me00/s303t0dr.json', 'init=/tmp/tmpjd45me00/zz1wqftr.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelcw1fs024/prophet_model-20260803144507.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:07 - cmdstanpy - INFO - Chain [1] start processing

Build prophet model for  store_14_dept_11
Build prophet model for  store_14_dept_12

INFO:cmdstanpy:Chain [1] start processing
14:45:07 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/i_3uti2x.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ghj4md_x.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=17050', 'data', 'file=/tmp/tmpjd45me00/i_3uti2x.json', 'init=/tmp/tmpjd45me00/ghj4md_x.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelfk6gd90m/prophet_model-20260803144507.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:07 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_14_dept_13

14:45:08 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xy2gxgt8.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/k43pdala.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=62753', 'data', 'file=/tmp/tmpjd45me00/xy2gxgt8.json', 'init=/tmp/tmpjd45me00/k43pdala.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model8dx_fqx9/prophet_model-20260803144508.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:08 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_14_dept_14

14:45:08 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/a71ujrx9.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1503adlp.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=37842', 'data', 'file=/tmp/tmpjd45me00/a71ujrx9.json', 'init=/tmp/tmpjd45me00/1503adlp.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelnufiapit/prophet_model-20260803144508.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:08 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:08 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_14_dept_16
Build prophet model for  store_14_dept_17

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/m2ev1xee.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/91gthssm.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=82346', 'data', 'file=/tmp/tmpjd45me00/m2ev1xee.json', 'init=/tmp/tmpjd45me00/91gthssm.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelph96io50/prophet_model-20260803144508.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:08 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:08 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/eavjpol2.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ji2z3_7a.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=13018', 'data', 'file=/tmp/tmpjd45me00/eavjpol2.json', 'init=/tmp/tmpjd45me00/ji2z3_7a.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelf7yb_8pg/prophet_model-20260803144508.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:08 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:08 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/nb7muig5.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/h8ygci3r.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=30225', 'data', 'file=/tmp/tmpjd45me00/nb7muig5.json', 'init=/tmp/tmpjd45me00/h8ygci3r.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelxvauj4v6/prophet_model-20260803144509.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:09 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_14_dept_18
Build prophet model for  store_14_dept_19

14:45:09 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/s5j8xjvo.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fxj1l_f9.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=72607', 'data', 'file=/tmp/tmpjd45me00/s5j8xjvo.json', 'init=/tmp/tmpjd45me00/fxj1l_f9.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelyw51cbw3/prophet_model-20260803144509.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:09 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:09 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_14_dept_2
Build prophet model for  store_14_dept_20

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/745jjljh.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/84vcpzk8.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=36002', 'data', 'file=/tmp/tmpjd45me00/745jjljh.json', 'init=/tmp/tmpjd45me00/84vcpzk8.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelsjr7e7la/prophet_model-20260803144509.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:09 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:09 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/sp9uvdh5.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/49letq86.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=72608', 'data', 'file=/tmp/tmpjd45me00/sp9uvdh5.json', 'init=/tmp/tmpjd45me00/49letq86.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelah_mmfse/prophet_model-20260803144509.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:09 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:09 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_14_dept_21
Build prophet model for  store_14_dept_22

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8b5sxk6u.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_jpvu_5k.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=77163', 'data', 'file=/tmp/tmpjd45me00/8b5sxk6u.json', 'init=/tmp/tmpjd45me00/_jpvu_5k.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelait_twgt/prophet_model-20260803144509.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:09 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:09 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fzwvqhyz.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/l6vpj77m.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=11143', 'data', 'file=/tmp/tmpjd45me00/fzwvqhyz.json', 'init=/tmp/tmpjd45me00/l6vpj77m.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelmpo_sg4m/prophet_model-20260803144510.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:10 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:10 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9fbcrwn0.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/likgursd.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=64986', 'data', 'file=/tmp/tmpjd45me00/9fbcrwn0.json', 'init=/tmp/tmpjd45me00/likgursd.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelq0bl2q6v/prophet_model-20260803144510.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:10 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_14_dept_23
Build prophet model for  store_14_dept_24

14:45:10 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2hbjys50.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pd3n667u.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=26149', 'data', 'file=/tmp/tmpjd45me00/2hbjys50.json', 'init=/tmp/tmpjd45me00/pd3n667u.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelpyx7a8e5/prophet_model-20260803144510.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:10 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_14_dept_25

14:45:10 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ovo3cder.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1gf15wr7.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=16785', 'data', 'file=/tmp/tmpjd45me00/ovo3cder.json', 'init=/tmp/tmpjd45me00/1gf15wr7.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelkhz3t336/prophet_model-20260803144510.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:10 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:10 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_14_dept_26
Build prophet model for  store_14_dept_27

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/66z4dv3b.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ya2imlw3.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=55361', 'data', 'file=/tmp/tmpjd45me00/66z4dv3b.json', 'init=/tmp/tmpjd45me00/ya2imlw3.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelphh2gdyb/prophet_model-20260803144510.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:10 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:10 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fo94cy_i.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vp7x_9mq.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=85191', 'data', 'file=/tmp/tmpjd45me00/fo94cy_i.json', 'init=/tmp/tmpjd45me00/vp7x_9mq.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelurcq3dyx/prophet_model-20260803144511.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:11 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:11 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4lh2l4bg.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/poxbq47w.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=66190', 'data', 'file=/tmp/tmpjd45me00/4lh2l4bg.json', 'init=/tmp/tmpjd45me00/poxbq47w.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model7gaeeo64/prophet_model-20260803144511.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:11 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_14_dept_28
Build prophet model for  store_14_dept_29

14:45:11 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jiiqnz38.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/l50c8t5_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=85549', 'data', 'file=/tmp/tmpjd45me00/jiiqnz38.json', 'init=/tmp/tmpjd45me00/l50c8t5_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelrar35pkz/prophet_model-20260803144511.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:11 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:11 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_14_dept_3

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/i_d90d1b.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/r7o5h0zh.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=16724', 'data', 'file=/tmp/tmpjd45me00/i_d90d1b.json', 'init=/tmp/tmpjd45me00/r7o5h0zh.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelbpr27fsr/prophet_model-20260803144511.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:11 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:11 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_14_dept_30
Build prophet model for  store_14_dept_31

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rc1oqj11.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/p54kawk7.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=92485', 'data', 'file=/tmp/tmpjd45me00/rc1oqj11.json', 'init=/tmp/tmpjd45me00/p54kawk7.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelus_zy57y/prophet_model-20260803144511.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:11 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:11 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/37end9fm.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3j7ogc2z.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=61661', 'data', 'file=/tmp/tmpjd45me00/37end9fm.json', 'init=/tmp/tmpjd45me00/3j7ogc2z.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model4lqn8xli/prophet_model-20260803144512.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:12 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:12 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ekzjj_y4.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4ejsb3ue.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=46365', 'data', 'file=/tmp/tmpjd45me00/ekzjj_y4.json', 'init=/tmp/tmpjd45me00/4ejsb3ue.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeld23jknet/prophet_model-20260803144512.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:12 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_14_dept_32
Build prophet model for  store_14_dept_33

14:45:12 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8m3087a6.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rytaj1s8.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=8951', 'data', 'file=/tmp/tmpjd45me00/8m3087a6.json', 'init=/tmp/tmpjd45me00/rytaj1s8.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model4vv70eu7/prophet_model-20260803144512.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:12 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:12 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rsytp45u.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mnqmhfyt.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=26651', 'data', 'file=/tmp/tmpjd45me00/rsytp45u.json', 'init=/tmp/tmpjd45me00/mnqmhfyt.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelkbqorw2q/prophet_model-20260803144512.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:12 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_14_dept_34
Build prophet model for  store_14_dept_35

14:45:12 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/i_x63rfi.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_2s8xvn_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=14819', 'data', 'file=/tmp/tmpjd45me00/i_x63rfi.json', 'init=/tmp/tmpjd45me00/_2s8xvn_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model0sw33tqu/prophet_model-20260803144512.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:12 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:12 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fqe7oo98.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ou_3b3gj.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=10213', 'data', 'file=/tmp/tmpjd45me00/fqe7oo98.json', 'init=/tmp/tmpjd45me00/ou_3b3gj.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelphpkdlup/prophet_model-20260803144512.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:12 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_14_dept_36
Build prophet model for  store_14_dept_38

14:45:13 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bpwbhc6n.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qbv7sm3y.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=80464', 'data', 'file=/tmp/tmpjd45me00/bpwbhc6n.json', 'init=/tmp/tmpjd45me00/qbv7sm3y.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelh4_gb947/prophet_model-20260803144513.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:13 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:13 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_14_dept_4
Build prophet model for  store_14_dept_40

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/quppb1qp.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jy6kniwd.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=67470', 'data', 'file=/tmp/tmpjd45me00/quppb1qp.json', 'init=/tmp/tmpjd45me00/jy6kniwd.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modele6u22_sf/prophet_model-20260803144513.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:13 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:13 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4g7sheor.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ur9ch56f.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=83650', 'data', 'file=/tmp/tmpjd45me00/4g7sheor.json', 'init=/tmp/tmpjd45me00/ur9ch56f.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelaqpt4qul/prophet_model-20260803144514.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:14 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_14_dept_41

14:45:14 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/47uv8yr7.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_f9pz2ed.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=36868', 'data', 'file=/tmp/tmpjd45me00/47uv8yr7.json', 'init=/tmp/tmpjd45me00/_f9pz2ed.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modele2tavuiw/prophet_model-20260803144514.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:14 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_14_dept_42

14:45:14 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/oodhqkgv.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7fc37f6t.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=33764', 'data', 'file=/tmp/tmpjd45me00/oodhqkgv.json', 'init=/tmp/tmpjd45me00/7fc37f6t.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelsplhj7e7/prophet_model-20260803144515.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:15 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:15 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_14_dept_44

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gjw7vy86.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/al8dwxup.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=988', 'data', 'file=/tmp/tmpjd45me00/gjw7vy86.json', 'init=/tmp/tmpjd45me00/al8dwxup.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelg1d567np/prophet_model-20260803144515.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:15 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_14_dept_45
Skip  store_14_dept_45 due to lack of data
Build prophet model for  store_14_dept_46

14:45:15 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ktr69p42.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8e6o63__.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=25409', 'data', 'file=/tmp/tmpjd45me00/ktr69p42.json', 'init=/tmp/tmpjd45me00/8e6o63__.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model9hjwt2lx/prophet_model-20260803144515.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:15 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_14_dept_49

14:45:15 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3iswl0rq.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/cqc2dyz2.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=16774', 'data', 'file=/tmp/tmpjd45me00/3iswl0rq.json', 'init=/tmp/tmpjd45me00/cqc2dyz2.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeli7xj6uiz/prophet_model-20260803144516.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:16 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:16 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_14_dept_5

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7ia4uwt0.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/22u59o6i.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=37218', 'data', 'file=/tmp/tmpjd45me00/7ia4uwt0.json', 'init=/tmp/tmpjd45me00/22u59o6i.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelzpgkf9qj/prophet_model-20260803144516.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:16 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:16 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_14_dept_50
Build prophet model for  store_14_dept_51

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wu4po8ht.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4783r0yh.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=89324', 'data', 'file=/tmp/tmpjd45me00/wu4po8ht.json', 'init=/tmp/tmpjd45me00/4783r0yh.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model48cw7yrk/prophet_model-20260803144516.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:45:16 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:18 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/w6dc70z2.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/q8cxn0au.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=59473', 'data', 'file=/tmp/tmpjd45me00/w6dc70z2.json', 'init=/tmp/tmpjd45me00/q8cxn0au.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelcxo0s1mp/prophet_model-20260803144518.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:18 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:18 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/sojmcjcf.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/c02aml6e.json
DEBUG:cmdstanpy:idx 0

Build prophet model for  store_14_dept_52
Build prophet model for  store_14_dept_54

DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=32720', 'data', 'file=/tmp/tmpjd45me00/sojmcjcf.json', 'init=/tmp/tmpjd45me00/c02aml6e.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelmo12ym4o/prophet_model-20260803144518.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:18 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:18 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9_8tnfds.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/m2c0rq62.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=75771', 'data', 'file=/tmp/tmpjd45me00/9_8tnfds.json', 'init=/tmp/tmpjd45me00/m2c0rq62.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelvnlyl5qt/prophet_model-20260803144518.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:18 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:18 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2zfrsp5g.json

Build prophet model for  store_14_dept_55
Build prophet model for  store_14_dept_56

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/o79jtewh.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=81137', 'data', 'file=/tmp/tmpjd45me00/2zfrsp5g.json', 'init=/tmp/tmpjd45me00/o79jtewh.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model5l89oe9_/prophet_model-20260803144518.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:18 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:18 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/l1r0ax28.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gra2c4tr.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=81376', 'data', 'file=/tmp/tmpjd45me00/l1r0ax28.json', 'init=/tmp/tmpjd45me00/gra2c4tr.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelr2ep737j/prophet_model-20260803144518.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:18 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:18 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/stq_j55v.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/eezl52db.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=33698', 'data', 'file=/tmp/tmpjd45me00/stq_j55v.json', 'init=/tmp/tmpjd45me00/eezl52db.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeln5i27ai9/prophet_model-20260803144518.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:18 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_14_dept_58
Build prophet model for  store_14_dept_59

14:45:19 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/v1nukwj4.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mhe6ktyc.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=86234', 'data', 'file=/tmp/tmpjd45me00/v1nukwj4.json', 'init=/tmp/tmpjd45me00/mhe6ktyc.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelwamwf3en/prophet_model-20260803144519.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:19 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:19 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zzo116d1.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/il2ktdtt.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=62696', 'data', 'file=/tmp/tmpjd45me00/zzo116d1.json', 'init=/tmp/tmpjd45me00/il2ktdtt.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model5lvbuusp/prophet_model-20260803144519.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:19 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_14_dept_6
Build prophet model for  store_14_dept_60

14:45:19 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/i5r8oxv2.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/24ld35fo.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=73175', 'data', 'file=/tmp/tmpjd45me00/i5r8oxv2.json', 'init=/tmp/tmpjd45me00/24ld35fo.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeln59y2_9y/prophet_model-20260803144519.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:19 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:19 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ep8a1f_8.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5hp751yr.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=6471', 'data', 'file=/tmp/tmpjd45me00/ep8a1f_8.json', 'init=/tmp/tmpjd45me00/5hp751yr.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelc7ffldea/prophet_model-20260803144519.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:19 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_14_dept_67
Build prophet model for  store_14_dept_7

14:45:19 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ayzy4ray.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/t0mr4rpp.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=39859', 'data', 'file=/tmp/tmpjd45me00/ayzy4ray.json', 'init=/tmp/tmpjd45me00/t0mr4rpp.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelp4sz2ltj/prophet_model-20260803144519.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:19 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:20 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/te33wjbo.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/yh6cojuy.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=81682', 'data', 'file=/tmp/tmpjd45me00/te33wjbo.json', 'init=/tmp/tmpjd45me00/yh6cojuy.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelg2yx7b15/prophet_model-20260803144520.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:20 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_14_dept_71
Build prophet model for  store_14_dept_72

14:45:20 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/f2u6bxc4.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_o5sit0f.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=55800', 'data', 'file=/tmp/tmpjd45me00/f2u6bxc4.json', 'init=/tmp/tmpjd45me00/_o5sit0f.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model985rciw1/prophet_model-20260803144520.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:20 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:20 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/moin3slb.json

Build prophet model for  store_14_dept_74
Build prophet model for  store_14_dept_79

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vk191p38.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=67219', 'data', 'file=/tmp/tmpjd45me00/moin3slb.json', 'init=/tmp/tmpjd45me00/vk191p38.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model6by1uvqa/prophet_model-20260803144520.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:20 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:20 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/yfyhf5ic.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/twdrrp3d.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=62637', 'data', 'file=/tmp/tmpjd45me00/yfyhf5ic.json', 'init=/tmp/tmpjd45me00/twdrrp3d.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelude_uhr0/prophet_model-20260803144520.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:20 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:20 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_14_dept_8
Build prophet model for  store_14_dept_80

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5lyb09qs.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jw17ir7k.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=81628', 'data', 'file=/tmp/tmpjd45me00/5lyb09qs.json', 'init=/tmp/tmpjd45me00/jw17ir7k.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelyc5fp016/prophet_model-20260803144520.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:20 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:21 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/esl_4ds0.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/iqqss38z.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=9956', 'data', 'file=/tmp/tmpjd45me00/esl_4ds0.json', 'init=/tmp/tmpjd45me00/iqqss38z.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelt48xexdx/prophet_model-20260803144521.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:21 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:21 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_14_dept_81
Build prophet model for  store_14_dept_82

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7v5a4_a8.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/h57z795_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=39985', 'data', 'file=/tmp/tmpjd45me00/7v5a4_a8.json', 'init=/tmp/tmpjd45me00/h57z795_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model4mwc2zmh/prophet_model-20260803144521.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:21 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:21 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/w9see1x2.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2py80cmi.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=71843', 'data', 'file=/tmp/tmpjd45me00/w9see1x2.json', 'init=/tmp/tmpjd45me00/2py80cmi.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelbdlon5nt/prophet_model-20260803144521.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:21 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:21 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/kbq5phb6.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/lwo_q4zj.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=20241', 'data', 'file=/tmp/tmpjd45me00/kbq5phb6.json', 'init=/tmp/tmpjd45me00/lwo_q4zj.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelolg7nf37/prophet_model-20260803144521.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:21 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_14_dept_83
Build prophet model for  store_14_dept_85

14:45:21 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/y792cgr9.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qh68q_7d.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=59841', 'data', 'file=/tmp/tmpjd45me00/y792cgr9.json', 'init=/tmp/tmpjd45me00/qh68q_7d.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelm9peajmf/prophet_model-20260803144521.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:21 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:21 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_14_dept_87
Build prophet model for  store_14_dept_9

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/oqs9cyoj.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ijup7xoh.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=97460', 'data', 'file=/tmp/tmpjd45me00/oqs9cyoj.json', 'init=/tmp/tmpjd45me00/ijup7xoh.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelf8mn5ek3/prophet_model-20260803144522.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:22 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:22 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7um_ivc1.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fskxh54t.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=96994', 'data', 'file=/tmp/tmpjd45me00/7um_ivc1.json', 'init=/tmp/tmpjd45me00/fskxh54t.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_oodaj9t/prophet_model-20260803144522.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:22 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:22 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_14_dept_90
Build prophet model for  store_14_dept_91

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zo4ieg0k.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/y2k6hpmp.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=74383', 'data', 'file=/tmp/tmpjd45me00/zo4ieg0k.json', 'init=/tmp/tmpjd45me00/y2k6hpmp.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelmjwleb2f/prophet_model-20260803144522.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:22 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:22 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/m7nhbufn.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1iydalfd.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=18207', 'data', 'file=/tmp/tmpjd45me00/m7nhbufn.json', 'init=/tmp/tmpjd45me00/1iydalfd.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model6ntne3m4/prophet_model-20260803144522.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:22 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:22 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_14_dept_92
Build prophet model for  store_14_dept_93

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/t71zvchm.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/invryn_u.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=71886', 'data', 'file=/tmp/tmpjd45me00/t71zvchm.json', 'init=/tmp/tmpjd45me00/invryn_u.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modele3e2_y6a/prophet_model-20260803144522.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:22 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:22 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_14_dept_94
Build prophet model for  store_14_dept_95

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/52gaeysr.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/52jf88ej.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=28163', 'data', 'file=/tmp/tmpjd45me00/52gaeysr.json', 'init=/tmp/tmpjd45me00/52jf88ej.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelw3e45qnh/prophet_model-20260803144523.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:23 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:23 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/e1_mczwj.json

Build prophet model for  store_14_dept_97
Build prophet model for  store_14_dept_98

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/h6rwtc7m.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=96561', 'data', 'file=/tmp/tmpjd45me00/e1_mczwj.json', 'init=/tmp/tmpjd45me00/h6rwtc7m.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelxr6iszkl/prophet_model-20260803144523.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:23 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:23 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fxa1nc6d.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rc_yku2x.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=89956', 'data', 'file=/tmp/tmpjd45me00/fxa1nc6d.json', 'init=/tmp/tmpjd45me00/rc_yku2x.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelemz7w3tt/prophet_model-20260803144523.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:23 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:23 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/tv_nogmj.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/nmmbxgpc.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=33733', 'data', 'file=/tmp/tmpjd45me00/tv_nogmj.json', 'init=/tmp/tmpjd45me00/nmmbxgpc.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelqs_z9zqx/prophet_model-20260803144523.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:23 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_15_dept_1
Build prophet model for  store_15_dept_10

14:45:23 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dp9164w2.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/i_b6vbl7.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=17860', 'data', 'file=/tmp/tmpjd45me00/dp9164w2.json', 'init=/tmp/tmpjd45me00/i_b6vbl7.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelcw_kh82k/prophet_model-20260803144523.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:23 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:24 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_15_dept_11

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6g716kde.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/90chppkd.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=59816', 'data', 'file=/tmp/tmpjd45me00/6g716kde.json', 'init=/tmp/tmpjd45me00/90chppkd.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelzwscnaao/prophet_model-20260803144524.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:24 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:24 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_15_dept_12
Build prophet model for  store_15_dept_13

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ekj3dokn.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/yd0097ld.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=95694', 'data', 'file=/tmp/tmpjd45me00/ekj3dokn.json', 'init=/tmp/tmpjd45me00/yd0097ld.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeltc32znwg/prophet_model-20260803144524.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:24 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:24 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2cdvcdm7.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qrvoog1g.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=37316', 'data', 'file=/tmp/tmpjd45me00/2cdvcdm7.json', 'init=/tmp/tmpjd45me00/qrvoog1g.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model51gj07jc/prophet_model-20260803144524.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:24 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:24 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/48e098zx.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/q7mfk23i.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=90436', 'data', 'file=/tmp/tmpjd45me00/48e098zx.json', 'init=/tmp/tmpjd45me00/q7mfk23i.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelr1b4rta1/prophet_model-20260803144524.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:24 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_15_dept_14
Build prophet model for  store_15_dept_16

14:45:24 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bs190ev6.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5a0gbb4h.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=21974', 'data', 'file=/tmp/tmpjd45me00/bs190ev6.json', 'init=/tmp/tmpjd45me00/5a0gbb4h.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model8fa2c0mo/prophet_model-20260803144524.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:24 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:24 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/yzsyjter.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/371_taio.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=62284', 'data', 'file=/tmp/tmpjd45me00/yzsyjter.json', 'init=/tmp/tmpjd45me00/371_taio.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelvjp8hpfz/prophet_model-20260803144525.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:45:25 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_15_dept_17
Build prophet model for  store_15_dept_18

14:45:25 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zedaniva.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0naw97nz.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=99704', 'data', 'file=/tmp/tmpjd45me00/zedaniva.json', 'init=/tmp/tmpjd45me00/0naw97nz.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model2snef2dy/prophet_model-20260803144526.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:26 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:26 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2f7zffrx.json

Build prophet model for  store_15_dept_19
Build prophet model for  store_15_dept_2

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/j3ck71t1.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=24046', 'data', 'file=/tmp/tmpjd45me00/2f7zffrx.json', 'init=/tmp/tmpjd45me00/j3ck71t1.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model49feyw71/prophet_model-20260803144526.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:26 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:26 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/53zo3wtd.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4myvskwk.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=76216', 'data', 'file=/tmp/tmpjd45me00/53zo3wtd.json', 'init=/tmp/tmpjd45me00/4myvskwk.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelbfj9gaks/prophet_model-20260803144526.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:26 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:26 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_15_dept_20
Build prophet model for  store_15_dept_21

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/63o1pa0n.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/eq5a3gtw.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=87668', 'data', 'file=/tmp/tmpjd45me00/63o1pa0n.json', 'init=/tmp/tmpjd45me00/eq5a3gtw.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model4glih3uy/prophet_model-20260803144526.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:26 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:26 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zna4zeiw.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0bedvxik.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=23531', 'data', 'file=/tmp/tmpjd45me00/zna4zeiw.json', 'init=/tmp/tmpjd45me00/0bedvxik.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model1jggomv0/prophet_model-20260803144526.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:26 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:27 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_15_dept_22
Build prophet model for  store_15_dept_23

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/lx4bmrq_.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gsdtw99i.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=68758', 'data', 'file=/tmp/tmpjd45me00/lx4bmrq_.json', 'init=/tmp/tmpjd45me00/gsdtw99i.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_rx91a4c/prophet_model-20260803144527.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:27 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:27 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/t8acjg7e.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_jw5w3rw.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=91366', 'data', 'file=/tmp/tmpjd45me00/t8acjg7e.json', 'init=/tmp/tmpjd45me00/_jw5w3rw.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelknbqbneq/prophet_model-20260803144527.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:27 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:27 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_15_dept_24

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7d2x7vhz.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/kqkwkh41.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=96111', 'data', 'file=/tmp/tmpjd45me00/7d2x7vhz.json', 'init=/tmp/tmpjd45me00/kqkwkh41.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeltwjyyx99/prophet_model-20260803144527.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:27 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:27 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_15_dept_25

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/uj6vla2t.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/85_d8kzk.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=55866', 'data', 'file=/tmp/tmpjd45me00/uj6vla2t.json', 'init=/tmp/tmpjd45me00/85_d8kzk.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelgyqted2l/prophet_model-20260803144528.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:28 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:28 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_15_dept_26

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gkao_bf6.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/l3uhco_y.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=17877', 'data', 'file=/tmp/tmpjd45me00/gkao_bf6.json', 'init=/tmp/tmpjd45me00/l3uhco_y.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelj206ij7o/prophet_model-20260803144528.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:28 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:28 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_15_dept_27

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ha0p1f2s.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/yotqr68y.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=75744', 'data', 'file=/tmp/tmpjd45me00/ha0p1f2s.json', 'init=/tmp/tmpjd45me00/yotqr68y.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modele8ph4yem/prophet_model-20260803144528.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:28 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_15_dept_28

14:45:29 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ki710ogv.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qk1hmign.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=89721', 'data', 'file=/tmp/tmpjd45me00/ki710ogv.json', 'init=/tmp/tmpjd45me00/qk1hmign.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelz7m06j9y/prophet_model-20260803144529.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:29 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:29 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_15_dept_29

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/impx5m5x.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/lp4kdcfz.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=70675', 'data', 'file=/tmp/tmpjd45me00/impx5m5x.json', 'init=/tmp/tmpjd45me00/lp4kdcfz.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelivrozqsz/prophet_model-20260803144529.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:29 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:29 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mqise27c.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/tm_je26c.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=77864', 'data', 'file=/tmp/tmpjd45me00/mqise27c.json', 'init=/tmp/tmpjd45me00/tm_je26c.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelt3xza3ha/prophet_model-20260803144529.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:29 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_15_dept_3
Build prophet model for  store_15_dept_30

14:45:29 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ppx7c0tm.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/s1l_nhdp.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=73131', 'data', 'file=/tmp/tmpjd45me00/ppx7c0tm.json', 'init=/tmp/tmpjd45me00/s1l_nhdp.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelbo50zk0m/prophet_model-20260803144529.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:29 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:29 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_1m48t3h.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/g_3p_44s.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=90289', 'data', 'file=/tmp/tmpjd45me00/_1m48t3h.json', 'init=/tmp/tmpjd45me00/g_3p_44s.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model5wr0k741/prophet_model-20260803144529.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:29 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_15_dept_31
Build prophet model for  store_15_dept_32

14:45:29 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/va1slwj3.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pecejn7w.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=28923', 'data', 'file=/tmp/tmpjd45me00/va1slwj3.json', 'init=/tmp/tmpjd45me00/pecejn7w.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model8rmrpf0z/prophet_model-20260803144530.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:30 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:30 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_mfncghc.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ty0vqaq0.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=66400', 'data', 'file=/tmp/tmpjd45me00/_mfncghc.json', 'init=/tmp/tmpjd45me00/ty0vqaq0.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelpo2gy0iy/prophet_model-20260803144530.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:30 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_15_dept_33
Build prophet model for  store_15_dept_34

14:45:30 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/h0vti6qq.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/g45_cwou.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=66313', 'data', 'file=/tmp/tmpjd45me00/h0vti6qq.json', 'init=/tmp/tmpjd45me00/g45_cwou.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelm1_xxm3r/prophet_model-20260803144530.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:30 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:30 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/u0xpc1g4.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/u39s601j.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=26265', 'data', 'file=/tmp/tmpjd45me00/u0xpc1g4.json', 'init=/tmp/tmpjd45me00/u39s601j.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelbszmye_t/prophet_model-20260803144530.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:30 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_15_dept_35
Build prophet model for  store_15_dept_36

14:45:30 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0nf5vyko.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/h17gcf4w.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=95083', 'data', 'file=/tmp/tmpjd45me00/0nf5vyko.json', 'init=/tmp/tmpjd45me00/h17gcf4w.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model5p5o85nf/prophet_model-20260803144530.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:30 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:30 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/obyt3119.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1ap_gp9g.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=8070', 'data', 'file=/tmp/tmpjd45me00/obyt3119.json', 'init=/tmp/tmpjd45me00/1ap_gp9g.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeli6c121uj/prophet_model-20260803144531.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:31 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_15_dept_38
Build prophet model for  store_15_dept_4

14:45:31 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ghhtkcsi.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mglu_0jq.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=79325', 'data', 'file=/tmp/tmpjd45me00/ghhtkcsi.json', 'init=/tmp/tmpjd45me00/mglu_0jq.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeln_km_f66/prophet_model-20260803144531.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:31 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:31 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_15_dept_40

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/umm27nug.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_lxcd7wz.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=12843', 'data', 'file=/tmp/tmpjd45me00/umm27nug.json', 'init=/tmp/tmpjd45me00/_lxcd7wz.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelj5spotv7/prophet_model-20260803144531.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:31 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:31 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_15_dept_41

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/r0vzzdfr.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5oz11xc2.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=41079', 'data', 'file=/tmp/tmpjd45me00/r0vzzdfr.json', 'init=/tmp/tmpjd45me00/5oz11xc2.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelf59vy3u5/prophet_model-20260803144531.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:31 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:31 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/oe8_e7af.json

Build prophet model for  store_15_dept_42
Build prophet model for  store_15_dept_44

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/u6j9pouj.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=5256', 'data', 'file=/tmp/tmpjd45me00/oe8_e7af.json', 'init=/tmp/tmpjd45me00/u6j9pouj.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelz4wrdbip/prophet_model-20260803144531.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:31 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:31 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/iymdw5y4.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/so3x73k3.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=85996', 'data', 'file=/tmp/tmpjd45me00/iymdw5y4.json', 'init=/tmp/tmpjd45me00/so3x73k3.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model2o_q55ah/prophet_model-20260803144532.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:32 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_15_dept_46

14:45:32 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/aj576hzr.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/l5yv2b0v.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=35626', 'data', 'file=/tmp/tmpjd45me00/aj576hzr.json', 'init=/tmp/tmpjd45me00/l5yv2b0v.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelvt69f51l/prophet_model-20260803144532.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:32 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:32 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_15_dept_49
Build prophet model for  store_15_dept_5

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bj_r0rks.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gdp1lcf_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=63919', 'data', 'file=/tmp/tmpjd45me00/bj_r0rks.json', 'init=/tmp/tmpjd45me00/gdp1lcf_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model6yi1ibzc/prophet_model-20260803144532.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:32 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:32 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/09jp1ib_.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rwl_xmdm.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=17130', 'data', 'file=/tmp/tmpjd45me00/09jp1ib_.json', 'init=/tmp/tmpjd45me00/rwl_xmdm.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelr_tw440b/prophet_model-20260803144532.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:32 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:32 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6ps8ejyq.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1_ldv04v.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=16525', 'data', 'file=/tmp/tmpjd45me00/6ps8ejyq.json', 'init=/tmp/tmpjd45me00/1_ldv04v.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model76j454zf/prophet_model-20260803144532.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:32 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_15_dept_50
Build prophet model for  store_15_dept_52

14:45:32 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ajjxtuyl.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ezgtrb9i.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=88617', 'data', 'file=/tmp/tmpjd45me00/ajjxtuyl.json', 'init=/tmp/tmpjd45me00/ezgtrb9i.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model86k4p1iv/prophet_model-20260803144532.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:32 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:33 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jf2wt96s.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jzf2rtjw.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=5894', 'data', 'file=/tmp/tmpjd45me00/jf2wt96s.json', 'init=/tmp/tmpjd45me00/jzf2rtjw.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelx2nxjflu/prophet_model-20260803144533.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:33 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_15_dept_54
Build prophet model for  store_15_dept_55

14:45:33 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zglhwq1f.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_o55yxkq.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=31800', 'data', 'file=/tmp/tmpjd45me00/zglhwq1f.json', 'init=/tmp/tmpjd45me00/_o55yxkq.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelar2ycrjh/prophet_model-20260803144533.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:33 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:33 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_15_dept_56
Build prophet model for  store_15_dept_58

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3bvbtnxq.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/toncc9bn.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=85190', 'data', 'file=/tmp/tmpjd45me00/3bvbtnxq.json', 'init=/tmp/tmpjd45me00/toncc9bn.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modellfn6oh8n/prophet_model-20260803144533.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:45:33 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:33 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/41sehd_9.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/m6wlv2yq.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=74416', 'data', 'file=/tmp/tmpjd45me00/41sehd_9.json', 'init=/tmp/tmpjd45me00/m6wlv2yq.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelthsoivbg/prophet_model-20260803144534.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:34 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_15_dept_59

14:45:34 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_dnrylww.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/i5szkft7.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=82458', 'data', 'file=/tmp/tmpjd45me00/_dnrylww.json', 'init=/tmp/tmpjd45me00/i5szkft7.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelxg2s2d18/prophet_model-20260803144534.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:34 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:34 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dg8ah4fq.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jemvn9dw.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=96990', 'data', 'file=/tmp/tmpjd45me00/dg8ah4fq.json', 'init=/tmp/tmpjd45me00/jemvn9dw.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model66_mw7k4/prophet_model-20260803144534.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:34 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_15_dept_6
Build prophet model for  store_15_dept_67

14:45:34 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ed3mpo6m.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/f_o5ah1z.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=51182', 'data', 'file=/tmp/tmpjd45me00/ed3mpo6m.json', 'init=/tmp/tmpjd45me00/f_o5ah1z.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model3yuxs6n3/prophet_model-20260803144534.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:34 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:34 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xeplagzz.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xoiss5az.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=56550', 'data', 'file=/tmp/tmpjd45me00/xeplagzz.json', 'init=/tmp/tmpjd45me00/xoiss5az.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeljq09dsfa/prophet_model-20260803144534.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:34 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:34 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_15_dept_7
Build prophet model for  store_15_dept_71

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ciie3hvh.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dk8hnhb2.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=70981', 'data', 'file=/tmp/tmpjd45me00/ciie3hvh.json', 'init=/tmp/tmpjd45me00/dk8hnhb2.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model6x70bvnp/prophet_model-20260803144535.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:35 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:35 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/oc0dj6ef.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0sax0ifu.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=49079', 'data', 'file=/tmp/tmpjd45me00/oc0dj6ef.json', 'init=/tmp/tmpjd45me00/0sax0ifu.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model0cbfwy_6/prophet_model-20260803144535.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:35 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_15_dept_72
Build prophet model for  store_15_dept_74

14:45:35 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vp5aly69.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zst0lpgr.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=84846', 'data', 'file=/tmp/tmpjd45me00/vp5aly69.json', 'init=/tmp/tmpjd45me00/zst0lpgr.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model9d9xl9cy/prophet_model-20260803144535.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:35 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:35 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/x9mlesyz.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ur2_gaie.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=812', 'data', 'file=/tmp/tmpjd45me00/x9mlesyz.json', 'init=/tmp/tmpjd45me00/ur2_gaie.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelow_0y072/prophet_model-20260803144535.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:35 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_15_dept_79
Build prophet model for  store_15_dept_8

14:45:35 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/exwa8kl1.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/prts3u_y.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=62658', 'data', 'file=/tmp/tmpjd45me00/exwa8kl1.json', 'init=/tmp/tmpjd45me00/prts3u_y.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelatzv2spe/prophet_model-20260803144535.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:35 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:35 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/00attckd.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/f5ml9hx5.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=70339', 'data', 'file=/tmp/tmpjd45me00/00attckd.json', 'init=/tmp/tmpjd45me00/f5ml9hx5.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model8msn0ggd/prophet_model-20260803144535.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:35 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_15_dept_80
Build prophet model for  store_15_dept_81

14:45:36 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4hi104oa.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/slkvs5hv.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=15909', 'data', 'file=/tmp/tmpjd45me00/4hi104oa.json', 'init=/tmp/tmpjd45me00/slkvs5hv.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelsc9skm1v/prophet_model-20260803144536.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:36 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_15_dept_82

14:45:36 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4qd3g82b.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/p1ud9niv.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=79712', 'data', 'file=/tmp/tmpjd45me00/4qd3g82b.json', 'init=/tmp/tmpjd45me00/p1ud9niv.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model8xzs_43b/prophet_model-20260803144536.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:36 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:36 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_15_dept_83

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1ocgzwvb.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zv9rgawt.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=58752', 'data', 'file=/tmp/tmpjd45me00/1ocgzwvb.json', 'init=/tmp/tmpjd45me00/zv9rgawt.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model4yemylpi/prophet_model-20260803144536.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:36 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_15_dept_85

14:45:37 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/j_5wy_ie.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/m6t6uwtj.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=41891', 'data', 'file=/tmp/tmpjd45me00/j_5wy_ie.json', 'init=/tmp/tmpjd45me00/m6t6uwtj.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelk1f20tta/prophet_model-20260803144537.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:37 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:37 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_15_dept_87

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/y70tl9wx.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2tpvqhfb.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=40825', 'data', 'file=/tmp/tmpjd45me00/y70tl9wx.json', 'init=/tmp/tmpjd45me00/2tpvqhfb.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model3cz4kl9t/prophet_model-20260803144537.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:37 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:37 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/e19uxjs5.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/j3740va4.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=94868', 'data', 'file=/tmp/tmpjd45me00/e19uxjs5.json', 'init=/tmp/tmpjd45me00/j3740va4.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeli9ghzx83/prophet_model-20260803144537.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:37 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_15_dept_9
Build prophet model for  store_15_dept_90

14:45:37 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/b7bjv69s.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/sncc_btg.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=40843', 'data', 'file=/tmp/tmpjd45me00/b7bjv69s.json', 'init=/tmp/tmpjd45me00/sncc_btg.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model2o2asuh8/prophet_model-20260803144537.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:37 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:38 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mtyaz2kh.json

Build prophet model for  store_15_dept_91
Build prophet model for  store_15_dept_92

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/r3l14yna.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=18943', 'data', 'file=/tmp/tmpjd45me00/mtyaz2kh.json', 'init=/tmp/tmpjd45me00/r3l14yna.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model1psdpjyj/prophet_model-20260803144538.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:38 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:38 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jov4qbdk.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/u2962o9w.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=51502', 'data', 'file=/tmp/tmpjd45me00/jov4qbdk.json', 'init=/tmp/tmpjd45me00/u2962o9w.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelpki084ld/prophet_model-20260803144538.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:38 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:38 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_15_dept_93

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zy6h1lxa.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/tqu_5ux2.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=1018', 'data', 'file=/tmp/tmpjd45me00/zy6h1lxa.json', 'init=/tmp/tmpjd45me00/tqu_5ux2.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_rc_x8xf/prophet_model-20260803144538.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:38 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:38 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_15_dept_95
Build prophet model for  store_15_dept_96

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/omxnqlba.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8nxz9v1g.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=86321', 'data', 'file=/tmp/tmpjd45me00/omxnqlba.json', 'init=/tmp/tmpjd45me00/8nxz9v1g.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelota90wtq/prophet_model-20260803144538.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:38 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:38 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/59z6c6pf.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9cztp85i.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=65662', 'data', 'file=/tmp/tmpjd45me00/59z6c6pf.json', 'init=/tmp/tmpjd45me00/9cztp85i.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelzuq_60be/prophet_model-20260803144538.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:38 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:39 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/s002xbza.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ecr_ifdd.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=47103', 'data', 'file=/tmp/tmpjd45me00/s002xbza.json', 'init=/tmp/tmpjd45me00/ecr_ifdd.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model526iqif9/prophet_model-20260803144539.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:39 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_15_dept_97
Build prophet model for  store_16_dept_1

14:45:39 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jl4sixlc.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gkvp4qh1.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=69496', 'data', 'file=/tmp/tmpjd45me00/jl4sixlc.json', 'init=/tmp/tmpjd45me00/gkvp4qh1.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model8etxu2il/prophet_model-20260803144539.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:39 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:39 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_16_dept_10
Build prophet model for  store_16_dept_11

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0e4vxza0.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/o7l08x75.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=66636', 'data', 'file=/tmp/tmpjd45me00/0e4vxza0.json', 'init=/tmp/tmpjd45me00/o7l08x75.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model5qf6aatj/prophet_model-20260803144539.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:39 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:39 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7vzu3dti.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1eytcne0.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=64522', 'data', 'file=/tmp/tmpjd45me00/7vzu3dti.json', 'init=/tmp/tmpjd45me00/1eytcne0.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modele6wblui5/prophet_model-20260803144539.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:39 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_16_dept_12

14:45:40 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zsoxqvbe.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8_5cemgg.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=49338', 'data', 'file=/tmp/tmpjd45me00/zsoxqvbe.json', 'init=/tmp/tmpjd45me00/8_5cemgg.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelqjetbew0/prophet_model-20260803144540.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:40 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:40 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_16_dept_13

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zy3fr6_p.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5yal6l94.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=74750', 'data', 'file=/tmp/tmpjd45me00/zy3fr6_p.json', 'init=/tmp/tmpjd45me00/5yal6l94.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelh9gfh0oj/prophet_model-20260803144540.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:40 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:40 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_16_dept_14

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/inomv61j.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pg_oit6e.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=8293', 'data', 'file=/tmp/tmpjd45me00/inomv61j.json', 'init=/tmp/tmpjd45me00/pg_oit6e.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelqbsvr2em/prophet_model-20260803144540.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:40 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_16_dept_16

14:45:41 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/srinqhcx.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/29gd3qlc.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=92811', 'data', 'file=/tmp/tmpjd45me00/srinqhcx.json', 'init=/tmp/tmpjd45me00/29gd3qlc.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelzhcbpmge/prophet_model-20260803144541.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:41 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:41 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_16_dept_17

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/58r__61v.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/48puvspo.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=67620', 'data', 'file=/tmp/tmpjd45me00/58r__61v.json', 'init=/tmp/tmpjd45me00/48puvspo.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelflpzr0mi/prophet_model-20260803144541.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:45:41 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_16_dept_18

14:45:43 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0bckn9qe.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/i7tft5lu.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=53955', 'data', 'file=/tmp/tmpjd45me00/0bckn9qe.json', 'init=/tmp/tmpjd45me00/i7tft5lu.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model1p4hrxrn/prophet_model-20260803144543.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:43 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:43 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_16_dept_19

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/lukqoofv.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/knz03n5o.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=42806', 'data', 'file=/tmp/tmpjd45me00/lukqoofv.json', 'init=/tmp/tmpjd45me00/knz03n5o.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model5kv13nsz/prophet_model-20260803144544.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:44 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:44 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_16_dept_2

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/goln4ufm.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/d7h13lsu.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=62949', 'data', 'file=/tmp/tmpjd45me00/goln4ufm.json', 'init=/tmp/tmpjd45me00/d7h13lsu.json', 'output', 'file=/tmp/tmpjd45me00/prophet_models4x82_oj/prophet_model-20260803144544.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:44 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:44 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/h2h_vtr_.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5qelth7e.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=47061', 'data', 'file=/tmp/tmpjd45me00/h2h_vtr_.json', 'init=/tmp/tmpjd45me00/5qelth7e.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelgjt1ea7r/prophet_model-20260803144544.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:44 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_16_dept_20
Build prophet model for  store_16_dept_21

14:45:44 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/czotzg0l.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/118994ix.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=52937', 'data', 'file=/tmp/tmpjd45me00/czotzg0l.json', 'init=/tmp/tmpjd45me00/118994ix.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeleb2uxe45/prophet_model-20260803144544.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:44 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:44 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_16_dept_22
Build prophet model for  store_16_dept_23

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/d01kxjdq.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/x74sovjh.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=88875', 'data', 'file=/tmp/tmpjd45me00/d01kxjdq.json', 'init=/tmp/tmpjd45me00/x74sovjh.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeltohb_yhq/prophet_model-20260803144544.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:44 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:44 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/kpw_snot.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wj43mqq1.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=41576', 'data', 'file=/tmp/tmpjd45me00/kpw_snot.json', 'init=/tmp/tmpjd45me00/wj43mqq1.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model2fy7zjlj/prophet_model-20260803144545.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:45 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:45 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/l54eoe42.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1_iq09is.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=34249', 'data', 'file=/tmp/tmpjd45me00/l54eoe42.json', 'init=/tmp/tmpjd45me00/1_iq09is.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model3w4r1_g5/prophet_model-20260803144545.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:45 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_16_dept_24
Build prophet model for  store_16_dept_25

14:45:45 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zxlhld_j.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/oyk1l7zy.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=18890', 'data', 'file=/tmp/tmpjd45me00/zxlhld_j.json', 'init=/tmp/tmpjd45me00/oyk1l7zy.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelx7ohmmas/prophet_model-20260803144545.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:45 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:45 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6829iebe.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/j3tgxv0e.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=12756', 'data', 'file=/tmp/tmpjd45me00/6829iebe.json', 'init=/tmp/tmpjd45me00/j3tgxv0e.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model2g_fv2tg/prophet_model-20260803144545.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:45 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_16_dept_26
Build prophet model for  store_16_dept_27

14:45:45 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/98yed7la.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qjkwbwqh.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=52312', 'data', 'file=/tmp/tmpjd45me00/98yed7la.json', 'init=/tmp/tmpjd45me00/qjkwbwqh.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelq337qdy5/prophet_model-20260803144545.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:45 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:45 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6df9y8ep.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8vkcbv4f.json

Build prophet model for  store_16_dept_28
Build prophet model for  store_16_dept_29

DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=32262', 'data', 'file=/tmp/tmpjd45me00/6df9y8ep.json', 'init=/tmp/tmpjd45me00/8vkcbv4f.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_mcv6igf/prophet_model-20260803144545.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:45 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:46 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/san0y7fp.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/nm6pgmng.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=43522', 'data', 'file=/tmp/tmpjd45me00/san0y7fp.json', 'init=/tmp/tmpjd45me00/nm6pgmng.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeldm6jh07v/prophet_model-20260803144546.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:46 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:46 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0fkygmyq.json

Build prophet model for  store_16_dept_3
Build prophet model for  store_16_dept_30

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ei7hpwm6.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=66826', 'data', 'file=/tmp/tmpjd45me00/0fkygmyq.json', 'init=/tmp/tmpjd45me00/ei7hpwm6.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelf2vngln1/prophet_model-20260803144546.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:46 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:46 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6ef_ui6m.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vfy9oiql.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=18128', 'data', 'file=/tmp/tmpjd45me00/6ef_ui6m.json', 'init=/tmp/tmpjd45me00/vfy9oiql.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model__9blba0/prophet_model-20260803144546.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:46 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:46 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_16_dept_31

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/sk400op0.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_6yl0iig.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=84126', 'data', 'file=/tmp/tmpjd45me00/sk400op0.json', 'init=/tmp/tmpjd45me00/_6yl0iig.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeljmgbxfp4/prophet_model-20260803144546.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:46 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:46 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4xnwh0ss.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fd00j_ni.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=48665', 'data', 'file=/tmp/tmpjd45me00/4xnwh0ss.json', 'init=/tmp/tmpjd45me00/fd00j_ni.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelq5x0l5mx/prophet_model-20260803144547.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:47 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_16_dept_32
Build prophet model for  store_16_dept_33

14:45:47 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hwa1ej6b.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/954xicel.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=65845', 'data', 'file=/tmp/tmpjd45me00/hwa1ej6b.json', 'init=/tmp/tmpjd45me00/954xicel.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model8datlrrg/prophet_model-20260803144547.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:47 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_16_dept_34

14:45:47 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3jmfkf45.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pmjaov5t.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=57978', 'data', 'file=/tmp/tmpjd45me00/3jmfkf45.json', 'init=/tmp/tmpjd45me00/pmjaov5t.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelkzr2krrk/prophet_model-20260803144547.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:47 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:47 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/o83_ye6d.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8g8q3j8v.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=18847', 'data', 'file=/tmp/tmpjd45me00/o83_ye6d.json', 'init=/tmp/tmpjd45me00/8g8q3j8v.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelk8brzrhu/prophet_model-20260803144547.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:47 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_16_dept_35
Build prophet model for  store_16_dept_36

14:45:48 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/etyhqh_p.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/c8l45xk_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=51676', 'data', 'file=/tmp/tmpjd45me00/etyhqh_p.json', 'init=/tmp/tmpjd45me00/c8l45xk_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modellvg1ao42/prophet_model-20260803144548.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:48 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:48 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5jh2x8bq.json

Build prophet model for  store_16_dept_38
Build prophet model for  store_16_dept_4

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vw096ydy.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=7966', 'data', 'file=/tmp/tmpjd45me00/5jh2x8bq.json', 'init=/tmp/tmpjd45me00/vw096ydy.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelbu5zahp0/prophet_model-20260803144548.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:48 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:48 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fkzc0p_z.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hnrrvuts.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=91487', 'data', 'file=/tmp/tmpjd45me00/fkzc0p_z.json', 'init=/tmp/tmpjd45me00/hnrrvuts.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelsmf_6782/prophet_model-20260803144548.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:48 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:48 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_16_dept_40

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/13mfolpr.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fo87i21h.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=63350', 'data', 'file=/tmp/tmpjd45me00/13mfolpr.json', 'init=/tmp/tmpjd45me00/fo87i21h.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeli08e7bp1/prophet_model-20260803144548.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:48 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:48 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_16_dept_41
Build prophet model for  store_16_dept_42

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/z3et6u_c.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2ib8ixpl.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=3217', 'data', 'file=/tmp/tmpjd45me00/z3et6u_c.json', 'init=/tmp/tmpjd45me00/2ib8ixpl.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model3kkwd5cg/prophet_model-20260803144549.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:49 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:49 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rfhvv1wy.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/h7gujmcv.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=31844', 'data', 'file=/tmp/tmpjd45me00/rfhvv1wy.json', 'init=/tmp/tmpjd45me00/h7gujmcv.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelaf56zjqx/prophet_model-20260803144549.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:49 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:49 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_16_dept_44

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/e7kx2300.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3an57ku6.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=38664', 'data', 'file=/tmp/tmpjd45me00/e7kx2300.json', 'init=/tmp/tmpjd45me00/3an57ku6.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeltp86qprx/prophet_model-20260803144549.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:49 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_16_dept_46

14:45:49 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gxrsalpj.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gii8m_0f.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=94789', 'data', 'file=/tmp/tmpjd45me00/gxrsalpj.json', 'init=/tmp/tmpjd45me00/gii8m_0f.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelm2zo0nim/prophet_model-20260803144549.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:49 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:49 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/92oiprl4.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/o211t20h.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=23016', 'data', 'file=/tmp/tmpjd45me00/92oiprl4.json', 'init=/tmp/tmpjd45me00/o211t20h.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelgvtdw70b/prophet_model-20260803144550.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:50 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_16_dept_5
Build prophet model for  store_16_dept_52

14:45:50 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5vavb3ax.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ytd3f9ku.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=98355', 'data', 'file=/tmp/tmpjd45me00/5vavb3ax.json', 'init=/tmp/tmpjd45me00/ytd3f9ku.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelxofys3bz/prophet_model-20260803144550.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:50 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:50 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ihj8y7dd.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/uocjobxw.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=9500', 'data', 'file=/tmp/tmpjd45me00/ihj8y7dd.json', 'init=/tmp/tmpjd45me00/uocjobxw.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model9xxdyp6u/prophet_model-20260803144550.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:50 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_16_dept_54
Build prophet model for  store_16_dept_55

14:45:50 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/86g770al.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/iioezotx.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=18819', 'data', 'file=/tmp/tmpjd45me00/86g770al.json', 'init=/tmp/tmpjd45me00/iioezotx.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelxgqtuzzy/prophet_model-20260803144550.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:50 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_16_dept_56

14:45:50 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/c0fc7cuc.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/de6moghf.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=56246', 'data', 'file=/tmp/tmpjd45me00/c0fc7cuc.json', 'init=/tmp/tmpjd45me00/de6moghf.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelaqlkgd3l/prophet_model-20260803144550.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:50 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:50 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6nnr9jq2.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pk2yy4sa.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=99610', 'data', 'file=/tmp/tmpjd45me00/6nnr9jq2.json', 'init=/tmp/tmpjd45me00/pk2yy4sa.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model3wapgjh5/prophet_model-20260803144551.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:51 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_16_dept_59
Build prophet model for  store_16_dept_6

14:45:51 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/cqad7v38.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vdo0rxdr.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=59789', 'data', 'file=/tmp/tmpjd45me00/cqad7v38.json', 'init=/tmp/tmpjd45me00/vdo0rxdr.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeldl9gfb31/prophet_model-20260803144551.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:51 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:51 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/erh729pu.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/phhhaoj4.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=31608', 'data', 'file=/tmp/tmpjd45me00/erh729pu.json', 'init=/tmp/tmpjd45me00/phhhaoj4.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelca4deb_4/prophet_model-20260803144551.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:51 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_16_dept_67
Build prophet model for  store_16_dept_7

14:45:51 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ig92ilgw.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qixsfp0f.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=9134', 'data', 'file=/tmp/tmpjd45me00/ig92ilgw.json', 'init=/tmp/tmpjd45me00/qixsfp0f.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelpkz_kvt_/prophet_model-20260803144551.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:51 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:51 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/e6txyf9m.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/iikaiiwf.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=15410', 'data', 'file=/tmp/tmpjd45me00/e6txyf9m.json', 'init=/tmp/tmpjd45me00/iikaiiwf.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelkh7s5664/prophet_model-20260803144551.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:51 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_16_dept_71
Build prophet model for  store_16_dept_72

14:45:51 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qis6gh5d.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/tqm9trw1.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=74780', 'data', 'file=/tmp/tmpjd45me00/qis6gh5d.json', 'init=/tmp/tmpjd45me00/tqm9trw1.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelk5v_h50y/prophet_model-20260803144552.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:52 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:52 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_16_dept_74
Build prophet model for  store_16_dept_79

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/cj5wh6bw.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/h8qeeonj.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=21776', 'data', 'file=/tmp/tmpjd45me00/cj5wh6bw.json', 'init=/tmp/tmpjd45me00/h8qeeonj.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model2vpaf4dm/prophet_model-20260803144552.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:52 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:52 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/yig3ctf4.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/tusi88q1.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=36110', 'data', 'file=/tmp/tmpjd45me00/yig3ctf4.json', 'init=/tmp/tmpjd45me00/tusi88q1.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelys8yqrht/prophet_model-20260803144552.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:52 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:52 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_16_dept_8
Build prophet model for  store_16_dept_81

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4gllum2s.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/whjzsqdm.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=11940', 'data', 'file=/tmp/tmpjd45me00/4gllum2s.json', 'init=/tmp/tmpjd45me00/whjzsqdm.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelq1ird6qx/prophet_model-20260803144552.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:52 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:53 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wqrarfht.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/l_qh9e5l.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=93083', 'data', 'file=/tmp/tmpjd45me00/wqrarfht.json', 'init=/tmp/tmpjd45me00/l_qh9e5l.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model9sor1t2m/prophet_model-20260803144553.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:53 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:53 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_16_dept_82

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/suc58_ar.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8epq8p32.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=3643', 'data', 'file=/tmp/tmpjd45me00/suc58_ar.json', 'init=/tmp/tmpjd45me00/8epq8p32.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model2lgmvq2a/prophet_model-20260803144553.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:53 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_16_dept_85

14:45:53 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/z_gf2_8j.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/tulvoayq.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=58240', 'data', 'file=/tmp/tmpjd45me00/z_gf2_8j.json', 'init=/tmp/tmpjd45me00/tulvoayq.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelhcr8g9tg/prophet_model-20260803144554.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:54 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_16_dept_87

14:45:54 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/lsd1uzlw.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rwphvek4.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=3878', 'data', 'file=/tmp/tmpjd45me00/lsd1uzlw.json', 'init=/tmp/tmpjd45me00/rwphvek4.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelo4vhhbyv/prophet_model-20260803144554.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:54 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:54 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_16_dept_9
Build prophet model for  store_16_dept_90

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4hi725nw.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/m9620pxm.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=94885', 'data', 'file=/tmp/tmpjd45me00/4hi725nw.json', 'init=/tmp/tmpjd45me00/m9620pxm.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelbzvtvwae/prophet_model-20260803144554.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:54 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:55 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vmq1h3z1.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rbowxgru.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=46791', 'data', 'file=/tmp/tmpjd45me00/vmq1h3z1.json', 'init=/tmp/tmpjd45me00/rbowxgru.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model1wm0o6lh/prophet_model-20260803144555.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:55 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_16_dept_91

14:45:55 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/oz98md43.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ehb7el_i.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=13055', 'data', 'file=/tmp/tmpjd45me00/oz98md43.json', 'init=/tmp/tmpjd45me00/ehb7el_i.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model76zq5pvu/prophet_model-20260803144555.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:55 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_16_dept_92

14:45:56 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qwbi5h8j.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/g_wlw0y3.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=74902', 'data', 'file=/tmp/tmpjd45me00/qwbi5h8j.json', 'init=/tmp/tmpjd45me00/g_wlw0y3.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelrtogkm6m/prophet_model-20260803144556.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:45:56 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_16_dept_94

14:45:57 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/lzjhq3um.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0f1pkv8i.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=36103', 'data', 'file=/tmp/tmpjd45me00/lzjhq3um.json', 'init=/tmp/tmpjd45me00/0f1pkv8i.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelnuiqfps7/prophet_model-20260803144557.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:57 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_16_dept_95

14:45:57 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ek9kc9hm.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/g51jzv1k.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=1562', 'data', 'file=/tmp/tmpjd45me00/ek9kc9hm.json', 'init=/tmp/tmpjd45me00/g51jzv1k.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelpxqmhblm/prophet_model-20260803144557.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:57 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:57 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_16_dept_96

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ngqmrar5.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/x2wa2bw6.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=70791', 'data', 'file=/tmp/tmpjd45me00/ngqmrar5.json', 'init=/tmp/tmpjd45me00/x2wa2bw6.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model3bvhzflq/prophet_model-20260803144558.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:58 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_16_dept_97

14:45:58 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_osdsyeg.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9t7e_4d_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=90018', 'data', 'file=/tmp/tmpjd45me00/_osdsyeg.json', 'init=/tmp/tmpjd45me00/9t7e_4d_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelnnezjf61/prophet_model-20260803144558.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:58 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:58 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/m9nurntg.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7pf8fvte.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=23307', 'data', 'file=/tmp/tmpjd45me00/m9nurntg.json', 'init=/tmp/tmpjd45me00/7pf8fvte.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelk4umlga7/prophet_model-20260803144558.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:58 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_17_dept_1
Build prophet model for  store_17_dept_10

14:45:58 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_gl7hq8z.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/flz_tl4n.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=65941', 'data', 'file=/tmp/tmpjd45me00/_gl7hq8z.json', 'init=/tmp/tmpjd45me00/flz_tl4n.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelgxcfqn04/prophet_model-20260803144558.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:58 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:58 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gn3vn_uw.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pppgzi6y.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=66269', 'data', 'file=/tmp/tmpjd45me00/gn3vn_uw.json', 'init=/tmp/tmpjd45me00/pppgzi6y.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model1i1rew16/prophet_model-20260803144558.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:58 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_17_dept_11
Build prophet model for  store_17_dept_12

14:45:59 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/h52fmmyf.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1yvnj1aw.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=64742', 'data', 'file=/tmp/tmpjd45me00/h52fmmyf.json', 'init=/tmp/tmpjd45me00/1yvnj1aw.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelbabecio2/prophet_model-20260803144559.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:59 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:59 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6kuw4e1h.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wq1k7_4j.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=45512', 'data', 'file=/tmp/tmpjd45me00/6kuw4e1h.json', 'init=/tmp/tmpjd45me00/wq1k7_4j.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model003enkng/prophet_model-20260803144559.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:59 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:59 - cmdstanpy - INFO - Chain [1] done processing

Build prophet model for  store_17_dept_13
Build prophet model for  store_17_dept_14

INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/w5oc8eyx.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/16mfmf3d.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=53374', 'data', 'file=/tmp/tmpjd45me00/w5oc8eyx.json', 'init=/tmp/tmpjd45me00/16mfmf3d.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelncka7xwy/prophet_model-20260803144559.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:59 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:59 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_17_dept_16
Build prophet model for  store_17_dept_17

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/djwnr8uh.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/utoqtrlo.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=93086', 'data', 'file=/tmp/tmpjd45me00/djwnr8uh.json', 'init=/tmp/tmpjd45me00/utoqtrlo.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelcwxmt1un/prophet_model-20260803144559.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:45:59 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:45:59 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8noswyzj.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/34l1e0cy.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=63473', 'data', 'file=/tmp/tmpjd45me00/8noswyzj.json', 'init=/tmp/tmpjd45me00/34l1e0cy.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelrm_6y1b4/prophet_model-20260803144559.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:45:59 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_17_dept_18

14:46:01 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/st3m5jp1.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hf8k7c81.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=61479', 'data', 'file=/tmp/tmpjd45me00/st3m5jp1.json', 'init=/tmp/tmpjd45me00/hf8k7c81.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelnojh_63w/prophet_model-20260803144601.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:01 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:01 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_17_dept_19
Build prophet model for  store_17_dept_2

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/eb4pckzq.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/o1_nfy7h.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=42152', 'data', 'file=/tmp/tmpjd45me00/eb4pckzq.json', 'init=/tmp/tmpjd45me00/o1_nfy7h.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeli7i6w091/prophet_model-20260803144601.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:01 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:01 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3k0p27h1.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6cua45m1.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=99629', 'data', 'file=/tmp/tmpjd45me00/3k0p27h1.json', 'init=/tmp/tmpjd45me00/6cua45m1.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_4lttf4d/prophet_model-20260803144601.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:01 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:01 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/you04w7j.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hcvtiu4v.json
DEBUG:cmdstanpy:idx 0

Build prophet model for  store_17_dept_20
Build prophet model for  store_17_dept_21

DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=83901', 'data', 'file=/tmp/tmpjd45me00/you04w7j.json', 'init=/tmp/tmpjd45me00/hcvtiu4v.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelld1iskrc/prophet_model-20260803144601.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:01 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:01 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8pxdj6r3.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gi5wxzdt.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=40529', 'data', 'file=/tmp/tmpjd45me00/8pxdj6r3.json', 'init=/tmp/tmpjd45me00/gi5wxzdt.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeliyqh7rao/prophet_model-20260803144602.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:02 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:02 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bjx6gcel.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dj7puc2x.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=10923', 'data', 'file=/tmp/tmpjd45me00/bjx6gcel.json', 'init=/tmp/tmpjd45me00/dj7puc2x.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelsusf5w7r/prophet_model-20260803144602.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:02 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_17_dept_22
Build prophet model for  store_17_dept_23

14:46:02 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/k1x3gmia.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gqcc9q_k.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=1873', 'data', 'file=/tmp/tmpjd45me00/k1x3gmia.json', 'init=/tmp/tmpjd45me00/gqcc9q_k.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelk1a74wvc/prophet_model-20260803144602.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:02 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:02 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_17_dept_24
Build prophet model for  store_17_dept_25

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/j85_ve1r.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/z0e8hu8e.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=94248', 'data', 'file=/tmp/tmpjd45me00/j85_ve1r.json', 'init=/tmp/tmpjd45me00/z0e8hu8e.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modellg4f3t5k/prophet_model-20260803144602.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:02 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:02 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8ncp5z4k.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/nbtredtg.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=15749', 'data', 'file=/tmp/tmpjd45me00/8ncp5z4k.json', 'init=/tmp/tmpjd45me00/nbtredtg.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeljvhq31b1/prophet_model-20260803144602.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:02 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:02 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_17_dept_26
Build prophet model for  store_17_dept_27

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fk6jx_qu.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gvm22equ.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=48564', 'data', 'file=/tmp/tmpjd45me00/fk6jx_qu.json', 'init=/tmp/tmpjd45me00/gvm22equ.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelcykqy7q1/prophet_model-20260803144602.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:02 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:02 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8vddmguv.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/x2vhfp31.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=69800', 'data', 'file=/tmp/tmpjd45me00/8vddmguv.json', 'init=/tmp/tmpjd45me00/x2vhfp31.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modely2jcyzby/prophet_model-20260803144603.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:03 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_17_dept_28

14:46:03 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1ibc7v7f.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_q36y64k.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=43142', 'data', 'file=/tmp/tmpjd45me00/1ibc7v7f.json', 'init=/tmp/tmpjd45me00/_q36y64k.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelgj8jt2tu/prophet_model-20260803144603.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:03 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:03 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_17_dept_29
Build prophet model for  store_17_dept_3

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vldyro0_.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/x1o9cgh9.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=19818', 'data', 'file=/tmp/tmpjd45me00/vldyro0_.json', 'init=/tmp/tmpjd45me00/x1o9cgh9.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model8u8y1opu/prophet_model-20260803144603.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:03 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:03 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zgadoumq.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/o_h6cnbi.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=40133', 'data', 'file=/tmp/tmpjd45me00/zgadoumq.json', 'init=/tmp/tmpjd45me00/o_h6cnbi.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model0gv4t4qt/prophet_model-20260803144603.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:03 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_17_dept_30

14:46:04 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1r2gwe7k.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/lk_8p35u.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=18381', 'data', 'file=/tmp/tmpjd45me00/1r2gwe7k.json', 'init=/tmp/tmpjd45me00/lk_8p35u.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelv6t3ab7g/prophet_model-20260803144604.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:04 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:04 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qzmj899y.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/whix3dkk.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=1090', 'data', 'file=/tmp/tmpjd45me00/qzmj899y.json', 'init=/tmp/tmpjd45me00/whix3dkk.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelwzw56zh0/prophet_model-20260803144604.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:04 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_17_dept_31
Build prophet model for  store_17_dept_32

14:46:04 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6jy35hj5.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qkenn4h0.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=33717', 'data', 'file=/tmp/tmpjd45me00/6jy35hj5.json', 'init=/tmp/tmpjd45me00/qkenn4h0.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelyn7srnzp/prophet_model-20260803144604.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:04 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:04 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/o8jf2pr9.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/y7o2oh2k.json

Build prophet model for  store_17_dept_35
Build prophet model for  store_17_dept_36

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/85gduzg3.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7rjudchz.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=93500', 'data', 'file=/tmp/tmpjd45me00/85gduzg3.json', 'init=/tmp/tmpjd45me00/7rjudchz.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelifjf92fy/prophet_model-20260803144605.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:05 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:05 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/so4aysio.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/l2xc2l4z.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=51159', 'data', 'file=/tmp/tmpjd45me00/so4aysio.json', 'init=/tmp/tmpjd45me00/l2xc2l4z.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model02c6dnur/prophet_model-20260803144605.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:05 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:05 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_17_dept_38

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xohheidq.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ctjtvtj_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=52204', 'data', 'file=/tmp/tmpjd45me00/xohheidq.json', 'init=/tmp/tmpjd45me00/ctjtvtj_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_jgiw36k/prophet_model-20260803144606.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:06 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:06 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_17_dept_4

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/y57xzc39.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/eqkjiwwg.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=62268', 'data', 'file=/tmp/tmpjd45me00/y57xzc39.json', 'init=/tmp/tmpjd45me00/eqkjiwwg.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelkpyvwq8f/prophet_model-20260803144606.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:06 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_17_dept_40

14:46:06 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/52cqhnde.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4ep4ghaa.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=55367', 'data', 'file=/tmp/tmpjd45me00/52cqhnde.json', 'init=/tmp/tmpjd45me00/4ep4ghaa.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelxv5ndcu6/prophet_model-20260803144606.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:06 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:06 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_17_dept_42

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/j53iwfub.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6r9f5u98.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=26159', 'data', 'file=/tmp/tmpjd45me00/j53iwfub.json', 'init=/tmp/tmpjd45me00/6r9f5u98.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model74pukp4n/prophet_model-20260803144606.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:06 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:06 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_17_dept_44

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fl4nytof.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ldqjw23j.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=17493', 'data', 'file=/tmp/tmpjd45me00/fl4nytof.json', 'init=/tmp/tmpjd45me00/ldqjw23j.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model07mdspag/prophet_model-20260803144607.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:07 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:07 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_17_dept_46

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mea4qgw8.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/y5jhyy6a.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=21807', 'data', 'file=/tmp/tmpjd45me00/mea4qgw8.json', 'init=/tmp/tmpjd45me00/y5jhyy6a.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model876wpbq1/prophet_model-20260803144607.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:07 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:07 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_17_dept_48
Build prophet model for  store_17_dept_5

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zix4e6im.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4hfcwe3f.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=4206', 'data', 'file=/tmp/tmpjd45me00/zix4e6im.json', 'init=/tmp/tmpjd45me00/4hfcwe3f.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelz1520pmu/prophet_model-20260803144607.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:07 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:07 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ktcvb9zy.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/t6nnjetf.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=23247', 'data', 'file=/tmp/tmpjd45me00/ktcvb9zy.json', 'init=/tmp/tmpjd45me00/t6nnjetf.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelq6q66tpb/prophet_model-20260803144607.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:46:07 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_17_dept_51

14:46:08 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xrxrbbdo.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/87ktdtbu.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=45508', 'data', 'file=/tmp/tmpjd45me00/xrxrbbdo.json', 'init=/tmp/tmpjd45me00/87ktdtbu.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model4rdkcsve/prophet_model-20260803144608.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:08 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_17_dept_52

14:46:08 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_72st40w.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bon5xuj1.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=29300', 'data', 'file=/tmp/tmpjd45me00/_72st40w.json', 'init=/tmp/tmpjd45me00/bon5xuj1.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeltn9n0946/prophet_model-20260803144608.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:08 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:08 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/uwf6eo3w.json

Build prophet model for  store_17_dept_54
Build prophet model for  store_17_dept_55

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ijszwz53.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=7741', 'data', 'file=/tmp/tmpjd45me00/uwf6eo3w.json', 'init=/tmp/tmpjd45me00/ijszwz53.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeln3w65wc7/prophet_model-20260803144609.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:09 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:09 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vu3dz8_e.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/kd_sr1ij.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=84056', 'data', 'file=/tmp/tmpjd45me00/vu3dz8_e.json', 'init=/tmp/tmpjd45me00/kd_sr1ij.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelo7kvevpn/prophet_model-20260803144609.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:09 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:09 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_17_dept_56

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/liqlvbd8.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_kxhkeut.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=93059', 'data', 'file=/tmp/tmpjd45me00/liqlvbd8.json', 'init=/tmp/tmpjd45me00/_kxhkeut.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model513w4yje/prophet_model-20260803144609.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:09 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:09 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2zvyem63.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/g5dm2flh.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=44271', 'data', 'file=/tmp/tmpjd45me00/2zvyem63.json', 'init=/tmp/tmpjd45me00/g5dm2flh.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model6uwxjwfe/prophet_model-20260803144609.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:09 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_17_dept_58
Build prophet model for  store_17_dept_59

14:46:09 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/d83cj8kt.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6fgyygey.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=93278', 'data', 'file=/tmp/tmpjd45me00/d83cj8kt.json', 'init=/tmp/tmpjd45me00/6fgyygey.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model4pfzgm4x/prophet_model-20260803144609.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:09 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:09 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_17_dept_6
Build prophet model for  store_17_dept_60

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/oj85g52h.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6qzjanpx.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=58817', 'data', 'file=/tmp/tmpjd45me00/oj85g52h.json', 'init=/tmp/tmpjd45me00/6qzjanpx.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model2i31mnb6/prophet_model-20260803144609.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:09 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:10 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/w_zpshrx.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0ixjsvka.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=46460', 'data', 'file=/tmp/tmpjd45me00/w_zpshrx.json', 'init=/tmp/tmpjd45me00/0ixjsvka.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelbw6djd6p/prophet_model-20260803144610.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:10 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:10 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jxgijom0.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zvektfv6.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=94220', 'data', 'file=/tmp/tmpjd45me00/jxgijom0.json', 'init=/tmp/tmpjd45me00/zvektfv6.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelj1x8328e/prophet_model-20260803144610.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']

Build prophet model for  store_17_dept_67
Build prophet model for  store_17_dept_7

14:46:10 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:10 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/66p2pwp8.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zfiqwegj.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=99261', 'data', 'file=/tmp/tmpjd45me00/66p2pwp8.json', 'init=/tmp/tmpjd45me00/zfiqwegj.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelyrb1kp8p/prophet_model-20260803144610.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:10 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:10 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/g88b93sr.json

Build prophet model for  store_17_dept_71
Build prophet model for  store_17_dept_72

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bl2wqh0h.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=52710', 'data', 'file=/tmp/tmpjd45me00/g88b93sr.json', 'init=/tmp/tmpjd45me00/bl2wqh0h.json', 'output', 'file=/tmp/tmpjd45me00/prophet_models79un29e/prophet_model-20260803144610.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:10 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:10 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/tnbrdvdj.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4wwgabry.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=62005', 'data', 'file=/tmp/tmpjd45me00/tnbrdvdj.json', 'init=/tmp/tmpjd45me00/4wwgabry.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelv_o5psxb/prophet_model-20260803144610.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:10 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:10 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wywh5cvf.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ewqh5qsm.json

Build prophet model for  store_17_dept_74
Build prophet model for  store_17_dept_79

DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=67276', 'data', 'file=/tmp/tmpjd45me00/wywh5cvf.json', 'init=/tmp/tmpjd45me00/ewqh5qsm.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model9plc35d4/prophet_model-20260803144610.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:10 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:10 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/b0b_nt8v.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wcrg5hwk.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=58208', 'data', 'file=/tmp/tmpjd45me00/b0b_nt8v.json', 'init=/tmp/tmpjd45me00/wcrg5hwk.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelkk7fr30h/prophet_model-20260803144611.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:11 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:11 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_17_dept_8
Build prophet model for  store_17_dept_80

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5e11eqmw.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/auijr4sm.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=78087', 'data', 'file=/tmp/tmpjd45me00/5e11eqmw.json', 'init=/tmp/tmpjd45me00/auijr4sm.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model9ub8tbar/prophet_model-20260803144611.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:11 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:11 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/z040h47c.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/i8b9pgjf.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=90840', 'data', 'file=/tmp/tmpjd45me00/z040h47c.json', 'init=/tmp/tmpjd45me00/i8b9pgjf.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelb1d7nee1/prophet_model-20260803144611.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:11 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:11 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rnb0d539.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/27xapy7p.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=76838', 'data', 'file=/tmp/tmpjd45me00/rnb0d539.json', 'init=/tmp/tmpjd45me00/27xapy7p.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelfob8_z8i/prophet_model-20260803144611.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:11 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_17_dept_81
Build prophet model for  store_17_dept_82

14:46:11 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rtnoawua.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/znjn5yx4.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=68130', 'data', 'file=/tmp/tmpjd45me00/rtnoawua.json', 'init=/tmp/tmpjd45me00/znjn5yx4.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelsuk0l8j9/prophet_model-20260803144611.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:11 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_17_dept_83

14:46:12 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/n1aipdm3.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/n4m8wty9.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=49494', 'data', 'file=/tmp/tmpjd45me00/n1aipdm3.json', 'init=/tmp/tmpjd45me00/n4m8wty9.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeltrio6kmj/prophet_model-20260803144612.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:12 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:12 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/eavltwc0.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/a_4cv71e.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=2942', 'data', 'file=/tmp/tmpjd45me00/eavltwc0.json', 'init=/tmp/tmpjd45me00/a_4cv71e.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model1pi42_a2/prophet_model-20260803144612.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:12 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_17_dept_85
Build prophet model for  store_17_dept_87

14:46:12 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/nzncybww.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2wcrjzes.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=68561', 'data', 'file=/tmp/tmpjd45me00/nzncybww.json', 'init=/tmp/tmpjd45me00/2wcrjzes.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeln03czy8c/prophet_model-20260803144612.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:12 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:12 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_17_dept_9
Build prophet model for  store_17_dept_90

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/nzqkeihw.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/36mwjcup.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=55319', 'data', 'file=/tmp/tmpjd45me00/nzqkeihw.json', 'init=/tmp/tmpjd45me00/36mwjcup.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelbkgz7k57/prophet_model-20260803144612.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:12 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:12 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/iuby2uwi.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hcukup0g.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=81012', 'data', 'file=/tmp/tmpjd45me00/iuby2uwi.json', 'init=/tmp/tmpjd45me00/hcukup0g.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelggbot0xk/prophet_model-20260803144612.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:12 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:12 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_17_dept_91
Build prophet model for  store_17_dept_92

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/o4jlks_s.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qslq_p2d.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=99260', 'data', 'file=/tmp/tmpjd45me00/o4jlks_s.json', 'init=/tmp/tmpjd45me00/qslq_p2d.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeld5xsgnln/prophet_model-20260803144613.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:13 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:13 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/g09jp3pw.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/95hxzn2m.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=60214', 'data', 'file=/tmp/tmpjd45me00/g09jp3pw.json', 'init=/tmp/tmpjd45me00/95hxzn2m.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelapaslr16/prophet_model-20260803144613.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:13 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:13 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/auls391k.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/sd2iqt5_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=82468', 'data', 'file=/tmp/tmpjd45me00/auls391k.json', 'init=/tmp/tmpjd45me00/sd2iqt5_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelfozayk7j/prophet_model-20260803144613.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:13 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_17_dept_93
Build prophet model for  store_17_dept_95

14:46:13 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/43vp5czn.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/lekc0b2t.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=8104', 'data', 'file=/tmp/tmpjd45me00/43vp5czn.json', 'init=/tmp/tmpjd45me00/lekc0b2t.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modellcryw5nd/prophet_model-20260803144613.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:13 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:13 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_17_dept_97
Build prophet model for  store_18_dept_1

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/uxbhj2lo.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/nn95pn8k.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=58116', 'data', 'file=/tmp/tmpjd45me00/uxbhj2lo.json', 'init=/tmp/tmpjd45me00/nn95pn8k.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model53loshd1/prophet_model-20260803144613.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:13 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:13 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qgudkoqy.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/t9vr7kag.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=79798', 'data', 'file=/tmp/tmpjd45me00/qgudkoqy.json', 'init=/tmp/tmpjd45me00/t9vr7kag.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model2rf1vfxr/prophet_model-20260803144613.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:13 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_18_dept_10

14:46:14 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ux9kcwdx.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9x6dng49.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=76428', 'data', 'file=/tmp/tmpjd45me00/ux9kcwdx.json', 'init=/tmp/tmpjd45me00/9x6dng49.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeltmyssnbr/prophet_model-20260803144614.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:14 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:14 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/odtrvb1p.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6rv54bl_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=48590', 'data', 'file=/tmp/tmpjd45me00/odtrvb1p.json', 'init=/tmp/tmpjd45me00/6rv54bl_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelycd5gf55/prophet_model-20260803144614.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']

Build prophet model for  store_18_dept_11
Build prophet model for  store_18_dept_12

14:46:14 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:14 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/t9s4r9ow.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pq2fejrb.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=92353', 'data', 'file=/tmp/tmpjd45me00/t9s4r9ow.json', 'init=/tmp/tmpjd45me00/pq2fejrb.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeluhi2bczj/prophet_model-20260803144614.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:14 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:14 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dovcuq39.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0krm7dbe.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=21910', 'data', 'file=/tmp/tmpjd45me00/dovcuq39.json', 'init=/tmp/tmpjd45me00/0krm7dbe.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model6zwwlu3u/prophet_model-20260803144614.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:14 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_18_dept_13
Build prophet model for  store_18_dept_14

14:46:14 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/kemrh_45.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/uo_w9jl_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=49174', 'data', 'file=/tmp/tmpjd45me00/kemrh_45.json', 'init=/tmp/tmpjd45me00/uo_w9jl_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model7f_u9ebi/prophet_model-20260803144615.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:15 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_18_dept_16

14:46:15 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pmq4wh9r.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/oadqhydu.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=69258', 'data', 'file=/tmp/tmpjd45me00/pmq4wh9r.json', 'init=/tmp/tmpjd45me00/oadqhydu.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model1cnxh1ca/prophet_model-20260803144615.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:15 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:15 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_18_dept_17
Build prophet model for  store_18_dept_18

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/orzpr1s7.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0wq8cg2l.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=15453', 'data', 'file=/tmp/tmpjd45me00/orzpr1s7.json', 'init=/tmp/tmpjd45me00/0wq8cg2l.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modellx8l8qcy/prophet_model-20260803144615.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:15 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:15 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/t6jigfnh.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/nxno381_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=96356', 'data', 'file=/tmp/tmpjd45me00/t6jigfnh.json', 'init=/tmp/tmpjd45me00/nxno381_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_models0uhqy8y/prophet_model-20260803144615.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:15 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:15 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/f_cw026c.json

Build prophet model for  store_18_dept_19
Build prophet model for  store_18_dept_2

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/f39r1204.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=32001', 'data', 'file=/tmp/tmpjd45me00/f_cw026c.json', 'init=/tmp/tmpjd45me00/f39r1204.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelvzxch0h0/prophet_model-20260803144615.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:15 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:16 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/75dqmazk.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/e4ut70m5.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=74299', 'data', 'file=/tmp/tmpjd45me00/75dqmazk.json', 'init=/tmp/tmpjd45me00/e4ut70m5.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelzttkz9ua/prophet_model-20260803144616.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:16 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:16 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_18_dept_20
Build prophet model for  store_18_dept_21

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wwjvwybz.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xjz4jcrx.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=47467', 'data', 'file=/tmp/tmpjd45me00/wwjvwybz.json', 'init=/tmp/tmpjd45me00/xjz4jcrx.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelu3qt89vj/prophet_model-20260803144616.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:16 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:16 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/it803i44.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/c8mlwtd9.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=93975', 'data', 'file=/tmp/tmpjd45me00/it803i44.json', 'init=/tmp/tmpjd45me00/c8mlwtd9.json', 'output', 'file=/tmp/tmpjd45me00/prophet_models27jfnk3/prophet_model-20260803144616.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:16 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:16 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ozekx9a4.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vk3epjsl.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=62209', 'data', 'file=/tmp/tmpjd45me00/ozekx9a4.json', 'init=/tmp/tmpjd45me00/vk3epjsl.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model3wgri472/prophet_model-20260803144616.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:16 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_18_dept_22
Build prophet model for  store_18_dept_23

14:46:16 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mhpxbe2i.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zmiz5qqv.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=24389', 'data', 'file=/tmp/tmpjd45me00/mhpxbe2i.json', 'init=/tmp/tmpjd45me00/zmiz5qqv.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelmi75jxjo/prophet_model-20260803144616.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:16 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:16 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6242_ueb.json

Build prophet model for  store_18_dept_24
Build prophet model for  store_18_dept_25

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/kwkpilx8.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=51917', 'data', 'file=/tmp/tmpjd45me00/6242_ueb.json', 'init=/tmp/tmpjd45me00/kwkpilx8.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model3w8cc5v5/prophet_model-20260803144616.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:16 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:17 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wu_28koj.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rv5tj9gg.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=57307', 'data', 'file=/tmp/tmpjd45me00/wu_28koj.json', 'init=/tmp/tmpjd45me00/rv5tj9gg.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelh9cb2_5v/prophet_model-20260803144617.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:17 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:17 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_18_dept_26
Build prophet model for  store_18_dept_27

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/p_fob9bl.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ky69zjvb.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=38527', 'data', 'file=/tmp/tmpjd45me00/p_fob9bl.json', 'init=/tmp/tmpjd45me00/ky69zjvb.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model0yj_iggf/prophet_model-20260803144617.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:17 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:17 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/oteqwise.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xjyodpsd.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=49037', 'data', 'file=/tmp/tmpjd45me00/oteqwise.json', 'init=/tmp/tmpjd45me00/xjyodpsd.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelkqxq4gm1/prophet_model-20260803144617.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:17 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:17 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_18_dept_28
Build prophet model for  store_18_dept_29

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1cupiaf6.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hpo1kq4k.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=95660', 'data', 'file=/tmp/tmpjd45me00/1cupiaf6.json', 'init=/tmp/tmpjd45me00/hpo1kq4k.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelh2ml8fu3/prophet_model-20260803144617.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:17 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:17 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/00ha9lwh.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/y_g8dj2p.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=49966', 'data', 'file=/tmp/tmpjd45me00/00ha9lwh.json', 'init=/tmp/tmpjd45me00/y_g8dj2p.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelat9jr0h6/prophet_model-20260803144617.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:17 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:18 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xs04r8zv.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zkn6wwq7.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=98992', 'data', 'file=/tmp/tmpjd45me00/xs04r8zv.json', 'init=/tmp/tmpjd45me00/zkn6wwq7.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelvstjtpgj/prophet_model-20260803144618.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:18 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_18_dept_3
Build prophet model for  store_18_dept_30

14:46:18 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ahlq0rfc.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/m8ibi9o9.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=61201', 'data', 'file=/tmp/tmpjd45me00/ahlq0rfc.json', 'init=/tmp/tmpjd45me00/m8ibi9o9.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model1xorcgha/prophet_model-20260803144618.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:18 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_18_dept_31

14:46:18 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7wewd9ay.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0lcj2r3b.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=83867', 'data', 'file=/tmp/tmpjd45me00/7wewd9ay.json', 'init=/tmp/tmpjd45me00/0lcj2r3b.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelt5q67vyz/prophet_model-20260803144618.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:18 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:18 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_18_dept_32
Build prophet model for  store_18_dept_33

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/d1dprj74.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/c4kcn8ci.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=39571', 'data', 'file=/tmp/tmpjd45me00/d1dprj74.json', 'init=/tmp/tmpjd45me00/c4kcn8ci.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model4nqg06_u/prophet_model-20260803144618.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:18 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:18 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xm4kylb9.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/oy0h8kzx.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=70620', 'data', 'file=/tmp/tmpjd45me00/xm4kylb9.json', 'init=/tmp/tmpjd45me00/oy0h8kzx.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_okz2_e3/prophet_model-20260803144619.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:19 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:19 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_18_dept_34

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rxbzwbea.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/13apqys0.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=33746', 'data', 'file=/tmp/tmpjd45me00/rxbzwbea.json', 'init=/tmp/tmpjd45me00/13apqys0.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelp1vot7gf/prophet_model-20260803144619.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:19 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:19 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_18_dept_35

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/z2z26nin.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qwz7swxg.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=44732', 'data', 'file=/tmp/tmpjd45me00/z2z26nin.json', 'init=/tmp/tmpjd45me00/qwz7swxg.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelfp9r8zy9/prophet_model-20260803144619.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:19 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:19 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_18_dept_36

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4_epadr3.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5w1411hz.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=48432', 'data', 'file=/tmp/tmpjd45me00/4_epadr3.json', 'init=/tmp/tmpjd45me00/5w1411hz.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelz9sxdf7y/prophet_model-20260803144619.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:19 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:19 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_18_dept_38

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/syl53ti6.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8crtuu0z.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=71387', 'data', 'file=/tmp/tmpjd45me00/syl53ti6.json', 'init=/tmp/tmpjd45me00/8crtuu0z.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model4cbn8oj3/prophet_model-20260803144620.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:20 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:20 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_18_dept_4

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rsfl4vl9.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zpazrio2.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=21777', 'data', 'file=/tmp/tmpjd45me00/rsfl4vl9.json', 'init=/tmp/tmpjd45me00/zpazrio2.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelmmwr7no4/prophet_model-20260803144620.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:20 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:20 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_18_dept_40

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zk34v1m4.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8w09l3c5.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=66162', 'data', 'file=/tmp/tmpjd45me00/zk34v1m4.json', 'init=/tmp/tmpjd45me00/8w09l3c5.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_c47fh7k/prophet_model-20260803144620.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:20 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:20 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_18_dept_41

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/spn82ujb.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/lgo7ak_d.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=97338', 'data', 'file=/tmp/tmpjd45me00/spn82ujb.json', 'init=/tmp/tmpjd45me00/lgo7ak_d.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model79em740t/prophet_model-20260803144620.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:20 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:20 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_18_dept_42
Build prophet model for  store_18_dept_44

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/cb2le7vg.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/b7c78v0g.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=97700', 'data', 'file=/tmp/tmpjd45me00/cb2le7vg.json', 'init=/tmp/tmpjd45me00/b7c78v0g.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model3gxhro_l/prophet_model-20260803144621.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:21 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:21 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9lcpvkh4.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1006peoi.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=29915', 'data', 'file=/tmp/tmpjd45me00/9lcpvkh4.json', 'init=/tmp/tmpjd45me00/1006peoi.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelnx3hf1wf/prophet_model-20260803144621.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:21 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:21 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_18_dept_46

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/e5pn9abq.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/95jv37yh.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=91409', 'data', 'file=/tmp/tmpjd45me00/e5pn9abq.json', 'init=/tmp/tmpjd45me00/95jv37yh.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model0x9fnmdq/prophet_model-20260803144621.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:21 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:21 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_18_dept_49

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/f1c9o9ub.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9vd44zjz.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=69899', 'data', 'file=/tmp/tmpjd45me00/f1c9o9ub.json', 'init=/tmp/tmpjd45me00/9vd44zjz.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model2e3cpa0n/prophet_model-20260803144621.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:21 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:21 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_18_dept_5
Build prophet model for  store_18_dept_52

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/j_2nduo7.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pf5u9hdg.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=61094', 'data', 'file=/tmp/tmpjd45me00/j_2nduo7.json', 'init=/tmp/tmpjd45me00/pf5u9hdg.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelc3x6ayr9/prophet_model-20260803144622.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:22 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:22 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5po0dm4k.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hzp6r180.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=77585', 'data', 'file=/tmp/tmpjd45me00/5po0dm4k.json', 'init=/tmp/tmpjd45me00/hzp6r180.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelnxocd1zh/prophet_model-20260803144622.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:22 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:22 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/evaj0wuu.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/k843ehut.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=10118', 'data', 'file=/tmp/tmpjd45me00/evaj0wuu.json', 'init=/tmp/tmpjd45me00/k843ehut.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model9s0udwav/prophet_model-20260803144622.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']

Build prophet model for  store_18_dept_54
Build prophet model for  store_18_dept_55

14:46:22 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:22 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/yq2cdmaj.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wexdkq8y.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=68951', 'data', 'file=/tmp/tmpjd45me00/yq2cdmaj.json', 'init=/tmp/tmpjd45me00/wexdkq8y.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeljt9wqato/prophet_model-20260803144622.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:22 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:22 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dx7mc707.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/psfxt92q.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=13966', 'data', 'file=/tmp/tmpjd45me00/dx7mc707.json', 'init=/tmp/tmpjd45me00/psfxt92q.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelxff816yp/prophet_model-20260803144622.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:22 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_18_dept_56
Build prophet model for  store_18_dept_58

14:46:22 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hc9hv6o4.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dvazmshu.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=4844', 'data', 'file=/tmp/tmpjd45me00/hc9hv6o4.json', 'init=/tmp/tmpjd45me00/dvazmshu.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelx9t3r3sw/prophet_model-20260803144622.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:22 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_18_dept_59

14:46:23 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/yhay0wqo.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jtq4c8g7.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=61660', 'data', 'file=/tmp/tmpjd45me00/yhay0wqo.json', 'init=/tmp/tmpjd45me00/jtq4c8g7.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelhb1y0rrj/prophet_model-20260803144623.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:23 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:23 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qjaum_uu.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rzlcqfhq.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=7585', 'data', 'file=/tmp/tmpjd45me00/qjaum_uu.json', 'init=/tmp/tmpjd45me00/rzlcqfhq.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelu6fzn8as/prophet_model-20260803144623.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:23 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_18_dept_6
Build prophet model for  store_18_dept_67

14:46:23 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ebf1e_jd.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gg_xf2pt.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=2095', 'data', 'file=/tmp/tmpjd45me00/ebf1e_jd.json', 'init=/tmp/tmpjd45me00/gg_xf2pt.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelrnea4_fk/prophet_model-20260803144623.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:23 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:23 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/45_m3yk5.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/g7_jk_lc.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=65004', 'data', 'file=/tmp/tmpjd45me00/45_m3yk5.json', 'init=/tmp/tmpjd45me00/g7_jk_lc.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelt6_r0qcq/prophet_model-20260803144623.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:23 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_18_dept_7
Build prophet model for  store_18_dept_71

14:46:23 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/r_xop9jr.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xpehi3c5.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=79823', 'data', 'file=/tmp/tmpjd45me00/r_xop9jr.json', 'init=/tmp/tmpjd45me00/xpehi3c5.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model7jnj51ah/prophet_model-20260803144623.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:24 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:24 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/e1zpbsrb.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/u0thhl08.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=55969', 'data', 'file=/tmp/tmpjd45me00/e1zpbsrb.json', 'init=/tmp/tmpjd45me00/u0thhl08.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model8x0zsukw/prophet_model-20260803144624.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:24 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_18_dept_72
Build prophet model for  store_18_dept_74

14:46:24 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_3rx2sx8.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/op5242gi.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=82395', 'data', 'file=/tmp/tmpjd45me00/_3rx2sx8.json', 'init=/tmp/tmpjd45me00/op5242gi.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelpiu8u6_k/prophet_model-20260803144624.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:24 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:24 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/l3blt0wc.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rjottoyc.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=47269', 'data', 'file=/tmp/tmpjd45me00/l3blt0wc.json', 'init=/tmp/tmpjd45me00/rjottoyc.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelx_j9p11s/prophet_model-20260803144624.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:24 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_18_dept_79
Build prophet model for  store_18_dept_8

14:46:24 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ymk2g70e.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/h6op_rgj.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=94988', 'data', 'file=/tmp/tmpjd45me00/ymk2g70e.json', 'init=/tmp/tmpjd45me00/h6op_rgj.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelew78s45b/prophet_model-20260803144624.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:24 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:24 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_18_dept_81

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/v013axfn.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/t8sl275u.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=76868', 'data', 'file=/tmp/tmpjd45me00/v013axfn.json', 'init=/tmp/tmpjd45me00/t8sl275u.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modela1gmdtxl/prophet_model-20260803144624.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:24 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:24 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/afc224s3.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/uq2_tz_h.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=14591', 'data', 'file=/tmp/tmpjd45me00/afc224s3.json', 'init=/tmp/tmpjd45me00/uq2_tz_h.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modellek_utud/prophet_model-20260803144625.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:25 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_18_dept_82
Build prophet model for  store_18_dept_83

14:46:25 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_slrymtp.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/atlytsd0.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=62733', 'data', 'file=/tmp/tmpjd45me00/_slrymtp.json', 'init=/tmp/tmpjd45me00/atlytsd0.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelffublpjj/prophet_model-20260803144625.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:25 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_18_dept_85

14:46:25 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/d1k5ojbi.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/a63lp3_0.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=67146', 'data', 'file=/tmp/tmpjd45me00/d1k5ojbi.json', 'init=/tmp/tmpjd45me00/a63lp3_0.json', 'output', 'file=/tmp/tmpjd45me00/prophet_models11mlhvi/prophet_model-20260803144625.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:25 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:25 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0p7yndmo.json

Build prophet model for  store_18_dept_87
Build prophet model for  store_18_dept_9

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/irddz_zt.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=15765', 'data', 'file=/tmp/tmpjd45me00/0p7yndmo.json', 'init=/tmp/tmpjd45me00/irddz_zt.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelkf8usp3_/prophet_model-20260803144625.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:25 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:25 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jb23goof.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/thheh668.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=22174', 'data', 'file=/tmp/tmpjd45me00/jb23goof.json', 'init=/tmp/tmpjd45me00/thheh668.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model4t5i9qod/prophet_model-20260803144625.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:25 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_18_dept_90

14:46:26 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/z35qojoe.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1skpytp5.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=90701', 'data', 'file=/tmp/tmpjd45me00/z35qojoe.json', 'init=/tmp/tmpjd45me00/1skpytp5.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelpu8jalhr/prophet_model-20260803144626.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:26 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:26 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_18_dept_91
Build prophet model for  store_18_dept_92

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7rdlyh04.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9yfvzmts.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=61464', 'data', 'file=/tmp/tmpjd45me00/7rdlyh04.json', 'init=/tmp/tmpjd45me00/9yfvzmts.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model197ayold/prophet_model-20260803144626.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:26 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:26 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mw_m8j1b.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ps5ts0fq.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=8542', 'data', 'file=/tmp/tmpjd45me00/mw_m8j1b.json', 'init=/tmp/tmpjd45me00/ps5ts0fq.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model9o0znmrv/prophet_model-20260803144626.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:26 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_18_dept_93

14:46:26 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/52l0yo0z.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/g98i1dkn.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=74645', 'data', 'file=/tmp/tmpjd45me00/52l0yo0z.json', 'init=/tmp/tmpjd45me00/g98i1dkn.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelkpuny2yd/prophet_model-20260803144626.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:26 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:27 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_18_dept_95

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ik5h2x0d.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3912kndf.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=71161', 'data', 'file=/tmp/tmpjd45me00/ik5h2x0d.json', 'init=/tmp/tmpjd45me00/3912kndf.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeltff58kog/prophet_model-20260803144627.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:27 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_18_dept_97

14:46:27 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2tmbw0ic.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/h_irca6e.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=14361', 'data', 'file=/tmp/tmpjd45me00/2tmbw0ic.json', 'init=/tmp/tmpjd45me00/h_irca6e.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeluc9jwmnx/prophet_model-20260803144627.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:27 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:27 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/cx27i7ix.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ppzw1k2p.json
DEBUG:cmdstanpy:idx 0

Build prophet model for  store_19_dept_1
Build prophet model for  store_19_dept_10

DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=94541', 'data', 'file=/tmp/tmpjd45me00/cx27i7ix.json', 'init=/tmp/tmpjd45me00/ppzw1k2p.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_rangta7/prophet_model-20260803144627.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:27 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:28 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/f1h4rhb1.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/lp7aeago.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=47457', 'data', 'file=/tmp/tmpjd45me00/f1h4rhb1.json', 'init=/tmp/tmpjd45me00/lp7aeago.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeljf9_yljh/prophet_model-20260803144628.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:28 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:28 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ybmjvhpb.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bnoe145u.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=27860', 'data', 'file=/tmp/tmpjd45me00/ybmjvhpb.json', 'init=/tmp/tmpjd45me00/bnoe145u.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model0ajvf446/prophet_model-20260803144628.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:28 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_19_dept_11
Build prophet model for  store_19_dept_12

14:46:28 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/spx96uh7.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/geavdmx8.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=58021', 'data', 'file=/tmp/tmpjd45me00/spx96uh7.json', 'init=/tmp/tmpjd45me00/geavdmx8.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model7dn28q1c/prophet_model-20260803144628.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:28 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_19_dept_13

14:46:28 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jav73q4z.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/15orabec.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=28361', 'data', 'file=/tmp/tmpjd45me00/jav73q4z.json', 'init=/tmp/tmpjd45me00/15orabec.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_i90kp25/prophet_model-20260803144628.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:28 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:28 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xwy8tsc3.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xjju92e7.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=71265', 'data', 'file=/tmp/tmpjd45me00/xwy8tsc3.json', 'init=/tmp/tmpjd45me00/xjju92e7.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelopdqa0ba/prophet_model-20260803144629.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:29 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_19_dept_14
Build prophet model for  store_19_dept_16

14:46:29 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zby_l8s0.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/uap9uq_i.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=64929', 'data', 'file=/tmp/tmpjd45me00/zby_l8s0.json', 'init=/tmp/tmpjd45me00/uap9uq_i.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelm10cbpv7/prophet_model-20260803144629.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:29 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:29 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/lssvp1lc.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/er2vvko1.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=61533', 'data', 'file=/tmp/tmpjd45me00/lssvp1lc.json', 'init=/tmp/tmpjd45me00/er2vvko1.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_3ibit0v/prophet_model-20260803144629.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:46:29 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_19_dept_17
Build prophet model for  store_19_dept_18

14:46:30 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ttx2ut7l.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ffm39od3.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=28126', 'data', 'file=/tmp/tmpjd45me00/ttx2ut7l.json', 'init=/tmp/tmpjd45me00/ffm39od3.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model4iw4x1jy/prophet_model-20260803144630.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:30 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:30 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/v1owrlym.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1r7ome0o.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=96671', 'data', 'file=/tmp/tmpjd45me00/v1owrlym.json', 'init=/tmp/tmpjd45me00/1r7ome0o.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelmgan17ut/prophet_model-20260803144630.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:30 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_19_dept_2
Build prophet model for  store_19_dept_20

14:46:30 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3v0cg7x_.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0ls4kp55.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=45564', 'data', 'file=/tmp/tmpjd45me00/3v0cg7x_.json', 'init=/tmp/tmpjd45me00/0ls4kp55.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelqs4puuq9/prophet_model-20260803144630.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:30 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_19_dept_21

14:46:30 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6tf84_mc.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/93n6sq1i.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=54115', 'data', 'file=/tmp/tmpjd45me00/6tf84_mc.json', 'init=/tmp/tmpjd45me00/93n6sq1i.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelbmnhga15/prophet_model-20260803144630.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:31 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:31 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/w5u926yu.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3d1_0z0q.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=54398', 'data', 'file=/tmp/tmpjd45me00/w5u926yu.json', 'init=/tmp/tmpjd45me00/3d1_0z0q.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model0hxunsf4/prophet_model-20260803144631.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:31 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_19_dept_22
Build prophet model for  store_19_dept_23

14:46:31 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zkm42l0k.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/oxg54lqz.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=82407', 'data', 'file=/tmp/tmpjd45me00/zkm42l0k.json', 'init=/tmp/tmpjd45me00/oxg54lqz.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeld_t8hbu9/prophet_model-20260803144631.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:31 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:31 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jpli615g.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bmhy0rmr.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=51710', 'data', 'file=/tmp/tmpjd45me00/jpli615g.json', 'init=/tmp/tmpjd45me00/bmhy0rmr.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeltuiiovx6/prophet_model-20260803144631.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:31 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_19_dept_24
Build prophet model for  store_19_dept_25

14:46:31 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ogdir1u2.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2tnus1l7.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=49672', 'data', 'file=/tmp/tmpjd45me00/ogdir1u2.json', 'init=/tmp/tmpjd45me00/2tnus1l7.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelhbeil479/prophet_model-20260803144631.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:31 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:31 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_19_dept_26
Build prophet model for  store_19_dept_27

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gkq9hyvg.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ownuta5l.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=28894', 'data', 'file=/tmp/tmpjd45me00/gkq9hyvg.json', 'init=/tmp/tmpjd45me00/ownuta5l.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model4gyj5b53/prophet_model-20260803144631.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:31 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:31 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/cc58_y04.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/j7oh1jyt.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=66785', 'data', 'file=/tmp/tmpjd45me00/cc58_y04.json', 'init=/tmp/tmpjd45me00/j7oh1jyt.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelgx2ed0u_/prophet_model-20260803144632.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:32 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:32 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_19_dept_28

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/09n4idw8.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mlo6jw1w.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=29822', 'data', 'file=/tmp/tmpjd45me00/09n4idw8.json', 'init=/tmp/tmpjd45me00/mlo6jw1w.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelf5dzxd08/prophet_model-20260803144632.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:32 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:32 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_19_dept_29

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zcpgdhxq.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/v4xjjgwl.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=57447', 'data', 'file=/tmp/tmpjd45me00/zcpgdhxq.json', 'init=/tmp/tmpjd45me00/v4xjjgwl.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelx8x6acsz/prophet_model-20260803144632.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:32 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:32 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_19_dept_3

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/yync6nd9.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bss0_n81.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=94391', 'data', 'file=/tmp/tmpjd45me00/yync6nd9.json', 'init=/tmp/tmpjd45me00/bss0_n81.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model5503no_h/prophet_model-20260803144632.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:32 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_19_dept_30

14:46:33 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/q60n_cui.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5oequhqt.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=91730', 'data', 'file=/tmp/tmpjd45me00/q60n_cui.json', 'init=/tmp/tmpjd45me00/5oequhqt.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelny0lm_b0/prophet_model-20260803144633.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:33 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:33 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_19_dept_31

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ls60b6g7.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vuu2yqwa.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=42067', 'data', 'file=/tmp/tmpjd45me00/ls60b6g7.json', 'init=/tmp/tmpjd45me00/vuu2yqwa.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model0iczxbvp/prophet_model-20260803144633.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:33 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:33 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_19_dept_32

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xlyt_lrn.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5ww0xk89.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=88761', 'data', 'file=/tmp/tmpjd45me00/xlyt_lrn.json', 'init=/tmp/tmpjd45me00/5ww0xk89.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_3tgic8u/prophet_model-20260803144633.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:33 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:33 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_19_dept_33

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/o5d816i7.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/s1mojh6o.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=15652', 'data', 'file=/tmp/tmpjd45me00/o5d816i7.json', 'init=/tmp/tmpjd45me00/s1mojh6o.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelb3v1_wkq/prophet_model-20260803144634.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:34 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_19_dept_34

14:46:34 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/29vn1qg6.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/26cu_8vb.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=31455', 'data', 'file=/tmp/tmpjd45me00/29vn1qg6.json', 'init=/tmp/tmpjd45me00/26cu_8vb.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeluc192d1c/prophet_model-20260803144634.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:34 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:34 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_19_dept_35

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bdrbbe9p.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5rd_3clw.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=6110', 'data', 'file=/tmp/tmpjd45me00/bdrbbe9p.json', 'init=/tmp/tmpjd45me00/5rd_3clw.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelx0j7gpqm/prophet_model-20260803144634.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:34 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:34 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_19_dept_36
Build prophet model for  store_19_dept_37

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/w2lwmhhb.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/c1p6v1pg.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=54119', 'data', 'file=/tmp/tmpjd45me00/w2lwmhhb.json', 'init=/tmp/tmpjd45me00/c1p6v1pg.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modela265stjy/prophet_model-20260803144634.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:34 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:34 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/i4d98w6i.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4iowgh54.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=93570', 'data', 'file=/tmp/tmpjd45me00/i4d98w6i.json', 'init=/tmp/tmpjd45me00/4iowgh54.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model4avzxejo/prophet_model-20260803144635.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:35 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:35 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ykieuuzg.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5y56vywk.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=38014', 'data', 'file=/tmp/tmpjd45me00/ykieuuzg.json', 'init=/tmp/tmpjd45me00/5y56vywk.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeliojwh2qp/prophet_model-20260803144635.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:35 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_19_dept_38
Build prophet model for  store_19_dept_4

14:46:35 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4grox69x.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ejm275go.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=46468', 'data', 'file=/tmp/tmpjd45me00/4grox69x.json', 'init=/tmp/tmpjd45me00/ejm275go.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model9e79515k/prophet_model-20260803144635.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:35 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:35 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_19_dept_40
Build prophet model for  store_19_dept_41

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/orga0f4d.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xe3w4pu_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=95789', 'data', 'file=/tmp/tmpjd45me00/orga0f4d.json', 'init=/tmp/tmpjd45me00/xe3w4pu_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelcowuo80c/prophet_model-20260803144635.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:35 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:35 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1cga_div.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/j2a_vht5.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=52623', 'data', 'file=/tmp/tmpjd45me00/1cga_div.json', 'init=/tmp/tmpjd45me00/j2a_vht5.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model5x6xbqcb/prophet_model-20260803144635.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:35 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:35 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_19_dept_42
Build prophet model for  store_19_dept_44

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/s5r1ro6n.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/d02_a3_d.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=59435', 'data', 'file=/tmp/tmpjd45me00/s5r1ro6n.json', 'init=/tmp/tmpjd45me00/d02_a3_d.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model6go2hm58/prophet_model-20260803144635.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:35 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:36 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7r3vfmyd.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/e7xbk7kb.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=97833', 'data', 'file=/tmp/tmpjd45me00/7r3vfmyd.json', 'init=/tmp/tmpjd45me00/e7xbk7kb.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelaz6d7akb/prophet_model-20260803144636.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:36 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:36 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/x0d918f_.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/v1njzhjc.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=28357', 'data', 'file=/tmp/tmpjd45me00/x0d918f_.json', 'init=/tmp/tmpjd45me00/v1njzhjc.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modellei3h9s0/prophet_model-20260803144636.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:36 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_19_dept_46
Build prophet model for  store_19_dept_49

14:46:36 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/yc79cw2t.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/p_01xbw7.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=46670', 'data', 'file=/tmp/tmpjd45me00/yc79cw2t.json', 'init=/tmp/tmpjd45me00/p_01xbw7.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modela0f7czds/prophet_model-20260803144636.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:36 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_19_dept_5

14:46:36 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dbfd72ce.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/u9qi64h5.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=31055', 'data', 'file=/tmp/tmpjd45me00/dbfd72ce.json', 'init=/tmp/tmpjd45me00/u9qi64h5.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelggknfj46/prophet_model-20260803144636.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:36 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:36 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/asb5ikom.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/uciij9p7.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=54798', 'data', 'file=/tmp/tmpjd45me00/asb5ikom.json', 'init=/tmp/tmpjd45me00/uciij9p7.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelg0wo2s0n/prophet_model-20260803144637.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:37 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_19_dept_50
Build prophet model for  store_19_dept_52

14:46:37 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/71r0ozzu.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/s_i_7442.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=48914', 'data', 'file=/tmp/tmpjd45me00/71r0ozzu.json', 'init=/tmp/tmpjd45me00/s_i_7442.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelv0qoerzb/prophet_model-20260803144637.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:37 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:37 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_19_dept_54
Build prophet model for  store_19_dept_55

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/c2zxm9p6.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hkav9lo7.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=35539', 'data', 'file=/tmp/tmpjd45me00/c2zxm9p6.json', 'init=/tmp/tmpjd45me00/hkav9lo7.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeld6_wbtnc/prophet_model-20260803144637.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:37 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:37 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_fbhq6hj.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wtimvfbj.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=6716', 'data', 'file=/tmp/tmpjd45me00/_fbhq6hj.json', 'init=/tmp/tmpjd45me00/wtimvfbj.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelo4d7vj9v/prophet_model-20260803144637.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:37 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:37 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/poqblbf7.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/sn8rgvps.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=34552', 'data', 'file=/tmp/tmpjd45me00/poqblbf7.json', 'init=/tmp/tmpjd45me00/sn8rgvps.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelze2z9si_/prophet_model-20260803144637.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:37 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_19_dept_56
Build prophet model for  store_19_dept_58

14:46:37 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5dioqjf2.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2qjy4ru7.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=55567', 'data', 'file=/tmp/tmpjd45me00/5dioqjf2.json', 'init=/tmp/tmpjd45me00/2qjy4ru7.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelf5ngkjj6/prophet_model-20260803144637.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:37 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_19_dept_59

14:46:38 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/oc5zc7i4.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/otw01f0r.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=27107', 'data', 'file=/tmp/tmpjd45me00/oc5zc7i4.json', 'init=/tmp/tmpjd45me00/otw01f0r.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelu4dmaih3/prophet_model-20260803144638.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:38 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:38 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/emaf07ym.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/afm6bu8f.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=94226', 'data', 'file=/tmp/tmpjd45me00/emaf07ym.json', 'init=/tmp/tmpjd45me00/afm6bu8f.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelivcjjotw/prophet_model-20260803144638.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:38 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:38 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_19_dept_6
Build prophet model for  store_19_dept_60

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_qs0_gkn.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/d3cnpr6w.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=37550', 'data', 'file=/tmp/tmpjd45me00/_qs0_gkn.json', 'init=/tmp/tmpjd45me00/d3cnpr6w.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model13ijkr6h/prophet_model-20260803144638.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:38 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:38 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mfp436he.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ggj2hbq7.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=54265', 'data', 'file=/tmp/tmpjd45me00/mfp436he.json', 'init=/tmp/tmpjd45me00/ggj2hbq7.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model45ubxfru/prophet_model-20260803144638.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:38 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_19_dept_67
Build prophet model for  store_19_dept_7

14:46:38 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rkptnaat.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/m4mku16p.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=4908', 'data', 'file=/tmp/tmpjd45me00/rkptnaat.json', 'init=/tmp/tmpjd45me00/m4mku16p.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeldbildg4n/prophet_model-20260803144638.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:38 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:38 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/epeo6v_f.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2_fnx3go.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=16177', 'data', 'file=/tmp/tmpjd45me00/epeo6v_f.json', 'init=/tmp/tmpjd45me00/2_fnx3go.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelsh5ryg90/prophet_model-20260803144638.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:38 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_19_dept_71
Build prophet model for  store_19_dept_72

14:46:38 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7z_k6a1j.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/v3ml1_bf.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=45362', 'data', 'file=/tmp/tmpjd45me00/7z_k6a1j.json', 'init=/tmp/tmpjd45me00/v3ml1_bf.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelojfk7_r1/prophet_model-20260803144639.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:39 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:39 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_19_dept_74
Build prophet model for  store_19_dept_79

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/oq7h078s.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4qotqzxs.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=213', 'data', 'file=/tmp/tmpjd45me00/oq7h078s.json', 'init=/tmp/tmpjd45me00/4qotqzxs.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelpupjln6r/prophet_model-20260803144639.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:39 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:39 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0sv77k0s.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mz241ed3.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=15359', 'data', 'file=/tmp/tmpjd45me00/0sv77k0s.json', 'init=/tmp/tmpjd45me00/mz241ed3.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model1mt5d8no/prophet_model-20260803144639.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:39 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:39 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/st5_7f53.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7ve5mknr.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=58515', 'data', 'file=/tmp/tmpjd45me00/st5_7f53.json', 'init=/tmp/tmpjd45me00/7ve5mknr.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelpe7wr4pr/prophet_model-20260803144639.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:39 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_19_dept_8
Build prophet model for  store_19_dept_80

14:46:39 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gbwl7f_4.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ln6tegun.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=83785', 'data', 'file=/tmp/tmpjd45me00/gbwl7f_4.json', 'init=/tmp/tmpjd45me00/ln6tegun.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelp9h2vfuj/prophet_model-20260803144639.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:39 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:39 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_and8siy.json

Build prophet model for  store_19_dept_81
Build prophet model for  store_19_dept_82

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/tztrxugq.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=84607', 'data', 'file=/tmp/tmpjd45me00/_and8siy.json', 'init=/tmp/tmpjd45me00/tztrxugq.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model8cq3j4s3/prophet_model-20260803144639.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:39 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:40 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/m6wh_2cc.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pzbmvrk6.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=67286', 'data', 'file=/tmp/tmpjd45me00/m6wh_2cc.json', 'init=/tmp/tmpjd45me00/pzbmvrk6.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelwbtvngxi/prophet_model-20260803144640.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:40 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:40 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6v8s_qse.json

Build prophet model for  store_19_dept_83
Build prophet model for  store_19_dept_85

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/e_ezdjz0.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=21791', 'data', 'file=/tmp/tmpjd45me00/6v8s_qse.json', 'init=/tmp/tmpjd45me00/e_ezdjz0.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelvna_c6dy/prophet_model-20260803144640.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:40 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:40 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ro0n4y9u.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/iajn1r5c.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=68169', 'data', 'file=/tmp/tmpjd45me00/ro0n4y9u.json', 'init=/tmp/tmpjd45me00/iajn1r5c.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelj4z8epc2/prophet_model-20260803144640.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:40 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:40 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_t291sxu.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7j5l9mnm.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=86911', 'data', 'file=/tmp/tmpjd45me00/_t291sxu.json', 'init=/tmp/tmpjd45me00/7j5l9mnm.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeluwusslve/prophet_model-20260803144640.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:40 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_19_dept_87
Build prophet model for  store_19_dept_9

14:46:40 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gb938izi.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/k_rlmt6g.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=28567', 'data', 'file=/tmp/tmpjd45me00/gb938izi.json', 'init=/tmp/tmpjd45me00/k_rlmt6g.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelzcob8jn6/prophet_model-20260803144640.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:40 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:40 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_19_dept_90
Build prophet model for  store_19_dept_91

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/nvqag91v.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/eu1xawy8.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=84263', 'data', 'file=/tmp/tmpjd45me00/nvqag91v.json', 'init=/tmp/tmpjd45me00/eu1xawy8.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeltlipj3ed/prophet_model-20260803144641.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:41 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:41 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/04itm8_h.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dt0sbhps.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=89794', 'data', 'file=/tmp/tmpjd45me00/04itm8_h.json', 'init=/tmp/tmpjd45me00/dt0sbhps.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeliohvkrrb/prophet_model-20260803144641.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:41 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:41 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_19_dept_92
Build prophet model for  store_19_dept_93

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/w99ooegx.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ygjj2g5w.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=97977', 'data', 'file=/tmp/tmpjd45me00/w99ooegx.json', 'init=/tmp/tmpjd45me00/ygjj2g5w.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeljibfko81/prophet_model-20260803144641.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:41 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:41 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_19_dept_94
Build prophet model for  store_19_dept_95

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/a6wrix8d.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7l0qfs10.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=67029', 'data', 'file=/tmp/tmpjd45me00/a6wrix8d.json', 'init=/tmp/tmpjd45me00/7l0qfs10.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model2ez8oe7r/prophet_model-20260803144641.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:41 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:41 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4mzrlvos.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hm2mor0n.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=99523', 'data', 'file=/tmp/tmpjd45me00/4mzrlvos.json', 'init=/tmp/tmpjd45me00/hm2mor0n.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model3mvopup6/prophet_model-20260803144642.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:42 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:42 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_19_dept_96
Build prophet model for  store_19_dept_97

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2520txhk.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/c55dp_id.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=73771', 'data', 'file=/tmp/tmpjd45me00/2520txhk.json', 'init=/tmp/tmpjd45me00/c55dp_id.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelosn14vm5/prophet_model-20260803144642.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:42 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:42 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/j_ripdtj.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jv_prrlu.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=51299', 'data', 'file=/tmp/tmpjd45me00/j_ripdtj.json', 'init=/tmp/tmpjd45me00/jv_prrlu.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model5yexz45y/prophet_model-20260803144642.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:42 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:42 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/effqje1c.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/50np03i3.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=10518', 'data', 'file=/tmp/tmpjd45me00/effqje1c.json', 'init=/tmp/tmpjd45me00/50np03i3.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelvnbi9v10/prophet_model-20260803144642.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:42 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_19_dept_98
Build prophet model for  store_1_dept_1

14:46:42 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7zk1du_8.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/q_ep64ux.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=40067', 'data', 'file=/tmp/tmpjd45me00/7zk1du_8.json', 'init=/tmp/tmpjd45me00/q_ep64ux.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model40rnj9fp/prophet_model-20260803144642.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:42 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:42 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/omyvptd4.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7o6vre3h.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=42267', 'data', 'file=/tmp/tmpjd45me00/omyvptd4.json', 'init=/tmp/tmpjd45me00/7o6vre3h.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelu4fbv4ln/prophet_model-20260803144642.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:42 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_1_dept_10
Build prophet model for  store_1_dept_11

14:46:42 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gcep4_88.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ur66de59.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=86729', 'data', 'file=/tmp/tmpjd45me00/gcep4_88.json', 'init=/tmp/tmpjd45me00/ur66de59.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeluyyp79of/prophet_model-20260803144643.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:43 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:43 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/k3aibwmf.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zjju66le.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=11470', 'data', 'file=/tmp/tmpjd45me00/k3aibwmf.json', 'init=/tmp/tmpjd45me00/zjju66le.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelruw6cx8l/prophet_model-20260803144643.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:43 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_1_dept_12
Build prophet model for  store_1_dept_13

14:46:43 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/y404e5kt.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0wifwvqk.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=25321', 'data', 'file=/tmp/tmpjd45me00/y404e5kt.json', 'init=/tmp/tmpjd45me00/0wifwvqk.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelpoz2xiit/prophet_model-20260803144643.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:43 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:43 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/44q_qypq.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pp95pm4r.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=5823', 'data', 'file=/tmp/tmpjd45me00/44q_qypq.json', 'init=/tmp/tmpjd45me00/pp95pm4r.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelc_h94fxr/prophet_model-20260803144643.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:43 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_1_dept_14
Build prophet model for  store_1_dept_16

14:46:43 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/nmljzr1l.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/tv7bj88q.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=82168', 'data', 'file=/tmp/tmpjd45me00/nmljzr1l.json', 'init=/tmp/tmpjd45me00/tv7bj88q.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelg9nddybh/prophet_model-20260803144644.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:44 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:44 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ipuhvzr0.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6xwwlgzs.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=48901', 'data', 'file=/tmp/tmpjd45me00/ipuhvzr0.json', 'init=/tmp/tmpjd45me00/6xwwlgzs.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model3j7ppia1/prophet_model-20260803144644.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:46:44 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_1_dept_17
Build prophet model for  store_1_dept_18

14:46:45 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qksomgc_.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6yuid7ds.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=51634', 'data', 'file=/tmp/tmpjd45me00/qksomgc_.json', 'init=/tmp/tmpjd45me00/6yuid7ds.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelkrk3alr_/prophet_model-20260803144645.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:45 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:46 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_1_dept_19

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/n27wjxf5.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8ltt74ks.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=92348', 'data', 'file=/tmp/tmpjd45me00/n27wjxf5.json', 'init=/tmp/tmpjd45me00/8ltt74ks.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelgjp5kgb2/prophet_model-20260803144646.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:46 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:46 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_1_dept_2

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qdt_e3rb.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/g__rcz7q.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=54342', 'data', 'file=/tmp/tmpjd45me00/qdt_e3rb.json', 'init=/tmp/tmpjd45me00/g__rcz7q.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model90mzdrkc/prophet_model-20260803144646.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:46 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:46 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_1_dept_20

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/w07w5yaf.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0sc0yawd.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=59453', 'data', 'file=/tmp/tmpjd45me00/w07w5yaf.json', 'init=/tmp/tmpjd45me00/0sc0yawd.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeloyoic3u4/prophet_model-20260803144646.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:46 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:46 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_1_dept_21

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5ny1g6bh.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0tt_klj6.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=13166', 'data', 'file=/tmp/tmpjd45me00/5ny1g6bh.json', 'init=/tmp/tmpjd45me00/0tt_klj6.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model0zhb7_ii/prophet_model-20260803144646.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:46 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:47 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_1_dept_22

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_vq6q7cx.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zm42_rne.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=56587', 'data', 'file=/tmp/tmpjd45me00/_vq6q7cx.json', 'init=/tmp/tmpjd45me00/zm42_rne.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeluxhduiq3/prophet_model-20260803144647.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:47 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:47 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_1_dept_23

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/08twn018.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/s3c1kc1t.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=24140', 'data', 'file=/tmp/tmpjd45me00/08twn018.json', 'init=/tmp/tmpjd45me00/s3c1kc1t.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelsmkbr_xo/prophet_model-20260803144647.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:47 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:47 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_1_dept_24

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wxmkkyb6.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xjkzufn2.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=33068', 'data', 'file=/tmp/tmpjd45me00/wxmkkyb6.json', 'init=/tmp/tmpjd45me00/xjkzufn2.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelwr0444_3/prophet_model-20260803144647.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:47 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:47 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_1_dept_25
Build prophet model for  store_1_dept_26

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/iz8h18wx.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/c3ushw5r.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=35175', 'data', 'file=/tmp/tmpjd45me00/iz8h18wx.json', 'init=/tmp/tmpjd45me00/c3ushw5r.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelg6doq3mv/prophet_model-20260803144647.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:47 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:48 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/h31g4l60.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wuerr6v8.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=99824', 'data', 'file=/tmp/tmpjd45me00/h31g4l60.json', 'init=/tmp/tmpjd45me00/wuerr6v8.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model3ai80f8e/prophet_model-20260803144648.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:48 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:48 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_1_dept_27
Build prophet model for  store_1_dept_28

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7ck2tx3j.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/31liuarb.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=71847', 'data', 'file=/tmp/tmpjd45me00/7ck2tx3j.json', 'init=/tmp/tmpjd45me00/31liuarb.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelr_ehnwk3/prophet_model-20260803144648.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:48 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:48 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0ffvbo0y.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/z1m0v0ry.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=37013', 'data', 'file=/tmp/tmpjd45me00/0ffvbo0y.json', 'init=/tmp/tmpjd45me00/z1m0v0ry.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model3pehb16u/prophet_model-20260803144648.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:48 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:48 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_1_dept_29
Build prophet model for  store_1_dept_3

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9rm2st3x.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/oytddkdf.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=98403', 'data', 'file=/tmp/tmpjd45me00/9rm2st3x.json', 'init=/tmp/tmpjd45me00/oytddkdf.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeltsqtcy2x/prophet_model-20260803144648.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:48 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:48 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bjhp_uab.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/a_4t5imm.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=53322', 'data', 'file=/tmp/tmpjd45me00/bjhp_uab.json', 'init=/tmp/tmpjd45me00/a_4t5imm.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model4weg1sbz/prophet_model-20260803144648.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:48 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:49 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_io8k9fh.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/91k8bcpp.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=92474', 'data', 'file=/tmp/tmpjd45me00/_io8k9fh.json', 'init=/tmp/tmpjd45me00/91k8bcpp.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelrr0_sg89/prophet_model-20260803144649.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:49 - cmdstanpy - INFO - Chain [1] start processing

Build prophet model for  store_1_dept_30
Build prophet model for  store_1_dept_31

INFO:cmdstanpy:Chain [1] start processing
14:46:49 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zlu9hhui.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/s_crutve.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=99636', 'data', 'file=/tmp/tmpjd45me00/zlu9hhui.json', 'init=/tmp/tmpjd45me00/s_crutve.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeluofgz6l7/prophet_model-20260803144649.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:49 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:49 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3tu02ysw.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vp5xp1az.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=71342', 'data', 'file=/tmp/tmpjd45me00/3tu02ysw.json', 'init=/tmp/tmpjd45me00/vp5xp1az.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelmieaje2j/prophet_model-20260803144649.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:49 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_1_dept_32
Build prophet model for  store_1_dept_33

14:46:49 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/k68bhvgc.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7ddfebe5.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=35487', 'data', 'file=/tmp/tmpjd45me00/k68bhvgc.json', 'init=/tmp/tmpjd45me00/7ddfebe5.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model32y5i6ge/prophet_model-20260803144649.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:49 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:49 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_1_dept_34
Build prophet model for  store_1_dept_35

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2m2v9txa.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/o5f2nkyw.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=56735', 'data', 'file=/tmp/tmpjd45me00/2m2v9txa.json', 'init=/tmp/tmpjd45me00/o5f2nkyw.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelsuanjnjl/prophet_model-20260803144649.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:49 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:49 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/izxrumvb.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wjfgalw3.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=61356', 'data', 'file=/tmp/tmpjd45me00/izxrumvb.json', 'init=/tmp/tmpjd45me00/wjfgalw3.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model0t8kffqr/prophet_model-20260803144649.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:49 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:49 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jdfi2c3r.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qdistsig.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=76845', 'data', 'file=/tmp/tmpjd45me00/jdfi2c3r.json', 'init=/tmp/tmpjd45me00/qdistsig.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model5y_zd8ws/prophet_model-20260803144650.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:50 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_1_dept_36
Build prophet model for  store_1_dept_37

14:46:50 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hgx0zh1t.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/d4i4r79f.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=55032', 'data', 'file=/tmp/tmpjd45me00/hgx0zh1t.json', 'init=/tmp/tmpjd45me00/d4i4r79f.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model67zla21p/prophet_model-20260803144650.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:50 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:50 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/kxc2fh3a.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8_vobfwa.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=26817', 'data', 'file=/tmp/tmpjd45me00/kxc2fh3a.json', 'init=/tmp/tmpjd45me00/8_vobfwa.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelpjvfwgj8/prophet_model-20260803144650.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:50 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_1_dept_38
Build prophet model for  store_1_dept_4

14:46:50 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vv4r_f5u.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/cpsfvjme.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=8878', 'data', 'file=/tmp/tmpjd45me00/vv4r_f5u.json', 'init=/tmp/tmpjd45me00/cpsfvjme.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeltxp2hjlc/prophet_model-20260803144650.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:50 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:50 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_1_dept_40

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rfrrto8_.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/c_d5yxni.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=16044', 'data', 'file=/tmp/tmpjd45me00/rfrrto8_.json', 'init=/tmp/tmpjd45me00/c_d5yxni.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelpndvvjq5/prophet_model-20260803144650.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:50 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:50 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_1_dept_41
Build prophet model for  store_1_dept_42

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/w0qhyksu.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9ozgogug.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=3958', 'data', 'file=/tmp/tmpjd45me00/w0qhyksu.json', 'init=/tmp/tmpjd45me00/9ozgogug.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelczw432rg/prophet_model-20260803144651.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:51 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:51 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ffp9vu82.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bz6twiya.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=2944', 'data', 'file=/tmp/tmpjd45me00/ffp9vu82.json', 'init=/tmp/tmpjd45me00/bz6twiya.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelibkaxg2t/prophet_model-20260803144651.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:51 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:51 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/yqbga1bo.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/b8s55kco.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=75567', 'data', 'file=/tmp/tmpjd45me00/yqbga1bo.json', 'init=/tmp/tmpjd45me00/b8s55kco.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelvey998fe/prophet_model-20260803144651.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:46:51 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_1_dept_44
Build prophet model for  store_1_dept_45

14:46:51 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/u_orxgz1.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hyiorob1.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=54364', 'data', 'file=/tmp/tmpjd45me00/u_orxgz1.json', 'init=/tmp/tmpjd45me00/hyiorob1.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model69r4rzl3/prophet_model-20260803144651.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:51 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:51 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9kamuanw.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/sbf_9rlz.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=55091', 'data', 'file=/tmp/tmpjd45me00/9kamuanw.json', 'init=/tmp/tmpjd45me00/sbf_9rlz.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelm9rnmjh_/prophet_model-20260803144652.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:52 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_1_dept_46
Build prophet model for  store_1_dept_48

14:46:52 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7cvel0ep.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zo69lkhz.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=7548', 'data', 'file=/tmp/tmpjd45me00/7cvel0ep.json', 'init=/tmp/tmpjd45me00/zo69lkhz.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeldvi2nq26/prophet_model-20260803144652.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:52 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:52 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/sm66oftv.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/kmqkahga.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=84895', 'data', 'file=/tmp/tmpjd45me00/sm66oftv.json', 'init=/tmp/tmpjd45me00/kmqkahga.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model7m50lhau/prophet_model-20260803144652.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:52 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_1_dept_49
Build prophet model for  store_1_dept_5

14:46:52 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6j5j3map.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/oani4726.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=40948', 'data', 'file=/tmp/tmpjd45me00/6j5j3map.json', 'init=/tmp/tmpjd45me00/oani4726.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeldj3y7nwx/prophet_model-20260803144652.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:52 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:52 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_1_dept_51
Skip  store_1_dept_51 due to lack of data
Build prophet model for  store_1_dept_52
Build prophet model for  store_1_dept_54

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0gkm32rt.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1_g4xcqi.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=75519', 'data', 'file=/tmp/tmpjd45me00/0gkm32rt.json', 'init=/tmp/tmpjd45me00/1_g4xcqi.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelsyt8lbfh/prophet_model-20260803144652.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:52 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:52 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5wan24ol.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_pp8yquc.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=86868', 'data', 'file=/tmp/tmpjd45me00/5wan24ol.json', 'init=/tmp/tmpjd45me00/_pp8yquc.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model1kmk5_u0/prophet_model-20260803144652.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:52 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:52 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/uvsky04f.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jh5gg3ag.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=9069', 'data', 'file=/tmp/tmpjd45me00/uvsky04f.json', 'init=/tmp/tmpjd45me00/jh5gg3ag.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model2sb0uc3f/prophet_model-20260803144653.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:53 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_1_dept_55
Build prophet model for  store_1_dept_56

14:46:53 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vqfnqb3k.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3c3zc1gi.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=94812', 'data', 'file=/tmp/tmpjd45me00/vqfnqb3k.json', 'init=/tmp/tmpjd45me00/3c3zc1gi.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model4c_itkb9/prophet_model-20260803144653.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:53 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:53 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_1_dept_58

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1dewc68c.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ta4p1t_7.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=572', 'data', 'file=/tmp/tmpjd45me00/1dewc68c.json', 'init=/tmp/tmpjd45me00/ta4p1t_7.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model48tl_ur_/prophet_model-20260803144653.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:53 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_1_dept_59

14:46:53 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qgl3lzf9.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vavzw0ke.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=7170', 'data', 'file=/tmp/tmpjd45me00/qgl3lzf9.json', 'init=/tmp/tmpjd45me00/vavzw0ke.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelxei496o8/prophet_model-20260803144653.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:53 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:53 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/a3u1pkbr.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gj6ozp8n.json
DEBUG:cmdstanpy:idx 0

Build prophet model for  store_1_dept_6
Build prophet model for  store_1_dept_60

DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=60277', 'data', 'file=/tmp/tmpjd45me00/a3u1pkbr.json', 'init=/tmp/tmpjd45me00/gj6ozp8n.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modellisfxhuz/prophet_model-20260803144653.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:53 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:54 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/t10jntwp.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1kusz3ve.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=47290', 'data', 'file=/tmp/tmpjd45me00/t10jntwp.json', 'init=/tmp/tmpjd45me00/1kusz3ve.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelr5_3um0j/prophet_model-20260803144654.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:54 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:54 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/84y9h1ok.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_hqgfg_y.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=36673', 'data', 'file=/tmp/tmpjd45me00/84y9h1ok.json', 'init=/tmp/tmpjd45me00/_hqgfg_y.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model86_36mlx/prophet_model-20260803144654.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:54 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_1_dept_67
Build prophet model for  store_1_dept_7

14:46:54 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4u3xy1ru.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/nzf02xai.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=77736', 'data', 'file=/tmp/tmpjd45me00/4u3xy1ru.json', 'init=/tmp/tmpjd45me00/nzf02xai.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model1bv82e2u/prophet_model-20260803144654.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:54 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:54 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_1_dept_71
Build prophet model for  store_1_dept_72

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9z8dfyi8.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/c9a3qebj.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=31419', 'data', 'file=/tmp/tmpjd45me00/9z8dfyi8.json', 'init=/tmp/tmpjd45me00/c9a3qebj.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model52b8ie8r/prophet_model-20260803144654.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:54 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:54 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mjmfx0ph.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wayeq4zw.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=74244', 'data', 'file=/tmp/tmpjd45me00/mjmfx0ph.json', 'init=/tmp/tmpjd45me00/wayeq4zw.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model5wjpqk4w/prophet_model-20260803144654.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:54 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:54 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_1_dept_74

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/l1nwk216.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/e0aw0xgs.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=71417', 'data', 'file=/tmp/tmpjd45me00/l1nwk216.json', 'init=/tmp/tmpjd45me00/e0aw0xgs.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelespunvkx/prophet_model-20260803144655.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:55 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:55 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/og5nfjiw.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3vel0tdv.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=22692', 'data', 'file=/tmp/tmpjd45me00/og5nfjiw.json', 'init=/tmp/tmpjd45me00/3vel0tdv.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model3acw3gbi/prophet_model-20260803144655.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:55 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_1_dept_79
Build prophet model for  store_1_dept_8

14:46:55 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/q2qf1pud.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/il951ti5.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=85734', 'data', 'file=/tmp/tmpjd45me00/q2qf1pud.json', 'init=/tmp/tmpjd45me00/il951ti5.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model503sepob/prophet_model-20260803144655.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:55 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:55 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9_5tkzv5.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/lqt9laaq.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=44644', 'data', 'file=/tmp/tmpjd45me00/9_5tkzv5.json', 'init=/tmp/tmpjd45me00/lqt9laaq.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model4w2a3_xi/prophet_model-20260803144655.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:55 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_1_dept_80
Build prophet model for  store_1_dept_81

14:46:55 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2ualekc6.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0fr4xrgz.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=71247', 'data', 'file=/tmp/tmpjd45me00/2ualekc6.json', 'init=/tmp/tmpjd45me00/0fr4xrgz.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelnhqmc7_1/prophet_model-20260803144655.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:55 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:55 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jdyvsnht.json

Build prophet model for  store_1_dept_82
Build prophet model for  store_1_dept_83

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/kzvl4wvl.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=77789', 'data', 'file=/tmp/tmpjd45me00/jdyvsnht.json', 'init=/tmp/tmpjd45me00/kzvl4wvl.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelczgm1nql/prophet_model-20260803144655.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:55 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:56 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/exhnf20e.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/01mhlrgq.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=34142', 'data', 'file=/tmp/tmpjd45me00/exhnf20e.json', 'init=/tmp/tmpjd45me00/01mhlrgq.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeljra1iajv/prophet_model-20260803144656.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:56 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:56 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9mizdw3u.json

Build prophet model for  store_1_dept_85
Build prophet model for  store_1_dept_87

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/a9jzimi8.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=81064', 'data', 'file=/tmp/tmpjd45me00/9mizdw3u.json', 'init=/tmp/tmpjd45me00/a9jzimi8.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model72y7cm2x/prophet_model-20260803144656.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:56 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:56 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/cwkj40qp.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2kba1ld2.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=70342', 'data', 'file=/tmp/tmpjd45me00/cwkj40qp.json', 'init=/tmp/tmpjd45me00/2kba1ld2.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelssk_6x2y/prophet_model-20260803144656.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:56 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:56 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/g3hlc7cd.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7vm0zn32.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=64872', 'data', 'file=/tmp/tmpjd45me00/g3hlc7cd.json', 'init=/tmp/tmpjd45me00/7vm0zn32.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelaid5vdvp/prophet_model-20260803144656.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:56 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_1_dept_9
Build prophet model for  store_1_dept_90

14:46:56 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rqx3e4ek.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5mgwo2v_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=2068', 'data', 'file=/tmp/tmpjd45me00/rqx3e4ek.json', 'init=/tmp/tmpjd45me00/5mgwo2v_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeljg_ftx00/prophet_model-20260803144656.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:56 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:56 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_1_dept_91
Build prophet model for  store_1_dept_92

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dqxmtg8a.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/h74k0yn3.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=165', 'data', 'file=/tmp/tmpjd45me00/dqxmtg8a.json', 'init=/tmp/tmpjd45me00/h74k0yn3.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model370zn_cp/prophet_model-20260803144657.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:57 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:57 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jx91ombx.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/frk1qvh_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=94217', 'data', 'file=/tmp/tmpjd45me00/jx91ombx.json', 'init=/tmp/tmpjd45me00/frk1qvh_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelc9b2e1rb/prophet_model-20260803144657.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:57 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_1_dept_93
Build prophet model for  store_1_dept_94

14:46:57 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rxiqpcjm.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/lb0py694.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=52939', 'data', 'file=/tmp/tmpjd45me00/rxiqpcjm.json', 'init=/tmp/tmpjd45me00/lb0py694.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelozqd39dd/prophet_model-20260803144657.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:57 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:57 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_1_dept_95
Build prophet model for  store_1_dept_97

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/i472xq5e.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9_jrz4q2.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=96552', 'data', 'file=/tmp/tmpjd45me00/i472xq5e.json', 'init=/tmp/tmpjd45me00/9_jrz4q2.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelxv21qnwl/prophet_model-20260803144657.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:57 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:57 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/nwukfcbf.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/e0_ns6j_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=52071', 'data', 'file=/tmp/tmpjd45me00/nwukfcbf.json', 'init=/tmp/tmpjd45me00/e0_ns6j_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelo6607m7_/prophet_model-20260803144657.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:57 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:57 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_1_dept_98
Build prophet model for  store_20_dept_1

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/olk5k2hg.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zgdgdzgt.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=27896', 'data', 'file=/tmp/tmpjd45me00/olk5k2hg.json', 'init=/tmp/tmpjd45me00/zgdgdzgt.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model7z5u1w9j/prophet_model-20260803144657.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:57 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_20_dept_10

14:46:58 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7dh0j7ei.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8rwwrgoh.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=14726', 'data', 'file=/tmp/tmpjd45me00/7dh0j7ei.json', 'init=/tmp/tmpjd45me00/8rwwrgoh.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelvw9f33fv/prophet_model-20260803144658.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:58 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:58 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_20_dept_11

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/w238exo1.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fihueulu.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=78760', 'data', 'file=/tmp/tmpjd45me00/w238exo1.json', 'init=/tmp/tmpjd45me00/fihueulu.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelkjnbusrg/prophet_model-20260803144658.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:58 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_20_dept_12

14:46:58 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/z70oycin.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/q4nsdo3y.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=7142', 'data', 'file=/tmp/tmpjd45me00/z70oycin.json', 'init=/tmp/tmpjd45me00/q4nsdo3y.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelq531nn2m/prophet_model-20260803144659.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:59 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:59 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_20_dept_13

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/90s_k4bd.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/f4fd_0ms.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=18816', 'data', 'file=/tmp/tmpjd45me00/90s_k4bd.json', 'init=/tmp/tmpjd45me00/f4fd_0ms.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelckdd005v/prophet_model-20260803144659.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:59 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:59 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_20_dept_14

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hqc7o98b.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ay8_kbk4.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=22075', 'data', 'file=/tmp/tmpjd45me00/hqc7o98b.json', 'init=/tmp/tmpjd45me00/ay8_kbk4.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelyfzgb_8i/prophet_model-20260803144659.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:59 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:59 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_20_dept_16

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/y0l0qdcu.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/t39y089_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=92953', 'data', 'file=/tmp/tmpjd45me00/y0l0qdcu.json', 'init=/tmp/tmpjd45me00/t39y089_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model8zw7opxi/prophet_model-20260803144659.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:46:59 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:46:59 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_20_dept_17

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/87no4cwz.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wo14addh.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=50889', 'data', 'file=/tmp/tmpjd45me00/87no4cwz.json', 'init=/tmp/tmpjd45me00/wo14addh.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model1zlb_h61/prophet_model-20260803144700.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:00 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:00 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_20_dept_18

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9nsd312p.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1o0rehl2.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=73587', 'data', 'file=/tmp/tmpjd45me00/9nsd312p.json', 'init=/tmp/tmpjd45me00/1o0rehl2.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model30n3hy9r/prophet_model-20260803144700.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:00 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:00 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_20_dept_2
Build prophet model for  store_20_dept_20

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ri84_0jn.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/la210j1j.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=29086', 'data', 'file=/tmp/tmpjd45me00/ri84_0jn.json', 'init=/tmp/tmpjd45me00/la210j1j.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model6iwhdhi7/prophet_model-20260803144700.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:00 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:00 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zhox8yoh.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/41b5ywq2.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=47639', 'data', 'file=/tmp/tmpjd45me00/zhox8yoh.json', 'init=/tmp/tmpjd45me00/41b5ywq2.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelznx29ppw/prophet_model-20260803144700.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:00 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_20_dept_21

14:47:00 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/40nn4x9f.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/415r0tyl.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=5073', 'data', 'file=/tmp/tmpjd45me00/40nn4x9f.json', 'init=/tmp/tmpjd45me00/415r0tyl.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelhc8a1l_z/prophet_model-20260803144701.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:01 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:01 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_20_dept_22

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ih7k27ts.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pj6j079u.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=21027', 'data', 'file=/tmp/tmpjd45me00/ih7k27ts.json', 'init=/tmp/tmpjd45me00/pj6j079u.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelbgwwm6_g/prophet_model-20260803144701.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:01 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:01 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_20_dept_23
Build prophet model for  store_20_dept_24

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rhwi1r7w.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/iiinic2u.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=88245', 'data', 'file=/tmp/tmpjd45me00/rhwi1r7w.json', 'init=/tmp/tmpjd45me00/iiinic2u.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model0ypgtr5f/prophet_model-20260803144701.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:01 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:01 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zgoxfuaw.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/i5h51rh0.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=68376', 'data', 'file=/tmp/tmpjd45me00/zgoxfuaw.json', 'init=/tmp/tmpjd45me00/i5h51rh0.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelvcnp7iam/prophet_model-20260803144701.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:01 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:01 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3bv7mluy.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/g9icr2qt.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=33768', 'data', 'file=/tmp/tmpjd45me00/3bv7mluy.json', 'init=/tmp/tmpjd45me00/g9icr2qt.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modely26fifpt/prophet_model-20260803144701.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:01 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_20_dept_25
Build prophet model for  store_20_dept_26

14:47:01 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/56kg3m1u.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/npzvuy6y.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=84155', 'data', 'file=/tmp/tmpjd45me00/56kg3m1u.json', 'init=/tmp/tmpjd45me00/npzvuy6y.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelbt6sfc_9/prophet_model-20260803144701.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:02 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:02 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mvnfnyhj.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/h0fqrgtk.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=24157', 'data', 'file=/tmp/tmpjd45me00/mvnfnyhj.json', 'init=/tmp/tmpjd45me00/h0fqrgtk.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modell8uft_wa/prophet_model-20260803144702.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:02 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_20_dept_27
Build prophet model for  store_20_dept_28

14:47:02 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rgppchf9.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/d_ol1plw.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=38102', 'data', 'file=/tmp/tmpjd45me00/rgppchf9.json', 'init=/tmp/tmpjd45me00/d_ol1plw.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model1hlvv5it/prophet_model-20260803144702.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:02 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:02 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ufrg6t2d.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/i465sy8r.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=8791', 'data', 'file=/tmp/tmpjd45me00/ufrg6t2d.json', 'init=/tmp/tmpjd45me00/i465sy8r.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelj94w63g9/prophet_model-20260803144702.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:02 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_20_dept_29
Build prophet model for  store_20_dept_3

14:47:02 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ni4esxil.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/e3a3y6b6.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=25087', 'data', 'file=/tmp/tmpjd45me00/ni4esxil.json', 'init=/tmp/tmpjd45me00/e3a3y6b6.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelwmf4ytxy/prophet_model-20260803144702.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:02 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:02 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9aksq4fo.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3wai7j01.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=30688', 'data', 'file=/tmp/tmpjd45me00/9aksq4fo.json', 'init=/tmp/tmpjd45me00/3wai7j01.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelju3gjh29/prophet_model-20260803144702.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:02 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_20_dept_30
Build prophet model for  store_20_dept_31

14:47:02 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/tl3fn009.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xm1sprqi.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=14871', 'data', 'file=/tmp/tmpjd45me00/tl3fn009.json', 'init=/tmp/tmpjd45me00/xm1sprqi.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelcgdwg2fe/prophet_model-20260803144703.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:03 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:03 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/q789_0v6.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/d2uvyirr.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=11400', 'data', 'file=/tmp/tmpjd45me00/q789_0v6.json', 'init=/tmp/tmpjd45me00/d2uvyirr.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model3u6z23ff/prophet_model-20260803144703.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:03 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_20_dept_32
Build prophet model for  store_20_dept_33

14:47:03 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qd9x0rjh.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ci_nzexv.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=38631', 'data', 'file=/tmp/tmpjd45me00/qd9x0rjh.json', 'init=/tmp/tmpjd45me00/ci_nzexv.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelt_s38t4o/prophet_model-20260803144703.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:03 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:03 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1acmdvll.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/g56iwkoj.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=234', 'data', 'file=/tmp/tmpjd45me00/1acmdvll.json', 'init=/tmp/tmpjd45me00/g56iwkoj.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model14jnwgby/prophet_model-20260803144703.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:03 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_20_dept_34
Build prophet model for  store_20_dept_35

14:47:03 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/buz9nga4.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vd13yjrn.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=46023', 'data', 'file=/tmp/tmpjd45me00/buz9nga4.json', 'init=/tmp/tmpjd45me00/vd13yjrn.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelbcdccmf9/prophet_model-20260803144703.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:03 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_20_dept_36

14:47:03 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jgo_fjqv.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/k6s8mzyk.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=22105', 'data', 'file=/tmp/tmpjd45me00/jgo_fjqv.json', 'init=/tmp/tmpjd45me00/k6s8mzyk.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modele4r45aaz/prophet_model-20260803144704.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:04 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:04 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_20_dept_37

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0ow29ig1.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/r8v3zde6.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=2079', 'data', 'file=/tmp/tmpjd45me00/0ow29ig1.json', 'init=/tmp/tmpjd45me00/r8v3zde6.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelvsv9wm8n/prophet_model-20260803144704.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:04 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:04 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_20_dept_38
Build prophet model for  store_20_dept_4

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/we8aenq1.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/kl9cg42h.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=64113', 'data', 'file=/tmp/tmpjd45me00/we8aenq1.json', 'init=/tmp/tmpjd45me00/kl9cg42h.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeltjm0edih/prophet_model-20260803144704.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:04 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:04 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vjwj42xc.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/q04dl8od.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=48928', 'data', 'file=/tmp/tmpjd45me00/vjwj42xc.json', 'init=/tmp/tmpjd45me00/q04dl8od.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_egpw8qr/prophet_model-20260803144704.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:04 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_20_dept_40
Build prophet model for  store_20_dept_41

14:47:05 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xqinyxae.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/lfz1ekom.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=49722', 'data', 'file=/tmp/tmpjd45me00/xqinyxae.json', 'init=/tmp/tmpjd45me00/lfz1ekom.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelvo2t_624/prophet_model-20260803144705.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:05 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:05 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_20_dept_42
Build prophet model for  store_20_dept_44

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/uh20f06j.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/evcdm3t6.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=48717', 'data', 'file=/tmp/tmpjd45me00/uh20f06j.json', 'init=/tmp/tmpjd45me00/evcdm3t6.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeljs_jeome/prophet_model-20260803144705.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:05 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:05 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9_aya7ph.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/g362rt2h.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=68763', 'data', 'file=/tmp/tmpjd45me00/9_aya7ph.json', 'init=/tmp/tmpjd45me00/g362rt2h.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelr2axsuoy/prophet_model-20260803144705.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:05 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:05 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gk5k64fj.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/z9l527le.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=83558', 'data', 'file=/tmp/tmpjd45me00/gk5k64fj.json', 'init=/tmp/tmpjd45me00/z9l527le.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeluwughqi2/prophet_model-20260803144705.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:05 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_20_dept_46
Build prophet model for  store_20_dept_49

14:47:05 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1a5uxpbu.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3rymu6gl.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=40814', 'data', 'file=/tmp/tmpjd45me00/1a5uxpbu.json', 'init=/tmp/tmpjd45me00/3rymu6gl.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model6yfr44x8/prophet_model-20260803144705.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:05 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:05 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/uen5osl7.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2biie913.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None

Build prophet model for  store_20_dept_5
Build prophet model for  store_20_dept_50

DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=28306', 'data', 'file=/tmp/tmpjd45me00/uen5osl7.json', 'init=/tmp/tmpjd45me00/2biie913.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelgnn1lu3w/prophet_model-20260803144706.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:06 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:06 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/kij029hr.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/k6vzfgb6.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=5778', 'data', 'file=/tmp/tmpjd45me00/kij029hr.json', 'init=/tmp/tmpjd45me00/k6vzfgb6.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelh6v076wy/prophet_model-20260803144706.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:06 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:06 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_20_dept_52
Build prophet model for  store_20_dept_54

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/tei_1j1c.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gzm4w872.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=62436', 'data', 'file=/tmp/tmpjd45me00/tei_1j1c.json', 'init=/tmp/tmpjd45me00/gzm4w872.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model95f8pb0v/prophet_model-20260803144706.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:06 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:06 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/b3iooz5x.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/f9j2b8m2.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=85565', 'data', 'file=/tmp/tmpjd45me00/b3iooz5x.json', 'init=/tmp/tmpjd45me00/f9j2b8m2.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeltmulg_ix/prophet_model-20260803144706.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:06 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:06 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7dggxs0y.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3pwtm7qv.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=61978', 'data', 'file=/tmp/tmpjd45me00/7dggxs0y.json', 'init=/tmp/tmpjd45me00/3pwtm7qv.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelnlfzc13c/prophet_model-20260803144706.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:06 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_20_dept_55
Build prophet model for  store_20_dept_56

14:47:06 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7sd25k5f.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qky0auf4.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=41901', 'data', 'file=/tmp/tmpjd45me00/7sd25k5f.json', 'init=/tmp/tmpjd45me00/qky0auf4.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelmj6ug834/prophet_model-20260803144707.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:07 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:07 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/en8d2wly.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xpmgh5ce.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=29052', 'data', 'file=/tmp/tmpjd45me00/en8d2wly.json', 'init=/tmp/tmpjd45me00/xpmgh5ce.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model4ygf89li/prophet_model-20260803144707.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:07 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_20_dept_58
Build prophet model for  store_20_dept_59

14:47:07 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vka53mp5.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5kr6ndqx.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=72154', 'data', 'file=/tmp/tmpjd45me00/vka53mp5.json', 'init=/tmp/tmpjd45me00/5kr6ndqx.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelpm6_e8gu/prophet_model-20260803144707.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:07 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:07 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8usk6wec.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3gyjngmk.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=76253', 'data', 'file=/tmp/tmpjd45me00/8usk6wec.json', 'init=/tmp/tmpjd45me00/3gyjngmk.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_wqkdyjq/prophet_model-20260803144707.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:07 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_20_dept_6
Build prophet model for  store_20_dept_60

14:47:07 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wdg9pmra.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/kj7d1b__.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=22182', 'data', 'file=/tmp/tmpjd45me00/wdg9pmra.json', 'init=/tmp/tmpjd45me00/kj7d1b__.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeljcadct85/prophet_model-20260803144707.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:07 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:08 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9wsw337l.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/w306vxj5.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=53979', 'data', 'file=/tmp/tmpjd45me00/9wsw337l.json', 'init=/tmp/tmpjd45me00/w306vxj5.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelhia7mo70/prophet_model-20260803144708.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:08 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_20_dept_67
Build prophet model for  store_20_dept_7

14:47:08 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hburir2p.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/q1yqep17.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=47784', 'data', 'file=/tmp/tmpjd45me00/hburir2p.json', 'init=/tmp/tmpjd45me00/q1yqep17.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modellh07tivz/prophet_model-20260803144708.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:08 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:08 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_20_dept_71
Build prophet model for  store_20_dept_72

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ftcv92le.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1nxaxoz3.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=57118', 'data', 'file=/tmp/tmpjd45me00/ftcv92le.json', 'init=/tmp/tmpjd45me00/1nxaxoz3.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelg7ehssys/prophet_model-20260803144708.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:08 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:08 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/lzquwklw.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pjwiva3b.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=60374', 'data', 'file=/tmp/tmpjd45me00/lzquwklw.json', 'init=/tmp/tmpjd45me00/pjwiva3b.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelx3gk62q_/prophet_model-20260803144708.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:08 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:08 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_20_dept_74
Build prophet model for  store_20_dept_79

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/u4pga6iq.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/n8a2osmk.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=98162', 'data', 'file=/tmp/tmpjd45me00/u4pga6iq.json', 'init=/tmp/tmpjd45me00/n8a2osmk.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelcvs79u_u/prophet_model-20260803144708.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:08 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:08 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jah38mnu.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hpfzci4t.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=38516', 'data', 'file=/tmp/tmpjd45me00/jah38mnu.json', 'init=/tmp/tmpjd45me00/hpfzci4t.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model5crwunwg/prophet_model-20260803144709.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:09 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:09 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/35vv8rqp.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3gpcpw4y.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=31086', 'data', 'file=/tmp/tmpjd45me00/35vv8rqp.json', 'init=/tmp/tmpjd45me00/3gpcpw4y.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeleazu5nk1/prophet_model-20260803144709.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:09 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_20_dept_8
Build prophet model for  store_20_dept_80

14:47:09 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bcath92n.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/c5n5c5jz.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=31242', 'data', 'file=/tmp/tmpjd45me00/bcath92n.json', 'init=/tmp/tmpjd45me00/c5n5c5jz.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model5y0u5ixv/prophet_model-20260803144709.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:09 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:09 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_20_dept_81
Build prophet model for  store_20_dept_82

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dv8k2jkx.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/cxyqqtwr.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=55011', 'data', 'file=/tmp/tmpjd45me00/dv8k2jkx.json', 'init=/tmp/tmpjd45me00/cxyqqtwr.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeldhnq6uvx/prophet_model-20260803144709.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:09 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:09 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/sfpxyk0u.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5xm0o8bf.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=74176', 'data', 'file=/tmp/tmpjd45me00/sfpxyk0u.json', 'init=/tmp/tmpjd45me00/5xm0o8bf.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelldu70_cl/prophet_model-20260803144709.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:09 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:09 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bv9qrye1.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/i_qvltgl.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=27736', 'data', 'file=/tmp/tmpjd45me00/bv9qrye1.json', 'init=/tmp/tmpjd45me00/i_qvltgl.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelj7zj8wmo/prophet_model-20260803144709.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:09 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_20_dept_83
Build prophet model for  store_20_dept_85

14:47:10 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8decbu7h.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3zr25_zq.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=99661', 'data', 'file=/tmp/tmpjd45me00/8decbu7h.json', 'init=/tmp/tmpjd45me00/3zr25_zq.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelfi0g_sdn/prophet_model-20260803144710.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:10 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:10 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rxgmhf5k.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/djnh0qtu.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=34323', 'data', 'file=/tmp/tmpjd45me00/rxgmhf5k.json', 'init=/tmp/tmpjd45me00/djnh0qtu.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model7t67jid0/prophet_model-20260803144710.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:10 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_20_dept_87
Build prophet model for  store_20_dept_9

14:47:10 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rt6drxlk.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wytb4d67.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=27217', 'data', 'file=/tmp/tmpjd45me00/rt6drxlk.json', 'init=/tmp/tmpjd45me00/wytb4d67.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelde1gjqqp/prophet_model-20260803144710.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:10 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:10 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jtzzhg1w.json

Build prophet model for  store_20_dept_90
Build prophet model for  store_20_dept_91

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fdkl8wo3.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=25954', 'data', 'file=/tmp/tmpjd45me00/jtzzhg1w.json', 'init=/tmp/tmpjd45me00/fdkl8wo3.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelnqtk9_q6/prophet_model-20260803144710.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:10 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:10 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ooc135ny.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ljno88cd.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=22087', 'data', 'file=/tmp/tmpjd45me00/ooc135ny.json', 'init=/tmp/tmpjd45me00/ljno88cd.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelm2lg_bdx/prophet_model-20260803144710.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:10 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:10 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_20_dept_92
Build prophet model for  store_20_dept_93

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bybux468.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ghebepb7.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=49184', 'data', 'file=/tmp/tmpjd45me00/bybux468.json', 'init=/tmp/tmpjd45me00/ghebepb7.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelx5327nu8/prophet_model-20260803144711.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:11 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:11 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_20_dept_94
Build prophet model for  store_20_dept_95

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/34w49mst.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vpwx9oja.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=36366', 'data', 'file=/tmp/tmpjd45me00/34w49mst.json', 'init=/tmp/tmpjd45me00/vpwx9oja.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modell82dotyv/prophet_model-20260803144711.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:11 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:11 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_20_dept_97
Build prophet model for  store_20_dept_98

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/njjn1jjr.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/asm8bunx.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=55905', 'data', 'file=/tmp/tmpjd45me00/njjn1jjr.json', 'init=/tmp/tmpjd45me00/asm8bunx.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_gjpew6r/prophet_model-20260803144711.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:11 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:11 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/cx849opk.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7q6ce48f.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=16365', 'data', 'file=/tmp/tmpjd45me00/cx849opk.json', 'init=/tmp/tmpjd45me00/7q6ce48f.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeluhzwwpio/prophet_model-20260803144711.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:11 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:11 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_21_dept_1
Build prophet model for  store_21_dept_10

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/42oixf8e.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gfh0q1a6.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=57586', 'data', 'file=/tmp/tmpjd45me00/42oixf8e.json', 'init=/tmp/tmpjd45me00/gfh0q1a6.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model08ir39mv/prophet_model-20260803144712.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:12 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:12 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dpymnpi7.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/b2kxlv6z.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=33668', 'data', 'file=/tmp/tmpjd45me00/dpymnpi7.json', 'init=/tmp/tmpjd45me00/b2kxlv6z.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelqa19wty7/prophet_model-20260803144712.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:12 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:12 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_21_dept_11

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ego66qon.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_3fz1neh.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=37108', 'data', 'file=/tmp/tmpjd45me00/ego66qon.json', 'init=/tmp/tmpjd45me00/_3fz1neh.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model6cioubtb/prophet_model-20260803144712.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:12 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:12 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_21_dept_12

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9a_ok0b8.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/i024g57a.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=86097', 'data', 'file=/tmp/tmpjd45me00/9a_ok0b8.json', 'init=/tmp/tmpjd45me00/i024g57a.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modellxdn8bwe/prophet_model-20260803144712.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:12 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_21_dept_13

14:47:13 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hcf1xipq.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pm79dt4s.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=99277', 'data', 'file=/tmp/tmpjd45me00/hcf1xipq.json', 'init=/tmp/tmpjd45me00/pm79dt4s.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelh5md8maj/prophet_model-20260803144713.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:13 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:13 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_21_dept_14

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fp4ey24f.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/uefg59l1.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=19347', 'data', 'file=/tmp/tmpjd45me00/fp4ey24f.json', 'init=/tmp/tmpjd45me00/uefg59l1.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model8by17vx1/prophet_model-20260803144713.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:13 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_21_dept_16

14:47:13 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7_oskpem.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fhoxfe_2.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=77302', 'data', 'file=/tmp/tmpjd45me00/7_oskpem.json', 'init=/tmp/tmpjd45me00/fhoxfe_2.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelyncysfs7/prophet_model-20260803144713.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:13 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_21_dept_17

14:47:14 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4gmj1_qz.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/htlugffh.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=85994', 'data', 'file=/tmp/tmpjd45me00/4gmj1_qz.json', 'init=/tmp/tmpjd45me00/htlugffh.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelvdgwp8k_/prophet_model-20260803144714.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:47:14 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_21_dept_18

14:47:16 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/l77_uxif.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/kzys_kiq.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=1342', 'data', 'file=/tmp/tmpjd45me00/l77_uxif.json', 'init=/tmp/tmpjd45me00/kzys_kiq.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeloanq17uf/prophet_model-20260803144716.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:16 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:16 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1e3rsc31.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/q0ax1_vv.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None

Build prophet model for  store_21_dept_19
Build prophet model for  store_21_dept_2

DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=80848', 'data', 'file=/tmp/tmpjd45me00/1e3rsc31.json', 'init=/tmp/tmpjd45me00/q0ax1_vv.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modely6g9wjak/prophet_model-20260803144716.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:16 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:16 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/anajro_9.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ypu1prrs.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=38442', 'data', 'file=/tmp/tmpjd45me00/anajro_9.json', 'init=/tmp/tmpjd45me00/ypu1prrs.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelvu63woqg/prophet_model-20260803144716.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:16 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:16 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/as29g_5k.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/07ar_90o.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=60152', 'data', 'file=/tmp/tmpjd45me00/as29g_5k.json', 'init=/tmp/tmpjd45me00/07ar_90o.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelheuady9g/prophet_model-20260803144716.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:16 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_21_dept_20
Build prophet model for  store_21_dept_21

14:47:16 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/76boz2a2.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5nu9zetf.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=54327', 'data', 'file=/tmp/tmpjd45me00/76boz2a2.json', 'init=/tmp/tmpjd45me00/5nu9zetf.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelw2cemlnt/prophet_model-20260803144717.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:17 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:17 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/uz0mntag.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6hyxxnwa.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=14314', 'data', 'file=/tmp/tmpjd45me00/uz0mntag.json', 'init=/tmp/tmpjd45me00/6hyxxnwa.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeljxxwahmy/prophet_model-20260803144717.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:17 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_21_dept_22
Build prophet model for  store_21_dept_23

14:47:17 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_ltxdhjr.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zv93jy1p.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=39171', 'data', 'file=/tmp/tmpjd45me00/_ltxdhjr.json', 'init=/tmp/tmpjd45me00/zv93jy1p.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model8xyveg3g/prophet_model-20260803144717.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:17 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:17 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ixffim_1.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fp071w0t.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=22021', 'data', 'file=/tmp/tmpjd45me00/ixffim_1.json', 'init=/tmp/tmpjd45me00/fp071w0t.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model44oznbo4/prophet_model-20260803144717.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:17 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_21_dept_24
Build prophet model for  store_21_dept_25

14:47:17 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/v3ll11og.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ysqx0_iu.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=16541', 'data', 'file=/tmp/tmpjd45me00/v3ll11og.json', 'init=/tmp/tmpjd45me00/ysqx0_iu.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_4zq1eow/prophet_model-20260803144717.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:17 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:17 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rht21f86.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/cl9d8qya.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=1228', 'data', 'file=/tmp/tmpjd45me00/rht21f86.json', 'init=/tmp/tmpjd45me00/cl9d8qya.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelpmwi82ko/prophet_model-20260803144717.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:17 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_21_dept_26
Build prophet model for  store_21_dept_27

14:47:17 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hzvkjpx5.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/n3qszliw.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=47222', 'data', 'file=/tmp/tmpjd45me00/hzvkjpx5.json', 'init=/tmp/tmpjd45me00/n3qszliw.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeljxdqhlsq/prophet_model-20260803144717.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:17 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:18 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9imshbp4.json

Build prophet model for  store_21_dept_28
Build prophet model for  store_21_dept_29

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/uyq4q081.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=43626', 'data', 'file=/tmp/tmpjd45me00/9imshbp4.json', 'init=/tmp/tmpjd45me00/uyq4q081.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeldhmtmys6/prophet_model-20260803144718.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:18 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:18 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wzwbx1wb.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6gb34jkb.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=33857', 'data', 'file=/tmp/tmpjd45me00/wzwbx1wb.json', 'init=/tmp/tmpjd45me00/6gb34jkb.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelg_1r0i68/prophet_model-20260803144718.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:18 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:18 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1o955lug.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/t2zfm_oq.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=94480', 'data', 'file=/tmp/tmpjd45me00/1o955lug.json', 'init=/tmp/tmpjd45me00/t2zfm_oq.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeliip6hmkv/prophet_model-20260803144718.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:18 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_21_dept_3
Build prophet model for  store_21_dept_30

14:47:18 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gg483_py.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rgvfz_vs.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=38022', 'data', 'file=/tmp/tmpjd45me00/gg483_py.json', 'init=/tmp/tmpjd45me00/rgvfz_vs.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelv7kd_p4h/prophet_model-20260803144718.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:18 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:18 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_9ltt0l9.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5eff4287.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=27275', 'data', 'file=/tmp/tmpjd45me00/_9ltt0l9.json', 'init=/tmp/tmpjd45me00/5eff4287.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelrmxqmu5f/prophet_model-20260803144718.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:18 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_21_dept_31
Build prophet model for  store_21_dept_32

14:47:18 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/i42wpiif.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/z8h76j5o.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=52275', 'data', 'file=/tmp/tmpjd45me00/i42wpiif.json', 'init=/tmp/tmpjd45me00/z8h76j5o.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelv2tq1cz6/prophet_model-20260803144718.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:18 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:18 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0_qtff5v.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qyica67x.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=30844', 'data', 'file=/tmp/tmpjd45me00/0_qtff5v.json', 'init=/tmp/tmpjd45me00/qyica67x.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeljh0kspk8/prophet_model-20260803144719.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:19 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_21_dept_33
Build prophet model for  store_21_dept_34

14:47:19 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/iu5ioap7.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5dsz5xw7.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=57417', 'data', 'file=/tmp/tmpjd45me00/iu5ioap7.json', 'init=/tmp/tmpjd45me00/5dsz5xw7.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model5395tmim/prophet_model-20260803144719.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:19 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:19 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vswfx_rf.json

Build prophet model for  store_21_dept_35
Build prophet model for  store_21_dept_36

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0wlsxfma.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=37131', 'data', 'file=/tmp/tmpjd45me00/vswfx_rf.json', 'init=/tmp/tmpjd45me00/0wlsxfma.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelb6hxzvw2/prophet_model-20260803144719.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:19 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:19 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/k6xdhen1.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/eih7zqve.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=87742', 'data', 'file=/tmp/tmpjd45me00/k6xdhen1.json', 'init=/tmp/tmpjd45me00/eih7zqve.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelnildtpih/prophet_model-20260803144719.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:19 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:19 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ce5vss5a.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1_3gaky6.json
DEBUG:cmdstanpy:idx 0

Build prophet model for  store_21_dept_38
Build prophet model for  store_21_dept_4

DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=20477', 'data', 'file=/tmp/tmpjd45me00/ce5vss5a.json', 'init=/tmp/tmpjd45me00/1_3gaky6.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelytal2vi2/prophet_model-20260803144719.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:19 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:19 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/kca_ltu2.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4n832dph.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=37935', 'data', 'file=/tmp/tmpjd45me00/kca_ltu2.json', 'init=/tmp/tmpjd45me00/4n832dph.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelx0t6jmq1/prophet_model-20260803144720.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:20 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:20 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_21_dept_40
Build prophet model for  store_21_dept_41

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/i98myy49.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/anayhv5z.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=3919', 'data', 'file=/tmp/tmpjd45me00/i98myy49.json', 'init=/tmp/tmpjd45me00/anayhv5z.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelfrxw5n0o/prophet_model-20260803144720.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:20 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:20 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/n0frdp14.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/q7k2m0x7.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=77558', 'data', 'file=/tmp/tmpjd45me00/n0frdp14.json', 'init=/tmp/tmpjd45me00/q7k2m0x7.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model9yvl1w_u/prophet_model-20260803144720.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:20 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:20 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0jnc5hyd.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/u71tr5em.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=30756', 'data', 'file=/tmp/tmpjd45me00/0jnc5hyd.json', 'init=/tmp/tmpjd45me00/u71tr5em.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelknyu4uf_/prophet_model-20260803144720.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:20 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_21_dept_42
Build prophet model for  store_21_dept_44

14:47:20 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qm_sctjk.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/n2b_2i6f.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=67112', 'data', 'file=/tmp/tmpjd45me00/qm_sctjk.json', 'init=/tmp/tmpjd45me00/n2b_2i6f.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelpikz21rd/prophet_model-20260803144720.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:20 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:20 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_21_dept_46
Build prophet model for  store_21_dept_49

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/nad0meh9.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/o98ky_w0.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=66175', 'data', 'file=/tmp/tmpjd45me00/nad0meh9.json', 'init=/tmp/tmpjd45me00/o98ky_w0.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelhqtd5f7n/prophet_model-20260803144721.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:21 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:21 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/293g22je.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/tpgbc2wt.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=38831', 'data', 'file=/tmp/tmpjd45me00/293g22je.json', 'init=/tmp/tmpjd45me00/tpgbc2wt.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model8hm2mp7r/prophet_model-20260803144721.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:21 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:21 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/kg8x65j4.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rrjmlh6e.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=20029', 'data', 'file=/tmp/tmpjd45me00/kg8x65j4.json', 'init=/tmp/tmpjd45me00/rrjmlh6e.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model9s4dhbrl/prophet_model-20260803144721.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:21 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_21_dept_5
Build prophet model for  store_21_dept_52

14:47:21 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_gj2kpac.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vrvj4ppz.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=50149', 'data', 'file=/tmp/tmpjd45me00/_gj2kpac.json', 'init=/tmp/tmpjd45me00/vrvj4ppz.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelbckzijav/prophet_model-20260803144721.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:21 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:21 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/law8azg0.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/e0ye6eyq.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=41929', 'data', 'file=/tmp/tmpjd45me00/law8azg0.json', 'init=/tmp/tmpjd45me00/e0ye6eyq.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model76sat2wb/prophet_model-20260803144721.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:21 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_21_dept_54
Build prophet model for  store_21_dept_55

14:47:21 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ivx66sqg.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6n7m4uyc.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=78412', 'data', 'file=/tmp/tmpjd45me00/ivx66sqg.json', 'init=/tmp/tmpjd45me00/6n7m4uyc.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelhgoyiw_9/prophet_model-20260803144721.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:21 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:21 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_21_dept_56
Build prophet model for  store_21_dept_58

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ku6mr0ng.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/c_qtsc5j.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=85486', 'data', 'file=/tmp/tmpjd45me00/ku6mr0ng.json', 'init=/tmp/tmpjd45me00/c_qtsc5j.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model4e67rjyk/prophet_model-20260803144722.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:22 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:22 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ysnfv5un.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/z0qyz0f1.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=66882', 'data', 'file=/tmp/tmpjd45me00/ysnfv5un.json', 'init=/tmp/tmpjd45me00/z0qyz0f1.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_km0sxmk/prophet_model-20260803144722.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:22 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_21_dept_59

14:47:22 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zec8jmh0.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/f_782vub.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=46472', 'data', 'file=/tmp/tmpjd45me00/zec8jmh0.json', 'init=/tmp/tmpjd45me00/f_782vub.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelox8ovz8l/prophet_model-20260803144722.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:22 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:22 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4bb_waxr.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fgdf0gwc.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=60711', 'data', 'file=/tmp/tmpjd45me00/4bb_waxr.json', 'init=/tmp/tmpjd45me00/fgdf0gwc.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelihe0zz_q/prophet_model-20260803144722.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:22 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_21_dept_6
Build prophet model for  store_21_dept_67

14:47:22 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/51jrt0bv.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0xfwcbyh.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=6674', 'data', 'file=/tmp/tmpjd45me00/51jrt0bv.json', 'init=/tmp/tmpjd45me00/0xfwcbyh.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model5wqfoq9h/prophet_model-20260803144722.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:22 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:22 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5q39xfep.json

Build prophet model for  store_21_dept_7
Build prophet model for  store_21_dept_71

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vn6tdxnt.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=37721', 'data', 'file=/tmp/tmpjd45me00/5q39xfep.json', 'init=/tmp/tmpjd45me00/vn6tdxnt.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model2_q4h6vv/prophet_model-20260803144723.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:23 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:23 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zfl4wqp7.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2w32m19z.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=1540', 'data', 'file=/tmp/tmpjd45me00/zfl4wqp7.json', 'init=/tmp/tmpjd45me00/2w32m19z.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeli5v9z4p2/prophet_model-20260803144723.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:23 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:23 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hwqqrs07.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/y1889jh0.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=17407', 'data', 'file=/tmp/tmpjd45me00/hwqqrs07.json', 'init=/tmp/tmpjd45me00/y1889jh0.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model5x3n43pn/prophet_model-20260803144723.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:23 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_21_dept_72
Build prophet model for  store_21_dept_74

14:47:23 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0er63wq6.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wvdojlbr.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=38942', 'data', 'file=/tmp/tmpjd45me00/0er63wq6.json', 'init=/tmp/tmpjd45me00/wvdojlbr.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelsj6j0qcl/prophet_model-20260803144723.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:23 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:23 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pjcq_1w8.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/w17yckbc.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=17188', 'data', 'file=/tmp/tmpjd45me00/pjcq_1w8.json', 'init=/tmp/tmpjd45me00/w17yckbc.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model4gtkqxvz/prophet_model-20260803144723.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:23 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_21_dept_79
Build prophet model for  store_21_dept_8

14:47:24 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/egxfcf2m.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/s80h1j5t.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=36583', 'data', 'file=/tmp/tmpjd45me00/egxfcf2m.json', 'init=/tmp/tmpjd45me00/s80h1j5t.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelztzdinu9/prophet_model-20260803144724.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:24 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_21_dept_81

14:47:24 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3drtq973.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vmd08h33.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=79970', 'data', 'file=/tmp/tmpjd45me00/3drtq973.json', 'init=/tmp/tmpjd45me00/vmd08h33.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelverp6ewq/prophet_model-20260803144724.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:24 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:24 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_21_dept_82
Build prophet model for  store_21_dept_83

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/cume1tb3.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/y2p1h3mu.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=66237', 'data', 'file=/tmp/tmpjd45me00/cume1tb3.json', 'init=/tmp/tmpjd45me00/y2p1h3mu.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model3h6buqrf/prophet_model-20260803144724.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:24 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:24 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/n3zwesha.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xqr4a_7k.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=78342', 'data', 'file=/tmp/tmpjd45me00/n3zwesha.json', 'init=/tmp/tmpjd45me00/xqr4a_7k.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelswgcjvve/prophet_model-20260803144725.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:25 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:25 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_21_dept_85
Build prophet model for  store_21_dept_87

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dwu702df.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7qxnswno.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=82597', 'data', 'file=/tmp/tmpjd45me00/dwu702df.json', 'init=/tmp/tmpjd45me00/7qxnswno.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeletulh4pu/prophet_model-20260803144725.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:25 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:25 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/lm3_5hvd.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/uzwrxynr.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=81922', 'data', 'file=/tmp/tmpjd45me00/lm3_5hvd.json', 'init=/tmp/tmpjd45me00/uzwrxynr.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelm7i2_qun/prophet_model-20260803144725.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:25 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:25 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_21_dept_9

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/tcect6om.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/w_bvoukr.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=74600', 'data', 'file=/tmp/tmpjd45me00/tcect6om.json', 'init=/tmp/tmpjd45me00/w_bvoukr.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_6vud9z8/prophet_model-20260803144725.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:25 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_21_dept_90

14:47:25 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/urongir0.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/opvn0tde.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=28025', 'data', 'file=/tmp/tmpjd45me00/urongir0.json', 'init=/tmp/tmpjd45me00/opvn0tde.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelnh2op7a3/prophet_model-20260803144726.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:26 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_21_dept_91

14:47:26 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/g6g3iexh.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4c94b8eg.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=94362', 'data', 'file=/tmp/tmpjd45me00/g6g3iexh.json', 'init=/tmp/tmpjd45me00/4c94b8eg.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model56o9se8m/prophet_model-20260803144726.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:26 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_21_dept_92

14:47:26 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/188mxwom.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/li1gk28j.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=28908', 'data', 'file=/tmp/tmpjd45me00/188mxwom.json', 'init=/tmp/tmpjd45me00/li1gk28j.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelvred7n8y/prophet_model-20260803144726.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:26 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:26 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_21_dept_93

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7212xt1p.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/enkddvn_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=28015', 'data', 'file=/tmp/tmpjd45me00/7212xt1p.json', 'init=/tmp/tmpjd45me00/enkddvn_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelf19wfw47/prophet_model-20260803144727.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:27 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_21_dept_95

14:47:27 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vm5ahq40.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2d6qd_pm.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=18690', 'data', 'file=/tmp/tmpjd45me00/vm5ahq40.json', 'init=/tmp/tmpjd45me00/2d6qd_pm.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model1vda9iu7/prophet_model-20260803144727.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:27 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:27 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_21_dept_97

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/c9ma93e_.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gg_f7p3i.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=6769', 'data', 'file=/tmp/tmpjd45me00/c9ma93e_.json', 'init=/tmp/tmpjd45me00/gg_f7p3i.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model13uplpac/prophet_model-20260803144727.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:27 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:27 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5g5uygkt.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jvx8wifx.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=49601', 'data', 'file=/tmp/tmpjd45me00/5g5uygkt.json', 'init=/tmp/tmpjd45me00/jvx8wifx.json', 'output', 'file=/tmp/tmpjd45me00/prophet_models4n12e6v/prophet_model-20260803144727.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:27 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_22_dept_1
Build prophet model for  store_22_dept_10

14:47:27 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fgqcun8r.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/j_cl77i_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=16244', 'data', 'file=/tmp/tmpjd45me00/fgqcun8r.json', 'init=/tmp/tmpjd45me00/j_cl77i_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelaxqo5qgg/prophet_model-20260803144728.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:28 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_22_dept_11

14:47:28 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3sem7n0m.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/es763no4.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=35195', 'data', 'file=/tmp/tmpjd45me00/3sem7n0m.json', 'init=/tmp/tmpjd45me00/es763no4.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model5vhhuaq_/prophet_model-20260803144728.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:28 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:28 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_22_dept_12
Build prophet model for  store_22_dept_13

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wmdyity1.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2uvtkat2.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=85806', 'data', 'file=/tmp/tmpjd45me00/wmdyity1.json', 'init=/tmp/tmpjd45me00/2uvtkat2.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modellc7klgby/prophet_model-20260803144728.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:28 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:28 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/tbzywuiy.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/iye9utb8.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=80558', 'data', 'file=/tmp/tmpjd45me00/tbzywuiy.json', 'init=/tmp/tmpjd45me00/iye9utb8.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelgsfb0uhx/prophet_model-20260803144728.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:28 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:28 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_5ymxclk.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2y28u_5b.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=50392', 'data', 'file=/tmp/tmpjd45me00/_5ymxclk.json', 'init=/tmp/tmpjd45me00/2y28u_5b.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelscknq4nw/prophet_model-20260803144728.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']

Build prophet model for  store_22_dept_14
Build prophet model for  store_22_dept_16

14:47:28 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:29 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/02mwtibd.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/elso82fl.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=20683', 'data', 'file=/tmp/tmpjd45me00/02mwtibd.json', 'init=/tmp/tmpjd45me00/elso82fl.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeluu2i_9nf/prophet_model-20260803144729.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:29 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:29 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/lijx31o4.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mncboh38.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=59979', 'data', 'file=/tmp/tmpjd45me00/lijx31o4.json', 'init=/tmp/tmpjd45me00/mncboh38.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelnfi1qumw/prophet_model-20260803144729.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:29 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_22_dept_17
Build prophet model for  store_22_dept_18

14:47:29 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wh54dgch.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/sbs_bfcj.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=12314', 'data', 'file=/tmp/tmpjd45me00/wh54dgch.json', 'init=/tmp/tmpjd45me00/sbs_bfcj.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelyarx36ge/prophet_model-20260803144729.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:29 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:29 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dyhlyjg6.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4_v5m2r7.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=71080', 'data', 'file=/tmp/tmpjd45me00/dyhlyjg6.json', 'init=/tmp/tmpjd45me00/4_v5m2r7.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model9b9vjyfd/prophet_model-20260803144729.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:29 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_22_dept_2
Build prophet model for  store_22_dept_20

14:47:29 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_57gf79v.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3i2286o6.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=88470', 'data', 'file=/tmp/tmpjd45me00/_57gf79v.json', 'init=/tmp/tmpjd45me00/3i2286o6.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model43zwp6e0/prophet_model-20260803144729.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:29 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:29 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0u8vxrij.json

Build prophet model for  store_22_dept_21
Build prophet model for  store_22_dept_22

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3n2phc3x.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=9135', 'data', 'file=/tmp/tmpjd45me00/0u8vxrij.json', 'init=/tmp/tmpjd45me00/3n2phc3x.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelbg8yfb2e/prophet_model-20260803144730.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:30 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:30 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/aooe18g2.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0fw83p75.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=43897', 'data', 'file=/tmp/tmpjd45me00/aooe18g2.json', 'init=/tmp/tmpjd45me00/0fw83p75.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model8o_zi724/prophet_model-20260803144730.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:30 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:30 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/c9e2gt6p.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8f7bwo0y.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=56638', 'data', 'file=/tmp/tmpjd45me00/c9e2gt6p.json', 'init=/tmp/tmpjd45me00/8f7bwo0y.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelco9qbm_7/prophet_model-20260803144730.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:30 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_22_dept_23
Build prophet model for  store_22_dept_24

14:47:30 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/43ety3b2.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/w30iwray.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=50610', 'data', 'file=/tmp/tmpjd45me00/43ety3b2.json', 'init=/tmp/tmpjd45me00/w30iwray.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelei5cp2jl/prophet_model-20260803144730.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:30 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:30 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_22_dept_25

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2fxdf4i4.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fhf0whgb.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=49108', 'data', 'file=/tmp/tmpjd45me00/2fxdf4i4.json', 'init=/tmp/tmpjd45me00/fhf0whgb.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelu0ygpav5/prophet_model-20260803144730.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:30 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:30 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/j75tlg7i.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ouluktn6.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=34345', 'data', 'file=/tmp/tmpjd45me00/j75tlg7i.json', 'init=/tmp/tmpjd45me00/ouluktn6.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model3n2efja_/prophet_model-20260803144730.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:30 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_22_dept_26
Build prophet model for  store_22_dept_27

14:47:30 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dtgrodk7.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mzp_nzwz.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=985', 'data', 'file=/tmp/tmpjd45me00/dtgrodk7.json', 'init=/tmp/tmpjd45me00/mzp_nzwz.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model8z1av9s1/prophet_model-20260803144731.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:31 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:31 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/tqse2byp.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6dc63czw.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=52267', 'data', 'file=/tmp/tmpjd45me00/tqse2byp.json', 'init=/tmp/tmpjd45me00/6dc63czw.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelpyu42x2l/prophet_model-20260803144731.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:31 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_22_dept_28
Build prophet model for  store_22_dept_29

14:47:31 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/snhd64v5.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bkmur57c.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=93453', 'data', 'file=/tmp/tmpjd45me00/snhd64v5.json', 'init=/tmp/tmpjd45me00/bkmur57c.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelbubrc51t/prophet_model-20260803144731.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:31 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:31 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rt869wih.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dqwjs_b4.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=3364', 'data', 'file=/tmp/tmpjd45me00/rt869wih.json', 'init=/tmp/tmpjd45me00/dqwjs_b4.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelgi9t2i5z/prophet_model-20260803144731.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:31 - cmdstanpy - INFO - Chain [1] start processing

Build prophet model for  store_22_dept_3
Build prophet model for  store_22_dept_30

INFO:cmdstanpy:Chain [1] start processing
14:47:31 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_q8xc1by.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_2fr4fc6.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=54389', 'data', 'file=/tmp/tmpjd45me00/_q8xc1by.json', 'init=/tmp/tmpjd45me00/_2fr4fc6.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeltaehhb03/prophet_model-20260803144731.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:31 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:31 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_22_dept_31
Build prophet model for  store_22_dept_32

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9x8lukws.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vkg5s7y5.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=80491', 'data', 'file=/tmp/tmpjd45me00/9x8lukws.json', 'init=/tmp/tmpjd45me00/vkg5s7y5.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelpetbhd9t/prophet_model-20260803144731.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:31 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:31 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/aealjuoz.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/uz2o5n9q.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=24261', 'data', 'file=/tmp/tmpjd45me00/aealjuoz.json', 'init=/tmp/tmpjd45me00/uz2o5n9q.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeli1tcah41/prophet_model-20260803144732.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:32 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:32 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8yatz1un.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/kwgw9slu.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None

Build prophet model for  store_22_dept_33
Build prophet model for  store_22_dept_34

DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=3714', 'data', 'file=/tmp/tmpjd45me00/8yatz1un.json', 'init=/tmp/tmpjd45me00/kwgw9slu.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelucc4qkn0/prophet_model-20260803144732.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:32 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:32 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/oji4s0df.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/cqi7owt4.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=65968', 'data', 'file=/tmp/tmpjd45me00/oji4s0df.json', 'init=/tmp/tmpjd45me00/cqi7owt4.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model1ooghp0k/prophet_model-20260803144732.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:32 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:32 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/z5rqsvvo.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/regqbf03.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=50322', 'data', 'file=/tmp/tmpjd45me00/z5rqsvvo.json', 'init=/tmp/tmpjd45me00/regqbf03.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modely7m5zq9o/prophet_model-20260803144732.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:32 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_22_dept_35
Build prophet model for  store_22_dept_36

14:47:32 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4xy24txn.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fz43nbhr.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=17326', 'data', 'file=/tmp/tmpjd45me00/4xy24txn.json', 'init=/tmp/tmpjd45me00/fz43nbhr.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model3mlefrv2/prophet_model-20260803144732.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:32 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:32 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4l6l0mo_.json

Build prophet model for  store_22_dept_38
Build prophet model for  store_22_dept_4

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/43o3jhre.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=81847', 'data', 'file=/tmp/tmpjd45me00/4l6l0mo_.json', 'init=/tmp/tmpjd45me00/43o3jhre.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelf1mf3m7c/prophet_model-20260803144732.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:32 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:32 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qqp50egj.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/uazr_dv4.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=6630', 'data', 'file=/tmp/tmpjd45me00/qqp50egj.json', 'init=/tmp/tmpjd45me00/uazr_dv4.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeletrh78df/prophet_model-20260803144732.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:32 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:33 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_22_dept_40
Build prophet model for  store_22_dept_41

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xinvjji7.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3dxsmar_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=56910', 'data', 'file=/tmp/tmpjd45me00/xinvjji7.json', 'init=/tmp/tmpjd45me00/3dxsmar_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelvvn6v3fb/prophet_model-20260803144733.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:33 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:33 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_74rqnc9.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zhe4ty40.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=56333', 'data', 'file=/tmp/tmpjd45me00/_74rqnc9.json', 'init=/tmp/tmpjd45me00/zhe4ty40.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model4oebbemi/prophet_model-20260803144733.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:33 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:33 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vvfi69sp.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9r2r9zwp.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=55417', 'data', 'file=/tmp/tmpjd45me00/vvfi69sp.json', 'init=/tmp/tmpjd45me00/9r2r9zwp.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelri1189r5/prophet_model-20260803144733.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:33 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_22_dept_42
Build prophet model for  store_22_dept_44

14:47:33 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/okdjok93.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7k7crfbl.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=56908', 'data', 'file=/tmp/tmpjd45me00/okdjok93.json', 'init=/tmp/tmpjd45me00/7k7crfbl.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelyhufgg18/prophet_model-20260803144733.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:33 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:33 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5j_72m5j.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9lhlvkgc.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=86676', 'data', 'file=/tmp/tmpjd45me00/5j_72m5j.json', 'init=/tmp/tmpjd45me00/9lhlvkgc.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelg04qa2b2/prophet_model-20260803144733.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:33 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_22_dept_46
Build prophet model for  store_22_dept_5

14:47:33 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/n_ev4yjv.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5sai0hj9.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=70275', 'data', 'file=/tmp/tmpjd45me00/n_ev4yjv.json', 'init=/tmp/tmpjd45me00/5sai0hj9.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelyo3t3yhy/prophet_model-20260803144733.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:33 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:34 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_22_dept_51
Skip  store_22_dept_51 due to lack of data
Build prophet model for  store_22_dept_52

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xhhg47dy.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/kot8d30d.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=83930', 'data', 'file=/tmp/tmpjd45me00/xhhg47dy.json', 'init=/tmp/tmpjd45me00/kot8d30d.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelee4jq3ns/prophet_model-20260803144734.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:34 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:34 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3ycdhlwl.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/t8ubx0e8.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=98947', 'data', 'file=/tmp/tmpjd45me00/3ycdhlwl.json', 'init=/tmp/tmpjd45me00/t8ubx0e8.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelk2t0sbsm/prophet_model-20260803144734.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:34 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_22_dept_54
Build prophet model for  store_22_dept_55

14:47:34 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/f3bncbdt.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_pyk59_b.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=81639', 'data', 'file=/tmp/tmpjd45me00/f3bncbdt.json', 'init=/tmp/tmpjd45me00/_pyk59_b.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model05mogemd/prophet_model-20260803144734.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:34 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:34 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_22_dept_56
Build prophet model for  store_22_dept_58

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/yoiyjulh.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/srjqfl6w.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=8880', 'data', 'file=/tmp/tmpjd45me00/yoiyjulh.json', 'init=/tmp/tmpjd45me00/srjqfl6w.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelp_0m_v34/prophet_model-20260803144734.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:34 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:34 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/lcg384r2.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/d5ptmtvb.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=9161', 'data', 'file=/tmp/tmpjd45me00/lcg384r2.json', 'init=/tmp/tmpjd45me00/d5ptmtvb.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model3w_vcnpa/prophet_model-20260803144734.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:34 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_22_dept_59

14:47:35 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5rs6kedq.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/anho9902.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=92270', 'data', 'file=/tmp/tmpjd45me00/5rs6kedq.json', 'init=/tmp/tmpjd45me00/anho9902.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model6gloov0y/prophet_model-20260803144735.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:35 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:35 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/36dciq4_.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ugi0ezlf.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=14446', 'data', 'file=/tmp/tmpjd45me00/36dciq4_.json', 'init=/tmp/tmpjd45me00/ugi0ezlf.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelqicbknkb/prophet_model-20260803144735.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:35 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_22_dept_6
Build prophet model for  store_22_dept_60

14:47:35 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dufwks7c.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/juwlau95.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=74249', 'data', 'file=/tmp/tmpjd45me00/dufwks7c.json', 'init=/tmp/tmpjd45me00/juwlau95.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model8_ntty0k/prophet_model-20260803144735.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:35 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:35 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4541fceb.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/j7bq1q76.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=83697', 'data', 'file=/tmp/tmpjd45me00/4541fceb.json', 'init=/tmp/tmpjd45me00/j7bq1q76.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelo6aid1o0/prophet_model-20260803144735.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:35 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_22_dept_67
Build prophet model for  store_22_dept_7

14:47:35 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/e_ftk22_.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jqkz8_w9.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=82118', 'data', 'file=/tmp/tmpjd45me00/e_ftk22_.json', 'init=/tmp/tmpjd45me00/jqkz8_w9.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelsj9w2owm/prophet_model-20260803144736.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:36 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:36 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/slvxtk4i.json

Build prophet model for  store_22_dept_71
Build prophet model for  store_22_dept_72

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/00iwt202.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=24268', 'data', 'file=/tmp/tmpjd45me00/slvxtk4i.json', 'init=/tmp/tmpjd45me00/00iwt202.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelhgx7no3j/prophet_model-20260803144736.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:36 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:36 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/78wk98ra.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pabpcsxy.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=34264', 'data', 'file=/tmp/tmpjd45me00/78wk98ra.json', 'init=/tmp/tmpjd45me00/pabpcsxy.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelwbkfby1u/prophet_model-20260803144736.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:36 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:36 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_22_dept_74
Build prophet model for  store_22_dept_79

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0s6raekz.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6b8f927j.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=81334', 'data', 'file=/tmp/tmpjd45me00/0s6raekz.json', 'init=/tmp/tmpjd45me00/6b8f927j.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model8frueyyc/prophet_model-20260803144736.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:36 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:36 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8jrzqmsf.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4kfx8q85.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=38853', 'data', 'file=/tmp/tmpjd45me00/8jrzqmsf.json', 'init=/tmp/tmpjd45me00/4kfx8q85.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeltonfyq7h/prophet_model-20260803144736.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:36 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:36 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/__ggfn6v.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pfwd99by.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=34575', 'data', 'file=/tmp/tmpjd45me00/__ggfn6v.json', 'init=/tmp/tmpjd45me00/pfwd99by.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelpol57cva/prophet_model-20260803144736.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:36 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_22_dept_8
Build prophet model for  store_22_dept_80

14:47:37 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/itbwcfq5.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wfqefy5i.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=5736', 'data', 'file=/tmp/tmpjd45me00/itbwcfq5.json', 'init=/tmp/tmpjd45me00/wfqefy5i.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelkfwiflx6/prophet_model-20260803144737.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:37 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:37 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_22_dept_81

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bng3all2.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zdvqial5.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=6055', 'data', 'file=/tmp/tmpjd45me00/bng3all2.json', 'init=/tmp/tmpjd45me00/zdvqial5.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelqqnaky02/prophet_model-20260803144737.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:37 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:37 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ks3sgh36.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/e6jx6qlz.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=18312', 'data', 'file=/tmp/tmpjd45me00/ks3sgh36.json', 'init=/tmp/tmpjd45me00/e6jx6qlz.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model235c49gi/prophet_model-20260803144737.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:37 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_22_dept_82
Build prophet model for  store_22_dept_83

14:47:37 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2srrcmxb.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9xt7ajij.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=17162', 'data', 'file=/tmp/tmpjd45me00/2srrcmxb.json', 'init=/tmp/tmpjd45me00/9xt7ajij.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model69kdzbw1/prophet_model-20260803144737.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:37 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_22_dept_85

14:47:38 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/23jrufqz.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/eijkg6ob.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=48520', 'data', 'file=/tmp/tmpjd45me00/23jrufqz.json', 'init=/tmp/tmpjd45me00/eijkg6ob.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model35rj7k9_/prophet_model-20260803144738.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:38 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:38 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_22_dept_87

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jbarcmjx.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1i896hf4.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=52669', 'data', 'file=/tmp/tmpjd45me00/jbarcmjx.json', 'init=/tmp/tmpjd45me00/1i896hf4.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelh1d6mjuq/prophet_model-20260803144738.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:38 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:38 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_22_dept_9

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vtfhdfe6.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9mdgrmrt.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=84388', 'data', 'file=/tmp/tmpjd45me00/vtfhdfe6.json', 'init=/tmp/tmpjd45me00/9mdgrmrt.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model43rq1hh9/prophet_model-20260803144739.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:39 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:39 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_22_dept_90
Build prophet model for  store_22_dept_91

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/c8k78upu.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4brodi7d.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=16166', 'data', 'file=/tmp/tmpjd45me00/c8k78upu.json', 'init=/tmp/tmpjd45me00/4brodi7d.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelzd11ozrw/prophet_model-20260803144739.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:39 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:39 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2rv2k8op.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/eibuojw5.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=41223', 'data', 'file=/tmp/tmpjd45me00/2rv2k8op.json', 'init=/tmp/tmpjd45me00/eibuojw5.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeld3ovnyhd/prophet_model-20260803144739.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:39 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:39 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_22_dept_92
Build prophet model for  store_22_dept_93

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/f9j64qdx.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ij5trujk.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=20044', 'data', 'file=/tmp/tmpjd45me00/f9j64qdx.json', 'init=/tmp/tmpjd45me00/ij5trujk.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelzk7ioivv/prophet_model-20260803144739.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:39 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:40 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/j2gb9wyf.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/lps1c5pg.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=20688', 'data', 'file=/tmp/tmpjd45me00/j2gb9wyf.json', 'init=/tmp/tmpjd45me00/lps1c5pg.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeljaggutcj/prophet_model-20260803144740.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:40 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:40 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_22_dept_95

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/23lowzdh.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/opcnhjjt.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=67885', 'data', 'file=/tmp/tmpjd45me00/23lowzdh.json', 'init=/tmp/tmpjd45me00/opcnhjjt.json', 'output', 'file=/tmp/tmpjd45me00/prophet_models1jq3x55/prophet_model-20260803144740.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:40 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:40 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_22_dept_97

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/h4by4jpa.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/o2y_nmhb.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=90081', 'data', 'file=/tmp/tmpjd45me00/h4by4jpa.json', 'init=/tmp/tmpjd45me00/o2y_nmhb.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeln2q46e24/prophet_model-20260803144740.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:40 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:40 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5r1hoepl.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/58jxy94s.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=2460', 'data', 'file=/tmp/tmpjd45me00/5r1hoepl.json', 'init=/tmp/tmpjd45me00/58jxy94s.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelc5oll785/prophet_model-20260803144741.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']

Build prophet model for  store_23_dept_1
Build prophet model for  store_23_dept_10

14:47:41 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:41 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7s70tg43.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fpbr2wir.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=15124', 'data', 'file=/tmp/tmpjd45me00/7s70tg43.json', 'init=/tmp/tmpjd45me00/fpbr2wir.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelkxoww2nz/prophet_model-20260803144741.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:41 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:41 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/c3l2v710.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/99zv5v9t.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=42294', 'data', 'file=/tmp/tmpjd45me00/c3l2v710.json', 'init=/tmp/tmpjd45me00/99zv5v9t.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model5_ta3xjk/prophet_model-20260803144741.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:41 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_23_dept_11
Build prophet model for  store_23_dept_12

14:47:41 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8jbvr6xv.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1z7g3kgv.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=40557', 'data', 'file=/tmp/tmpjd45me00/8jbvr6xv.json', 'init=/tmp/tmpjd45me00/1z7g3kgv.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelzvzasfvy/prophet_model-20260803144741.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:41 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:41 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_23_dept_13
Build prophet model for  store_23_dept_14

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5r05vfpz.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wxqz2h6d.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=8869', 'data', 'file=/tmp/tmpjd45me00/5r05vfpz.json', 'init=/tmp/tmpjd45me00/wxqz2h6d.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model37ak_fnm/prophet_model-20260803144741.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:41 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:41 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xtjlta_e.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hgliyodo.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=23046', 'data', 'file=/tmp/tmpjd45me00/xtjlta_e.json', 'init=/tmp/tmpjd45me00/hgliyodo.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeln0crhwo6/prophet_model-20260803144742.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:42 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:42 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qzg9ddkj.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/69sbezx1.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=12227', 'data', 'file=/tmp/tmpjd45me00/qzg9ddkj.json', 'init=/tmp/tmpjd45me00/69sbezx1.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelma9xcra_/prophet_model-20260803144742.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:42 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_23_dept_16
Build prophet model for  store_23_dept_17

14:47:42 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/b1y8ymr9.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2rhb_pjv.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=21935', 'data', 'file=/tmp/tmpjd45me00/b1y8ymr9.json', 'init=/tmp/tmpjd45me00/2rhb_pjv.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelbsgxzqnv/prophet_model-20260803144742.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:42 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:42 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0odm6a_m.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fncz_2vt.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=22650', 'data', 'file=/tmp/tmpjd45me00/0odm6a_m.json', 'init=/tmp/tmpjd45me00/fncz_2vt.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelxy0ss7gl/prophet_model-20260803144742.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:42 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_23_dept_18
Build prophet model for  store_23_dept_19

14:47:42 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wt9y2j6x.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2bqv_y97.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=40234', 'data', 'file=/tmp/tmpjd45me00/wt9y2j6x.json', 'init=/tmp/tmpjd45me00/2bqv_y97.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelx4rmyeka/prophet_model-20260803144743.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:43 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:43 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_23_dept_2
Build prophet model for  store_23_dept_20

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2lioa_8d.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/iwydueqh.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=2443', 'data', 'file=/tmp/tmpjd45me00/2lioa_8d.json', 'init=/tmp/tmpjd45me00/iwydueqh.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model7qvdi8m8/prophet_model-20260803144743.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:43 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:43 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/l5fz8hhx.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/k4cs6y5g.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=85998', 'data', 'file=/tmp/tmpjd45me00/l5fz8hhx.json', 'init=/tmp/tmpjd45me00/k4cs6y5g.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelbiyqx991/prophet_model-20260803144743.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:43 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:43 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_23_dept_21
Build prophet model for  store_23_dept_22

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/d9yczaeg.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/sj_ecjwz.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=36493', 'data', 'file=/tmp/tmpjd45me00/d9yczaeg.json', 'init=/tmp/tmpjd45me00/sj_ecjwz.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelkv11kru9/prophet_model-20260803144743.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:43 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:43 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/45trchct.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9ibsa6lt.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=53999', 'data', 'file=/tmp/tmpjd45me00/45trchct.json', 'init=/tmp/tmpjd45me00/9ibsa6lt.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model6p9wy3xb/prophet_model-20260803144743.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:43 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:43 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ws9inh3k.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rqshsyxa.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=21218', 'data', 'file=/tmp/tmpjd45me00/ws9inh3k.json', 'init=/tmp/tmpjd45me00/rqshsyxa.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model7713wt12/prophet_model-20260803144743.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:43 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_23_dept_23
Build prophet model for  store_23_dept_24

14:47:43 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/87j4ytbr.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/yz7um7_s.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=37407', 'data', 'file=/tmp/tmpjd45me00/87j4ytbr.json', 'init=/tmp/tmpjd45me00/yz7um7_s.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelwhtvx8e0/prophet_model-20260803144744.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:44 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_23_dept_25

14:47:44 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7g8l62fb.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/aek41eb4.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=1987', 'data', 'file=/tmp/tmpjd45me00/7g8l62fb.json', 'init=/tmp/tmpjd45me00/aek41eb4.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelnv_x893z/prophet_model-20260803144744.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:44 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:44 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/p8y3mx_h.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mtyw7lf9.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=86902', 'data', 'file=/tmp/tmpjd45me00/p8y3mx_h.json', 'init=/tmp/tmpjd45me00/mtyw7lf9.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelvi6a34vm/prophet_model-20260803144744.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:44 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_23_dept_26
Build prophet model for  store_23_dept_27

14:47:44 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6h0j2jla.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/lkfz55f6.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=51014', 'data', 'file=/tmp/tmpjd45me00/6h0j2jla.json', 'init=/tmp/tmpjd45me00/lkfz55f6.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelzuqbs55m/prophet_model-20260803144744.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:44 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:45 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_23_dept_28
Build prophet model for  store_23_dept_29

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/yhbq9xwk.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/unzf2630.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=6635', 'data', 'file=/tmp/tmpjd45me00/yhbq9xwk.json', 'init=/tmp/tmpjd45me00/unzf2630.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model1w60bqvw/prophet_model-20260803144745.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:45 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:45 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fghg9y7t.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/e9cem9xt.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=52927', 'data', 'file=/tmp/tmpjd45me00/fghg9y7t.json', 'init=/tmp/tmpjd45me00/e9cem9xt.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelxn3a1hcx/prophet_model-20260803144745.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:45 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_23_dept_3

14:47:45 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9fz6l9jb.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/iji4c4mr.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=79744', 'data', 'file=/tmp/tmpjd45me00/9fz6l9jb.json', 'init=/tmp/tmpjd45me00/iji4c4mr.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelr08jzxj8/prophet_model-20260803144745.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:45 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:45 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_23_dept_30
Build prophet model for  store_23_dept_31

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/tic1mmdk.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qzii09cy.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=76337', 'data', 'file=/tmp/tmpjd45me00/tic1mmdk.json', 'init=/tmp/tmpjd45me00/qzii09cy.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelokusjgnl/prophet_model-20260803144746.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:46 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:46 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/tres708u.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/chhj2ntv.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=9531', 'data', 'file=/tmp/tmpjd45me00/tres708u.json', 'init=/tmp/tmpjd45me00/chhj2ntv.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelukcetqju/prophet_model-20260803144746.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:46 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:46 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mk_hqq7s.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/l37e7e7t.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=34581', 'data', 'file=/tmp/tmpjd45me00/mk_hqq7s.json', 'init=/tmp/tmpjd45me00/l37e7e7t.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model4shtpn4u/prophet_model-20260803144746.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:46 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_23_dept_32
Build prophet model for  store_23_dept_33

14:47:46 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5826hcx3.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/njr08ajy.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=61958', 'data', 'file=/tmp/tmpjd45me00/5826hcx3.json', 'init=/tmp/tmpjd45me00/njr08ajy.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelpisjp_9p/prophet_model-20260803144746.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:46 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:46 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dqbblc_s.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_czr3x6m.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=95307', 'data', 'file=/tmp/tmpjd45me00/dqbblc_s.json', 'init=/tmp/tmpjd45me00/_czr3x6m.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelsetf394d/prophet_model-20260803144746.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:46 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:46 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_23_dept_34
Build prophet model for  store_23_dept_35

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/g3dgjhve.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/netk1vwb.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=15462', 'data', 'file=/tmp/tmpjd45me00/g3dgjhve.json', 'init=/tmp/tmpjd45me00/netk1vwb.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelpum6c41x/prophet_model-20260803144746.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:46 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:47 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_23_dept_36

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4w6b4s86.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/84zayehy.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=36108', 'data', 'file=/tmp/tmpjd45me00/4w6b4s86.json', 'init=/tmp/tmpjd45me00/84zayehy.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelftwnvey1/prophet_model-20260803144747.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:47 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:47 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_23_dept_38
Build prophet model for  store_23_dept_4

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xxakkakw.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/yy3tf9e2.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=39884', 'data', 'file=/tmp/tmpjd45me00/xxakkakw.json', 'init=/tmp/tmpjd45me00/yy3tf9e2.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelcgsu8a__/prophet_model-20260803144747.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:47 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:47 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vlx7segc.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/p5x78xw4.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=43731', 'data', 'file=/tmp/tmpjd45me00/vlx7segc.json', 'init=/tmp/tmpjd45me00/p5x78xw4.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelsgssl889/prophet_model-20260803144747.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:47 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_23_dept_40

14:47:47 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/kqczyf2g.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xsk16nwj.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=32526', 'data', 'file=/tmp/tmpjd45me00/kqczyf2g.json', 'init=/tmp/tmpjd45me00/xsk16nwj.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model6ang8t2r/prophet_model-20260803144747.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:47 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:47 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7t3v3l3p.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/61avcvlw.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None

Build prophet model for  store_23_dept_41
Build prophet model for  store_23_dept_42

DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=39446', 'data', 'file=/tmp/tmpjd45me00/7t3v3l3p.json', 'init=/tmp/tmpjd45me00/61avcvlw.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modellbp38ssa/prophet_model-20260803144748.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:48 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:48 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mnt_5co9.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/t1bfcup9.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=35762', 'data', 'file=/tmp/tmpjd45me00/mnt_5co9.json', 'init=/tmp/tmpjd45me00/t1bfcup9.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model0fhaf6pu/prophet_model-20260803144748.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:48 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:48 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/elcdqn6w.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/z0n0ph4n.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=73740', 'data', 'file=/tmp/tmpjd45me00/elcdqn6w.json', 'init=/tmp/tmpjd45me00/z0n0ph4n.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelvnauc43c/prophet_model-20260803144748.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:48 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_23_dept_44
Build prophet model for  store_23_dept_45

14:47:48 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/a5z58ha7.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rjohllxd.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=63021', 'data', 'file=/tmp/tmpjd45me00/a5z58ha7.json', 'init=/tmp/tmpjd45me00/rjohllxd.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelolzxg8rd/prophet_model-20260803144748.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:48 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:48 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4o7vqkgb.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/o5dolluh.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=31012', 'data', 'file=/tmp/tmpjd45me00/4o7vqkgb.json', 'init=/tmp/tmpjd45me00/o5dolluh.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelncr42jez/prophet_model-20260803144748.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:48 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_23_dept_46
Build prophet model for  store_23_dept_49

14:47:48 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4_tvfuei.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vjal7__t.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=10150', 'data', 'file=/tmp/tmpjd45me00/4_tvfuei.json', 'init=/tmp/tmpjd45me00/vjal7__t.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelin4hle92/prophet_model-20260803144748.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:48 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:49 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/yso6hzvc.json

Build prophet model for  store_23_dept_5
Build prophet model for  store_23_dept_50

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hk_3k0zk.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=4590', 'data', 'file=/tmp/tmpjd45me00/yso6hzvc.json', 'init=/tmp/tmpjd45me00/hk_3k0zk.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model7mm41_mi/prophet_model-20260803144749.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:49 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:49 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zu4sv5nk.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/z0fxyyo8.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=43519', 'data', 'file=/tmp/tmpjd45me00/zu4sv5nk.json', 'init=/tmp/tmpjd45me00/z0fxyyo8.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelhe9kedfx/prophet_model-20260803144749.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:49 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:49 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_23_dept_51
Skip  store_23_dept_51 due to lack of data
Build prophet model for  store_23_dept_52
Build prophet model for  store_23_dept_54

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/025wjlct.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/h82sylj_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=64094', 'data', 'file=/tmp/tmpjd45me00/025wjlct.json', 'init=/tmp/tmpjd45me00/h82sylj_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelqko4rn50/prophet_model-20260803144749.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:49 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:49 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2b6yy3tu.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5dy0f423.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=8246', 'data', 'file=/tmp/tmpjd45me00/2b6yy3tu.json', 'init=/tmp/tmpjd45me00/5dy0f423.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelqgeb_b4x/prophet_model-20260803144749.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:49 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:49 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_x1bzaip.json

Build prophet model for  store_23_dept_55
Build prophet model for  store_23_dept_56

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/k5jr8ywt.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=39877', 'data', 'file=/tmp/tmpjd45me00/_x1bzaip.json', 'init=/tmp/tmpjd45me00/k5jr8ywt.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeldhrml6ge/prophet_model-20260803144749.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:49 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:50 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mdd0lzml.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/own344j7.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=58108', 'data', 'file=/tmp/tmpjd45me00/mdd0lzml.json', 'init=/tmp/tmpjd45me00/own344j7.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeljg7lr_da/prophet_model-20260803144750.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:50 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:50 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_23_dept_58
Build prophet model for  store_23_dept_59

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/c3qnx8kr.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/66l_4wp1.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=67566', 'data', 'file=/tmp/tmpjd45me00/c3qnx8kr.json', 'init=/tmp/tmpjd45me00/66l_4wp1.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelujtbm0km/prophet_model-20260803144750.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:50 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:50 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gupc80yv.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/h3w9f671.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=74955', 'data', 'file=/tmp/tmpjd45me00/gupc80yv.json', 'init=/tmp/tmpjd45me00/h3w9f671.json', 'output', 'file=/tmp/tmpjd45me00/prophet_models6ab8ytf/prophet_model-20260803144750.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:50 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:50 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_23_dept_6
Build prophet model for  store_23_dept_67

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6vh5we36.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/cz5pr4ab.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=4668', 'data', 'file=/tmp/tmpjd45me00/6vh5we36.json', 'init=/tmp/tmpjd45me00/cz5pr4ab.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model7sy0ut8a/prophet_model-20260803144751.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:51 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:51 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/omx3zpx6.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ql0pnb4r.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=95635', 'data', 'file=/tmp/tmpjd45me00/omx3zpx6.json', 'init=/tmp/tmpjd45me00/ql0pnb4r.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelpsdn5c3f/prophet_model-20260803144751.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:51 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_23_dept_7

14:47:51 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1rb6v4cu.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/f4w4pm0t.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=82', 'data', 'file=/tmp/tmpjd45me00/1rb6v4cu.json', 'init=/tmp/tmpjd45me00/f4w4pm0t.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelz20seat1/prophet_model-20260803144751.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:51 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:51 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_23_dept_71

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/kdr5oo9e.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/c4dvloua.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=38590', 'data', 'file=/tmp/tmpjd45me00/kdr5oo9e.json', 'init=/tmp/tmpjd45me00/c4dvloua.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeli358btal/prophet_model-20260803144751.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:51 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:51 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_23_dept_72

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fzsppd29.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4cgyofsn.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=5904', 'data', 'file=/tmp/tmpjd45me00/fzsppd29.json', 'init=/tmp/tmpjd45me00/4cgyofsn.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelxkeanrsu/prophet_model-20260803144752.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:52 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:52 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_23_dept_74

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/yguqm044.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/w2wuwc1y.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=1627', 'data', 'file=/tmp/tmpjd45me00/yguqm044.json', 'init=/tmp/tmpjd45me00/w2wuwc1y.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeltlq3m_dm/prophet_model-20260803144752.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:52 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:52 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_23_dept_79
Build prophet model for  store_23_dept_8

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/uhxplc1y.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1ut72lns.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=28869', 'data', 'file=/tmp/tmpjd45me00/uhxplc1y.json', 'init=/tmp/tmpjd45me00/1ut72lns.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeln0327o80/prophet_model-20260803144752.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:52 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:52 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/md5ye5ne.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/texsicb_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=86324', 'data', 'file=/tmp/tmpjd45me00/md5ye5ne.json', 'init=/tmp/tmpjd45me00/texsicb_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model1gog2uxl/prophet_model-20260803144752.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:52 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:52 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_23_dept_81

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8vorucrw.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/30vw3j4_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=95505', 'data', 'file=/tmp/tmpjd45me00/8vorucrw.json', 'init=/tmp/tmpjd45me00/30vw3j4_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelgal09ia_/prophet_model-20260803144753.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:53 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:53 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_23_dept_82
Build prophet model for  store_23_dept_83

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_aup4j1j.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/q169eel5.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=3292', 'data', 'file=/tmp/tmpjd45me00/_aup4j1j.json', 'init=/tmp/tmpjd45me00/q169eel5.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model3f2tz1je/prophet_model-20260803144753.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:53 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:53 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7fjlury8.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_2o3gchr.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=52654', 'data', 'file=/tmp/tmpjd45me00/7fjlury8.json', 'init=/tmp/tmpjd45me00/_2o3gchr.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeleb_3j6y5/prophet_model-20260803144753.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:53 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_23_dept_85

14:47:54 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0f_vjlsd.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ezgn6oh0.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=27333', 'data', 'file=/tmp/tmpjd45me00/0f_vjlsd.json', 'init=/tmp/tmpjd45me00/ezgn6oh0.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modellc_8mwl0/prophet_model-20260803144754.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:54 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:54 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8gs2nbnl.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xht8a7ee.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=28073', 'data', 'file=/tmp/tmpjd45me00/8gs2nbnl.json', 'init=/tmp/tmpjd45me00/xht8a7ee.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelzf4h_pzl/prophet_model-20260803144754.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:54 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_23_dept_87
Build prophet model for  store_23_dept_9

14:47:54 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9nnkedhg.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ibk4zpyq.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=68209', 'data', 'file=/tmp/tmpjd45me00/9nnkedhg.json', 'init=/tmp/tmpjd45me00/ibk4zpyq.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model8r0v7onq/prophet_model-20260803144754.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:54 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_23_dept_90

14:47:54 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6e1t3ruc.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qqg5jmo8.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=92517', 'data', 'file=/tmp/tmpjd45me00/6e1t3ruc.json', 'init=/tmp/tmpjd45me00/qqg5jmo8.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model6ziyb9v5/prophet_model-20260803144754.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:54 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_23_dept_91

14:47:55 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wxhvyb9g.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/iyu1jq9z.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=3634', 'data', 'file=/tmp/tmpjd45me00/wxhvyb9g.json', 'init=/tmp/tmpjd45me00/iyu1jq9z.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeljb_sqc0y/prophet_model-20260803144755.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:55 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_23_dept_92

14:47:55 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2nrpshvl.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jy2_balh.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=68386', 'data', 'file=/tmp/tmpjd45me00/2nrpshvl.json', 'init=/tmp/tmpjd45me00/jy2_balh.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelldc79t8t/prophet_model-20260803144755.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:55 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_23_dept_93

14:47:55 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xbw5t08k.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/km4y3ury.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=11079', 'data', 'file=/tmp/tmpjd45me00/xbw5t08k.json', 'init=/tmp/tmpjd45me00/km4y3ury.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelcemvp8bn/prophet_model-20260803144756.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:47:56 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_23_dept_94

14:47:57 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/cksiw78o.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/uh21f3v7.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=80275', 'data', 'file=/tmp/tmpjd45me00/cksiw78o.json', 'init=/tmp/tmpjd45me00/uh21f3v7.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeldnkrhlr2/prophet_model-20260803144757.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:57 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_23_dept_95

14:47:57 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xfs4jn6f.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2_uvph1a.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=18431', 'data', 'file=/tmp/tmpjd45me00/xfs4jn6f.json', 'init=/tmp/tmpjd45me00/2_uvph1a.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeljokv_om1/prophet_model-20260803144757.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:57 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_23_dept_96

14:47:57 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/v_o99smy.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ag5cuiqq.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=7806', 'data', 'file=/tmp/tmpjd45me00/v_o99smy.json', 'init=/tmp/tmpjd45me00/ag5cuiqq.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model46wb454l/prophet_model-20260803144757.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:57 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_23_dept_97

14:47:58 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/t_ypgdgy.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0ef6j8fy.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=56052', 'data', 'file=/tmp/tmpjd45me00/t_ypgdgy.json', 'init=/tmp/tmpjd45me00/0ef6j8fy.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model34q08jl_/prophet_model-20260803144758.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:58 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:58 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_24_dept_1

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6_0hhilp.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/uilyt9ze.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=22492', 'data', 'file=/tmp/tmpjd45me00/6_0hhilp.json', 'init=/tmp/tmpjd45me00/uilyt9ze.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelq2f_9gvu/prophet_model-20260803144758.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:58 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:59 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_24_dept_10

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/nl9rxoug.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0id8zlkv.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=4922', 'data', 'file=/tmp/tmpjd45me00/nl9rxoug.json', 'init=/tmp/tmpjd45me00/0id8zlkv.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelz4nnej0g/prophet_model-20260803144759.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:59 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:59 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ooo_d1aa.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jd5ab961.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=24336', 'data', 'file=/tmp/tmpjd45me00/ooo_d1aa.json', 'init=/tmp/tmpjd45me00/jd5ab961.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeli7id6a8b/prophet_model-20260803144759.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:59 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_24_dept_11
Build prophet model for  store_24_dept_12

14:47:59 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/par1xsz5.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/r1v2ucvh.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=2785', 'data', 'file=/tmp/tmpjd45me00/par1xsz5.json', 'init=/tmp/tmpjd45me00/r1v2ucvh.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modely7dccpdt/prophet_model-20260803144759.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:59 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:59 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_24_dept_13

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/48pd4fbs.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2ko76xa7.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=1555', 'data', 'file=/tmp/tmpjd45me00/48pd4fbs.json', 'init=/tmp/tmpjd45me00/2ko76xa7.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelyuyeje0o/prophet_model-20260803144759.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:47:59 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:47:59 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dti3jyr2.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xhjv0dai.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=19704', 'data', 'file=/tmp/tmpjd45me00/dti3jyr2.json', 'init=/tmp/tmpjd45me00/xhjv0dai.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelb50qowte/prophet_model-20260803144800.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:00 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_24_dept_14
Build prophet model for  store_24_dept_16

14:48:00 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8jkzu_v8.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/c8m1ntpu.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=11667', 'data', 'file=/tmp/tmpjd45me00/8jkzu_v8.json', 'init=/tmp/tmpjd45me00/c8m1ntpu.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model5gz47ijp/prophet_model-20260803144800.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:00 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:00 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/d0_ubfli.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jri7wj9w.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=90433', 'data', 'file=/tmp/tmpjd45me00/d0_ubfli.json', 'init=/tmp/tmpjd45me00/jri7wj9w.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model40mqcna0/prophet_model-20260803144800.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:00 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_24_dept_17
Build prophet model for  store_24_dept_18

14:48:00 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/smwbd4gd.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3h28v3od.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=21196', 'data', 'file=/tmp/tmpjd45me00/smwbd4gd.json', 'init=/tmp/tmpjd45me00/3h28v3od.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model6j1funv5/prophet_model-20260803144800.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:00 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:00 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/et5phk9k.json

Build prophet model for  store_24_dept_19
Build prophet model for  store_24_dept_2

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/sv1z40ri.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=28245', 'data', 'file=/tmp/tmpjd45me00/et5phk9k.json', 'init=/tmp/tmpjd45me00/sv1z40ri.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model7wjlev48/prophet_model-20260803144800.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:00 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:00 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ckhbqeuo.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9t9er5rx.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=41761', 'data', 'file=/tmp/tmpjd45me00/ckhbqeuo.json', 'init=/tmp/tmpjd45me00/9t9er5rx.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model9dxu6n7r/prophet_model-20260803144801.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:01 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:01 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_24_dept_20
Build prophet model for  store_24_dept_21

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/n188jot7.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ibpfnfwc.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=42654', 'data', 'file=/tmp/tmpjd45me00/n188jot7.json', 'init=/tmp/tmpjd45me00/ibpfnfwc.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelx2trw5d9/prophet_model-20260803144801.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:01 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:01 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1b1cvshj.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vhc_j4kv.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=63317', 'data', 'file=/tmp/tmpjd45me00/1b1cvshj.json', 'init=/tmp/tmpjd45me00/vhc_j4kv.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model3plm_n1d/prophet_model-20260803144801.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:01 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:01 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bp7hldb7.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_6w775np.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=61368', 'data', 'file=/tmp/tmpjd45me00/bp7hldb7.json', 'init=/tmp/tmpjd45me00/_6w775np.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model9zka3748/prophet_model-20260803144801.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:01 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_24_dept_22
Build prophet model for  store_24_dept_23

14:48:01 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bml9p5pj.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wgznb9s1.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=41546', 'data', 'file=/tmp/tmpjd45me00/bml9p5pj.json', 'init=/tmp/tmpjd45me00/wgznb9s1.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model1eefyh7i/prophet_model-20260803144801.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:01 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:02 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/krprxm7z.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/l0r2559i.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=22347', 'data', 'file=/tmp/tmpjd45me00/krprxm7z.json', 'init=/tmp/tmpjd45me00/l0r2559i.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelpm88w7qs/prophet_model-20260803144802.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:02 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_24_dept_24
Build prophet model for  store_24_dept_25

14:48:02 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/yi__jsm9.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jjz0oi8g.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=7367', 'data', 'file=/tmp/tmpjd45me00/yi__jsm9.json', 'init=/tmp/tmpjd45me00/jjz0oi8g.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model6jntf4rf/prophet_model-20260803144802.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:02 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:02 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/43axem5k.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5_s8b8z_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=79982', 'data', 'file=/tmp/tmpjd45me00/43axem5k.json', 'init=/tmp/tmpjd45me00/5_s8b8z_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelxrobhrqz/prophet_model-20260803144802.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:02 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_24_dept_26
Build prophet model for  store_24_dept_27

14:48:02 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bp4sk64s.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/y1ujciit.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=68314', 'data', 'file=/tmp/tmpjd45me00/bp4sk64s.json', 'init=/tmp/tmpjd45me00/y1ujciit.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model3i642jbz/prophet_model-20260803144802.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:02 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:02 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_24_dept_28

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/233gltnp.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_6iaxdn5.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=76206', 'data', 'file=/tmp/tmpjd45me00/233gltnp.json', 'init=/tmp/tmpjd45me00/_6iaxdn5.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelhu8qv6tz/prophet_model-20260803144802.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:02 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:02 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/j5nbptv6.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/sxkzdif6.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=89870', 'data', 'file=/tmp/tmpjd45me00/j5nbptv6.json', 'init=/tmp/tmpjd45me00/sxkzdif6.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelzs1r94kv/prophet_model-20260803144803.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:03 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_24_dept_29
Build prophet model for  store_24_dept_3

14:48:03 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/z4o4f03_.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/s4v9sui3.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=24737', 'data', 'file=/tmp/tmpjd45me00/z4o4f03_.json', 'init=/tmp/tmpjd45me00/s4v9sui3.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelv_kj57zn/prophet_model-20260803144803.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:03 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:03 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_24_dept_30

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/on50269d.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/q6gpphm2.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=54326', 'data', 'file=/tmp/tmpjd45me00/on50269d.json', 'init=/tmp/tmpjd45me00/q6gpphm2.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelyrepvxtp/prophet_model-20260803144803.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:03 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_24_dept_31

14:48:03 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/um4s03mm.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/iq93vhnp.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=29224', 'data', 'file=/tmp/tmpjd45me00/um4s03mm.json', 'init=/tmp/tmpjd45me00/iq93vhnp.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeldsa26815/prophet_model-20260803144803.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:03 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:03 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_24_dept_32
Build prophet model for  store_24_dept_33

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xa5xri7t.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xhs5z91v.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=3873', 'data', 'file=/tmp/tmpjd45me00/xa5xri7t.json', 'init=/tmp/tmpjd45me00/xhs5z91v.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model8ow9zasl/prophet_model-20260803144804.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:04 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:04 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/g1w6htpl.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/a1jsybcq.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=37941', 'data', 'file=/tmp/tmpjd45me00/g1w6htpl.json', 'init=/tmp/tmpjd45me00/a1jsybcq.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelilv6vxcq/prophet_model-20260803144804.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:04 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:04 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_24_dept_34

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/q2u3f7ka.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/t3rypz2u.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=66044', 'data', 'file=/tmp/tmpjd45me00/q2u3f7ka.json', 'init=/tmp/tmpjd45me00/t3rypz2u.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_06r1ze4/prophet_model-20260803144804.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:04 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:04 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_24_dept_35

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6kk0p2ym.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2v_bhg0g.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=72968', 'data', 'file=/tmp/tmpjd45me00/6kk0p2ym.json', 'init=/tmp/tmpjd45me00/2v_bhg0g.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelx0kyjf5u/prophet_model-20260803144804.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:04 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_24_dept_36

14:48:04 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gdxrnwix.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/t7qgu6h_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=90279', 'data', 'file=/tmp/tmpjd45me00/gdxrnwix.json', 'init=/tmp/tmpjd45me00/t7qgu6h_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeloxd1phwv/prophet_model-20260803144805.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:05 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_24_dept_37

14:48:05 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hee5xd4x.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3fton786.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=82942', 'data', 'file=/tmp/tmpjd45me00/hee5xd4x.json', 'init=/tmp/tmpjd45me00/3fton786.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelz_2_leua/prophet_model-20260803144805.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:05 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:05 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_24_dept_38

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/iu2760ts.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/007gxozz.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=5727', 'data', 'file=/tmp/tmpjd45me00/iu2760ts.json', 'init=/tmp/tmpjd45me00/007gxozz.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_kmqn5ev/prophet_model-20260803144805.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:05 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:05 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_24_dept_4
Build prophet model for  store_24_dept_40

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/e8k5ao9q.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/s9kj_52_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=98614', 'data', 'file=/tmp/tmpjd45me00/e8k5ao9q.json', 'init=/tmp/tmpjd45me00/s9kj_52_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model3lqnx3jp/prophet_model-20260803144806.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:06 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:06 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3c7xzvby.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dcvyij94.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=6271', 'data', 'file=/tmp/tmpjd45me00/3c7xzvby.json', 'init=/tmp/tmpjd45me00/dcvyij94.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelcr08_q_o/prophet_model-20260803144806.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:06 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_24_dept_41

14:48:06 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4y056_to.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/o8qrzyi5.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=16939', 'data', 'file=/tmp/tmpjd45me00/4y056_to.json', 'init=/tmp/tmpjd45me00/o8qrzyi5.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeluhykpd50/prophet_model-20260803144806.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:06 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_24_dept_42

14:48:07 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/iw5lz7in.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/aak5qm20.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=91703', 'data', 'file=/tmp/tmpjd45me00/iw5lz7in.json', 'init=/tmp/tmpjd45me00/aak5qm20.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelknne6ble/prophet_model-20260803144807.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:07 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:07 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_24_dept_44
Build prophet model for  store_24_dept_46

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jnn9eg0i.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ivv3gu4m.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=32199', 'data', 'file=/tmp/tmpjd45me00/jnn9eg0i.json', 'init=/tmp/tmpjd45me00/ivv3gu4m.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model7esoiuvo/prophet_model-20260803144807.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:07 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:07 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jvn0lm51.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/26myf897.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=16289', 'data', 'file=/tmp/tmpjd45me00/jvn0lm51.json', 'init=/tmp/tmpjd45me00/26myf897.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelunv878sp/prophet_model-20260803144807.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:07 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:07 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bfdnxe_v.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_41giq9q.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=30795', 'data', 'file=/tmp/tmpjd45me00/bfdnxe_v.json', 'init=/tmp/tmpjd45me00/_41giq9q.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelrjxecrl9/prophet_model-20260803144807.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:07 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_24_dept_49
Build prophet model for  store_24_dept_5

14:48:07 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/icbnrg_s.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fqt9f2l6.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=3590', 'data', 'file=/tmp/tmpjd45me00/icbnrg_s.json', 'init=/tmp/tmpjd45me00/fqt9f2l6.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model5ouimwqt/prophet_model-20260803144807.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:07 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:07 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ryvqtsvy.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hbmp6ml4.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=94427', 'data', 'file=/tmp/tmpjd45me00/ryvqtsvy.json', 'init=/tmp/tmpjd45me00/hbmp6ml4.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelh7n1fk7j/prophet_model-20260803144807.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:07 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_24_dept_50
Build prophet model for  store_24_dept_52

14:48:08 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1ik_fcwe.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3wu1yprw.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=22295', 'data', 'file=/tmp/tmpjd45me00/1ik_fcwe.json', 'init=/tmp/tmpjd45me00/3wu1yprw.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model4mjhctoy/prophet_model-20260803144808.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:08 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:08 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/a5bflc5r.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/elf6oy_m.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=59824', 'data', 'file=/tmp/tmpjd45me00/a5bflc5r.json', 'init=/tmp/tmpjd45me00/elf6oy_m.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model4oofnfx7/prophet_model-20260803144808.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:08 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:08 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_24_dept_54
Build prophet model for  store_24_dept_55

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3girn8ti.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/m8798grs.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=44270', 'data', 'file=/tmp/tmpjd45me00/3girn8ti.json', 'init=/tmp/tmpjd45me00/m8798grs.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model1elvzwum/prophet_model-20260803144808.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:08 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_24_dept_56

14:48:08 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0jqzhix0.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xvhty2pu.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=62340', 'data', 'file=/tmp/tmpjd45me00/0jqzhix0.json', 'init=/tmp/tmpjd45me00/xvhty2pu.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelcyo3hteg/prophet_model-20260803144808.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:08 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:08 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3xe0oknw.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dtlt12os.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=29926', 'data', 'file=/tmp/tmpjd45me00/3xe0oknw.json', 'init=/tmp/tmpjd45me00/dtlt12os.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelq627a54p/prophet_model-20260803144808.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:08 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_24_dept_58
Build prophet model for  store_24_dept_59

14:48:09 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pzxsrbva.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/314pmwuy.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=43730', 'data', 'file=/tmp/tmpjd45me00/pzxsrbva.json', 'init=/tmp/tmpjd45me00/314pmwuy.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_awch4ge/prophet_model-20260803144809.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:09 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:09 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/maavum24.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zdemgwgb.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=2065', 'data', 'file=/tmp/tmpjd45me00/maavum24.json', 'init=/tmp/tmpjd45me00/zdemgwgb.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelj665grue/prophet_model-20260803144809.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:09 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_24_dept_6
Build prophet model for  store_24_dept_67

14:48:09 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/kqbsnczu.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7hn8oi6r.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=74448', 'data', 'file=/tmp/tmpjd45me00/kqbsnczu.json', 'init=/tmp/tmpjd45me00/7hn8oi6r.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelt9nzbpzj/prophet_model-20260803144809.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:09 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:09 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/sysnc6ge.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/sh5j4fn8.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=15761', 'data', 'file=/tmp/tmpjd45me00/sysnc6ge.json', 'init=/tmp/tmpjd45me00/sh5j4fn8.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelrmumkx_w/prophet_model-20260803144809.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:09 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_24_dept_7
Build prophet model for  store_24_dept_71

14:48:09 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/aqc_1xyl.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/aye35lqg.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=33345', 'data', 'file=/tmp/tmpjd45me00/aqc_1xyl.json', 'init=/tmp/tmpjd45me00/aye35lqg.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model3mgdyzgv/prophet_model-20260803144810.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:10 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:10 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/apkphwyt.json

Build prophet model for  store_24_dept_72
Build prophet model for  store_24_dept_74

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/54lssnq0.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=95136', 'data', 'file=/tmp/tmpjd45me00/apkphwyt.json', 'init=/tmp/tmpjd45me00/54lssnq0.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelmz2gwuji/prophet_model-20260803144810.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:10 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:10 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8e3pfcjx.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8xvj56rd.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=25173', 'data', 'file=/tmp/tmpjd45me00/8e3pfcjx.json', 'init=/tmp/tmpjd45me00/8xvj56rd.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeld3fjr1re/prophet_model-20260803144810.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:10 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:10 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3vj4qd65.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qjtvrhwv.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None

Build prophet model for  store_24_dept_79
Build prophet model for  store_24_dept_8

DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=20430', 'data', 'file=/tmp/tmpjd45me00/3vj4qd65.json', 'init=/tmp/tmpjd45me00/qjtvrhwv.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelzp9vwphz/prophet_model-20260803144810.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:10 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:10 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/tm8mf7i1.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vv1w2gh9.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=2766', 'data', 'file=/tmp/tmpjd45me00/tm8mf7i1.json', 'init=/tmp/tmpjd45me00/vv1w2gh9.json', 'output', 'file=/tmp/tmpjd45me00/prophet_models2sf38sj/prophet_model-20260803144810.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:10 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:10 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_24_dept_80
Build prophet model for  store_24_dept_81

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hz89bb5z.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4cks9vgh.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=65311', 'data', 'file=/tmp/tmpjd45me00/hz89bb5z.json', 'init=/tmp/tmpjd45me00/4cks9vgh.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model4pz99z59/prophet_model-20260803144810.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:10 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:10 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/52jc66_i.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ma0clajp.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=11758', 'data', 'file=/tmp/tmpjd45me00/52jc66_i.json', 'init=/tmp/tmpjd45me00/ma0clajp.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelq0rd6og9/prophet_model-20260803144811.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:11 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:11 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_24_dept_82
Build prophet model for  store_24_dept_83

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2q2xsl_2.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/r5b2bzm0.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=42121', 'data', 'file=/tmp/tmpjd45me00/2q2xsl_2.json', 'init=/tmp/tmpjd45me00/r5b2bzm0.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model1l56te79/prophet_model-20260803144811.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:11 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:11 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/nbe0pdgf.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/g6zt83ei.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=80682', 'data', 'file=/tmp/tmpjd45me00/nbe0pdgf.json', 'init=/tmp/tmpjd45me00/g6zt83ei.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelyol4w7sm/prophet_model-20260803144811.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:11 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_24_dept_85

14:48:11 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ngilvvcy.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/z3hbuxye.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=73933', 'data', 'file=/tmp/tmpjd45me00/ngilvvcy.json', 'init=/tmp/tmpjd45me00/z3hbuxye.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelpzk_gxpg/prophet_model-20260803144811.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:11 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:11 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_24_dept_87
Build prophet model for  store_24_dept_9

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/icrb859r.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/lps1i1s0.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=50302', 'data', 'file=/tmp/tmpjd45me00/icrb859r.json', 'init=/tmp/tmpjd45me00/lps1i1s0.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelj_3t0j3j/prophet_model-20260803144812.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:12 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:12 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5ptouqc5.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wimvmo4i.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=21733', 'data', 'file=/tmp/tmpjd45me00/5ptouqc5.json', 'init=/tmp/tmpjd45me00/wimvmo4i.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model6zu6smxr/prophet_model-20260803144812.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:12 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:12 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_24_dept_90
Build prophet model for  store_24_dept_91

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/70_wgu3s.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_xjit86f.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=37', 'data', 'file=/tmp/tmpjd45me00/70_wgu3s.json', 'init=/tmp/tmpjd45me00/_xjit86f.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelr83gfhpt/prophet_model-20260803144812.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:12 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:12 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/w9eztd6p.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/synedln5.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=46189', 'data', 'file=/tmp/tmpjd45me00/w9eztd6p.json', 'init=/tmp/tmpjd45me00/synedln5.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeltknjd58t/prophet_model-20260803144813.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:13 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_24_dept_92
Build prophet model for  store_24_dept_93

14:48:13 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3x1ixyh1.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zzj2ycks.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=82989', 'data', 'file=/tmp/tmpjd45me00/3x1ixyh1.json', 'init=/tmp/tmpjd45me00/zzj2ycks.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelwj8tpdij/prophet_model-20260803144813.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:13 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:13 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/lxaukygk.json

Build prophet model for  store_24_dept_94
Build prophet model for  store_24_dept_95

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/c3v_qf31.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=53431', 'data', 'file=/tmp/tmpjd45me00/lxaukygk.json', 'init=/tmp/tmpjd45me00/c3v_qf31.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelxt89n5nw/prophet_model-20260803144813.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:13 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:13 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vt6azedu.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vaqwfy0e.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=55587', 'data', 'file=/tmp/tmpjd45me00/vt6azedu.json', 'init=/tmp/tmpjd45me00/vaqwfy0e.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_x1w6s4q/prophet_model-20260803144813.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:13 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_24_dept_96

14:48:13 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/tm0zcvi_.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ptmjznkp.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=20479', 'data', 'file=/tmp/tmpjd45me00/tm0zcvi_.json', 'init=/tmp/tmpjd45me00/ptmjznkp.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelpnsbl840/prophet_model-20260803144814.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:14 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:14 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/j6e23kdo.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/414fqv50.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=88089', 'data', 'file=/tmp/tmpjd45me00/j6e23kdo.json', 'init=/tmp/tmpjd45me00/414fqv50.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelz958fc22/prophet_model-20260803144814.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:14 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_24_dept_97
Build prophet model for  store_24_dept_98

14:48:14 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/w6b4vqce.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/srwxe8z1.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=90194', 'data', 'file=/tmp/tmpjd45me00/w6b4vqce.json', 'init=/tmp/tmpjd45me00/srwxe8z1.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeldsg6gtvw/prophet_model-20260803144814.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:14 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:14 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/veauukig.json

Build prophet model for  store_25_dept_1
Build prophet model for  store_25_dept_10

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bcyq_5i4.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=78364', 'data', 'file=/tmp/tmpjd45me00/veauukig.json', 'init=/tmp/tmpjd45me00/bcyq_5i4.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modellj405fdq/prophet_model-20260803144814.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:14 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:14 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vvjzd7f8.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gqq93ler.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=46666', 'data', 'file=/tmp/tmpjd45me00/vvjzd7f8.json', 'init=/tmp/tmpjd45me00/gqq93ler.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modell8stc5mo/prophet_model-20260803144814.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:14 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:14 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gk2eco20.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/y2ilw0ba.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None

Build prophet model for  store_25_dept_11
Build prophet model for  store_25_dept_12

DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=64702', 'data', 'file=/tmp/tmpjd45me00/gk2eco20.json', 'init=/tmp/tmpjd45me00/y2ilw0ba.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelw8syptmn/prophet_model-20260803144815.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:15 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:15 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_4juvqxx.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/br9n_u0d.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=60978', 'data', 'file=/tmp/tmpjd45me00/_4juvqxx.json', 'init=/tmp/tmpjd45me00/br9n_u0d.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model8oz1g945/prophet_model-20260803144815.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:15 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_25_dept_13

14:48:15 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/myvm2nb0.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/x88otlgp.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=21566', 'data', 'file=/tmp/tmpjd45me00/myvm2nb0.json', 'init=/tmp/tmpjd45me00/x88otlgp.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_hveeer1/prophet_model-20260803144815.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:15 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:15 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ubqk5e4_.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/st9ot9uw.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=97481', 'data', 'file=/tmp/tmpjd45me00/ubqk5e4_.json', 'init=/tmp/tmpjd45me00/st9ot9uw.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model76faiqpp/prophet_model-20260803144815.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:15 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_25_dept_14
Build prophet model for  store_25_dept_16

14:48:16 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fjv0zuim.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dmj5y_c1.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=91583', 'data', 'file=/tmp/tmpjd45me00/fjv0zuim.json', 'init=/tmp/tmpjd45me00/dmj5y_c1.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelkdklxl6f/prophet_model-20260803144816.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:16 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:16 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/o3pl2sy3.json

Build prophet model for  store_25_dept_17
Build prophet model for  store_25_dept_18

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xa507rb_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=7622', 'data', 'file=/tmp/tmpjd45me00/o3pl2sy3.json', 'init=/tmp/tmpjd45me00/xa507rb_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeltov9yyiq/prophet_model-20260803144816.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:16 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:16 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fi90z24c.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2p14cltb.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=98320', 'data', 'file=/tmp/tmpjd45me00/fi90z24c.json', 'init=/tmp/tmpjd45me00/2p14cltb.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelzk5_3itv/prophet_model-20260803144816.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:16 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:16 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_25_dept_2
Build prophet model for  store_25_dept_20

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/v0jrr2ds.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zfwamjix.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=68178', 'data', 'file=/tmp/tmpjd45me00/v0jrr2ds.json', 'init=/tmp/tmpjd45me00/zfwamjix.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelam1i84cs/prophet_model-20260803144817.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:17 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:17 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/h7lkqwdc.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/q3lrzin0.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=83330', 'data', 'file=/tmp/tmpjd45me00/h7lkqwdc.json', 'init=/tmp/tmpjd45me00/q3lrzin0.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeln66uybt0/prophet_model-20260803144817.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:17 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_25_dept_21

14:48:17 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/p8_lum7m.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0xog93k2.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=10949', 'data', 'file=/tmp/tmpjd45me00/p8_lum7m.json', 'init=/tmp/tmpjd45me00/0xog93k2.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelv8ly5sc7/prophet_model-20260803144818.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:18 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:18 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_25_dept_22
Build prophet model for  store_25_dept_23

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5jk3j9d3.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/iwrowyrq.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=26105', 'data', 'file=/tmp/tmpjd45me00/5jk3j9d3.json', 'init=/tmp/tmpjd45me00/iwrowyrq.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model91nlssp2/prophet_model-20260803144818.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:18 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:18 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rfyup9w8.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ahxn7ov6.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=43266', 'data', 'file=/tmp/tmpjd45me00/rfyup9w8.json', 'init=/tmp/tmpjd45me00/ahxn7ov6.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelufnb4wlz/prophet_model-20260803144818.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:18 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:18 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_25_dept_24

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_vloa6w6.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_u0ctz85.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=54750', 'data', 'file=/tmp/tmpjd45me00/_vloa6w6.json', 'init=/tmp/tmpjd45me00/_u0ctz85.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelbhg9kpq1/prophet_model-20260803144818.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:18 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:18 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_25_dept_25

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/cpq6i9ic.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hd2mjo7d.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=39612', 'data', 'file=/tmp/tmpjd45me00/cpq6i9ic.json', 'init=/tmp/tmpjd45me00/hd2mjo7d.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelcvants0b/prophet_model-20260803144819.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:19 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:19 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_25_dept_26
Build prophet model for  store_25_dept_27

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/yarvbd0i.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/sj2iavnd.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=94478', 'data', 'file=/tmp/tmpjd45me00/yarvbd0i.json', 'init=/tmp/tmpjd45me00/sj2iavnd.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model53q8z61k/prophet_model-20260803144819.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:19 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:19 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bmg995dy.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/c0od69os.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=30831', 'data', 'file=/tmp/tmpjd45me00/bmg995dy.json', 'init=/tmp/tmpjd45me00/c0od69os.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelhoykqisj/prophet_model-20260803144819.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:19 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:19 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_25_dept_28

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ak3usj5v.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_0bqg42l.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=93249', 'data', 'file=/tmp/tmpjd45me00/ak3usj5v.json', 'init=/tmp/tmpjd45me00/_0bqg42l.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelyjzzfpap/prophet_model-20260803144819.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:19 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:19 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_25_dept_29

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/g5m8k648.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/n2eiv7w_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=35340', 'data', 'file=/tmp/tmpjd45me00/g5m8k648.json', 'init=/tmp/tmpjd45me00/n2eiv7w_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelq7f1dyev/prophet_model-20260803144820.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:20 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_25_dept_3

14:48:20 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8ewzq53p.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rmbeg48b.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=86479', 'data', 'file=/tmp/tmpjd45me00/8ewzq53p.json', 'init=/tmp/tmpjd45me00/rmbeg48b.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelibjij0yj/prophet_model-20260803144820.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:20 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_25_dept_30

14:48:20 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/y47nyrg7.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fgai8mdv.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=5431', 'data', 'file=/tmp/tmpjd45me00/y47nyrg7.json', 'init=/tmp/tmpjd45me00/fgai8mdv.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelqp52we0j/prophet_model-20260803144821.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:21 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:21 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dj771k67.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/z7c_bzyg.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=93610', 'data', 'file=/tmp/tmpjd45me00/dj771k67.json', 'init=/tmp/tmpjd45me00/z7c_bzyg.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeljhzrmj2t/prophet_model-20260803144821.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:21 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_25_dept_31
Build prophet model for  store_25_dept_32

14:48:21 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wzyu2qfi.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ga7unkyz.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=74819', 'data', 'file=/tmp/tmpjd45me00/wzyu2qfi.json', 'init=/tmp/tmpjd45me00/ga7unkyz.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelpubu94e0/prophet_model-20260803144821.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:21 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:21 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/aauojtor.json

Build prophet model for  store_25_dept_33
Build prophet model for  store_25_dept_34

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vdfes1ni.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=46830', 'data', 'file=/tmp/tmpjd45me00/aauojtor.json', 'init=/tmp/tmpjd45me00/vdfes1ni.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model5tuk8xg_/prophet_model-20260803144821.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:21 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:21 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/g9ioab2h.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pnhpgueb.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=54652', 'data', 'file=/tmp/tmpjd45me00/g9ioab2h.json', 'init=/tmp/tmpjd45me00/pnhpgueb.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model70k_5ljt/prophet_model-20260803144821.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:21 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:21 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/32nigco4.json

Build prophet model for  store_25_dept_35
Build prophet model for  store_25_dept_36

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xezxxxag.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=53011', 'data', 'file=/tmp/tmpjd45me00/32nigco4.json', 'init=/tmp/tmpjd45me00/xezxxxag.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modela242k05y/prophet_model-20260803144822.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:22 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:22 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5xegyx7n.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fnrumy39.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=71255', 'data', 'file=/tmp/tmpjd45me00/5xegyx7n.json', 'init=/tmp/tmpjd45me00/fnrumy39.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelt_n2t19c/prophet_model-20260803144822.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:22 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_25_dept_37

14:48:22 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/82vi5re5.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4yraos6g.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=65330', 'data', 'file=/tmp/tmpjd45me00/82vi5re5.json', 'init=/tmp/tmpjd45me00/4yraos6g.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeley4ssc3r/prophet_model-20260803144822.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:22 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:22 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mxae7c3d.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/a82nj0s2.json

Build prophet model for  store_25_dept_38
Build prophet model for  store_25_dept_4

DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=8720', 'data', 'file=/tmp/tmpjd45me00/mxae7c3d.json', 'init=/tmp/tmpjd45me00/a82nj0s2.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeldmx4tt35/prophet_model-20260803144822.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:22 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:23 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8cfn3el9.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ceqoq_p7.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=28330', 'data', 'file=/tmp/tmpjd45me00/8cfn3el9.json', 'init=/tmp/tmpjd45me00/ceqoq_p7.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelofxn6xr9/prophet_model-20260803144823.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:23 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:23 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_25_dept_40
Build prophet model for  store_25_dept_41

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/oyy28np2.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/e_nz5htt.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=2067', 'data', 'file=/tmp/tmpjd45me00/oyy28np2.json', 'init=/tmp/tmpjd45me00/e_nz5htt.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelilsjtpen/prophet_model-20260803144823.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:23 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:23 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pi3sd1dv.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ek0ecmsy.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=61273', 'data', 'file=/tmp/tmpjd45me00/pi3sd1dv.json', 'init=/tmp/tmpjd45me00/ek0ecmsy.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelgs8_29nu/prophet_model-20260803144823.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:23 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:23 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/j_dnqmb_.json

Build prophet model for  store_25_dept_42
Build prophet model for  store_25_dept_44

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ehebhaoa.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=84596', 'data', 'file=/tmp/tmpjd45me00/j_dnqmb_.json', 'init=/tmp/tmpjd45me00/ehebhaoa.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_ejkc45l/prophet_model-20260803144823.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:23 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:23 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/eb5du_yo.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/z6fwn1_j.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=59101', 'data', 'file=/tmp/tmpjd45me00/eb5du_yo.json', 'init=/tmp/tmpjd45me00/z6fwn1_j.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelx53qzwls/prophet_model-20260803144824.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:24 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_25_dept_46

14:48:24 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hxg0oyxr.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/u9px7opi.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=7099', 'data', 'file=/tmp/tmpjd45me00/hxg0oyxr.json', 'init=/tmp/tmpjd45me00/u9px7opi.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_c7mqpkr/prophet_model-20260803144824.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:24 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:24 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_zh5gn01.json

Build prophet model for  store_25_dept_49
Build prophet model for  store_25_dept_5

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qbao8eq2.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=15816', 'data', 'file=/tmp/tmpjd45me00/_zh5gn01.json', 'init=/tmp/tmpjd45me00/qbao8eq2.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelpm562xas/prophet_model-20260803144824.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:24 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:24 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/kagw14_x.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0kr3b19_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=10203', 'data', 'file=/tmp/tmpjd45me00/kagw14_x.json', 'init=/tmp/tmpjd45me00/0kr3b19_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelhklb1efn/prophet_model-20260803144824.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:24 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:24 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jdbl2ymi.json

Build prophet model for  store_25_dept_50
Build prophet model for  store_25_dept_52

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/i8hrk729.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=26797', 'data', 'file=/tmp/tmpjd45me00/jdbl2ymi.json', 'init=/tmp/tmpjd45me00/i8hrk729.json', 'output', 'file=/tmp/tmpjd45me00/prophet_models_me4sty/prophet_model-20260803144824.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:24 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:25 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/39iadeka.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/__z1h3xu.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=69172', 'data', 'file=/tmp/tmpjd45me00/39iadeka.json', 'init=/tmp/tmpjd45me00/__z1h3xu.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelpn7b3urh/prophet_model-20260803144825.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:48:25 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_25_dept_54

14:48:25 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/de8polgd.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6ddvnklb.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=49793', 'data', 'file=/tmp/tmpjd45me00/de8polgd.json', 'init=/tmp/tmpjd45me00/6ddvnklb.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelkja6smnx/prophet_model-20260803144826.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:26 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:26 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hywjtp27.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/17gu_arh.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=79731', 'data', 'file=/tmp/tmpjd45me00/hywjtp27.json', 'init=/tmp/tmpjd45me00/17gu_arh.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelxzoq1qnn/prophet_model-20260803144826.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:26 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_25_dept_55
Build prophet model for  store_25_dept_56

14:48:26 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gxxxv35n.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dw2ofd5s.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=57212', 'data', 'file=/tmp/tmpjd45me00/gxxxv35n.json', 'init=/tmp/tmpjd45me00/dw2ofd5s.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelyyjjfu1u/prophet_model-20260803144826.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:26 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_25_dept_59

14:48:26 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/udnicpvt.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9yqt_w_f.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=76809', 'data', 'file=/tmp/tmpjd45me00/udnicpvt.json', 'init=/tmp/tmpjd45me00/9yqt_w_f.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelcro2jhmc/prophet_model-20260803144826.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:26 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:26 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5milnlxf.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qokzzbvj.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=64955', 'data', 'file=/tmp/tmpjd45me00/5milnlxf.json', 'init=/tmp/tmpjd45me00/qokzzbvj.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelywe1u0bn/prophet_model-20260803144826.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:26 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:26 - cmdstanpy - INFO - Chain [1] done processing

Build prophet model for  store_25_dept_6
Build prophet model for  store_25_dept_67

INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7u5zbhrd.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ylv5xjw3.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=80243', 'data', 'file=/tmp/tmpjd45me00/7u5zbhrd.json', 'init=/tmp/tmpjd45me00/ylv5xjw3.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelxw77nkc6/prophet_model-20260803144827.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:27 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:27 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_jmgy4hf.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/y7e6001y.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=25441', 'data', 'file=/tmp/tmpjd45me00/_jmgy4hf.json', 'init=/tmp/tmpjd45me00/y7e6001y.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelfn9pxy05/prophet_model-20260803144827.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:27 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_25_dept_7
Build prophet model for  store_25_dept_71

14:48:27 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/675iqx5v.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/03wj3mo1.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=53603', 'data', 'file=/tmp/tmpjd45me00/675iqx5v.json', 'init=/tmp/tmpjd45me00/03wj3mo1.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelsacggov_/prophet_model-20260803144827.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:27 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:27 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8vdm6ppw.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/yo14oorn.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=56966', 'data', 'file=/tmp/tmpjd45me00/8vdm6ppw.json', 'init=/tmp/tmpjd45me00/yo14oorn.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelcfx0qf5a/prophet_model-20260803144827.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:27 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_25_dept_72
Build prophet model for  store_25_dept_74

14:48:27 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jo8ony4l.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/n4bul3_c.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=88087', 'data', 'file=/tmp/tmpjd45me00/jo8ony4l.json', 'init=/tmp/tmpjd45me00/n4bul3_c.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modele2z6trr3/prophet_model-20260803144827.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:27 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:27 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/22xj6n9v.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ymnbr9ip.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=58382', 'data', 'file=/tmp/tmpjd45me00/22xj6n9v.json', 'init=/tmp/tmpjd45me00/ymnbr9ip.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelie7vi6zs/prophet_model-20260803144827.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:27 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_25_dept_79
Build prophet model for  store_25_dept_8

14:48:27 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/47bw5z5i.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fqp9ybry.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=12575', 'data', 'file=/tmp/tmpjd45me00/47bw5z5i.json', 'init=/tmp/tmpjd45me00/fqp9ybry.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model2p0igxuu/prophet_model-20260803144827.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:27 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_25_dept_81

14:48:28 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4bb9s1zu.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/m07ltaun.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=48889', 'data', 'file=/tmp/tmpjd45me00/4bb9s1zu.json', 'init=/tmp/tmpjd45me00/m07ltaun.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelvdzo9q5q/prophet_model-20260803144828.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:28 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:28 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xcde5lkm.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2gxf7phb.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=3510', 'data', 'file=/tmp/tmpjd45me00/xcde5lkm.json', 'init=/tmp/tmpjd45me00/2gxf7phb.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelfocjlom9/prophet_model-20260803144828.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:28 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_25_dept_82
Build prophet model for  store_25_dept_83

14:48:28 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/nr5wd0sh.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/p0ba3_sx.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=396', 'data', 'file=/tmp/tmpjd45me00/nr5wd0sh.json', 'init=/tmp/tmpjd45me00/p0ba3_sx.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model7o_ebilp/prophet_model-20260803144828.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:28 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_25_dept_85

14:48:29 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/f1ysz5ir.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/tdilvnlk.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=90998', 'data', 'file=/tmp/tmpjd45me00/f1ysz5ir.json', 'init=/tmp/tmpjd45me00/tdilvnlk.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelannaajvu/prophet_model-20260803144829.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:29 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:29 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/be7l8r_5.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/58xcggw1.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=3585', 'data', 'file=/tmp/tmpjd45me00/be7l8r_5.json', 'init=/tmp/tmpjd45me00/58xcggw1.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model56hf9jit/prophet_model-20260803144829.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:29 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_25_dept_87
Build prophet model for  store_25_dept_9

14:48:29 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/f1pxmpfk.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/kdt3qwxn.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=64863', 'data', 'file=/tmp/tmpjd45me00/f1pxmpfk.json', 'init=/tmp/tmpjd45me00/kdt3qwxn.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelhslg3_rv/prophet_model-20260803144829.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:29 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:29 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_25_dept_90
Build prophet model for  store_25_dept_91

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gbyq1lq_.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/c0vpbtqi.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=59427', 'data', 'file=/tmp/tmpjd45me00/gbyq1lq_.json', 'init=/tmp/tmpjd45me00/c0vpbtqi.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model__icvtuw/prophet_model-20260803144829.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:29 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:29 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/267fc7p7.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ivg9utmp.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=18710', 'data', 'file=/tmp/tmpjd45me00/267fc7p7.json', 'init=/tmp/tmpjd45me00/ivg9utmp.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelevb4t0sr/prophet_model-20260803144829.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:29 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:30 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_25_dept_92

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xrdgp_9t.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/aeah7u8x.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=57585', 'data', 'file=/tmp/tmpjd45me00/xrdgp_9t.json', 'init=/tmp/tmpjd45me00/aeah7u8x.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelfsi3dkey/prophet_model-20260803144830.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:30 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:30 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_25_dept_93
Build prophet model for  store_25_dept_95

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vbve80hu.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ehzi5txy.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=32554', 'data', 'file=/tmp/tmpjd45me00/vbve80hu.json', 'init=/tmp/tmpjd45me00/ehzi5txy.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelkhmbq9xx/prophet_model-20260803144830.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:30 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:30 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/al2l4t_b.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zer21ggk.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=32889', 'data', 'file=/tmp/tmpjd45me00/al2l4t_b.json', 'init=/tmp/tmpjd45me00/zer21ggk.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeleb56kt7k/prophet_model-20260803144830.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:30 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:30 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_25_dept_97

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xat2k6qv.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/c4axtyaz.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=15388', 'data', 'file=/tmp/tmpjd45me00/xat2k6qv.json', 'init=/tmp/tmpjd45me00/c4axtyaz.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelut6686je/prophet_model-20260803144831.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:31 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_25_dept_98

14:48:31 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/baa64urz.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/uvco3mgx.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=82917', 'data', 'file=/tmp/tmpjd45me00/baa64urz.json', 'init=/tmp/tmpjd45me00/uvco3mgx.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelo5w2m8ad/prophet_model-20260803144831.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:31 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:31 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_26_dept_1

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/spdbw9q1.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/f9_yijnw.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=42928', 'data', 'file=/tmp/tmpjd45me00/spdbw9q1.json', 'init=/tmp/tmpjd45me00/f9_yijnw.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelege79e5d/prophet_model-20260803144831.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:31 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:31 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_26_dept_10

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vf7nqgch.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2my33yyr.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=34899', 'data', 'file=/tmp/tmpjd45me00/vf7nqgch.json', 'init=/tmp/tmpjd45me00/2my33yyr.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelcyd4g3qf/prophet_model-20260803144832.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:32 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:32 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_26_dept_11

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6a37gjqw.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/sabyzn99.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=4905', 'data', 'file=/tmp/tmpjd45me00/6a37gjqw.json', 'init=/tmp/tmpjd45me00/sabyzn99.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model78dlgoxi/prophet_model-20260803144832.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:32 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:32 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_26_dept_12

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/n34kp5kq.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/olrw4e9h.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=47483', 'data', 'file=/tmp/tmpjd45me00/n34kp5kq.json', 'init=/tmp/tmpjd45me00/olrw4e9h.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelaxu8wopm/prophet_model-20260803144832.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:32 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:32 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_26_dept_13

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/kfdj2a6m.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7ja1x7s4.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=91191', 'data', 'file=/tmp/tmpjd45me00/kfdj2a6m.json', 'init=/tmp/tmpjd45me00/7ja1x7s4.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model3v5ja98h/prophet_model-20260803144833.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:33 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:33 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_26_dept_14
Build prophet model for  store_26_dept_16

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gwnmbn9k.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ht0vet8u.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=75270', 'data', 'file=/tmp/tmpjd45me00/gwnmbn9k.json', 'init=/tmp/tmpjd45me00/ht0vet8u.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelzltbt6_4/prophet_model-20260803144833.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:33 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:33 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/efxht7p0.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/i59co2kg.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=5896', 'data', 'file=/tmp/tmpjd45me00/efxht7p0.json', 'init=/tmp/tmpjd45me00/i59co2kg.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelcerfe3dt/prophet_model-20260803144833.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:33 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:33 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0rbwu9ty.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/goxmovtn.json

Build prophet model for  store_26_dept_17
Build prophet model for  store_26_dept_18

DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=47002', 'data', 'file=/tmp/tmpjd45me00/0rbwu9ty.json', 'init=/tmp/tmpjd45me00/goxmovtn.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelb522nz48/prophet_model-20260803144833.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:33 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:33 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/a7k3gc1t.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vn9l0yem.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=82832', 'data', 'file=/tmp/tmpjd45me00/a7k3gc1t.json', 'init=/tmp/tmpjd45me00/vn9l0yem.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelu7dophg4/prophet_model-20260803144834.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:34 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:34 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_26_dept_19
Build prophet model for  store_26_dept_2

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zmtuwhvy.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/w5szft0d.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=20034', 'data', 'file=/tmp/tmpjd45me00/zmtuwhvy.json', 'init=/tmp/tmpjd45me00/w5szft0d.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelhb2qck9e/prophet_model-20260803144834.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:34 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:34 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/aqrqjgtq.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_x4nm1q2.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=85723', 'data', 'file=/tmp/tmpjd45me00/aqrqjgtq.json', 'init=/tmp/tmpjd45me00/_x4nm1q2.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelnrdugrg6/prophet_model-20260803144834.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:34 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:34 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ywbnxzbr.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/se7t4ygc.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=45373', 'data', 'file=/tmp/tmpjd45me00/ywbnxzbr.json', 'init=/tmp/tmpjd45me00/se7t4ygc.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelm_t1q1if/prophet_model-20260803144834.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:34 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_26_dept_20
Build prophet model for  store_26_dept_21

14:48:34 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dj_3j8da.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/56gdnr4o.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=52537', 'data', 'file=/tmp/tmpjd45me00/dj_3j8da.json', 'init=/tmp/tmpjd45me00/56gdnr4o.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelq8h_ohg2/prophet_model-20260803144834.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:34 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:34 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zmjgrg7u.json

Build prophet model for  store_26_dept_22
Build prophet model for  store_26_dept_23

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7m5z0x52.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=49508', 'data', 'file=/tmp/tmpjd45me00/zmjgrg7u.json', 'init=/tmp/tmpjd45me00/7m5z0x52.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelwadw02af/prophet_model-20260803144834.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:34 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:34 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ba08wafi.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2681vn3v.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=70872', 'data', 'file=/tmp/tmpjd45me00/ba08wafi.json', 'init=/tmp/tmpjd45me00/2681vn3v.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeld5isrjll/prophet_model-20260803144835.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:35 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:35 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_26_dept_24
Build prophet model for  store_26_dept_25

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7aqdlnhx.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/93e79f2u.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=36154', 'data', 'file=/tmp/tmpjd45me00/7aqdlnhx.json', 'init=/tmp/tmpjd45me00/93e79f2u.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelgrs1f8mf/prophet_model-20260803144835.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:35 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:35 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2y_wi_d3.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rtuaqio4.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=36026', 'data', 'file=/tmp/tmpjd45me00/2y_wi_d3.json', 'init=/tmp/tmpjd45me00/rtuaqio4.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeld5whid_u/prophet_model-20260803144835.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:35 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:35 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mk2ry_u3.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8xq8_7ir.json
DEBUG:cmdstanpy:idx 0

Build prophet model for  store_26_dept_26
Build prophet model for  store_26_dept_27

DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=62840', 'data', 'file=/tmp/tmpjd45me00/mk2ry_u3.json', 'init=/tmp/tmpjd45me00/8xq8_7ir.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelxapo0auq/prophet_model-20260803144835.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:35 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:35 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wp4gbl40.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/95rd8f4_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=74064', 'data', 'file=/tmp/tmpjd45me00/wp4gbl40.json', 'init=/tmp/tmpjd45me00/95rd8f4_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelrd3rgjhg/prophet_model-20260803144835.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:35 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:35 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wpqgu0kw.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ekfj2m3s.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=45807', 'data', 'file=/tmp/tmpjd45me00/wpqgu0kw.json', 'init=/tmp/tmpjd45me00/ekfj2m3s.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelz1s513lb/prophet_model-20260803144835.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:35 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_26_dept_28
Build prophet model for  store_26_dept_29

14:48:35 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/aw01xwnz.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/nizln_c_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=21506', 'data', 'file=/tmp/tmpjd45me00/aw01xwnz.json', 'init=/tmp/tmpjd45me00/nizln_c_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelmvokl1po/prophet_model-20260803144836.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:36 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_26_dept_3

14:48:36 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8rkznb0r.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/x8g4efqn.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=89456', 'data', 'file=/tmp/tmpjd45me00/8rkznb0r.json', 'init=/tmp/tmpjd45me00/x8g4efqn.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model6tugs_sz/prophet_model-20260803144836.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:36 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:36 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5sg681wz.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9vodpdog.json
DEBUG:cmdstanpy:idx 0

Build prophet model for  store_26_dept_30
Build prophet model for  store_26_dept_31

DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=33407', 'data', 'file=/tmp/tmpjd45me00/5sg681wz.json', 'init=/tmp/tmpjd45me00/9vodpdog.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelckup55zd/prophet_model-20260803144836.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:36 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:36 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/yioy0ipi.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ka__f2h4.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=15519', 'data', 'file=/tmp/tmpjd45me00/yioy0ipi.json', 'init=/tmp/tmpjd45me00/ka__f2h4.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelmezalw53/prophet_model-20260803144836.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:36 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:36 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9div8wuc.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rox8i8oa.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=86745', 'data', 'file=/tmp/tmpjd45me00/9div8wuc.json', 'init=/tmp/tmpjd45me00/rox8i8oa.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model4ucov5bq/prophet_model-20260803144836.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:36 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_26_dept_32
Build prophet model for  store_26_dept_33

14:48:36 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0pakzjg0.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pn1x966i.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=45565', 'data', 'file=/tmp/tmpjd45me00/0pakzjg0.json', 'init=/tmp/tmpjd45me00/pn1x966i.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelnahf6w1z/prophet_model-20260803144837.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:37 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:37 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wtkqn2pw.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5mloju1x.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=88272', 'data', 'file=/tmp/tmpjd45me00/wtkqn2pw.json', 'init=/tmp/tmpjd45me00/5mloju1x.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeldkmr6gpq/prophet_model-20260803144837.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:37 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_26_dept_34
Build prophet model for  store_26_dept_35

14:48:37 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0vwi9qxp.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zjqv6tce.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=75869', 'data', 'file=/tmp/tmpjd45me00/0vwi9qxp.json', 'init=/tmp/tmpjd45me00/zjqv6tce.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model4z5nccyp/prophet_model-20260803144837.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:37 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:37 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_26_dept_36

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fse74_jx.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ksew2w88.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=18369', 'data', 'file=/tmp/tmpjd45me00/fse74_jx.json', 'init=/tmp/tmpjd45me00/ksew2w88.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelewd1icjq/prophet_model-20260803144837.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:37 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:37 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_26_dept_38
Build prophet model for  store_26_dept_4

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8xp_qhit.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/48nm3k1y.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=59997', 'data', 'file=/tmp/tmpjd45me00/8xp_qhit.json', 'init=/tmp/tmpjd45me00/48nm3k1y.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelidxb7iuk/prophet_model-20260803144838.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:38 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:38 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/y8mh71_1.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/lci75h9i.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=4586', 'data', 'file=/tmp/tmpjd45me00/y8mh71_1.json', 'init=/tmp/tmpjd45me00/lci75h9i.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelypty4938/prophet_model-20260803144838.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:38 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_26_dept_40
Build prophet model for  store_26_dept_41

14:48:38 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_d6i8zr3.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bgxbert7.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=16606', 'data', 'file=/tmp/tmpjd45me00/_d6i8zr3.json', 'init=/tmp/tmpjd45me00/bgxbert7.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelhkbm9w0w/prophet_model-20260803144838.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:38 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:38 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_26_dept_42
Build prophet model for  store_26_dept_44

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5hdy_f7_.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/r2c0wpwe.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=20084', 'data', 'file=/tmp/tmpjd45me00/5hdy_f7_.json', 'init=/tmp/tmpjd45me00/r2c0wpwe.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelp9l3fmc6/prophet_model-20260803144838.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:38 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:38 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9hmvz366.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/v0kwnnvo.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=27029', 'data', 'file=/tmp/tmpjd45me00/9hmvz366.json', 'init=/tmp/tmpjd45me00/v0kwnnvo.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_jdo7frt/prophet_model-20260803144838.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:38 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:38 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_yghz2uw.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/d58g6hoh.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=21093', 'data', 'file=/tmp/tmpjd45me00/_yghz2uw.json', 'init=/tmp/tmpjd45me00/d58g6hoh.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model7gf1io5z/prophet_model-20260803144838.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:38 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_26_dept_46
Build prophet model for  store_26_dept_49

14:48:39 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wcv3w1ls.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2wqndv4m.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=27003', 'data', 'file=/tmp/tmpjd45me00/wcv3w1ls.json', 'init=/tmp/tmpjd45me00/2wqndv4m.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model7ay3rl7k/prophet_model-20260803144839.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:39 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_26_dept_5

14:48:39 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/30h37qrp.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ga4yk5i2.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=53488', 'data', 'file=/tmp/tmpjd45me00/30h37qrp.json', 'init=/tmp/tmpjd45me00/ga4yk5i2.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model46rqreq8/prophet_model-20260803144839.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:39 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:39 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gnjzjbp2.json

Build prophet model for  store_26_dept_52
Build prophet model for  store_26_dept_54

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ywdzzwf5.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=54244', 'data', 'file=/tmp/tmpjd45me00/gnjzjbp2.json', 'init=/tmp/tmpjd45me00/ywdzzwf5.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelx8bb5z9m/prophet_model-20260803144839.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:39 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:39 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ivo42edu.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/j1xygq1t.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=31959', 'data', 'file=/tmp/tmpjd45me00/ivo42edu.json', 'init=/tmp/tmpjd45me00/j1xygq1t.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelmnbv6hqk/prophet_model-20260803144839.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:39 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:39 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vb6q_igb.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_oj_xw66.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=64362', 'data', 'file=/tmp/tmpjd45me00/vb6q_igb.json', 'init=/tmp/tmpjd45me00/_oj_xw66.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeli2_kiba6/prophet_model-20260803144839.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:39 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_26_dept_55
Build prophet model for  store_26_dept_56

14:48:39 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gc0z3pme.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/a1x80i3d.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=96399', 'data', 'file=/tmp/tmpjd45me00/gc0z3pme.json', 'init=/tmp/tmpjd45me00/a1x80i3d.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model1yxxfj28/prophet_model-20260803144840.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:40 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_26_dept_59

14:48:40 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/86wny156.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/n2t5apcm.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=52540', 'data', 'file=/tmp/tmpjd45me00/86wny156.json', 'init=/tmp/tmpjd45me00/n2t5apcm.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model9m7ie5s_/prophet_model-20260803144840.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:40 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:40 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dy13sp06.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/cv9dbgdn.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=46165', 'data', 'file=/tmp/tmpjd45me00/dy13sp06.json', 'init=/tmp/tmpjd45me00/cv9dbgdn.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeleaw1rcub/prophet_model-20260803144840.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:40 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_26_dept_6
Build prophet model for  store_26_dept_67

14:48:40 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ww3fa418.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/swh3yiks.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=36507', 'data', 'file=/tmp/tmpjd45me00/ww3fa418.json', 'init=/tmp/tmpjd45me00/swh3yiks.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model2z3hxehg/prophet_model-20260803144840.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:40 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:40 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/c81hfto3.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2e5vv78_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=67653', 'data', 'file=/tmp/tmpjd45me00/c81hfto3.json', 'init=/tmp/tmpjd45me00/2e5vv78_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelghyednu_/prophet_model-20260803144840.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:40 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_26_dept_7
Build prophet model for  store_26_dept_71

14:48:40 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3aeyucni.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/lew6vbgh.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=11163', 'data', 'file=/tmp/tmpjd45me00/3aeyucni.json', 'init=/tmp/tmpjd45me00/lew6vbgh.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelnageqajy/prophet_model-20260803144841.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:41 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:41 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/a6f9ju1s.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ly6e3748.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=10526', 'data', 'file=/tmp/tmpjd45me00/a6f9ju1s.json', 'init=/tmp/tmpjd45me00/ly6e3748.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model2d3xfhqz/prophet_model-20260803144841.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:41 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_26_dept_72
Build prophet model for  store_26_dept_74

14:48:41 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jx1ygj75.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ay9tl3m0.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=58627', 'data', 'file=/tmp/tmpjd45me00/jx1ygj75.json', 'init=/tmp/tmpjd45me00/ay9tl3m0.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeltd66fqo7/prophet_model-20260803144841.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:41 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:41 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_26_dept_79
Build prophet model for  store_26_dept_8

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/une2kzaz.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/b79col1r.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=63205', 'data', 'file=/tmp/tmpjd45me00/une2kzaz.json', 'init=/tmp/tmpjd45me00/b79col1r.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model378lm8go/prophet_model-20260803144841.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:41 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:41 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dcg06i8l.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bljmko1d.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=41615', 'data', 'file=/tmp/tmpjd45me00/dcg06i8l.json', 'init=/tmp/tmpjd45me00/bljmko1d.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model9_h70k87/prophet_model-20260803144841.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:41 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:41 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/cpvzrhuv.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/h2dhpfq4.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=94654', 'data', 'file=/tmp/tmpjd45me00/cpvzrhuv.json', 'init=/tmp/tmpjd45me00/h2dhpfq4.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelszden_cm/prophet_model-20260803144841.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:41 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_26_dept_80
Build prophet model for  store_26_dept_81

14:48:41 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/35y24z7u.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_ec419pt.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=32109', 'data', 'file=/tmp/tmpjd45me00/35y24z7u.json', 'init=/tmp/tmpjd45me00/_ec419pt.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model0hixt3bw/prophet_model-20260803144842.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:42 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:42 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/owfw1e3e.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/k_chphjh.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=21514', 'data', 'file=/tmp/tmpjd45me00/owfw1e3e.json', 'init=/tmp/tmpjd45me00/k_chphjh.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelurkrwio5/prophet_model-20260803144842.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:42 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_26_dept_82
Build prophet model for  store_26_dept_83

14:48:42 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7ubrtxhy.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rmdpfy8c.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=78116', 'data', 'file=/tmp/tmpjd45me00/7ubrtxhy.json', 'init=/tmp/tmpjd45me00/rmdpfy8c.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelu_e2g6o_/prophet_model-20260803144842.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:42 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:42 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_26_dept_85
Build prophet model for  store_26_dept_87

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/eu3nyg4a.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/i755qt3v.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=35452', 'data', 'file=/tmp/tmpjd45me00/eu3nyg4a.json', 'init=/tmp/tmpjd45me00/i755qt3v.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelnc7ln94j/prophet_model-20260803144842.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:42 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:42 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vh8aatpo.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qmx70qqo.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=58746', 'data', 'file=/tmp/tmpjd45me00/vh8aatpo.json', 'init=/tmp/tmpjd45me00/qmx70qqo.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelb8f8lj07/prophet_model-20260803144842.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:42 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:42 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hc7utgz9.json

Build prophet model for  store_26_dept_9
Build prophet model for  store_26_dept_90

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/81b12gpm.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=87134', 'data', 'file=/tmp/tmpjd45me00/hc7utgz9.json', 'init=/tmp/tmpjd45me00/81b12gpm.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelmlthe5ea/prophet_model-20260803144842.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:42 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:43 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_2zkqxna.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3xydv6jz.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=56773', 'data', 'file=/tmp/tmpjd45me00/_2zkqxna.json', 'init=/tmp/tmpjd45me00/3xydv6jz.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model1wcc_drm/prophet_model-20260803144843.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:43 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:43 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2ayor2nu.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zpnjahl3.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=8001', 'data', 'file=/tmp/tmpjd45me00/2ayor2nu.json', 'init=/tmp/tmpjd45me00/zpnjahl3.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeljd4dpw9j/prophet_model-20260803144843.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:43 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_26_dept_91
Build prophet model for  store_26_dept_92

14:48:43 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/elwec_1v.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/x52ux7do.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=11329', 'data', 'file=/tmp/tmpjd45me00/elwec_1v.json', 'init=/tmp/tmpjd45me00/x52ux7do.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model6qiz6b2_/prophet_model-20260803144843.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:43 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:43 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_26_dept_93
Build prophet model for  store_26_dept_94

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/unz1vr1m.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/b4zmspl1.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=69721', 'data', 'file=/tmp/tmpjd45me00/unz1vr1m.json', 'init=/tmp/tmpjd45me00/b4zmspl1.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model3sgi53j7/prophet_model-20260803144843.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:43 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:43 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/diy8kn4n.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/d31iuwjy.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=31053', 'data', 'file=/tmp/tmpjd45me00/diy8kn4n.json', 'init=/tmp/tmpjd45me00/d31iuwjy.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model0xz6zfkl/prophet_model-20260803144844.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:44 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:44 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_26_dept_95
Build prophet model for  store_26_dept_96

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/i6gqmvpj.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xywx9elj.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=73729', 'data', 'file=/tmp/tmpjd45me00/i6gqmvpj.json', 'init=/tmp/tmpjd45me00/xywx9elj.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelmzxm38op/prophet_model-20260803144844.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:44 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:44 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8q32fb24.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wabzmyi8.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=20945', 'data', 'file=/tmp/tmpjd45me00/8q32fb24.json', 'init=/tmp/tmpjd45me00/wabzmyi8.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modell3xqac_8/prophet_model-20260803144844.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:44 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:44 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_26_dept_97
Build prophet model for  store_26_dept_98

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vf6q_fx_.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/txvx3jye.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=18364', 'data', 'file=/tmp/tmpjd45me00/vf6q_fx_.json', 'init=/tmp/tmpjd45me00/txvx3jye.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modellphdv395/prophet_model-20260803144845.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:45 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:45 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1bwjlwp8.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/npw25qx0.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=77410', 'data', 'file=/tmp/tmpjd45me00/1bwjlwp8.json', 'init=/tmp/tmpjd45me00/npw25qx0.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelwwtp0jwe/prophet_model-20260803144845.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:45 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:45 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_27_dept_1
Build prophet model for  store_27_dept_10

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4wlu8fev.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/cnhobd8d.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=8805', 'data', 'file=/tmp/tmpjd45me00/4wlu8fev.json', 'init=/tmp/tmpjd45me00/cnhobd8d.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeltske0hlx/prophet_model-20260803144845.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:45 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:46 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mccduprv.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xrswmjpr.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=57878', 'data', 'file=/tmp/tmpjd45me00/mccduprv.json', 'init=/tmp/tmpjd45me00/xrswmjpr.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model8xwt98uq/prophet_model-20260803144846.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:46 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:46 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_27_dept_11

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/e3vv05fw.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/l4aqz5yw.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=3695', 'data', 'file=/tmp/tmpjd45me00/e3vv05fw.json', 'init=/tmp/tmpjd45me00/l4aqz5yw.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_iglqh99/prophet_model-20260803144846.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:46 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:46 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_27_dept_12

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/d7cf9wsc.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3j0zi_as.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=27053', 'data', 'file=/tmp/tmpjd45me00/d7cf9wsc.json', 'init=/tmp/tmpjd45me00/3j0zi_as.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model1ssvn19z/prophet_model-20260803144846.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:46 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:46 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_27_dept_13

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ti4g_ptb.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4f_tsxam.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=3383', 'data', 'file=/tmp/tmpjd45me00/ti4g_ptb.json', 'init=/tmp/tmpjd45me00/4f_tsxam.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelmlb6b156/prophet_model-20260803144847.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:47 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:47 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0heo7wsb.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/y1trz9ma.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=18999', 'data', 'file=/tmp/tmpjd45me00/0heo7wsb.json', 'init=/tmp/tmpjd45me00/y1trz9ma.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelxtxm4p5_/prophet_model-20260803144847.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:47 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_27_dept_14
Build prophet model for  store_27_dept_16

14:48:47 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ek1uk0ba.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2t3jragz.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=49707', 'data', 'file=/tmp/tmpjd45me00/ek1uk0ba.json', 'init=/tmp/tmpjd45me00/2t3jragz.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelt2t8afdd/prophet_model-20260803144847.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:47 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:47 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_ua9okrx.json

Build prophet model for  store_27_dept_17
Build prophet model for  store_27_dept_18

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wtywu5u3.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=91460', 'data', 'file=/tmp/tmpjd45me00/_ua9okrx.json', 'init=/tmp/tmpjd45me00/wtywu5u3.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelbrjpse96/prophet_model-20260803144847.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:47 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:47 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/viremblc.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1tddfgba.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=78993', 'data', 'file=/tmp/tmpjd45me00/viremblc.json', 'init=/tmp/tmpjd45me00/1tddfgba.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelpglrjmwz/prophet_model-20260803144848.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:48 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_27_dept_19

14:48:48 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vl686lpz.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/s0mn8hke.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=88492', 'data', 'file=/tmp/tmpjd45me00/vl686lpz.json', 'init=/tmp/tmpjd45me00/s0mn8hke.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelg02x_3ee/prophet_model-20260803144848.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:48 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:48 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vp94r8i_.json

Build prophet model for  store_27_dept_2
Build prophet model for  store_27_dept_20

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7pivo3vx.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=60590', 'data', 'file=/tmp/tmpjd45me00/vp94r8i_.json', 'init=/tmp/tmpjd45me00/7pivo3vx.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelazpm88dw/prophet_model-20260803144848.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:48 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:48 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0vns5rk2.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/37a1elj0.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=61698', 'data', 'file=/tmp/tmpjd45me00/0vns5rk2.json', 'init=/tmp/tmpjd45me00/37a1elj0.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model957rnjf9/prophet_model-20260803144848.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:48 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:48 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/lmqi1m7s.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/g5v6ta_h.json

Build prophet model for  store_27_dept_21
Build prophet model for  store_27_dept_22

DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=84004', 'data', 'file=/tmp/tmpjd45me00/lmqi1m7s.json', 'init=/tmp/tmpjd45me00/g5v6ta_h.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelmkw8oa_u/prophet_model-20260803144848.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:48 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:48 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2ngg1ttl.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/sz286iv_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=28269', 'data', 'file=/tmp/tmpjd45me00/2ngg1ttl.json', 'init=/tmp/tmpjd45me00/sz286iv_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelerpzheac/prophet_model-20260803144849.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:49 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_27_dept_23

14:48:49 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bj3s2mgm.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/40wxa2lt.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=17778', 'data', 'file=/tmp/tmpjd45me00/bj3s2mgm.json', 'init=/tmp/tmpjd45me00/40wxa2lt.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model728ij31t/prophet_model-20260803144849.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:49 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:49 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/v_140vu6.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0bj8c9sz.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=15841', 'data', 'file=/tmp/tmpjd45me00/v_140vu6.json', 'init=/tmp/tmpjd45me00/0bj8c9sz.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_pgdjmew/prophet_model-20260803144849.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']

Build prophet model for  store_27_dept_24
Build prophet model for  store_27_dept_25

14:48:49 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:49 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vqct9gas.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/42o9rosl.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=23402', 'data', 'file=/tmp/tmpjd45me00/vqct9gas.json', 'init=/tmp/tmpjd45me00/42o9rosl.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelq7qo2mm3/prophet_model-20260803144850.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:50 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:50 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rlg9deei.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ig1jq7ck.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=50720', 'data', 'file=/tmp/tmpjd45me00/rlg9deei.json', 'init=/tmp/tmpjd45me00/ig1jq7ck.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelwajexroo/prophet_model-20260803144850.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:50 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_27_dept_26
Build prophet model for  store_27_dept_27

14:48:50 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8woobtdb.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/p8kifjcg.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=10456', 'data', 'file=/tmp/tmpjd45me00/8woobtdb.json', 'init=/tmp/tmpjd45me00/p8kifjcg.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelhfdog8ib/prophet_model-20260803144850.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:50 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:50 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_27_dept_28

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/n48xc03k.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/s4g6_fkv.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=55523', 'data', 'file=/tmp/tmpjd45me00/n48xc03k.json', 'init=/tmp/tmpjd45me00/s4g6_fkv.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model3znwmazc/prophet_model-20260803144850.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:50 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:50 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_27_dept_29

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/w9nlzg5r.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vxmuqnn2.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=58165', 'data', 'file=/tmp/tmpjd45me00/w9nlzg5r.json', 'init=/tmp/tmpjd45me00/vxmuqnn2.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeljl4s_8vi/prophet_model-20260803144850.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:50 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_27_dept_3

14:48:51 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/sagd7mxk.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/78638uom.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=102', 'data', 'file=/tmp/tmpjd45me00/sagd7mxk.json', 'init=/tmp/tmpjd45me00/78638uom.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model0137k6mn/prophet_model-20260803144851.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:51 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_27_dept_30

14:48:51 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4v7kipn0.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/f9u4szxl.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=94970', 'data', 'file=/tmp/tmpjd45me00/4v7kipn0.json', 'init=/tmp/tmpjd45me00/f9u4szxl.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelsgq332f_/prophet_model-20260803144851.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:51 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_27_dept_31

14:48:51 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/w_0kp70d.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/94nwu18d.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=14052', 'data', 'file=/tmp/tmpjd45me00/w_0kp70d.json', 'init=/tmp/tmpjd45me00/94nwu18d.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model1k0gn3c1/prophet_model-20260803144851.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:51 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:51 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/z11ca9b1.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/haa867av.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=14590', 'data', 'file=/tmp/tmpjd45me00/z11ca9b1.json', 'init=/tmp/tmpjd45me00/haa867av.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model36y5joiz/prophet_model-20260803144852.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:52 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_27_dept_32
Build prophet model for  store_27_dept_33

14:48:52 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/tu0kktuk.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mev53e4i.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=1402', 'data', 'file=/tmp/tmpjd45me00/tu0kktuk.json', 'init=/tmp/tmpjd45me00/mev53e4i.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_8pcfvjc/prophet_model-20260803144852.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:52 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_27_dept_34

14:48:52 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/b085f7vv.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/keronrsn.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=62581', 'data', 'file=/tmp/tmpjd45me00/b085f7vv.json', 'init=/tmp/tmpjd45me00/keronrsn.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelw5mogvwr/prophet_model-20260803144852.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:52 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:52 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_27_dept_35
Build prophet model for  store_27_dept_36

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wjxnoce7.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/tcb8_ijb.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=62253', 'data', 'file=/tmp/tmpjd45me00/wjxnoce7.json', 'init=/tmp/tmpjd45me00/tcb8_ijb.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeluv2vaju0/prophet_model-20260803144852.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:52 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:52 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/b881al1q.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/m2cmjlms.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=85358', 'data', 'file=/tmp/tmpjd45me00/b881al1q.json', 'init=/tmp/tmpjd45me00/m2cmjlms.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelc_i3nooi/prophet_model-20260803144853.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:53 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:53 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_27_dept_37

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6ogpzcdt.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2gwra_j7.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=22106', 'data', 'file=/tmp/tmpjd45me00/6ogpzcdt.json', 'init=/tmp/tmpjd45me00/2gwra_j7.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model2wswsj8m/prophet_model-20260803144853.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:53 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:53 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/q_a7zckc.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/sfs0tkbt.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=81781', 'data', 'file=/tmp/tmpjd45me00/q_a7zckc.json', 'init=/tmp/tmpjd45me00/sfs0tkbt.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model1vgx4ggh/prophet_model-20260803144853.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:53 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_27_dept_38
Build prophet model for  store_27_dept_4

14:48:53 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/aoik1_6o.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/g8s2b8o0.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=64546', 'data', 'file=/tmp/tmpjd45me00/aoik1_6o.json', 'init=/tmp/tmpjd45me00/g8s2b8o0.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelitl37vav/prophet_model-20260803144853.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:53 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:53 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/tqu0rg_s.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fhqkjfnx.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=78488', 'data', 'file=/tmp/tmpjd45me00/tqu0rg_s.json', 'init=/tmp/tmpjd45me00/fhqkjfnx.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model7lst75bi/prophet_model-20260803144853.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:53 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_27_dept_40
Build prophet model for  store_27_dept_41

14:48:53 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/o9fbxf90.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gjter3cs.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=18364', 'data', 'file=/tmp/tmpjd45me00/o9fbxf90.json', 'init=/tmp/tmpjd45me00/gjter3cs.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model2mdqstf1/prophet_model-20260803144854.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:54 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:54 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_27_dept_42

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ha0zaes8.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/in3t5e96.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=27814', 'data', 'file=/tmp/tmpjd45me00/ha0zaes8.json', 'init=/tmp/tmpjd45me00/in3t5e96.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model899cak_7/prophet_model-20260803144854.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:54 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:54 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qjnxf32a.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/v1qsym63.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=36453', 'data', 'file=/tmp/tmpjd45me00/qjnxf32a.json', 'init=/tmp/tmpjd45me00/v1qsym63.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelzwanllru/prophet_model-20260803144854.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:54 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_27_dept_44
Build prophet model for  store_27_dept_46

14:48:54 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fsfuwb61.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zdhidz4i.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=43450', 'data', 'file=/tmp/tmpjd45me00/fsfuwb61.json', 'init=/tmp/tmpjd45me00/zdhidz4i.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modela3z6ehh9/prophet_model-20260803144854.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:54 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:54 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ov1bvy_w.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/kip3ks91.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=66333', 'data', 'file=/tmp/tmpjd45me00/ov1bvy_w.json', 'init=/tmp/tmpjd45me00/kip3ks91.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model6zsvb0e2/prophet_model-20260803144854.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:54 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_27_dept_49
Build prophet model for  store_27_dept_5

14:48:54 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mlbh2nc7.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zwi4wg2f.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=47252', 'data', 'file=/tmp/tmpjd45me00/mlbh2nc7.json', 'init=/tmp/tmpjd45me00/zwi4wg2f.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modele_5hfn1f/prophet_model-20260803144855.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:55 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:55 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/twpkmv7f.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3euinp2w.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=33340', 'data', 'file=/tmp/tmpjd45me00/twpkmv7f.json', 'init=/tmp/tmpjd45me00/3euinp2w.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelhhcny8_w/prophet_model-20260803144855.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:55 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_27_dept_50
Build prophet model for  store_27_dept_52

14:48:55 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/nxzwyag2.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xvdcmpgx.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=69223', 'data', 'file=/tmp/tmpjd45me00/nxzwyag2.json', 'init=/tmp/tmpjd45me00/xvdcmpgx.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelkcj4jonh/prophet_model-20260803144855.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:55 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:55 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_27_dept_54
Build prophet model for  store_27_dept_55

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5y9dgt_0.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/lflagil4.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=10806', 'data', 'file=/tmp/tmpjd45me00/5y9dgt_0.json', 'init=/tmp/tmpjd45me00/lflagil4.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model1nko7w7l/prophet_model-20260803144855.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:55 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:55 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/eqrivhuv.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9ey05vl8.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=12625', 'data', 'file=/tmp/tmpjd45me00/eqrivhuv.json', 'init=/tmp/tmpjd45me00/9ey05vl8.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modell4kixge6/prophet_model-20260803144855.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:55 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_27_dept_56

14:48:55 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/uaho2lsf.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/j2rpdjng.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=11693', 'data', 'file=/tmp/tmpjd45me00/uaho2lsf.json', 'init=/tmp/tmpjd45me00/j2rpdjng.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model9nrqssj1/prophet_model-20260803144856.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:56 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:56 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jugp1fq5.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/e8ea3bcm.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=25258', 'data', 'file=/tmp/tmpjd45me00/jugp1fq5.json', 'init=/tmp/tmpjd45me00/e8ea3bcm.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelvk6ysnie/prophet_model-20260803144856.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:56 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_27_dept_58
Build prophet model for  store_27_dept_59

14:48:56 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/lcbgrbg8.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/66pom_p8.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=84436', 'data', 'file=/tmp/tmpjd45me00/lcbgrbg8.json', 'init=/tmp/tmpjd45me00/66pom_p8.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeletkqve2n/prophet_model-20260803144856.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:56 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:56 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_27_dept_6

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3rgtgfel.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0i3va_nk.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=96838', 'data', 'file=/tmp/tmpjd45me00/3rgtgfel.json', 'init=/tmp/tmpjd45me00/0i3va_nk.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model97bib5gg/prophet_model-20260803144856.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:56 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:56 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_27_dept_67

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/yfclzoaj.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5tsg_vwj.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=6441', 'data', 'file=/tmp/tmpjd45me00/yfclzoaj.json', 'init=/tmp/tmpjd45me00/5tsg_vwj.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model03j5bs4p/prophet_model-20260803144857.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:57 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:57 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_27_dept_7

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5vkv1j93.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8ezhqor7.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=69523', 'data', 'file=/tmp/tmpjd45me00/5vkv1j93.json', 'init=/tmp/tmpjd45me00/8ezhqor7.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modele19pxtk2/prophet_model-20260803144857.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:57 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:57 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_27_dept_71

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_oxfho1v.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/g6ucf8n3.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=66505', 'data', 'file=/tmp/tmpjd45me00/_oxfho1v.json', 'init=/tmp/tmpjd45me00/g6ucf8n3.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model4cnxkpsm/prophet_model-20260803144857.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:57 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:57 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_27_dept_72

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/euqjhz2i.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gogguco9.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=31167', 'data', 'file=/tmp/tmpjd45me00/euqjhz2i.json', 'init=/tmp/tmpjd45me00/gogguco9.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model0prdgt6s/prophet_model-20260803144857.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:57 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:57 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_27_dept_74

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hlzgkoe3.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qa66dyj1.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=78261', 'data', 'file=/tmp/tmpjd45me00/hlzgkoe3.json', 'init=/tmp/tmpjd45me00/qa66dyj1.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeldp33sa9r/prophet_model-20260803144858.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:58 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:58 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_27_dept_79

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/kesbszu5.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pb49ni06.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=7202', 'data', 'file=/tmp/tmpjd45me00/kesbszu5.json', 'init=/tmp/tmpjd45me00/pb49ni06.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelvjn5va5a/prophet_model-20260803144858.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:58 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:58 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_27_dept_8
Build prophet model for  store_27_dept_80

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/psw827ce.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/alm38mr_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=94965', 'data', 'file=/tmp/tmpjd45me00/psw827ce.json', 'init=/tmp/tmpjd45me00/alm38mr_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model1hg9yxh3/prophet_model-20260803144858.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:58 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:58 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/g37t8e74.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/z4xy_44r.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=78670', 'data', 'file=/tmp/tmpjd45me00/g37t8e74.json', 'init=/tmp/tmpjd45me00/z4xy_44r.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model2ij2lj2h/prophet_model-20260803144858.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:58 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:58 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_27_dept_81

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fp5afqq0.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/y8rp8ysg.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=8999', 'data', 'file=/tmp/tmpjd45me00/fp5afqq0.json', 'init=/tmp/tmpjd45me00/y8rp8ysg.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model1ti0yuzc/prophet_model-20260803144859.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:59 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:59 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_27_dept_82
Build prophet model for  store_27_dept_83

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/40ii1zio.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/g4mipdc7.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=32057', 'data', 'file=/tmp/tmpjd45me00/40ii1zio.json', 'init=/tmp/tmpjd45me00/g4mipdc7.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelfvl3i3d3/prophet_model-20260803144859.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:59 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:59 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7w3brg2o.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/on1xabeq.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=9822', 'data', 'file=/tmp/tmpjd45me00/7w3brg2o.json', 'init=/tmp/tmpjd45me00/on1xabeq.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelp45lg1dw/prophet_model-20260803144859.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:59 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_27_dept_85

14:48:59 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9c7yfo6y.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/19o3codh.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=28416', 'data', 'file=/tmp/tmpjd45me00/9c7yfo6y.json', 'init=/tmp/tmpjd45me00/19o3codh.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model190_drm8/prophet_model-20260803144859.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:48:59 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:48:59 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ubtvdjrp.json

Build prophet model for  store_27_dept_87
Build prophet model for  store_27_dept_9

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/t11oqey_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=53240', 'data', 'file=/tmp/tmpjd45me00/ubtvdjrp.json', 'init=/tmp/tmpjd45me00/t11oqey_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeltxs76v5w/prophet_model-20260803144900.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:00 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:00 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9p578fmv.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/l74z_i4q.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=62064', 'data', 'file=/tmp/tmpjd45me00/9p578fmv.json', 'init=/tmp/tmpjd45me00/l74z_i4q.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelz8gwo46k/prophet_model-20260803144900.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:00 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:00 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5aahj8ne.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xsaunyzk.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=84769', 'data', 'file=/tmp/tmpjd45me00/5aahj8ne.json', 'init=/tmp/tmpjd45me00/xsaunyzk.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model9999qfhb/prophet_model-20260803144900.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:00 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_27_dept_90
Build prophet model for  store_27_dept_91

14:49:00 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/u5ejsm0_.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_b8p4l7u.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=98559', 'data', 'file=/tmp/tmpjd45me00/u5ejsm0_.json', 'init=/tmp/tmpjd45me00/_b8p4l7u.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeln9u1dtxo/prophet_model-20260803144900.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:00 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:00 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_27_dept_92
Build prophet model for  store_27_dept_93

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4n8yptyj.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4bwf6z5j.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=24534', 'data', 'file=/tmp/tmpjd45me00/4n8yptyj.json', 'init=/tmp/tmpjd45me00/4bwf6z5j.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelig2xwl5i/prophet_model-20260803144900.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:00 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:00 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_27_dept_94
Build prophet model for  store_27_dept_95

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ccdvqxq6.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5l_a25c1.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=98669', 'data', 'file=/tmp/tmpjd45me00/ccdvqxq6.json', 'init=/tmp/tmpjd45me00/5l_a25c1.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeljnkjie8s/prophet_model-20260803144901.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:01 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_27_dept_96

14:49:01 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zl8gukjf.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mf_5utao.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=67471', 'data', 'file=/tmp/tmpjd45me00/zl8gukjf.json', 'init=/tmp/tmpjd45me00/mf_5utao.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelp4o5_tsa/prophet_model-20260803144901.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:01 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:01 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/u75qo1vp.json

Build prophet model for  store_27_dept_97
Build prophet model for  store_27_dept_98

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rp197a2m.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=54700', 'data', 'file=/tmp/tmpjd45me00/u75qo1vp.json', 'init=/tmp/tmpjd45me00/rp197a2m.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model30k04af4/prophet_model-20260803144901.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:01 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:01 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ctg5ta3m.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/cy81wmad.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=35106', 'data', 'file=/tmp/tmpjd45me00/ctg5ta3m.json', 'init=/tmp/tmpjd45me00/cy81wmad.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model4326t6rf/prophet_model-20260803144901.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:01 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:01 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7y7pg7eh.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/uyewrqdd.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=48402', 'data', 'file=/tmp/tmpjd45me00/7y7pg7eh.json', 'init=/tmp/tmpjd45me00/uyewrqdd.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelov5a9e6b/prophet_model-20260803144901.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:01 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_28_dept_1
Build prophet model for  store_28_dept_10

14:49:01 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/q_joki55.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0uce_qg9.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=2576', 'data', 'file=/tmp/tmpjd45me00/q_joki55.json', 'init=/tmp/tmpjd45me00/0uce_qg9.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeleab8waxw/prophet_model-20260803144902.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:02 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:02 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/nif6fi3m.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fjwl3vqf.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=24921', 'data', 'file=/tmp/tmpjd45me00/nif6fi3m.json', 'init=/tmp/tmpjd45me00/fjwl3vqf.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelnw7p9wvr/prophet_model-20260803144902.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:02 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_28_dept_11
Build prophet model for  store_28_dept_12

14:49:02 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0aqz0k69.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/n09t6uh1.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=58183', 'data', 'file=/tmp/tmpjd45me00/0aqz0k69.json', 'init=/tmp/tmpjd45me00/n09t6uh1.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelsi_o30_3/prophet_model-20260803144902.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:02 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:02 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/scj8r5si.json

Build prophet model for  store_28_dept_13
Build prophet model for  store_28_dept_14

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xu3zqs78.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=79320', 'data', 'file=/tmp/tmpjd45me00/scj8r5si.json', 'init=/tmp/tmpjd45me00/xu3zqs78.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model8how0emg/prophet_model-20260803144902.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:02 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:02 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mntczmqx.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pz5ii0wc.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=73388', 'data', 'file=/tmp/tmpjd45me00/mntczmqx.json', 'init=/tmp/tmpjd45me00/pz5ii0wc.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelylkhujcl/prophet_model-20260803144902.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:02 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:02 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8qquhj5m.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rvo4j4f5.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=77656', 'data', 'file=/tmp/tmpjd45me00/8qquhj5m.json', 'init=/tmp/tmpjd45me00/rvo4j4f5.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelwosj3er_/prophet_model-20260803144902.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:02 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_28_dept_16
Build prophet model for  store_28_dept_17

14:49:02 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1lzy9728.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bjdyhwq4.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=56858', 'data', 'file=/tmp/tmpjd45me00/1lzy9728.json', 'init=/tmp/tmpjd45me00/bjdyhwq4.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model1pw5lnnt/prophet_model-20260803144902.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:49:02 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_28_dept_18

14:49:03 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hu1xu8y6.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rrw3gsk3.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=42732', 'data', 'file=/tmp/tmpjd45me00/hu1xu8y6.json', 'init=/tmp/tmpjd45me00/rrw3gsk3.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelom2y8wha/prophet_model-20260803144904.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:04 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:04 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_28_dept_19
Build prophet model for  store_28_dept_2

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/v7li3j2m.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/57j60if_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=50384', 'data', 'file=/tmp/tmpjd45me00/v7li3j2m.json', 'init=/tmp/tmpjd45me00/57j60if_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelptcki9ei/prophet_model-20260803144904.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:04 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:04 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jzqn2xkv.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/eztwf4l4.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=26682', 'data', 'file=/tmp/tmpjd45me00/jzqn2xkv.json', 'init=/tmp/tmpjd45me00/eztwf4l4.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeljxnoaftq/prophet_model-20260803144904.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:04 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:04 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_28_dept_20
Build prophet model for  store_28_dept_21

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zfepqbc9.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fcz08da3.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=92998', 'data', 'file=/tmp/tmpjd45me00/zfepqbc9.json', 'init=/tmp/tmpjd45me00/fcz08da3.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeltmux3t1f/prophet_model-20260803144904.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:04 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:04 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/m_acnpmx.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/sbkixhuf.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=94293', 'data', 'file=/tmp/tmpjd45me00/m_acnpmx.json', 'init=/tmp/tmpjd45me00/sbkixhuf.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelszov64k3/prophet_model-20260803144904.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:04 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:04 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/j5a86rv1.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9a6lm312.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=92383', 'data', 'file=/tmp/tmpjd45me00/j5a86rv1.json', 'init=/tmp/tmpjd45me00/9a6lm312.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelo6z2tqo1/prophet_model-20260803144904.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:04 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_28_dept_22
Build prophet model for  store_28_dept_23

14:49:04 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ferwhm83.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/evpfwv7_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=45411', 'data', 'file=/tmp/tmpjd45me00/ferwhm83.json', 'init=/tmp/tmpjd45me00/evpfwv7_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelo8ful5sk/prophet_model-20260803144905.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:05 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:05 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/f9s7rpez.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0bl38q33.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=41061', 'data', 'file=/tmp/tmpjd45me00/f9s7rpez.json', 'init=/tmp/tmpjd45me00/0bl38q33.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeloig9uo6t/prophet_model-20260803144905.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:05 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_28_dept_24
Build prophet model for  store_28_dept_25

14:49:05 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4bwmv5io.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/y2cc035_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=60461', 'data', 'file=/tmp/tmpjd45me00/4bwmv5io.json', 'init=/tmp/tmpjd45me00/y2cc035_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model3nqjstoq/prophet_model-20260803144905.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:05 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:05 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mhs6p6az.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6w3s1hxn.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=13871', 'data', 'file=/tmp/tmpjd45me00/mhs6p6az.json', 'init=/tmp/tmpjd45me00/6w3s1hxn.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modela4fa3j49/prophet_model-20260803144905.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:05 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_28_dept_26
Build prophet model for  store_28_dept_27

14:49:05 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/f6kqz2ro.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9yclrzj3.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=27233', 'data', 'file=/tmp/tmpjd45me00/f6kqz2ro.json', 'init=/tmp/tmpjd45me00/9yclrzj3.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelcm6az04v/prophet_model-20260803144905.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:05 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:05 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6782fpqy.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qkcaetkf.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=93635', 'data', 'file=/tmp/tmpjd45me00/6782fpqy.json', 'init=/tmp/tmpjd45me00/qkcaetkf.json', 'output', 'file=/tmp/tmpjd45me00/prophet_models7ifrlue/prophet_model-20260803144905.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:05 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_28_dept_28
Build prophet model for  store_28_dept_29

14:49:05 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xux5g48y.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2mr50qh5.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=11599', 'data', 'file=/tmp/tmpjd45me00/xux5g48y.json', 'init=/tmp/tmpjd45me00/2mr50qh5.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model2ojr86pf/prophet_model-20260803144906.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:06 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:06 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qrcirmj5.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/q3_t00ld.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=91085', 'data', 'file=/tmp/tmpjd45me00/qrcirmj5.json', 'init=/tmp/tmpjd45me00/q3_t00ld.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelyu3w_g2l/prophet_model-20260803144906.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:06 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_28_dept_3
Build prophet model for  store_28_dept_30

14:49:06 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/spf7hiva.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mw6sa0wg.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=14317', 'data', 'file=/tmp/tmpjd45me00/spf7hiva.json', 'init=/tmp/tmpjd45me00/mw6sa0wg.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeli5s7drm_/prophet_model-20260803144906.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:06 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:06 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/uswo14a_.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/f5spgopi.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=43117', 'data', 'file=/tmp/tmpjd45me00/uswo14a_.json', 'init=/tmp/tmpjd45me00/f5spgopi.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model5_3yhy25/prophet_model-20260803144906.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:06 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_28_dept_31
Build prophet model for  store_28_dept_32

14:49:06 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/i5ezbsn2.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bkerlcn3.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=31055', 'data', 'file=/tmp/tmpjd45me00/i5ezbsn2.json', 'init=/tmp/tmpjd45me00/bkerlcn3.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_cm7357_/prophet_model-20260803144906.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:06 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:06 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/it_0pq_e.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/io9y9c3e.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=16749', 'data', 'file=/tmp/tmpjd45me00/it_0pq_e.json', 'init=/tmp/tmpjd45me00/io9y9c3e.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model0d_63jvr/prophet_model-20260803144906.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:06 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_28_dept_33
Build prophet model for  store_28_dept_34

14:49:06 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/54ku9t_t.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/j1zw9unk.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=2123', 'data', 'file=/tmp/tmpjd45me00/54ku9t_t.json', 'init=/tmp/tmpjd45me00/j1zw9unk.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelfu640xpd/prophet_model-20260803144907.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:07 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:07 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/exflh0wt.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/c2qhnu3q.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=7988', 'data', 'file=/tmp/tmpjd45me00/exflh0wt.json', 'init=/tmp/tmpjd45me00/c2qhnu3q.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelqn9eaxt9/prophet_model-20260803144907.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:07 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_28_dept_35
Build prophet model for  store_28_dept_36

14:49:07 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qxhtzgit.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4j4lyz5_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=15372', 'data', 'file=/tmp/tmpjd45me00/qxhtzgit.json', 'init=/tmp/tmpjd45me00/4j4lyz5_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelnpg0t_96/prophet_model-20260803144907.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:07 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:07 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/tujqg2rg.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/14i1ul6z.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=71503', 'data', 'file=/tmp/tmpjd45me00/tujqg2rg.json', 'init=/tmp/tmpjd45me00/14i1ul6z.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model45u55a8y/prophet_model-20260803144907.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:07 - cmdstanpy - INFO - Chain [1] start processing

Build prophet model for  store_28_dept_37
Build prophet model for  store_28_dept_38

INFO:cmdstanpy:Chain [1] start processing
14:49:07 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/myhk9hes.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/u80zii_a.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=46820', 'data', 'file=/tmp/tmpjd45me00/myhk9hes.json', 'init=/tmp/tmpjd45me00/u80zii_a.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model42thl3c4/prophet_model-20260803144907.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:07 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:07 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dmxf7pot.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/szckf1h1.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=42432', 'data', 'file=/tmp/tmpjd45me00/dmxf7pot.json', 'init=/tmp/tmpjd45me00/szckf1h1.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelsz234dfu/prophet_model-20260803144907.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:07 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_28_dept_4
Build prophet model for  store_28_dept_40

14:49:07 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/cwql84of.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/q6wqca04.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=26044', 'data', 'file=/tmp/tmpjd45me00/cwql84of.json', 'init=/tmp/tmpjd45me00/q6wqca04.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeli8uf73hd/prophet_model-20260803144908.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:08 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:08 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fam1jv8f.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mwy7n8y0.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=48918', 'data', 'file=/tmp/tmpjd45me00/fam1jv8f.json', 'init=/tmp/tmpjd45me00/mwy7n8y0.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelv4c2n5_u/prophet_model-20260803144908.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:08 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_28_dept_41
Build prophet model for  store_28_dept_42

14:49:08 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xq94l6o5.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/e8qr5abz.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=19784', 'data', 'file=/tmp/tmpjd45me00/xq94l6o5.json', 'init=/tmp/tmpjd45me00/e8qr5abz.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelckgdw595/prophet_model-20260803144908.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:08 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:08 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wp0dtedy.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/sw7vt8e_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=86051', 'data', 'file=/tmp/tmpjd45me00/wp0dtedy.json', 'init=/tmp/tmpjd45me00/sw7vt8e_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelchpb636k/prophet_model-20260803144908.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:08 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_28_dept_44
Build prophet model for  store_28_dept_46

14:49:08 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0cqybnyu.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/d_frc8fu.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=48587', 'data', 'file=/tmp/tmpjd45me00/0cqybnyu.json', 'init=/tmp/tmpjd45me00/d_frc8fu.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelbqei28rk/prophet_model-20260803144908.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:08 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:08 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/damgx0g_.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_u3jqdy2.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None

Build prophet model for  store_28_dept_49
Build prophet model for  store_28_dept_5

DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=75088', 'data', 'file=/tmp/tmpjd45me00/damgx0g_.json', 'init=/tmp/tmpjd45me00/_u3jqdy2.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model70ekpsko/prophet_model-20260803144908.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:08 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:08 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/srl7ffr5.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vmjhagr_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=69762', 'data', 'file=/tmp/tmpjd45me00/srl7ffr5.json', 'init=/tmp/tmpjd45me00/vmjhagr_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_3yun1nt/prophet_model-20260803144909.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:09 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:09 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_28_dept_52
Build prophet model for  store_28_dept_54

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hyem9a43.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/l6z27d80.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=61204', 'data', 'file=/tmp/tmpjd45me00/hyem9a43.json', 'init=/tmp/tmpjd45me00/l6z27d80.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelut9_n1_r/prophet_model-20260803144909.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:09 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:09 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5difwt2_.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/l9ki8gce.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=99272', 'data', 'file=/tmp/tmpjd45me00/5difwt2_.json', 'init=/tmp/tmpjd45me00/l9ki8gce.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model3s_c4qe8/prophet_model-20260803144909.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:09 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:09 - cmdstanpy - INFO - Chain [1] done processing

Build prophet model for  store_28_dept_55

INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/r8g6v_hc.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_2tjf6v2.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=97600', 'data', 'file=/tmp/tmpjd45me00/r8g6v_hc.json', 'init=/tmp/tmpjd45me00/_2tjf6v2.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelkn34fdbs/prophet_model-20260803144909.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:09 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:09 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_28_dept_56

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/npe6xr1s.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/tb3tc06u.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=94803', 'data', 'file=/tmp/tmpjd45me00/npe6xr1s.json', 'init=/tmp/tmpjd45me00/tb3tc06u.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelzm_frrji/prophet_model-20260803144910.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:10 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_28_dept_58

14:49:10 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8klimpxi.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xm82qo3n.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=30414', 'data', 'file=/tmp/tmpjd45me00/8klimpxi.json', 'init=/tmp/tmpjd45me00/xm82qo3n.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelfonl_u0w/prophet_model-20260803144910.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:10 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_28_dept_59

14:49:10 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2zo37mq4.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/boqmczdf.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=65320', 'data', 'file=/tmp/tmpjd45me00/2zo37mq4.json', 'init=/tmp/tmpjd45me00/boqmczdf.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelwuydv03y/prophet_model-20260803144910.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:10 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:11 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_28_dept_6

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fpndmhyy.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/at6brply.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=95343', 'data', 'file=/tmp/tmpjd45me00/fpndmhyy.json', 'init=/tmp/tmpjd45me00/at6brply.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeltjkzo8vb/prophet_model-20260803144911.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:11 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:11 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_28_dept_60
Build prophet model for  store_28_dept_67

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ccnxf22e.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_b4xuxrj.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=30655', 'data', 'file=/tmp/tmpjd45me00/ccnxf22e.json', 'init=/tmp/tmpjd45me00/_b4xuxrj.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model8usik45q/prophet_model-20260803144911.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:11 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:11 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6bdi1mjo.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xps0sbpv.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=1399', 'data', 'file=/tmp/tmpjd45me00/6bdi1mjo.json', 'init=/tmp/tmpjd45me00/xps0sbpv.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelhzud00_j/prophet_model-20260803144911.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:11 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:11 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_28_dept_7
Build prophet model for  store_28_dept_71

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/d6ifaof1.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ynkbtkj5.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=90861', 'data', 'file=/tmp/tmpjd45me00/d6ifaof1.json', 'init=/tmp/tmpjd45me00/ynkbtkj5.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelwerbni0i/prophet_model-20260803144911.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:11 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:11 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5p00hs8x.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0o2946em.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=94003', 'data', 'file=/tmp/tmpjd45me00/5p00hs8x.json', 'init=/tmp/tmpjd45me00/0o2946em.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelmtwb8fpz/prophet_model-20260803144912.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:12 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:12 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_28_dept_72
Build prophet model for  store_28_dept_74

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/nrglx_lq.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/d6ma44iq.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=78430', 'data', 'file=/tmp/tmpjd45me00/nrglx_lq.json', 'init=/tmp/tmpjd45me00/d6ma44iq.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model6ao0zzh_/prophet_model-20260803144912.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:12 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:12 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_rcx4qz9.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/x_d0pq0m.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=78636', 'data', 'file=/tmp/tmpjd45me00/_rcx4qz9.json', 'init=/tmp/tmpjd45me00/x_d0pq0m.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelry5lrkfv/prophet_model-20260803144912.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:12 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:12 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/l9ubequb.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/uzt1dfoi.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=10143', 'data', 'file=/tmp/tmpjd45me00/l9ubequb.json', 'init=/tmp/tmpjd45me00/uzt1dfoi.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeljb46cvqx/prophet_model-20260803144912.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:12 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_28_dept_79
Build prophet model for  store_28_dept_8

14:49:12 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6pm6fr9t.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/76m7w7bf.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=45074', 'data', 'file=/tmp/tmpjd45me00/6pm6fr9t.json', 'init=/tmp/tmpjd45me00/76m7w7bf.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model1r1axred/prophet_model-20260803144912.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:12 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:12 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_28_dept_80
Build prophet model for  store_28_dept_81

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ho3lfq9t.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/txobhy08.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=97837', 'data', 'file=/tmp/tmpjd45me00/ho3lfq9t.json', 'init=/tmp/tmpjd45me00/txobhy08.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model3ewzx4u9/prophet_model-20260803144913.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:13 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:13 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/peyjy39d.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/abqz0dny.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=24686', 'data', 'file=/tmp/tmpjd45me00/peyjy39d.json', 'init=/tmp/tmpjd45me00/abqz0dny.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modele2i5lsne/prophet_model-20260803144913.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:13 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:13 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_28_dept_82
Build prophet model for  store_28_dept_83

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3do0tjyw.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mz6jc7yx.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=29601', 'data', 'file=/tmp/tmpjd45me00/3do0tjyw.json', 'init=/tmp/tmpjd45me00/mz6jc7yx.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelqrlmv2if/prophet_model-20260803144913.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:13 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:13 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/azmazqhj.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5gad458l.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=19051', 'data', 'file=/tmp/tmpjd45me00/azmazqhj.json', 'init=/tmp/tmpjd45me00/5gad458l.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeldcj3re56/prophet_model-20260803144913.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:13 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:13 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_28_dept_85
Build prophet model for  store_28_dept_87

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/g2of8p42.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pcm4axtm.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=38325', 'data', 'file=/tmp/tmpjd45me00/g2of8p42.json', 'init=/tmp/tmpjd45me00/pcm4axtm.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modellgn9i2mc/prophet_model-20260803144913.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:13 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:13 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/trq5_axq.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2amgub2n.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=95938', 'data', 'file=/tmp/tmpjd45me00/trq5_axq.json', 'init=/tmp/tmpjd45me00/2amgub2n.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelgtad40bc/prophet_model-20260803144913.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:13 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:13 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/lvku1f6v.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dxcwxwwl.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None

Build prophet model for  store_28_dept_9
Build prophet model for  store_28_dept_90

DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=47148', 'data', 'file=/tmp/tmpjd45me00/lvku1f6v.json', 'init=/tmp/tmpjd45me00/dxcwxwwl.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelgqnk2daf/prophet_model-20260803144914.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:14 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:14 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qm2ktd9d.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/nsb2h43i.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=10741', 'data', 'file=/tmp/tmpjd45me00/qm2ktd9d.json', 'init=/tmp/tmpjd45me00/nsb2h43i.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model5_qv5x15/prophet_model-20260803144914.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:14 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:14 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fvcvcp3n.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fcptokx7.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=39879', 'data', 'file=/tmp/tmpjd45me00/fvcvcp3n.json', 'init=/tmp/tmpjd45me00/fcptokx7.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model5kr0_242/prophet_model-20260803144914.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:14 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_28_dept_91
Build prophet model for  store_28_dept_92

14:49:14 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xzhuspwk.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fxrupcmw.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=68595', 'data', 'file=/tmp/tmpjd45me00/xzhuspwk.json', 'init=/tmp/tmpjd45me00/fxrupcmw.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model038ipojc/prophet_model-20260803144914.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:14 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:14 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_kba08t3.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7qclhq7w.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=43657', 'data', 'file=/tmp/tmpjd45me00/_kba08t3.json', 'init=/tmp/tmpjd45me00/7qclhq7w.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modely2nyglcx/prophet_model-20260803144914.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:14 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:14 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_28_dept_93
Build prophet model for  store_28_dept_94

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/o9pu0cse.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hg7y8cyr.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=42958', 'data', 'file=/tmp/tmpjd45me00/o9pu0cse.json', 'init=/tmp/tmpjd45me00/hg7y8cyr.json', 'output', 'file=/tmp/tmpjd45me00/prophet_models7nfqdws/prophet_model-20260803144914.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:14 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:14 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/96a_obpj.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zcw0ajdd.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=1757', 'data', 'file=/tmp/tmpjd45me00/96a_obpj.json', 'init=/tmp/tmpjd45me00/zcw0ajdd.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelmo9ehdo5/prophet_model-20260803144914.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:14 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_28_dept_95
Build prophet model for  store_28_dept_96

14:49:14 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4ioe55ny.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ha97_vs_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=97527', 'data', 'file=/tmp/tmpjd45me00/4ioe55ny.json', 'init=/tmp/tmpjd45me00/ha97_vs_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modellqah7qbf/prophet_model-20260803144915.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:15 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:15 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6qoh2x3m.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4yc5khps.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=54799', 'data', 'file=/tmp/tmpjd45me00/6qoh2x3m.json', 'init=/tmp/tmpjd45me00/4yc5khps.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeloncrtqrk/prophet_model-20260803144915.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:15 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_28_dept_97
Build prophet model for  store_28_dept_98

14:49:15 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/k4zfnf8s.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fop9zsgg.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=73125', 'data', 'file=/tmp/tmpjd45me00/k4zfnf8s.json', 'init=/tmp/tmpjd45me00/fop9zsgg.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modell0natgr0/prophet_model-20260803144915.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:15 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:15 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/b9y5rwqn.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/is4fq56o.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=88506', 'data', 'file=/tmp/tmpjd45me00/b9y5rwqn.json', 'init=/tmp/tmpjd45me00/is4fq56o.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modellreryarr/prophet_model-20260803144915.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:15 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_29_dept_1
Build prophet model for  store_29_dept_10

14:49:15 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9gm4dwko.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/x3u9vpet.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=8988', 'data', 'file=/tmp/tmpjd45me00/9gm4dwko.json', 'init=/tmp/tmpjd45me00/x3u9vpet.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelxwpyrbf1/prophet_model-20260803144915.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:15 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:15 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/k7g9ar_8.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/54wx0srs.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=22159', 'data', 'file=/tmp/tmpjd45me00/k7g9ar_8.json', 'init=/tmp/tmpjd45me00/54wx0srs.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelc80o1nk9/prophet_model-20260803144915.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:15 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_29_dept_11
Build prophet model for  store_29_dept_12

14:49:15 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dzg5q_fn.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1o2klqi1.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=26286', 'data', 'file=/tmp/tmpjd45me00/dzg5q_fn.json', 'init=/tmp/tmpjd45me00/1o2klqi1.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model9u3w5ej9/prophet_model-20260803144916.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:16 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:16 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_29_dept_13

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8gmaqib5.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1w8tkw9t.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=84726', 'data', 'file=/tmp/tmpjd45me00/8gmaqib5.json', 'init=/tmp/tmpjd45me00/1w8tkw9t.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model7zqdusvh/prophet_model-20260803144916.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:16 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:16 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xl2wby5i.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/m_tq1_dt.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=37518', 'data', 'file=/tmp/tmpjd45me00/xl2wby5i.json', 'init=/tmp/tmpjd45me00/m_tq1_dt.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelik54ry83/prophet_model-20260803144916.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:16 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_29_dept_14
Build prophet model for  store_29_dept_16

14:49:16 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/o476f3yg.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pke1f2yz.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=3999', 'data', 'file=/tmp/tmpjd45me00/o476f3yg.json', 'init=/tmp/tmpjd45me00/pke1f2yz.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeljsvhqyzl/prophet_model-20260803144916.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:16 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:16 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pteuf0wf.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pugn06dd.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=67965', 'data', 'file=/tmp/tmpjd45me00/pteuf0wf.json', 'init=/tmp/tmpjd45me00/pugn06dd.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeld_q_begq/prophet_model-20260803144916.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:49:16 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_29_dept_17
Build prophet model for  store_29_dept_18

14:49:17 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fd9m1agu.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/lq0iahsx.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=43646', 'data', 'file=/tmp/tmpjd45me00/fd9m1agu.json', 'init=/tmp/tmpjd45me00/lq0iahsx.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelwt9j11ej/prophet_model-20260803144917.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:17 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:18 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/t07arlym.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/t9hurptx.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=83585', 'data', 'file=/tmp/tmpjd45me00/t07arlym.json', 'init=/tmp/tmpjd45me00/t9hurptx.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelg90jiga7/prophet_model-20260803144918.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:18 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_29_dept_2
Build prophet model for  store_29_dept_20

14:49:18 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/oytstbb7.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ddvmpo9c.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=57409', 'data', 'file=/tmp/tmpjd45me00/oytstbb7.json', 'init=/tmp/tmpjd45me00/ddvmpo9c.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelz7f1ng3q/prophet_model-20260803144918.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:18 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:18 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/f_mxlmio.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ytcou9xe.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=90506', 'data', 'file=/tmp/tmpjd45me00/f_mxlmio.json', 'init=/tmp/tmpjd45me00/ytcou9xe.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model38l1g54t/prophet_model-20260803144918.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:18 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_29_dept_21
Build prophet model for  store_29_dept_22

14:49:18 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wk9zhj_y.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/v8yj7ip7.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=44280', 'data', 'file=/tmp/tmpjd45me00/wk9zhj_y.json', 'init=/tmp/tmpjd45me00/v8yj7ip7.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelymkueeph/prophet_model-20260803144918.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:18 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:18 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6yjnqxhw.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5_wse7_l.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=83039', 'data', 'file=/tmp/tmpjd45me00/6yjnqxhw.json', 'init=/tmp/tmpjd45me00/5_wse7_l.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelybifx3yo/prophet_model-20260803144918.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:18 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_29_dept_23
Build prophet model for  store_29_dept_24

14:49:18 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mop68idn.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8jon0rcu.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=81206', 'data', 'file=/tmp/tmpjd45me00/mop68idn.json', 'init=/tmp/tmpjd45me00/8jon0rcu.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelaoilom9t/prophet_model-20260803144918.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:18 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:19 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_29_dept_25
Build prophet model for  store_29_dept_26

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qsflpoff.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4z5__7b6.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=74685', 'data', 'file=/tmp/tmpjd45me00/qsflpoff.json', 'init=/tmp/tmpjd45me00/4z5__7b6.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelfdtvymud/prophet_model-20260803144919.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:19 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:19 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/i_18uy4k.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zl6sweo8.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=60305', 'data', 'file=/tmp/tmpjd45me00/i_18uy4k.json', 'init=/tmp/tmpjd45me00/zl6sweo8.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelcme7a6db/prophet_model-20260803144919.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:19 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:19 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2c5_6nui.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/p1n2ep91.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=95233', 'data', 'file=/tmp/tmpjd45me00/2c5_6nui.json', 'init=/tmp/tmpjd45me00/p1n2ep91.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelx3hjx315/prophet_model-20260803144919.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:19 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_29_dept_27
Build prophet model for  store_29_dept_28

14:49:19 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0g7dzjc9.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dedwizne.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=80238', 'data', 'file=/tmp/tmpjd45me00/0g7dzjc9.json', 'init=/tmp/tmpjd45me00/dedwizne.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelik_92jiy/prophet_model-20260803144919.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:19 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:19 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pefn81pc.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wu1zs0lz.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=69840', 'data', 'file=/tmp/tmpjd45me00/pefn81pc.json', 'init=/tmp/tmpjd45me00/wu1zs0lz.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeln4z4ky41/prophet_model-20260803144919.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:19 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_29_dept_29
Build prophet model for  store_29_dept_3

14:49:19 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fizfe82k.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0z0y95h5.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=43886', 'data', 'file=/tmp/tmpjd45me00/fizfe82k.json', 'init=/tmp/tmpjd45me00/0z0y95h5.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelyb7xbvc3/prophet_model-20260803144919.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:19 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:19 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/n9h698v5.json

Build prophet model for  store_29_dept_30
Build prophet model for  store_29_dept_31

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qd2hks03.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=62185', 'data', 'file=/tmp/tmpjd45me00/n9h698v5.json', 'init=/tmp/tmpjd45me00/qd2hks03.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelu7gx1ibc/prophet_model-20260803144920.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:20 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:20 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/c8yx8_dw.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/oe72g6ld.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=72842', 'data', 'file=/tmp/tmpjd45me00/c8yx8_dw.json', 'init=/tmp/tmpjd45me00/oe72g6ld.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelpdjrq64h/prophet_model-20260803144920.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:20 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:20 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/sir6dtn4.json

Build prophet model for  store_29_dept_32
Build prophet model for  store_29_dept_33

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fdoab99e.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=85888', 'data', 'file=/tmp/tmpjd45me00/sir6dtn4.json', 'init=/tmp/tmpjd45me00/fdoab99e.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelp5aealn6/prophet_model-20260803144920.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:20 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:20 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/nsdg9lgn.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/uyjrydsm.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=54792', 'data', 'file=/tmp/tmpjd45me00/nsdg9lgn.json', 'init=/tmp/tmpjd45me00/uyjrydsm.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_lskqab6/prophet_model-20260803144920.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:20 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:20 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_29_dept_34

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_28sjehb.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qz2bfkf0.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=54155', 'data', 'file=/tmp/tmpjd45me00/_28sjehb.json', 'init=/tmp/tmpjd45me00/qz2bfkf0.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model1q3rg9wf/prophet_model-20260803144920.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:20 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:20 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_29_dept_35
Build prophet model for  store_29_dept_36

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/akq4f2bx.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_14768_g.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=95153', 'data', 'file=/tmp/tmpjd45me00/akq4f2bx.json', 'init=/tmp/tmpjd45me00/_14768_g.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelmrb9hog5/prophet_model-20260803144920.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:20 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:21 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/33b5f995.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4x4gh3rz.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=69529', 'data', 'file=/tmp/tmpjd45me00/33b5f995.json', 'init=/tmp/tmpjd45me00/4x4gh3rz.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modele2hdwb6d/prophet_model-20260803144921.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:21 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:21 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_08766tg.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ty1k_lkq.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=55833', 'data', 'file=/tmp/tmpjd45me00/_08766tg.json', 'init=/tmp/tmpjd45me00/ty1k_lkq.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelo_0e_942/prophet_model-20260803144921.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:21 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_29_dept_38
Build prophet model for  store_29_dept_4

14:49:21 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ng4n3txv.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jtp25lld.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=72237', 'data', 'file=/tmp/tmpjd45me00/ng4n3txv.json', 'init=/tmp/tmpjd45me00/jtp25lld.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelxmop_f5r/prophet_model-20260803144921.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:21 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:22 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_29_dept_40

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/d89v0d16.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/d5z3hplr.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=12623', 'data', 'file=/tmp/tmpjd45me00/d89v0d16.json', 'init=/tmp/tmpjd45me00/d5z3hplr.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model9k4yefhr/prophet_model-20260803144922.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:22 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:22 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_29_dept_41
Build prophet model for  store_29_dept_42

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/g2yt_tkk.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/z8xrvbnx.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=19891', 'data', 'file=/tmp/tmpjd45me00/g2yt_tkk.json', 'init=/tmp/tmpjd45me00/z8xrvbnx.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelwta3br8t/prophet_model-20260803144922.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:22 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:22 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0kamyza8.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ozmouavv.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=99562', 'data', 'file=/tmp/tmpjd45me00/0kamyza8.json', 'init=/tmp/tmpjd45me00/ozmouavv.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelumna2p2p/prophet_model-20260803144922.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:22 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_29_dept_44

14:49:22 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wqnbe7xc.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/uzl_ps8m.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=26141', 'data', 'file=/tmp/tmpjd45me00/wqnbe7xc.json', 'init=/tmp/tmpjd45me00/uzl_ps8m.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelzj9lzp6d/prophet_model-20260803144923.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:23 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:23 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_29_dept_46

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2bvt_n7p.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/upz2hzi0.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=88573', 'data', 'file=/tmp/tmpjd45me00/2bvt_n7p.json', 'init=/tmp/tmpjd45me00/upz2hzi0.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeljzos2m44/prophet_model-20260803144923.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:23 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:23 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_29_dept_5
Build prophet model for  store_29_dept_52

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7f5sgww6.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/d49ok2fw.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=26326', 'data', 'file=/tmp/tmpjd45me00/7f5sgww6.json', 'init=/tmp/tmpjd45me00/d49ok2fw.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeleg2oa13f/prophet_model-20260803144924.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:24 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:24 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/601e7tst.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/67j41yve.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=640', 'data', 'file=/tmp/tmpjd45me00/601e7tst.json', 'init=/tmp/tmpjd45me00/67j41yve.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeljqtmq3xu/prophet_model-20260803144924.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:49:24 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_29_dept_54

14:49:25 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/a2ig6fnz.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ugvbru3x.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=47681', 'data', 'file=/tmp/tmpjd45me00/a2ig6fnz.json', 'init=/tmp/tmpjd45me00/ugvbru3x.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeleql51a29/prophet_model-20260803144925.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:25 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_29_dept_55

14:49:26 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/y_wd3vo_.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/l6r8xemw.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=23327', 'data', 'file=/tmp/tmpjd45me00/y_wd3vo_.json', 'init=/tmp/tmpjd45me00/l6r8xemw.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelpea9xt29/prophet_model-20260803144926.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:26 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_29_dept_56

14:49:26 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/heny7bin.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/g4ogsjqu.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=40636', 'data', 'file=/tmp/tmpjd45me00/heny7bin.json', 'init=/tmp/tmpjd45me00/g4ogsjqu.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelkrp_nkv2/prophet_model-20260803144926.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:49:26 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_29_dept_58

14:49:27 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/yge7kx2w.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/uo9kmoxd.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=4768', 'data', 'file=/tmp/tmpjd45me00/yge7kx2w.json', 'init=/tmp/tmpjd45me00/uo9kmoxd.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelw4bxa_cs/prophet_model-20260803144927.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:27 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_29_dept_59

14:49:27 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ujfp2751.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/io5k8b6d.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=31956', 'data', 'file=/tmp/tmpjd45me00/ujfp2751.json', 'init=/tmp/tmpjd45me00/io5k8b6d.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelaf04egxy/prophet_model-20260803144927.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:27 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:28 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_29_dept_6

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/i9h73c4h.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4p_a6q76.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=20904', 'data', 'file=/tmp/tmpjd45me00/i9h73c4h.json', 'init=/tmp/tmpjd45me00/4p_a6q76.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeld_lth2wm/prophet_model-20260803144928.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:28 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:28 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1njxq58m.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6dmm7m_u.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=90387', 'data', 'file=/tmp/tmpjd45me00/1njxq58m.json', 'init=/tmp/tmpjd45me00/6dmm7m_u.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelbu35x2lk/prophet_model-20260803144928.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:28 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:28 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_29_dept_67
Build prophet model for  store_29_dept_7

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ivx_rmv3.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/i7cqhb0h.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=10761', 'data', 'file=/tmp/tmpjd45me00/ivx_rmv3.json', 'init=/tmp/tmpjd45me00/i7cqhb0h.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelocznspz8/prophet_model-20260803144928.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:28 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:28 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bpnjeb54.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pqte06v9.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=21979', 'data', 'file=/tmp/tmpjd45me00/bpnjeb54.json', 'init=/tmp/tmpjd45me00/pqte06v9.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model4icergc0/prophet_model-20260803144928.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:28 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:28 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_29_dept_71
Build prophet model for  store_29_dept_72

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ml57o_jy.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/k6kcxnng.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=3234', 'data', 'file=/tmp/tmpjd45me00/ml57o_jy.json', 'init=/tmp/tmpjd45me00/k6kcxnng.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelwy0d4qga/prophet_model-20260803144928.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:28 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:28 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_29_dept_74

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wixb1dy_.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/m0ukzi3m.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=95500', 'data', 'file=/tmp/tmpjd45me00/wixb1dy_.json', 'init=/tmp/tmpjd45me00/m0ukzi3m.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelj94wfxef/prophet_model-20260803144929.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:29 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:29 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/m_wwk862.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/j8dbjwtc.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=76433', 'data', 'file=/tmp/tmpjd45me00/m_wwk862.json', 'init=/tmp/tmpjd45me00/j8dbjwtc.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model84xbni0a/prophet_model-20260803144929.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:29 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_29_dept_79
Build prophet model for  store_29_dept_8

14:49:29 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/lut94pi5.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1pnay84v.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=27674', 'data', 'file=/tmp/tmpjd45me00/lut94pi5.json', 'init=/tmp/tmpjd45me00/1pnay84v.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelbac5d30x/prophet_model-20260803144929.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:29 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:29 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hgd78af2.json

Build prophet model for  store_29_dept_81
Build prophet model for  store_29_dept_82

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qo8694si.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=60849', 'data', 'file=/tmp/tmpjd45me00/hgd78af2.json', 'init=/tmp/tmpjd45me00/qo8694si.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model49wlunxw/prophet_model-20260803144929.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:29 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:29 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/thhepn4r.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rtz9od55.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=75348', 'data', 'file=/tmp/tmpjd45me00/thhepn4r.json', 'init=/tmp/tmpjd45me00/rtz9od55.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelh8mn6rn8/prophet_model-20260803144929.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:29 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:29 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vfl0loah.json

Build prophet model for  store_29_dept_83
Build prophet model for  store_29_dept_85

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9cdt1mvx.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=92175', 'data', 'file=/tmp/tmpjd45me00/vfl0loah.json', 'init=/tmp/tmpjd45me00/9cdt1mvx.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelor7rvxn7/prophet_model-20260803144929.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:29 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:30 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pjnudsgv.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/21i2gz_5.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=4626', 'data', 'file=/tmp/tmpjd45me00/pjnudsgv.json', 'init=/tmp/tmpjd45me00/21i2gz_5.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modell70e2ooz/prophet_model-20260803144930.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:30 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:30 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vtmurwoy.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vp6tj6k9.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=69519', 'data', 'file=/tmp/tmpjd45me00/vtmurwoy.json', 'init=/tmp/tmpjd45me00/vp6tj6k9.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelxe94vmbi/prophet_model-20260803144930.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:30 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_29_dept_87
Build prophet model for  store_29_dept_9

14:49:30 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/g6__ee1h.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fi2db9kw.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=79218', 'data', 'file=/tmp/tmpjd45me00/g6__ee1h.json', 'init=/tmp/tmpjd45me00/fi2db9kw.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model6vdy5s5u/prophet_model-20260803144930.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:30 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:30 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/e9shavvj.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/n9icbogk.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=90854', 'data', 'file=/tmp/tmpjd45me00/e9shavvj.json', 'init=/tmp/tmpjd45me00/n9icbogk.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model3jrsplci/prophet_model-20260803144930.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:30 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_29_dept_90
Build prophet model for  store_29_dept_91

14:49:30 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_y5szybq.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/lrg6a45j.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=79970', 'data', 'file=/tmp/tmpjd45me00/_y5szybq.json', 'init=/tmp/tmpjd45me00/lrg6a45j.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model0lfghk4e/prophet_model-20260803144930.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:30 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:31 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_29_dept_92
Build prophet model for  store_29_dept_93

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/yo91bkkp.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/nshbbwgo.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=81101', 'data', 'file=/tmp/tmpjd45me00/yo91bkkp.json', 'init=/tmp/tmpjd45me00/nshbbwgo.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelgvyei4zq/prophet_model-20260803144931.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:31 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:31 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/r4ixw78v.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/oxr7s3xc.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=76595', 'data', 'file=/tmp/tmpjd45me00/r4ixw78v.json', 'init=/tmp/tmpjd45me00/oxr7s3xc.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelzcj8n75m/prophet_model-20260803144931.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:31 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:31 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_29_dept_95
Build prophet model for  store_29_dept_97

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/leegkuft.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/h5miud99.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=21689', 'data', 'file=/tmp/tmpjd45me00/leegkuft.json', 'init=/tmp/tmpjd45me00/h5miud99.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model6g0ao8cj/prophet_model-20260803144931.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:31 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:31 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vsmgfzhx.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/n6p4f4r0.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=29103', 'data', 'file=/tmp/tmpjd45me00/vsmgfzhx.json', 'init=/tmp/tmpjd45me00/n6p4f4r0.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelfv5rfcbe/prophet_model-20260803144931.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:31 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:31 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_2_dept_1
Build prophet model for  store_2_dept_10

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/nbzjys_v.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ncjzzx7l.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=23847', 'data', 'file=/tmp/tmpjd45me00/nbzjys_v.json', 'init=/tmp/tmpjd45me00/ncjzzx7l.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_np9_ipl/prophet_model-20260803144931.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:31 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:31 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/n4kc2j_i.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/41bfx9rm.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=39691', 'data', 'file=/tmp/tmpjd45me00/n4kc2j_i.json', 'init=/tmp/tmpjd45me00/41bfx9rm.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelcm9rrl7r/prophet_model-20260803144932.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:32 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:32 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/c2cs3rm_.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hf1zozqn.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=87866', 'data', 'file=/tmp/tmpjd45me00/c2cs3rm_.json', 'init=/tmp/tmpjd45me00/hf1zozqn.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model9u58pb6n/prophet_model-20260803144932.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:32 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_2_dept_11
Build prophet model for  store_2_dept_12

14:49:32 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wlcq_ugx.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9a4bor8a.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=81532', 'data', 'file=/tmp/tmpjd45me00/wlcq_ugx.json', 'init=/tmp/tmpjd45me00/9a4bor8a.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelc91fzn0b/prophet_model-20260803144932.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:32 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:32 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_2_dept_13

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/37y2w4rk.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fm__pca6.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=96177', 'data', 'file=/tmp/tmpjd45me00/37y2w4rk.json', 'init=/tmp/tmpjd45me00/fm__pca6.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model50_fhsuz/prophet_model-20260803144932.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:32 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:32 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/yjr2q2hx.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jdz0cqg1.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=77203', 'data', 'file=/tmp/tmpjd45me00/yjr2q2hx.json', 'init=/tmp/tmpjd45me00/jdz0cqg1.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model1vvzx6ai/prophet_model-20260803144932.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:32 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_2_dept_14
Build prophet model for  store_2_dept_16

14:49:32 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vowcrf_v.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zcqt2maw.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=30918', 'data', 'file=/tmp/tmpjd45me00/vowcrf_v.json', 'init=/tmp/tmpjd45me00/zcqt2maw.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelfrp1atoa/prophet_model-20260803144932.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:32 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:32 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dxz6j43i.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/h3op1umt.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=88860', 'data', 'file=/tmp/tmpjd45me00/dxz6j43i.json', 'init=/tmp/tmpjd45me00/h3op1umt.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelagoob2i4/prophet_model-20260803144933.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:49:33 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_2_dept_17
Build prophet model for  store_2_dept_18

14:49:34 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/k21pv0fz.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/i0u8p5q_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=3587', 'data', 'file=/tmp/tmpjd45me00/k21pv0fz.json', 'init=/tmp/tmpjd45me00/i0u8p5q_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelbb43pimm/prophet_model-20260803144934.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:34 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:34 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_2_dept_19

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/iqylbk_f.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/t0gwt_ef.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=49664', 'data', 'file=/tmp/tmpjd45me00/iqylbk_f.json', 'init=/tmp/tmpjd45me00/t0gwt_ef.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model2parb9cu/prophet_model-20260803144934.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:34 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:34 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rru52efb.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1yomwrbw.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=62071', 'data', 'file=/tmp/tmpjd45me00/rru52efb.json', 'init=/tmp/tmpjd45me00/1yomwrbw.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeljs3pxvsr/prophet_model-20260803144935.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:35 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_2_dept_2
Build prophet model for  store_2_dept_20

14:49:35 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qezk8ejd.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bn056ncy.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=60279', 'data', 'file=/tmp/tmpjd45me00/qezk8ejd.json', 'init=/tmp/tmpjd45me00/bn056ncy.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelkd6ha4vu/prophet_model-20260803144935.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:35 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:35 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_2_dept_21

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/v3d5wcc2.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rn8q57vd.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=47703', 'data', 'file=/tmp/tmpjd45me00/v3d5wcc2.json', 'init=/tmp/tmpjd45me00/rn8q57vd.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelzdpdrxko/prophet_model-20260803144935.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:35 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:35 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_2_dept_22

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gc1l2j87.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gafm60km.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=12736', 'data', 'file=/tmp/tmpjd45me00/gc1l2j87.json', 'init=/tmp/tmpjd45me00/gafm60km.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelnfht4vob/prophet_model-20260803144935.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:35 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_2_dept_23

14:49:36 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/325ev_iv.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5njycydd.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=49778', 'data', 'file=/tmp/tmpjd45me00/325ev_iv.json', 'init=/tmp/tmpjd45me00/5njycydd.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model1ed2822c/prophet_model-20260803144936.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:36 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:36 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_2_dept_24

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hx83ywfm.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mbasyjao.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=79871', 'data', 'file=/tmp/tmpjd45me00/hx83ywfm.json', 'init=/tmp/tmpjd45me00/mbasyjao.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelq5k7lq_9/prophet_model-20260803144936.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:36 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:36 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_2_dept_25
Build prophet model for  store_2_dept_26

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7u6f54j9.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/lh0lpfu8.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=15547', 'data', 'file=/tmp/tmpjd45me00/7u6f54j9.json', 'init=/tmp/tmpjd45me00/lh0lpfu8.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelr7pzeena/prophet_model-20260803144937.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:37 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:37 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1mqbcd8q.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/yrwfs_2y.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=53568', 'data', 'file=/tmp/tmpjd45me00/1mqbcd8q.json', 'init=/tmp/tmpjd45me00/yrwfs_2y.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelu7v2xpx_/prophet_model-20260803144937.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:37 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:37 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_2_dept_27

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ubnhm3ue.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fsfmla04.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=10018', 'data', 'file=/tmp/tmpjd45me00/ubnhm3ue.json', 'init=/tmp/tmpjd45me00/fsfmla04.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelp9_v5l7s/prophet_model-20260803144937.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:37 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_2_dept_28

14:49:37 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/i9n3m080.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/eeti3udo.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=16096', 'data', 'file=/tmp/tmpjd45me00/i9n3m080.json', 'init=/tmp/tmpjd45me00/eeti3udo.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelubltzrba/prophet_model-20260803144937.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:37 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:37 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_2_dept_29

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/14nucj1m.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dn9acww9.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=97001', 'data', 'file=/tmp/tmpjd45me00/14nucj1m.json', 'init=/tmp/tmpjd45me00/dn9acww9.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelaox04q3r/prophet_model-20260803144938.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:38 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:38 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_2_dept_3
Build prophet model for  store_2_dept_30

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/acy19m1i.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/o7tknkr1.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=84361', 'data', 'file=/tmp/tmpjd45me00/acy19m1i.json', 'init=/tmp/tmpjd45me00/o7tknkr1.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelnud0n9rj/prophet_model-20260803144938.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:38 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:38 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3x5dxxbw.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/kjt5wo7n.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=20817', 'data', 'file=/tmp/tmpjd45me00/3x5dxxbw.json', 'init=/tmp/tmpjd45me00/kjt5wo7n.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model84w1cmkl/prophet_model-20260803144938.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:38 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:38 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_43h93gg.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hp9y6gr1.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=85600', 'data', 'file=/tmp/tmpjd45me00/_43h93gg.json', 'init=/tmp/tmpjd45me00/hp9y6gr1.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model4mk20_37/prophet_model-20260803144938.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:38 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:38 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_2_dept_31
Build prophet model for  store_2_dept_32

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/64fjyq9o.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/l9_o6ar0.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=73018', 'data', 'file=/tmp/tmpjd45me00/64fjyq9o.json', 'init=/tmp/tmpjd45me00/l9_o6ar0.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modellnc6kz1p/prophet_model-20260803144938.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:38 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:38 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gkpnjz_x.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1wz5subu.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=81921', 'data', 'file=/tmp/tmpjd45me00/gkpnjz_x.json', 'init=/tmp/tmpjd45me00/1wz5subu.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modela255jsr0/prophet_model-20260803144939.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:39 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_2_dept_33
Build prophet model for  store_2_dept_34

14:49:39 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5uodx01t.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8b6v_4as.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=32754', 'data', 'file=/tmp/tmpjd45me00/5uodx01t.json', 'init=/tmp/tmpjd45me00/8b6v_4as.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model24o8hs52/prophet_model-20260803144939.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:39 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:39 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_2_dept_35

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/g55_l46l.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/np15wjv1.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=79453', 'data', 'file=/tmp/tmpjd45me00/g55_l46l.json', 'init=/tmp/tmpjd45me00/np15wjv1.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelyngdnu37/prophet_model-20260803144939.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:39 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:39 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/n85rs6jh.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mgb33pso.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=82285', 'data', 'file=/tmp/tmpjd45me00/n85rs6jh.json', 'init=/tmp/tmpjd45me00/mgb33pso.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelobvuf09t/prophet_model-20260803144939.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:39 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_2_dept_36
Build prophet model for  store_2_dept_37

14:49:39 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/17ga1dn7.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xw2kx95_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=80680', 'data', 'file=/tmp/tmpjd45me00/17ga1dn7.json', 'init=/tmp/tmpjd45me00/xw2kx95_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeljvxqblho/prophet_model-20260803144939.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:39 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:39 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/a4jc3p66.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/a968etu4.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=91869', 'data', 'file=/tmp/tmpjd45me00/a4jc3p66.json', 'init=/tmp/tmpjd45me00/a968etu4.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelvrxhi8rh/prophet_model-20260803144939.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:39 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_2_dept_38
Build prophet model for  store_2_dept_4

14:49:39 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/uz0yzr5o.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/976v7zid.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=47615', 'data', 'file=/tmp/tmpjd45me00/uz0yzr5o.json', 'init=/tmp/tmpjd45me00/976v7zid.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelb3pkk3ne/prophet_model-20260803144940.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:40 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:40 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0aebblyf.json

Build prophet model for  store_2_dept_40
Build prophet model for  store_2_dept_41

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/na_jstdy.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=95923', 'data', 'file=/tmp/tmpjd45me00/0aebblyf.json', 'init=/tmp/tmpjd45me00/na_jstdy.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelkb_yz9rm/prophet_model-20260803144940.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:40 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:40 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/um_azpg4.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/sbfa7d8_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=40553', 'data', 'file=/tmp/tmpjd45me00/um_azpg4.json', 'init=/tmp/tmpjd45me00/sbfa7d8_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model160wfrm0/prophet_model-20260803144940.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:40 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:40 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/on3fa1hu.json

Build prophet model for  store_2_dept_42
Build prophet model for  store_2_dept_44

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3goij503.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=15623', 'data', 'file=/tmp/tmpjd45me00/on3fa1hu.json', 'init=/tmp/tmpjd45me00/3goij503.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model6e59xk5_/prophet_model-20260803144940.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:40 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:40 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/w41vza9n.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3ib4mt0l.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=85003', 'data', 'file=/tmp/tmpjd45me00/w41vza9n.json', 'init=/tmp/tmpjd45me00/3ib4mt0l.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelac94b3vb/prophet_model-20260803144940.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:49:40 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_2_dept_45

14:49:41 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ooy8sy5w.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/tmfeqeh0.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=93710', 'data', 'file=/tmp/tmpjd45me00/ooy8sy5w.json', 'init=/tmp/tmpjd45me00/tmfeqeh0.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelfey0i0kv/prophet_model-20260803144941.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:41 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:41 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/u1frk3ag.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/znzp2o3p.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=2612', 'data', 'file=/tmp/tmpjd45me00/u1frk3ag.json', 'init=/tmp/tmpjd45me00/znzp2o3p.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelzbhndh78/prophet_model-20260803144941.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:41 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_2_dept_46
Build prophet model for  store_2_dept_48

14:49:41 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/m6jcqvsg.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/utq49vs6.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=87665', 'data', 'file=/tmp/tmpjd45me00/m6jcqvsg.json', 'init=/tmp/tmpjd45me00/utq49vs6.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelh7shq1g7/prophet_model-20260803144941.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:41 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:41 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_2_dept_49
Build prophet model for  store_2_dept_5

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_lnbhuyg.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zeca45qq.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=28510', 'data', 'file=/tmp/tmpjd45me00/_lnbhuyg.json', 'init=/tmp/tmpjd45me00/zeca45qq.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelhfssbanx/prophet_model-20260803144942.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:42 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:42 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/nd8i947x.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0a7_zyrj.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=21293', 'data', 'file=/tmp/tmpjd45me00/nd8i947x.json', 'init=/tmp/tmpjd45me00/0a7_zyrj.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelzigkmg2b/prophet_model-20260803144942.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:42 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:42 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/w0dc7rhh.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/an4wa4se.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=29631', 'data', 'file=/tmp/tmpjd45me00/w0dc7rhh.json', 'init=/tmp/tmpjd45me00/an4wa4se.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model8acu2gnm/prophet_model-20260803144942.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:42 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_2_dept_52
Build prophet model for  store_2_dept_54

14:49:42 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gdh3k0zl.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/yrm9u7bh.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=7376', 'data', 'file=/tmp/tmpjd45me00/gdh3k0zl.json', 'init=/tmp/tmpjd45me00/yrm9u7bh.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelli8iyxep/prophet_model-20260803144942.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:42 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:42 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/clmzdh5g.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/sr77ac0i.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=71721', 'data', 'file=/tmp/tmpjd45me00/clmzdh5g.json', 'init=/tmp/tmpjd45me00/sr77ac0i.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelvs9u9vji/prophet_model-20260803144942.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:42 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_2_dept_55
Build prophet model for  store_2_dept_56

14:49:42 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6te8z46q.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/n1h515ng.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=67218', 'data', 'file=/tmp/tmpjd45me00/6te8z46q.json', 'init=/tmp/tmpjd45me00/n1h515ng.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelzhjp_dl9/prophet_model-20260803144943.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:43 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:43 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/j8v6cl5e.json

Build prophet model for  store_2_dept_58
Build prophet model for  store_2_dept_59

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/tsb71_yt.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=87415', 'data', 'file=/tmp/tmpjd45me00/j8v6cl5e.json', 'init=/tmp/tmpjd45me00/tsb71_yt.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modela0r5_84l/prophet_model-20260803144943.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:43 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:43 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ri2u2l7i.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/h5hbdrcq.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=1703', 'data', 'file=/tmp/tmpjd45me00/ri2u2l7i.json', 'init=/tmp/tmpjd45me00/h5hbdrcq.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelq_px94vr/prophet_model-20260803144943.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:43 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:43 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fk7f383y.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ecp0u19y.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=22073', 'data', 'file=/tmp/tmpjd45me00/fk7f383y.json', 'init=/tmp/tmpjd45me00/ecp0u19y.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelpihvwk2v/prophet_model-20260803144943.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:43 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_2_dept_6
Build prophet model for  store_2_dept_67

14:49:43 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8l1prg81.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3exjoxz0.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=16509', 'data', 'file=/tmp/tmpjd45me00/8l1prg81.json', 'init=/tmp/tmpjd45me00/3exjoxz0.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelm51vumlo/prophet_model-20260803144943.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:43 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:43 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jwv7x520.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/a32y60gf.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=39130', 'data', 'file=/tmp/tmpjd45me00/jwv7x520.json', 'init=/tmp/tmpjd45me00/a32y60gf.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeljcfu69es/prophet_model-20260803144943.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:43 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_2_dept_7
Build prophet model for  store_2_dept_71

14:49:44 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/w66aenyh.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/443t2ho3.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=3763', 'data', 'file=/tmp/tmpjd45me00/w66aenyh.json', 'init=/tmp/tmpjd45me00/443t2ho3.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model7i4_hb37/prophet_model-20260803144944.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:44 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:44 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/33nkvjip.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mxf_09z9.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=30138', 'data', 'file=/tmp/tmpjd45me00/33nkvjip.json', 'init=/tmp/tmpjd45me00/mxf_09z9.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelxfod45bc/prophet_model-20260803144944.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:44 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_2_dept_72
Build prophet model for  store_2_dept_74

14:49:44 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/d28t4ofy.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/goxh_0nq.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=65187', 'data', 'file=/tmp/tmpjd45me00/d28t4ofy.json', 'init=/tmp/tmpjd45me00/goxh_0nq.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelxwkamm1c/prophet_model-20260803144944.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:44 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:44 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bpof0i_i.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ozvkxi2u.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=65357', 'data', 'file=/tmp/tmpjd45me00/bpof0i_i.json', 'init=/tmp/tmpjd45me00/ozvkxi2u.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelaehub2m3/prophet_model-20260803144944.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:44 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_2_dept_79
Build prophet model for  store_2_dept_8

14:49:44 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/g7j5xhkw.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qzllgv1c.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=2864', 'data', 'file=/tmp/tmpjd45me00/g7j5xhkw.json', 'init=/tmp/tmpjd45me00/qzllgv1c.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model71vl80nj/prophet_model-20260803144944.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:44 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:44 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_2_dept_80
Build prophet model for  store_2_dept_81

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/g9xz8p28.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xcdr25gt.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=33376', 'data', 'file=/tmp/tmpjd45me00/g9xz8p28.json', 'init=/tmp/tmpjd45me00/xcdr25gt.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelsh9akbcs/prophet_model-20260803144945.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:45 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:45 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5obyuf15.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/elqwqgfb.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=41030', 'data', 'file=/tmp/tmpjd45me00/5obyuf15.json', 'init=/tmp/tmpjd45me00/elqwqgfb.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model9sjh8bxq/prophet_model-20260803144945.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:45 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:45 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zhtcir_k.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/t8rn11fg.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=89764', 'data', 'file=/tmp/tmpjd45me00/zhtcir_k.json', 'init=/tmp/tmpjd45me00/t8rn11fg.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelbo74lu02/prophet_model-20260803144945.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:45 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_2_dept_82
Build prophet model for  store_2_dept_83

14:49:45 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7s4fhddi.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/uwjccvj_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=74253', 'data', 'file=/tmp/tmpjd45me00/7s4fhddi.json', 'init=/tmp/tmpjd45me00/uwjccvj_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_xw7jwwo/prophet_model-20260803144945.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:45 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_2_dept_85

14:49:45 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0_lcex2r.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/nu3awzam.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=54125', 'data', 'file=/tmp/tmpjd45me00/0_lcex2r.json', 'init=/tmp/tmpjd45me00/nu3awzam.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelrmfnd4cw/prophet_model-20260803144945.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:45 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:46 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_2_dept_87
Build prophet model for  store_2_dept_9

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4v64bg19.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/thlgux0g.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=29203', 'data', 'file=/tmp/tmpjd45me00/4v64bg19.json', 'init=/tmp/tmpjd45me00/thlgux0g.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modely0gicmkg/prophet_model-20260803144946.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:46 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:46 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7vfeonoo.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/s80sz5me.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=1390', 'data', 'file=/tmp/tmpjd45me00/7vfeonoo.json', 'init=/tmp/tmpjd45me00/s80sz5me.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeldrkoqsu8/prophet_model-20260803144946.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:46 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:46 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_2_dept_90
Build prophet model for  store_2_dept_91

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_drou2bz.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hy3ucu8x.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=16589', 'data', 'file=/tmp/tmpjd45me00/_drou2bz.json', 'init=/tmp/tmpjd45me00/hy3ucu8x.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelgcslxgd_/prophet_model-20260803144946.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:46 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:46 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_2_dept_92
Build prophet model for  store_2_dept_93

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/b3w9ytrm.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ij9do7e6.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=41852', 'data', 'file=/tmp/tmpjd45me00/b3w9ytrm.json', 'init=/tmp/tmpjd45me00/ij9do7e6.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model1k699c4v/prophet_model-20260803144946.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:46 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:46 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_2_dept_94
Build prophet model for  store_2_dept_95

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ulxm_ekx.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/934dqj_m.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=67683', 'data', 'file=/tmp/tmpjd45me00/ulxm_ekx.json', 'init=/tmp/tmpjd45me00/934dqj_m.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeli6njucg1/prophet_model-20260803144947.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:47 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:47 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_2_dept_96
Build prophet model for  store_2_dept_97

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_c3gkb77.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xao3d5zq.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=88666', 'data', 'file=/tmp/tmpjd45me00/_c3gkb77.json', 'init=/tmp/tmpjd45me00/xao3d5zq.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelu1ofo4uu/prophet_model-20260803144947.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:47 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:47 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/csghb7zc.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/45tsh0fd.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=63644', 'data', 'file=/tmp/tmpjd45me00/csghb7zc.json', 'init=/tmp/tmpjd45me00/45tsh0fd.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modely5pjzgiv/prophet_model-20260803144947.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:47 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:47 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hp5oazx5.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2vrzj55p.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=74312', 'data', 'file=/tmp/tmpjd45me00/hp5oazx5.json', 'init=/tmp/tmpjd45me00/2vrzj55p.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeldu9h5qm6/prophet_model-20260803144947.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:47 - cmdstanpy - INFO - Chain [1] start processing

Build prophet model for  store_2_dept_98
Build prophet model for  store_30_dept_1

INFO:cmdstanpy:Chain [1] start processing
14:49:47 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/y4far_pi.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hkyns5fy.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=72959', 'data', 'file=/tmp/tmpjd45me00/y4far_pi.json', 'init=/tmp/tmpjd45me00/hkyns5fy.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeln1ci4k_r/prophet_model-20260803144947.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:47 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:47 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/14p05zr2.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jfli9wun.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=57099', 'data', 'file=/tmp/tmpjd45me00/14p05zr2.json', 'init=/tmp/tmpjd45me00/jfli9wun.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model7d8ep59y/prophet_model-20260803144947.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:47 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_30_dept_10
Build prophet model for  store_30_dept_11

14:49:47 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/t_za3qon.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xeeoulqi.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=32587', 'data', 'file=/tmp/tmpjd45me00/t_za3qon.json', 'init=/tmp/tmpjd45me00/xeeoulqi.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model7zsdyh44/prophet_model-20260803144948.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:48 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:48 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_30_dept_12
Build prophet model for  store_30_dept_13

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4nvx_cvy.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/g8r_mft1.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=41988', 'data', 'file=/tmp/tmpjd45me00/4nvx_cvy.json', 'init=/tmp/tmpjd45me00/g8r_mft1.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelbldzseel/prophet_model-20260803144948.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:48 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:48 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/e2rq3gv2.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2izsusez.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=91828', 'data', 'file=/tmp/tmpjd45me00/e2rq3gv2.json', 'init=/tmp/tmpjd45me00/2izsusez.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeljlwb3q9d/prophet_model-20260803144948.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:48 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:48 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_30_dept_14

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/w_c8153_.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/kdwmdw9p.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=30273', 'data', 'file=/tmp/tmpjd45me00/w_c8153_.json', 'init=/tmp/tmpjd45me00/kdwmdw9p.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelruaj2rf0/prophet_model-20260803144949.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:49 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_30_dept_16

14:49:49 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/njoyh40t.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/b5x4p2kj.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=59629', 'data', 'file=/tmp/tmpjd45me00/njoyh40t.json', 'init=/tmp/tmpjd45me00/b5x4p2kj.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelcqkp35o6/prophet_model-20260803144949.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:49 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_30_dept_17

14:49:49 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/b2bd9xhy.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/miiswt53.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=25942', 'data', 'file=/tmp/tmpjd45me00/b2bd9xhy.json', 'init=/tmp/tmpjd45me00/miiswt53.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model3e2a__uz/prophet_model-20260803144949.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:49:49 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_30_dept_18

14:49:51 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/j_7v9uws.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/w5lvmzdk.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=55332', 'data', 'file=/tmp/tmpjd45me00/j_7v9uws.json', 'init=/tmp/tmpjd45me00/w5lvmzdk.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelxodi0808/prophet_model-20260803144951.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:51 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_30_dept_2

14:49:51 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/a5_xhcg0.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/x2fzvwxq.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=96215', 'data', 'file=/tmp/tmpjd45me00/a5_xhcg0.json', 'init=/tmp/tmpjd45me00/x2fzvwxq.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelrgp3gupv/prophet_model-20260803144951.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:51 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_30_dept_21

14:49:51 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/117x1rf5.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/r6kns6rc.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=24878', 'data', 'file=/tmp/tmpjd45me00/117x1rf5.json', 'init=/tmp/tmpjd45me00/r6kns6rc.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modely7e1jm5v/prophet_model-20260803144951.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:51 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:51 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jw_n4m3j.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8rd0ziir.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=49271', 'data', 'file=/tmp/tmpjd45me00/jw_n4m3j.json', 'init=/tmp/tmpjd45me00/8rd0ziir.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model6sr60tp7/prophet_model-20260803144951.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:51 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_30_dept_25
Build prophet model for  store_30_dept_28

14:49:51 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/x91rodkf.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/t67n6sko.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=64165', 'data', 'file=/tmp/tmpjd45me00/x91rodkf.json', 'init=/tmp/tmpjd45me00/t67n6sko.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model5pahs_0w/prophet_model-20260803144952.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:52 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_30_dept_3

14:49:52 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/q554tp4g.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/osuz86y2.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=44397', 'data', 'file=/tmp/tmpjd45me00/q554tp4g.json', 'init=/tmp/tmpjd45me00/osuz86y2.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelh02ho3dt/prophet_model-20260803144952.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:52 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:52 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/sl4qmdan.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/sj_t00az.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=78378', 'data', 'file=/tmp/tmpjd45me00/sl4qmdan.json', 'init=/tmp/tmpjd45me00/sj_t00az.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model9xondhxk/prophet_model-20260803144952.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:52 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_30_dept_38
Build prophet model for  store_30_dept_4

14:49:52 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5ba_vkig.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/e2debttn.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=49522', 'data', 'file=/tmp/tmpjd45me00/5ba_vkig.json', 'init=/tmp/tmpjd45me00/e2debttn.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelob17uq4t/prophet_model-20260803144952.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:52 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:53 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/520xqz8o.json

Build prophet model for  store_30_dept_40
Build prophet model for  store_30_dept_42

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/w_mscg2_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=46597', 'data', 'file=/tmp/tmpjd45me00/520xqz8o.json', 'init=/tmp/tmpjd45me00/w_mscg2_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelz417qrbb/prophet_model-20260803144953.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:49:53 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:49:53 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 6.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zpdms4rl.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/q30cyppi.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=31402', 'data', 'file=/tmp/tmpjd45me00/zpdms4rl.json', 'init=/tmp/tmpjd45me00/q30cyppi.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model40dokycl/prophet_model-20260803144953.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:49:53 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_30_dept_44

14:50:03 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wta5b6ev.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zuqleyb2.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=36973', 'data', 'file=/tmp/tmpjd45me00/wta5b6ev.json', 'init=/tmp/tmpjd45me00/zuqleyb2.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model42j4iqr5/prophet_model-20260803145003.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:03 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_30_dept_46

14:50:04 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zth0dv7a.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1s1dhcyc.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=46218', 'data', 'file=/tmp/tmpjd45me00/zth0dv7a.json', 'init=/tmp/tmpjd45me00/1s1dhcyc.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelh_2l2jw2/prophet_model-20260803145004.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:04 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:04 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_30_dept_5
Build prophet model for  store_30_dept_52

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xm7wem5m.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/smdnssa_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=25819', 'data', 'file=/tmp/tmpjd45me00/xm7wem5m.json', 'init=/tmp/tmpjd45me00/smdnssa_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelkba52xsn/prophet_model-20260803145004.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:04 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:04 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2tjgwhz8.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/s0fubawf.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=99632', 'data', 'file=/tmp/tmpjd45me00/2tjgwhz8.json', 'init=/tmp/tmpjd45me00/s0fubawf.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelerhoavcx/prophet_model-20260803145004.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:04 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_30_dept_59

14:50:04 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/o8qzd3xy.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gkd_n4a3.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=57333', 'data', 'file=/tmp/tmpjd45me00/o8qzd3xy.json', 'init=/tmp/tmpjd45me00/gkd_n4a3.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model0xii5jxu/prophet_model-20260803145005.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:05 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:05 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/cm468coa.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/yi_bf5r4.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=72817', 'data', 'file=/tmp/tmpjd45me00/cm468coa.json', 'init=/tmp/tmpjd45me00/yi_bf5r4.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeljw1q9abo/prophet_model-20260803145005.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:05 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_30_dept_6
Build prophet model for  store_30_dept_60

14:50:05 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gvr_ugvw.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vvvjj0uz.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=8160', 'data', 'file=/tmp/tmpjd45me00/gvr_ugvw.json', 'init=/tmp/tmpjd45me00/vvvjj0uz.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelr5jq270q/prophet_model-20260803145005.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:05 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:05 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6xzu4k3p.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/y9_uq76v.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=56412', 'data', 'file=/tmp/tmpjd45me00/6xzu4k3p.json', 'init=/tmp/tmpjd45me00/y9_uq76v.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modela093rdt_/prophet_model-20260803145005.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:05 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_30_dept_67
Build prophet model for  store_30_dept_7

14:50:05 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/j_tcmn6f.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/x7sqtffe.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=63535', 'data', 'file=/tmp/tmpjd45me00/j_tcmn6f.json', 'init=/tmp/tmpjd45me00/x7sqtffe.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modellck5bk3g/prophet_model-20260803145005.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:05 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:05 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/misoqdlc.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4dei4s38.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=22834', 'data', 'file=/tmp/tmpjd45me00/misoqdlc.json', 'init=/tmp/tmpjd45me00/4dei4s38.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model2_edf9kt/prophet_model-20260803145005.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:05 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_30_dept_72
Build prophet model for  store_30_dept_74

14:50:06 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/v9qd4g_a.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/om3gsc65.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=89267', 'data', 'file=/tmp/tmpjd45me00/v9qd4g_a.json', 'init=/tmp/tmpjd45me00/om3gsc65.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model5bn_g84j/prophet_model-20260803145006.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:06 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:06 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2okjd_oa.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/uv6f_p3b.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=42575', 'data', 'file=/tmp/tmpjd45me00/2okjd_oa.json', 'init=/tmp/tmpjd45me00/uv6f_p3b.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelpks0dlm_/prophet_model-20260803145006.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:06 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_30_dept_79
Build prophet model for  store_30_dept_8

14:50:06 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/me_4wmol.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pbpd7tnb.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=16306', 'data', 'file=/tmp/tmpjd45me00/me_4wmol.json', 'init=/tmp/tmpjd45me00/pbpd7tnb.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model3hrk2ke4/prophet_model-20260803145006.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:06 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_30_dept_80

14:50:07 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fw2t4a_4.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7h1y6ru2.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=8119', 'data', 'file=/tmp/tmpjd45me00/fw2t4a_4.json', 'init=/tmp/tmpjd45me00/7h1y6ru2.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelnk7q65hi/prophet_model-20260803145007.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:07 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_30_dept_81

14:50:07 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7mi77ov_.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/yrmfydgs.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=81483', 'data', 'file=/tmp/tmpjd45me00/7mi77ov_.json', 'init=/tmp/tmpjd45me00/yrmfydgs.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelvtkau90g/prophet_model-20260803145007.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:07 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:07 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/sn1e2jw2.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_gamyyjg.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=47049', 'data', 'file=/tmp/tmpjd45me00/sn1e2jw2.json', 'init=/tmp/tmpjd45me00/_gamyyjg.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model6h8zt4d_/prophet_model-20260803145007.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:07 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_30_dept_82
Build prophet model for  store_30_dept_83

14:50:07 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/m8g7fdtx.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/74sd60bh.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=47043', 'data', 'file=/tmp/tmpjd45me00/m8g7fdtx.json', 'init=/tmp/tmpjd45me00/74sd60bh.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model2vpuva3k/prophet_model-20260803145007.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:07 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:07 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/54h1folq.json

Build prophet model for  store_30_dept_85
Build prophet model for  store_30_dept_87

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wnmmuhqe.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=31219', 'data', 'file=/tmp/tmpjd45me00/54h1folq.json', 'init=/tmp/tmpjd45me00/wnmmuhqe.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelp7qx419p/prophet_model-20260803145008.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:08 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:08 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rjdks79u.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vu49zh9m.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=73121', 'data', 'file=/tmp/tmpjd45me00/rjdks79u.json', 'init=/tmp/tmpjd45me00/vu49zh9m.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model7zulzhte/prophet_model-20260803145008.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:08 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:08 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_30_dept_9
Build prophet model for  store_30_dept_90

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/os57eweh.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wegh2dyq.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=56205', 'data', 'file=/tmp/tmpjd45me00/os57eweh.json', 'init=/tmp/tmpjd45me00/wegh2dyq.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelcn1li_2q/prophet_model-20260803145008.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:08 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:08 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/txmks1p4.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/m5cu5og_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=55819', 'data', 'file=/tmp/tmpjd45me00/txmks1p4.json', 'init=/tmp/tmpjd45me00/m5cu5og_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelmknjjzgp/prophet_model-20260803145008.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:08 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_30_dept_91

14:50:08 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/a67uxng2.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/f8fkxh2a.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=79152', 'data', 'file=/tmp/tmpjd45me00/a67uxng2.json', 'init=/tmp/tmpjd45me00/f8fkxh2a.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model5_jffvyv/prophet_model-20260803145009.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:09 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:09 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_30_dept_92
Build prophet model for  store_30_dept_93

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/v2nm3a0s.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/30r4t00h.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=27091', 'data', 'file=/tmp/tmpjd45me00/v2nm3a0s.json', 'init=/tmp/tmpjd45me00/30r4t00h.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model2y47yx45/prophet_model-20260803145009.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:09 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:09 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qv33i589.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xnnonm6l.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=46266', 'data', 'file=/tmp/tmpjd45me00/qv33i589.json', 'init=/tmp/tmpjd45me00/xnnonm6l.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelkj64960j/prophet_model-20260803145009.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:09 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:09 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_30_dept_94
Build prophet model for  store_30_dept_95

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/222zvuc3.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6q1ahq4v.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=20050', 'data', 'file=/tmp/tmpjd45me00/222zvuc3.json', 'init=/tmp/tmpjd45me00/6q1ahq4v.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeljcs047fx/prophet_model-20260803145009.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:09 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:09 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/faw5umy9.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/y82qeqae.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=53784', 'data', 'file=/tmp/tmpjd45me00/faw5umy9.json', 'init=/tmp/tmpjd45me00/y82qeqae.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelba_g_o9l/prophet_model-20260803145009.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:10 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:10 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_30_dept_96
Build prophet model for  store_30_dept_97

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/apich1gt.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4anr0eel.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=28941', 'data', 'file=/tmp/tmpjd45me00/apich1gt.json', 'init=/tmp/tmpjd45me00/4anr0eel.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model0xj193w1/prophet_model-20260803145010.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:10 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:10 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/nbdwp8lm.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/enxum0aa.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=72326', 'data', 'file=/tmp/tmpjd45me00/nbdwp8lm.json', 'init=/tmp/tmpjd45me00/enxum0aa.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modell7wiyx_v/prophet_model-20260803145010.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:10 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:10 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/of05lmu_.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/39psbd6k.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=51008', 'data', 'file=/tmp/tmpjd45me00/of05lmu_.json', 'init=/tmp/tmpjd45me00/39psbd6k.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeleevutrs8/prophet_model-20260803145010.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:10 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_30_dept_98
Build prophet model for  store_31_dept_1

14:50:10 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ysgqv_id.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wuso6jm0.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=99708', 'data', 'file=/tmp/tmpjd45me00/ysgqv_id.json', 'init=/tmp/tmpjd45me00/wuso6jm0.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model4k7y0fdp/prophet_model-20260803145010.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:10 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:11 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_31_dept_10

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bia24xqz.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/c6yayfht.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=2691', 'data', 'file=/tmp/tmpjd45me00/bia24xqz.json', 'init=/tmp/tmpjd45me00/c6yayfht.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model01fe4u_k/prophet_model-20260803145011.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:11 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:11 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0jeiafj2.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/j3d516lj.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=83469', 'data', 'file=/tmp/tmpjd45me00/0jeiafj2.json', 'init=/tmp/tmpjd45me00/j3d516lj.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelw19253bf/prophet_model-20260803145011.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:11 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_31_dept_11
Build prophet model for  store_31_dept_12

14:50:11 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/g133d5ik.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ojz5jxaa.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=10127', 'data', 'file=/tmp/tmpjd45me00/g133d5ik.json', 'init=/tmp/tmpjd45me00/ojz5jxaa.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelgxfy7ekk/prophet_model-20260803145011.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:11 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:11 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_31_dept_13

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/uxdd0jyx.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/h05suak6.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=64417', 'data', 'file=/tmp/tmpjd45me00/uxdd0jyx.json', 'init=/tmp/tmpjd45me00/h05suak6.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelblp7e7i9/prophet_model-20260803145011.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:11 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:11 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/g3bc5yh4.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/cs09wui9.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=999', 'data', 'file=/tmp/tmpjd45me00/g3bc5yh4.json', 'init=/tmp/tmpjd45me00/cs09wui9.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeltsdk439_/prophet_model-20260803145011.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:11 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:11 - cmdstanpy - INFO - Chain [1] done processing

Build prophet model for  store_31_dept_14
Build prophet model for  store_31_dept_16

INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/idsnpjv3.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xnoc4pbb.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=84661', 'data', 'file=/tmp/tmpjd45me00/idsnpjv3.json', 'init=/tmp/tmpjd45me00/xnoc4pbb.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelj29tfb3g/prophet_model-20260803145012.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:12 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:12 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2v__0shj.json

Build prophet model for  store_31_dept_17
Build prophet model for  store_31_dept_18

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ctj3dy5z.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=19209', 'data', 'file=/tmp/tmpjd45me00/2v__0shj.json', 'init=/tmp/tmpjd45me00/ctj3dy5z.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelcamorj37/prophet_model-20260803145012.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:12 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:12 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pw1oylno.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bve4w59q.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=54780', 'data', 'file=/tmp/tmpjd45me00/pw1oylno.json', 'init=/tmp/tmpjd45me00/bve4w59q.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelc420ov_5/prophet_model-20260803145012.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:12 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:12 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hrh0dao5.json

Build prophet model for  store_31_dept_19
Build prophet model for  store_31_dept_2

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/kmj07t1u.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=11830', 'data', 'file=/tmp/tmpjd45me00/hrh0dao5.json', 'init=/tmp/tmpjd45me00/kmj07t1u.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelc4a9w6by/prophet_model-20260803145012.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:12 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:12 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/uyc0bkg_.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vi28_r4f.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=64651', 'data', 'file=/tmp/tmpjd45me00/uyc0bkg_.json', 'init=/tmp/tmpjd45me00/vi28_r4f.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelao6gbpfn/prophet_model-20260803145012.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:12 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:12 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ogjbl0xj.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/46ldzqir.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=75882', 'data', 'file=/tmp/tmpjd45me00/ogjbl0xj.json', 'init=/tmp/tmpjd45me00/46ldzqir.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model30otfp0i/prophet_model-20260803145012.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:12 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_31_dept_20
Build prophet model for  store_31_dept_21

14:50:13 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fnf0digz.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ed2iqd28.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=99931', 'data', 'file=/tmp/tmpjd45me00/fnf0digz.json', 'init=/tmp/tmpjd45me00/ed2iqd28.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelb5wosoc2/prophet_model-20260803145013.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:13 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:13 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wix5c4s3.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rxt6tols.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=53544', 'data', 'file=/tmp/tmpjd45me00/wix5c4s3.json', 'init=/tmp/tmpjd45me00/rxt6tols.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model8ixve026/prophet_model-20260803145013.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:13 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_31_dept_22
Build prophet model for  store_31_dept_23

14:50:13 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5iifyrt0.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jfwkkibs.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=16730', 'data', 'file=/tmp/tmpjd45me00/5iifyrt0.json', 'init=/tmp/tmpjd45me00/jfwkkibs.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeltbu7aqwu/prophet_model-20260803145013.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:13 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:13 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_31_dept_24
Build prophet model for  store_31_dept_25

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7b3oi_gj.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1r9y0spz.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=8753', 'data', 'file=/tmp/tmpjd45me00/7b3oi_gj.json', 'init=/tmp/tmpjd45me00/1r9y0spz.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelmywerrhn/prophet_model-20260803145013.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:13 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:13 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8posmo09.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1ssb1c9w.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=29369', 'data', 'file=/tmp/tmpjd45me00/8posmo09.json', 'init=/tmp/tmpjd45me00/1ssb1c9w.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelpcnaw5fu/prophet_model-20260803145013.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:13 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:13 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/k8chx759.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/97l5u515.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=48217', 'data', 'file=/tmp/tmpjd45me00/k8chx759.json', 'init=/tmp/tmpjd45me00/97l5u515.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelfbkbecfv/prophet_model-20260803145013.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:13 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:13 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_31_dept_26
Build prophet model for  store_31_dept_27

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/81x7kntl.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bsfqhgex.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=90410', 'data', 'file=/tmp/tmpjd45me00/81x7kntl.json', 'init=/tmp/tmpjd45me00/bsfqhgex.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model5qhc4qz7/prophet_model-20260803145014.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:14 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:14 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_31_dept_28

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zk2y0l5z.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fgj_piu_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=31785', 'data', 'file=/tmp/tmpjd45me00/zk2y0l5z.json', 'init=/tmp/tmpjd45me00/fgj_piu_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelswjg9bnq/prophet_model-20260803145014.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:14 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:14 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_31_dept_29

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2fk9ms7b.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/x19r15h5.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=5994', 'data', 'file=/tmp/tmpjd45me00/2fk9ms7b.json', 'init=/tmp/tmpjd45me00/x19r15h5.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelyogrhyda/prophet_model-20260803145014.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:14 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:14 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_31_dept_3

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ppb38gq8.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5fhu73vr.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=67540', 'data', 'file=/tmp/tmpjd45me00/ppb38gq8.json', 'init=/tmp/tmpjd45me00/5fhu73vr.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeleayu5844/prophet_model-20260803145014.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:14 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:14 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_31_dept_30

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pw6bgn0x.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/w0zwc_b6.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=19708', 'data', 'file=/tmp/tmpjd45me00/pw6bgn0x.json', 'init=/tmp/tmpjd45me00/w0zwc_b6.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelt0ydk1kv/prophet_model-20260803145015.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:15 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:15 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_31_dept_31

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/k1tfjuxw.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ckfxnqh9.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=36084', 'data', 'file=/tmp/tmpjd45me00/k1tfjuxw.json', 'init=/tmp/tmpjd45me00/ckfxnqh9.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelcmeux6_j/prophet_model-20260803145015.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:15 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:15 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_31_dept_32

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/k2h3rt_3.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2s1417w0.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=75791', 'data', 'file=/tmp/tmpjd45me00/k2h3rt_3.json', 'init=/tmp/tmpjd45me00/2s1417w0.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelajrurw36/prophet_model-20260803145015.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:15 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:15 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_31_dept_33

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5m93arl7.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/a7qerk50.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=82939', 'data', 'file=/tmp/tmpjd45me00/5m93arl7.json', 'init=/tmp/tmpjd45me00/a7qerk50.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model87xynzoc/prophet_model-20260803145015.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:15 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_31_dept_34

14:50:15 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2tygpiso.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2eix94um.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=69726', 'data', 'file=/tmp/tmpjd45me00/2tygpiso.json', 'init=/tmp/tmpjd45me00/2eix94um.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelryed66np/prophet_model-20260803145016.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:16 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:16 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_31_dept_35

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/05waq1so.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/znpkzr5q.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=38845', 'data', 'file=/tmp/tmpjd45me00/05waq1so.json', 'init=/tmp/tmpjd45me00/znpkzr5q.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelmvg61ccz/prophet_model-20260803145016.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:16 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:16 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_31_dept_36

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/k4ij2g0j.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jgyxr8c0.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=25905', 'data', 'file=/tmp/tmpjd45me00/k4ij2g0j.json', 'init=/tmp/tmpjd45me00/jgyxr8c0.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model2l8115lj/prophet_model-20260803145016.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:16 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:16 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_31_dept_37

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_9oqr8tj.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ss1tqbuv.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=88732', 'data', 'file=/tmp/tmpjd45me00/_9oqr8tj.json', 'init=/tmp/tmpjd45me00/ss1tqbuv.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelj_mg0ntp/prophet_model-20260803145016.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:16 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:17 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_31_dept_38

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fxr33h4n.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2msxfuu_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=21771', 'data', 'file=/tmp/tmpjd45me00/fxr33h4n.json', 'init=/tmp/tmpjd45me00/2msxfuu_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelo6_gd1a8/prophet_model-20260803145017.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:17 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:17 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_31_dept_4
Build prophet model for  store_31_dept_40

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wi1c825i.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/k93fh8ph.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=18098', 'data', 'file=/tmp/tmpjd45me00/wi1c825i.json', 'init=/tmp/tmpjd45me00/k93fh8ph.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model89foe0z3/prophet_model-20260803145017.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:17 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:17 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/s6rrma3l.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/m1vfe55a.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=41244', 'data', 'file=/tmp/tmpjd45me00/s6rrma3l.json', 'init=/tmp/tmpjd45me00/m1vfe55a.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model4_4ojgf1/prophet_model-20260803145017.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:17 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:17 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jrlq_yuf.json

Build prophet model for  store_31_dept_41
Build prophet model for  store_31_dept_42

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ag0gj2j1.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=85609', 'data', 'file=/tmp/tmpjd45me00/jrlq_yuf.json', 'init=/tmp/tmpjd45me00/ag0gj2j1.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelxaqw6ilx/prophet_model-20260803145017.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:17 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:17 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4poslbv3.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ventre8v.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=2010', 'data', 'file=/tmp/tmpjd45me00/4poslbv3.json', 'init=/tmp/tmpjd45me00/ventre8v.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeluql4a6pu/prophet_model-20260803145017.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:17 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:18 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/f_x16b_b.json

Build prophet model for  store_31_dept_44
Build prophet model for  store_31_dept_46

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2i8i3liu.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=21954', 'data', 'file=/tmp/tmpjd45me00/f_x16b_b.json', 'init=/tmp/tmpjd45me00/2i8i3liu.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelgsvpzqgn/prophet_model-20260803145018.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:18 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:18 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6i3xjbci.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/m7e0ongp.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=62150', 'data', 'file=/tmp/tmpjd45me00/6i3xjbci.json', 'init=/tmp/tmpjd45me00/m7e0ongp.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelxiyru8nm/prophet_model-20260803145018.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:18 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:18 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/cfjf9v1b.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/kjuvu_6p.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=62959', 'data', 'file=/tmp/tmpjd45me00/cfjf9v1b.json', 'init=/tmp/tmpjd45me00/kjuvu_6p.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeleuj5_8na/prophet_model-20260803145018.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:18 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_31_dept_49
Build prophet model for  store_31_dept_5

14:50:18 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fx8qhqer.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/evm1vjpr.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=74777', 'data', 'file=/tmp/tmpjd45me00/fx8qhqer.json', 'init=/tmp/tmpjd45me00/evm1vjpr.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model3sn0bvwn/prophet_model-20260803145018.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:18 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:18 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_31_dept_51
Skip  store_31_dept_51 due to lack of data
Build prophet model for  store_31_dept_52
Build prophet model for  store_31_dept_54

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9d3lijtm.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/kdvelh7w.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=86723', 'data', 'file=/tmp/tmpjd45me00/9d3lijtm.json', 'init=/tmp/tmpjd45me00/kdvelh7w.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelykcvcrz4/prophet_model-20260803145018.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:18 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:18 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/b49u4dzp.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2t_123vg.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=93396', 'data', 'file=/tmp/tmpjd45me00/b49u4dzp.json', 'init=/tmp/tmpjd45me00/2t_123vg.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelewgbh6vr/prophet_model-20260803145018.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:18 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:18 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7u7g9arc.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bswe7ldi.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=87004', 'data', 'file=/tmp/tmpjd45me00/7u7g9arc.json', 'init=/tmp/tmpjd45me00/bswe7ldi.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelnfs34aku/prophet_model-20260803145019.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:19 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_31_dept_55
Build prophet model for  store_31_dept_56

14:50:19 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/801mfs7f.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mlvbggw2.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=56785', 'data', 'file=/tmp/tmpjd45me00/801mfs7f.json', 'init=/tmp/tmpjd45me00/mlvbggw2.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelrya625xh/prophet_model-20260803145019.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:19 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:19 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/k2ea7cja.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/tzl6nzqk.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=5181', 'data', 'file=/tmp/tmpjd45me00/k2ea7cja.json', 'init=/tmp/tmpjd45me00/tzl6nzqk.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelv19betht/prophet_model-20260803145019.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:19 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_31_dept_58
Build prophet model for  store_31_dept_59

14:50:19 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5wmrh1dr.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7mqy6i_2.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=7738', 'data', 'file=/tmp/tmpjd45me00/5wmrh1dr.json', 'init=/tmp/tmpjd45me00/7mqy6i_2.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelcrp9au5_/prophet_model-20260803145019.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:19 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:19 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vks12x7p.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/sdghmdhj.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=78420', 'data', 'file=/tmp/tmpjd45me00/vks12x7p.json', 'init=/tmp/tmpjd45me00/sdghmdhj.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelzanv2_3f/prophet_model-20260803145020.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:20 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_31_dept_6
Build prophet model for  store_31_dept_67

14:50:20 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mzvqlpum.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/x80mllif.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=31913', 'data', 'file=/tmp/tmpjd45me00/mzvqlpum.json', 'init=/tmp/tmpjd45me00/x80mllif.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelldlon9_e/prophet_model-20260803145020.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:20 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:20 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7t7asm96.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fxx05kmx.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=64442', 'data', 'file=/tmp/tmpjd45me00/7t7asm96.json', 'init=/tmp/tmpjd45me00/fxx05kmx.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model4uiz410j/prophet_model-20260803145020.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:20 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_31_dept_7
Build prophet model for  store_31_dept_71

14:50:20 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/q7pmq_g5.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jps6p071.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=44653', 'data', 'file=/tmp/tmpjd45me00/q7pmq_g5.json', 'init=/tmp/tmpjd45me00/jps6p071.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model5y8nuqe6/prophet_model-20260803145020.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:20 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:20 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5cksz1_6.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mtftlbou.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=10580', 'data', 'file=/tmp/tmpjd45me00/5cksz1_6.json', 'init=/tmp/tmpjd45me00/mtftlbou.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model2m5g9i3w/prophet_model-20260803145020.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:20 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_31_dept_72
Build prophet model for  store_31_dept_74

14:50:20 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_jr3ixu3.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8b4tah__.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=16094', 'data', 'file=/tmp/tmpjd45me00/_jr3ixu3.json', 'init=/tmp/tmpjd45me00/8b4tah__.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelm5mgfm37/prophet_model-20260803145020.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:20 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:20 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7m2p5pfy.json

Build prophet model for  store_31_dept_79
Build prophet model for  store_31_dept_8

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/eppqwx36.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=63704', 'data', 'file=/tmp/tmpjd45me00/7m2p5pfy.json', 'init=/tmp/tmpjd45me00/eppqwx36.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelj9bqo6j7/prophet_model-20260803145020.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:20 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:21 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/00eg9juv.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4hzhlxca.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=94665', 'data', 'file=/tmp/tmpjd45me00/00eg9juv.json', 'init=/tmp/tmpjd45me00/4hzhlxca.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model6lnpe3nc/prophet_model-20260803145021.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:21 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:21 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_31_dept_80
Build prophet model for  store_31_dept_81

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/myq4i5yl.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/eo8p4iti.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=92491', 'data', 'file=/tmp/tmpjd45me00/myq4i5yl.json', 'init=/tmp/tmpjd45me00/eo8p4iti.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeltd8gr2n6/prophet_model-20260803145021.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:21 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:21 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8oc26a4s.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/e_m95bu8.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=26077', 'data', 'file=/tmp/tmpjd45me00/8oc26a4s.json', 'init=/tmp/tmpjd45me00/e_m95bu8.json', 'output', 'file=/tmp/tmpjd45me00/prophet_models5risfji/prophet_model-20260803145021.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:21 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_31_dept_82

14:50:21 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vs1k9j65.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mawmmhi_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=74167', 'data', 'file=/tmp/tmpjd45me00/vs1k9j65.json', 'init=/tmp/tmpjd45me00/mawmmhi_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model67pr0fop/prophet_model-20260803145022.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:22 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:22 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_31_dept_83
Build prophet model for  store_31_dept_85

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wjl4navc.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/x_ps_cwu.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=10913', 'data', 'file=/tmp/tmpjd45me00/wjl4navc.json', 'init=/tmp/tmpjd45me00/x_ps_cwu.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelysc8qur_/prophet_model-20260803145022.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:22 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:22 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/sty76k7m.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ti5jph9s.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=43881', 'data', 'file=/tmp/tmpjd45me00/sty76k7m.json', 'init=/tmp/tmpjd45me00/ti5jph9s.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelw5tronp6/prophet_model-20260803145022.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:22 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:22 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_31_dept_87

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/kdqxyj7g.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/i7p6d8o1.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=60089', 'data', 'file=/tmp/tmpjd45me00/kdqxyj7g.json', 'init=/tmp/tmpjd45me00/i7p6d8o1.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modellw_kcfgy/prophet_model-20260803145022.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:22 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:22 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/__txodms.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wxw8zcco.json

Build prophet model for  store_31_dept_9
Build prophet model for  store_31_dept_90

DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=56063', 'data', 'file=/tmp/tmpjd45me00/__txodms.json', 'init=/tmp/tmpjd45me00/wxw8zcco.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelyc0xg9ot/prophet_model-20260803145022.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:22 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:22 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/b61k9t7x.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/t7_qegdl.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=44155', 'data', 'file=/tmp/tmpjd45me00/b61k9t7x.json', 'init=/tmp/tmpjd45me00/t7_qegdl.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_tcx6k_a/prophet_model-20260803145023.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:23 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:23 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_31_dept_91
Build prophet model for  store_31_dept_92

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/eq31133r.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jr5axj9w.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=43201', 'data', 'file=/tmp/tmpjd45me00/eq31133r.json', 'init=/tmp/tmpjd45me00/jr5axj9w.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelpp8t5tj3/prophet_model-20260803145023.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:23 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:23 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7e1dtd_x.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fjl71kzv.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=14155', 'data', 'file=/tmp/tmpjd45me00/7e1dtd_x.json', 'init=/tmp/tmpjd45me00/fjl71kzv.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelww4e6su9/prophet_model-20260803145023.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:23 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_31_dept_93
Build prophet model for  store_31_dept_94

14:50:23 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3kj2c7ch.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/clsujpov.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=8653', 'data', 'file=/tmp/tmpjd45me00/3kj2c7ch.json', 'init=/tmp/tmpjd45me00/clsujpov.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelz5isb90b/prophet_model-20260803145023.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:23 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_31_dept_95
Build prophet model for  store_31_dept_96

14:50:23 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7mr8xm0a.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/oc18_2j9.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=82878', 'data', 'file=/tmp/tmpjd45me00/7mr8xm0a.json', 'init=/tmp/tmpjd45me00/oc18_2j9.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model2vzfk6yl/prophet_model-20260803145024.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:24 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:24 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/i7ab5x6x.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hh4jm8nq.json

Build prophet model for  store_31_dept_97
Build prophet model for  store_31_dept_98

DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=377', 'data', 'file=/tmp/tmpjd45me00/i7ab5x6x.json', 'init=/tmp/tmpjd45me00/hh4jm8nq.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelq84bhsgn/prophet_model-20260803145024.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:24 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:24 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jo0zq6le.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/y3tqjlob.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=97544', 'data', 'file=/tmp/tmpjd45me00/jo0zq6le.json', 'init=/tmp/tmpjd45me00/y3tqjlob.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model61jqk3y_/prophet_model-20260803145024.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:24 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:24 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/470z8pbr.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/inewfzhq.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=16668', 'data', 'file=/tmp/tmpjd45me00/470z8pbr.json', 'init=/tmp/tmpjd45me00/inewfzhq.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeln38nvl4w/prophet_model-20260803145024.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:24 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_32_dept_1
Build prophet model for  store_32_dept_10

14:50:24 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gp7_ty39.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/e66hfmfs.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=16282', 'data', 'file=/tmp/tmpjd45me00/gp7_ty39.json', 'init=/tmp/tmpjd45me00/e66hfmfs.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelgdlpzgrn/prophet_model-20260803145024.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:24 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:24 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/21js60ik.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/as5f_erm.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=25058', 'data', 'file=/tmp/tmpjd45me00/21js60ik.json', 'init=/tmp/tmpjd45me00/as5f_erm.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model5k182tfl/prophet_model-20260803145024.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:24 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_32_dept_11
Build prophet model for  store_32_dept_12

14:50:24 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/b99r8xol.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rm150ogp.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=90022', 'data', 'file=/tmp/tmpjd45me00/b99r8xol.json', 'init=/tmp/tmpjd45me00/rm150ogp.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeldkzslzbi/prophet_model-20260803145025.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:25 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:25 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4y1uuehn.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9nx7ceqw.json
DEBUG:cmdstanpy:idx 0

Build prophet model for  store_32_dept_13
Build prophet model for  store_32_dept_14

DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=46710', 'data', 'file=/tmp/tmpjd45me00/4y1uuehn.json', 'init=/tmp/tmpjd45me00/9nx7ceqw.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelzvhcosq2/prophet_model-20260803145025.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:25 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:25 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/a97_bk93.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zxar9n7d.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=75171', 'data', 'file=/tmp/tmpjd45me00/a97_bk93.json', 'init=/tmp/tmpjd45me00/zxar9n7d.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelztrudj8p/prophet_model-20260803145025.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:25 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_32_dept_16

14:50:25 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/iojasjkt.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/smmn515o.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=27128', 'data', 'file=/tmp/tmpjd45me00/iojasjkt.json', 'init=/tmp/tmpjd45me00/smmn515o.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeldpy5ell6/prophet_model-20260803145025.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:25 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:25 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wemcuigy.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/b8gp_iox.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=60156', 'data', 'file=/tmp/tmpjd45me00/wemcuigy.json', 'init=/tmp/tmpjd45me00/b8gp_iox.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeluengfnpc/prophet_model-20260803145025.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:25 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:25 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_32_dept_17
Build prophet model for  store_32_dept_18

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bpjyb_ah.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qm4gt8s7.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=94173', 'data', 'file=/tmp/tmpjd45me00/bpjyb_ah.json', 'init=/tmp/tmpjd45me00/qm4gt8s7.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model6pfld5ed/prophet_model-20260803145025.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:25 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:26 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_32_dept_19

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_cxp3wjs.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/seust_n4.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=91584', 'data', 'file=/tmp/tmpjd45me00/_cxp3wjs.json', 'init=/tmp/tmpjd45me00/seust_n4.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model9pskiz5s/prophet_model-20260803145026.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:26 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:26 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rszib5f8.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/kdp7yf13.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None

Build prophet model for  store_32_dept_2
Build prophet model for  store_32_dept_20

DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=44489', 'data', 'file=/tmp/tmpjd45me00/rszib5f8.json', 'init=/tmp/tmpjd45me00/kdp7yf13.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model3t0osgx8/prophet_model-20260803145026.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:26 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:26 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/p9a0ib5w.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/szsrdgxl.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=53343', 'data', 'file=/tmp/tmpjd45me00/p9a0ib5w.json', 'init=/tmp/tmpjd45me00/szsrdgxl.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model7m3ht_kl/prophet_model-20260803145026.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:26 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_32_dept_21

14:50:26 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hia700qt.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/z5tyunil.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=59306', 'data', 'file=/tmp/tmpjd45me00/hia700qt.json', 'init=/tmp/tmpjd45me00/z5tyunil.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model5z8q16rm/prophet_model-20260803145026.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:26 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:26 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wmsp60ra.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/u070qzy5.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=63113', 'data', 'file=/tmp/tmpjd45me00/wmsp60ra.json', 'init=/tmp/tmpjd45me00/u070qzy5.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelh9izdzu6/prophet_model-20260803145027.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:27 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_32_dept_22
Build prophet model for  store_32_dept_23

14:50:27 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/01zu_j1m.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/62rvfi1a.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=31612', 'data', 'file=/tmp/tmpjd45me00/01zu_j1m.json', 'init=/tmp/tmpjd45me00/62rvfi1a.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model3rwg_9ds/prophet_model-20260803145027.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:27 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:27 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_32_dept_24

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4jz7osi2.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/d5s9j_un.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=96552', 'data', 'file=/tmp/tmpjd45me00/4jz7osi2.json', 'init=/tmp/tmpjd45me00/d5s9j_un.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelfhj6zhnd/prophet_model-20260803145027.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:27 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:27 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_32_dept_25

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/oig3ipwg.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/56r454gn.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=23336', 'data', 'file=/tmp/tmpjd45me00/oig3ipwg.json', 'init=/tmp/tmpjd45me00/56r454gn.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelb2groe3p/prophet_model-20260803145027.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:27 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:27 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_32_dept_26

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bl9i4o09.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/t2vc29rv.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=54529', 'data', 'file=/tmp/tmpjd45me00/bl9i4o09.json', 'init=/tmp/tmpjd45me00/t2vc29rv.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelgm9yjjee/prophet_model-20260803145028.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:28 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:28 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_32_dept_27

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/azv09rc9.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/p0hkbu70.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=84643', 'data', 'file=/tmp/tmpjd45me00/azv09rc9.json', 'init=/tmp/tmpjd45me00/p0hkbu70.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelp84dger3/prophet_model-20260803145028.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:28 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:28 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_32_dept_28

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/spne_m5m.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/voxythn4.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=13707', 'data', 'file=/tmp/tmpjd45me00/spne_m5m.json', 'init=/tmp/tmpjd45me00/voxythn4.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelsmevb56w/prophet_model-20260803145028.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:28 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:28 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_32_dept_29

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/43emp490.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/p53n8_9c.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=91972', 'data', 'file=/tmp/tmpjd45me00/43emp490.json', 'init=/tmp/tmpjd45me00/p53n8_9c.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelyxo0i_rw/prophet_model-20260803145028.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:28 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:28 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_32_dept_3

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/d8jc_6n7.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/u6dczbmj.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=65248', 'data', 'file=/tmp/tmpjd45me00/d8jc_6n7.json', 'init=/tmp/tmpjd45me00/u6dczbmj.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelnzes0t1x/prophet_model-20260803145028.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:28 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:28 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_32_dept_30
Build prophet model for  store_32_dept_31

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ho5b_t5o.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/p038ncqa.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=33990', 'data', 'file=/tmp/tmpjd45me00/ho5b_t5o.json', 'init=/tmp/tmpjd45me00/p038ncqa.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_m7u6tb6/prophet_model-20260803145029.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:29 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:29 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bxo60j4s.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ib764aj4.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=20144', 'data', 'file=/tmp/tmpjd45me00/bxo60j4s.json', 'init=/tmp/tmpjd45me00/ib764aj4.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelb5_vrxco/prophet_model-20260803145029.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:29 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:29 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_32_dept_32

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/l7rkmgau.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hhr_9tep.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=4975', 'data', 'file=/tmp/tmpjd45me00/l7rkmgau.json', 'init=/tmp/tmpjd45me00/hhr_9tep.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model4uwiplac/prophet_model-20260803145029.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:29 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:29 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_32_dept_33
Build prophet model for  store_32_dept_34

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/kvlptv2v.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/m40314vr.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=96702', 'data', 'file=/tmp/tmpjd45me00/kvlptv2v.json', 'init=/tmp/tmpjd45me00/m40314vr.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeln0drbmhf/prophet_model-20260803145029.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:29 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:30 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9cg4_3yc.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2mqyoo4d.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=83918', 'data', 'file=/tmp/tmpjd45me00/9cg4_3yc.json', 'init=/tmp/tmpjd45me00/2mqyoo4d.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_rk0dc1r/prophet_model-20260803145030.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:30 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:30 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_kji9czz.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2lp_ri8b.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=24041', 'data', 'file=/tmp/tmpjd45me00/_kji9czz.json', 'init=/tmp/tmpjd45me00/2lp_ri8b.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model61ikncvh/prophet_model-20260803145030.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:30 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_32_dept_35
Build prophet model for  store_32_dept_36

14:50:30 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rt9q_5d7.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/tnt7xyis.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=13246', 'data', 'file=/tmp/tmpjd45me00/rt9q_5d7.json', 'init=/tmp/tmpjd45me00/tnt7xyis.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_52xsntq/prophet_model-20260803145030.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:30 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_32_dept_37

14:50:31 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9wbkcfju.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ymdh81t_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=61324', 'data', 'file=/tmp/tmpjd45me00/9wbkcfju.json', 'init=/tmp/tmpjd45me00/ymdh81t_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelcu8zf2q6/prophet_model-20260803145031.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:31 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:31 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/nc4r1d2d.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/m94wm2rr.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=5396', 'data', 'file=/tmp/tmpjd45me00/nc4r1d2d.json', 'init=/tmp/tmpjd45me00/m94wm2rr.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modellmz1vdh3/prophet_model-20260803145031.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:31 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:31 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_32_dept_38
Build prophet model for  store_32_dept_4

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/sa3mvv2e.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bsnp6qcw.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=41066', 'data', 'file=/tmp/tmpjd45me00/sa3mvv2e.json', 'init=/tmp/tmpjd45me00/bsnp6qcw.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model1hbdzhnt/prophet_model-20260803145031.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:31 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_32_dept_40

14:50:31 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bl9m_78q.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/b5da5zcm.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=78299', 'data', 'file=/tmp/tmpjd45me00/bl9m_78q.json', 'init=/tmp/tmpjd45me00/b5da5zcm.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelcwscgpps/prophet_model-20260803145031.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:31 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:32 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_32_dept_41
Build prophet model for  store_32_dept_42

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0rck_vaw.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/eh0557ce.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=61374', 'data', 'file=/tmp/tmpjd45me00/0rck_vaw.json', 'init=/tmp/tmpjd45me00/eh0557ce.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeluly41unc/prophet_model-20260803145032.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:32 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:32 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/tmoioe_v.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xw_38aty.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=84974', 'data', 'file=/tmp/tmpjd45me00/tmoioe_v.json', 'init=/tmp/tmpjd45me00/xw_38aty.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelxvol4piy/prophet_model-20260803145032.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:32 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:32 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/p8fv1wn_.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jn2rbzvq.json

Build prophet model for  store_32_dept_44
Build prophet model for  store_32_dept_46

DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=78221', 'data', 'file=/tmp/tmpjd45me00/p8fv1wn_.json', 'init=/tmp/tmpjd45me00/jn2rbzvq.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelx2kopobp/prophet_model-20260803145032.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:32 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:32 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/66sde9x9.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/kbyoz9ke.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=70652', 'data', 'file=/tmp/tmpjd45me00/66sde9x9.json', 'init=/tmp/tmpjd45me00/kbyoz9ke.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model9l02_w65/prophet_model-20260803145032.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:32 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:32 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2fhdrsro.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9r9y6gvr.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=93524', 'data', 'file=/tmp/tmpjd45me00/2fhdrsro.json', 'init=/tmp/tmpjd45me00/9r9y6gvr.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelhjt49gmh/prophet_model-20260803145032.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:32 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_32_dept_49
Build prophet model for  store_32_dept_5

14:50:33 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6ssajt6y.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/y4m0svol.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=19102', 'data', 'file=/tmp/tmpjd45me00/6ssajt6y.json', 'init=/tmp/tmpjd45me00/y4m0svol.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelb1d96pod/prophet_model-20260803145033.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:33 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:33 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_32_dept_51
Skip  store_32_dept_51 due to lack of data
Build prophet model for  store_32_dept_52
Build prophet model for  store_32_dept_54

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ae5n4nvy.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4rlp7csk.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=73386', 'data', 'file=/tmp/tmpjd45me00/ae5n4nvy.json', 'init=/tmp/tmpjd45me00/4rlp7csk.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeluw0zfvq7/prophet_model-20260803145033.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:33 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:33 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ooshymiz.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/biqlgy5_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=79689', 'data', 'file=/tmp/tmpjd45me00/ooshymiz.json', 'init=/tmp/tmpjd45me00/biqlgy5_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelxbi1kivz/prophet_model-20260803145033.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:33 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:33 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/08765l5n.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3gd086ci.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=15312', 'data', 'file=/tmp/tmpjd45me00/08765l5n.json', 'init=/tmp/tmpjd45me00/3gd086ci.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelcwxy4tim/prophet_model-20260803145033.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:33 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_32_dept_55
Build prophet model for  store_32_dept_56

14:50:33 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2ko9i_l4.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/aa83rhw7.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=33643', 'data', 'file=/tmp/tmpjd45me00/2ko9i_l4.json', 'init=/tmp/tmpjd45me00/aa83rhw7.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model1p4fdifi/prophet_model-20260803145033.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:33 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:33 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_32_dept_58
Build prophet model for  store_32_dept_59

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8or_tsex.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dsksxrxy.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=90980', 'data', 'file=/tmp/tmpjd45me00/8or_tsex.json', 'init=/tmp/tmpjd45me00/dsksxrxy.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model3u4xuv_8/prophet_model-20260803145034.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:34 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:34 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/usrhfjbh.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/185z7l5g.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=93771', 'data', 'file=/tmp/tmpjd45me00/usrhfjbh.json', 'init=/tmp/tmpjd45me00/185z7l5g.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelgs9evhwt/prophet_model-20260803145034.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:34 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:34 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/yqxjiy23.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xxjb2c05.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=96863', 'data', 'file=/tmp/tmpjd45me00/yqxjiy23.json', 'init=/tmp/tmpjd45me00/xxjb2c05.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelj9nwmo1j/prophet_model-20260803145034.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:34 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_32_dept_6
Build prophet model for  store_32_dept_60

14:50:34 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fnjhzxkz.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_m0g4jy_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=33662', 'data', 'file=/tmp/tmpjd45me00/fnjhzxkz.json', 'init=/tmp/tmpjd45me00/_m0g4jy_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelqop1t9tn/prophet_model-20260803145034.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:34 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:34 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_u8nrwmg.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/crxx6wxw.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=5621', 'data', 'file=/tmp/tmpjd45me00/_u8nrwmg.json', 'init=/tmp/tmpjd45me00/crxx6wxw.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelst295sjp/prophet_model-20260803145034.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:34 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_32_dept_67
Build prophet model for  store_32_dept_7

14:50:34 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4w1unstr.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vbibi889.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=3619', 'data', 'file=/tmp/tmpjd45me00/4w1unstr.json', 'init=/tmp/tmpjd45me00/vbibi889.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model5kslye60/prophet_model-20260803145034.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:34 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:34 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ixwqns60.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/p__mi6wc.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=53422', 'data', 'file=/tmp/tmpjd45me00/ixwqns60.json', 'init=/tmp/tmpjd45me00/p__mi6wc.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelj3j8m7z4/prophet_model-20260803145035.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:35 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:35 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_32_dept_71
Build prophet model for  store_32_dept_72

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ykrlu7m0.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hkx33_ne.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=1152', 'data', 'file=/tmp/tmpjd45me00/ykrlu7m0.json', 'init=/tmp/tmpjd45me00/hkx33_ne.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelia663s0n/prophet_model-20260803145035.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:35 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_32_dept_74

14:50:35 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/evtv5mrc.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/kwhe67na.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=44188', 'data', 'file=/tmp/tmpjd45me00/evtv5mrc.json', 'init=/tmp/tmpjd45me00/kwhe67na.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelm6yvvzpz/prophet_model-20260803145035.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:35 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:35 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/j0fwx3v7.json

Build prophet model for  store_32_dept_79
Build prophet model for  store_32_dept_8

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5_b3y6vy.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=78809', 'data', 'file=/tmp/tmpjd45me00/j0fwx3v7.json', 'init=/tmp/tmpjd45me00/5_b3y6vy.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelzoviyklc/prophet_model-20260803145035.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:35 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:35 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/33rjmpil.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4lhxsv69.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=99005', 'data', 'file=/tmp/tmpjd45me00/33rjmpil.json', 'init=/tmp/tmpjd45me00/4lhxsv69.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelwqeezacm/prophet_model-20260803145035.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:35 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:35 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_32_dept_80

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/kw5md7by.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9sk59i3x.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=20877', 'data', 'file=/tmp/tmpjd45me00/kw5md7by.json', 'init=/tmp/tmpjd45me00/9sk59i3x.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model8k6jrehx/prophet_model-20260803145036.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:36 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:36 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_32_dept_81

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3hmitbmj.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1rw54tln.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=1482', 'data', 'file=/tmp/tmpjd45me00/3hmitbmj.json', 'init=/tmp/tmpjd45me00/1rw54tln.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelrqex5u9_/prophet_model-20260803145036.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:36 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:36 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/utfosrwm.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vxoglzs1.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=92487', 'data', 'file=/tmp/tmpjd45me00/utfosrwm.json', 'init=/tmp/tmpjd45me00/vxoglzs1.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model3clzvj53/prophet_model-20260803145036.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:36 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_32_dept_82
Build prophet model for  store_32_dept_83

14:50:36 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/iyir667g.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/h22r_hp7.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=98060', 'data', 'file=/tmp/tmpjd45me00/iyir667g.json', 'init=/tmp/tmpjd45me00/h22r_hp7.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelexsr4n50/prophet_model-20260803145036.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:36 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:36 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qvxavgau.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/uejebmqk.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=5422', 'data', 'file=/tmp/tmpjd45me00/qvxavgau.json', 'init=/tmp/tmpjd45me00/uejebmqk.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model6qq301fa/prophet_model-20260803145036.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:36 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_32_dept_85
Build prophet model for  store_32_dept_87

14:50:36 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ptsruhhi.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xjfqavto.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=95288', 'data', 'file=/tmp/tmpjd45me00/ptsruhhi.json', 'init=/tmp/tmpjd45me00/xjfqavto.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model1oddh1wd/prophet_model-20260803145037.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:37 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:37 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_32_dept_9

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/q1rnbzhw.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7tsn4jys.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=23332', 'data', 'file=/tmp/tmpjd45me00/q1rnbzhw.json', 'init=/tmp/tmpjd45me00/7tsn4jys.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelkqubpjre/prophet_model-20260803145037.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:37 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:37 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/nbryv8bp.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/35l5crmv.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=21326', 'data', 'file=/tmp/tmpjd45me00/nbryv8bp.json', 'init=/tmp/tmpjd45me00/35l5crmv.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model1aa9gh4_/prophet_model-20260803145037.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:37 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_32_dept_90
Build prophet model for  store_32_dept_91

14:50:37 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8dh99gal.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rl88ia4j.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=2908', 'data', 'file=/tmp/tmpjd45me00/8dh99gal.json', 'init=/tmp/tmpjd45me00/rl88ia4j.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelqo_u2fix/prophet_model-20260803145037.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:37 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:37 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_32_dept_92
Build prophet model for  store_32_dept_93

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9dlkpy_e.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gqqeil9j.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=19347', 'data', 'file=/tmp/tmpjd45me00/9dlkpy_e.json', 'init=/tmp/tmpjd45me00/gqqeil9j.json', 'output', 'file=/tmp/tmpjd45me00/prophet_models9sfte6m/prophet_model-20260803145037.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:37 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:37 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/y39bo44z.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0c10mvhd.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=88095', 'data', 'file=/tmp/tmpjd45me00/y39bo44z.json', 'init=/tmp/tmpjd45me00/0c10mvhd.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model2z8lp5xr/prophet_model-20260803145038.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:38 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:38 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_32_dept_94
Build prophet model for  store_32_dept_95

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/kwjjmt_o.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vhsc9uu_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=65804', 'data', 'file=/tmp/tmpjd45me00/kwjjmt_o.json', 'init=/tmp/tmpjd45me00/vhsc9uu_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelbp3wudjw/prophet_model-20260803145038.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:38 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:38 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9r_34gxz.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jca9x_a3.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=97274', 'data', 'file=/tmp/tmpjd45me00/9r_34gxz.json', 'init=/tmp/tmpjd45me00/jca9x_a3.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model3pxlprqv/prophet_model-20260803145038.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:38 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:38 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0_0f4pcb.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/o_dhej_f.json
DEBUG:cmdstanpy:idx 0

Build prophet model for  store_32_dept_96
Build prophet model for  store_32_dept_97

DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=54761', 'data', 'file=/tmp/tmpjd45me00/0_0f4pcb.json', 'init=/tmp/tmpjd45me00/o_dhej_f.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model4qdiorcl/prophet_model-20260803145038.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:38 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:38 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bhm02_3f.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gidrop9s.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=91596', 'data', 'file=/tmp/tmpjd45me00/bhm02_3f.json', 'init=/tmp/tmpjd45me00/gidrop9s.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelv71s5kky/prophet_model-20260803145038.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:38 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:38 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/knzn2ntk.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/67vditx9.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=7475', 'data', 'file=/tmp/tmpjd45me00/knzn2ntk.json', 'init=/tmp/tmpjd45me00/67vditx9.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelwqpela2z/prophet_model-20260803145038.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:38 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_32_dept_98
Build prophet model for  store_33_dept_1

14:50:38 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_8dcys1t.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zp9ezizp.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=44780', 'data', 'file=/tmp/tmpjd45me00/_8dcys1t.json', 'init=/tmp/tmpjd45me00/zp9ezizp.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelz4z5rm28/prophet_model-20260803145039.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:39 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:39 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/tiojofqt.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7a5kyef0.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None

Build prophet model for  store_33_dept_10
Build prophet model for  store_33_dept_11

DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=97116', 'data', 'file=/tmp/tmpjd45me00/tiojofqt.json', 'init=/tmp/tmpjd45me00/7a5kyef0.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelun7zmq3r/prophet_model-20260803145039.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:39 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:39 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/c4gws2_4.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/roh1rahf.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=75383', 'data', 'file=/tmp/tmpjd45me00/c4gws2_4.json', 'init=/tmp/tmpjd45me00/roh1rahf.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelworjfrxp/prophet_model-20260803145039.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:39 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:39 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_33_dept_13
Build prophet model for  store_33_dept_14

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/h3aa25tr.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/402azujj.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=36856', 'data', 'file=/tmp/tmpjd45me00/h3aa25tr.json', 'init=/tmp/tmpjd45me00/402azujj.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelxclj78bn/prophet_model-20260803145039.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:39 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:39 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/svmoxcm7.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dkwti6nc.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=24288', 'data', 'file=/tmp/tmpjd45me00/svmoxcm7.json', 'init=/tmp/tmpjd45me00/dkwti6nc.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model1nqfnqtj/prophet_model-20260803145039.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:40 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:40 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_33_dept_16
Build prophet model for  store_33_dept_17

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8uvja0hf.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9lk2ft03.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=16073', 'data', 'file=/tmp/tmpjd45me00/8uvja0hf.json', 'init=/tmp/tmpjd45me00/9lk2ft03.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeltp19y_hj/prophet_model-20260803145040.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:40 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:40 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8ph3ly8w.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5v46afjm.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=42198', 'data', 'file=/tmp/tmpjd45me00/8ph3ly8w.json', 'init=/tmp/tmpjd45me00/5v46afjm.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelo75b6vc1/prophet_model-20260803145040.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:40 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_33_dept_2

14:50:40 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bu4jgwza.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/tu071h_q.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=97069', 'data', 'file=/tmp/tmpjd45me00/bu4jgwza.json', 'init=/tmp/tmpjd45me00/tu071h_q.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelvm066jod/prophet_model-20260803145040.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:40 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_33_dept_21

14:50:40 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/g17rsyd6.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dme86ac9.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=55159', 'data', 'file=/tmp/tmpjd45me00/g17rsyd6.json', 'init=/tmp/tmpjd45me00/dme86ac9.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeloc1eqd8d/prophet_model-20260803145041.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:41 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_33_dept_26

14:50:41 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/cg_jejik.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/98fcjl39.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=15885', 'data', 'file=/tmp/tmpjd45me00/cg_jejik.json', 'init=/tmp/tmpjd45me00/98fcjl39.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model8y3nh21v/prophet_model-20260803145041.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:41 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:41 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_33_dept_3

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/z5fno56k.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/geblilsz.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=37747', 'data', 'file=/tmp/tmpjd45me00/z5fno56k.json', 'init=/tmp/tmpjd45me00/geblilsz.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model2_fub9z1/prophet_model-20260803145042.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:42 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:42 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_33_dept_38

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/q3gsf973.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fmh7ukvb.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=91627', 'data', 'file=/tmp/tmpjd45me00/q3gsf973.json', 'init=/tmp/tmpjd45me00/fmh7ukvb.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model4h_545v9/prophet_model-20260803145042.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:42 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_33_dept_4

14:50:42 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8qtt741k.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bhle0lto.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=25837', 'data', 'file=/tmp/tmpjd45me00/8qtt741k.json', 'init=/tmp/tmpjd45me00/bhle0lto.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model3f2k057v/prophet_model-20260803145042.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:42 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:43 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_33_dept_40

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/y2ttt3wa.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/yblb41bt.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=52572', 'data', 'file=/tmp/tmpjd45me00/y2ttt3wa.json', 'init=/tmp/tmpjd45me00/yblb41bt.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelsgfhvw5e/prophet_model-20260803145043.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:43 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:43 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/yh_lttmz.json

Build prophet model for  store_33_dept_46
Build prophet model for  store_33_dept_5

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qsox8740.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=14332', 'data', 'file=/tmp/tmpjd45me00/yh_lttmz.json', 'init=/tmp/tmpjd45me00/qsox8740.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model8e5efykg/prophet_model-20260803145043.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:43 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:43 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zyj32qk4.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/arhbxrms.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=19155', 'data', 'file=/tmp/tmpjd45me00/zyj32qk4.json', 'init=/tmp/tmpjd45me00/arhbxrms.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelrrjpkvy6/prophet_model-20260803145043.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:43 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:43 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/okaxu7ac.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/h6f1yife.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=33571', 'data', 'file=/tmp/tmpjd45me00/okaxu7ac.json', 'init=/tmp/tmpjd45me00/h6f1yife.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelcas0ql6k/prophet_model-20260803145043.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:43 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_33_dept_60
Build prophet model for  store_33_dept_67

14:50:43 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/yu5f77b8.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/axl248qj.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=78358', 'data', 'file=/tmp/tmpjd45me00/yu5f77b8.json', 'init=/tmp/tmpjd45me00/axl248qj.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelgftji951/prophet_model-20260803145043.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:43 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:43 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_33_dept_7
Build prophet model for  store_33_dept_74

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/g_udal4t.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gwh7nwbx.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=57083', 'data', 'file=/tmp/tmpjd45me00/g_udal4t.json', 'init=/tmp/tmpjd45me00/gwh7nwbx.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelgii5i9cf/prophet_model-20260803145044.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:44 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:44 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/84kgcvbh.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/th7v_6sm.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=87579', 'data', 'file=/tmp/tmpjd45me00/84kgcvbh.json', 'init=/tmp/tmpjd45me00/th7v_6sm.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelq6p7nzsb/prophet_model-20260803145044.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:44 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:44 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_33_dept_79

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8ddxkdps.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/b__d14w2.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=65227', 'data', 'file=/tmp/tmpjd45me00/8ddxkdps.json', 'init=/tmp/tmpjd45me00/b__d14w2.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelc_my9_p4/prophet_model-20260803145044.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:44 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:44 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_33_dept_8

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xb811duy.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1cyinct4.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=48404', 'data', 'file=/tmp/tmpjd45me00/xb811duy.json', 'init=/tmp/tmpjd45me00/1cyinct4.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelzq2qgerq/prophet_model-20260803145044.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:44 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:44 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/p52_scv3.json

Build prophet model for  store_33_dept_80
Build prophet model for  store_33_dept_81

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8o34hnr3.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=68867', 'data', 'file=/tmp/tmpjd45me00/p52_scv3.json', 'init=/tmp/tmpjd45me00/8o34hnr3.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model4ivj_g9w/prophet_model-20260803145044.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:44 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:45 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dtinpcxt.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/snq4exyg.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=9320', 'data', 'file=/tmp/tmpjd45me00/dtinpcxt.json', 'init=/tmp/tmpjd45me00/snq4exyg.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelnx3gy7hs/prophet_model-20260803145045.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:45 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_33_dept_82

14:50:45 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2q6yys94.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/e6mhpdtm.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=86680', 'data', 'file=/tmp/tmpjd45me00/2q6yys94.json', 'init=/tmp/tmpjd45me00/e6mhpdtm.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeldfhxsii0/prophet_model-20260803145045.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:45 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_33_dept_83

14:50:45 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ug44pa1_.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/e4994vfh.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=67188', 'data', 'file=/tmp/tmpjd45me00/ug44pa1_.json', 'init=/tmp/tmpjd45me00/e4994vfh.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelt1b8mfl0/prophet_model-20260803145045.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:45 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_33_dept_87

14:50:46 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ftk6ksyj.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7_7kv49w.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=67229', 'data', 'file=/tmp/tmpjd45me00/ftk6ksyj.json', 'init=/tmp/tmpjd45me00/7_7kv49w.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelkc2mqq6u/prophet_model-20260803145046.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:46 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:46 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_33_dept_90
Build prophet model for  store_33_dept_91

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ubr52m5r.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/nmo8qgmu.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=56571', 'data', 'file=/tmp/tmpjd45me00/ubr52m5r.json', 'init=/tmp/tmpjd45me00/nmo8qgmu.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelngxw8uyj/prophet_model-20260803145046.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:46 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:46 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7xpbmp5m.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/v9l4wqag.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=36722', 'data', 'file=/tmp/tmpjd45me00/7xpbmp5m.json', 'init=/tmp/tmpjd45me00/v9l4wqag.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelk3kh0yge/prophet_model-20260803145046.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:46 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:46 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xaus8j4m.json

Build prophet model for  store_33_dept_92
Build prophet model for  store_33_dept_93

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fc5dh_gv.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=53683', 'data', 'file=/tmp/tmpjd45me00/xaus8j4m.json', 'init=/tmp/tmpjd45me00/fc5dh_gv.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model22wbrv7t/prophet_model-20260803145046.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:46 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:46 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1tueto80.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/uhzucrp4.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=90300', 'data', 'file=/tmp/tmpjd45me00/1tueto80.json', 'init=/tmp/tmpjd45me00/uhzucrp4.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelz3vvzygt/prophet_model-20260803145046.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:46 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:47 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_33_dept_94

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3xj33n10.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0wd_snvy.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=99309', 'data', 'file=/tmp/tmpjd45me00/3xj33n10.json', 'init=/tmp/tmpjd45me00/0wd_snvy.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model2iob2hnj/prophet_model-20260803145047.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:47 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:47 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_33_dept_95

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/y4dhhm34.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hsyj0wcd.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=95802', 'data', 'file=/tmp/tmpjd45me00/y4dhhm34.json', 'init=/tmp/tmpjd45me00/hsyj0wcd.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model9wrt7_f4/prophet_model-20260803145047.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:47 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:47 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_33_dept_96

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mj2thixv.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/e_4wnb3k.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=84225', 'data', 'file=/tmp/tmpjd45me00/mj2thixv.json', 'init=/tmp/tmpjd45me00/e_4wnb3k.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelsf1se3qp/prophet_model-20260803145047.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:47 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:47 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dhcx1on2.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vpb9t15o.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=59242', 'data', 'file=/tmp/tmpjd45me00/dhcx1on2.json', 'init=/tmp/tmpjd45me00/vpb9t15o.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model1z_thkaw/prophet_model-20260803145047.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:47 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_33_dept_97
Build prophet model for  store_33_dept_98

14:50:47 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_1hssaf_.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/e2_o1cjy.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=54727', 'data', 'file=/tmp/tmpjd45me00/_1hssaf_.json', 'init=/tmp/tmpjd45me00/e2_o1cjy.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelln5eop4j/prophet_model-20260803145048.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:48 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:48 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_34_dept_1
Build prophet model for  store_34_dept_10

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ynoms73b.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/z8dqc762.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=96442', 'data', 'file=/tmp/tmpjd45me00/ynoms73b.json', 'init=/tmp/tmpjd45me00/z8dqc762.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_pkq2baq/prophet_model-20260803145048.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:48 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:48 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/b0dkbjmf.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/29mz33gt.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=65735', 'data', 'file=/tmp/tmpjd45me00/b0dkbjmf.json', 'init=/tmp/tmpjd45me00/29mz33gt.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelasgtkyps/prophet_model-20260803145048.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:48 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:48 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_34_dept_11
Build prophet model for  store_34_dept_12

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5nijjr7m.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_kujnip9.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=10536', 'data', 'file=/tmp/tmpjd45me00/5nijjr7m.json', 'init=/tmp/tmpjd45me00/_kujnip9.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelemynj3bi/prophet_model-20260803145048.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:48 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:48 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/sdsb7i2b.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ojfbo6aa.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=76555', 'data', 'file=/tmp/tmpjd45me00/sdsb7i2b.json', 'init=/tmp/tmpjd45me00/ojfbo6aa.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelqjh86zua/prophet_model-20260803145048.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:48 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:48 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_34_dept_13
Build prophet model for  store_34_dept_14

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/q85enefw.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dr1z0f6w.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=79975', 'data', 'file=/tmp/tmpjd45me00/q85enefw.json', 'init=/tmp/tmpjd45me00/dr1z0f6w.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelre309s7b/prophet_model-20260803145048.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:48 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:48 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/762gvj8m.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6mz896o_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=63809', 'data', 'file=/tmp/tmpjd45me00/762gvj8m.json', 'init=/tmp/tmpjd45me00/6mz896o_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelmnb3x2wv/prophet_model-20260803145049.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:49 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_34_dept_16

14:50:49 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vr8iab4x.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/kep7blv5.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=98883', 'data', 'file=/tmp/tmpjd45me00/vr8iab4x.json', 'init=/tmp/tmpjd45me00/kep7blv5.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelv6jfv_wn/prophet_model-20260803145049.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:49 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:49 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ginm1trq.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/r6comg9x.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=32942', 'data', 'file=/tmp/tmpjd45me00/ginm1trq.json', 'init=/tmp/tmpjd45me00/r6comg9x.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model0lifx252/prophet_model-20260803145049.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:49 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_34_dept_17
Build prophet model for  store_34_dept_18

14:50:49 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7gt9ub5c.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fjp9g2to.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=31053', 'data', 'file=/tmp/tmpjd45me00/7gt9ub5c.json', 'init=/tmp/tmpjd45me00/fjp9g2to.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelci47025u/prophet_model-20260803145049.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:49 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:49 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vhjzta68.json

Build prophet model for  store_34_dept_2
Build prophet model for  store_34_dept_20

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0ymge5h0.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=88430', 'data', 'file=/tmp/tmpjd45me00/vhjzta68.json', 'init=/tmp/tmpjd45me00/0ymge5h0.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model64ink3p4/prophet_model-20260803145049.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:49 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:49 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/l3zveswd.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_8ikqonh.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=95842', 'data', 'file=/tmp/tmpjd45me00/l3zveswd.json', 'init=/tmp/tmpjd45me00/_8ikqonh.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelttmovpeb/prophet_model-20260803145050.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:50 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:50 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_34_dept_21

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8lcedlw0.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/t02i1bdr.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=76491', 'data', 'file=/tmp/tmpjd45me00/8lcedlw0.json', 'init=/tmp/tmpjd45me00/t02i1bdr.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelum72mhwm/prophet_model-20260803145050.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:50 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:50 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/n66l5glx.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8c5bkp_z.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=41167', 'data', 'file=/tmp/tmpjd45me00/n66l5glx.json', 'init=/tmp/tmpjd45me00/8c5bkp_z.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelrlhrdjmr/prophet_model-20260803145050.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:50 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_34_dept_22
Build prophet model for  store_34_dept_23

14:50:50 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/h5snxdam.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/npbvab6e.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=77194', 'data', 'file=/tmp/tmpjd45me00/h5snxdam.json', 'init=/tmp/tmpjd45me00/npbvab6e.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modela5_io2t2/prophet_model-20260803145050.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:50 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:50 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/kxp6to7n.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/lrpaamla.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=84729', 'data', 'file=/tmp/tmpjd45me00/kxp6to7n.json', 'init=/tmp/tmpjd45me00/lrpaamla.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modely4uq5puo/prophet_model-20260803145050.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:50 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_34_dept_24
Build prophet model for  store_34_dept_25

14:50:50 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fld5hqt7.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/b9vr2gba.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=67945', 'data', 'file=/tmp/tmpjd45me00/fld5hqt7.json', 'init=/tmp/tmpjd45me00/b9vr2gba.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeldr83zcvy/prophet_model-20260803145051.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:51 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:51 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fe1vsa7o.json

Build prophet model for  store_34_dept_26
Build prophet model for  store_34_dept_27

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/a3dilc23.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=66686', 'data', 'file=/tmp/tmpjd45me00/fe1vsa7o.json', 'init=/tmp/tmpjd45me00/a3dilc23.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelyuegeh41/prophet_model-20260803145051.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:51 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:51 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_0rx92o8.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ul5vrtz9.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=1779', 'data', 'file=/tmp/tmpjd45me00/_0rx92o8.json', 'init=/tmp/tmpjd45me00/ul5vrtz9.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelpt247dof/prophet_model-20260803145051.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:51 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:51 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_34_dept_28
Build prophet model for  store_34_dept_29

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/txzh98g2.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5xqyzjap.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=39541', 'data', 'file=/tmp/tmpjd45me00/txzh98g2.json', 'init=/tmp/tmpjd45me00/5xqyzjap.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model6r2o7z23/prophet_model-20260803145051.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:51 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:51 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/th45mqj7.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/cxqev9_1.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=64168', 'data', 'file=/tmp/tmpjd45me00/th45mqj7.json', 'init=/tmp/tmpjd45me00/cxqev9_1.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelaiosc7n1/prophet_model-20260803145051.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:51 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:52 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ojgkp88e.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vzft5enh.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=94636', 'data', 'file=/tmp/tmpjd45me00/ojgkp88e.json', 'init=/tmp/tmpjd45me00/vzft5enh.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelbyj7bht4/prophet_model-20260803145052.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:52 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_34_dept_3
Build prophet model for  store_34_dept_30

14:50:52 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/tkhs0max.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_uzvh425.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=56969', 'data', 'file=/tmp/tmpjd45me00/tkhs0max.json', 'init=/tmp/tmpjd45me00/_uzvh425.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model68nmczge/prophet_model-20260803145052.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:52 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:52 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/kzuuhao6.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6yv0bq3a.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=84827', 'data', 'file=/tmp/tmpjd45me00/kzuuhao6.json', 'init=/tmp/tmpjd45me00/6yv0bq3a.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model5dpbc7ti/prophet_model-20260803145052.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']

Build prophet model for  store_34_dept_31
Build prophet model for  store_34_dept_32

14:50:52 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:52 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/svwjr02o.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ed4rhex3.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=98430', 'data', 'file=/tmp/tmpjd45me00/svwjr02o.json', 'init=/tmp/tmpjd45me00/ed4rhex3.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model5jv3vlw1/prophet_model-20260803145052.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:52 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:52 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/za4jfllx.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/q_oqd8hu.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=78022', 'data', 'file=/tmp/tmpjd45me00/za4jfllx.json', 'init=/tmp/tmpjd45me00/q_oqd8hu.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelk5q1ffrp/prophet_model-20260803145052.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:52 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_34_dept_33
Build prophet model for  store_34_dept_34

14:50:52 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9w_nf5t1.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/04kr36to.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=56009', 'data', 'file=/tmp/tmpjd45me00/9w_nf5t1.json', 'init=/tmp/tmpjd45me00/04kr36to.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_2a546x8/prophet_model-20260803145053.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:53 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:53 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_34_dept_35
Build prophet model for  store_34_dept_36

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/eoih_685.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/f7v3uru4.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=73978', 'data', 'file=/tmp/tmpjd45me00/eoih_685.json', 'init=/tmp/tmpjd45me00/f7v3uru4.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model6shazxki/prophet_model-20260803145053.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:53 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:53 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bgk78rnt.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7g6hb3km.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=4433', 'data', 'file=/tmp/tmpjd45me00/bgk78rnt.json', 'init=/tmp/tmpjd45me00/7g6hb3km.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model56u04bxm/prophet_model-20260803145053.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:53 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_34_dept_37

14:50:53 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7lmmoh87.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/x26jl5ha.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=35972', 'data', 'file=/tmp/tmpjd45me00/7lmmoh87.json', 'init=/tmp/tmpjd45me00/x26jl5ha.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelmcg3nlwy/prophet_model-20260803145053.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:53 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:53 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_34_dept_38

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rtwx5wxi.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/js5nzmcw.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=8463', 'data', 'file=/tmp/tmpjd45me00/rtwx5wxi.json', 'init=/tmp/tmpjd45me00/js5nzmcw.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelv8b_p1yg/prophet_model-20260803145054.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:54 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:54 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_34_dept_4
Build prophet model for  store_34_dept_40

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dw01uzm8.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/go5u20sk.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=55038', 'data', 'file=/tmp/tmpjd45me00/dw01uzm8.json', 'init=/tmp/tmpjd45me00/go5u20sk.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model908_dmst/prophet_model-20260803145054.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:54 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:54 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/r4gky2yd.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ev39x94i.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=82665', 'data', 'file=/tmp/tmpjd45me00/r4gky2yd.json', 'init=/tmp/tmpjd45me00/ev39x94i.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model7t4achg9/prophet_model-20260803145054.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:54 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_34_dept_41

14:50:55 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8qa9c0td.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/47yvx9i8.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=80901', 'data', 'file=/tmp/tmpjd45me00/8qa9c0td.json', 'init=/tmp/tmpjd45me00/47yvx9i8.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model36odxtxe/prophet_model-20260803145055.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:55 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:55 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_34_dept_42

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8b1ipi2o.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3gxn4r99.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=92973', 'data', 'file=/tmp/tmpjd45me00/8b1ipi2o.json', 'init=/tmp/tmpjd45me00/3gxn4r99.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelsqm8oex_/prophet_model-20260803145055.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:55 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:55 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_34_dept_44

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/z0rfmxa3.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fkc4rc7w.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=54698', 'data', 'file=/tmp/tmpjd45me00/z0rfmxa3.json', 'init=/tmp/tmpjd45me00/fkc4rc7w.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelpyic1j_9/prophet_model-20260803145056.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:56 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:56 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_34_dept_46

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/37p489iu.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/n8k80fgf.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=37013', 'data', 'file=/tmp/tmpjd45me00/37p489iu.json', 'init=/tmp/tmpjd45me00/n8k80fgf.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeltcat441m/prophet_model-20260803145056.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:56 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:56 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pd7t9nms.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/60qgpb8x.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=10725', 'data', 'file=/tmp/tmpjd45me00/pd7t9nms.json', 'init=/tmp/tmpjd45me00/60qgpb8x.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelpnsyatrb/prophet_model-20260803145056.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:56 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_34_dept_48
Build prophet model for  store_34_dept_49

14:50:56 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9bkhkhy6.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dknafv1r.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=57017', 'data', 'file=/tmp/tmpjd45me00/9bkhkhy6.json', 'init=/tmp/tmpjd45me00/dknafv1r.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model7cum97p_/prophet_model-20260803145056.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:56 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:56 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_34_dept_5
Build prophet model for  store_34_dept_51
Skip  store_34_dept_51 due to lack of data
Build prophet model for  store_34_dept_52

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pbp8_d33.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0_pnhmsl.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=33840', 'data', 'file=/tmp/tmpjd45me00/pbp8_d33.json', 'init=/tmp/tmpjd45me00/0_pnhmsl.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelvsk8d5s0/prophet_model-20260803145056.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:56 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:56 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6sl2xy4n.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/k84_q72w.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=62276', 'data', 'file=/tmp/tmpjd45me00/6sl2xy4n.json', 'init=/tmp/tmpjd45me00/k84_q72w.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelrg0kom30/prophet_model-20260803145056.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:56 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_34_dept_54

14:50:57 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vphcbkru.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/cdh3_rb8.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=44262', 'data', 'file=/tmp/tmpjd45me00/vphcbkru.json', 'init=/tmp/tmpjd45me00/cdh3_rb8.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelx8xxfsr_/prophet_model-20260803145057.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:57 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:57 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/umjnl6qd.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_izc7ni8.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=33176', 'data', 'file=/tmp/tmpjd45me00/umjnl6qd.json', 'init=/tmp/tmpjd45me00/_izc7ni8.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model0dzvbxja/prophet_model-20260803145057.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:57 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_34_dept_55
Build prophet model for  store_34_dept_56

14:50:57 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2r9wkrhm.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fugv6k3o.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=86703', 'data', 'file=/tmp/tmpjd45me00/2r9wkrhm.json', 'init=/tmp/tmpjd45me00/fugv6k3o.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model7bp87td_/prophet_model-20260803145057.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:57 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_34_dept_59

14:50:57 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ndzf3s9f.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/uq3mjn7i.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=22705', 'data', 'file=/tmp/tmpjd45me00/ndzf3s9f.json', 'init=/tmp/tmpjd45me00/uq3mjn7i.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelcbar3rer/prophet_model-20260803145058.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:58 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:58 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9se7y8d4.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1p6jl3yx.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=20842', 'data', 'file=/tmp/tmpjd45me00/9se7y8d4.json', 'init=/tmp/tmpjd45me00/1p6jl3yx.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_wvh_ofi/prophet_model-20260803145058.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:58 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_34_dept_6
Build prophet model for  store_34_dept_65

14:50:58 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0tgbagh4.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7gbri0cn.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=15795', 'data', 'file=/tmp/tmpjd45me00/0tgbagh4.json', 'init=/tmp/tmpjd45me00/7gbri0cn.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model8dpfu6tx/prophet_model-20260803145058.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:58 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:58 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ps93ijzc.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dc75e9q_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=25991', 'data', 'file=/tmp/tmpjd45me00/ps93ijzc.json', 'init=/tmp/tmpjd45me00/dc75e9q_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeltidgpvn3/prophet_model-20260803145058.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:58 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_34_dept_67
Build prophet model for  store_34_dept_7

14:50:58 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vc8au5fx.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8rs4d14i.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=62028', 'data', 'file=/tmp/tmpjd45me00/vc8au5fx.json', 'init=/tmp/tmpjd45me00/8rs4d14i.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model4hplzr1t/prophet_model-20260803145058.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:58 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:58 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_34_dept_71

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qersif_1.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pd3ncfee.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=16740', 'data', 'file=/tmp/tmpjd45me00/qersif_1.json', 'init=/tmp/tmpjd45me00/pd3ncfee.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelhdw8ogxg/prophet_model-20260803145059.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:59 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:59 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/sf5hat_b.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/l5xdw0bg.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=74888', 'data', 'file=/tmp/tmpjd45me00/sf5hat_b.json', 'init=/tmp/tmpjd45me00/l5xdw0bg.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modele80kfwf0/prophet_model-20260803145059.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:59 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_34_dept_72
Build prophet model for  store_34_dept_74

14:50:59 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/55_utdrh.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/i9p2n8al.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=94471', 'data', 'file=/tmp/tmpjd45me00/55_utdrh.json', 'init=/tmp/tmpjd45me00/i9p2n8al.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeluy5p3r30/prophet_model-20260803145059.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:59 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:59 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_34_dept_79
Build prophet model for  store_34_dept_8

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1wfl3152.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pu0g62iz.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=25512', 'data', 'file=/tmp/tmpjd45me00/1wfl3152.json', 'init=/tmp/tmpjd45me00/pu0g62iz.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelyerut3z0/prophet_model-20260803145059.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:59 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:59 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gkyagckf.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_ihmbd9o.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=61750', 'data', 'file=/tmp/tmpjd45me00/gkyagckf.json', 'init=/tmp/tmpjd45me00/_ihmbd9o.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_oqfc8jr/prophet_model-20260803145059.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:50:59 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:50:59 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_34_dept_80
Build prophet model for  store_34_dept_81

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ch2y5c9z.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/cdx2xw7b.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=87248', 'data', 'file=/tmp/tmpjd45me00/ch2y5c9z.json', 'init=/tmp/tmpjd45me00/cdx2xw7b.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelx79q3ayb/prophet_model-20260803145100.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:00 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:00 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dd6ljb7l.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/sggr2m2r.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=87590', 'data', 'file=/tmp/tmpjd45me00/dd6ljb7l.json', 'init=/tmp/tmpjd45me00/sggr2m2r.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model10gzr4o4/prophet_model-20260803145100.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:00 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:00 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/invde1j3.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/esifeu4w.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=89584', 'data', 'file=/tmp/tmpjd45me00/invde1j3.json', 'init=/tmp/tmpjd45me00/esifeu4w.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelsw15ngmg/prophet_model-20260803145100.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:00 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_34_dept_82
Build prophet model for  store_34_dept_83

14:51:00 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/45apilo2.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/80uuanqm.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=1008', 'data', 'file=/tmp/tmpjd45me00/45apilo2.json', 'init=/tmp/tmpjd45me00/80uuanqm.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelwwk3ljts/prophet_model-20260803145100.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:00 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:00 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qhmr906a.json

Build prophet model for  store_34_dept_85
Build prophet model for  store_34_dept_87

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xs9cjyzp.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=82253', 'data', 'file=/tmp/tmpjd45me00/qhmr906a.json', 'init=/tmp/tmpjd45me00/xs9cjyzp.json', 'output', 'file=/tmp/tmpjd45me00/prophet_models1dyn9ha/prophet_model-20260803145100.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:00 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:00 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mhvlklqr.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/lhtxpmus.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=32608', 'data', 'file=/tmp/tmpjd45me00/mhvlklqr.json', 'init=/tmp/tmpjd45me00/lhtxpmus.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model5m_d0uco/prophet_model-20260803145100.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:00 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:00 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/98k66uag.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3saxlai8.json

Build prophet model for  store_34_dept_9
Build prophet model for  store_34_dept_90

DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=17455', 'data', 'file=/tmp/tmpjd45me00/98k66uag.json', 'init=/tmp/tmpjd45me00/3saxlai8.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelb33fpp_h/prophet_model-20260803145101.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:01 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:01 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/t7575hf7.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/kuk1o0su.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=15262', 'data', 'file=/tmp/tmpjd45me00/t7575hf7.json', 'init=/tmp/tmpjd45me00/kuk1o0su.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelqs36yjj6/prophet_model-20260803145101.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:01 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:01 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/td_bm98r.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/lzmnlxfe.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=75567', 'data', 'file=/tmp/tmpjd45me00/td_bm98r.json', 'init=/tmp/tmpjd45me00/lzmnlxfe.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model78h5c_t6/prophet_model-20260803145101.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:01 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:01 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_34_dept_91
Build prophet model for  store_34_dept_92

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0hilozl_.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xxopv0qz.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=13713', 'data', 'file=/tmp/tmpjd45me00/0hilozl_.json', 'init=/tmp/tmpjd45me00/xxopv0qz.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelhephe9db/prophet_model-20260803145101.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:01 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:01 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/khx0i0r7.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/a102mxvh.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=19442', 'data', 'file=/tmp/tmpjd45me00/khx0i0r7.json', 'init=/tmp/tmpjd45me00/a102mxvh.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelsi6a3tmx/prophet_model-20260803145101.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:01 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_34_dept_93
Build prophet model for  store_34_dept_94

14:51:01 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/t_0n8ae2.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/x3f1d3vp.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=38096', 'data', 'file=/tmp/tmpjd45me00/t_0n8ae2.json', 'init=/tmp/tmpjd45me00/x3f1d3vp.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelxncyjqui/prophet_model-20260803145101.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:01 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:01 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/sc05zwf4.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1o_uocnk.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=38613', 'data', 'file=/tmp/tmpjd45me00/sc05zwf4.json', 'init=/tmp/tmpjd45me00/1o_uocnk.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelj2cto7i8/prophet_model-20260803145101.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:01 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_34_dept_95
Build prophet model for  store_34_dept_96

14:51:02 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/sss55bu3.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bm5vmyg0.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=41056', 'data', 'file=/tmp/tmpjd45me00/sss55bu3.json', 'init=/tmp/tmpjd45me00/bm5vmyg0.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model67hk6lj0/prophet_model-20260803145102.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:02 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:02 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_34_dept_97
Build prophet model for  store_34_dept_98

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jggyuwe_.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xf3xmwff.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=39870', 'data', 'file=/tmp/tmpjd45me00/jggyuwe_.json', 'init=/tmp/tmpjd45me00/xf3xmwff.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelm6vcswor/prophet_model-20260803145102.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:02 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:02 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qoxg8khz.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rka6fjev.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=47633', 'data', 'file=/tmp/tmpjd45me00/qoxg8khz.json', 'init=/tmp/tmpjd45me00/rka6fjev.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model8l2hh6l_/prophet_model-20260803145102.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:02 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:02 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_35_dept_1
Build prophet model for  store_35_dept_10

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/lk6o_z68.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/oug67juu.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=78141', 'data', 'file=/tmp/tmpjd45me00/lk6o_z68.json', 'init=/tmp/tmpjd45me00/oug67juu.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model9ix3cctq/prophet_model-20260803145102.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:02 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:02 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/stm2fqns.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1fgce4a9.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=17456', 'data', 'file=/tmp/tmpjd45me00/stm2fqns.json', 'init=/tmp/tmpjd45me00/1fgce4a9.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelubo5b1wj/prophet_model-20260803145103.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:03 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:03 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_35_dept_11

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zh5n9zpw.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/lj9nff7t.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=60838', 'data', 'file=/tmp/tmpjd45me00/zh5n9zpw.json', 'init=/tmp/tmpjd45me00/lj9nff7t.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model06o96zq5/prophet_model-20260803145103.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:03 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:03 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rbcpcqqn.json

Build prophet model for  store_35_dept_12
Build prophet model for  store_35_dept_13

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jk4h5vj1.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=13571', 'data', 'file=/tmp/tmpjd45me00/rbcpcqqn.json', 'init=/tmp/tmpjd45me00/jk4h5vj1.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelb_66i_ed/prophet_model-20260803145103.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:03 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:03 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dehl5zg2.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rurnyzm9.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=29133', 'data', 'file=/tmp/tmpjd45me00/dehl5zg2.json', 'init=/tmp/tmpjd45me00/rurnyzm9.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model0nbuontl/prophet_model-20260803145103.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:03 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:03 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/muedwzyj.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/cd0_ulhe.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=81124', 'data', 'file=/tmp/tmpjd45me00/muedwzyj.json', 'init=/tmp/tmpjd45me00/cd0_ulhe.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model0o1jrgg0/prophet_model-20260803145103.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:03 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_35_dept_14
Build prophet model for  store_35_dept_16

14:51:04 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8i92ibzj.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9tgzvfv7.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=73798', 'data', 'file=/tmp/tmpjd45me00/8i92ibzj.json', 'init=/tmp/tmpjd45me00/9tgzvfv7.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model3r8u38qq/prophet_model-20260803145104.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:04 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:04 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_35_dept_17

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/lwtrtgsd.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ewim91x4.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=58001', 'data', 'file=/tmp/tmpjd45me00/lwtrtgsd.json', 'init=/tmp/tmpjd45me00/ewim91x4.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelmfa49d1m/prophet_model-20260803145104.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:04 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:04 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/b_u3h7gb.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zjmlfbvh.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=51961', 'data', 'file=/tmp/tmpjd45me00/b_u3h7gb.json', 'init=/tmp/tmpjd45me00/zjmlfbvh.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeldfeqvh9h/prophet_model-20260803145104.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:04 - cmdstanpy - INFO - Chain [1] start processing

Build prophet model for  store_35_dept_18
Build prophet model for  store_35_dept_2

INFO:cmdstanpy:Chain [1] start processing
14:51:04 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/060h0jbv.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jpaccpgf.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=60982', 'data', 'file=/tmp/tmpjd45me00/060h0jbv.json', 'init=/tmp/tmpjd45me00/jpaccpgf.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelwvdj7aoj/prophet_model-20260803145104.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:04 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:04 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_35_dept_20
Build prophet model for  store_35_dept_21

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/lxxjkoih.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/27zt8b9n.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=87048', 'data', 'file=/tmp/tmpjd45me00/lxxjkoih.json', 'init=/tmp/tmpjd45me00/27zt8b9n.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelm9oukbp9/prophet_model-20260803145105.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:05 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:05 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wike7r9w.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7ybata4s.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=91767', 'data', 'file=/tmp/tmpjd45me00/wike7r9w.json', 'init=/tmp/tmpjd45me00/7ybata4s.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model0geby_52/prophet_model-20260803145105.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:05 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:05 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_35_dept_22

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/k5oitm4v.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ezu_abe8.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=95292', 'data', 'file=/tmp/tmpjd45me00/k5oitm4v.json', 'init=/tmp/tmpjd45me00/ezu_abe8.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelo8wly__p/prophet_model-20260803145105.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:05 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:05 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/y2i_vp00.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pj9be3qw.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=72217', 'data', 'file=/tmp/tmpjd45me00/y2i_vp00.json', 'init=/tmp/tmpjd45me00/pj9be3qw.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelm6ne8uj0/prophet_model-20260803145105.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:05 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_35_dept_23
Build prophet model for  store_35_dept_24

14:51:05 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/53gc2h15.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4pbagmci.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=39089', 'data', 'file=/tmp/tmpjd45me00/53gc2h15.json', 'init=/tmp/tmpjd45me00/4pbagmci.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelj4805rjl/prophet_model-20260803145106.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:06 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_35_dept_25

14:51:06 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7xczlop7.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0rqe55zc.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=13553', 'data', 'file=/tmp/tmpjd45me00/7xczlop7.json', 'init=/tmp/tmpjd45me00/0rqe55zc.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelxjh4u5f3/prophet_model-20260803145106.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:06 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_35_dept_26

14:51:06 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/12ob6e8x.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/c0a3pnod.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=1922', 'data', 'file=/tmp/tmpjd45me00/12ob6e8x.json', 'init=/tmp/tmpjd45me00/c0a3pnod.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelx101b0bi/prophet_model-20260803145106.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:06 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:06 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_35_dept_27
Build prophet model for  store_35_dept_28

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/uufdrxbb.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/g8efyd5i.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=34564', 'data', 'file=/tmp/tmpjd45me00/uufdrxbb.json', 'init=/tmp/tmpjd45me00/g8efyd5i.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modely6g49882/prophet_model-20260803145107.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:07 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:07 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bgsqqzkk.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bjz5n70y.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=86423', 'data', 'file=/tmp/tmpjd45me00/bgsqqzkk.json', 'init=/tmp/tmpjd45me00/bjz5n70y.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeliix1a1hx/prophet_model-20260803145107.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:07 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_35_dept_29

14:51:07 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/p23g335y.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/s9at32uk.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=86350', 'data', 'file=/tmp/tmpjd45me00/p23g335y.json', 'init=/tmp/tmpjd45me00/s9at32uk.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeluom9j46h/prophet_model-20260803145107.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:07 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_35_dept_3

14:51:07 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wp69d6av.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vr09k7ph.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=93674', 'data', 'file=/tmp/tmpjd45me00/wp69d6av.json', 'init=/tmp/tmpjd45me00/vr09k7ph.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modela9y_841w/prophet_model-20260803145108.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:08 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_35_dept_30

14:51:08 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5hetc9o9.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/lfy46vr4.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=24636', 'data', 'file=/tmp/tmpjd45me00/5hetc9o9.json', 'init=/tmp/tmpjd45me00/lfy46vr4.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelrksd0bmo/prophet_model-20260803145108.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:08 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:08 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_35_dept_31

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/62_d0kkn.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wwd6up6p.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=68335', 'data', 'file=/tmp/tmpjd45me00/62_d0kkn.json', 'init=/tmp/tmpjd45me00/wwd6up6p.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeld57kgto8/prophet_model-20260803145108.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:08 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:08 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_35_dept_32
Build prophet model for  store_35_dept_33

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mot61ujb.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/yxhhhrmt.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=19629', 'data', 'file=/tmp/tmpjd45me00/mot61ujb.json', 'init=/tmp/tmpjd45me00/yxhhhrmt.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model84e9p47m/prophet_model-20260803145109.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:09 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:09 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/db41g059.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pd40sr7h.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=35310', 'data', 'file=/tmp/tmpjd45me00/db41g059.json', 'init=/tmp/tmpjd45me00/pd40sr7h.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model63ddvauu/prophet_model-20260803145109.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:09 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:09 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_35_dept_34
Build prophet model for  store_35_dept_35

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_4htgpfz.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qw3d2pba.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=38522', 'data', 'file=/tmp/tmpjd45me00/_4htgpfz.json', 'init=/tmp/tmpjd45me00/qw3d2pba.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model45m7wxy2/prophet_model-20260803145109.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:09 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:09 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/uohflwn2.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/a_xjfu63.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=30466', 'data', 'file=/tmp/tmpjd45me00/uohflwn2.json', 'init=/tmp/tmpjd45me00/a_xjfu63.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelh3zs9j90/prophet_model-20260803145109.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:09 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_35_dept_36

14:51:09 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vkkdzq5w.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/s482dqj4.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=59448', 'data', 'file=/tmp/tmpjd45me00/vkkdzq5w.json', 'init=/tmp/tmpjd45me00/s482dqj4.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelq_nnsgat/prophet_model-20260803145110.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:10 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:10 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_35_dept_38
Build prophet model for  store_35_dept_4

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ophqx9q0.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/51jcv91a.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=94245', 'data', 'file=/tmp/tmpjd45me00/ophqx9q0.json', 'init=/tmp/tmpjd45me00/51jcv91a.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelibn5nwky/prophet_model-20260803145110.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:10 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:10 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4f9srx_o.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/e19y2sd1.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=12731', 'data', 'file=/tmp/tmpjd45me00/4f9srx_o.json', 'init=/tmp/tmpjd45me00/e19y2sd1.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelwl2c2dcm/prophet_model-20260803145110.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:10 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_35_dept_40

14:51:10 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6_kvfd59.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/94hgi5j8.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=88286', 'data', 'file=/tmp/tmpjd45me00/6_kvfd59.json', 'init=/tmp/tmpjd45me00/94hgi5j8.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelafg8ol5b/prophet_model-20260803145110.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:10 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_35_dept_41

14:51:11 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/138bj13f.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/v98hhsq5.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=36362', 'data', 'file=/tmp/tmpjd45me00/138bj13f.json', 'init=/tmp/tmpjd45me00/v98hhsq5.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelhceb2_vr/prophet_model-20260803145111.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:11 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:11 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_35_dept_42
Build prophet model for  store_35_dept_44

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/27w04clg.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6ofaq3ka.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=14623', 'data', 'file=/tmp/tmpjd45me00/27w04clg.json', 'init=/tmp/tmpjd45me00/6ofaq3ka.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelthfspqp5/prophet_model-20260803145111.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:11 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:11 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/amebei_m.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9ouz4f86.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=55610', 'data', 'file=/tmp/tmpjd45me00/amebei_m.json', 'init=/tmp/tmpjd45me00/9ouz4f86.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelo53u2byd/prophet_model-20260803145111.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:11 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:11 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/s0addjs9.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2clh9c3j.json

Build prophet model for  store_35_dept_46
Build prophet model for  store_35_dept_5

DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=89586', 'data', 'file=/tmp/tmpjd45me00/s0addjs9.json', 'init=/tmp/tmpjd45me00/2clh9c3j.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model92gjs220/prophet_model-20260803145111.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:11 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:11 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/n4_7wwkf.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hd7t6vtp.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=84770', 'data', 'file=/tmp/tmpjd45me00/n4_7wwkf.json', 'init=/tmp/tmpjd45me00/hd7t6vtp.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model3m1ay_4p/prophet_model-20260803145112.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:51:12 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_35_dept_51

14:51:12 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gjcaltfi.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vlb28pus.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=42066', 'data', 'file=/tmp/tmpjd45me00/gjcaltfi.json', 'init=/tmp/tmpjd45me00/vlb28pus.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model4u55j0eu/prophet_model-20260803145113.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:13 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:13 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_35_dept_52
Build prophet model for  store_35_dept_54

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/a151j2u5.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hxictfqx.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=14348', 'data', 'file=/tmp/tmpjd45me00/a151j2u5.json', 'init=/tmp/tmpjd45me00/hxictfqx.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelg0d097h2/prophet_model-20260803145113.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:13 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:13 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8iv71fgx.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/aleih6h9.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=39998', 'data', 'file=/tmp/tmpjd45me00/8iv71fgx.json', 'init=/tmp/tmpjd45me00/aleih6h9.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeljq5vmvse/prophet_model-20260803145113.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:13 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_35_dept_55

14:51:13 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0l8md2nc.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/19c2xng_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=63737', 'data', 'file=/tmp/tmpjd45me00/0l8md2nc.json', 'init=/tmp/tmpjd45me00/19c2xng_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model6xyuha66/prophet_model-20260803145113.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:13 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:13 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/u91f594t.json

Build prophet model for  store_35_dept_56
Build prophet model for  store_35_dept_58

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/k67fubvy.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=19909', 'data', 'file=/tmp/tmpjd45me00/u91f594t.json', 'init=/tmp/tmpjd45me00/k67fubvy.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelqmvk9gze/prophet_model-20260803145113.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:13 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:13 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/a5e8qe40.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/69bdxjqq.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=48066', 'data', 'file=/tmp/tmpjd45me00/a5e8qe40.json', 'init=/tmp/tmpjd45me00/69bdxjqq.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelou7_k0cl/prophet_model-20260803145114.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:14 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_35_dept_59

14:51:14 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2dvkqn8k.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jkde1zv1.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=85558', 'data', 'file=/tmp/tmpjd45me00/2dvkqn8k.json', 'init=/tmp/tmpjd45me00/jkde1zv1.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_wantpt3/prophet_model-20260803145114.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:14 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:14 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ujjg2g5d.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4eeyh3vk.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=16532', 'data', 'file=/tmp/tmpjd45me00/ujjg2g5d.json', 'init=/tmp/tmpjd45me00/4eeyh3vk.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelmek7a7ww/prophet_model-20260803145114.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:14 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_35_dept_6
Build prophet model for  store_35_dept_60

14:51:14 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/63y4yd9y.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rac5i4n5.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=90852', 'data', 'file=/tmp/tmpjd45me00/63y4yd9y.json', 'init=/tmp/tmpjd45me00/rac5i4n5.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelry4vr9cn/prophet_model-20260803145114.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:14 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:14 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/34q4kj86.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/50ujv5cy.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=10666', 'data', 'file=/tmp/tmpjd45me00/34q4kj86.json', 'init=/tmp/tmpjd45me00/50ujv5cy.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model0ojxy74e/prophet_model-20260803145114.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']

Build prophet model for  store_35_dept_67
Build prophet model for  store_35_dept_7

14:51:14 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:14 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6se0mt70.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0zj9ddfp.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=22635', 'data', 'file=/tmp/tmpjd45me00/6se0mt70.json', 'init=/tmp/tmpjd45me00/0zj9ddfp.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelm7nglip1/prophet_model-20260803145115.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:15 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_35_dept_71

14:51:15 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/06yt2j2d.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/nj9gh1yu.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=82589', 'data', 'file=/tmp/tmpjd45me00/06yt2j2d.json', 'init=/tmp/tmpjd45me00/nj9gh1yu.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model9rrjsgnp/prophet_model-20260803145115.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:15 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:15 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_35_dept_72
Build prophet model for  store_35_dept_74

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/12won3mk.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/o787b2j6.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=82013', 'data', 'file=/tmp/tmpjd45me00/12won3mk.json', 'init=/tmp/tmpjd45me00/o787b2j6.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelpqr4f05l/prophet_model-20260803145115.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:15 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:15 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/677inhdh.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/x9qazjdv.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=86354', 'data', 'file=/tmp/tmpjd45me00/677inhdh.json', 'init=/tmp/tmpjd45me00/x9qazjdv.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model46iri6hm/prophet_model-20260803145116.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:16 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:16 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_35_dept_79

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hozfleud.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wunp76lk.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=57312', 'data', 'file=/tmp/tmpjd45me00/hozfleud.json', 'init=/tmp/tmpjd45me00/wunp76lk.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model34g2loq0/prophet_model-20260803145116.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:16 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:16 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_35_dept_8
Build prophet model for  store_35_dept_81

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6xkfudeo.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/czgamb1s.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=38218', 'data', 'file=/tmp/tmpjd45me00/6xkfudeo.json', 'init=/tmp/tmpjd45me00/czgamb1s.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelyutc6fol/prophet_model-20260803145116.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:16 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:16 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6uev389h.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8cpeea3q.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=8053', 'data', 'file=/tmp/tmpjd45me00/6uev389h.json', 'init=/tmp/tmpjd45me00/8cpeea3q.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelljx2syf9/prophet_model-20260803145116.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:16 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:16 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/79j3pncq.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/u3mk0vaj.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=56100', 'data', 'file=/tmp/tmpjd45me00/79j3pncq.json', 'init=/tmp/tmpjd45me00/u3mk0vaj.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_w1zyfj4/prophet_model-20260803145116.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:16 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_35_dept_82
Build prophet model for  store_35_dept_83

14:51:17 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/re7v7w90.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/lgkyl76r.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=38652', 'data', 'file=/tmp/tmpjd45me00/re7v7w90.json', 'init=/tmp/tmpjd45me00/lgkyl76r.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model6y933su3/prophet_model-20260803145117.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:17 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_35_dept_85

14:51:17 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/flvdruzu.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/shdylk7u.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=56927', 'data', 'file=/tmp/tmpjd45me00/flvdruzu.json', 'init=/tmp/tmpjd45me00/shdylk7u.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelhf4k32sl/prophet_model-20260803145117.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:17 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:17 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_35_dept_87
Build prophet model for  store_35_dept_9

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/n_qtpz_6.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/t2sqp19j.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=96319', 'data', 'file=/tmp/tmpjd45me00/n_qtpz_6.json', 'init=/tmp/tmpjd45me00/t2sqp19j.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelvxcx4yfn/prophet_model-20260803145117.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:17 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:18 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9amvx9de.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1a72yxez.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=25725', 'data', 'file=/tmp/tmpjd45me00/9amvx9de.json', 'init=/tmp/tmpjd45me00/1a72yxez.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model15m5rj5v/prophet_model-20260803145118.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:18 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:18 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_35_dept_90

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bqe1c4js.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/f60hmud_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=91821', 'data', 'file=/tmp/tmpjd45me00/bqe1c4js.json', 'init=/tmp/tmpjd45me00/f60hmud_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelh2yfqiy4/prophet_model-20260803145118.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:18 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_35_dept_91

14:51:18 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8woh0x2t.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/llzvhfdi.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=57243', 'data', 'file=/tmp/tmpjd45me00/8woh0x2t.json', 'init=/tmp/tmpjd45me00/llzvhfdi.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelfeshl1fp/prophet_model-20260803145118.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:18 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:18 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_35_dept_92

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/09kctblo.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/e47wda45.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=3985', 'data', 'file=/tmp/tmpjd45me00/09kctblo.json', 'init=/tmp/tmpjd45me00/e47wda45.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelph4kmx3f/prophet_model-20260803145119.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:19 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_35_dept_93

14:51:19 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2w0vqp_o.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jwrdhem4.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=28444', 'data', 'file=/tmp/tmpjd45me00/2w0vqp_o.json', 'init=/tmp/tmpjd45me00/jwrdhem4.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelcb53ks2e/prophet_model-20260803145119.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:19 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_35_dept_95

14:51:19 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mzn2smca.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/tmw05xhe.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=24055', 'data', 'file=/tmp/tmpjd45me00/mzn2smca.json', 'init=/tmp/tmpjd45me00/tmw05xhe.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelk_gwk_gx/prophet_model-20260803145120.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:20 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:20 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_35_dept_97

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/to7ih8nx.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ym2abvll.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=79610', 'data', 'file=/tmp/tmpjd45me00/to7ih8nx.json', 'init=/tmp/tmpjd45me00/ym2abvll.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_jr6f7ms/prophet_model-20260803145120.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:20 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:20 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_36_dept_1

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/u71yqibq.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8sva_e_3.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=15332', 'data', 'file=/tmp/tmpjd45me00/u71yqibq.json', 'init=/tmp/tmpjd45me00/8sva_e_3.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model6e8_wt2d/prophet_model-20260803145120.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:20 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:20 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_36_dept_10

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2413hvym.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ltmj9gip.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=99153', 'data', 'file=/tmp/tmpjd45me00/2413hvym.json', 'init=/tmp/tmpjd45me00/ltmj9gip.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model1ltqwuxh/prophet_model-20260803145120.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:20 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_36_dept_13

14:51:21 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/cuqnyzk8.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bpfsxx63.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=20564', 'data', 'file=/tmp/tmpjd45me00/cuqnyzk8.json', 'init=/tmp/tmpjd45me00/bpfsxx63.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model5xgxxezg/prophet_model-20260803145121.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:21 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_36_dept_14

14:51:21 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ibybjrqt.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0m7nc140.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=1580', 'data', 'file=/tmp/tmpjd45me00/ibybjrqt.json', 'init=/tmp/tmpjd45me00/0m7nc140.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model11p2j_ky/prophet_model-20260803145121.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:21 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:21 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_36_dept_16

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0m12smks.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/duk_rw1e.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=13525', 'data', 'file=/tmp/tmpjd45me00/0m12smks.json', 'init=/tmp/tmpjd45me00/duk_rw1e.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelzljsv5qy/prophet_model-20260803145122.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:22 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:22 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_36_dept_17

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/32iknnk7.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ge446fqc.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=29340', 'data', 'file=/tmp/tmpjd45me00/32iknnk7.json', 'init=/tmp/tmpjd45me00/ge446fqc.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelnfvx26zb/prophet_model-20260803145122.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:22 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:22 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_36_dept_2

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rc_ctry9.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/k32onr_e.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=57750', 'data', 'file=/tmp/tmpjd45me00/rc_ctry9.json', 'init=/tmp/tmpjd45me00/k32onr_e.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelx_m56h3i/prophet_model-20260803145122.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:22 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:22 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/002msgf9.json

Build prophet model for  store_36_dept_21
Build prophet model for  store_36_dept_26

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5mtb339_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=35113', 'data', 'file=/tmp/tmpjd45me00/002msgf9.json', 'init=/tmp/tmpjd45me00/5mtb339_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelvyrm_hgy/prophet_model-20260803145122.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:22 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:23 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0qvzz3th.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/cbfmpchb.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=19404', 'data', 'file=/tmp/tmpjd45me00/0qvzz3th.json', 'init=/tmp/tmpjd45me00/cbfmpchb.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model2vgjua_3/prophet_model-20260803145123.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:23 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:23 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_36_dept_3

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/43b65pim.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/cvlhgz1b.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=10366', 'data', 'file=/tmp/tmpjd45me00/43b65pim.json', 'init=/tmp/tmpjd45me00/cvlhgz1b.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelqulroycd/prophet_model-20260803145123.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:23 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:23 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/sekn3q2s.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/d89i2j78.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=10756', 'data', 'file=/tmp/tmpjd45me00/sekn3q2s.json', 'init=/tmp/tmpjd45me00/d89i2j78.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelo7wlqqfb/prophet_model-20260803145123.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:23 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_36_dept_38
Build prophet model for  store_36_dept_4

14:51:23 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/i5eoke53.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zevc0hqa.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=34272', 'data', 'file=/tmp/tmpjd45me00/i5eoke53.json', 'init=/tmp/tmpjd45me00/zevc0hqa.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelxwbvszmm/prophet_model-20260803145123.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:23 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:24 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_36_dept_40

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/h3h1_vz5.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mi5o6k8o.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=17459', 'data', 'file=/tmp/tmpjd45me00/h3h1_vz5.json', 'init=/tmp/tmpjd45me00/mi5o6k8o.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeln8ywb5u4/prophet_model-20260803145124.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:24 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:24 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_36_dept_46

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/w01ibe6b.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/f2d9wspw.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=67364', 'data', 'file=/tmp/tmpjd45me00/w01ibe6b.json', 'init=/tmp/tmpjd45me00/f2d9wspw.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelxnwb4kvc/prophet_model-20260803145124.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:24 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:24 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_36_dept_55
Skip  store_36_dept_55 due to lack of data
Build prophet model for  store_36_dept_59
Skip  store_36_dept_59 due to lack of data
Build prophet model for  store_36_dept_60
Build prophet model for  store_36_dept_67

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/78mgcwv0.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/f7xrns41.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=83793', 'data', 'file=/tmp/tmpjd45me00/78mgcwv0.json', 'init=/tmp/tmpjd45me00/f7xrns41.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model98u8inyp/prophet_model-20260803145124.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:24 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:24 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/j9qw70p_.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/20vlm7cr.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=57429', 'data', 'file=/tmp/tmpjd45me00/j9qw70p_.json', 'init=/tmp/tmpjd45me00/20vlm7cr.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelop0fph70/prophet_model-20260803145124.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:24 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:24 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_36_dept_7

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/efdyfvfz.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/uk9vn6uf.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=32038', 'data', 'file=/tmp/tmpjd45me00/efdyfvfz.json', 'init=/tmp/tmpjd45me00/uk9vn6uf.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelu2kz07th/prophet_model-20260803145125.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:25 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:25 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/q6bf_evu.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qxi2of_k.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=34745', 'data', 'file=/tmp/tmpjd45me00/q6bf_evu.json', 'init=/tmp/tmpjd45me00/qxi2of_k.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeln8zlcd2k/prophet_model-20260803145125.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:25 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_36_dept_74
Build prophet model for  store_36_dept_79

14:51:25 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fv1njdip.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/o9xm01mr.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=155', 'data', 'file=/tmp/tmpjd45me00/fv1njdip.json', 'init=/tmp/tmpjd45me00/o9xm01mr.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelgxpzgagj/prophet_model-20260803145125.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:25 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:25 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_36_dept_8

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/g7visxad.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/h7m8gto8.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=59955', 'data', 'file=/tmp/tmpjd45me00/g7visxad.json', 'init=/tmp/tmpjd45me00/h7m8gto8.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeltrih34on/prophet_model-20260803145125.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:25 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:25 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_36_dept_80

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/yvebv2wr.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/oq25tvns.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=46394', 'data', 'file=/tmp/tmpjd45me00/yvebv2wr.json', 'init=/tmp/tmpjd45me00/oq25tvns.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelb0gd_qo8/prophet_model-20260803145125.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:25 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:25 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_36_dept_81
Build prophet model for  store_36_dept_82

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/52c_hd8f.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/a841qna_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=82167', 'data', 'file=/tmp/tmpjd45me00/52c_hd8f.json', 'init=/tmp/tmpjd45me00/a841qna_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelosxl7qng/prophet_model-20260803145126.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:26 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:26 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/uw8wb10d.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7wgpnk7a.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=82343', 'data', 'file=/tmp/tmpjd45me00/uw8wb10d.json', 'init=/tmp/tmpjd45me00/7wgpnk7a.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model3n2nun_q/prophet_model-20260803145126.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:26 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:26 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3ibul82u.json

Build prophet model for  store_36_dept_83
Build prophet model for  store_36_dept_90

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/arh9o12j.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=99603', 'data', 'file=/tmp/tmpjd45me00/3ibul82u.json', 'init=/tmp/tmpjd45me00/arh9o12j.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelqg5r9d1k/prophet_model-20260803145126.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:26 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:26 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0zb761py.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/no2q9h7u.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=12028', 'data', 'file=/tmp/tmpjd45me00/0zb761py.json', 'init=/tmp/tmpjd45me00/no2q9h7u.json', 'output', 'file=/tmp/tmpjd45me00/prophet_models6rldj30/prophet_model-20260803145126.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:26 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:26 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_36_dept_91
Build prophet model for  store_36_dept_92

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wxxn2i92.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2k3z1vfc.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=40664', 'data', 'file=/tmp/tmpjd45me00/wxxn2i92.json', 'init=/tmp/tmpjd45me00/2k3z1vfc.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelk8ym489q/prophet_model-20260803145127.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:27 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:27 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rlswxzle.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1f5u3yxk.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=65335', 'data', 'file=/tmp/tmpjd45me00/rlswxzle.json', 'init=/tmp/tmpjd45me00/1f5u3yxk.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model90pcydg1/prophet_model-20260803145127.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:27 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:27 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_36_dept_93
Build prophet model for  store_36_dept_94

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wf5lw91m.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ruuez6c7.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=89121', 'data', 'file=/tmp/tmpjd45me00/wf5lw91m.json', 'init=/tmp/tmpjd45me00/ruuez6c7.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelsfk6jeww/prophet_model-20260803145127.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:27 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:27 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8n1ac32t.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3r3bkmh6.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=3328', 'data', 'file=/tmp/tmpjd45me00/8n1ac32t.json', 'init=/tmp/tmpjd45me00/3r3bkmh6.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelgmahylxq/prophet_model-20260803145127.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:27 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:27 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_36_dept_95

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/s02j3kl1.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4rkptuge.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=56335', 'data', 'file=/tmp/tmpjd45me00/s02j3kl1.json', 'init=/tmp/tmpjd45me00/4rkptuge.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model9olk9iyh/prophet_model-20260803145127.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:27 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:28 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_36_dept_96
Build prophet model for  store_36_dept_97

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0cnk12ba.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/h8gjju4j.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=4231', 'data', 'file=/tmp/tmpjd45me00/0cnk12ba.json', 'init=/tmp/tmpjd45me00/h8gjju4j.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelxmxmmhl3/prophet_model-20260803145128.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:28 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:28 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pbci7dcw.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/te4p3l7m.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=18725', 'data', 'file=/tmp/tmpjd45me00/pbci7dcw.json', 'init=/tmp/tmpjd45me00/te4p3l7m.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelgn2apugb/prophet_model-20260803145128.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:28 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:29 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0o2q48tu.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rulpow2u.json
DEBUG:cmdstanpy:idx 0

Build prophet model for  store_36_dept_98
Build prophet model for  store_37_dept_1

DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=96688', 'data', 'file=/tmp/tmpjd45me00/0o2q48tu.json', 'init=/tmp/tmpjd45me00/rulpow2u.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelg0aju_hh/prophet_model-20260803145129.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:29 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:29 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5rcem4fl.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ci1sr5l0.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=12810', 'data', 'file=/tmp/tmpjd45me00/5rcem4fl.json', 'init=/tmp/tmpjd45me00/ci1sr5l0.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelphcorcbm/prophet_model-20260803145129.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:29 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:29 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_37_dept_10
Build prophet model for  store_37_dept_11

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ssf8c12v.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jt1diy19.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=98442', 'data', 'file=/tmp/tmpjd45me00/ssf8c12v.json', 'init=/tmp/tmpjd45me00/jt1diy19.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelabqm15zu/prophet_model-20260803145129.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:29 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:29 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3u5zzggd.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gymcvlpq.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=15164', 'data', 'file=/tmp/tmpjd45me00/3u5zzggd.json', 'init=/tmp/tmpjd45me00/gymcvlpq.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_ygpbkh2/prophet_model-20260803145129.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:29 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:29 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_37_dept_12
Build prophet model for  store_37_dept_13

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/kry28rf9.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/z1w0jmr0.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=4839', 'data', 'file=/tmp/tmpjd45me00/kry28rf9.json', 'init=/tmp/tmpjd45me00/z1w0jmr0.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelv1czriuk/prophet_model-20260803145129.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:29 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:30 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/i2f281_q.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4h54s37m.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=24145', 'data', 'file=/tmp/tmpjd45me00/i2f281_q.json', 'init=/tmp/tmpjd45me00/4h54s37m.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelpr60zz_w/prophet_model-20260803145130.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:30 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:30 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/khrooiyv.json

Build prophet model for  store_37_dept_14
Build prophet model for  store_37_dept_16

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/24tkym7y.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=8071', 'data', 'file=/tmp/tmpjd45me00/khrooiyv.json', 'init=/tmp/tmpjd45me00/24tkym7y.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_j0dz7hw/prophet_model-20260803145130.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:30 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:30 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/q4zn__mq.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/n1hqeyo6.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=70720', 'data', 'file=/tmp/tmpjd45me00/q4zn__mq.json', 'init=/tmp/tmpjd45me00/n1hqeyo6.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelta897f1k/prophet_model-20260803145130.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:30 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_37_dept_17

14:51:30 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/z8m8z1uy.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/j0nrkgvu.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=67493', 'data', 'file=/tmp/tmpjd45me00/z8m8z1uy.json', 'init=/tmp/tmpjd45me00/j0nrkgvu.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model6o08boym/prophet_model-20260803145130.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:51:30 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_37_dept_18

14:51:32 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8_lzfsr9.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/btw5mq4e.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=12913', 'data', 'file=/tmp/tmpjd45me00/8_lzfsr9.json', 'init=/tmp/tmpjd45me00/btw5mq4e.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model4xr5mvs0/prophet_model-20260803145132.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:32 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:32 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_37_dept_2

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/v5m7rhsl.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/cndhzvao.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=62432', 'data', 'file=/tmp/tmpjd45me00/v5m7rhsl.json', 'init=/tmp/tmpjd45me00/cndhzvao.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model0ev6n6o0/prophet_model-20260803145132.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:32 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:32 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_37_dept_21

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wbbcx_ja.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/krn3e33p.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=97545', 'data', 'file=/tmp/tmpjd45me00/wbbcx_ja.json', 'init=/tmp/tmpjd45me00/krn3e33p.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelolrquxy8/prophet_model-20260803145132.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:32 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:32 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_37_dept_25

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4xxmscfg.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3vtxee_j.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=18129', 'data', 'file=/tmp/tmpjd45me00/4xxmscfg.json', 'init=/tmp/tmpjd45me00/3vtxee_j.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modela0urgor2/prophet_model-20260803145133.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:33 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_37_dept_28

14:51:33 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1ag1y4_t.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/nxyz2n8r.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=42850', 'data', 'file=/tmp/tmpjd45me00/1ag1y4_t.json', 'init=/tmp/tmpjd45me00/nxyz2n8r.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelq9ts1z8b/prophet_model-20260803145133.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:33 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_37_dept_3

14:51:33 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/anndvwc7.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vkw5gwu9.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=31823', 'data', 'file=/tmp/tmpjd45me00/anndvwc7.json', 'init=/tmp/tmpjd45me00/vkw5gwu9.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model9kckvpmo/prophet_model-20260803145133.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:33 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:33 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_37_dept_31

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wi5mnx76.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/movqyhn0.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=93067', 'data', 'file=/tmp/tmpjd45me00/wi5mnx76.json', 'init=/tmp/tmpjd45me00/movqyhn0.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelvwvlr74s/prophet_model-20260803145134.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:34 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_37_dept_38

14:51:34 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mbvnfsko.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/d9rzazsu.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=10857', 'data', 'file=/tmp/tmpjd45me00/mbvnfsko.json', 'init=/tmp/tmpjd45me00/d9rzazsu.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelfempq6xy/prophet_model-20260803145134.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:34 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:34 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_37_dept_4

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/114oeg3f.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rlfrndph.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=60913', 'data', 'file=/tmp/tmpjd45me00/114oeg3f.json', 'init=/tmp/tmpjd45me00/rlfrndph.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model7tlrv4r1/prophet_model-20260803145134.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:34 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_37_dept_40

14:51:34 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/g4tat0gi.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/otiltri_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=29786', 'data', 'file=/tmp/tmpjd45me00/g4tat0gi.json', 'init=/tmp/tmpjd45me00/otiltri_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelf9g9_dsp/prophet_model-20260803145135.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:35 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:35 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/nzl28tif.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/yvp8c62z.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=50010', 'data', 'file=/tmp/tmpjd45me00/nzl28tif.json', 'init=/tmp/tmpjd45me00/yvp8c62z.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelp0sfp2yv/prophet_model-20260803145135.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:35 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_37_dept_42
Build prophet model for  store_37_dept_46

14:51:35 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hhqvkzqi.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ij7zh0ob.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=83791', 'data', 'file=/tmp/tmpjd45me00/hhqvkzqi.json', 'init=/tmp/tmpjd45me00/ij7zh0ob.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelb59ignr2/prophet_model-20260803145135.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:35 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:35 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bd59j7y6.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ked_yt79.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=55897', 'data', 'file=/tmp/tmpjd45me00/bd59j7y6.json', 'init=/tmp/tmpjd45me00/ked_yt79.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelchg0ch0r/prophet_model-20260803145135.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:35 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_37_dept_5
Build prophet model for  store_37_dept_52

14:51:35 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ltst7s5k.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vwgpjqzi.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=11879', 'data', 'file=/tmp/tmpjd45me00/ltst7s5k.json', 'init=/tmp/tmpjd45me00/vwgpjqzi.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeljkwyf0tn/prophet_model-20260803145135.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:35 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_37_dept_59

14:51:35 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ivjcj8c9.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1p6655y7.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=58609', 'data', 'file=/tmp/tmpjd45me00/ivjcj8c9.json', 'init=/tmp/tmpjd45me00/1p6655y7.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelx3cux52t/prophet_model-20260803145136.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:36 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:36 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gv7f9vxw.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/j5on0bvf.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=57484', 'data', 'file=/tmp/tmpjd45me00/gv7f9vxw.json', 'init=/tmp/tmpjd45me00/j5on0bvf.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelgxs67qld/prophet_model-20260803145136.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:36 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_37_dept_6
Build prophet model for  store_37_dept_60

14:51:36 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/irvm19n0.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/grk7r0uh.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=71219', 'data', 'file=/tmp/tmpjd45me00/irvm19n0.json', 'init=/tmp/tmpjd45me00/grk7r0uh.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model7rnsebaj/prophet_model-20260803145136.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:36 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:36 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6zkw51i8.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8kl9dkh6.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=12153', 'data', 'file=/tmp/tmpjd45me00/6zkw51i8.json', 'init=/tmp/tmpjd45me00/8kl9dkh6.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model565bs0xq/prophet_model-20260803145136.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:36 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_37_dept_67
Build prophet model for  store_37_dept_7

14:51:36 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1w7o7wfp.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vcbfpj78.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=16656', 'data', 'file=/tmp/tmpjd45me00/1w7o7wfp.json', 'init=/tmp/tmpjd45me00/vcbfpj78.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model8s7sxsl2/prophet_model-20260803145136.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:36 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:36 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/oti3jgm3.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ih7qv48z.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=77826', 'data', 'file=/tmp/tmpjd45me00/oti3jgm3.json', 'init=/tmp/tmpjd45me00/ih7qv48z.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeljy512c4f/prophet_model-20260803145136.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:36 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_37_dept_72
Build prophet model for  store_37_dept_74

14:51:36 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hujaucph.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qjz9fpvf.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=91214', 'data', 'file=/tmp/tmpjd45me00/hujaucph.json', 'init=/tmp/tmpjd45me00/qjz9fpvf.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelib0w3zzv/prophet_model-20260803145137.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:37 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:37 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/c3cel7qk.json

Build prophet model for  store_37_dept_79
Build prophet model for  store_37_dept_8

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_faudiny.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=21687', 'data', 'file=/tmp/tmpjd45me00/c3cel7qk.json', 'init=/tmp/tmpjd45me00/_faudiny.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelzw304qao/prophet_model-20260803145137.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:37 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:37 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/uhyqsz8q.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0v02athd.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=88591', 'data', 'file=/tmp/tmpjd45me00/uhyqsz8q.json', 'init=/tmp/tmpjd45me00/0v02athd.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelhmhwq2cj/prophet_model-20260803145137.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:37 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:37 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_37_dept_80

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wxfz8xem.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1v_2khi0.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=62609', 'data', 'file=/tmp/tmpjd45me00/wxfz8xem.json', 'init=/tmp/tmpjd45me00/1v_2khi0.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model8cv6rc4y/prophet_model-20260803145137.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:37 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:37 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_37_dept_81
Build prophet model for  store_37_dept_82

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/btir0vv1.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/s23igqy6.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=55880', 'data', 'file=/tmp/tmpjd45me00/btir0vv1.json', 'init=/tmp/tmpjd45me00/s23igqy6.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelt7m0mivp/prophet_model-20260803145137.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:37 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:37 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7ilc26xm.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4frcsxuf.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=30694', 'data', 'file=/tmp/tmpjd45me00/7ilc26xm.json', 'init=/tmp/tmpjd45me00/4frcsxuf.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model33boa7xd/prophet_model-20260803145138.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:38 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:38 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2wx5kw5p.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/yknkyur4.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=14240', 'data', 'file=/tmp/tmpjd45me00/2wx5kw5p.json', 'init=/tmp/tmpjd45me00/yknkyur4.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelij2hl08j/prophet_model-20260803145138.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']

Build prophet model for  store_37_dept_83
Build prophet model for  store_37_dept_85

14:51:38 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:38 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2o43e6jv.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/txdjnegz.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=70222', 'data', 'file=/tmp/tmpjd45me00/2o43e6jv.json', 'init=/tmp/tmpjd45me00/txdjnegz.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelk4efzpl4/prophet_model-20260803145138.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:38 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:38 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2szabmg2.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7ftu3tg6.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=63797', 'data', 'file=/tmp/tmpjd45me00/2szabmg2.json', 'init=/tmp/tmpjd45me00/7ftu3tg6.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelxs9xkxd4/prophet_model-20260803145138.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:38 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_37_dept_87
Build prophet model for  store_37_dept_9

14:51:38 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/53ckayj2.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/o2d6bfys.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=67339', 'data', 'file=/tmp/tmpjd45me00/53ckayj2.json', 'init=/tmp/tmpjd45me00/o2d6bfys.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelj3y3jycq/prophet_model-20260803145138.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:38 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:38 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_dmxhj9v.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zw3jv15f.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=51757', 'data', 'file=/tmp/tmpjd45me00/_dmxhj9v.json', 'init=/tmp/tmpjd45me00/zw3jv15f.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model2zolejeo/prophet_model-20260803145138.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:38 - cmdstanpy - INFO - Chain [1] start processing

Build prophet model for  store_37_dept_90
Build prophet model for  store_37_dept_91

INFO:cmdstanpy:Chain [1] start processing
14:51:38 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2jhmlf63.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wsld92fp.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=99505', 'data', 'file=/tmp/tmpjd45me00/2jhmlf63.json', 'init=/tmp/tmpjd45me00/wsld92fp.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model68c7qkma/prophet_model-20260803145139.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:39 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:39 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2_xufhxk.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/kk70osnq.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=25735', 'data', 'file=/tmp/tmpjd45me00/2_xufhxk.json', 'init=/tmp/tmpjd45me00/kk70osnq.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model4ucp4jkw/prophet_model-20260803145139.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']

Build prophet model for  store_37_dept_92
Build prophet model for  store_37_dept_93

14:51:39 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:39 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/d6xb9bjl.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pk_5umhc.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=57473', 'data', 'file=/tmp/tmpjd45me00/d6xb9bjl.json', 'init=/tmp/tmpjd45me00/pk_5umhc.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelb3dtol8t/prophet_model-20260803145139.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:39 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:39 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_37_dept_94

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/41h95ky8.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0ysarck1.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=13346', 'data', 'file=/tmp/tmpjd45me00/41h95ky8.json', 'init=/tmp/tmpjd45me00/0ysarck1.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelgw3hn054/prophet_model-20260803145139.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:39 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:39 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2dcpvgcd.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zpx6rpwt.json

Build prophet model for  store_37_dept_95
Build prophet model for  store_37_dept_96

DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=89394', 'data', 'file=/tmp/tmpjd45me00/2dcpvgcd.json', 'init=/tmp/tmpjd45me00/zpx6rpwt.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelo8d1qav5/prophet_model-20260803145139.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:39 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:39 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/x3gmb0k9.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xj5uronj.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=70622', 'data', 'file=/tmp/tmpjd45me00/x3gmb0k9.json', 'init=/tmp/tmpjd45me00/xj5uronj.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelsz04p_9w/prophet_model-20260803145139.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:39 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:39 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_37_dept_97
Build prophet model for  store_37_dept_98

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mzoymfu_.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4g1_4mzk.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=78045', 'data', 'file=/tmp/tmpjd45me00/mzoymfu_.json', 'init=/tmp/tmpjd45me00/4g1_4mzk.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model9l9wjq0y/prophet_model-20260803145140.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:40 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:40 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/kwrm24q0.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2wwfs21w.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=36929', 'data', 'file=/tmp/tmpjd45me00/kwrm24q0.json', 'init=/tmp/tmpjd45me00/2wwfs21w.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelupie66dx/prophet_model-20260803145140.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:40 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:40 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/q3qioqrl.json

Build prophet model for  store_38_dept_1
Build prophet model for  store_38_dept_10

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mj4w8spg.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=46855', 'data', 'file=/tmp/tmpjd45me00/q3qioqrl.json', 'init=/tmp/tmpjd45me00/mj4w8spg.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelehvr0j6i/prophet_model-20260803145140.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:40 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:40 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/d6gnsn1l.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2azgfq1w.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=66228', 'data', 'file=/tmp/tmpjd45me00/d6gnsn1l.json', 'init=/tmp/tmpjd45me00/2azgfq1w.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelm14_q8jr/prophet_model-20260803145140.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:40 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:40 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gmjyr0x3.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fm9tr317.json

Build prophet model for  store_38_dept_11
Build prophet model for  store_38_dept_12

DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=88544', 'data', 'file=/tmp/tmpjd45me00/gmjyr0x3.json', 'init=/tmp/tmpjd45me00/fm9tr317.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model37rnuxz6/prophet_model-20260803145140.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:40 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:40 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/g6rnh2w2.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bmoc4bzb.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=71909', 'data', 'file=/tmp/tmpjd45me00/g6rnh2w2.json', 'init=/tmp/tmpjd45me00/bmoc4bzb.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelcc1417mu/prophet_model-20260803145141.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:41 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:41 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_38_dept_13

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/k7mhj4z8.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6hbdkn91.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=56143', 'data', 'file=/tmp/tmpjd45me00/k7mhj4z8.json', 'init=/tmp/tmpjd45me00/6hbdkn91.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model3w294c09/prophet_model-20260803145141.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:41 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_38_dept_14

14:51:41 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xg0fl0gr.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ytl587zn.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=62088', 'data', 'file=/tmp/tmpjd45me00/xg0fl0gr.json', 'init=/tmp/tmpjd45me00/ytl587zn.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_unyd5l5/prophet_model-20260803145141.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:41 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:41 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wsmdkpwd.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/du9gl7_h.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=96987', 'data', 'file=/tmp/tmpjd45me00/wsmdkpwd.json', 'init=/tmp/tmpjd45me00/du9gl7_h.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelkzindmym/prophet_model-20260803145141.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:41 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_38_dept_16
Build prophet model for  store_38_dept_17

14:51:42 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ij6zuryw.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/afycszfs.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=40272', 'data', 'file=/tmp/tmpjd45me00/ij6zuryw.json', 'init=/tmp/tmpjd45me00/afycszfs.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelfkw9t655/prophet_model-20260803145142.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:51:42 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_38_dept_18

14:51:43 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ji8w385t.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4jiqw8nt.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=66986', 'data', 'file=/tmp/tmpjd45me00/ji8w385t.json', 'init=/tmp/tmpjd45me00/4jiqw8nt.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeldsawn7qb/prophet_model-20260803145143.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:43 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:43 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fziljl18.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/v1etu1za.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=7084', 'data', 'file=/tmp/tmpjd45me00/fziljl18.json', 'init=/tmp/tmpjd45me00/v1etu1za.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelfain7gdj/prophet_model-20260803145143.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']

Build prophet model for  store_38_dept_2
Build prophet model for  store_38_dept_21

14:51:43 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:43 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2emph_2b.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2f0f6wo2.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=62721', 'data', 'file=/tmp/tmpjd45me00/2emph_2b.json', 'init=/tmp/tmpjd45me00/2f0f6wo2.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelx0x1ua7n/prophet_model-20260803145143.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:43 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:43 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_38_dept_25

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/on49g_6f.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fppt32l4.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=18196', 'data', 'file=/tmp/tmpjd45me00/on49g_6f.json', 'init=/tmp/tmpjd45me00/fppt32l4.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelytlfq8on/prophet_model-20260803145143.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:43 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:43 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9zspgfkz.json

Build prophet model for  store_38_dept_28
Build prophet model for  store_38_dept_3

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/61pv1rez.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=75861', 'data', 'file=/tmp/tmpjd45me00/9zspgfkz.json', 'init=/tmp/tmpjd45me00/61pv1rez.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelphb9nunv/prophet_model-20260803145144.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:44 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:44 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pt1m1ohk.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/99np7bua.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=10981', 'data', 'file=/tmp/tmpjd45me00/pt1m1ohk.json', 'init=/tmp/tmpjd45me00/99np7bua.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelb1etrqeg/prophet_model-20260803145144.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:44 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:44 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4koyos0m.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/794onqpl.json

Build prophet model for  store_38_dept_38
Build prophet model for  store_38_dept_4

DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=83202', 'data', 'file=/tmp/tmpjd45me00/4koyos0m.json', 'init=/tmp/tmpjd45me00/794onqpl.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model06ume1l5/prophet_model-20260803145144.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:44 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:44 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/oyxrjtl1.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/sfrsjl_c.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=35003', 'data', 'file=/tmp/tmpjd45me00/oyxrjtl1.json', 'init=/tmp/tmpjd45me00/sfrsjl_c.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelxg_jtu1y/prophet_model-20260803145144.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:44 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:44 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_38_dept_40
Build prophet model for  store_38_dept_42

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/lfyr1001.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/nndvqrk_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=82115', 'data', 'file=/tmp/tmpjd45me00/lfyr1001.json', 'init=/tmp/tmpjd45me00/nndvqrk_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model12sygvx5/prophet_model-20260803145144.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:44 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:45 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ei6tqdsy.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ndpw0nb1.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=30571', 'data', 'file=/tmp/tmpjd45me00/ei6tqdsy.json', 'init=/tmp/tmpjd45me00/ndpw0nb1.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelavk7csf5/prophet_model-20260803145145.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:45 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_38_dept_46

14:51:45 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/w307npvu.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/yi7u8ppr.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=42449', 'data', 'file=/tmp/tmpjd45me00/w307npvu.json', 'init=/tmp/tmpjd45me00/yi7u8ppr.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelue70kvnv/prophet_model-20260803145145.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:45 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_38_dept_5

14:51:45 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/nfbaeazv.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ani26pjo.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=92698', 'data', 'file=/tmp/tmpjd45me00/nfbaeazv.json', 'init=/tmp/tmpjd45me00/ani26pjo.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modely6z0b7no/prophet_model-20260803145146.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:46 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:46 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_38_dept_52

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hj1mszcv.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8zb93rx3.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=90709', 'data', 'file=/tmp/tmpjd45me00/hj1mszcv.json', 'init=/tmp/tmpjd45me00/8zb93rx3.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model6bl99t92/prophet_model-20260803145146.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:46 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_38_dept_59

14:51:46 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6unz0zvx.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qe90ca05.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=67702', 'data', 'file=/tmp/tmpjd45me00/6unz0zvx.json', 'init=/tmp/tmpjd45me00/qe90ca05.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model1nadmu47/prophet_model-20260803145146.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:46 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:46 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_38_dept_6

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ca252dcs.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pmoivz7b.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=34590', 'data', 'file=/tmp/tmpjd45me00/ca252dcs.json', 'init=/tmp/tmpjd45me00/pmoivz7b.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model7g_3of_d/prophet_model-20260803145147.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:47 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:47 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_38_dept_60

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4_e0m8f9.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/p_0vts_k.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=48805', 'data', 'file=/tmp/tmpjd45me00/4_e0m8f9.json', 'init=/tmp/tmpjd45me00/p_0vts_k.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelnpr7xn3b/prophet_model-20260803145147.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:47 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:47 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_38_dept_67
Build prophet model for  store_38_dept_7

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4i4uw14n.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/atw2d84a.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=47949', 'data', 'file=/tmp/tmpjd45me00/4i4uw14n.json', 'init=/tmp/tmpjd45me00/atw2d84a.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelsv17wfww/prophet_model-20260803145147.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:47 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:47 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/u2o791rq.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/035c39qe.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=36322', 'data', 'file=/tmp/tmpjd45me00/u2o791rq.json', 'init=/tmp/tmpjd45me00/035c39qe.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model3pcq7ppr/prophet_model-20260803145147.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:47 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:47 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_38_dept_72

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ttqndenm.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/03bggtv2.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=3574', 'data', 'file=/tmp/tmpjd45me00/ttqndenm.json', 'init=/tmp/tmpjd45me00/03bggtv2.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelmwzqecjk/prophet_model-20260803145147.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:47 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:48 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_38_dept_74

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qsaomd7g.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/d1onzu06.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=48770', 'data', 'file=/tmp/tmpjd45me00/qsaomd7g.json', 'init=/tmp/tmpjd45me00/d1onzu06.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelnc7htewt/prophet_model-20260803145148.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:48 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:48 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/liooybrx.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7_todrrr.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=24733', 'data', 'file=/tmp/tmpjd45me00/liooybrx.json', 'init=/tmp/tmpjd45me00/7_todrrr.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelc4ogjqm7/prophet_model-20260803145148.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:48 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_38_dept_79
Build prophet model for  store_38_dept_8

14:51:48 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/37l_ee3d.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vqxg4yct.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=13741', 'data', 'file=/tmp/tmpjd45me00/37l_ee3d.json', 'init=/tmp/tmpjd45me00/vqxg4yct.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model6i80225g/prophet_model-20260803145148.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:48 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:48 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4sl58op0.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/aapyxldy.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=14424', 'data', 'file=/tmp/tmpjd45me00/4sl58op0.json', 'init=/tmp/tmpjd45me00/aapyxldy.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model9mipv93_/prophet_model-20260803145148.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:48 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_38_dept_80
Build prophet model for  store_38_dept_81

14:51:48 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/tdoo73tc.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hxswoezg.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=30696', 'data', 'file=/tmp/tmpjd45me00/tdoo73tc.json', 'init=/tmp/tmpjd45me00/hxswoezg.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelcy7ytyed/prophet_model-20260803145148.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:48 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:48 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/iiyp1b1z.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/w1wr42nx.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=94992', 'data', 'file=/tmp/tmpjd45me00/iiyp1b1z.json', 'init=/tmp/tmpjd45me00/w1wr42nx.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model5ijtg6pi/prophet_model-20260803145149.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:49 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_38_dept_82
Build prophet model for  store_38_dept_83

14:51:49 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hrpwpxc4.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4sojhvvy.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=29514', 'data', 'file=/tmp/tmpjd45me00/hrpwpxc4.json', 'init=/tmp/tmpjd45me00/4sojhvvy.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelthaup7bp/prophet_model-20260803145149.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:49 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:49 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rg0ecn9r.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/03j2hyu4.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=53611', 'data', 'file=/tmp/tmpjd45me00/rg0ecn9r.json', 'init=/tmp/tmpjd45me00/03j2hyu4.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modellkvwiwan/prophet_model-20260803145149.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:49 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_38_dept_85
Build prophet model for  store_38_dept_87

14:51:49 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bh7c3z6y.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2c5d4i0c.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=35608', 'data', 'file=/tmp/tmpjd45me00/bh7c3z6y.json', 'init=/tmp/tmpjd45me00/2c5d4i0c.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeltg4m2zzn/prophet_model-20260803145149.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:49 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:49 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2tpf4bi_.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/msrmotnc.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=53001', 'data', 'file=/tmp/tmpjd45me00/2tpf4bi_.json', 'init=/tmp/tmpjd45me00/msrmotnc.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeloc2cf_2z/prophet_model-20260803145149.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:49 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_38_dept_9
Build prophet model for  store_38_dept_90

14:51:49 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/a3r7bho8.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/sn3j5ilk.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=59686', 'data', 'file=/tmp/tmpjd45me00/a3r7bho8.json', 'init=/tmp/tmpjd45me00/sn3j5ilk.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelbng8rpzx/prophet_model-20260803145149.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:49 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:49 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/eyxd4z3m.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/sb15f8o0.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=39515', 'data', 'file=/tmp/tmpjd45me00/eyxd4z3m.json', 'init=/tmp/tmpjd45me00/sb15f8o0.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelg8ngdwqt/prophet_model-20260803145150.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:50 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:50 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_38_dept_91
Build prophet model for  store_38_dept_92

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6kwa86a2.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/uzaagkr7.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=16548', 'data', 'file=/tmp/tmpjd45me00/6kwa86a2.json', 'init=/tmp/tmpjd45me00/uzaagkr7.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_68ft836/prophet_model-20260803145150.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:50 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:50 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5sscfnrg.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pbj17muh.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=13463', 'data', 'file=/tmp/tmpjd45me00/5sscfnrg.json', 'init=/tmp/tmpjd45me00/pbj17muh.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelr8ojgkja/prophet_model-20260803145150.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:50 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_38_dept_93
Build prophet model for  store_38_dept_94

14:51:50 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/n13g9rwc.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/q568w5yp.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=27777', 'data', 'file=/tmp/tmpjd45me00/n13g9rwc.json', 'init=/tmp/tmpjd45me00/q568w5yp.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelrr5nno_s/prophet_model-20260803145150.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:50 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:50 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zcvhicd0.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gocl6sff.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=92818', 'data', 'file=/tmp/tmpjd45me00/zcvhicd0.json', 'init=/tmp/tmpjd45me00/gocl6sff.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelf4tc2jww/prophet_model-20260803145150.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:50 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_38_dept_95
Build prophet model for  store_38_dept_96

14:51:50 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/n6d7rfqs.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0f5mp8c5.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=24070', 'data', 'file=/tmp/tmpjd45me00/n6d7rfqs.json', 'init=/tmp/tmpjd45me00/0f5mp8c5.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model5bk5ta4y/prophet_model-20260803145150.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:50 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:50 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4y8zxkgr.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5al_9wa_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=50557', 'data', 'file=/tmp/tmpjd45me00/4y8zxkgr.json', 'init=/tmp/tmpjd45me00/5al_9wa_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_9_r9_mo/prophet_model-20260803145151.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:51 - cmdstanpy - INFO - Chain [1] start processing

Build prophet model for  store_38_dept_97
Build prophet model for  store_38_dept_98

INFO:cmdstanpy:Chain [1] start processing
14:51:51 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9yzwqxc9.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5wnw18vp.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=87119', 'data', 'file=/tmp/tmpjd45me00/9yzwqxc9.json', 'init=/tmp/tmpjd45me00/5wnw18vp.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeligzruv9e/prophet_model-20260803145151.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:51 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:51 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/cf53zrls.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/d9zep6bk.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=7030', 'data', 'file=/tmp/tmpjd45me00/cf53zrls.json', 'init=/tmp/tmpjd45me00/d9zep6bk.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeln0plh7ql/prophet_model-20260803145151.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:51 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_39_dept_1
Build prophet model for  store_39_dept_10

14:51:51 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dx5uoync.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2o2nesox.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=1158', 'data', 'file=/tmp/tmpjd45me00/dx5uoync.json', 'init=/tmp/tmpjd45me00/2o2nesox.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelvs6hzftl/prophet_model-20260803145151.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:51 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:51 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_39_dept_11
Build prophet model for  store_39_dept_12

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/a3ikzs1w.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ad_50xu9.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=56936', 'data', 'file=/tmp/tmpjd45me00/a3ikzs1w.json', 'init=/tmp/tmpjd45me00/ad_50xu9.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model4jyni3ld/prophet_model-20260803145151.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:51 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:51 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/evsyh2u4.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8uesmf7t.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=90570', 'data', 'file=/tmp/tmpjd45me00/evsyh2u4.json', 'init=/tmp/tmpjd45me00/8uesmf7t.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model3s19mriq/prophet_model-20260803145151.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:51 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:52 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_39_dept_13
Build prophet model for  store_39_dept_14

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/90sxbm88.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zj2iccru.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=60936', 'data', 'file=/tmp/tmpjd45me00/90sxbm88.json', 'init=/tmp/tmpjd45me00/zj2iccru.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeltt607wk1/prophet_model-20260803145152.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:52 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:52 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/19x9ipck.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/54hmkvsr.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=95034', 'data', 'file=/tmp/tmpjd45me00/19x9ipck.json', 'init=/tmp/tmpjd45me00/54hmkvsr.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelucwq37n2/prophet_model-20260803145152.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:52 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:52 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/yx4qpfdd.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4r7_gfqw.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=87978', 'data', 'file=/tmp/tmpjd45me00/yx4qpfdd.json', 'init=/tmp/tmpjd45me00/4r7_gfqw.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelhht0gxcs/prophet_model-20260803145152.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:52 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_39_dept_16
Build prophet model for  store_39_dept_17

14:51:52 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mstcbeh6.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/k3auxr36.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=26937', 'data', 'file=/tmp/tmpjd45me00/mstcbeh6.json', 'init=/tmp/tmpjd45me00/k3auxr36.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelpj8xri8k/prophet_model-20260803145152.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:52 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:52 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/a642kiol.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/38jd2m_r.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=69783', 'data', 'file=/tmp/tmpjd45me00/a642kiol.json', 'init=/tmp/tmpjd45me00/38jd2m_r.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelhxyn84bm/prophet_model-20260803145152.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:52 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_39_dept_18
Build prophet model for  store_39_dept_2

14:51:52 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3o86coye.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mz7hvyz7.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=1413', 'data', 'file=/tmp/tmpjd45me00/3o86coye.json', 'init=/tmp/tmpjd45me00/mz7hvyz7.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelotmtio0p/prophet_model-20260803145152.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:52 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:52 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/msdrsnyd.json

Build prophet model for  store_39_dept_20
Build prophet model for  store_39_dept_21

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gv1y2ngc.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=46556', 'data', 'file=/tmp/tmpjd45me00/msdrsnyd.json', 'init=/tmp/tmpjd45me00/gv1y2ngc.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelo9eicpml/prophet_model-20260803145153.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:53 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:53 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ev6hm3xy.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/kjydhl_d.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=26059', 'data', 'file=/tmp/tmpjd45me00/ev6hm3xy.json', 'init=/tmp/tmpjd45me00/kjydhl_d.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelkxxg0lqt/prophet_model-20260803145153.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:53 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:53 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/lk0i1oi5.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7qaz7cju.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=8093', 'data', 'file=/tmp/tmpjd45me00/lk0i1oi5.json', 'init=/tmp/tmpjd45me00/7qaz7cju.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model4l9w02wx/prophet_model-20260803145153.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:53 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_39_dept_22
Build prophet model for  store_39_dept_23

14:51:53 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4e2532th.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/40fx3shk.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=8167', 'data', 'file=/tmp/tmpjd45me00/4e2532th.json', 'init=/tmp/tmpjd45me00/40fx3shk.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model6n46jpod/prophet_model-20260803145153.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:53 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:53 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/q9e086cr.json

Build prophet model for  store_39_dept_24
Build prophet model for  store_39_dept_25

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2qajupsd.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=1787', 'data', 'file=/tmp/tmpjd45me00/q9e086cr.json', 'init=/tmp/tmpjd45me00/2qajupsd.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model443ptrvw/prophet_model-20260803145153.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:53 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:53 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/w25yv972.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/596vw7fx.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=86772', 'data', 'file=/tmp/tmpjd45me00/w25yv972.json', 'init=/tmp/tmpjd45me00/596vw7fx.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model4n7gg2ia/prophet_model-20260803145154.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:54 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:54 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/tlmh_87x.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_2eqzduf.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=37994', 'data', 'file=/tmp/tmpjd45me00/tlmh_87x.json', 'init=/tmp/tmpjd45me00/_2eqzduf.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelheh1e3ma/prophet_model-20260803145154.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:54 - cmdstanpy - INFO - Chain [1] start processing

Build prophet model for  store_39_dept_26
Build prophet model for  store_39_dept_27

INFO:cmdstanpy:Chain [1] start processing
14:51:54 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2c80u6ce.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5mx7nalt.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=62323', 'data', 'file=/tmp/tmpjd45me00/2c80u6ce.json', 'init=/tmp/tmpjd45me00/5mx7nalt.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelnmcm3dzg/prophet_model-20260803145154.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:54 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:54 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2ve2pskg.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zzswnu2s.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=36941', 'data', 'file=/tmp/tmpjd45me00/2ve2pskg.json', 'init=/tmp/tmpjd45me00/zzswnu2s.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelz5qxhit9/prophet_model-20260803145154.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:54 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_39_dept_28
Build prophet model for  store_39_dept_29

14:51:54 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9agz6hhq.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/b8jldnid.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=61236', 'data', 'file=/tmp/tmpjd45me00/9agz6hhq.json', 'init=/tmp/tmpjd45me00/b8jldnid.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model4po1zhj_/prophet_model-20260803145154.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:54 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:54 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gsjtp5qx.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9x8ulmix.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=75164', 'data', 'file=/tmp/tmpjd45me00/gsjtp5qx.json', 'init=/tmp/tmpjd45me00/9x8ulmix.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeli4_weub0/prophet_model-20260803145154.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:54 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_39_dept_3
Build prophet model for  store_39_dept_30

14:51:54 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pe18a_nm.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xz2qehgb.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=70465', 'data', 'file=/tmp/tmpjd45me00/pe18a_nm.json', 'init=/tmp/tmpjd45me00/xz2qehgb.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modele7pevp5a/prophet_model-20260803145154.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:54 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:55 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_39_dept_31
Build prophet model for  store_39_dept_32

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/91itc63y.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/v9cwn57t.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=59067', 'data', 'file=/tmp/tmpjd45me00/91itc63y.json', 'init=/tmp/tmpjd45me00/v9cwn57t.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelo2go7qgy/prophet_model-20260803145155.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:55 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:55 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wivnw8fi.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3gh2st27.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=27826', 'data', 'file=/tmp/tmpjd45me00/wivnw8fi.json', 'init=/tmp/tmpjd45me00/3gh2st27.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeleqm_uvv5/prophet_model-20260803145155.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:55 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:55 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8z5enq9w.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/l9mj2jex.json
DEBUG:cmdstanpy:idx 0

Build prophet model for  store_39_dept_33
Build prophet model for  store_39_dept_34

DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=89906', 'data', 'file=/tmp/tmpjd45me00/8z5enq9w.json', 'init=/tmp/tmpjd45me00/l9mj2jex.json', 'output', 'file=/tmp/tmpjd45me00/prophet_models47t087h/prophet_model-20260803145155.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:55 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:55 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/s4m7wtx0.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0huee2yf.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=24511', 'data', 'file=/tmp/tmpjd45me00/s4m7wtx0.json', 'init=/tmp/tmpjd45me00/0huee2yf.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelx_q0xib6/prophet_model-20260803145155.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:55 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:55 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/18umltor.json

Build prophet model for  store_39_dept_35
Build prophet model for  store_39_dept_36

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zafpfl93.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=833', 'data', 'file=/tmp/tmpjd45me00/18umltor.json', 'init=/tmp/tmpjd45me00/zafpfl93.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelqygbobw0/prophet_model-20260803145155.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:55 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:55 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/iwy3ez0z.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qva4tvuq.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=89070', 'data', 'file=/tmp/tmpjd45me00/iwy3ez0z.json', 'init=/tmp/tmpjd45me00/qva4tvuq.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelldiudhs5/prophet_model-20260803145156.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:56 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:56 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8o511wv5.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/488fkbrz.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=71995', 'data', 'file=/tmp/tmpjd45me00/8o511wv5.json', 'init=/tmp/tmpjd45me00/488fkbrz.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeldn2mwfbk/prophet_model-20260803145156.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:56 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_39_dept_38
Build prophet model for  store_39_dept_4

14:51:56 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mildn8r2.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/u3_k_sus.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=62420', 'data', 'file=/tmp/tmpjd45me00/mildn8r2.json', 'init=/tmp/tmpjd45me00/u3_k_sus.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelihkp7of5/prophet_model-20260803145156.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:56 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:56 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_39_dept_40

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/col9hmm9.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/cxtafmmd.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=35770', 'data', 'file=/tmp/tmpjd45me00/col9hmm9.json', 'init=/tmp/tmpjd45me00/cxtafmmd.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelh4cdf1i5/prophet_model-20260803145156.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:56 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:56 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_39_dept_41

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/n094nrfv.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1pswjfbm.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=49589', 'data', 'file=/tmp/tmpjd45me00/n094nrfv.json', 'init=/tmp/tmpjd45me00/1pswjfbm.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeltdqaw1ct/prophet_model-20260803145156.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:56 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:57 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_39_dept_42

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/k26lizub.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qlk91z2t.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=26040', 'data', 'file=/tmp/tmpjd45me00/k26lizub.json', 'init=/tmp/tmpjd45me00/qlk91z2t.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelp74ph_vz/prophet_model-20260803145157.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:57 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:57 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/sen7kv95.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/tyr17yba.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=92568', 'data', 'file=/tmp/tmpjd45me00/sen7kv95.json', 'init=/tmp/tmpjd45me00/tyr17yba.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model2kuwgd61/prophet_model-20260803145157.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:57 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_39_dept_44
Build prophet model for  store_39_dept_46

14:51:57 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1bkh7iah.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/u43sehw_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=16051', 'data', 'file=/tmp/tmpjd45me00/1bkh7iah.json', 'init=/tmp/tmpjd45me00/u43sehw_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model6g6e2y6c/prophet_model-20260803145157.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:57 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:57 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dq5lkli5.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/12lnp9mn.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=15757', 'data', 'file=/tmp/tmpjd45me00/dq5lkli5.json', 'init=/tmp/tmpjd45me00/12lnp9mn.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model830f2yam/prophet_model-20260803145157.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:57 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_39_dept_49
Build prophet model for  store_39_dept_5

14:51:57 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qx_l2ezn.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/d4shmlj7.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=48722', 'data', 'file=/tmp/tmpjd45me00/qx_l2ezn.json', 'init=/tmp/tmpjd45me00/d4shmlj7.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelznw0avqe/prophet_model-20260803145157.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:57 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:57 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_39_dept_52
Build prophet model for  store_39_dept_54

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dluw7ifz.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rx2c8hd4.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=89163', 'data', 'file=/tmp/tmpjd45me00/dluw7ifz.json', 'init=/tmp/tmpjd45me00/rx2c8hd4.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelrs_j8kf9/prophet_model-20260803145158.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:58 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:58 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ed8lvpka.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4c1qsifx.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=81591', 'data', 'file=/tmp/tmpjd45me00/ed8lvpka.json', 'init=/tmp/tmpjd45me00/4c1qsifx.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeljmn0c2p2/prophet_model-20260803145158.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:58 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:58 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_39_dept_55
Build prophet model for  store_39_dept_56

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ojk_bwi2.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/m18gtw4q.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=11604', 'data', 'file=/tmp/tmpjd45me00/ojk_bwi2.json', 'init=/tmp/tmpjd45me00/m18gtw4q.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeloez1styd/prophet_model-20260803145158.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:58 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:51:58 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9mdk4uzn.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bjgrq_lh.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=12974', 'data', 'file=/tmp/tmpjd45me00/9mdk4uzn.json', 'init=/tmp/tmpjd45me00/bjgrq_lh.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model3lt00uhw/prophet_model-20260803145158.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:58 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_39_dept_58

14:51:59 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bnpx7p96.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/u727639n.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=66196', 'data', 'file=/tmp/tmpjd45me00/bnpx7p96.json', 'init=/tmp/tmpjd45me00/u727639n.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model3w79g3aa/prophet_model-20260803145159.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:59 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_39_dept_59

14:51:59 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/t5wpj7df.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wmyzeqio.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=17485', 'data', 'file=/tmp/tmpjd45me00/t5wpj7df.json', 'init=/tmp/tmpjd45me00/wmyzeqio.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model67cmscw9/prophet_model-20260803145159.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:51:59 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_39_dept_6

14:52:00 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mve62j5b.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/f719dj9_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=68154', 'data', 'file=/tmp/tmpjd45me00/mve62j5b.json', 'init=/tmp/tmpjd45me00/f719dj9_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeluenn9hp_/prophet_model-20260803145200.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:00 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:00 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_39_dept_67

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dq_5to6d.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qb1wx13b.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=60723', 'data', 'file=/tmp/tmpjd45me00/dq_5to6d.json', 'init=/tmp/tmpjd45me00/qb1wx13b.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model29c5e4t4/prophet_model-20260803145200.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:00 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:00 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3yo9cuj8.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fo4a64iz.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=14898', 'data', 'file=/tmp/tmpjd45me00/3yo9cuj8.json', 'init=/tmp/tmpjd45me00/fo4a64iz.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model1a83hsa1/prophet_model-20260803145200.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']

Build prophet model for  store_39_dept_7
Build prophet model for  store_39_dept_71

14:52:00 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:01 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/n6pd1qch.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9o37_on2.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=23694', 'data', 'file=/tmp/tmpjd45me00/n6pd1qch.json', 'init=/tmp/tmpjd45me00/9o37_on2.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model7v4wau32/prophet_model-20260803145201.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:01 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:01 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jkw89t9f.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5b39gt1n.json
DEBUG:cmdstanpy:idx 0

Build prophet model for  store_39_dept_72
Build prophet model for  store_39_dept_74

DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=74518', 'data', 'file=/tmp/tmpjd45me00/jkw89t9f.json', 'init=/tmp/tmpjd45me00/5b39gt1n.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelaenba_l3/prophet_model-20260803145201.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:01 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:01 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ko5udon_.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0cvbxb6a.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=79945', 'data', 'file=/tmp/tmpjd45me00/ko5udon_.json', 'init=/tmp/tmpjd45me00/0cvbxb6a.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelganxn647/prophet_model-20260803145201.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:01 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:01 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dliiy5gf.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9auvacy6.json

Build prophet model for  store_39_dept_79
Build prophet model for  store_39_dept_8

DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=10433', 'data', 'file=/tmp/tmpjd45me00/dliiy5gf.json', 'init=/tmp/tmpjd45me00/9auvacy6.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelvqv7x8w3/prophet_model-20260803145201.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:01 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:01 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/c7yh1h43.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/j6qjnuhf.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=84154', 'data', 'file=/tmp/tmpjd45me00/c7yh1h43.json', 'init=/tmp/tmpjd45me00/j6qjnuhf.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model4miz7r8s/prophet_model-20260803145201.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:01 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:02 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_39_dept_80

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jn781kvn.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rxifglwp.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=94266', 'data', 'file=/tmp/tmpjd45me00/jn781kvn.json', 'init=/tmp/tmpjd45me00/rxifglwp.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelegt4g05u/prophet_model-20260803145202.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:02 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:02 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_39_dept_81

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8ii5rj5u.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fdwp_m5v.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=87315', 'data', 'file=/tmp/tmpjd45me00/8ii5rj5u.json', 'init=/tmp/tmpjd45me00/fdwp_m5v.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelzd5qu3xw/prophet_model-20260803145202.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:02 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:02 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/a9wrgztl.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3bw271_5.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=91407', 'data', 'file=/tmp/tmpjd45me00/a9wrgztl.json', 'init=/tmp/tmpjd45me00/3bw271_5.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model5z3dj_1g/prophet_model-20260803145202.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:02 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_39_dept_82
Build prophet model for  store_39_dept_83

14:52:02 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/u3pva9t5.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rld5ynzx.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=43404', 'data', 'file=/tmp/tmpjd45me00/u3pva9t5.json', 'init=/tmp/tmpjd45me00/rld5ynzx.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelpyxtr_5c/prophet_model-20260803145202.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:02 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:02 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/emsdzmxo.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/z7mgau9j.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=26094', 'data', 'file=/tmp/tmpjd45me00/emsdzmxo.json', 'init=/tmp/tmpjd45me00/z7mgau9j.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeloxg04901/prophet_model-20260803145202.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:02 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_39_dept_85
Build prophet model for  store_39_dept_87

14:52:02 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fe4x5_me.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/g3261q1x.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=87346', 'data', 'file=/tmp/tmpjd45me00/fe4x5_me.json', 'init=/tmp/tmpjd45me00/g3261q1x.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelscxm1ssc/prophet_model-20260803145203.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:03 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:03 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/v7reudo4.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bfveiqvh.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=269', 'data', 'file=/tmp/tmpjd45me00/v7reudo4.json', 'init=/tmp/tmpjd45me00/bfveiqvh.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelv0zmahfs/prophet_model-20260803145203.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:03 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_39_dept_9
Build prophet model for  store_39_dept_90

14:52:03 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dlzn635e.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/saiv4bmw.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=81655', 'data', 'file=/tmp/tmpjd45me00/dlzn635e.json', 'init=/tmp/tmpjd45me00/saiv4bmw.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelzo1iymwl/prophet_model-20260803145203.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:03 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:03 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_39_dept_91
Build prophet model for  store_39_dept_92

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/h1c73903.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9ewe6g4z.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=90326', 'data', 'file=/tmp/tmpjd45me00/h1c73903.json', 'init=/tmp/tmpjd45me00/9ewe6g4z.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelae4rjzot/prophet_model-20260803145203.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:03 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:03 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ihgnkuec.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5cwnr0o6.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=57675', 'data', 'file=/tmp/tmpjd45me00/ihgnkuec.json', 'init=/tmp/tmpjd45me00/5cwnr0o6.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelrdy6ekp8/prophet_model-20260803145203.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:03 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_39_dept_93
Build prophet model for  store_39_dept_94

14:52:03 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/h0f9ozux.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/j5lgs20t.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=83894', 'data', 'file=/tmp/tmpjd45me00/h0f9ozux.json', 'init=/tmp/tmpjd45me00/j5lgs20t.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelc1dtnjdv/prophet_model-20260803145204.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:04 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:04 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/nrhbjkq1.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7_8eu6rh.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=81058', 'data', 'file=/tmp/tmpjd45me00/nrhbjkq1.json', 'init=/tmp/tmpjd45me00/7_8eu6rh.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model8f8ujr1d/prophet_model-20260803145204.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:04 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_39_dept_95
Build prophet model for  store_39_dept_96

14:52:04 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ud_2kl62.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/afuy_idz.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=17404', 'data', 'file=/tmp/tmpjd45me00/ud_2kl62.json', 'init=/tmp/tmpjd45me00/afuy_idz.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelxom25w7g/prophet_model-20260803145204.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:04 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:04 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/v3yc4gjf.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xspw5p_r.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=95989', 'data', 'file=/tmp/tmpjd45me00/v3yc4gjf.json', 'init=/tmp/tmpjd45me00/xspw5p_r.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeljyoh_qug/prophet_model-20260803145204.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:04 - cmdstanpy - INFO - Chain [1] start processing

Build prophet model for  store_39_dept_97
Build prophet model for  store_39_dept_98

INFO:cmdstanpy:Chain [1] start processing
14:52:04 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4osvhr74.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zyd8zd6m.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=52891', 'data', 'file=/tmp/tmpjd45me00/4osvhr74.json', 'init=/tmp/tmpjd45me00/zyd8zd6m.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelrfwqxc03/prophet_model-20260803145204.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:04 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:04 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/d8hyuxps.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/k2vvwle6.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=6477', 'data', 'file=/tmp/tmpjd45me00/d8hyuxps.json', 'init=/tmp/tmpjd45me00/k2vvwle6.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modela2beau6t/prophet_model-20260803145204.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']

Build prophet model for  store_3_dept_1
Build prophet model for  store_3_dept_10

14:52:04 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:04 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0ptt_s7f.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/lo6i8yti.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=31614', 'data', 'file=/tmp/tmpjd45me00/0ptt_s7f.json', 'init=/tmp/tmpjd45me00/lo6i8yti.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model07n0c1yr/prophet_model-20260803145204.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:04 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:04 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vp9e25av.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/c4_4uj90.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=24266', 'data', 'file=/tmp/tmpjd45me00/vp9e25av.json', 'init=/tmp/tmpjd45me00/c4_4uj90.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeld0gtzk62/prophet_model-20260803145205.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:05 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_3_dept_11
Build prophet model for  store_3_dept_12

14:52:05 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/671wuq77.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/yphs7sab.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=40675', 'data', 'file=/tmp/tmpjd45me00/671wuq77.json', 'init=/tmp/tmpjd45me00/yphs7sab.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelb1jxzahv/prophet_model-20260803145205.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:05 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:05 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_3_dept_13
Build prophet model for  store_3_dept_14

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/k1kbrz4q.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/34_w73r7.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=62294', 'data', 'file=/tmp/tmpjd45me00/k1kbrz4q.json', 'init=/tmp/tmpjd45me00/34_w73r7.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model14np2q_o/prophet_model-20260803145205.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:05 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:05 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/tcddy3wu.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wsnckv9u.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=38397', 'data', 'file=/tmp/tmpjd45me00/tcddy3wu.json', 'init=/tmp/tmpjd45me00/wsnckv9u.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model1u1kib_h/prophet_model-20260803145205.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:05 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:05 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_3_dept_16
Build prophet model for  store_3_dept_17

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/h5si3saq.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/u2agzs4k.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=4730', 'data', 'file=/tmp/tmpjd45me00/h5si3saq.json', 'init=/tmp/tmpjd45me00/u2agzs4k.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelgpccn6y0/prophet_model-20260803145206.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:06 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:06 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vfe6y1wr.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0372zii9.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=60258', 'data', 'file=/tmp/tmpjd45me00/vfe6y1wr.json', 'init=/tmp/tmpjd45me00/0372zii9.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelqkk57ebx/prophet_model-20260803145206.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:52:06 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_3_dept_18

14:52:07 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4rspkivs.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/to_mjyf_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=76187', 'data', 'file=/tmp/tmpjd45me00/4rspkivs.json', 'init=/tmp/tmpjd45me00/to_mjyf_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model2sw84emb/prophet_model-20260803145207.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:07 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_3_dept_19

14:52:07 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4g5_cig_.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4loutakz.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=79777', 'data', 'file=/tmp/tmpjd45me00/4g5_cig_.json', 'init=/tmp/tmpjd45me00/4loutakz.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelu22_1dxn/prophet_model-20260803145207.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:07 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:07 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/i4bc0m_u.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/kgno0qiq.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=75836', 'data', 'file=/tmp/tmpjd45me00/i4bc0m_u.json', 'init=/tmp/tmpjd45me00/kgno0qiq.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelv0v4nd9i/prophet_model-20260803145208.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:08 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_3_dept_2
Build prophet model for  store_3_dept_20

14:52:08 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8p0x3i2_.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/eo5x_3ir.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=11047', 'data', 'file=/tmp/tmpjd45me00/8p0x3i2_.json', 'init=/tmp/tmpjd45me00/eo5x_3ir.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model9121qtnk/prophet_model-20260803145208.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:08 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_3_dept_21

14:52:08 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/086izd9t.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9p00n0yg.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=30930', 'data', 'file=/tmp/tmpjd45me00/086izd9t.json', 'init=/tmp/tmpjd45me00/9p00n0yg.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model8qh1dk56/prophet_model-20260803145208.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:08 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_3_dept_22

14:52:08 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/nuqr3uz1.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/i98hiqei.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=49118', 'data', 'file=/tmp/tmpjd45me00/nuqr3uz1.json', 'init=/tmp/tmpjd45me00/i98hiqei.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelsj3x2v3z/prophet_model-20260803145209.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:09 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:09 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/uawrz1zc.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/axbm82_o.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=25203', 'data', 'file=/tmp/tmpjd45me00/uawrz1zc.json', 'init=/tmp/tmpjd45me00/axbm82_o.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model46gqwfl9/prophet_model-20260803145209.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:09 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_3_dept_23
Build prophet model for  store_3_dept_24

14:52:09 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4082t4fh.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hunt66j4.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=50254', 'data', 'file=/tmp/tmpjd45me00/4082t4fh.json', 'init=/tmp/tmpjd45me00/hunt66j4.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeleljtgwy0/prophet_model-20260803145209.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:09 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:09 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2_93ngdm.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/83qntzpe.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=51833', 'data', 'file=/tmp/tmpjd45me00/2_93ngdm.json', 'init=/tmp/tmpjd45me00/83qntzpe.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelun629rf8/prophet_model-20260803145209.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:09 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_3_dept_25
Build prophet model for  store_3_dept_26

14:52:09 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fnzqotic.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zs3uhobm.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=9778', 'data', 'file=/tmp/tmpjd45me00/fnzqotic.json', 'init=/tmp/tmpjd45me00/zs3uhobm.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model7iqdxhti/prophet_model-20260803145209.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:09 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:09 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_3_dept_27
Build prophet model for  store_3_dept_28

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8o59laqx.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/08fx1dmq.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=12440', 'data', 'file=/tmp/tmpjd45me00/8o59laqx.json', 'init=/tmp/tmpjd45me00/08fx1dmq.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model5q9ipwfu/prophet_model-20260803145209.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:09 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:10 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rersbo58.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hy0vd_vf.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=20832', 'data', 'file=/tmp/tmpjd45me00/rersbo58.json', 'init=/tmp/tmpjd45me00/hy0vd_vf.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_gquo6ny/prophet_model-20260803145210.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:10 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:10 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ktz50p0m.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/oj4gtzvs.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=72785', 'data', 'file=/tmp/tmpjd45me00/ktz50p0m.json', 'init=/tmp/tmpjd45me00/oj4gtzvs.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model9owou7ne/prophet_model-20260803145210.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:10 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_3_dept_29
Build prophet model for  store_3_dept_3

14:52:10 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/e4gjv96r.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gr4xrc6p.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=43302', 'data', 'file=/tmp/tmpjd45me00/e4gjv96r.json', 'init=/tmp/tmpjd45me00/gr4xrc6p.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeldnmh08a8/prophet_model-20260803145210.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:10 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_3_dept_30

14:52:10 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ta713drz.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7ngu77vw.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=75198', 'data', 'file=/tmp/tmpjd45me00/ta713drz.json', 'init=/tmp/tmpjd45me00/7ngu77vw.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeltyhwiy0z/prophet_model-20260803145210.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:10 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:10 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_3_dept_31

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_vkxlp_j.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6993o_3g.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=70216', 'data', 'file=/tmp/tmpjd45me00/_vkxlp_j.json', 'init=/tmp/tmpjd45me00/6993o_3g.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelg8w0nqae/prophet_model-20260803145211.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:11 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:11 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_3_dept_32

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dkeb34t8.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/snfakmz1.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=64061', 'data', 'file=/tmp/tmpjd45me00/dkeb34t8.json', 'init=/tmp/tmpjd45me00/snfakmz1.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model6_stntzr/prophet_model-20260803145211.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:11 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:11 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_3_dept_33
Build prophet model for  store_3_dept_34

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/y35tga55.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mkgwocdn.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=92550', 'data', 'file=/tmp/tmpjd45me00/y35tga55.json', 'init=/tmp/tmpjd45me00/mkgwocdn.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeleg0r7tgh/prophet_model-20260803145211.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:11 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:11 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0qcbv061.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/02c39443.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=17353', 'data', 'file=/tmp/tmpjd45me00/0qcbv061.json', 'init=/tmp/tmpjd45me00/02c39443.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelawiu8vpc/prophet_model-20260803145211.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:11 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:11 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_3_dept_35
Build prophet model for  store_3_dept_36

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/r0wxlsau.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vrmanebe.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=80153', 'data', 'file=/tmp/tmpjd45me00/r0wxlsau.json', 'init=/tmp/tmpjd45me00/vrmanebe.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelm0dxdvni/prophet_model-20260803145211.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:11 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:12 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8bqivui3.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xz1gunan.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=16749', 'data', 'file=/tmp/tmpjd45me00/8bqivui3.json', 'init=/tmp/tmpjd45me00/xz1gunan.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelm52o5g86/prophet_model-20260803145212.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:12 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:12 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_3_dept_38

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gzpkh3wu.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8u5urpjq.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=71870', 'data', 'file=/tmp/tmpjd45me00/gzpkh3wu.json', 'init=/tmp/tmpjd45me00/8u5urpjq.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelurgsvc4v/prophet_model-20260803145212.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:12 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:12 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_3_dept_4

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/n4mxkj21.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/br7yhb17.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=97719', 'data', 'file=/tmp/tmpjd45me00/n4mxkj21.json', 'init=/tmp/tmpjd45me00/br7yhb17.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model2m4r_jy8/prophet_model-20260803145212.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:12 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:12 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_3_dept_40

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vaqsw9s0.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/69_6m4tm.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=6425', 'data', 'file=/tmp/tmpjd45me00/vaqsw9s0.json', 'init=/tmp/tmpjd45me00/69_6m4tm.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelky1dvj71/prophet_model-20260803145212.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:12 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_3_dept_41

14:52:13 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/70b8ikte.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/j2u3psqd.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=11995', 'data', 'file=/tmp/tmpjd45me00/70b8ikte.json', 'init=/tmp/tmpjd45me00/j2u3psqd.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelchbm_t3r/prophet_model-20260803145213.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:13 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:13 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_3_dept_42
Build prophet model for  store_3_dept_44

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hw0dy90n.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/shkurlfb.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=46387', 'data', 'file=/tmp/tmpjd45me00/hw0dy90n.json', 'init=/tmp/tmpjd45me00/shkurlfb.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model5b6g594e/prophet_model-20260803145213.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:13 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:13 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/leoozu_q.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9t83plfg.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=3952', 'data', 'file=/tmp/tmpjd45me00/leoozu_q.json', 'init=/tmp/tmpjd45me00/9t83plfg.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelpqi5msps/prophet_model-20260803145213.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:13 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_3_dept_46

14:52:14 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vsimqb3r.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jmtjjqqs.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=86420', 'data', 'file=/tmp/tmpjd45me00/vsimqb3r.json', 'init=/tmp/tmpjd45me00/jmtjjqqs.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model6mb57f6m/prophet_model-20260803145214.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:14 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_3_dept_5

14:52:14 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/s49zf1bo.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/55vk2t2w.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=1562', 'data', 'file=/tmp/tmpjd45me00/s49zf1bo.json', 'init=/tmp/tmpjd45me00/55vk2t2w.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelb1fxg_me/prophet_model-20260803145214.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:14 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:14 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hlkldw17.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/uk7fd6fb.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=29540', 'data', 'file=/tmp/tmpjd45me00/hlkldw17.json', 'init=/tmp/tmpjd45me00/uk7fd6fb.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeloajoajqc/prophet_model-20260803145214.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:52:14 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_3_dept_52
Build prophet model for  store_3_dept_54

14:52:15 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rypuq6c6.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bmyuaqsp.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=53044', 'data', 'file=/tmp/tmpjd45me00/rypuq6c6.json', 'init=/tmp/tmpjd45me00/bmyuaqsp.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelegyke0mv/prophet_model-20260803145215.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:15 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_3_dept_55

14:52:16 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/l5lmjqx5.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/__xg7sdq.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=16076', 'data', 'file=/tmp/tmpjd45me00/l5lmjqx5.json', 'init=/tmp/tmpjd45me00/__xg7sdq.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelwlnw32ru/prophet_model-20260803145216.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:16 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:16 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/krqu0v_x.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ne9hyjjn.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=31491', 'data', 'file=/tmp/tmpjd45me00/krqu0v_x.json', 'init=/tmp/tmpjd45me00/ne9hyjjn.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelhc6puo4o/prophet_model-20260803145216.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:16 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_3_dept_56
Build prophet model for  store_3_dept_59

14:52:16 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/h51nspbb.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zdod_3fv.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=30329', 'data', 'file=/tmp/tmpjd45me00/h51nspbb.json', 'init=/tmp/tmpjd45me00/zdod_3fv.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model1nrhe296/prophet_model-20260803145216.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:16 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_3_dept_6

14:52:17 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7lpmp1ua.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qs8z574c.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=35387', 'data', 'file=/tmp/tmpjd45me00/7lpmp1ua.json', 'init=/tmp/tmpjd45me00/qs8z574c.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeln8b76dr5/prophet_model-20260803145217.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:17 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:17 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/lyh8ini0.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/r0ltcw9s.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=68399', 'data', 'file=/tmp/tmpjd45me00/lyh8ini0.json', 'init=/tmp/tmpjd45me00/r0ltcw9s.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelxshev7ma/prophet_model-20260803145217.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:17 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:17 - cmdstanpy - INFO - Chain [1] done processing

Build prophet model for  store_3_dept_60
Build prophet model for  store_3_dept_67

INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bld92645.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/y9h177_j.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=87812', 'data', 'file=/tmp/tmpjd45me00/bld92645.json', 'init=/tmp/tmpjd45me00/y9h177_j.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeltih_k6iq/prophet_model-20260803145217.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:17 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_3_dept_7

14:52:17 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qb5a6h58.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/muefnu3x.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=53872', 'data', 'file=/tmp/tmpjd45me00/qb5a6h58.json', 'init=/tmp/tmpjd45me00/muefnu3x.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeln9hodl3i/prophet_model-20260803145217.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:17 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:18 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_3_dept_71

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jrw_btm5.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fum8sel_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=71846', 'data', 'file=/tmp/tmpjd45me00/jrw_btm5.json', 'init=/tmp/tmpjd45me00/fum8sel_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model3jtu6_g6/prophet_model-20260803145218.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:18 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:18 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_3_dept_72

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/eyaltlg_.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/otvx4e54.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=62218', 'data', 'file=/tmp/tmpjd45me00/eyaltlg_.json', 'init=/tmp/tmpjd45me00/otvx4e54.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelypp77ubu/prophet_model-20260803145218.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:18 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_3_dept_74

14:52:18 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/f4qo7hsx.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/n8a1wrhu.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=2581', 'data', 'file=/tmp/tmpjd45me00/f4qo7hsx.json', 'init=/tmp/tmpjd45me00/n8a1wrhu.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_i0gzh80/prophet_model-20260803145218.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:18 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:18 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/g2_xjb4e.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/flngihyq.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=94092', 'data', 'file=/tmp/tmpjd45me00/g2_xjb4e.json', 'init=/tmp/tmpjd45me00/flngihyq.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelf7rwfdme/prophet_model-20260803145218.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:18 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_3_dept_79
Build prophet model for  store_3_dept_8

14:52:18 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/x2g25vdk.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4mm66shi.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=15557', 'data', 'file=/tmp/tmpjd45me00/x2g25vdk.json', 'init=/tmp/tmpjd45me00/4mm66shi.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeluftszcfu/prophet_model-20260803145219.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:19 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_3_dept_81

14:52:19 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/e216xgdr.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pvyr4l16.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=18693', 'data', 'file=/tmp/tmpjd45me00/e216xgdr.json', 'init=/tmp/tmpjd45me00/pvyr4l16.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelwo1jcey4/prophet_model-20260803145219.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:19 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_3_dept_82

14:52:19 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bp_3djmt.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4hbi9qf5.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=74521', 'data', 'file=/tmp/tmpjd45me00/bp_3djmt.json', 'init=/tmp/tmpjd45me00/4hbi9qf5.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelua8eup0q/prophet_model-20260803145219.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:19 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:19 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_3_dept_85

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/a4kdnkzk.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hqfnzims.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=98031', 'data', 'file=/tmp/tmpjd45me00/a4kdnkzk.json', 'init=/tmp/tmpjd45me00/hqfnzims.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelyx3ygc5l/prophet_model-20260803145220.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:20 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:20 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_3_dept_87
Build prophet model for  store_3_dept_9

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/scsqayjz.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6th1ebcy.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=69710', 'data', 'file=/tmp/tmpjd45me00/scsqayjz.json', 'init=/tmp/tmpjd45me00/6th1ebcy.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model91ni9yaa/prophet_model-20260803145220.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:20 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:20 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/nd36_j_b.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dfj154sd.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=73832', 'data', 'file=/tmp/tmpjd45me00/nd36_j_b.json', 'init=/tmp/tmpjd45me00/dfj154sd.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model471b3axr/prophet_model-20260803145220.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:20 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_3_dept_90

14:52:20 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9c5urghr.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8kbo7ff_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=54939', 'data', 'file=/tmp/tmpjd45me00/9c5urghr.json', 'init=/tmp/tmpjd45me00/8kbo7ff_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelasvlrujx/prophet_model-20260803145220.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:20 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:20 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1o7ngi3h.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/nsrqgu5t.json
DEBUG:cmdstanpy:idx 0

Build prophet model for  store_3_dept_91
Build prophet model for  store_3_dept_92

DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=85856', 'data', 'file=/tmp/tmpjd45me00/1o7ngi3h.json', 'init=/tmp/tmpjd45me00/nsrqgu5t.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modellhro9z5c/prophet_model-20260803145220.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:20 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:21 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0ky86yzj.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hzvgsku9.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=70536', 'data', 'file=/tmp/tmpjd45me00/0ky86yzj.json', 'init=/tmp/tmpjd45me00/hzvgsku9.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modell0txem8j/prophet_model-20260803145221.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:21 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_3_dept_95

14:52:21 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7c625i52.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/h3c62_1i.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=41634', 'data', 'file=/tmp/tmpjd45me00/7c625i52.json', 'init=/tmp/tmpjd45me00/h3c62_1i.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelpod_h139/prophet_model-20260803145221.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:21 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:21 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5pe_xaqh.json

Build prophet model for  store_3_dept_96
Build prophet model for  store_3_dept_97

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fyazxbzm.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=63912', 'data', 'file=/tmp/tmpjd45me00/5pe_xaqh.json', 'init=/tmp/tmpjd45me00/fyazxbzm.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelxugexj5y/prophet_model-20260803145221.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:21 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:21 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pp9lket5.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4oqrjl92.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=81489', 'data', 'file=/tmp/tmpjd45me00/pp9lket5.json', 'init=/tmp/tmpjd45me00/4oqrjl92.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelpke6pud_/prophet_model-20260803145222.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:22 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:22 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/h70vpnty.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/njery24w.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=34690', 'data', 'file=/tmp/tmpjd45me00/h70vpnty.json', 'init=/tmp/tmpjd45me00/njery24w.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model81ql5lzt/prophet_model-20260803145222.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:22 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_40_dept_1
Build prophet model for  store_40_dept_10

14:52:22 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fuh1pzz5.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/thmrznvb.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=25573', 'data', 'file=/tmp/tmpjd45me00/fuh1pzz5.json', 'init=/tmp/tmpjd45me00/thmrznvb.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelhanl5kwg/prophet_model-20260803145222.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:22 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:22 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/r2ivg6lz.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/iy7swt3g.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=24281', 'data', 'file=/tmp/tmpjd45me00/r2ivg6lz.json', 'init=/tmp/tmpjd45me00/iy7swt3g.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model4g9mt5p2/prophet_model-20260803145222.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:22 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_40_dept_11
Build prophet model for  store_40_dept_12

14:52:22 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/i2re5omr.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1qp3bba4.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=87646', 'data', 'file=/tmp/tmpjd45me00/i2re5omr.json', 'init=/tmp/tmpjd45me00/1qp3bba4.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelv2gd10ji/prophet_model-20260803145222.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:22 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:22 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zmflp57y.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4r9lxq28.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=76258', 'data', 'file=/tmp/tmpjd45me00/zmflp57y.json', 'init=/tmp/tmpjd45me00/4r9lxq28.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model595hjv3y/prophet_model-20260803145222.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:22 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_40_dept_13
Build prophet model for  store_40_dept_14

14:52:22 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/78yx9uzu.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dsbjdg_u.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=57162', 'data', 'file=/tmp/tmpjd45me00/78yx9uzu.json', 'init=/tmp/tmpjd45me00/dsbjdg_u.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelodrmav16/prophet_model-20260803145223.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:23 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:23 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/kslf4sog.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/c66ms6z9.json

Build prophet model for  store_40_dept_16
Build prophet model for  store_40_dept_17

DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=55834', 'data', 'file=/tmp/tmpjd45me00/kslf4sog.json', 'init=/tmp/tmpjd45me00/c66ms6z9.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeljpbedw1z/prophet_model-20260803145223.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:23 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:23 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/t8pri2mw.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/066jrmos.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=2962', 'data', 'file=/tmp/tmpjd45me00/t8pri2mw.json', 'init=/tmp/tmpjd45me00/066jrmos.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_7ghn1zj/prophet_model-20260803145223.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:23 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:23 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vg6eb0wo.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/h3dr13b9.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=37997', 'data', 'file=/tmp/tmpjd45me00/vg6eb0wo.json', 'init=/tmp/tmpjd45me00/h3dr13b9.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelvqcz94nz/prophet_model-20260803145223.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:23 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_40_dept_18
Build prophet model for  store_40_dept_2

14:52:23 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dfbrg9qy.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0mijg5ou.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=71434', 'data', 'file=/tmp/tmpjd45me00/dfbrg9qy.json', 'init=/tmp/tmpjd45me00/0mijg5ou.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelapl8hu8p/prophet_model-20260803145223.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:23 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_40_dept_20

14:52:23 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/u8hel3r4.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wq7s7wrj.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=15462', 'data', 'file=/tmp/tmpjd45me00/u8hel3r4.json', 'init=/tmp/tmpjd45me00/wq7s7wrj.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelzx53cqc8/prophet_model-20260803145224.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:24 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:24 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_40_dept_21

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0hnmijtm.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/tpyy7yrg.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=84582', 'data', 'file=/tmp/tmpjd45me00/0hnmijtm.json', 'init=/tmp/tmpjd45me00/tpyy7yrg.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeli3awd1hz/prophet_model-20260803145224.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:24 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:24 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_40_dept_22
Build prophet model for  store_40_dept_23

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/r8uih44_.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/w38hcb10.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=12453', 'data', 'file=/tmp/tmpjd45me00/r8uih44_.json', 'init=/tmp/tmpjd45me00/w38hcb10.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelaa7ybqzu/prophet_model-20260803145224.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:24 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:24 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/q663lt9a.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2s2akyfr.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=70430', 'data', 'file=/tmp/tmpjd45me00/q663lt9a.json', 'init=/tmp/tmpjd45me00/2s2akyfr.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model4lej9ohz/prophet_model-20260803145224.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:24 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:24 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_40_dept_24

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/k8swsi7e.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8276qh2o.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=40529', 'data', 'file=/tmp/tmpjd45me00/k8swsi7e.json', 'init=/tmp/tmpjd45me00/8276qh2o.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelzaxw7b6_/prophet_model-20260803145225.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:25 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:25 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_40_dept_25

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gmgbz5ko.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/c6jbz4ap.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=81298', 'data', 'file=/tmp/tmpjd45me00/gmgbz5ko.json', 'init=/tmp/tmpjd45me00/c6jbz4ap.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelclxp8iu2/prophet_model-20260803145225.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:25 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:25 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_40_dept_26
Build prophet model for  store_40_dept_27

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zszagzp3.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vvckhwpm.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=68715', 'data', 'file=/tmp/tmpjd45me00/zszagzp3.json', 'init=/tmp/tmpjd45me00/vvckhwpm.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelcrdq0qa6/prophet_model-20260803145225.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:25 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:26 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zi3ja1fh.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/egac2q2a.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=59483', 'data', 'file=/tmp/tmpjd45me00/zi3ja1fh.json', 'init=/tmp/tmpjd45me00/egac2q2a.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelfb03tqkd/prophet_model-20260803145226.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:26 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:26 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_40_dept_28

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xymnz4ax.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hvo0zv1d.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=75266', 'data', 'file=/tmp/tmpjd45me00/xymnz4ax.json', 'init=/tmp/tmpjd45me00/hvo0zv1d.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model6nyyrupo/prophet_model-20260803145226.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:26 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:26 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_40_dept_29
Build prophet model for  store_40_dept_3

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/w0z9xwfa.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9cisbbdy.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=88510', 'data', 'file=/tmp/tmpjd45me00/w0z9xwfa.json', 'init=/tmp/tmpjd45me00/9cisbbdy.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelaho11gwg/prophet_model-20260803145226.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:26 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:26 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/kheneyrm.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/g772gpto.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=15272', 'data', 'file=/tmp/tmpjd45me00/kheneyrm.json', 'init=/tmp/tmpjd45me00/g772gpto.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model0c9_l65f/prophet_model-20260803145226.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:26 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:27 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_40_dept_30
Build prophet model for  store_40_dept_31

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bkr8o8vp.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/r6fx6995.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=78836', 'data', 'file=/tmp/tmpjd45me00/bkr8o8vp.json', 'init=/tmp/tmpjd45me00/r6fx6995.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelc7a3gx12/prophet_model-20260803145227.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:27 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:27 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_ed1h5lk.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/78t7kb1c.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=30982', 'data', 'file=/tmp/tmpjd45me00/_ed1h5lk.json', 'init=/tmp/tmpjd45me00/78t7kb1c.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelbll8jh1m/prophet_model-20260803145227.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:27 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:27 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4kboa0dt.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/muzwiz_5.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=89784', 'data', 'file=/tmp/tmpjd45me00/4kboa0dt.json', 'init=/tmp/tmpjd45me00/muzwiz_5.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model8zr0a6f4/prophet_model-20260803145227.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:27 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_40_dept_32
Build prophet model for  store_40_dept_33

14:52:27 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qad1ina4.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pctwyos7.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=64795', 'data', 'file=/tmp/tmpjd45me00/qad1ina4.json', 'init=/tmp/tmpjd45me00/pctwyos7.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelax97oyrw/prophet_model-20260803145227.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:27 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:27 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/nrmtya2f.json

Build prophet model for  store_40_dept_34
Build prophet model for  store_40_dept_35

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ny1719g4.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=35888', 'data', 'file=/tmp/tmpjd45me00/nrmtya2f.json', 'init=/tmp/tmpjd45me00/ny1719g4.json', 'output', 'file=/tmp/tmpjd45me00/prophet_models3sub03e/prophet_model-20260803145227.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:27 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:27 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1mo9291k.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/v44wc89q.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=84805', 'data', 'file=/tmp/tmpjd45me00/1mo9291k.json', 'init=/tmp/tmpjd45me00/v44wc89q.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model0zneqvlr/prophet_model-20260803145228.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:28 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:28 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_40_dept_36
Build prophet model for  store_40_dept_37

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/q0boqchq.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/b_3eohzt.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=21707', 'data', 'file=/tmp/tmpjd45me00/q0boqchq.json', 'init=/tmp/tmpjd45me00/b_3eohzt.json', 'output', 'file=/tmp/tmpjd45me00/prophet_models83m8p85/prophet_model-20260803145228.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:28 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:28 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/puas0tvc.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0or9fe1o.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=79133', 'data', 'file=/tmp/tmpjd45me00/puas0tvc.json', 'init=/tmp/tmpjd45me00/0or9fe1o.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelfqcjurab/prophet_model-20260803145228.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:28 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:28 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xxxq35lj.json

Build prophet model for  store_40_dept_38
Build prophet model for  store_40_dept_4

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ppibljak.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=85090', 'data', 'file=/tmp/tmpjd45me00/xxxq35lj.json', 'init=/tmp/tmpjd45me00/ppibljak.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelrracv6or/prophet_model-20260803145228.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:28 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:28 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/coptx7o3.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/d21ue82j.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=41643', 'data', 'file=/tmp/tmpjd45me00/coptx7o3.json', 'init=/tmp/tmpjd45me00/d21ue82j.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelxxyk_qov/prophet_model-20260803145228.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:28 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:28 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/12s3gssi.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/n3g5l0sj.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=66210', 'data', 'file=/tmp/tmpjd45me00/12s3gssi.json', 'init=/tmp/tmpjd45me00/n3g5l0sj.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelox37xyze/prophet_model-20260803145228.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:28 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_40_dept_40
Build prophet model for  store_40_dept_41

14:52:28 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/oaf_tvcl.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4g64_8pc.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=41831', 'data', 'file=/tmp/tmpjd45me00/oaf_tvcl.json', 'init=/tmp/tmpjd45me00/4g64_8pc.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model8028u9xm/prophet_model-20260803145229.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:29 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:29 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_40_dept_42
Build prophet model for  store_40_dept_44

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gc_yo5wg.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/uik1d0b3.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=51417', 'data', 'file=/tmp/tmpjd45me00/gc_yo5wg.json', 'init=/tmp/tmpjd45me00/uik1d0b3.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model7jzt1v4j/prophet_model-20260803145229.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:29 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:29 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0valoex1.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_4ccdla_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=92925', 'data', 'file=/tmp/tmpjd45me00/0valoex1.json', 'init=/tmp/tmpjd45me00/_4ccdla_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeloar9ldzi/prophet_model-20260803145229.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:52:29 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_40_dept_45

14:52:30 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/la3zkctc.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mocsjii3.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=35680', 'data', 'file=/tmp/tmpjd45me00/la3zkctc.json', 'init=/tmp/tmpjd45me00/mocsjii3.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelnf6v8eih/prophet_model-20260803145230.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:30 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:30 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xtu52mh3.json

Build prophet model for  store_40_dept_46
Build prophet model for  store_40_dept_48

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/92rc6vp4.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=75890', 'data', 'file=/tmp/tmpjd45me00/xtu52mh3.json', 'init=/tmp/tmpjd45me00/92rc6vp4.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelm8dstlej/prophet_model-20260803145230.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:30 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:30 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_t0m5nox.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/y9d0knaf.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=59795', 'data', 'file=/tmp/tmpjd45me00/_t0m5nox.json', 'init=/tmp/tmpjd45me00/y9d0knaf.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelxom7_0xp/prophet_model-20260803145230.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:30 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:30 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/b1ewcrts.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4rw3oqgd.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=3634', 'data', 'file=/tmp/tmpjd45me00/b1ewcrts.json', 'init=/tmp/tmpjd45me00/4rw3oqgd.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model0gzk7dp7/prophet_model-20260803145230.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:30 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:30 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_40_dept_5
Build prophet model for  store_40_dept_52

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/i7ged21o.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/g_ynqb02.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=56407', 'data', 'file=/tmp/tmpjd45me00/i7ged21o.json', 'init=/tmp/tmpjd45me00/g_ynqb02.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelzepz5gm1/prophet_model-20260803145231.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:31 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:31 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/q4rz5zn0.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ygrswl22.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=6480', 'data', 'file=/tmp/tmpjd45me00/q4rz5zn0.json', 'init=/tmp/tmpjd45me00/ygrswl22.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelgeagyd_4/prophet_model-20260803145231.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']

Build prophet model for  store_40_dept_54
Build prophet model for  store_40_dept_55

14:52:31 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:31 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ziod13s3.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/lmut2k8x.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=46671', 'data', 'file=/tmp/tmpjd45me00/ziod13s3.json', 'init=/tmp/tmpjd45me00/lmut2k8x.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelssf7e79f/prophet_model-20260803145231.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:31 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_40_dept_56

14:52:31 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ljklxjay.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/sx02odwx.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=69774', 'data', 'file=/tmp/tmpjd45me00/ljklxjay.json', 'init=/tmp/tmpjd45me00/sx02odwx.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelb19rw7bp/prophet_model-20260803145231.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:31 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_40_dept_59

14:52:31 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/n_7o14ry.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2zaacl8f.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=41168', 'data', 'file=/tmp/tmpjd45me00/n_7o14ry.json', 'init=/tmp/tmpjd45me00/2zaacl8f.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model61upi34j/prophet_model-20260803145232.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:32 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:32 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7036hjcz.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3gp7jmdo.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=46020', 'data', 'file=/tmp/tmpjd45me00/7036hjcz.json', 'init=/tmp/tmpjd45me00/3gp7jmdo.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelkh35uiav/prophet_model-20260803145232.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:32 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_40_dept_6
Build prophet model for  store_40_dept_60

14:52:32 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wze6ajwv.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zzmzvus_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=84029', 'data', 'file=/tmp/tmpjd45me00/wze6ajwv.json', 'init=/tmp/tmpjd45me00/zzmzvus_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelhd9v9b9a/prophet_model-20260803145232.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:32 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:32 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6lqd6fqa.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/z2elqwkv.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=84807', 'data', 'file=/tmp/tmpjd45me00/6lqd6fqa.json', 'init=/tmp/tmpjd45me00/z2elqwkv.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model2iihvf1z/prophet_model-20260803145232.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:32 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_40_dept_67
Build prophet model for  store_40_dept_7

14:52:32 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bp48eltv.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7_icg02p.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=54250', 'data', 'file=/tmp/tmpjd45me00/bp48eltv.json', 'init=/tmp/tmpjd45me00/7_icg02p.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeljwnuhdzc/prophet_model-20260803145232.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:32 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:32 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/irdgf54d.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/89cudwyu.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=19398', 'data', 'file=/tmp/tmpjd45me00/irdgf54d.json', 'init=/tmp/tmpjd45me00/89cudwyu.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model7ha6ekst/prophet_model-20260803145232.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:32 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_40_dept_71
Build prophet model for  store_40_dept_72

14:52:32 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/acybwde3.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8dq4vsql.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=55090', 'data', 'file=/tmp/tmpjd45me00/acybwde3.json', 'init=/tmp/tmpjd45me00/8dq4vsql.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeli2jvg2fm/prophet_model-20260803145233.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:33 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:33 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_40_dept_74
Build prophet model for  store_40_dept_79

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/j8vapbtr.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0ujpl5it.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=72249', 'data', 'file=/tmp/tmpjd45me00/j8vapbtr.json', 'init=/tmp/tmpjd45me00/0ujpl5it.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelm9hq_eec/prophet_model-20260803145233.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:33 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:33 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0gd2twp3.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/87lv5xgd.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=1505', 'data', 'file=/tmp/tmpjd45me00/0gd2twp3.json', 'init=/tmp/tmpjd45me00/87lv5xgd.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model8dydo2lr/prophet_model-20260803145233.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:33 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:33 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_40_dept_8
Build prophet model for  store_40_dept_80

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bpl46f3n.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/87jw15lb.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=90860', 'data', 'file=/tmp/tmpjd45me00/bpl46f3n.json', 'init=/tmp/tmpjd45me00/87jw15lb.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelwlehk2_j/prophet_model-20260803145233.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:33 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:33 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wv4h0fq8.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pnxqd_65.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=31373', 'data', 'file=/tmp/tmpjd45me00/wv4h0fq8.json', 'init=/tmp/tmpjd45me00/pnxqd_65.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelt9rt4jr3/prophet_model-20260803145233.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:33 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:33 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dvw_hn62.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8b9nx7pn.json

Build prophet model for  store_40_dept_81
Build prophet model for  store_40_dept_82

DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=11780', 'data', 'file=/tmp/tmpjd45me00/dvw_hn62.json', 'init=/tmp/tmpjd45me00/8b9nx7pn.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelll974cho/prophet_model-20260803145233.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:33 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:34 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fpgh2rlw.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3lys9xvr.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=9625', 'data', 'file=/tmp/tmpjd45me00/fpgh2rlw.json', 'init=/tmp/tmpjd45me00/3lys9xvr.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model9b5k38l7/prophet_model-20260803145234.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:34 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_40_dept_83

14:52:34 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gw2jm2b8.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/z3g_k9od.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=8866', 'data', 'file=/tmp/tmpjd45me00/gw2jm2b8.json', 'init=/tmp/tmpjd45me00/z3g_k9od.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model7qm2ahzq/prophet_model-20260803145234.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:34 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_40_dept_85

14:52:34 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vyystag9.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/24gi5leo.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=33995', 'data', 'file=/tmp/tmpjd45me00/vyystag9.json', 'init=/tmp/tmpjd45me00/24gi5leo.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeli9qr0gf6/prophet_model-20260803145234.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:34 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:34 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/w15g0tg4.json

Build prophet model for  store_40_dept_87
Build prophet model for  store_40_dept_9

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/kone4982.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=72018', 'data', 'file=/tmp/tmpjd45me00/w15g0tg4.json', 'init=/tmp/tmpjd45me00/kone4982.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelqza37_ne/prophet_model-20260803145234.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:34 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:35 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5fj2ma7k.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1vf1pot1.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=69125', 'data', 'file=/tmp/tmpjd45me00/5fj2ma7k.json', 'init=/tmp/tmpjd45me00/1vf1pot1.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelaf8xtf14/prophet_model-20260803145235.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:35 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:35 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/w_jkhvhk.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8r2fxbua.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=57521', 'data', 'file=/tmp/tmpjd45me00/w_jkhvhk.json', 'init=/tmp/tmpjd45me00/8r2fxbua.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelke8kq99o/prophet_model-20260803145235.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:35 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:35 - cmdstanpy - INFO - Chain [1] done processing

Build prophet model for  store_40_dept_90
Build prophet model for  store_40_dept_91

INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zezrjy8t.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/w_jrc7cf.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=9677', 'data', 'file=/tmp/tmpjd45me00/zezrjy8t.json', 'init=/tmp/tmpjd45me00/w_jrc7cf.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelkjf8de7m/prophet_model-20260803145235.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:35 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:35 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4oobelr8.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8vx107nm.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=72180', 'data', 'file=/tmp/tmpjd45me00/4oobelr8.json', 'init=/tmp/tmpjd45me00/8vx107nm.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelr5q7up45/prophet_model-20260803145235.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:35 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_40_dept_92
Build prophet model for  store_40_dept_93

14:52:35 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zxdsufd9.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/293wooin.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=71555', 'data', 'file=/tmp/tmpjd45me00/zxdsufd9.json', 'init=/tmp/tmpjd45me00/293wooin.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelro9k2p1w/prophet_model-20260803145235.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:35 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:35 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/nwb928mm.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/l0ly0ffh.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=92360', 'data', 'file=/tmp/tmpjd45me00/nwb928mm.json', 'init=/tmp/tmpjd45me00/l0ly0ffh.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelld1ko4or/prophet_model-20260803145235.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:35 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_40_dept_94
Build prophet model for  store_40_dept_95

14:52:35 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xh94_r1f.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/h8xvfl5a.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=19869', 'data', 'file=/tmp/tmpjd45me00/xh94_r1f.json', 'init=/tmp/tmpjd45me00/h8xvfl5a.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model5k17w31k/prophet_model-20260803145236.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:36 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_40_dept_96

14:52:36 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/cbaguuor.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/79fz961_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=76450', 'data', 'file=/tmp/tmpjd45me00/cbaguuor.json', 'init=/tmp/tmpjd45me00/79fz961_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model5ncf_mem/prophet_model-20260803145236.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:36 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:36 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4zxr_q7r.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ll0jqkfe.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=51845', 'data', 'file=/tmp/tmpjd45me00/4zxr_q7r.json', 'init=/tmp/tmpjd45me00/ll0jqkfe.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelq039ea2y/prophet_model-20260803145236.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:36 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_40_dept_97
Build prophet model for  store_40_dept_98

14:52:36 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/u2y0n3xe.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/j928maub.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=8696', 'data', 'file=/tmp/tmpjd45me00/u2y0n3xe.json', 'init=/tmp/tmpjd45me00/j928maub.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelqegbvmp0/prophet_model-20260803145236.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:36 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:36 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_41_dept_1
Build prophet model for  store_41_dept_10

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vxdmgfnn.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0lc0xbkk.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=61740', 'data', 'file=/tmp/tmpjd45me00/vxdmgfnn.json', 'init=/tmp/tmpjd45me00/0lc0xbkk.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model990ly6d6/prophet_model-20260803145236.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:36 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:36 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5492u3vl.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5w2_xfsb.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=19480', 'data', 'file=/tmp/tmpjd45me00/5492u3vl.json', 'init=/tmp/tmpjd45me00/5w2_xfsb.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelskppk4bp/prophet_model-20260803145237.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:37 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:37 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_41_dept_11

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2me58y6k.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bjuran4e.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=8291', 'data', 'file=/tmp/tmpjd45me00/2me58y6k.json', 'init=/tmp/tmpjd45me00/bjuran4e.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modela97twbdg/prophet_model-20260803145237.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:37 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:37 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_41_dept_12

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ttn0m9t1.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/l4tu72n4.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=89609', 'data', 'file=/tmp/tmpjd45me00/ttn0m9t1.json', 'init=/tmp/tmpjd45me00/l4tu72n4.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelibp38ivz/prophet_model-20260803145237.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:37 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_41_dept_13

14:52:37 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qrkasvjd.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/htyhc9a8.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=1632', 'data', 'file=/tmp/tmpjd45me00/qrkasvjd.json', 'init=/tmp/tmpjd45me00/htyhc9a8.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model68xemj5g/prophet_model-20260803145238.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:38 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:38 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_41_dept_14
Build prophet model for  store_41_dept_16

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ngc1t0u4.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3ttp160b.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=74772', 'data', 'file=/tmp/tmpjd45me00/ngc1t0u4.json', 'init=/tmp/tmpjd45me00/3ttp160b.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelk1yrgvu1/prophet_model-20260803145238.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:38 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:38 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2460pzcu.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5we6smy7.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=10872', 'data', 'file=/tmp/tmpjd45me00/2460pzcu.json', 'init=/tmp/tmpjd45me00/5we6smy7.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelijzu9ihs/prophet_model-20260803145238.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:38 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:38 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_41_dept_17
Build prophet model for  store_41_dept_18

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_2l11ulh.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1axtztln.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=59297', 'data', 'file=/tmp/tmpjd45me00/_2l11ulh.json', 'init=/tmp/tmpjd45me00/1axtztln.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelewyu9ukz/prophet_model-20260803145239.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:52:39 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:40 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3ah91y88.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zndn425m.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=84947', 'data', 'file=/tmp/tmpjd45me00/3ah91y88.json', 'init=/tmp/tmpjd45me00/zndn425m.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelarpo20b0/prophet_model-20260803145241.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:41 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:41 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fwpmkpj7.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/nnlxlcao.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=58918', 'data', 'file=/tmp/tmpjd45me00/fwpmkpj7.json', 'init=/tmp/tmpjd45me00/nnlxlcao.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modela9atmu9f/prophet_model-20260803145241.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:41 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_41_dept_2
Build prophet model for  store_41_dept_20

14:52:41 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/u36qe_c2.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/u79he7z2.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=62252', 'data', 'file=/tmp/tmpjd45me00/u36qe_c2.json', 'init=/tmp/tmpjd45me00/u79he7z2.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelklxuhaxt/prophet_model-20260803145241.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:41 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:41 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/yrshh8k6.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/uz6dtbn9.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=3336', 'data', 'file=/tmp/tmpjd45me00/yrshh8k6.json', 'init=/tmp/tmpjd45me00/uz6dtbn9.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model5frm8yfp/prophet_model-20260803145241.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:41 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_41_dept_21
Build prophet model for  store_41_dept_22

14:52:41 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/aij3hixv.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vt8mlyg4.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=16524', 'data', 'file=/tmp/tmpjd45me00/aij3hixv.json', 'init=/tmp/tmpjd45me00/vt8mlyg4.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeljtf8tqzg/prophet_model-20260803145241.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:41 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:41 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dlcahvtn.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ytc1a5_h.json
DEBUG:cmdstanpy:idx 0

Build prophet model for  store_41_dept_23
Build prophet model for  store_41_dept_24

DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=20373', 'data', 'file=/tmp/tmpjd45me00/dlcahvtn.json', 'init=/tmp/tmpjd45me00/ytc1a5_h.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelnf35oezx/prophet_model-20260803145241.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:41 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:41 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xlb8rtqw.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/cptrhlm3.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=95690', 'data', 'file=/tmp/tmpjd45me00/xlb8rtqw.json', 'init=/tmp/tmpjd45me00/cptrhlm3.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelhlan75jo/prophet_model-20260803145242.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:42 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:42 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_41_dept_25
Build prophet model for  store_41_dept_26

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/z7572oa0.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pqyp5xzn.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=72224', 'data', 'file=/tmp/tmpjd45me00/z7572oa0.json', 'init=/tmp/tmpjd45me00/pqyp5xzn.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelmlxcy503/prophet_model-20260803145242.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:42 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:42 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5iip3lo8.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/844uxiw8.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=21951', 'data', 'file=/tmp/tmpjd45me00/5iip3lo8.json', 'init=/tmp/tmpjd45me00/844uxiw8.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelcpf_uivc/prophet_model-20260803145242.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:42 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:42 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/kq6wdwrw.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7z41jbut.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=72379', 'data', 'file=/tmp/tmpjd45me00/kq6wdwrw.json', 'init=/tmp/tmpjd45me00/7z41jbut.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelw55mtnsx/prophet_model-20260803145242.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:42 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_41_dept_27
Build prophet model for  store_41_dept_28

14:52:42 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ahraw_h1.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gv7kff6t.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=82529', 'data', 'file=/tmp/tmpjd45me00/ahraw_h1.json', 'init=/tmp/tmpjd45me00/gv7kff6t.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelcnq84iun/prophet_model-20260803145242.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:42 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:42 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/k5jfzunw.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3pigl8dh.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=59727', 'data', 'file=/tmp/tmpjd45me00/k5jfzunw.json', 'init=/tmp/tmpjd45me00/3pigl8dh.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelf1lqd35h/prophet_model-20260803145242.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:42 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_41_dept_29
Build prophet model for  store_41_dept_3

14:52:43 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rsbp6xlm.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0pieh4id.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=3940', 'data', 'file=/tmp/tmpjd45me00/rsbp6xlm.json', 'init=/tmp/tmpjd45me00/0pieh4id.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model0nktro0m/prophet_model-20260803145243.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:43 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:43 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/tvfg2h_5.json

Build prophet model for  store_41_dept_30
Build prophet model for  store_41_dept_31

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/j2lrmie9.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=20626', 'data', 'file=/tmp/tmpjd45me00/tvfg2h_5.json', 'init=/tmp/tmpjd45me00/j2lrmie9.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modellg94a906/prophet_model-20260803145243.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:43 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:43 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/j06xwxbh.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qk1t7wvj.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=33404', 'data', 'file=/tmp/tmpjd45me00/j06xwxbh.json', 'init=/tmp/tmpjd45me00/qk1t7wvj.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeljgwt_9q_/prophet_model-20260803145243.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:43 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:43 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/l88vt7y_.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xceswdpk.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=6170', 'data', 'file=/tmp/tmpjd45me00/l88vt7y_.json', 'init=/tmp/tmpjd45me00/xceswdpk.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelulc6wvzp/prophet_model-20260803145243.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:43 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:43 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_41_dept_32
Build prophet model for  store_41_dept_33

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_sehp_83.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jbvwlx_d.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=44194', 'data', 'file=/tmp/tmpjd45me00/_sehp_83.json', 'init=/tmp/tmpjd45me00/jbvwlx_d.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model03qmdfmn/prophet_model-20260803145243.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:43 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_41_dept_34

14:52:44 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qum8qvlh.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/uy6ndn9h.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=75290', 'data', 'file=/tmp/tmpjd45me00/qum8qvlh.json', 'init=/tmp/tmpjd45me00/uy6ndn9h.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelw25ajzvn/prophet_model-20260803145244.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:44 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:44 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6_yl3r5e.json

Build prophet model for  store_41_dept_35
Build prophet model for  store_41_dept_36

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/67jbu_um.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=69622', 'data', 'file=/tmp/tmpjd45me00/6_yl3r5e.json', 'init=/tmp/tmpjd45me00/67jbu_um.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelgrryrxz3/prophet_model-20260803145244.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:44 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:44 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bi9bpec7.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dn1k4fca.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=17520', 'data', 'file=/tmp/tmpjd45me00/bi9bpec7.json', 'init=/tmp/tmpjd45me00/dn1k4fca.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modellw5on5ls/prophet_model-20260803145244.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:44 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:44 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/otv7yc44.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3d7gj8s6.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=80424', 'data', 'file=/tmp/tmpjd45me00/otv7yc44.json', 'init=/tmp/tmpjd45me00/3d7gj8s6.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelsjayc6ig/prophet_model-20260803145244.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:44 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_41_dept_38
Build prophet model for  store_41_dept_4

14:52:44 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/f0rxbo4i.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bh7jsizr.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=7158', 'data', 'file=/tmp/tmpjd45me00/f0rxbo4i.json', 'init=/tmp/tmpjd45me00/bh7jsizr.json', 'output', 'file=/tmp/tmpjd45me00/prophet_models5exiiur/prophet_model-20260803145244.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:44 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:44 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ohbzjxi2.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gy710c1j.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=68056', 'data', 'file=/tmp/tmpjd45me00/ohbzjxi2.json', 'init=/tmp/tmpjd45me00/gy710c1j.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelvfu351ne/prophet_model-20260803145245.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:45 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_41_dept_40
Build prophet model for  store_41_dept_41

14:52:45 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/lvmlv7oh.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ntd6nlun.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=45183', 'data', 'file=/tmp/tmpjd45me00/lvmlv7oh.json', 'init=/tmp/tmpjd45me00/ntd6nlun.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelll5qabhs/prophet_model-20260803145245.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:45 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:45 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jm84zosv.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/p2amp8fl.json

Build prophet model for  store_41_dept_42
Build prophet model for  store_41_dept_44

DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=77111', 'data', 'file=/tmp/tmpjd45me00/jm84zosv.json', 'init=/tmp/tmpjd45me00/p2amp8fl.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelnyfl92t2/prophet_model-20260803145245.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:45 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:45 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rz0m61yu.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/yoqko2dv.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=53126', 'data', 'file=/tmp/tmpjd45me00/rz0m61yu.json', 'init=/tmp/tmpjd45me00/yoqko2dv.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelj19md3kx/prophet_model-20260803145245.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:52:45 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_41_dept_45

14:52:46 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_ysjo4xt.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/387xj8re.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=72649', 'data', 'file=/tmp/tmpjd45me00/_ysjo4xt.json', 'init=/tmp/tmpjd45me00/387xj8re.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model5jm31zjs/prophet_model-20260803145246.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:46 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:46 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/v9bi4jkz.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gpyfj2ak.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=62922', 'data', 'file=/tmp/tmpjd45me00/v9bi4jkz.json', 'init=/tmp/tmpjd45me00/gpyfj2ak.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model2zkdat5w/prophet_model-20260803145246.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:46 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_41_dept_46
Build prophet model for  store_41_dept_49

14:52:46 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mgzp1rr2.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pjy1jl4l.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=71097', 'data', 'file=/tmp/tmpjd45me00/mgzp1rr2.json', 'init=/tmp/tmpjd45me00/pjy1jl4l.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelqajzoi4p/prophet_model-20260803145247.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:47 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:47 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/m54_qb84.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gzg8gbop.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=17451', 'data', 'file=/tmp/tmpjd45me00/m54_qb84.json', 'init=/tmp/tmpjd45me00/gzg8gbop.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model6l190bfs/prophet_model-20260803145247.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:52:47 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_41_dept_5
Build prophet model for  store_41_dept_51

14:52:47 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fdtxkbdv.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dnd9gurf.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=11322', 'data', 'file=/tmp/tmpjd45me00/fdtxkbdv.json', 'init=/tmp/tmpjd45me00/dnd9gurf.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modele6of89pb/prophet_model-20260803145247.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:47 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:47 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dor4vefc.json

Build prophet model for  store_41_dept_52
Build prophet model for  store_41_dept_54

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vnd___2e.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=63931', 'data', 'file=/tmp/tmpjd45me00/dor4vefc.json', 'init=/tmp/tmpjd45me00/vnd___2e.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelol78lw1_/prophet_model-20260803145247.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:47 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:48 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/yle6qiuw.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fey90c5y.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=65435', 'data', 'file=/tmp/tmpjd45me00/yle6qiuw.json', 'init=/tmp/tmpjd45me00/fey90c5y.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model8y3gl9iz/prophet_model-20260803145248.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:48 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:48 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_41_dept_55
Build prophet model for  store_41_dept_56

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/c6a069r2.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ncvkwnmp.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=85422', 'data', 'file=/tmp/tmpjd45me00/c6a069r2.json', 'init=/tmp/tmpjd45me00/ncvkwnmp.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeljr51yqgb/prophet_model-20260803145248.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:48 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:48 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zxgg8e_z.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/guicdwv7.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=81619', 'data', 'file=/tmp/tmpjd45me00/zxgg8e_z.json', 'init=/tmp/tmpjd45me00/guicdwv7.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelpux1bpkd/prophet_model-20260803145248.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:48 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:48 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/i4twle8f.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wp9ijsil.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=65108', 'data', 'file=/tmp/tmpjd45me00/i4twle8f.json', 'init=/tmp/tmpjd45me00/wp9ijsil.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_wh247z6/prophet_model-20260803145248.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:48 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_41_dept_58
Build prophet model for  store_41_dept_59

14:52:48 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9vxsinev.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ngo71012.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=41212', 'data', 'file=/tmp/tmpjd45me00/9vxsinev.json', 'init=/tmp/tmpjd45me00/ngo71012.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model4bwvtid9/prophet_model-20260803145249.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:49 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:49 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/u0px1zsu.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/eoz616_2.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=89321', 'data', 'file=/tmp/tmpjd45me00/u0px1zsu.json', 'init=/tmp/tmpjd45me00/eoz616_2.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelegld9xry/prophet_model-20260803145249.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:49 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_41_dept_6
Build prophet model for  store_41_dept_60

14:52:49 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1neh0i54.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3c6mb6no.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=34383', 'data', 'file=/tmp/tmpjd45me00/1neh0i54.json', 'init=/tmp/tmpjd45me00/3c6mb6no.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelcj60alit/prophet_model-20260803145249.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:49 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:49 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/81tv7vz7.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/uumti_p6.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=84447', 'data', 'file=/tmp/tmpjd45me00/81tv7vz7.json', 'init=/tmp/tmpjd45me00/uumti_p6.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model2ukg2x_n/prophet_model-20260803145249.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:49 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_41_dept_67
Build prophet model for  store_41_dept_7

14:52:49 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/lq8bvg2_.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/z3jvc4j8.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=33280', 'data', 'file=/tmp/tmpjd45me00/lq8bvg2_.json', 'init=/tmp/tmpjd45me00/z3jvc4j8.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelgo5_xb59/prophet_model-20260803145249.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:49 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:49 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_41_dept_71
Build prophet model for  store_41_dept_72

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4aex7ihr.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/u50yabcd.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=12984', 'data', 'file=/tmp/tmpjd45me00/4aex7ihr.json', 'init=/tmp/tmpjd45me00/u50yabcd.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelyhans884/prophet_model-20260803145249.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:49 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:49 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/i0r7pe86.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/el3ya4lj.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=91063', 'data', 'file=/tmp/tmpjd45me00/i0r7pe86.json', 'init=/tmp/tmpjd45me00/el3ya4lj.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model4dnq35gk/prophet_model-20260803145250.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:50 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:50 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_41_dept_74

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/egi6ykho.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6c4r6yal.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=14532', 'data', 'file=/tmp/tmpjd45me00/egi6ykho.json', 'init=/tmp/tmpjd45me00/6c4r6yal.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modellef9ktcq/prophet_model-20260803145250.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:50 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:50 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_41_dept_79
Build prophet model for  store_41_dept_8

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8uycctnn.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xba6djj5.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=47694', 'data', 'file=/tmp/tmpjd45me00/8uycctnn.json', 'init=/tmp/tmpjd45me00/xba6djj5.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model368xbfue/prophet_model-20260803145250.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:50 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:50 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jtltvq6c.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jxc9ucuv.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=9088', 'data', 'file=/tmp/tmpjd45me00/jtltvq6c.json', 'init=/tmp/tmpjd45me00/jxc9ucuv.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_4sh6pa_/prophet_model-20260803145250.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:50 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_41_dept_80

14:52:51 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/of8880fi.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1o3womdo.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=13555', 'data', 'file=/tmp/tmpjd45me00/of8880fi.json', 'init=/tmp/tmpjd45me00/1o3womdo.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelp7n4qffu/prophet_model-20260803145251.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:51 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:51 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_41_dept_81

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5f8079wb.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/tcxvcwdc.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=58386', 'data', 'file=/tmp/tmpjd45me00/5f8079wb.json', 'init=/tmp/tmpjd45me00/tcxvcwdc.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model72s5kmoa/prophet_model-20260803145251.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:51 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:51 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_41_dept_82

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/e_07umyw.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/s5y5_5gh.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=48350', 'data', 'file=/tmp/tmpjd45me00/e_07umyw.json', 'init=/tmp/tmpjd45me00/s5y5_5gh.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model69myjxyd/prophet_model-20260803145251.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:51 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:51 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_41_dept_83
Build prophet model for  store_41_dept_85

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/tdxo9rvq.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0l9s0d52.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=98123', 'data', 'file=/tmp/tmpjd45me00/tdxo9rvq.json', 'init=/tmp/tmpjd45me00/0l9s0d52.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelehqoxyvw/prophet_model-20260803145251.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:52 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:52 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2_8271sc.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5iw35h5i.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=87848', 'data', 'file=/tmp/tmpjd45me00/2_8271sc.json', 'init=/tmp/tmpjd45me00/5iw35h5i.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modely9x_5lk5/prophet_model-20260803145252.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:52 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_41_dept_87

14:52:52 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/cbrpowdy.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9ja6ag_h.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=2507', 'data', 'file=/tmp/tmpjd45me00/cbrpowdy.json', 'init=/tmp/tmpjd45me00/9ja6ag_h.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelaw6flhrc/prophet_model-20260803145252.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:52 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:52 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_41_dept_9
Build prophet model for  store_41_dept_90

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rm0bebm9.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/h9kgdivw.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=95593', 'data', 'file=/tmp/tmpjd45me00/rm0bebm9.json', 'init=/tmp/tmpjd45me00/h9kgdivw.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelzrpgi96s/prophet_model-20260803145253.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:53 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:53 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_yiywoak.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/r98jv_2k.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=35626', 'data', 'file=/tmp/tmpjd45me00/_yiywoak.json', 'init=/tmp/tmpjd45me00/r98jv_2k.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model45s_k9n3/prophet_model-20260803145253.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:53 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:53 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_41_dept_91
Build prophet model for  store_41_dept_92

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/l1168i5m.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rae5zett.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=13170', 'data', 'file=/tmp/tmpjd45me00/l1168i5m.json', 'init=/tmp/tmpjd45me00/rae5zett.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model4s7ac52f/prophet_model-20260803145253.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:53 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:53 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_41_dept_93
Build prophet model for  store_41_dept_94

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/c9t8x57o.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ofo7kc1r.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=26738', 'data', 'file=/tmp/tmpjd45me00/c9t8x57o.json', 'init=/tmp/tmpjd45me00/ofo7kc1r.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelia1qb983/prophet_model-20260803145253.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:53 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:53 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ptq0dfbt.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/r8dzotp3.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=68617', 'data', 'file=/tmp/tmpjd45me00/ptq0dfbt.json', 'init=/tmp/tmpjd45me00/r8dzotp3.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelkcvkj__i/prophet_model-20260803145253.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:53 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:53 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/luoithwd.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1x59kftv.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=38775', 'data', 'file=/tmp/tmpjd45me00/luoithwd.json', 'init=/tmp/tmpjd45me00/1x59kftv.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelvhgf89dt/prophet_model-20260803145254.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:54 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_41_dept_95
Build prophet model for  store_41_dept_96

14:52:54 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rjig553z.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zj859ksn.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=41250', 'data', 'file=/tmp/tmpjd45me00/rjig553z.json', 'init=/tmp/tmpjd45me00/zj859ksn.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelta7xzfiv/prophet_model-20260803145254.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:54 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:54 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vcg0v__3.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/woey2n6k.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=42049', 'data', 'file=/tmp/tmpjd45me00/vcg0v__3.json', 'init=/tmp/tmpjd45me00/woey2n6k.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelk8v4pra1/prophet_model-20260803145254.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:54 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_41_dept_97
Build prophet model for  store_41_dept_98

14:52:54 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rg722pke.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/c91smw9h.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=97810', 'data', 'file=/tmp/tmpjd45me00/rg722pke.json', 'init=/tmp/tmpjd45me00/c91smw9h.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelnwdsujuh/prophet_model-20260803145254.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:54 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:54 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1u498430.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5g0edhb5.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=82562', 'data', 'file=/tmp/tmpjd45me00/1u498430.json', 'init=/tmp/tmpjd45me00/5g0edhb5.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelbbuln_n7/prophet_model-20260803145254.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:54 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_42_dept_1
Build prophet model for  store_42_dept_10

14:52:54 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/01xw_iww.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9jrx0y66.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=88354', 'data', 'file=/tmp/tmpjd45me00/01xw_iww.json', 'init=/tmp/tmpjd45me00/9jrx0y66.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modely6ltr5m4/prophet_model-20260803145254.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:54 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:54 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/j941tz2g.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jsk045gj.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=26688', 'data', 'file=/tmp/tmpjd45me00/j941tz2g.json', 'init=/tmp/tmpjd45me00/jsk045gj.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelzx1p4071/prophet_model-20260803145254.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:54 - cmdstanpy - INFO - Chain [1] start processing

Build prophet model for  store_42_dept_11
Build prophet model for  store_42_dept_12

INFO:cmdstanpy:Chain [1] start processing
14:52:55 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/kcmyn3gd.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1fqkfd87.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=32670', 'data', 'file=/tmp/tmpjd45me00/kcmyn3gd.json', 'init=/tmp/tmpjd45me00/1fqkfd87.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelggoexxjz/prophet_model-20260803145255.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:55 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:55 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/00ph_n62.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/tje9usn9.json
DEBUG:cmdstanpy:idx 0

Build prophet model for  store_42_dept_13
Build prophet model for  store_42_dept_14

DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=20433', 'data', 'file=/tmp/tmpjd45me00/00ph_n62.json', 'init=/tmp/tmpjd45me00/tje9usn9.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelzp6p0ts6/prophet_model-20260803145255.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:55 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:55 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/n1fo53kk.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/n2t1lt7t.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=38231', 'data', 'file=/tmp/tmpjd45me00/n1fo53kk.json', 'init=/tmp/tmpjd45me00/n2t1lt7t.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeleg3tjnyh/prophet_model-20260803145255.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:55 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:55 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/j4lw6wh7.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dhbvg8t8.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=58035', 'data', 'file=/tmp/tmpjd45me00/j4lw6wh7.json', 'init=/tmp/tmpjd45me00/dhbvg8t8.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeln9flcjmv/prophet_model-20260803145255.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:55 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_42_dept_16
Build prophet model for  store_42_dept_17

14:52:55 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pu24wl10.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/x9cwtua4.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=29529', 'data', 'file=/tmp/tmpjd45me00/pu24wl10.json', 'init=/tmp/tmpjd45me00/x9cwtua4.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model12_pkt5v/prophet_model-20260803145256.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:52:56 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_42_dept_18

14:52:57 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pppear77.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/d_qo49k7.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=68471', 'data', 'file=/tmp/tmpjd45me00/pppear77.json', 'init=/tmp/tmpjd45me00/d_qo49k7.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model029n5ihd/prophet_model-20260803145257.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:57 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:57 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_42_dept_2
Build prophet model for  store_42_dept_21

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/394g3h57.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/kddsb1pm.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=12169', 'data', 'file=/tmp/tmpjd45me00/394g3h57.json', 'init=/tmp/tmpjd45me00/kddsb1pm.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model4wextegp/prophet_model-20260803145257.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:57 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:57 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/70vrufiq.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/q44ky5_0.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=73177', 'data', 'file=/tmp/tmpjd45me00/70vrufiq.json', 'init=/tmp/tmpjd45me00/q44ky5_0.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeloz88xyxk/prophet_model-20260803145258.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:58 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:58 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_42_dept_25

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_l4udv96.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/e3c3kb8n.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=7898', 'data', 'file=/tmp/tmpjd45me00/_l4udv96.json', 'init=/tmp/tmpjd45me00/e3c3kb8n.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelky1_zm2_/prophet_model-20260803145258.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:58 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:58 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dhmn7h3l.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/lzz2wb2b.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=30727', 'data', 'file=/tmp/tmpjd45me00/dhmn7h3l.json', 'init=/tmp/tmpjd45me00/lzz2wb2b.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelbc3tu4h2/prophet_model-20260803145258.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:58 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_42_dept_28
Build prophet model for  store_42_dept_3

14:52:58 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gay5o_6h.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8nws13_p.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=28844', 'data', 'file=/tmp/tmpjd45me00/gay5o_6h.json', 'init=/tmp/tmpjd45me00/8nws13_p.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeln036eigh/prophet_model-20260803145258.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:58 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:58 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_42_dept_31

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wy364lno.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fmqvwr5s.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=94147', 'data', 'file=/tmp/tmpjd45me00/wy364lno.json', 'init=/tmp/tmpjd45me00/fmqvwr5s.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelkwammus6/prophet_model-20260803145258.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:58 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:58 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/k0ub35d5.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/l0whtkfp.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=70458', 'data', 'file=/tmp/tmpjd45me00/k0ub35d5.json', 'init=/tmp/tmpjd45me00/l0whtkfp.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelv0oxpv45/prophet_model-20260803145259.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:59 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_42_dept_32
Build prophet model for  store_42_dept_38

14:52:59 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6q336sl_.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/80cljlac.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=39809', 'data', 'file=/tmp/tmpjd45me00/6q336sl_.json', 'init=/tmp/tmpjd45me00/80cljlac.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeltmgtwxts/prophet_model-20260803145259.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:59 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:59 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_42_dept_4
Build prophet model for  store_42_dept_40

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9wofe5wq.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2q4v31f1.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=63321', 'data', 'file=/tmp/tmpjd45me00/9wofe5wq.json', 'init=/tmp/tmpjd45me00/2q4v31f1.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelcf0h3pxs/prophet_model-20260803145259.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:59 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:59 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/eznkneks.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gpd4mjp4.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=77371', 'data', 'file=/tmp/tmpjd45me00/eznkneks.json', 'init=/tmp/tmpjd45me00/gpd4mjp4.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model2xpr5630/prophet_model-20260803145259.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:52:59 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:52:59 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_42_dept_42
Build prophet model for  store_42_dept_46

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9xv4e924.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zllzm6yj.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=49817', 'data', 'file=/tmp/tmpjd45me00/9xv4e924.json', 'init=/tmp/tmpjd45me00/zllzm6yj.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model5nlm_gaw/prophet_model-20260803145300.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:00 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:00 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wvipp9o_.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/780zy70g.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=3158', 'data', 'file=/tmp/tmpjd45me00/wvipp9o_.json', 'init=/tmp/tmpjd45me00/780zy70g.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelw69rf6i5/prophet_model-20260803145300.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:00 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:00 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_42_dept_5
Build prophet model for  store_42_dept_52

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/raxg7ukd.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/d7y07cok.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=2985', 'data', 'file=/tmp/tmpjd45me00/raxg7ukd.json', 'init=/tmp/tmpjd45me00/d7y07cok.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelb4np8rby/prophet_model-20260803145300.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:00 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:00 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ueb96md5.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5qntbfa2.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=94954', 'data', 'file=/tmp/tmpjd45me00/ueb96md5.json', 'init=/tmp/tmpjd45me00/5qntbfa2.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelbhblfzny/prophet_model-20260803145300.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:00 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_42_dept_59

14:53:00 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/s5mryjj3.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/s3nl5cci.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=70687', 'data', 'file=/tmp/tmpjd45me00/s5mryjj3.json', 'init=/tmp/tmpjd45me00/s3nl5cci.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelv2uvixr7/prophet_model-20260803145300.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:00 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:00 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/44zjf6b9.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/sscc07py.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=66098', 'data', 'file=/tmp/tmpjd45me00/44zjf6b9.json', 'init=/tmp/tmpjd45me00/sscc07py.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelyjvws48y/prophet_model-20260803145301.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:01 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_42_dept_60
Build prophet model for  store_42_dept_67

14:53:01 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wdhgt7mj.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/z7ku16gj.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=71580', 'data', 'file=/tmp/tmpjd45me00/wdhgt7mj.json', 'init=/tmp/tmpjd45me00/z7ku16gj.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model35v5l42s/prophet_model-20260803145301.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:01 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:01 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_42_dept_7

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1sx8wwhv.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mcqv4ttp.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=28450', 'data', 'file=/tmp/tmpjd45me00/1sx8wwhv.json', 'init=/tmp/tmpjd45me00/mcqv4ttp.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeldr6cf4ad/prophet_model-20260803145301.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:01 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:01 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/038x79mw.json

Build prophet model for  store_42_dept_74
Build prophet model for  store_42_dept_79

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/y4youc5v.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=77781', 'data', 'file=/tmp/tmpjd45me00/038x79mw.json', 'init=/tmp/tmpjd45me00/y4youc5v.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelnyoc4igb/prophet_model-20260803145301.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:01 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:01 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/kyntsstv.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jwcw_ii1.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=88629', 'data', 'file=/tmp/tmpjd45me00/kyntsstv.json', 'init=/tmp/tmpjd45me00/jwcw_ii1.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelolr9991x/prophet_model-20260803145301.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:01 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:02 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_42_dept_8

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/z1a9qlvy.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/lor6x18x.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=91833', 'data', 'file=/tmp/tmpjd45me00/z1a9qlvy.json', 'init=/tmp/tmpjd45me00/lor6x18x.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelrl49rp5v/prophet_model-20260803145302.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:02 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:02 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zrdsxu5o.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/11kwbmjz.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=11967', 'data', 'file=/tmp/tmpjd45me00/zrdsxu5o.json', 'init=/tmp/tmpjd45me00/11kwbmjz.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelu3hwqqph/prophet_model-20260803145302.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:02 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_42_dept_80
Build prophet model for  store_42_dept_81

14:53:02 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/tzjd4eej.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/01i31xra.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=308', 'data', 'file=/tmp/tmpjd45me00/tzjd4eej.json', 'init=/tmp/tmpjd45me00/01i31xra.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeljz_km4r1/prophet_model-20260803145302.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:02 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:02 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/399l28nz.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rof55d_7.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None

Build prophet model for  store_42_dept_82
Build prophet model for  store_42_dept_83

DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=55225', 'data', 'file=/tmp/tmpjd45me00/399l28nz.json', 'init=/tmp/tmpjd45me00/rof55d_7.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelp99vh032/prophet_model-20260803145302.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:02 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:02 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ct3awy_y.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/f8eixqhd.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=56061', 'data', 'file=/tmp/tmpjd45me00/ct3awy_y.json', 'init=/tmp/tmpjd45me00/f8eixqhd.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelo_saskir/prophet_model-20260803145302.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:02 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:02 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_42_dept_85

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7i05vtbu.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jt1zplcx.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=17828', 'data', 'file=/tmp/tmpjd45me00/7i05vtbu.json', 'init=/tmp/tmpjd45me00/jt1zplcx.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model8x66aiv7/prophet_model-20260803145303.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:03 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:03 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_42_dept_9

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1_zertia.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/yq3xgf43.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=18370', 'data', 'file=/tmp/tmpjd45me00/1_zertia.json', 'init=/tmp/tmpjd45me00/yq3xgf43.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_t286bzk/prophet_model-20260803145303.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:03 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:03 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_42_dept_90

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/q2wqb_70.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vnia5a1q.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=93102', 'data', 'file=/tmp/tmpjd45me00/q2wqb_70.json', 'init=/tmp/tmpjd45me00/vnia5a1q.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model19xknfk8/prophet_model-20260803145303.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:03 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:03 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_42_dept_91

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/apg5gj3p.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xnxx537q.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=16317', 'data', 'file=/tmp/tmpjd45me00/apg5gj3p.json', 'init=/tmp/tmpjd45me00/xnxx537q.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelx9wypnxr/prophet_model-20260803145303.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:03 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:03 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_42_dept_92

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/774pz544.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/n3k57qmr.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=21204', 'data', 'file=/tmp/tmpjd45me00/774pz544.json', 'init=/tmp/tmpjd45me00/n3k57qmr.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_syb9r37/prophet_model-20260803145304.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:04 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:04 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_42_dept_93

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rsx9u5kr.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fyiovpzi.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=7987', 'data', 'file=/tmp/tmpjd45me00/rsx9u5kr.json', 'init=/tmp/tmpjd45me00/fyiovpzi.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelctwq5r78/prophet_model-20260803145304.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:04 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:04 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_42_dept_94
Build prophet model for  store_42_dept_95

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ob0c0_5_.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xg74mwnk.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=53465', 'data', 'file=/tmp/tmpjd45me00/ob0c0_5_.json', 'init=/tmp/tmpjd45me00/xg74mwnk.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelgfy8lu8z/prophet_model-20260803145304.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:04 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:04 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/x1rco6eo.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/18ilkmqp.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=71330', 'data', 'file=/tmp/tmpjd45me00/x1rco6eo.json', 'init=/tmp/tmpjd45me00/18ilkmqp.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model9r4lgl8t/prophet_model-20260803145304.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:04 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_42_dept_96

14:53:05 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/73df38s7.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xb_r65lr.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=31161', 'data', 'file=/tmp/tmpjd45me00/73df38s7.json', 'init=/tmp/tmpjd45me00/xb_r65lr.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeltadptcwy/prophet_model-20260803145305.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:05 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:05 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_42_dept_97
Build prophet model for  store_42_dept_98

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5ck5h2mp.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qluisam5.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=89661', 'data', 'file=/tmp/tmpjd45me00/5ck5h2mp.json', 'init=/tmp/tmpjd45me00/qluisam5.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeltwdn58m5/prophet_model-20260803145305.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:05 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:05 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/h5jmq3ps.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/tr4ss379.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=44582', 'data', 'file=/tmp/tmpjd45me00/h5jmq3ps.json', 'init=/tmp/tmpjd45me00/tr4ss379.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model7xycuu0e/prophet_model-20260803145305.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:05 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:05 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_43_dept_1

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/f6x63ucz.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/au84xder.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=50603', 'data', 'file=/tmp/tmpjd45me00/f6x63ucz.json', 'init=/tmp/tmpjd45me00/au84xder.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model23cn6c9z/prophet_model-20260803145306.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:06 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:06 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_43_dept_10
Build prophet model for  store_43_dept_11

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pffiaujc.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/faqqca_6.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=93925', 'data', 'file=/tmp/tmpjd45me00/pffiaujc.json', 'init=/tmp/tmpjd45me00/faqqca_6.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelo483x68a/prophet_model-20260803145306.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:06 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:06 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xh86skwb.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/cx2ggdgi.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=14724', 'data', 'file=/tmp/tmpjd45me00/xh86skwb.json', 'init=/tmp/tmpjd45me00/cx2ggdgi.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model0i64f8w4/prophet_model-20260803145306.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:06 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:06 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7anb52oy.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/q0nm41eg.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=55439', 'data', 'file=/tmp/tmpjd45me00/7anb52oy.json', 'init=/tmp/tmpjd45me00/q0nm41eg.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_6319p5c/prophet_model-20260803145306.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:06 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_43_dept_12
Build prophet model for  store_43_dept_13

14:53:07 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/cjj6jgz_.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jfylkdtd.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=67003', 'data', 'file=/tmp/tmpjd45me00/cjj6jgz_.json', 'init=/tmp/tmpjd45me00/jfylkdtd.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelwslr254c/prophet_model-20260803145307.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:07 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_43_dept_14

14:53:07 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gsvsf_qg.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_6p0j13k.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=59835', 'data', 'file=/tmp/tmpjd45me00/gsvsf_qg.json', 'init=/tmp/tmpjd45me00/_6p0j13k.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelvulqvccm/prophet_model-20260803145307.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:07 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:07 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ctdfzy8d.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_lil9ejo.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=66005', 'data', 'file=/tmp/tmpjd45me00/ctdfzy8d.json', 'init=/tmp/tmpjd45me00/_lil9ejo.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modellnv_r60c/prophet_model-20260803145307.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:07 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_43_dept_16
Build prophet model for  store_43_dept_17

14:53:08 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/n3xazssi.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5opybh2_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=4264', 'data', 'file=/tmp/tmpjd45me00/n3xazssi.json', 'init=/tmp/tmpjd45me00/5opybh2_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model19i9ue4v/prophet_model-20260803145308.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:53:08 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_43_dept_18

14:53:09 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/cn35e3_8.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/kf03edc9.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=62842', 'data', 'file=/tmp/tmpjd45me00/cn35e3_8.json', 'init=/tmp/tmpjd45me00/kf03edc9.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model6ga9da5f/prophet_model-20260803145309.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:09 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_43_dept_2

14:53:09 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/c8emsgcj.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/w83wd427.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=6334', 'data', 'file=/tmp/tmpjd45me00/c8emsgcj.json', 'init=/tmp/tmpjd45me00/w83wd427.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelzh7c7et3/prophet_model-20260803145309.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:09 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:10 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_43_dept_21
Build prophet model for  store_43_dept_25

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3ud4hj2p.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hds0xksn.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=58792', 'data', 'file=/tmp/tmpjd45me00/3ud4hj2p.json', 'init=/tmp/tmpjd45me00/hds0xksn.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model7urtmowy/prophet_model-20260803145310.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:10 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:10 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/c71uj26g.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/kotg6dvq.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=50273', 'data', 'file=/tmp/tmpjd45me00/c71uj26g.json', 'init=/tmp/tmpjd45me00/kotg6dvq.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeluxhct9sj/prophet_model-20260803145310.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:10 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:10 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wqr6hn6v.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/99b_t27v.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=41354', 'data', 'file=/tmp/tmpjd45me00/wqr6hn6v.json', 'init=/tmp/tmpjd45me00/99b_t27v.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelpe9c4o_g/prophet_model-20260803145310.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:10 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_43_dept_28
Build prophet model for  store_43_dept_3

14:53:10 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bdwbfzlx.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_0_9gjkj.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=25296', 'data', 'file=/tmp/tmpjd45me00/bdwbfzlx.json', 'init=/tmp/tmpjd45me00/_0_9gjkj.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelnsu2lliy/prophet_model-20260803145311.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:11 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:11 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bq0eb8r6.json

Build prophet model for  store_43_dept_38
Build prophet model for  store_43_dept_4

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/juqfny7a.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=77662', 'data', 'file=/tmp/tmpjd45me00/bq0eb8r6.json', 'init=/tmp/tmpjd45me00/juqfny7a.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model40e4t_r2/prophet_model-20260803145311.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:11 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:11 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/lbh6s_hs.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/np1t7at_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=66529', 'data', 'file=/tmp/tmpjd45me00/lbh6s_hs.json', 'init=/tmp/tmpjd45me00/np1t7at_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelhfhjjo_p/prophet_model-20260803145311.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:11 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_43_dept_40

14:53:11 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/stpamw9w.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mmt1tp1y.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=54410', 'data', 'file=/tmp/tmpjd45me00/stpamw9w.json', 'init=/tmp/tmpjd45me00/mmt1tp1y.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelepy_t2my/prophet_model-20260803145311.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:11 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:11 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rr5ddsfo.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2ld5c17r.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=36726', 'data', 'file=/tmp/tmpjd45me00/rr5ddsfo.json', 'init=/tmp/tmpjd45me00/2ld5c17r.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model5ucnw5fi/prophet_model-20260803145312.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:12 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_43_dept_42
Build prophet model for  store_43_dept_46

14:53:12 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gkkfel02.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_oe67g50.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=93915', 'data', 'file=/tmp/tmpjd45me00/gkkfel02.json', 'init=/tmp/tmpjd45me00/_oe67g50.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelp05rv9gj/prophet_model-20260803145312.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:12 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:12 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wcj8pa_3.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/t7pcpcm1.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=1661', 'data', 'file=/tmp/tmpjd45me00/wcj8pa_3.json', 'init=/tmp/tmpjd45me00/t7pcpcm1.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelyrlxwpqm/prophet_model-20260803145312.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:53:12 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_43_dept_52
Build prophet model for  store_43_dept_59

14:53:13 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/btlsw5qa.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xags4dg7.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=28251', 'data', 'file=/tmp/tmpjd45me00/btlsw5qa.json', 'init=/tmp/tmpjd45me00/xags4dg7.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelm0yzdnk1/prophet_model-20260803145313.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:53:13 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_43_dept_6

14:53:15 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/oxfxaqep.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6888xphd.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=1466', 'data', 'file=/tmp/tmpjd45me00/oxfxaqep.json', 'init=/tmp/tmpjd45me00/6888xphd.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modely6eanx4q/prophet_model-20260803145315.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:15 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:15 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rfucjtmp.json

Build prophet model for  store_43_dept_60
Build prophet model for  store_43_dept_67

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/yx6i7d3j.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=74906', 'data', 'file=/tmp/tmpjd45me00/rfucjtmp.json', 'init=/tmp/tmpjd45me00/yx6i7d3j.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model75l2tz1j/prophet_model-20260803145315.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:15 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:15 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/t_99f6gb.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/u8mzqhkh.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=83374', 'data', 'file=/tmp/tmpjd45me00/t_99f6gb.json', 'init=/tmp/tmpjd45me00/u8mzqhkh.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelice1o890/prophet_model-20260803145315.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:15 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:15 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ix0kam5t.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/78b6kdvl.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=72691', 'data', 'file=/tmp/tmpjd45me00/ix0kam5t.json', 'init=/tmp/tmpjd45me00/78b6kdvl.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeljsqkscsd/prophet_model-20260803145315.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:15 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_43_dept_7
Build prophet model for  store_43_dept_72

14:53:15 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/42p4yctn.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_cy4d5y8.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=12407', 'data', 'file=/tmp/tmpjd45me00/42p4yctn.json', 'init=/tmp/tmpjd45me00/_cy4d5y8.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model619so_gv/prophet_model-20260803145315.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:15 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_43_dept_74

14:53:16 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/a9cziffu.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1sk7813b.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=18836', 'data', 'file=/tmp/tmpjd45me00/a9cziffu.json', 'init=/tmp/tmpjd45me00/1sk7813b.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelx_7cvkiu/prophet_model-20260803145316.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:16 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_43_dept_79

14:53:16 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/f9de2upv.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/g_61exla.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=27386', 'data', 'file=/tmp/tmpjd45me00/f9de2upv.json', 'init=/tmp/tmpjd45me00/g_61exla.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeltuqw3etc/prophet_model-20260803145316.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:16 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_43_dept_8

14:53:17 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/iw4wqotz.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1l9c1y2g.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=93556', 'data', 'file=/tmp/tmpjd45me00/iw4wqotz.json', 'init=/tmp/tmpjd45me00/1l9c1y2g.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modela9r8_j2q/prophet_model-20260803145317.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:17 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_43_dept_80

14:53:17 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ggbqipj3.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/i55o6mca.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=52014', 'data', 'file=/tmp/tmpjd45me00/ggbqipj3.json', 'init=/tmp/tmpjd45me00/i55o6mca.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model4xamgl_x/prophet_model-20260803145317.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:17 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_43_dept_81

14:53:18 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zs0o9whj.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/k062jxg6.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=99863', 'data', 'file=/tmp/tmpjd45me00/zs0o9whj.json', 'init=/tmp/tmpjd45me00/k062jxg6.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model5iosjtvv/prophet_model-20260803145318.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:18 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_43_dept_82

14:53:18 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1f7q1c43.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vwaorq_s.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=33572', 'data', 'file=/tmp/tmpjd45me00/1f7q1c43.json', 'init=/tmp/tmpjd45me00/vwaorq_s.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_q30r8kx/prophet_model-20260803145319.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:19 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:19 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_43_dept_83
Build prophet model for  store_43_dept_85

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/l1_4ikhj.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bfv8ejxq.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=58233', 'data', 'file=/tmp/tmpjd45me00/l1_4ikhj.json', 'init=/tmp/tmpjd45me00/bfv8ejxq.json', 'output', 'file=/tmp/tmpjd45me00/prophet_models8q5phhr/prophet_model-20260803145319.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:53:19 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:19 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/t9inw5ov.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/av0bfki3.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=55207', 'data', 'file=/tmp/tmpjd45me00/t9inw5ov.json', 'init=/tmp/tmpjd45me00/av0bfki3.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeliyo12zsh/prophet_model-20260803145320.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:20 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:20 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3e2569hb.json

Build prophet model for  store_43_dept_9
Build prophet model for  store_43_dept_90

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0xkd4wfw.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=39436', 'data', 'file=/tmp/tmpjd45me00/3e2569hb.json', 'init=/tmp/tmpjd45me00/0xkd4wfw.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelezmn0233/prophet_model-20260803145320.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:20 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:20 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/azokx4cz.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mzbtk0hv.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=86195', 'data', 'file=/tmp/tmpjd45me00/azokx4cz.json', 'init=/tmp/tmpjd45me00/mzbtk0hv.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelwk2_la30/prophet_model-20260803145320.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:20 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:20 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_ows41wb.json

Build prophet model for  store_43_dept_91
Build prophet model for  store_43_dept_92

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vmrkvgjr.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=53221', 'data', 'file=/tmp/tmpjd45me00/_ows41wb.json', 'init=/tmp/tmpjd45me00/vmrkvgjr.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model2azdrdtg/prophet_model-20260803145320.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:20 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:20 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rvl0hyvf.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/sm_xsqvo.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=68982', 'data', 'file=/tmp/tmpjd45me00/rvl0hyvf.json', 'init=/tmp/tmpjd45me00/sm_xsqvo.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modele2ua2cj7/prophet_model-20260803145320.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:20 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:20 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_43_dept_93
Build prophet model for  store_43_dept_94

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0zpmlphg.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6275p411.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=45803', 'data', 'file=/tmp/tmpjd45me00/0zpmlphg.json', 'init=/tmp/tmpjd45me00/6275p411.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelskw6z2r4/prophet_model-20260803145321.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:21 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:21 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xtyvovpu.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_kcxco3n.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=87138', 'data', 'file=/tmp/tmpjd45me00/xtyvovpu.json', 'init=/tmp/tmpjd45me00/_kcxco3n.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelzxz11cfi/prophet_model-20260803145321.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:21 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:21 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6831gn2d.json

Build prophet model for  store_43_dept_95
Build prophet model for  store_43_dept_96

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/16o3shwp.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=20440', 'data', 'file=/tmp/tmpjd45me00/6831gn2d.json', 'init=/tmp/tmpjd45me00/16o3shwp.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeldbu4rdzd/prophet_model-20260803145321.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:21 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:21 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mak_izf8.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ba5hjd89.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=51837', 'data', 'file=/tmp/tmpjd45me00/mak_izf8.json', 'init=/tmp/tmpjd45me00/ba5hjd89.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelp6fw0myv/prophet_model-20260803145321.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:21 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:21 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_43_dept_97
Build prophet model for  store_43_dept_98

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dtv98ckx.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jggwzj66.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=57796', 'data', 'file=/tmp/tmpjd45me00/dtv98ckx.json', 'init=/tmp/tmpjd45me00/jggwzj66.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeltdjn03yb/prophet_model-20260803145321.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:21 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:21 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pu563o51.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ma9t8my8.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=85654', 'data', 'file=/tmp/tmpjd45me00/pu563o51.json', 'init=/tmp/tmpjd45me00/ma9t8my8.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeltndjl3aj/prophet_model-20260803145322.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:22 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:22 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5qu2xepx.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/cgrghly1.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=91144', 'data', 'file=/tmp/tmpjd45me00/5qu2xepx.json', 'init=/tmp/tmpjd45me00/cgrghly1.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeldkwiae55/prophet_model-20260803145322.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:22 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_44_dept_1
Build prophet model for  store_44_dept_10

14:53:22 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wnmhi3z8.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dciohnw7.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=43891', 'data', 'file=/tmp/tmpjd45me00/wnmhi3z8.json', 'init=/tmp/tmpjd45me00/dciohnw7.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelreflfkn9/prophet_model-20260803145322.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:22 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:22 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/l2tqfkgk.json

Build prophet model for  store_44_dept_11
Build prophet model for  store_44_dept_12

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qui3p4rc.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=15069', 'data', 'file=/tmp/tmpjd45me00/l2tqfkgk.json', 'init=/tmp/tmpjd45me00/qui3p4rc.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelsn9cmqfu/prophet_model-20260803145322.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:22 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:22 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/i4rqxb5t.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qu1jd361.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=68410', 'data', 'file=/tmp/tmpjd45me00/i4rqxb5t.json', 'init=/tmp/tmpjd45me00/qu1jd361.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model6sj_tug7/prophet_model-20260803145322.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:22 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:22 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1u3do71p.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ebvhumgm.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=83808', 'data', 'file=/tmp/tmpjd45me00/1u3do71p.json', 'init=/tmp/tmpjd45me00/ebvhumgm.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelxhu4yxq7/prophet_model-20260803145323.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:23 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_44_dept_13
Build prophet model for  store_44_dept_14

14:53:23 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/b_6z030g.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rfg1hxz3.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=94334', 'data', 'file=/tmp/tmpjd45me00/b_6z030g.json', 'init=/tmp/tmpjd45me00/rfg1hxz3.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelewvra2eq/prophet_model-20260803145323.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:23 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_44_dept_16

14:53:23 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/tz1zjbi9.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zu5x17u_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=60241', 'data', 'file=/tmp/tmpjd45me00/tz1zjbi9.json', 'init=/tmp/tmpjd45me00/zu5x17u_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelotz2n0rw/prophet_model-20260803145323.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:23 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:23 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_44_dept_17
Build prophet model for  store_44_dept_18

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/doe6v1in.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qb7brgo_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=32012', 'data', 'file=/tmp/tmpjd45me00/doe6v1in.json', 'init=/tmp/tmpjd45me00/qb7brgo_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_models0cx34io/prophet_model-20260803145323.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:53:23 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:25 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/cx8ol7pk.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/n7hodwqu.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=32309', 'data', 'file=/tmp/tmpjd45me00/cx8ol7pk.json', 'init=/tmp/tmpjd45me00/n7hodwqu.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelfk7rynng/prophet_model-20260803145325.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:25 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:25 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_44_dept_2

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ww051gwu.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/40xyxuwb.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=95266', 'data', 'file=/tmp/tmpjd45me00/ww051gwu.json', 'init=/tmp/tmpjd45me00/40xyxuwb.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelnz7z8ry9/prophet_model-20260803145325.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:25 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:25 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_44_dept_21
Build prophet model for  store_44_dept_25

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5cr68t12.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/o5cbnwni.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=19317', 'data', 'file=/tmp/tmpjd45me00/5cr68t12.json', 'init=/tmp/tmpjd45me00/o5cbnwni.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelc2_2x71p/prophet_model-20260803145325.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:25 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:25 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xd7z558u.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wcg3jk17.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=3366', 'data', 'file=/tmp/tmpjd45me00/xd7z558u.json', 'init=/tmp/tmpjd45me00/wcg3jk17.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeljc_zvq0k/prophet_model-20260803145325.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:25 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:25 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_44_dept_28
Build prophet model for  store_44_dept_3

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/01__yufa.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/m28phy4a.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=60635', 'data', 'file=/tmp/tmpjd45me00/01__yufa.json', 'init=/tmp/tmpjd45me00/m28phy4a.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model2oy4w_sx/prophet_model-20260803145326.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:26 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:26 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ha8ly83f.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/yon3qw0u.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=73893', 'data', 'file=/tmp/tmpjd45me00/ha8ly83f.json', 'init=/tmp/tmpjd45me00/yon3qw0u.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelfdk83anz/prophet_model-20260803145326.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:26 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:26 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pj6amj1q.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/x33v8pgq.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=66239', 'data', 'file=/tmp/tmpjd45me00/pj6amj1q.json', 'init=/tmp/tmpjd45me00/x33v8pgq.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model0r_134_f/prophet_model-20260803145326.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:26 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_44_dept_38
Build prophet model for  store_44_dept_4

14:53:26 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wooyp79l.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/k4wd6o0p.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=51465', 'data', 'file=/tmp/tmpjd45me00/wooyp79l.json', 'init=/tmp/tmpjd45me00/k4wd6o0p.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelfj0chldf/prophet_model-20260803145326.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:26 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:26 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_44_dept_40

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/331htcia.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0ia7kw6p.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=15257', 'data', 'file=/tmp/tmpjd45me00/331htcia.json', 'init=/tmp/tmpjd45me00/0ia7kw6p.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modele1ahmlru/prophet_model-20260803145326.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:26 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:26 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2q4aix8q.json

Build prophet model for  store_44_dept_42
Build prophet model for  store_44_dept_46

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vtntsc9l.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=99906', 'data', 'file=/tmp/tmpjd45me00/2q4aix8q.json', 'init=/tmp/tmpjd45me00/vtntsc9l.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelohb9r397/prophet_model-20260803145327.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:27 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:27 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/d5c2m1kr.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9yeeqanm.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=56109', 'data', 'file=/tmp/tmpjd45me00/d5c2m1kr.json', 'init=/tmp/tmpjd45me00/9yeeqanm.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeln732f1yi/prophet_model-20260803145327.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:27 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_44_dept_5

14:53:27 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/s2_kxm0h.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/al3b34yl.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=9611', 'data', 'file=/tmp/tmpjd45me00/s2_kxm0h.json', 'init=/tmp/tmpjd45me00/al3b34yl.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelnxp_sk0v/prophet_model-20260803145327.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:27 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:27 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_44_dept_52
Build prophet model for  store_44_dept_59

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mhhdlib_.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gahxsyso.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=76002', 'data', 'file=/tmp/tmpjd45me00/mhhdlib_.json', 'init=/tmp/tmpjd45me00/gahxsyso.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelzdp2_ude/prophet_model-20260803145327.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:27 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:27 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mwhgx_3q.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ou4j0m1e.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=30668', 'data', 'file=/tmp/tmpjd45me00/mwhgx_3q.json', 'init=/tmp/tmpjd45me00/ou4j0m1e.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeljn1eek1u/prophet_model-20260803145328.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:28 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:28 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/nj_a1vv0.json

Build prophet model for  store_44_dept_6
Build prophet model for  store_44_dept_60

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/y1g7v_nq.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=62739', 'data', 'file=/tmp/tmpjd45me00/nj_a1vv0.json', 'init=/tmp/tmpjd45me00/y1g7v_nq.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelrd7gsjiy/prophet_model-20260803145328.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:28 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:28 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/82gs_19s.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vh4yg7mn.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=11182', 'data', 'file=/tmp/tmpjd45me00/82gs_19s.json', 'init=/tmp/tmpjd45me00/vh4yg7mn.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelndreql6b/prophet_model-20260803145328.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:28 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:28 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jrgx_anb.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/884pwzxj.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=43035', 'data', 'file=/tmp/tmpjd45me00/jrgx_anb.json', 'init=/tmp/tmpjd45me00/884pwzxj.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeltpz4_ykj/prophet_model-20260803145328.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:28 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_44_dept_67
Build prophet model for  store_44_dept_7

14:53:28 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/41kul_mi.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mofqo3ta.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=38395', 'data', 'file=/tmp/tmpjd45me00/41kul_mi.json', 'init=/tmp/tmpjd45me00/mofqo3ta.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeltfe9xjsb/prophet_model-20260803145328.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:28 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:28 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/sg0qz6kf.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/d3o7vdxj.json
DEBUG:cmdstanpy:idx 0

Build prophet model for  store_44_dept_72
Build prophet model for  store_44_dept_74

DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=35990', 'data', 'file=/tmp/tmpjd45me00/sg0qz6kf.json', 'init=/tmp/tmpjd45me00/d3o7vdxj.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelmrbpaevw/prophet_model-20260803145328.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:28 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:28 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/351fwwdz.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ifvui698.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=9105', 'data', 'file=/tmp/tmpjd45me00/351fwwdz.json', 'init=/tmp/tmpjd45me00/ifvui698.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeltlncq8ax/prophet_model-20260803145328.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:28 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:29 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_44_dept_79

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7wxdsx64.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_pvqhjsu.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=1305', 'data', 'file=/tmp/tmpjd45me00/7wxdsx64.json', 'init=/tmp/tmpjd45me00/_pvqhjsu.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model9p8lrp5f/prophet_model-20260803145329.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:29 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:29 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_44_dept_8

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9xliucay.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qpap6qko.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=52077', 'data', 'file=/tmp/tmpjd45me00/9xliucay.json', 'init=/tmp/tmpjd45me00/qpap6qko.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeleober1tz/prophet_model-20260803145329.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:29 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:29 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_44_dept_80

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/oo4bn4x1.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/grm0uca3.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=13625', 'data', 'file=/tmp/tmpjd45me00/oo4bn4x1.json', 'init=/tmp/tmpjd45me00/grm0uca3.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_4t8goei/prophet_model-20260803145329.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:29 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:29 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_44_dept_81

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_8broofe.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/n_6vjkgm.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=72622', 'data', 'file=/tmp/tmpjd45me00/_8broofe.json', 'init=/tmp/tmpjd45me00/n_6vjkgm.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model0d9q6wuq/prophet_model-20260803145330.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:30 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_44_dept_82

14:53:30 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zz7b51_r.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4ie_nbg3.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=31171', 'data', 'file=/tmp/tmpjd45me00/zz7b51_r.json', 'init=/tmp/tmpjd45me00/4ie_nbg3.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelfbgigj_q/prophet_model-20260803145330.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:30 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:30 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_44_dept_83

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/d4exmptb.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ve69056i.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=69867', 'data', 'file=/tmp/tmpjd45me00/d4exmptb.json', 'init=/tmp/tmpjd45me00/ve69056i.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model7nhj2x1b/prophet_model-20260803145330.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:30 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:30 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_44_dept_87
Build prophet model for  store_44_dept_9

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3m8c5fda.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vo1qok6i.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=80065', 'data', 'file=/tmp/tmpjd45me00/3m8c5fda.json', 'init=/tmp/tmpjd45me00/vo1qok6i.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model3qself3t/prophet_model-20260803145331.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:31 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:31 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jzdzthgy.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hvhvew1m.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=17678', 'data', 'file=/tmp/tmpjd45me00/jzdzthgy.json', 'init=/tmp/tmpjd45me00/hvhvew1m.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelyzg19kb2/prophet_model-20260803145331.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:31 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_44_dept_90

14:53:31 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/r5nwmqlo.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5hh06q3x.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=11115', 'data', 'file=/tmp/tmpjd45me00/r5nwmqlo.json', 'init=/tmp/tmpjd45me00/5hh06q3x.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelj53q_ns5/prophet_model-20260803145331.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:31 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:31 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_44_dept_91

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_86gj_61.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mty6qlej.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=80824', 'data', 'file=/tmp/tmpjd45me00/_86gj_61.json', 'init=/tmp/tmpjd45me00/mty6qlej.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelukn7ckeh/prophet_model-20260803145331.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:31 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:31 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_44_dept_92
Build prophet model for  store_44_dept_93

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/t081r3ao.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bx9a1a8p.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=51435', 'data', 'file=/tmp/tmpjd45me00/t081r3ao.json', 'init=/tmp/tmpjd45me00/bx9a1a8p.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model3b95ympn/prophet_model-20260803145332.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:32 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:32 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wic9hpqb.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xnvv1v7t.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=60458', 'data', 'file=/tmp/tmpjd45me00/wic9hpqb.json', 'init=/tmp/tmpjd45me00/xnvv1v7t.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modell_uh1of_/prophet_model-20260803145332.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:32 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:32 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_44_dept_94

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mkajq523.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6cqs1sqq.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=35652', 'data', 'file=/tmp/tmpjd45me00/mkajq523.json', 'init=/tmp/tmpjd45me00/6cqs1sqq.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelm3mhcsqb/prophet_model-20260803145332.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:32 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:32 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_44_dept_95
Build prophet model for  store_44_dept_96

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/z991d5f0.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1prp723h.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=9340', 'data', 'file=/tmp/tmpjd45me00/z991d5f0.json', 'init=/tmp/tmpjd45me00/1prp723h.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeltfdkik9e/prophet_model-20260803145332.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:32 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:32 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7nf1a0op.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/f3wlzx2d.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=23946', 'data', 'file=/tmp/tmpjd45me00/7nf1a0op.json', 'init=/tmp/tmpjd45me00/f3wlzx2d.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeldzultfcy/prophet_model-20260803145332.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:32 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:32 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ua9c1ka2.json

Build prophet model for  store_44_dept_97
Build prophet model for  store_44_dept_98

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ijq8ru0g.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=26381', 'data', 'file=/tmp/tmpjd45me00/ua9c1ka2.json', 'init=/tmp/tmpjd45me00/ijq8ru0g.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modely8l8o96e/prophet_model-20260803145332.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:32 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:33 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0s9je8c_.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fjef569c.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=93204', 'data', 'file=/tmp/tmpjd45me00/0s9je8c_.json', 'init=/tmp/tmpjd45me00/fjef569c.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelvul_n_u2/prophet_model-20260803145333.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:33 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:33 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/tb93gebm.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qhc221dk.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=72548', 'data', 'file=/tmp/tmpjd45me00/tb93gebm.json', 'init=/tmp/tmpjd45me00/qhc221dk.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelz8dri7xr/prophet_model-20260803145333.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:33 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_45_dept_1
Build prophet model for  store_45_dept_10

14:53:33 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/tpmlo5pu.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/nd8_g7yg.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=8493', 'data', 'file=/tmp/tmpjd45me00/tpmlo5pu.json', 'init=/tmp/tmpjd45me00/nd8_g7yg.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelix5zmgd_/prophet_model-20260803145333.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:33 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_45_dept_11

14:53:33 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/z__lkhfj.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/c5xxv4g4.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=98878', 'data', 'file=/tmp/tmpjd45me00/z__lkhfj.json', 'init=/tmp/tmpjd45me00/c5xxv4g4.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelwikdkhst/prophet_model-20260803145334.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:34 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:34 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_45_dept_12
Build prophet model for  store_45_dept_13

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ul6_0nju.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/sf8gw11z.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=5329', 'data', 'file=/tmp/tmpjd45me00/ul6_0nju.json', 'init=/tmp/tmpjd45me00/sf8gw11z.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelrebjvfmn/prophet_model-20260803145334.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:34 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:34 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/clgzyr8p.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/e7v53ann.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=82760', 'data', 'file=/tmp/tmpjd45me00/clgzyr8p.json', 'init=/tmp/tmpjd45me00/e7v53ann.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelj1zejw1u/prophet_model-20260803145334.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:34 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:34 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/a27a4fwr.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/duyn5ddz.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=46393', 'data', 'file=/tmp/tmpjd45me00/a27a4fwr.json', 'init=/tmp/tmpjd45me00/duyn5ddz.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelcitrwch1/prophet_model-20260803145334.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:34 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_45_dept_14
Build prophet model for  store_45_dept_16

14:53:34 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hluzn51i.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/k2qid469.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=67500', 'data', 'file=/tmp/tmpjd45me00/hluzn51i.json', 'init=/tmp/tmpjd45me00/k2qid469.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model3f3_cpuz/prophet_model-20260803145334.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:34 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:34 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/p8mbzboc.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dfpt8q2w.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=50807', 'data', 'file=/tmp/tmpjd45me00/p8mbzboc.json', 'init=/tmp/tmpjd45me00/dfpt8q2w.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model9o8_lovm/prophet_model-20260803145335.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:35 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_45_dept_17
Build prophet model for  store_45_dept_18

14:53:35 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gb_qvadm.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hgky9a1r.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=18877', 'data', 'file=/tmp/tmpjd45me00/gb_qvadm.json', 'init=/tmp/tmpjd45me00/hgky9a1r.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model5r4jvhka/prophet_model-20260803145335.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:35 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:35 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_45_dept_19
Build prophet model for  store_45_dept_2

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/n7zp27nn.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/470yyvtc.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=16734', 'data', 'file=/tmp/tmpjd45me00/n7zp27nn.json', 'init=/tmp/tmpjd45me00/470yyvtc.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelva6u0o13/prophet_model-20260803145335.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:35 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:35 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/a0y04swc.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qv6sx72e.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=83104', 'data', 'file=/tmp/tmpjd45me00/a0y04swc.json', 'init=/tmp/tmpjd45me00/qv6sx72e.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeljc1e_oe2/prophet_model-20260803145335.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:35 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:35 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_45_dept_20

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jhv0d706.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/461e5ph7.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=29571', 'data', 'file=/tmp/tmpjd45me00/jhv0d706.json', 'init=/tmp/tmpjd45me00/461e5ph7.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeloim3q77t/prophet_model-20260803145336.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:36 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:36 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/89svwq1l.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/j6e9wkp8.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=90326', 'data', 'file=/tmp/tmpjd45me00/89svwq1l.json', 'init=/tmp/tmpjd45me00/j6e9wkp8.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modele0dzqutl/prophet_model-20260803145336.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:36 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_45_dept_21
Build prophet model for  store_45_dept_22

14:53:36 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/td3tsvo6.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9odxvgko.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=78075', 'data', 'file=/tmp/tmpjd45me00/td3tsvo6.json', 'init=/tmp/tmpjd45me00/9odxvgko.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model0hctj5ok/prophet_model-20260803145336.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:36 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:36 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ui812x7d.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8a75otzq.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=21064', 'data', 'file=/tmp/tmpjd45me00/ui812x7d.json', 'init=/tmp/tmpjd45me00/8a75otzq.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelbf3wy3tq/prophet_model-20260803145336.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:36 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_45_dept_23
Build prophet model for  store_45_dept_24

14:53:36 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/68xk93qo.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3cmrudv0.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=80435', 'data', 'file=/tmp/tmpjd45me00/68xk93qo.json', 'init=/tmp/tmpjd45me00/3cmrudv0.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelp7antwyk/prophet_model-20260803145336.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:36 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_45_dept_25

14:53:37 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/71hhp8nt.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vbwm3ux4.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=49869', 'data', 'file=/tmp/tmpjd45me00/71hhp8nt.json', 'init=/tmp/tmpjd45me00/vbwm3ux4.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modela179slof/prophet_model-20260803145337.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:37 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:37 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0oy4n3b8.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wpc_9f4u.json
DEBUG:cmdstanpy:idx 0

Build prophet model for  store_45_dept_26
Build prophet model for  store_45_dept_27

DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=64454', 'data', 'file=/tmp/tmpjd45me00/0oy4n3b8.json', 'init=/tmp/tmpjd45me00/wpc_9f4u.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modela1yqnbak/prophet_model-20260803145337.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:37 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:37 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/phlwwqvo.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/24_jm3y2.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=51438', 'data', 'file=/tmp/tmpjd45me00/phlwwqvo.json', 'init=/tmp/tmpjd45me00/24_jm3y2.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modely3zd4r5_/prophet_model-20260803145337.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:37 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:37 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xjsp2h2g.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/f3ylsng8.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=1727', 'data', 'file=/tmp/tmpjd45me00/xjsp2h2g.json', 'init=/tmp/tmpjd45me00/f3ylsng8.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelny13emtr/prophet_model-20260803145337.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:37 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_45_dept_28
Build prophet model for  store_45_dept_29

14:53:37 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xcc_2dmo.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/36skcug0.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=89445', 'data', 'file=/tmp/tmpjd45me00/xcc_2dmo.json', 'init=/tmp/tmpjd45me00/36skcug0.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelij0kv4ga/prophet_model-20260803145337.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:37 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:37 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vyln_0t1.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/42bh5g86.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=89950', 'data', 'file=/tmp/tmpjd45me00/vyln_0t1.json', 'init=/tmp/tmpjd45me00/42bh5g86.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelsudmfn45/prophet_model-20260803145337.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:37 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_45_dept_3
Build prophet model for  store_45_dept_30

14:53:38 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2vluax2o.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/06p80bua.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=24160', 'data', 'file=/tmp/tmpjd45me00/2vluax2o.json', 'init=/tmp/tmpjd45me00/06p80bua.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model11xkn1hk/prophet_model-20260803145338.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:38 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_45_dept_31

14:53:38 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/kfk768be.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vya9jmtb.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=58896', 'data', 'file=/tmp/tmpjd45me00/kfk768be.json', 'init=/tmp/tmpjd45me00/vya9jmtb.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelw9yjrejq/prophet_model-20260803145338.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:38 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:38 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_ws8pd1p.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/38hopkzo.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=27013', 'data', 'file=/tmp/tmpjd45me00/_ws8pd1p.json', 'init=/tmp/tmpjd45me00/38hopkzo.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelv_o82kqv/prophet_model-20260803145338.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:38 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_45_dept_32
Build prophet model for  store_45_dept_33

14:53:38 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/cfc2tc9k.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/t9mxdxa1.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=57224', 'data', 'file=/tmp/tmpjd45me00/cfc2tc9k.json', 'init=/tmp/tmpjd45me00/t9mxdxa1.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelz4x28stv/prophet_model-20260803145338.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:38 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_45_dept_34

14:53:39 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/flalgzjc.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/m1lq5opd.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=69710', 'data', 'file=/tmp/tmpjd45me00/flalgzjc.json', 'init=/tmp/tmpjd45me00/m1lq5opd.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelz4tt79eu/prophet_model-20260803145339.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:39 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:39 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rpqhs3yd.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/a_d5o8l1.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=46197', 'data', 'file=/tmp/tmpjd45me00/rpqhs3yd.json', 'init=/tmp/tmpjd45me00/a_d5o8l1.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelu6ydhn2i/prophet_model-20260803145339.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:39 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_45_dept_35
Build prophet model for  store_45_dept_36

14:53:39 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/lxc51ve3.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2o0p7ad4.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=11431', 'data', 'file=/tmp/tmpjd45me00/lxc51ve3.json', 'init=/tmp/tmpjd45me00/2o0p7ad4.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelsxvxaw6s/prophet_model-20260803145339.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:39 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:39 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4v_xw3zg.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/kg0dpw44.json

Build prophet model for  store_45_dept_38
Build prophet model for  store_45_dept_4

DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=46951', 'data', 'file=/tmp/tmpjd45me00/4v_xw3zg.json', 'init=/tmp/tmpjd45me00/kg0dpw44.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model2tzn6nqv/prophet_model-20260803145339.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:39 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:39 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/iuysfekw.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ng40q7_c.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=49643', 'data', 'file=/tmp/tmpjd45me00/iuysfekw.json', 'init=/tmp/tmpjd45me00/ng40q7_c.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelmacd7o2n/prophet_model-20260803145339.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:39 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:39 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_45_dept_40

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ppj84pcv.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/snqekfam.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=18817', 'data', 'file=/tmp/tmpjd45me00/ppj84pcv.json', 'init=/tmp/tmpjd45me00/snqekfam.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model48r636y4/prophet_model-20260803145340.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:40 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_45_dept_41

14:53:40 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/59yslr5y.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zlbxrq_0.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=63219', 'data', 'file=/tmp/tmpjd45me00/59yslr5y.json', 'init=/tmp/tmpjd45me00/zlbxrq_0.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelbfjz3b0b/prophet_model-20260803145340.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:40 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:40 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_45_dept_42

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/os1vfpgi.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/g8jgvj_l.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=63095', 'data', 'file=/tmp/tmpjd45me00/os1vfpgi.json', 'init=/tmp/tmpjd45me00/g8jgvj_l.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modele927cny0/prophet_model-20260803145340.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:40 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:40 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_45_dept_44

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/iq3iogk6.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/y3b08cw4.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=54729', 'data', 'file=/tmp/tmpjd45me00/iq3iogk6.json', 'init=/tmp/tmpjd45me00/y3b08cw4.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelcdhue7i5/prophet_model-20260803145340.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:40 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:40 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1_zfeb4w.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3c06aari.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=92258', 'data', 'file=/tmp/tmpjd45me00/1_zfeb4w.json', 'init=/tmp/tmpjd45me00/3c06aari.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelbpa3zgj7/prophet_model-20260803145341.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:41 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_45_dept_46
Build prophet model for  store_45_dept_5

14:53:41 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9dasr32s.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/i5jqc_5_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=53431', 'data', 'file=/tmp/tmpjd45me00/9dasr32s.json', 'init=/tmp/tmpjd45me00/i5jqc_5_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelge9zjmm0/prophet_model-20260803145341.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:41 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:41 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_45_dept_52
Build prophet model for  store_45_dept_54

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/j17tmf1x.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fodjjbel.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=51150', 'data', 'file=/tmp/tmpjd45me00/j17tmf1x.json', 'init=/tmp/tmpjd45me00/fodjjbel.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelyzapfzft/prophet_model-20260803145341.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:41 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:41 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rl53hm2g.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/i1t6u4tt.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=82852', 'data', 'file=/tmp/tmpjd45me00/rl53hm2g.json', 'init=/tmp/tmpjd45me00/i1t6u4tt.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modell5ojcwj5/prophet_model-20260803145341.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:41 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:41 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/q3y70rmg.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/oc56n08v.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=26153', 'data', 'file=/tmp/tmpjd45me00/q3y70rmg.json', 'init=/tmp/tmpjd45me00/oc56n08v.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelb8a6z174/prophet_model-20260803145341.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:41 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_45_dept_55
Build prophet model for  store_45_dept_56

14:53:41 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vf1xmvp1.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ryg_i1gr.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=97902', 'data', 'file=/tmp/tmpjd45me00/vf1xmvp1.json', 'init=/tmp/tmpjd45me00/ryg_i1gr.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeleo_r3jrd/prophet_model-20260803145342.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:42 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:42 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_45_dept_58

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/lazem7nm.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/v4ckcy86.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=12613', 'data', 'file=/tmp/tmpjd45me00/lazem7nm.json', 'init=/tmp/tmpjd45me00/v4ckcy86.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelwr5j_b83/prophet_model-20260803145342.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:42 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_45_dept_59

14:53:42 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/419ckang.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/70gipwop.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=24390', 'data', 'file=/tmp/tmpjd45me00/419ckang.json', 'init=/tmp/tmpjd45me00/70gipwop.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelxxxz97bn/prophet_model-20260803145342.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:42 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:42 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_45_dept_6

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/n_rdbrl5.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wxpngury.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=38444', 'data', 'file=/tmp/tmpjd45me00/n_rdbrl5.json', 'init=/tmp/tmpjd45me00/wxpngury.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model4okvlgmb/prophet_model-20260803145343.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:43 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:43 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_45_dept_60
Build prophet model for  store_45_dept_67

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zl9xj_9w.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/a743eyr8.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=8188', 'data', 'file=/tmp/tmpjd45me00/zl9xj_9w.json', 'init=/tmp/tmpjd45me00/a743eyr8.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelr5uwzp4q/prophet_model-20260803145343.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:43 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:43 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/lqd59ruv.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qxptz3y5.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=59580', 'data', 'file=/tmp/tmpjd45me00/lqd59ruv.json', 'init=/tmp/tmpjd45me00/qxptz3y5.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelmaiscozr/prophet_model-20260803145343.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:43 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:43 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_45_dept_7

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/29yzcebr.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9otd3_q3.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=28361', 'data', 'file=/tmp/tmpjd45me00/29yzcebr.json', 'init=/tmp/tmpjd45me00/9otd3_q3.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelqhf2obvu/prophet_model-20260803145343.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:43 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:43 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_45_dept_71

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/igteyk_6.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xke0qlo9.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=28916', 'data', 'file=/tmp/tmpjd45me00/igteyk_6.json', 'init=/tmp/tmpjd45me00/xke0qlo9.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model9hw84afz/prophet_model-20260803145344.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:44 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:45 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/t_wpzqxm.json

Build prophet model for  store_45_dept_72
Build prophet model for  store_45_dept_74

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/sqoo7ppu.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=91672', 'data', 'file=/tmp/tmpjd45me00/t_wpzqxm.json', 'init=/tmp/tmpjd45me00/sqoo7ppu.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelq0wazu2t/prophet_model-20260803145345.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:45 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:45 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ultvnqmp.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6391_jvo.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=76110', 'data', 'file=/tmp/tmpjd45me00/ultvnqmp.json', 'init=/tmp/tmpjd45me00/6391_jvo.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model3uiwucwl/prophet_model-20260803145345.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:45 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:45 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_45_dept_79
Build prophet model for  store_45_dept_8

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ygctq1jz.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7ju6na0j.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=82335', 'data', 'file=/tmp/tmpjd45me00/ygctq1jz.json', 'init=/tmp/tmpjd45me00/7ju6na0j.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelo2xrjddb/prophet_model-20260803145345.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:45 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:45 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7vo_awoo.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/caglotmj.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=12716', 'data', 'file=/tmp/tmpjd45me00/7vo_awoo.json', 'init=/tmp/tmpjd45me00/caglotmj.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelujwcwcjw/prophet_model-20260803145345.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:45 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_45_dept_81

14:53:45 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/cz8czxhl.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5pxql8d2.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=62882', 'data', 'file=/tmp/tmpjd45me00/cz8czxhl.json', 'init=/tmp/tmpjd45me00/5pxql8d2.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model7a6qb69w/prophet_model-20260803145345.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:45 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:46 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ryomdyee.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/04547yet.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=4160', 'data', 'file=/tmp/tmpjd45me00/ryomdyee.json', 'init=/tmp/tmpjd45me00/04547yet.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelwo610gvm/prophet_model-20260803145346.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:46 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_45_dept_82
Build prophet model for  store_45_dept_83

14:53:46 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/66kw4kip.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/k20whre6.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=27860', 'data', 'file=/tmp/tmpjd45me00/66kw4kip.json', 'init=/tmp/tmpjd45me00/k20whre6.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelwetkq5mc/prophet_model-20260803145346.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:46 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_45_dept_85

14:53:46 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/yn7kqv0f.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/16mamp_n.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=42161', 'data', 'file=/tmp/tmpjd45me00/yn7kqv0f.json', 'init=/tmp/tmpjd45me00/16mamp_n.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelld4m2l79/prophet_model-20260803145346.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:46 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:46 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/k698xb2y.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hrpq_1ix.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=52083', 'data', 'file=/tmp/tmpjd45me00/k698xb2y.json', 'init=/tmp/tmpjd45me00/hrpq_1ix.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelcefnudlv/prophet_model-20260803145346.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:46 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_45_dept_87
Build prophet model for  store_45_dept_9

14:53:46 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/snnnr_dc.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/b64633_k.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=59243', 'data', 'file=/tmp/tmpjd45me00/snnnr_dc.json', 'init=/tmp/tmpjd45me00/b64633_k.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeldqq0z81z/prophet_model-20260803145346.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:46 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:47 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_45_dept_90

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/17mkuroq.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/y21mlfdb.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=73133', 'data', 'file=/tmp/tmpjd45me00/17mkuroq.json', 'init=/tmp/tmpjd45me00/y21mlfdb.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelqvx1lri9/prophet_model-20260803145347.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:47 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:47 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qxva7isv.json

Build prophet model for  store_45_dept_91
Build prophet model for  store_45_dept_92

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/j_ufpa82.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=20713', 'data', 'file=/tmp/tmpjd45me00/qxva7isv.json', 'init=/tmp/tmpjd45me00/j_ufpa82.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelm6z7s_qt/prophet_model-20260803145347.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:47 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:47 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mn8dxxdg.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/a0689c14.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=42709', 'data', 'file=/tmp/tmpjd45me00/mn8dxxdg.json', 'init=/tmp/tmpjd45me00/a0689c14.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model8b1w08na/prophet_model-20260803145347.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:47 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:47 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_45_dept_93

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/n3cxu1ss.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mrixwf5n.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=50600', 'data', 'file=/tmp/tmpjd45me00/n3cxu1ss.json', 'init=/tmp/tmpjd45me00/mrixwf5n.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelzv46kvai/prophet_model-20260803145347.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:47 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:47 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_45_dept_95
Build prophet model for  store_45_dept_97

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/webpbqmu.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gxy6ewbp.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=82408', 'data', 'file=/tmp/tmpjd45me00/webpbqmu.json', 'init=/tmp/tmpjd45me00/gxy6ewbp.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelhtri1_yf/prophet_model-20260803145348.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:48 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:48 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/lgwmd6ei.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/tjfk8dc1.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=66480', 'data', 'file=/tmp/tmpjd45me00/lgwmd6ei.json', 'init=/tmp/tmpjd45me00/tjfk8dc1.json', 'output', 'file=/tmp/tmpjd45me00/prophet_models2gv88j8/prophet_model-20260803145348.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:48 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_45_dept_98

14:53:48 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vpg8oo3x.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/oaw0i6ah.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=27974', 'data', 'file=/tmp/tmpjd45me00/vpg8oo3x.json', 'init=/tmp/tmpjd45me00/oaw0i6ah.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelfx1aom2g/prophet_model-20260803145348.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:48 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:48 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/l_6l2mvl.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2wf4ds06.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=25787', 'data', 'file=/tmp/tmpjd45me00/l_6l2mvl.json', 'init=/tmp/tmpjd45me00/2wf4ds06.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelcjkxhgdc/prophet_model-20260803145348.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:48 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:48 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_4_dept_1
Build prophet model for  store_4_dept_10

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/c1hb_7gr.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hyju79fc.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=3114', 'data', 'file=/tmp/tmpjd45me00/c1hb_7gr.json', 'init=/tmp/tmpjd45me00/hyju79fc.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelvyonp18s/prophet_model-20260803145348.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:48 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_4_dept_11

14:53:49 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1q3u6_is.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vrrfxq46.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=329', 'data', 'file=/tmp/tmpjd45me00/1q3u6_is.json', 'init=/tmp/tmpjd45me00/vrrfxq46.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model9zl41irh/prophet_model-20260803145349.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:49 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:49 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3pof_9tb.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3o4dzone.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=7061', 'data', 'file=/tmp/tmpjd45me00/3pof_9tb.json', 'init=/tmp/tmpjd45me00/3o4dzone.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeldmdg9pza/prophet_model-20260803145349.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:49 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:49 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_4_dept_12
Build prophet model for  store_4_dept_13

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rw8uhpsa.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7jfkhvgk.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=87705', 'data', 'file=/tmp/tmpjd45me00/rw8uhpsa.json', 'init=/tmp/tmpjd45me00/7jfkhvgk.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_k95v0lc/prophet_model-20260803145349.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:49 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:49 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1ph0ac5d.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qtpka5dg.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=31479', 'data', 'file=/tmp/tmpjd45me00/1ph0ac5d.json', 'init=/tmp/tmpjd45me00/qtpka5dg.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelzryammf6/prophet_model-20260803145349.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:49 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_4_dept_14
Build prophet model for  store_4_dept_16

14:53:49 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8yy294q6.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9jt455zz.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=89588', 'data', 'file=/tmp/tmpjd45me00/8yy294q6.json', 'init=/tmp/tmpjd45me00/9jt455zz.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modela56hx0od/prophet_model-20260803145350.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:50 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:50 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fl933ejd.json

Build prophet model for  store_4_dept_17
Build prophet model for  store_4_dept_18

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/w96hrrp6.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=23735', 'data', 'file=/tmp/tmpjd45me00/fl933ejd.json', 'init=/tmp/tmpjd45me00/w96hrrp6.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelqukilght/prophet_model-20260803145350.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:50 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:50 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/59lr18v1.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wxun1lmo.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=91095', 'data', 'file=/tmp/tmpjd45me00/59lr18v1.json', 'init=/tmp/tmpjd45me00/wxun1lmo.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeloo8ppvl0/prophet_model-20260803145350.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:50 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:50 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_4_dept_19
Build prophet model for  store_4_dept_2

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2mdl3j3o.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/juqfszid.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=41160', 'data', 'file=/tmp/tmpjd45me00/2mdl3j3o.json', 'init=/tmp/tmpjd45me00/juqfszid.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelhrxj_44i/prophet_model-20260803145350.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:50 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:50 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7pm4q8q0.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8xyo5uic.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=67744', 'data', 'file=/tmp/tmpjd45me00/7pm4q8q0.json', 'init=/tmp/tmpjd45me00/8xyo5uic.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model0cnqrl35/prophet_model-20260803145350.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:50 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:50 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/07uoj08r.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fywsi9ci.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=88330', 'data', 'file=/tmp/tmpjd45me00/07uoj08r.json', 'init=/tmp/tmpjd45me00/fywsi9ci.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelf4anmwpi/prophet_model-20260803145350.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:50 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_4_dept_20
Build prophet model for  store_4_dept_21

14:53:51 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/eu1b9ifa.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_w_1qy94.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=27267', 'data', 'file=/tmp/tmpjd45me00/eu1b9ifa.json', 'init=/tmp/tmpjd45me00/_w_1qy94.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelhmrmj4o1/prophet_model-20260803145351.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:51 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:51 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/u1xrc_24.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9ou9qo9o.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=45655', 'data', 'file=/tmp/tmpjd45me00/u1xrc_24.json', 'init=/tmp/tmpjd45me00/9ou9qo9o.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model92qo2twu/prophet_model-20260803145351.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:51 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_4_dept_22
Build prophet model for  store_4_dept_23

14:53:51 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hxt2m6hr.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bv0td3ly.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=80556', 'data', 'file=/tmp/tmpjd45me00/hxt2m6hr.json', 'init=/tmp/tmpjd45me00/bv0td3ly.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model3a7s2bpk/prophet_model-20260803145351.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:51 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:51 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/kdxlgmn6.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mz8h9f_q.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=93255', 'data', 'file=/tmp/tmpjd45me00/kdxlgmn6.json', 'init=/tmp/tmpjd45me00/mz8h9f_q.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model4xhusegn/prophet_model-20260803145351.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:51 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_4_dept_24
Build prophet model for  store_4_dept_25

14:53:51 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/niw78lpw.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/oirb_q80.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=19074', 'data', 'file=/tmp/tmpjd45me00/niw78lpw.json', 'init=/tmp/tmpjd45me00/oirb_q80.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelb8jiwtn0/prophet_model-20260803145351.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:51 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:51 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/lq8nj39t.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/80fh6s2c.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=92388', 'data', 'file=/tmp/tmpjd45me00/lq8nj39t.json', 'init=/tmp/tmpjd45me00/80fh6s2c.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model4dq2z0t0/prophet_model-20260803145351.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:51 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_4_dept_26
Build prophet model for  store_4_dept_27

14:53:51 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3173e6c_.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/lzydpjka.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=12440', 'data', 'file=/tmp/tmpjd45me00/3173e6c_.json', 'init=/tmp/tmpjd45me00/lzydpjka.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model8dlhm0k1/prophet_model-20260803145352.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:52 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_4_dept_28

14:53:52 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1sc6fkuw.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6r_oyucn.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=8632', 'data', 'file=/tmp/tmpjd45me00/1sc6fkuw.json', 'init=/tmp/tmpjd45me00/6r_oyucn.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model2l9lwhrb/prophet_model-20260803145352.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:52 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:52 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/huf9sj9z.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rqjlzrer.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=64963', 'data', 'file=/tmp/tmpjd45me00/huf9sj9z.json', 'init=/tmp/tmpjd45me00/rqjlzrer.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelns44ho1h/prophet_model-20260803145352.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:52 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_4_dept_29
Build prophet model for  store_4_dept_3

14:53:52 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fedre6zj.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0p7s9ceg.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=32747', 'data', 'file=/tmp/tmpjd45me00/fedre6zj.json', 'init=/tmp/tmpjd45me00/0p7s9ceg.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelc9aitipg/prophet_model-20260803145352.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:52 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:52 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_4_dept_30
Build prophet model for  store_4_dept_31

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/18h1ohaa.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5332q3vz.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=14999', 'data', 'file=/tmp/tmpjd45me00/18h1ohaa.json', 'init=/tmp/tmpjd45me00/5332q3vz.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeld467066y/prophet_model-20260803145352.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:52 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:52 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4x8vjv9l.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/40wxxjs_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=42781', 'data', 'file=/tmp/tmpjd45me00/4x8vjv9l.json', 'init=/tmp/tmpjd45me00/40wxxjs_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model5mk_jcjy/prophet_model-20260803145353.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:53 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:53 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/iyo_93zg.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pdvowyyo.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=53581', 'data', 'file=/tmp/tmpjd45me00/iyo_93zg.json', 'init=/tmp/tmpjd45me00/pdvowyyo.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model5a74w9pv/prophet_model-20260803145353.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:53 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_4_dept_32
Build prophet model for  store_4_dept_33

14:53:53 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/f7g_heip.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/d9_17n87.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=81391', 'data', 'file=/tmp/tmpjd45me00/f7g_heip.json', 'init=/tmp/tmpjd45me00/d9_17n87.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelk9291uk2/prophet_model-20260803145353.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:53 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:53 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2g9sw21q.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zssalgfp.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=50539', 'data', 'file=/tmp/tmpjd45me00/2g9sw21q.json', 'init=/tmp/tmpjd45me00/zssalgfp.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model3kfx1rs0/prophet_model-20260803145353.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:53 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:53 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_4_dept_34
Build prophet model for  store_4_dept_35

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mb_i844m.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/lankqcuh.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=9342', 'data', 'file=/tmp/tmpjd45me00/mb_i844m.json', 'init=/tmp/tmpjd45me00/lankqcuh.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelj2w8zkkr/prophet_model-20260803145353.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:53 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:53 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ymz6d3pf.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/b9xprd3_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=21401', 'data', 'file=/tmp/tmpjd45me00/ymz6d3pf.json', 'init=/tmp/tmpjd45me00/b9xprd3_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_ywo9nir/prophet_model-20260803145353.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:53 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_4_dept_36
Build prophet model for  store_4_dept_37

14:53:53 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/v4httdml.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mfsp3cub.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=30608', 'data', 'file=/tmp/tmpjd45me00/v4httdml.json', 'init=/tmp/tmpjd45me00/mfsp3cub.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelo7peqhbt/prophet_model-20260803145354.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:54 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:54 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/epkl2d54.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/nkzap1i9.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=73367', 'data', 'file=/tmp/tmpjd45me00/epkl2d54.json', 'init=/tmp/tmpjd45me00/nkzap1i9.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model3tlwclbb/prophet_model-20260803145354.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:54 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_4_dept_38
Build prophet model for  store_4_dept_4

14:53:54 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xx9gfl9d.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/e1p3_5nn.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=25498', 'data', 'file=/tmp/tmpjd45me00/xx9gfl9d.json', 'init=/tmp/tmpjd45me00/e1p3_5nn.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeld_nt505y/prophet_model-20260803145354.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:54 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:54 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2j47qpsj.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/k2g4jciw.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=87901', 'data', 'file=/tmp/tmpjd45me00/2j47qpsj.json', 'init=/tmp/tmpjd45me00/k2g4jciw.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelhp25s99y/prophet_model-20260803145354.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:54 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_4_dept_40
Build prophet model for  store_4_dept_41

14:53:54 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dluqg_z5.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/il8rnbpz.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=228', 'data', 'file=/tmp/tmpjd45me00/dluqg_z5.json', 'init=/tmp/tmpjd45me00/il8rnbpz.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelhke4_4v9/prophet_model-20260803145354.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:54 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_4_dept_42

14:53:54 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1zm5qdoa.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9ve_tet2.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=52934', 'data', 'file=/tmp/tmpjd45me00/1zm5qdoa.json', 'init=/tmp/tmpjd45me00/9ve_tet2.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelk0sfuokl/prophet_model-20260803145355.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:55 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:55 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_4_dept_44

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jwa56yf9.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/lck8uh2v.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=60176', 'data', 'file=/tmp/tmpjd45me00/jwa56yf9.json', 'init=/tmp/tmpjd45me00/lck8uh2v.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelg1cbczpz/prophet_model-20260803145355.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:55 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:55 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_4_dept_46
Build prophet model for  store_4_dept_48

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/g1yj6wa4.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/n3a5vl8_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=66591', 'data', 'file=/tmp/tmpjd45me00/g1yj6wa4.json', 'init=/tmp/tmpjd45me00/n3a5vl8_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelbneb04no/prophet_model-20260803145355.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:55 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:55 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5x9mbhus.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7r1tvuun.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=73592', 'data', 'file=/tmp/tmpjd45me00/5x9mbhus.json', 'init=/tmp/tmpjd45me00/7r1tvuun.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelnytqcnt0/prophet_model-20260803145355.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:55 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:55 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_4_dept_49
Build prophet model for  store_4_dept_5

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gpwkl2jc.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/51ttwmvs.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=87896', 'data', 'file=/tmp/tmpjd45me00/gpwkl2jc.json', 'init=/tmp/tmpjd45me00/51ttwmvs.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelbpjfzaa5/prophet_model-20260803145356.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:56 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:56 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vrfp6wdl.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/o_lx64x2.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=89093', 'data', 'file=/tmp/tmpjd45me00/vrfp6wdl.json', 'init=/tmp/tmpjd45me00/o_lx64x2.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelo02s1cxi/prophet_model-20260803145356.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:56 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:56 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_4_dept_52

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vxaygy4m.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/je_nitdi.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=48570', 'data', 'file=/tmp/tmpjd45me00/vxaygy4m.json', 'init=/tmp/tmpjd45me00/je_nitdi.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model79ctqle_/prophet_model-20260803145356.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:56 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:56 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_4_dept_54

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6u235hj7.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bn1vdwsa.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=61808', 'data', 'file=/tmp/tmpjd45me00/6u235hj7.json', 'init=/tmp/tmpjd45me00/bn1vdwsa.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelzria5wud/prophet_model-20260803145356.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:56 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:56 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_4_dept_55
Build prophet model for  store_4_dept_56

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bpkp1nmg.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ej0a_hzp.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=88123', 'data', 'file=/tmp/tmpjd45me00/bpkp1nmg.json', 'init=/tmp/tmpjd45me00/ej0a_hzp.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelg998l8lr/prophet_model-20260803145357.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:57 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:57 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/sqn4f4eg.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jadadehl.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=17883', 'data', 'file=/tmp/tmpjd45me00/sqn4f4eg.json', 'init=/tmp/tmpjd45me00/jadadehl.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelaplq02az/prophet_model-20260803145357.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:57 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:57 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_4_dept_58

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3jz7t99u.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/k3e4kn7s.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=95854', 'data', 'file=/tmp/tmpjd45me00/3jz7t99u.json', 'init=/tmp/tmpjd45me00/k3e4kn7s.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelf517zswu/prophet_model-20260803145358.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:58 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_4_dept_59

14:53:58 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/a9odno_9.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/u5r0k1jj.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=2398', 'data', 'file=/tmp/tmpjd45me00/a9odno_9.json', 'init=/tmp/tmpjd45me00/u5r0k1jj.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelicli0b7f/prophet_model-20260803145358.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:58 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:58 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/98ucnusf.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/a7rpj5cl.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=82773', 'data', 'file=/tmp/tmpjd45me00/98ucnusf.json', 'init=/tmp/tmpjd45me00/a7rpj5cl.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelk9so12tz/prophet_model-20260803145358.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:58 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_4_dept_6
Build prophet model for  store_4_dept_60

14:53:58 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/we3jysn8.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/opjpwnev.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=62736', 'data', 'file=/tmp/tmpjd45me00/we3jysn8.json', 'init=/tmp/tmpjd45me00/opjpwnev.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model2rxf3nt6/prophet_model-20260803145358.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:58 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:58 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/et7prmch.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/h89369is.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=54560', 'data', 'file=/tmp/tmpjd45me00/et7prmch.json', 'init=/tmp/tmpjd45me00/h89369is.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelhbri_htp/prophet_model-20260803145358.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:58 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_4_dept_67
Build prophet model for  store_4_dept_7

14:53:58 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dqfu_a5l.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zh0j1w4l.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=53991', 'data', 'file=/tmp/tmpjd45me00/dqfu_a5l.json', 'init=/tmp/tmpjd45me00/zh0j1w4l.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeltytnetkz/prophet_model-20260803145358.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:58 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:58 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_3irfuci.json

Build prophet model for  store_4_dept_71
Build prophet model for  store_4_dept_72

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jq3bop2w.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=89243', 'data', 'file=/tmp/tmpjd45me00/_3irfuci.json', 'init=/tmp/tmpjd45me00/jq3bop2w.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelyfsa9p51/prophet_model-20260803145359.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:59 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:59 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/k5__n8m4.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/sz59o5vq.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=5780', 'data', 'file=/tmp/tmpjd45me00/k5__n8m4.json', 'init=/tmp/tmpjd45me00/sz59o5vq.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelq4zh43me/prophet_model-20260803145359.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:59 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:59 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/friwl6kz.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/q97gxczk.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=27608', 'data', 'file=/tmp/tmpjd45me00/friwl6kz.json', 'init=/tmp/tmpjd45me00/q97gxczk.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelkf_mbrux/prophet_model-20260803145359.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:59 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_4_dept_74
Build prophet model for  store_4_dept_79

14:53:59 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/a1kbpycf.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mdsw71ix.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=46115', 'data', 'file=/tmp/tmpjd45me00/a1kbpycf.json', 'init=/tmp/tmpjd45me00/mdsw71ix.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model613kjij1/prophet_model-20260803145359.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:59 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:53:59 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_4_dept_8
Build prophet model for  store_4_dept_80

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ptxuetbe.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/nguqpycm.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=25107', 'data', 'file=/tmp/tmpjd45me00/ptxuetbe.json', 'init=/tmp/tmpjd45me00/nguqpycm.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelzo6lp761/prophet_model-20260803145359.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:53:59 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:00 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vg6yfpsq.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ab9cj6sn.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=65141', 'data', 'file=/tmp/tmpjd45me00/vg6yfpsq.json', 'init=/tmp/tmpjd45me00/ab9cj6sn.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model56hl7aqk/prophet_model-20260803145400.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:00 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:00 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/83v3_3px.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jl4dhr7w.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None

Build prophet model for  store_4_dept_81
Build prophet model for  store_4_dept_82

DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=87138', 'data', 'file=/tmp/tmpjd45me00/83v3_3px.json', 'init=/tmp/tmpjd45me00/jl4dhr7w.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modellhoqga27/prophet_model-20260803145400.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:00 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:00 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4io5902i.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2qlqgyik.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=54481', 'data', 'file=/tmp/tmpjd45me00/4io5902i.json', 'init=/tmp/tmpjd45me00/2qlqgyik.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelqy1mv01_/prophet_model-20260803145400.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:00 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:00 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_4_dept_83
Build prophet model for  store_4_dept_85

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rxxw_8pf.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6gxnnv2_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=94768', 'data', 'file=/tmp/tmpjd45me00/rxxw_8pf.json', 'init=/tmp/tmpjd45me00/6gxnnv2_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model38fx1gif/prophet_model-20260803145400.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:00 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:00 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/z12kgq30.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/h9ui4gde.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=50772', 'data', 'file=/tmp/tmpjd45me00/z12kgq30.json', 'init=/tmp/tmpjd45me00/h9ui4gde.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modele3yoneis/prophet_model-20260803145401.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:01 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:01 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_4_dept_87
Build prophet model for  store_4_dept_9

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/sa9m2xh3.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/p36co7m0.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=98904', 'data', 'file=/tmp/tmpjd45me00/sa9m2xh3.json', 'init=/tmp/tmpjd45me00/p36co7m0.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model9z5v4n27/prophet_model-20260803145401.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:01 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:01 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9wuu576y.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/tycydw4o.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=73902', 'data', 'file=/tmp/tmpjd45me00/9wuu576y.json', 'init=/tmp/tmpjd45me00/tycydw4o.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelz0katdfw/prophet_model-20260803145401.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:01 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:01 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hsfudpnr.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8asxpv7p.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=59924', 'data', 'file=/tmp/tmpjd45me00/hsfudpnr.json', 'init=/tmp/tmpjd45me00/8asxpv7p.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model0y68qdqp/prophet_model-20260803145401.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:01 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_4_dept_90
Build prophet model for  store_4_dept_91

14:54:01 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/yuduxhu7.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dyy4_0qm.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=11525', 'data', 'file=/tmp/tmpjd45me00/yuduxhu7.json', 'init=/tmp/tmpjd45me00/dyy4_0qm.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelflz0363o/prophet_model-20260803145401.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:01 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:01 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_4_dept_92
Build prophet model for  store_4_dept_93

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mxfg5o5_.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/66ag187t.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=85615', 'data', 'file=/tmp/tmpjd45me00/mxfg5o5_.json', 'init=/tmp/tmpjd45me00/66ag187t.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelqvjeuxe_/prophet_model-20260803145401.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:01 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:02 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_4_dept_94
Build prophet model for  store_4_dept_95

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8qer6y14.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ls5hucwh.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=30578', 'data', 'file=/tmp/tmpjd45me00/8qer6y14.json', 'init=/tmp/tmpjd45me00/ls5hucwh.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelelnyyp59/prophet_model-20260803145402.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:02 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:02 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bnhxqkax.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/91zyvxbm.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=35764', 'data', 'file=/tmp/tmpjd45me00/bnhxqkax.json', 'init=/tmp/tmpjd45me00/91zyvxbm.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modely7jtjs6p/prophet_model-20260803145402.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:02 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_4_dept_96
Build prophet model for  store_4_dept_97

14:54:02 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/t_5acx3v.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pf0a6ppz.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=28514', 'data', 'file=/tmp/tmpjd45me00/t_5acx3v.json', 'init=/tmp/tmpjd45me00/pf0a6ppz.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeldoijcobg/prophet_model-20260803145402.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:02 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:02 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/u23wvs7w.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qm9fjlfh.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=17641', 'data', 'file=/tmp/tmpjd45me00/u23wvs7w.json', 'init=/tmp/tmpjd45me00/qm9fjlfh.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelvjx9izmn/prophet_model-20260803145402.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:02 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_4_dept_98
Build prophet model for  store_5_dept_1

14:54:02 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/nlzd3oc0.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/cjujmg20.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=5681', 'data', 'file=/tmp/tmpjd45me00/nlzd3oc0.json', 'init=/tmp/tmpjd45me00/cjujmg20.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelpertx_n7/prophet_model-20260803145402.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:02 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:03 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_5_dept_10
Build prophet model for  store_5_dept_11

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/x9uemimm.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pqtxr49s.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=8654', 'data', 'file=/tmp/tmpjd45me00/x9uemimm.json', 'init=/tmp/tmpjd45me00/pqtxr49s.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model159orz02/prophet_model-20260803145403.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:03 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:03 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pwj6alw_.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/69ybc_0c.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=44894', 'data', 'file=/tmp/tmpjd45me00/pwj6alw_.json', 'init=/tmp/tmpjd45me00/69ybc_0c.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelooiccw4y/prophet_model-20260803145403.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:03 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:03 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_5_dept_12
Build prophet model for  store_5_dept_13

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wlw81dbu.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/tz0yrovg.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=53938', 'data', 'file=/tmp/tmpjd45me00/wlw81dbu.json', 'init=/tmp/tmpjd45me00/tz0yrovg.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelrfkh2qql/prophet_model-20260803145403.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:03 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:03 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/tgziu344.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/chzvhqv2.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=3758', 'data', 'file=/tmp/tmpjd45me00/tgziu344.json', 'init=/tmp/tmpjd45me00/chzvhqv2.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeln1bliwgv/prophet_model-20260803145403.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:03 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:03 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ii1ee5ya.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gyhl82g5.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=20834', 'data', 'file=/tmp/tmpjd45me00/ii1ee5ya.json', 'init=/tmp/tmpjd45me00/gyhl82g5.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model9jkjw741/prophet_model-20260803145403.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:03 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_5_dept_14
Build prophet model for  store_5_dept_16

14:54:04 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/f9u7_lpp.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/oif3139t.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=20357', 'data', 'file=/tmp/tmpjd45me00/f9u7_lpp.json', 'init=/tmp/tmpjd45me00/oif3139t.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelatz4jz8p/prophet_model-20260803145404.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:04 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:04 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xhrzfxu4.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/50ccclys.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=94505', 'data', 'file=/tmp/tmpjd45me00/xhrzfxu4.json', 'init=/tmp/tmpjd45me00/50ccclys.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeluzfgwsz0/prophet_model-20260803145404.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:54:04 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_5_dept_17
Build prophet model for  store_5_dept_18

14:54:05 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/u2vn5549.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ga91qilm.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=51984', 'data', 'file=/tmp/tmpjd45me00/u2vn5549.json', 'init=/tmp/tmpjd45me00/ga91qilm.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model4wiu9458/prophet_model-20260803145405.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:05 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:05 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_5_dept_2

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0n7t5i5d.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ukp1evqa.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=581', 'data', 'file=/tmp/tmpjd45me00/0n7t5i5d.json', 'init=/tmp/tmpjd45me00/ukp1evqa.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model0303olby/prophet_model-20260803145405.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:05 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:05 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8o8axx2x.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zjppcvyf.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=69480', 'data', 'file=/tmp/tmpjd45me00/8o8axx2x.json', 'init=/tmp/tmpjd45me00/zjppcvyf.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelpnpdb0rv/prophet_model-20260803145406.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:06 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_5_dept_20
Build prophet model for  store_5_dept_21

14:54:06 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fubwfr4_.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/m7f6jnly.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=14320', 'data', 'file=/tmp/tmpjd45me00/fubwfr4_.json', 'init=/tmp/tmpjd45me00/m7f6jnly.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelgj4p0iel/prophet_model-20260803145406.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:06 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:06 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/f5uvenzg.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/tsln6p38.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None

Build prophet model for  store_5_dept_22
Build prophet model for  store_5_dept_23

DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=60940', 'data', 'file=/tmp/tmpjd45me00/f5uvenzg.json', 'init=/tmp/tmpjd45me00/tsln6p38.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelens1_suf/prophet_model-20260803145406.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:06 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:06 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ulitj7e3.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/12ez9e3j.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=17765', 'data', 'file=/tmp/tmpjd45me00/ulitj7e3.json', 'init=/tmp/tmpjd45me00/12ez9e3j.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelvgfokp5r/prophet_model-20260803145406.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:06 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:06 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/kkj_v0c3.json

Build prophet model for  store_5_dept_24
Build prophet model for  store_5_dept_25

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wdz0lbsv.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=74967', 'data', 'file=/tmp/tmpjd45me00/kkj_v0c3.json', 'init=/tmp/tmpjd45me00/wdz0lbsv.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelf99lbvhs/prophet_model-20260803145406.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:06 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:06 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gtn3ezg0.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bucd25p9.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=92787', 'data', 'file=/tmp/tmpjd45me00/gtn3ezg0.json', 'init=/tmp/tmpjd45me00/bucd25p9.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelit7n25al/prophet_model-20260803145406.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:06 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:06 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9ldyk2hy.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wrwx0ejw.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=81048', 'data', 'file=/tmp/tmpjd45me00/9ldyk2hy.json', 'init=/tmp/tmpjd45me00/wrwx0ejw.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model5ygvnjoa/prophet_model-20260803145407.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:07 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_5_dept_26
Build prophet model for  store_5_dept_27

14:54:07 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/g9jwvksp.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/kiv5rj2u.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=28997', 'data', 'file=/tmp/tmpjd45me00/g9jwvksp.json', 'init=/tmp/tmpjd45me00/kiv5rj2u.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelqrlf6q3e/prophet_model-20260803145407.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:07 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:07 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/twerbgpd.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qlc6x5xs.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=43986', 'data', 'file=/tmp/tmpjd45me00/twerbgpd.json', 'init=/tmp/tmpjd45me00/qlc6x5xs.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelqe9mwzko/prophet_model-20260803145407.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:07 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:07 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_5_dept_28
Build prophet model for  store_5_dept_29

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/yh5flk6j.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/l8cgzzbg.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=39039', 'data', 'file=/tmp/tmpjd45me00/yh5flk6j.json', 'init=/tmp/tmpjd45me00/l8cgzzbg.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelghaj_e87/prophet_model-20260803145407.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:07 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:07 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/keih56oq.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3l8oyqtf.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=97469', 'data', 'file=/tmp/tmpjd45me00/keih56oq.json', 'init=/tmp/tmpjd45me00/3l8oyqtf.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelvn57nm8a/prophet_model-20260803145407.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:07 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_5_dept_3
Build prophet model for  store_5_dept_30

14:54:07 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/yrbmd0tx.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/uaj8el6c.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=82360', 'data', 'file=/tmp/tmpjd45me00/yrbmd0tx.json', 'init=/tmp/tmpjd45me00/uaj8el6c.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model5_rpuzag/prophet_model-20260803145408.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:08 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:08 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_5_dept_31
Build prophet model for  store_5_dept_32

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/y81h2f18.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9nhqtc95.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=38323', 'data', 'file=/tmp/tmpjd45me00/y81h2f18.json', 'init=/tmp/tmpjd45me00/9nhqtc95.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelrvpe7_we/prophet_model-20260803145408.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:08 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:08 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/p6vni14u.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/cloga1qa.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=54391', 'data', 'file=/tmp/tmpjd45me00/p6vni14u.json', 'init=/tmp/tmpjd45me00/cloga1qa.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model7he8v6eb/prophet_model-20260803145408.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:08 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:08 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_5_dept_33
Build prophet model for  store_5_dept_34

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2va59mtc.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zfct9aih.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=70460', 'data', 'file=/tmp/tmpjd45me00/2va59mtc.json', 'init=/tmp/tmpjd45me00/zfct9aih.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelyfmozu5c/prophet_model-20260803145408.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:08 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:08 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/57mvw_t6.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qb2r1icf.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=80044', 'data', 'file=/tmp/tmpjd45me00/57mvw_t6.json', 'init=/tmp/tmpjd45me00/qb2r1icf.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeli1o9hln6/prophet_model-20260803145409.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:09 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_5_dept_35

14:54:09 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qar6jd9t.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/tfp67bc2.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=40282', 'data', 'file=/tmp/tmpjd45me00/qar6jd9t.json', 'init=/tmp/tmpjd45me00/tfp67bc2.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modela685ojx2/prophet_model-20260803145409.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:09 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:09 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_5_dept_36

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/oippt56l.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/luzem_im.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=34663', 'data', 'file=/tmp/tmpjd45me00/oippt56l.json', 'init=/tmp/tmpjd45me00/luzem_im.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelxrovuvc8/prophet_model-20260803145409.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:09 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:09 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_5_dept_38
Build prophet model for  store_5_dept_4

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/91y0ibhw.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ccmh0q98.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=11692', 'data', 'file=/tmp/tmpjd45me00/91y0ibhw.json', 'init=/tmp/tmpjd45me00/ccmh0q98.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelhdxp3duk/prophet_model-20260803145409.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:09 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:09 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2rskxpen.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/96ky9bq7.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=64908', 'data', 'file=/tmp/tmpjd45me00/2rskxpen.json', 'init=/tmp/tmpjd45me00/96ky9bq7.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelk2072jsx/prophet_model-20260803145410.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:10 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:10 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_5_dept_40
Build prophet model for  store_5_dept_41

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8og_kdci.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9e_kp3lt.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=56420', 'data', 'file=/tmp/tmpjd45me00/8og_kdci.json', 'init=/tmp/tmpjd45me00/9e_kp3lt.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model8119fank/prophet_model-20260803145410.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:10 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:10 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wpy74k6d.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qiq2czfw.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=37150', 'data', 'file=/tmp/tmpjd45me00/wpy74k6d.json', 'init=/tmp/tmpjd45me00/qiq2czfw.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model660ytg4y/prophet_model-20260803145410.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:10 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:10 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_5_dept_42

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/c0502aut.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/069lw0sg.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=28281', 'data', 'file=/tmp/tmpjd45me00/c0502aut.json', 'init=/tmp/tmpjd45me00/069lw0sg.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelllxy6zs5/prophet_model-20260803145410.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:10 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_5_dept_44

14:54:11 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/f6aag3d8.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3xubq9xc.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=24969', 'data', 'file=/tmp/tmpjd45me00/f6aag3d8.json', 'init=/tmp/tmpjd45me00/3xubq9xc.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelwf6_si0m/prophet_model-20260803145411.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:11 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:11 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/k9ahcd5i.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/73ddehnz.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=98948', 'data', 'file=/tmp/tmpjd45me00/k9ahcd5i.json', 'init=/tmp/tmpjd45me00/73ddehnz.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelq8enokh0/prophet_model-20260803145411.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:11 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_5_dept_46
Build prophet model for  store_5_dept_5

14:54:11 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/g9c2ccbb.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4fx8rua3.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=5163', 'data', 'file=/tmp/tmpjd45me00/g9c2ccbb.json', 'init=/tmp/tmpjd45me00/4fx8rua3.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelmtt2p64k/prophet_model-20260803145411.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:11 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:11 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_5_dept_52
Build prophet model for  store_5_dept_54

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/f28ly644.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zk1d_dgt.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=58315', 'data', 'file=/tmp/tmpjd45me00/f28ly644.json', 'init=/tmp/tmpjd45me00/zk1d_dgt.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelaeqqoorj/prophet_model-20260803145411.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:54:11 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:12 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/v724j2yo.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/13j050h_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=12953', 'data', 'file=/tmp/tmpjd45me00/v724j2yo.json', 'init=/tmp/tmpjd45me00/13j050h_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model1bgrw471/prophet_model-20260803145413.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:13 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:13 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/aqey6_vo.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/v2jk_w2f.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=99783', 'data', 'file=/tmp/tmpjd45me00/aqey6_vo.json', 'init=/tmp/tmpjd45me00/v2jk_w2f.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelc68k0mfp/prophet_model-20260803145413.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:13 - cmdstanpy - INFO - Chain [1] start processing

Build prophet model for  store_5_dept_55
Build prophet model for  store_5_dept_56

INFO:cmdstanpy:Chain [1] start processing
14:54:13 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/t_cxznu4.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/o4617upq.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=75931', 'data', 'file=/tmp/tmpjd45me00/t_cxznu4.json', 'init=/tmp/tmpjd45me00/o4617upq.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelj9_mbqow/prophet_model-20260803145413.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:54:13 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_5_dept_59

14:54:15 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9mia1ogz.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/97u_1t_b.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=26429', 'data', 'file=/tmp/tmpjd45me00/9mia1ogz.json', 'init=/tmp/tmpjd45me00/97u_1t_b.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model41pkjwgv/prophet_model-20260803145415.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:15 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_5_dept_6

14:54:15 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ai1xpp0j.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4e30hlxm.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=15206', 'data', 'file=/tmp/tmpjd45me00/ai1xpp0j.json', 'init=/tmp/tmpjd45me00/4e30hlxm.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelekqdtfq5/prophet_model-20260803145415.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:15 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:15 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2qv5vxvk.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6xn35khh.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=93943', 'data', 'file=/tmp/tmpjd45me00/2qv5vxvk.json', 'init=/tmp/tmpjd45me00/6xn35khh.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model5rfquqn5/prophet_model-20260803145415.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:15 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_5_dept_60
Build prophet model for  store_5_dept_67

14:54:15 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5tg3sknc.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/aw_92p1l.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=51804', 'data', 'file=/tmp/tmpjd45me00/5tg3sknc.json', 'init=/tmp/tmpjd45me00/aw_92p1l.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model2e9m8cob/prophet_model-20260803145415.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:15 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:15 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1szwf0if.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wrtvch7n.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=88136', 'data', 'file=/tmp/tmpjd45me00/1szwf0if.json', 'init=/tmp/tmpjd45me00/wrtvch7n.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelu_f04fyq/prophet_model-20260803145416.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:16 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_5_dept_7
Build prophet model for  store_5_dept_71

14:54:16 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/axkfruzw.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4bmuqvyl.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=77690', 'data', 'file=/tmp/tmpjd45me00/axkfruzw.json', 'init=/tmp/tmpjd45me00/4bmuqvyl.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model9m60srfh/prophet_model-20260803145416.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:16 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:16 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/m7x83oyy.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/h5km3cnb.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=86742', 'data', 'file=/tmp/tmpjd45me00/m7x83oyy.json', 'init=/tmp/tmpjd45me00/h5km3cnb.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelw6uzg2au/prophet_model-20260803145416.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:16 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_5_dept_72
Build prophet model for  store_5_dept_74

14:54:16 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/swi3alps.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/c0f83d98.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=727', 'data', 'file=/tmp/tmpjd45me00/swi3alps.json', 'init=/tmp/tmpjd45me00/c0f83d98.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelub1vu9am/prophet_model-20260803145416.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:16 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:16 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gy2_vmf7.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_139i8sg.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=22109', 'data', 'file=/tmp/tmpjd45me00/gy2_vmf7.json', 'init=/tmp/tmpjd45me00/_139i8sg.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelc27duh3x/prophet_model-20260803145416.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:16 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_5_dept_79
Build prophet model for  store_5_dept_8

14:54:16 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ufwe3dul.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/q00j9ihh.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=87099', 'data', 'file=/tmp/tmpjd45me00/ufwe3dul.json', 'init=/tmp/tmpjd45me00/q00j9ihh.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeldby5gz9x/prophet_model-20260803145416.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:16 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_5_dept_81

14:54:17 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/s3py_6jn.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/op7k5fbq.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=31798', 'data', 'file=/tmp/tmpjd45me00/s3py_6jn.json', 'init=/tmp/tmpjd45me00/op7k5fbq.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model010h4tv4/prophet_model-20260803145417.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:17 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_5_dept_82

14:54:17 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ewaeayu8.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gcylsd_m.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=29720', 'data', 'file=/tmp/tmpjd45me00/ewaeayu8.json', 'init=/tmp/tmpjd45me00/gcylsd_m.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model9e15qyxq/prophet_model-20260803145417.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:17 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:17 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/kjbri23q.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wbtiwpyp.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=85740', 'data', 'file=/tmp/tmpjd45me00/kjbri23q.json', 'init=/tmp/tmpjd45me00/wbtiwpyp.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_yo72cit/prophet_model-20260803145417.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:17 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_5_dept_85
Build prophet model for  store_5_dept_87

14:54:17 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4payhsty.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1wp_jcq1.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=33397', 'data', 'file=/tmp/tmpjd45me00/4payhsty.json', 'init=/tmp/tmpjd45me00/1wp_jcq1.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_r1n6fi6/prophet_model-20260803145417.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:18 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:18 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ea1952vj.json

Build prophet model for  store_5_dept_9
Build prophet model for  store_5_dept_90

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/12yw7kg9.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=18843', 'data', 'file=/tmp/tmpjd45me00/ea1952vj.json', 'init=/tmp/tmpjd45me00/12yw7kg9.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelz3g6mowd/prophet_model-20260803145418.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:18 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:18 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bzntk_mp.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2k6i6loa.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=28286', 'data', 'file=/tmp/tmpjd45me00/bzntk_mp.json', 'init=/tmp/tmpjd45me00/2k6i6loa.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelo3uxaiq9/prophet_model-20260803145418.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:18 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_5_dept_91

14:54:18 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/x0mx0zty.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/awe9x4pd.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=40663', 'data', 'file=/tmp/tmpjd45me00/x0mx0zty.json', 'init=/tmp/tmpjd45me00/awe9x4pd.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelnhffe4wv/prophet_model-20260803145418.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:18 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_5_dept_92

14:54:19 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/nriob12q.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qgbm_7mj.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=82269', 'data', 'file=/tmp/tmpjd45me00/nriob12q.json', 'init=/tmp/tmpjd45me00/qgbm_7mj.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model771s2fb0/prophet_model-20260803145419.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:19 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:19 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_5_dept_95
Build prophet model for  store_5_dept_96

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/oi6es6c0.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/v9xa6oe9.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=96469', 'data', 'file=/tmp/tmpjd45me00/oi6es6c0.json', 'init=/tmp/tmpjd45me00/v9xa6oe9.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model88saqj08/prophet_model-20260803145419.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:19 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:19 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/d5bjibrn.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/eqfzwtda.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=16664', 'data', 'file=/tmp/tmpjd45me00/d5bjibrn.json', 'init=/tmp/tmpjd45me00/eqfzwtda.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelyqz5102h/prophet_model-20260803145419.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:19 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:19 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1_ljmagi.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/b8b2unir.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=37012', 'data', 'file=/tmp/tmpjd45me00/1_ljmagi.json', 'init=/tmp/tmpjd45me00/b8b2unir.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model08of8d4o/prophet_model-20260803145419.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:19 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_6_dept_1
Build prophet model for  store_6_dept_10

14:54:19 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gi_fllcp.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/d9u9u1r5.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=48171', 'data', 'file=/tmp/tmpjd45me00/gi_fllcp.json', 'init=/tmp/tmpjd45me00/d9u9u1r5.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model97zh0vxe/prophet_model-20260803145419.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:19 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:20 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/sdtzbqrh.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/b89m8em7.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=6640', 'data', 'file=/tmp/tmpjd45me00/sdtzbqrh.json', 'init=/tmp/tmpjd45me00/b89m8em7.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model3wiikwwh/prophet_model-20260803145420.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:20 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_6_dept_11
Build prophet model for  store_6_dept_12

14:54:20 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/17pq0xmg.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8ph016oz.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=8642', 'data', 'file=/tmp/tmpjd45me00/17pq0xmg.json', 'init=/tmp/tmpjd45me00/8ph016oz.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelhs7p33q0/prophet_model-20260803145420.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:20 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:20 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_6_dept_13
Build prophet model for  store_6_dept_14

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2ei_1vtr.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/e1tes_gf.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=64177', 'data', 'file=/tmp/tmpjd45me00/2ei_1vtr.json', 'init=/tmp/tmpjd45me00/e1tes_gf.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelg1hpeqaa/prophet_model-20260803145420.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:20 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:20 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wdqqq276.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/nx54_r83.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=4712', 'data', 'file=/tmp/tmpjd45me00/wdqqq276.json', 'init=/tmp/tmpjd45me00/nx54_r83.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model1yggtrla/prophet_model-20260803145420.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:20 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:20 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_6_dept_16
Build prophet model for  store_6_dept_17

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/p6z3k9_8.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/iw38qh0c.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=28517', 'data', 'file=/tmp/tmpjd45me00/p6z3k9_8.json', 'init=/tmp/tmpjd45me00/iw38qh0c.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelrp7p431q/prophet_model-20260803145420.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:20 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:20 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/cjbuxbop.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wf5xecym.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=66412', 'data', 'file=/tmp/tmpjd45me00/cjbuxbop.json', 'init=/tmp/tmpjd45me00/wf5xecym.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeluw5seo40/prophet_model-20260803145421.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:54:21 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_6_dept_18

14:54:23 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/etdk3izp.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/obo80ftx.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=40005', 'data', 'file=/tmp/tmpjd45me00/etdk3izp.json', 'init=/tmp/tmpjd45me00/obo80ftx.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelpmwahirc/prophet_model-20260803145423.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:23 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_6_dept_19

14:54:24 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pdtpwznt.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4tj63rx6.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=34452', 'data', 'file=/tmp/tmpjd45me00/pdtpwznt.json', 'init=/tmp/tmpjd45me00/4tj63rx6.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelnw_9yl39/prophet_model-20260803145424.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:24 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:24 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/giviajyl.json

Build prophet model for  store_6_dept_2
Build prophet model for  store_6_dept_20

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ym2hu89f.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=30435', 'data', 'file=/tmp/tmpjd45me00/giviajyl.json', 'init=/tmp/tmpjd45me00/ym2hu89f.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modela4_mvzi0/prophet_model-20260803145424.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:24 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:24 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5is7dlct.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zsfcrjje.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=26088', 'data', 'file=/tmp/tmpjd45me00/5is7dlct.json', 'init=/tmp/tmpjd45me00/zsfcrjje.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model7d4ykzr5/prophet_model-20260803145424.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:24 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_6_dept_21

14:54:24 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bgwnrscl.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/atn7swqo.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=64707', 'data', 'file=/tmp/tmpjd45me00/bgwnrscl.json', 'init=/tmp/tmpjd45me00/atn7swqo.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modely3dngvv4/prophet_model-20260803145424.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:24 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:25 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/283zjefg.json

Build prophet model for  store_6_dept_22
Build prophet model for  store_6_dept_23

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fndh39ya.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=42269', 'data', 'file=/tmp/tmpjd45me00/283zjefg.json', 'init=/tmp/tmpjd45me00/fndh39ya.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelp3xrbr64/prophet_model-20260803145425.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:25 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:25 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/teznwmhl.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0nslnpzy.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=85692', 'data', 'file=/tmp/tmpjd45me00/teznwmhl.json', 'init=/tmp/tmpjd45me00/0nslnpzy.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model5zdlmm1q/prophet_model-20260803145425.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:25 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:25 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/iedikht6.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xght0mn5.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=72979', 'data', 'file=/tmp/tmpjd45me00/iedikht6.json', 'init=/tmp/tmpjd45me00/xght0mn5.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelsn1m_oet/prophet_model-20260803145425.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']

Build prophet model for  store_6_dept_24
Build prophet model for  store_6_dept_25

14:54:25 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:25 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/09eo_ulb.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/prfongw2.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=79625', 'data', 'file=/tmp/tmpjd45me00/09eo_ulb.json', 'init=/tmp/tmpjd45me00/prfongw2.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelzjv074pv/prophet_model-20260803145425.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:25 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:25 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rva260gf.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ezfvkups.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=44125', 'data', 'file=/tmp/tmpjd45me00/rva260gf.json', 'init=/tmp/tmpjd45me00/ezfvkups.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelxq3qlz32/prophet_model-20260803145425.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:25 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_6_dept_26
Build prophet model for  store_6_dept_27

14:54:25 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1gsbvwfe.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/h1rfllhn.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=82906', 'data', 'file=/tmp/tmpjd45me00/1gsbvwfe.json', 'init=/tmp/tmpjd45me00/h1rfllhn.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelqla9x3ds/prophet_model-20260803145425.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:25 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:26 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_6_dept_28
Build prophet model for  store_6_dept_29

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1ana9lww.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/49kazvrw.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=42178', 'data', 'file=/tmp/tmpjd45me00/1ana9lww.json', 'init=/tmp/tmpjd45me00/49kazvrw.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeli14gr0cs/prophet_model-20260803145426.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:26 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:26 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6c8vls10.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/w3wu7qou.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=949', 'data', 'file=/tmp/tmpjd45me00/6c8vls10.json', 'init=/tmp/tmpjd45me00/w3wu7qou.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model4tsstskr/prophet_model-20260803145426.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:26 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:26 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/g1_w05lj.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/97y2nfsr.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=84708', 'data', 'file=/tmp/tmpjd45me00/g1_w05lj.json', 'init=/tmp/tmpjd45me00/97y2nfsr.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_j2zx5yg/prophet_model-20260803145426.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:26 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_6_dept_3
Build prophet model for  store_6_dept_30

14:54:26 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xeqdyxz2.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/kwxopsgd.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=84569', 'data', 'file=/tmp/tmpjd45me00/xeqdyxz2.json', 'init=/tmp/tmpjd45me00/kwxopsgd.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model1n0qqc7q/prophet_model-20260803145426.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:26 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:26 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/nr5dvpmq.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4zogk8wd.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=60090', 'data', 'file=/tmp/tmpjd45me00/nr5dvpmq.json', 'init=/tmp/tmpjd45me00/4zogk8wd.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelle7jjyy8/prophet_model-20260803145426.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:26 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:26 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_6_dept_31
Build prophet model for  store_6_dept_32

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/t8ml6b8l.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zs6q2693.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=38733', 'data', 'file=/tmp/tmpjd45me00/t8ml6b8l.json', 'init=/tmp/tmpjd45me00/zs6q2693.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelxh33edy4/prophet_model-20260803145427.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:27 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:27 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/q203yw8r.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qhfhp9tn.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=58177', 'data', 'file=/tmp/tmpjd45me00/q203yw8r.json', 'init=/tmp/tmpjd45me00/qhfhp9tn.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelomefmxf3/prophet_model-20260803145427.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:27 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_6_dept_33
Build prophet model for  store_6_dept_34

14:54:27 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/i6cmcdvk.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ia1k3ouz.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=36119', 'data', 'file=/tmp/tmpjd45me00/i6cmcdvk.json', 'init=/tmp/tmpjd45me00/ia1k3ouz.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelk5nn059k/prophet_model-20260803145427.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:27 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:27 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/u0sfxwf3.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0c5ny68g.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=97691', 'data', 'file=/tmp/tmpjd45me00/u0sfxwf3.json', 'init=/tmp/tmpjd45me00/0c5ny68g.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model4n2y8_em/prophet_model-20260803145427.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:27 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:27 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_6_dept_35
Build prophet model for  store_6_dept_36

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jqi0w22f.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/q449rxuk.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=43787', 'data', 'file=/tmp/tmpjd45me00/jqi0w22f.json', 'init=/tmp/tmpjd45me00/q449rxuk.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model4k74ozp_/prophet_model-20260803145427.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:27 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:27 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_6_dept_37
Build prophet model for  store_6_dept_38

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/s16w2nvf.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/nvvvuiob.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=99811', 'data', 'file=/tmp/tmpjd45me00/s16w2nvf.json', 'init=/tmp/tmpjd45me00/nvvvuiob.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelz9588qov/prophet_model-20260803145427.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:27 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:27 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/essl9_0b.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/31nn5zm4.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=11290', 'data', 'file=/tmp/tmpjd45me00/essl9_0b.json', 'init=/tmp/tmpjd45me00/31nn5zm4.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeldeqjzvbm/prophet_model-20260803145427.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:27 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:28 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mjon0zlp.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mktvn646.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=74050', 'data', 'file=/tmp/tmpjd45me00/mjon0zlp.json', 'init=/tmp/tmpjd45me00/mktvn646.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelyuhrvkrk/prophet_model-20260803145428.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:28 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_6_dept_4
Build prophet model for  store_6_dept_40

14:54:28 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/uexehhin.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ftznoelh.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=79907', 'data', 'file=/tmp/tmpjd45me00/uexehhin.json', 'init=/tmp/tmpjd45me00/ftznoelh.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model6qy7mac0/prophet_model-20260803145428.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:28 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:28 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_6_dept_41
Build prophet model for  store_6_dept_42

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qfpdrbm0.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/w6jyqqt5.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=88928', 'data', 'file=/tmp/tmpjd45me00/qfpdrbm0.json', 'init=/tmp/tmpjd45me00/w6jyqqt5.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelzovz1s_o/prophet_model-20260803145428.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:28 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:28 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/txt59r0x.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/h9b889ew.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=16688', 'data', 'file=/tmp/tmpjd45me00/txt59r0x.json', 'init=/tmp/tmpjd45me00/h9b889ew.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model65sk8_ll/prophet_model-20260803145428.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:28 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:28 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_6_dept_44

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2f4kubo9.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jo7ejp1q.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=21933', 'data', 'file=/tmp/tmpjd45me00/2f4kubo9.json', 'init=/tmp/tmpjd45me00/jo7ejp1q.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelkq86x73l/prophet_model-20260803145429.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:29 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:29 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_6_dept_45
Skip  store_6_dept_45 due to lack of data
Build prophet model for  store_6_dept_46
Build prophet model for  store_6_dept_48

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/cr7lh6yq.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dvlnr98a.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=73419', 'data', 'file=/tmp/tmpjd45me00/cr7lh6yq.json', 'init=/tmp/tmpjd45me00/dvlnr98a.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelw4sj5bxu/prophet_model-20260803145429.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:29 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:29 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2geqv1dq.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/nss_nrnn.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=47233', 'data', 'file=/tmp/tmpjd45me00/2geqv1dq.json', 'init=/tmp/tmpjd45me00/nss_nrnn.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelh3hbq17x/prophet_model-20260803145429.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:29 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:29 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/m7k5v84x.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mk3896im.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=94231', 'data', 'file=/tmp/tmpjd45me00/m7k5v84x.json', 'init=/tmp/tmpjd45me00/mk3896im.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model29x0audw/prophet_model-20260803145429.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:29 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_6_dept_49
Build prophet model for  store_6_dept_5

14:54:29 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vf30m1e0.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_z31y0ms.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=94212', 'data', 'file=/tmp/tmpjd45me00/vf30m1e0.json', 'init=/tmp/tmpjd45me00/_z31y0ms.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model3lxtojqu/prophet_model-20260803145429.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:29 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:29 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/q62wxw_t.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/nrz2dh5t.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=95805', 'data', 'file=/tmp/tmpjd45me00/q62wxw_t.json', 'init=/tmp/tmpjd45me00/nrz2dh5t.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_f5fm4g_/prophet_model-20260803145429.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:29 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_6_dept_52
Build prophet model for  store_6_dept_54

14:54:29 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/sk86rhxu.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8x3r5_cu.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=40434', 'data', 'file=/tmp/tmpjd45me00/sk86rhxu.json', 'init=/tmp/tmpjd45me00/8x3r5_cu.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_8hvrjxl/prophet_model-20260803145430.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:30 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:30 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xn4173ot.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gecr1_06.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=10101', 'data', 'file=/tmp/tmpjd45me00/xn4173ot.json', 'init=/tmp/tmpjd45me00/gecr1_06.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeli5hmqsvx/prophet_model-20260803145430.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:30 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_6_dept_55
Build prophet model for  store_6_dept_56

14:54:30 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2mvhx_xf.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/91c3t0y_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=80730', 'data', 'file=/tmp/tmpjd45me00/2mvhx_xf.json', 'init=/tmp/tmpjd45me00/91c3t0y_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_models177m_o_/prophet_model-20260803145430.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:30 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:30 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_4easalk.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/go0ax53e.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=17349', 'data', 'file=/tmp/tmpjd45me00/_4easalk.json', 'init=/tmp/tmpjd45me00/go0ax53e.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeljcmo8_x0/prophet_model-20260803145430.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:30 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_6_dept_58
Build prophet model for  store_6_dept_59

14:54:30 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wizyyhjf.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wvfpxo6a.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=68611', 'data', 'file=/tmp/tmpjd45me00/wizyyhjf.json', 'init=/tmp/tmpjd45me00/wvfpxo6a.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelcde05gt5/prophet_model-20260803145430.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:30 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:30 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xnxhl_eg.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8pxwljpn.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=42237', 'data', 'file=/tmp/tmpjd45me00/xnxhl_eg.json', 'init=/tmp/tmpjd45me00/8pxwljpn.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model3wlu_r_q/prophet_model-20260803145430.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:30 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_6_dept_6
Build prophet model for  store_6_dept_67

14:54:31 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fi40kugo.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/kco8c2uu.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=67936', 'data', 'file=/tmp/tmpjd45me00/fi40kugo.json', 'init=/tmp/tmpjd45me00/kco8c2uu.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelbeamnmkk/prophet_model-20260803145431.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:31 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:31 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/of72wbhi.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7pymh0od.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=94908', 'data', 'file=/tmp/tmpjd45me00/of72wbhi.json', 'init=/tmp/tmpjd45me00/7pymh0od.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model6ea2av5z/prophet_model-20260803145431.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:31 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_6_dept_7
Build prophet model for  store_6_dept_71

14:54:31 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/66oqzoyq.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ez_g89v2.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=64892', 'data', 'file=/tmp/tmpjd45me00/66oqzoyq.json', 'init=/tmp/tmpjd45me00/ez_g89v2.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelmg8gzcwi/prophet_model-20260803145431.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:31 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:31 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9rrm_g22.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/s38zpjz3.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=39642', 'data', 'file=/tmp/tmpjd45me00/9rrm_g22.json', 'init=/tmp/tmpjd45me00/s38zpjz3.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model8esg9iva/prophet_model-20260803145431.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:31 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_6_dept_72
Build prophet model for  store_6_dept_74

14:54:31 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ob1mwbtv.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vmcj2vij.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=59777', 'data', 'file=/tmp/tmpjd45me00/ob1mwbtv.json', 'init=/tmp/tmpjd45me00/vmcj2vij.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelia5nyliq/prophet_model-20260803145431.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:31 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:31 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/h1892ivs.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1o7yljj9.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=83409', 'data', 'file=/tmp/tmpjd45me00/h1892ivs.json', 'init=/tmp/tmpjd45me00/1o7yljj9.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelolx_z_o4/prophet_model-20260803145432.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:32 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_6_dept_79
Build prophet model for  store_6_dept_8

14:54:32 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vl_qvj0_.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vb_162f7.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=38485', 'data', 'file=/tmp/tmpjd45me00/vl_qvj0_.json', 'init=/tmp/tmpjd45me00/vb_162f7.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelru8uxrjw/prophet_model-20260803145432.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:32 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:32 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0ek_k6d6.json

Build prophet model for  store_6_dept_80
Build prophet model for  store_6_dept_81

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1_hrl2hz.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=16869', 'data', 'file=/tmp/tmpjd45me00/0ek_k6d6.json', 'init=/tmp/tmpjd45me00/1_hrl2hz.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeld1frx9np/prophet_model-20260803145432.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:32 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:32 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5xfubrmz.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/emuejxy_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=13245', 'data', 'file=/tmp/tmpjd45me00/5xfubrmz.json', 'init=/tmp/tmpjd45me00/emuejxy_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model3m0tz7q6/prophet_model-20260803145432.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:32 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:32 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7z6x8o6y.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0i219dug.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=52455', 'data', 'file=/tmp/tmpjd45me00/7z6x8o6y.json', 'init=/tmp/tmpjd45me00/0i219dug.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model4wxskv2i/prophet_model-20260803145432.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:32 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_6_dept_82
Build prophet model for  store_6_dept_83

14:54:32 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/a6c9g3io.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xogulqhj.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=35414', 'data', 'file=/tmp/tmpjd45me00/a6c9g3io.json', 'init=/tmp/tmpjd45me00/xogulqhj.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelv_ifj6ve/prophet_model-20260803145432.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:32 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:32 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vyoy22xd.json

Build prophet model for  store_6_dept_85
Build prophet model for  store_6_dept_87

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/q5n3rl4l.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=31971', 'data', 'file=/tmp/tmpjd45me00/vyoy22xd.json', 'init=/tmp/tmpjd45me00/q5n3rl4l.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelsrbkddr1/prophet_model-20260803145433.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:33 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:33 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dtcnkj7e.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vez1u6oq.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=56527', 'data', 'file=/tmp/tmpjd45me00/dtcnkj7e.json', 'init=/tmp/tmpjd45me00/vez1u6oq.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeltojl69ht/prophet_model-20260803145433.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:33 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:33 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wlgh8ycu.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/nggu00ro.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=79090', 'data', 'file=/tmp/tmpjd45me00/wlgh8ycu.json', 'init=/tmp/tmpjd45me00/nggu00ro.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model170xp1qu/prophet_model-20260803145433.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:33 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:33 - cmdstanpy - INFO - Chain [1] done processing

Build prophet model for  store_6_dept_9
Build prophet model for  store_6_dept_90

INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wgaycfzc.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vv4gvk_y.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=21194', 'data', 'file=/tmp/tmpjd45me00/wgaycfzc.json', 'init=/tmp/tmpjd45me00/vv4gvk_y.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model0b1dq605/prophet_model-20260803145433.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:33 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:33 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4h0gdax1.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0o6j79e2.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=82590', 'data', 'file=/tmp/tmpjd45me00/4h0gdax1.json', 'init=/tmp/tmpjd45me00/0o6j79e2.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelck2n12ul/prophet_model-20260803145433.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:33 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_6_dept_91
Build prophet model for  store_6_dept_92

14:54:33 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/d1cogd5e.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/q_fy_tf2.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=433', 'data', 'file=/tmp/tmpjd45me00/d1cogd5e.json', 'init=/tmp/tmpjd45me00/q_fy_tf2.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeltn4dv84i/prophet_model-20260803145433.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:33 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:33 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9pe4afzk.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/e9o9pp4t.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=53210', 'data', 'file=/tmp/tmpjd45me00/9pe4afzk.json', 'init=/tmp/tmpjd45me00/e9o9pp4t.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model3_tz2tfb/prophet_model-20260803145433.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:33 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_6_dept_93
Build prophet model for  store_6_dept_94

14:54:34 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/74_el_20.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6mxlosmz.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=79184', 'data', 'file=/tmp/tmpjd45me00/74_el_20.json', 'init=/tmp/tmpjd45me00/6mxlosmz.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeld0r2drpa/prophet_model-20260803145434.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:34 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:34 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_6_dept_95
Build prophet model for  store_6_dept_96

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qw6alvzj.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9xd_h9hw.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=27463', 'data', 'file=/tmp/tmpjd45me00/qw6alvzj.json', 'init=/tmp/tmpjd45me00/9xd_h9hw.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model50p37tyf/prophet_model-20260803145434.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:34 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:34 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bscjirt0.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/cdbhk1ep.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=67294', 'data', 'file=/tmp/tmpjd45me00/bscjirt0.json', 'init=/tmp/tmpjd45me00/cdbhk1ep.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelbp9ndj6m/prophet_model-20260803145434.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:34 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:34 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_6_dept_97

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/h_5iw0xr.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qhj4kdz6.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=61189', 'data', 'file=/tmp/tmpjd45me00/h_5iw0xr.json', 'init=/tmp/tmpjd45me00/qhj4kdz6.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelogs3n9l5/prophet_model-20260803145435.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:35 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:35 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_6_dept_98

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/elu4ck4_.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/t34v07fc.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=79246', 'data', 'file=/tmp/tmpjd45me00/elu4ck4_.json', 'init=/tmp/tmpjd45me00/t34v07fc.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model60gvtzzd/prophet_model-20260803145435.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:35 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_7_dept_1

14:54:35 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ekd5grmo.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/182u8pa4.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=92129', 'data', 'file=/tmp/tmpjd45me00/ekd5grmo.json', 'init=/tmp/tmpjd45me00/182u8pa4.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeleah12qyv/prophet_model-20260803145435.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:35 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_7_dept_10

14:54:35 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/35o_b7tc.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/k5ulv8mp.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=44151', 'data', 'file=/tmp/tmpjd45me00/35o_b7tc.json', 'init=/tmp/tmpjd45me00/k5ulv8mp.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeldlasvfm_/prophet_model-20260803145436.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:36 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:36 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_7_dept_11

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1fj0psch.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5om0w1q5.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=48452', 'data', 'file=/tmp/tmpjd45me00/1fj0psch.json', 'init=/tmp/tmpjd45me00/5om0w1q5.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model02i8fh4g/prophet_model-20260803145436.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:36 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_7_dept_12

14:54:36 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/i2k7qgrt.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5ny5w57w.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=6230', 'data', 'file=/tmp/tmpjd45me00/i2k7qgrt.json', 'init=/tmp/tmpjd45me00/5ny5w57w.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelzkqxkwxc/prophet_model-20260803145436.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:36 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_7_dept_13

14:54:36 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2pzdwxtk.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qbm9c0sh.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=75047', 'data', 'file=/tmp/tmpjd45me00/2pzdwxtk.json', 'init=/tmp/tmpjd45me00/qbm9c0sh.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model6dkacypl/prophet_model-20260803145437.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:37 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:37 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vwjg_oll.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/247bpf26.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=10598', 'data', 'file=/tmp/tmpjd45me00/vwjg_oll.json', 'init=/tmp/tmpjd45me00/247bpf26.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model6bqorktx/prophet_model-20260803145437.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:37 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_7_dept_14
Build prophet model for  store_7_dept_16

14:54:37 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/tmblx729.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/d_co_lz6.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=56428', 'data', 'file=/tmp/tmpjd45me00/tmblx729.json', 'init=/tmp/tmpjd45me00/d_co_lz6.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelopd_gk5m/prophet_model-20260803145437.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:37 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:37 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_7_dept_17
Build prophet model for  store_7_dept_18

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wv3a00pz.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qmohkkb0.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=90588', 'data', 'file=/tmp/tmpjd45me00/wv3a00pz.json', 'init=/tmp/tmpjd45me00/qmohkkb0.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelbq2rry5s/prophet_model-20260803145437.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:54:37 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:39 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/c5tfhi91.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/e7tzypls.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=18540', 'data', 'file=/tmp/tmpjd45me00/c5tfhi91.json', 'init=/tmp/tmpjd45me00/e7tzypls.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelfhw62k9z/prophet_model-20260803145439.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:39 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:39 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_7_dept_19
Skip  store_7_dept_19 due to lack of data
Build prophet model for  store_7_dept_2

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ti__phdu.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/df1z7dye.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=92827', 'data', 'file=/tmp/tmpjd45me00/ti__phdu.json', 'init=/tmp/tmpjd45me00/df1z7dye.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelsdgxxmd_/prophet_model-20260803145439.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:39 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:39 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_7_dept_20
Build prophet model for  store_7_dept_21

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/02_ncllj.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/nw9pcy_1.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=90525', 'data', 'file=/tmp/tmpjd45me00/02_ncllj.json', 'init=/tmp/tmpjd45me00/nw9pcy_1.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelxfgk3xsl/prophet_model-20260803145439.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:39 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:39 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gcba_n06.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8roc651t.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=70640', 'data', 'file=/tmp/tmpjd45me00/gcba_n06.json', 'init=/tmp/tmpjd45me00/8roc651t.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelqg9ssffa/prophet_model-20260803145439.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:39 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:39 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ongmk357.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/82ca_3h2.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=39364', 'data', 'file=/tmp/tmpjd45me00/ongmk357.json', 'init=/tmp/tmpjd45me00/82ca_3h2.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model65w67gqc/prophet_model-20260803145440.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:40 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_7_dept_22
Build prophet model for  store_7_dept_23

14:54:40 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mtygf8tg.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/47c5s2bh.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=79661', 'data', 'file=/tmp/tmpjd45me00/mtygf8tg.json', 'init=/tmp/tmpjd45me00/47c5s2bh.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelima2loyv/prophet_model-20260803145440.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:40 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:40 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_spakhpn.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/lq5q0ig5.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=71961', 'data', 'file=/tmp/tmpjd45me00/_spakhpn.json', 'init=/tmp/tmpjd45me00/lq5q0ig5.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelayp0u9uf/prophet_model-20260803145440.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:40 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_7_dept_24
Build prophet model for  store_7_dept_25

14:54:40 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/02vwmmzx.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2dv2zi0g.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=68166', 'data', 'file=/tmp/tmpjd45me00/02vwmmzx.json', 'init=/tmp/tmpjd45me00/2dv2zi0g.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model7gjhp9ye/prophet_model-20260803145440.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:40 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:40 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/oz60n528.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8spfjhhu.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=74639', 'data', 'file=/tmp/tmpjd45me00/oz60n528.json', 'init=/tmp/tmpjd45me00/8spfjhhu.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_mltb0xu/prophet_model-20260803145440.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:40 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_7_dept_26
Build prophet model for  store_7_dept_27

14:54:40 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dq9wezbf.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ne923cb1.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=10955', 'data', 'file=/tmp/tmpjd45me00/dq9wezbf.json', 'init=/tmp/tmpjd45me00/ne923cb1.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelx989ikdb/prophet_model-20260803145441.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:41 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:41 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_7_dept_28

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ebl1or41.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mke9n76c.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=79128', 'data', 'file=/tmp/tmpjd45me00/ebl1or41.json', 'init=/tmp/tmpjd45me00/mke9n76c.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model6z50xluc/prophet_model-20260803145441.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:41 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:41 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_7_dept_29
Build prophet model for  store_7_dept_3

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gvyi5kyy.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/antrj1vl.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=13068', 'data', 'file=/tmp/tmpjd45me00/gvyi5kyy.json', 'init=/tmp/tmpjd45me00/antrj1vl.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model9osksppg/prophet_model-20260803145441.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:41 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:41 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wlpboia9.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/tfac2mrg.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=18457', 'data', 'file=/tmp/tmpjd45me00/wlpboia9.json', 'init=/tmp/tmpjd45me00/tfac2mrg.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modely3drqlzf/prophet_model-20260803145441.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:41 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:41 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_7_dept_30

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vq6rxet5.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/85qbu1j7.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=26254', 'data', 'file=/tmp/tmpjd45me00/vq6rxet5.json', 'init=/tmp/tmpjd45me00/85qbu1j7.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_snprejn/prophet_model-20260803145441.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:41 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:41 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ew3x_59z.json

Build prophet model for  store_7_dept_31
Build prophet model for  store_7_dept_32

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/oeenubvz.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=20335', 'data', 'file=/tmp/tmpjd45me00/ew3x_59z.json', 'init=/tmp/tmpjd45me00/oeenubvz.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelbu5l7an1/prophet_model-20260803145442.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:42 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:42 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/m46qkpfe.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5f20dkq0.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=37548', 'data', 'file=/tmp/tmpjd45me00/m46qkpfe.json', 'init=/tmp/tmpjd45me00/5f20dkq0.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelvk5wm6xl/prophet_model-20260803145442.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:42 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:42 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fbzjdt6r.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/sn689iax.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=12122', 'data', 'file=/tmp/tmpjd45me00/fbzjdt6r.json', 'init=/tmp/tmpjd45me00/sn689iax.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelji4ktruy/prophet_model-20260803145442.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:42 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_7_dept_33
Build prophet model for  store_7_dept_34

14:54:42 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_dneat_v.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xvtv54l3.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=30050', 'data', 'file=/tmp/tmpjd45me00/_dneat_v.json', 'init=/tmp/tmpjd45me00/xvtv54l3.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelyz5eh6pi/prophet_model-20260803145442.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:42 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:42 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/e_4ih6zo.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6zh78ba4.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=61028', 'data', 'file=/tmp/tmpjd45me00/e_4ih6zo.json', 'init=/tmp/tmpjd45me00/6zh78ba4.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model6lw2l03s/prophet_model-20260803145443.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:43 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_7_dept_35
Build prophet model for  store_7_dept_36

14:54:43 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0fhk8vl4.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fyvfxmi3.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=56826', 'data', 'file=/tmp/tmpjd45me00/0fhk8vl4.json', 'init=/tmp/tmpjd45me00/fyvfxmi3.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelss1canfo/prophet_model-20260803145443.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:43 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:43 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0w__wekf.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/czi4p9pm.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=36009', 'data', 'file=/tmp/tmpjd45me00/0w__wekf.json', 'init=/tmp/tmpjd45me00/czi4p9pm.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model7pxofapj/prophet_model-20260803145443.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:43 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_7_dept_38
Build prophet model for  store_7_dept_4

14:54:43 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/me9v2mes.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/n9zgrg3h.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=38800', 'data', 'file=/tmp/tmpjd45me00/me9v2mes.json', 'init=/tmp/tmpjd45me00/n9zgrg3h.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model29d4oug0/prophet_model-20260803145443.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:43 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:43 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_7_dept_40

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5zficcks.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/r7cd7tlt.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=91729', 'data', 'file=/tmp/tmpjd45me00/5zficcks.json', 'init=/tmp/tmpjd45me00/r7cd7tlt.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelb9yr_rtx/prophet_model-20260803145443.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:43 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:44 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_7_dept_41
Build prophet model for  store_7_dept_42

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/r_wkrgkp.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/o2exi0t3.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=6693', 'data', 'file=/tmp/tmpjd45me00/r_wkrgkp.json', 'init=/tmp/tmpjd45me00/o2exi0t3.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model55622psz/prophet_model-20260803145444.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:44 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:44 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7kdq1d7x.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/56drs3es.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=24188', 'data', 'file=/tmp/tmpjd45me00/7kdq1d7x.json', 'init=/tmp/tmpjd45me00/56drs3es.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelr0e160h5/prophet_model-20260803145444.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:44 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:44 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wi21ybf5.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/a3eznius.json

Build prophet model for  store_7_dept_44
Build prophet model for  store_7_dept_45

DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=57014', 'data', 'file=/tmp/tmpjd45me00/wi21ybf5.json', 'init=/tmp/tmpjd45me00/a3eznius.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model7f9nbsd_/prophet_model-20260803145444.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:54:44 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:45 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jhva2f0w.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ryhjt_cs.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=32118', 'data', 'file=/tmp/tmpjd45me00/jhva2f0w.json', 'init=/tmp/tmpjd45me00/ryhjt_cs.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelp33qh_ja/prophet_model-20260803145446.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:46 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:46 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_7_dept_46

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/p_b5k6fa.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/edc6mfb5.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=96330', 'data', 'file=/tmp/tmpjd45me00/p_b5k6fa.json', 'init=/tmp/tmpjd45me00/edc6mfb5.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelb8zwg071/prophet_model-20260803145446.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:54:46 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_7_dept_49

14:54:47 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/k9g42bwd.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wzou1cff.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=11179', 'data', 'file=/tmp/tmpjd45me00/k9g42bwd.json', 'init=/tmp/tmpjd45me00/wzou1cff.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelagygmyha/prophet_model-20260803145447.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:47 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:47 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_7_dept_5

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/em_c34kl.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dvjssla5.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=25606', 'data', 'file=/tmp/tmpjd45me00/em_c34kl.json', 'init=/tmp/tmpjd45me00/dvjssla5.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelo69akduv/prophet_model-20260803145447.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:47 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_7_dept_51
Skip  store_7_dept_51 due to lack of data
Build prophet model for  store_7_dept_52

14:54:48 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fs4su62q.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ipsumlmt.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=11079', 'data', 'file=/tmp/tmpjd45me00/fs4su62q.json', 'init=/tmp/tmpjd45me00/ipsumlmt.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelmn3n393q/prophet_model-20260803145448.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:48 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:48 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_7_dept_54

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/aj23ygk1.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/v_7jv9w1.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=44446', 'data', 'file=/tmp/tmpjd45me00/aj23ygk1.json', 'init=/tmp/tmpjd45me00/v_7jv9w1.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelrpy7hiky/prophet_model-20260803145448.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:48 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:48 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_7_dept_55

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jsfee3rj.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rg3hm_pk.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=87660', 'data', 'file=/tmp/tmpjd45me00/jsfee3rj.json', 'init=/tmp/tmpjd45me00/rg3hm_pk.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_mzx0o11/prophet_model-20260803145448.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:48 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_7_dept_56

14:54:49 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/n_2jc14q.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4a6dkiz8.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=86747', 'data', 'file=/tmp/tmpjd45me00/n_2jc14q.json', 'init=/tmp/tmpjd45me00/4a6dkiz8.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model6ggb9la5/prophet_model-20260803145449.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:49 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:49 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_7_dept_59
Build prophet model for  store_7_dept_6

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/v7if_dq7.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/m5ibn7bo.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=77453', 'data', 'file=/tmp/tmpjd45me00/v7if_dq7.json', 'init=/tmp/tmpjd45me00/m5ibn7bo.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeljth_lvwz/prophet_model-20260803145449.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:49 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:49 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/n5pudkj7.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/cft067_1.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=84955', 'data', 'file=/tmp/tmpjd45me00/n5pudkj7.json', 'init=/tmp/tmpjd45me00/cft067_1.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeld3w35f2q/prophet_model-20260803145449.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:49 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:49 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_7_dept_60
Build prophet model for  store_7_dept_67

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/oq7qnb89.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8ji9v2ro.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=68826', 'data', 'file=/tmp/tmpjd45me00/oq7qnb89.json', 'init=/tmp/tmpjd45me00/8ji9v2ro.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeld55zeu8r/prophet_model-20260803145450.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:50 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:50 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/lp8n64cr.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vqub2lhx.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=49725', 'data', 'file=/tmp/tmpjd45me00/lp8n64cr.json', 'init=/tmp/tmpjd45me00/vqub2lhx.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeluzjafxja/prophet_model-20260803145450.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:50 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:50 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/abz8ovp6.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/17wfts3p.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=25833', 'data', 'file=/tmp/tmpjd45me00/abz8ovp6.json', 'init=/tmp/tmpjd45me00/17wfts3p.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelfsoi5eos/prophet_model-20260803145450.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:50 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_7_dept_7
Build prophet model for  store_7_dept_71

14:54:50 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6c_y5j7v.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/kjli1npn.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=98492', 'data', 'file=/tmp/tmpjd45me00/6c_y5j7v.json', 'init=/tmp/tmpjd45me00/kjli1npn.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeln32eq50h/prophet_model-20260803145450.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:50 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:50 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/k_bv8j8n.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/kqfsfu1i.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=83546', 'data', 'file=/tmp/tmpjd45me00/k_bv8j8n.json', 'init=/tmp/tmpjd45me00/kqfsfu1i.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model9tje1u8a/prophet_model-20260803145450.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:50 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_7_dept_72
Build prophet model for  store_7_dept_74

14:54:50 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_51d4wt9.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ml9eahqg.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=71359', 'data', 'file=/tmp/tmpjd45me00/_51d4wt9.json', 'init=/tmp/tmpjd45me00/ml9eahqg.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model5cc0v3vp/prophet_model-20260803145451.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:51 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:51 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jdncsvof.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/k8bdnb5g.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=96448', 'data', 'file=/tmp/tmpjd45me00/jdncsvof.json', 'init=/tmp/tmpjd45me00/k8bdnb5g.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model9q2vzwey/prophet_model-20260803145451.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:51 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_7_dept_79
Build prophet model for  store_7_dept_8

14:54:51 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ddtz1lqh.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9rns6h2u.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=50211', 'data', 'file=/tmp/tmpjd45me00/ddtz1lqh.json', 'init=/tmp/tmpjd45me00/9rns6h2u.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model6frj0dub/prophet_model-20260803145451.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:51 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:51 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_7_dept_81

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qt6lxesi.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fj0p1di8.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=47614', 'data', 'file=/tmp/tmpjd45me00/qt6lxesi.json', 'init=/tmp/tmpjd45me00/fj0p1di8.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modellf7apk61/prophet_model-20260803145451.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:51 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_7_dept_82

14:54:51 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/01psv8jv.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/lywrip5l.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=45332', 'data', 'file=/tmp/tmpjd45me00/01psv8jv.json', 'init=/tmp/tmpjd45me00/lywrip5l.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model0bhiq0wc/prophet_model-20260803145452.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:52 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:52 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_7_dept_83

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ep1h4snc.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9rsh3di2.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=40296', 'data', 'file=/tmp/tmpjd45me00/ep1h4snc.json', 'init=/tmp/tmpjd45me00/9rsh3di2.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeljn7gshst/prophet_model-20260803145452.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:52 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_7_dept_85

14:54:52 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_jmnkzkw.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_quwqwrv.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=91412', 'data', 'file=/tmp/tmpjd45me00/_jmnkzkw.json', 'init=/tmp/tmpjd45me00/_quwqwrv.json', 'output', 'file=/tmp/tmpjd45me00/prophet_models0vwl35b/prophet_model-20260803145452.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:52 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:52 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_7_dept_87

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/o7y9geku.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_ebcaoid.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=24439', 'data', 'file=/tmp/tmpjd45me00/o7y9geku.json', 'init=/tmp/tmpjd45me00/_ebcaoid.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelhhet6gw_/prophet_model-20260803145452.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:52 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:52 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/s9on2zyc.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4dabcwju.json
DEBUG:cmdstanpy:idx 0

Build prophet model for  store_7_dept_9
Build prophet model for  store_7_dept_90

DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=20961', 'data', 'file=/tmp/tmpjd45me00/s9on2zyc.json', 'init=/tmp/tmpjd45me00/4dabcwju.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model4x861i0u/prophet_model-20260803145453.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:53 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:53 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ny1yjlgh.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ycx7libq.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=76003', 'data', 'file=/tmp/tmpjd45me00/ny1yjlgh.json', 'init=/tmp/tmpjd45me00/ycx7libq.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelsa8vzcbr/prophet_model-20260803145453.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:53 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:53 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_7_dept_91

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/35bm1mon.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/izbu7zsw.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=97733', 'data', 'file=/tmp/tmpjd45me00/35bm1mon.json', 'init=/tmp/tmpjd45me00/izbu7zsw.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model48zflmo0/prophet_model-20260803145453.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:53 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:53 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fu4xtq9r.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/z88qt228.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None

Build prophet model for  store_7_dept_92
Build prophet model for  store_7_dept_93

DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=40516', 'data', 'file=/tmp/tmpjd45me00/fu4xtq9r.json', 'init=/tmp/tmpjd45me00/z88qt228.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelsg4qui_6/prophet_model-20260803145453.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:53 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:53 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/j37rgz9f.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/38obx49c.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=90912', 'data', 'file=/tmp/tmpjd45me00/j37rgz9f.json', 'init=/tmp/tmpjd45me00/38obx49c.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeln57zn1tl/prophet_model-20260803145454.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:54:54 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_7_dept_94

14:54:55 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/tjaj88c7.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hxlord6h.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=27698', 'data', 'file=/tmp/tmpjd45me00/tjaj88c7.json', 'init=/tmp/tmpjd45me00/hxlord6h.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model6nd6glqs/prophet_model-20260803145455.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:55 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:55 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_7_dept_95

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/aw833ki1.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/b3z_0qqd.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=63200', 'data', 'file=/tmp/tmpjd45me00/aw833ki1.json', 'init=/tmp/tmpjd45me00/b3z_0qqd.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelhdgx801y/prophet_model-20260803145455.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:55 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:55 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_7_dept_96

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/q_6faa59.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/b0ad0aw5.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=27878', 'data', 'file=/tmp/tmpjd45me00/q_6faa59.json', 'init=/tmp/tmpjd45me00/b0ad0aw5.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelukojw2bb/prophet_model-20260803145456.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:56 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:56 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_7_dept_97
Build prophet model for  store_7_dept_98

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0jl159lv.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/io8tjmbw.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=77994', 'data', 'file=/tmp/tmpjd45me00/0jl159lv.json', 'init=/tmp/tmpjd45me00/io8tjmbw.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelznocak3m/prophet_model-20260803145456.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:56 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:56 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/tj_xn_qo.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7vqc6e4t.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=81162', 'data', 'file=/tmp/tmpjd45me00/tj_xn_qo.json', 'init=/tmp/tmpjd45me00/7vqc6e4t.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modele8n7i9pi/prophet_model-20260803145456.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:56 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:56 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pjh2hyt2.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xwe9i8ht.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=53723', 'data', 'file=/tmp/tmpjd45me00/pjh2hyt2.json', 'init=/tmp/tmpjd45me00/xwe9i8ht.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model3zhofr8a/prophet_model-20260803145456.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:56 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_8_dept_1
Build prophet model for  store_8_dept_10

14:54:56 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/m13tmnuw.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/li2bfx1v.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=56234', 'data', 'file=/tmp/tmpjd45me00/m13tmnuw.json', 'init=/tmp/tmpjd45me00/li2bfx1v.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelduk4l_am/prophet_model-20260803145456.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:56 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:56 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/i7e7myv3.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6e6vvocv.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=77576', 'data', 'file=/tmp/tmpjd45me00/i7e7myv3.json', 'init=/tmp/tmpjd45me00/6e6vvocv.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelzdzah1ue/prophet_model-20260803145456.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:56 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_8_dept_11
Build prophet model for  store_8_dept_12

14:54:56 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/y1xyedwh.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ckicof5u.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=92229', 'data', 'file=/tmp/tmpjd45me00/y1xyedwh.json', 'init=/tmp/tmpjd45me00/ckicof5u.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modellltqdppc/prophet_model-20260803145457.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:57 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:57 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/emldxhhq.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/oc6tqvkw.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=42078', 'data', 'file=/tmp/tmpjd45me00/emldxhhq.json', 'init=/tmp/tmpjd45me00/oc6tqvkw.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelqvt_tnut/prophet_model-20260803145457.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:57 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_8_dept_13
Build prophet model for  store_8_dept_14

14:54:57 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/32h8m48z.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xneyku3r.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=30709', 'data', 'file=/tmp/tmpjd45me00/32h8m48z.json', 'init=/tmp/tmpjd45me00/xneyku3r.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelsq6xkl1o/prophet_model-20260803145457.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:57 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_8_dept_16

14:54:57 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gi0z2hxb.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pou4s16c.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=20698', 'data', 'file=/tmp/tmpjd45me00/gi0z2hxb.json', 'init=/tmp/tmpjd45me00/pou4s16c.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model5c1yd5jj/prophet_model-20260803145457.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:57 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:57 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ptrax0ld.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/di7jowen.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=17995', 'data', 'file=/tmp/tmpjd45me00/ptrax0ld.json', 'init=/tmp/tmpjd45me00/di7jowen.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeltpta_1b8/prophet_model-20260803145457.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:54:57 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_8_dept_17
Build prophet model for  store_8_dept_18

14:54:59 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ad40y_ix.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/akvb8nce.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=76542', 'data', 'file=/tmp/tmpjd45me00/ad40y_ix.json', 'init=/tmp/tmpjd45me00/akvb8nce.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelh81pbb0z/prophet_model-20260803145459.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:59 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_8_dept_19

14:54:59 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/72djs8jg.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mi1gouig.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=68799', 'data', 'file=/tmp/tmpjd45me00/72djs8jg.json', 'init=/tmp/tmpjd45me00/mi1gouig.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelksesar1g/prophet_model-20260803145459.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:59 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:59 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wtbpnjb3.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/d7nmnz2c.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=3769', 'data', 'file=/tmp/tmpjd45me00/wtbpnjb3.json', 'init=/tmp/tmpjd45me00/d7nmnz2c.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelm_b6weh8/prophet_model-20260803145459.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:59 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_8_dept_2
Build prophet model for  store_8_dept_20

14:54:59 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0gle0564.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4mnifuya.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=79535', 'data', 'file=/tmp/tmpjd45me00/0gle0564.json', 'init=/tmp/tmpjd45me00/4mnifuya.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelogk58q7u/prophet_model-20260803145459.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:54:59 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:54:59 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_8_dept_21
Build prophet model for  store_8_dept_22

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dddm5__m.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3qk47l96.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=71940', 'data', 'file=/tmp/tmpjd45me00/dddm5__m.json', 'init=/tmp/tmpjd45me00/3qk47l96.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelrvgpnnpo/prophet_model-20260803145500.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:00 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:00 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/q4a58y4s.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wzzwb31j.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=3111', 'data', 'file=/tmp/tmpjd45me00/q4a58y4s.json', 'init=/tmp/tmpjd45me00/wzzwb31j.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelbryqz39p/prophet_model-20260803145500.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:00 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:00 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_8_dept_23
Build prophet model for  store_8_dept_24

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/168z73se.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/z7p_c0te.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=78512', 'data', 'file=/tmp/tmpjd45me00/168z73se.json', 'init=/tmp/tmpjd45me00/z7p_c0te.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelphxa95hk/prophet_model-20260803145500.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:00 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:00 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/iu6dkdrc.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gtb6tw_f.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=80866', 'data', 'file=/tmp/tmpjd45me00/iu6dkdrc.json', 'init=/tmp/tmpjd45me00/gtb6tw_f.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model0hfr0y1t/prophet_model-20260803145500.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:00 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:00 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_8_dept_25
Build prophet model for  store_8_dept_26

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6a7d2nzn.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3digj7z0.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=91939', 'data', 'file=/tmp/tmpjd45me00/6a7d2nzn.json', 'init=/tmp/tmpjd45me00/3digj7z0.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelsiatrbeo/prophet_model-20260803145501.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:01 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:01 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/m9s5v1bt.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bbce9a30.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=49127', 'data', 'file=/tmp/tmpjd45me00/m9s5v1bt.json', 'init=/tmp/tmpjd45me00/bbce9a30.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model6yc8bmdd/prophet_model-20260803145501.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:01 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:01 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_8_dept_27

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4wcgk58v.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/aeqh90m8.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=35559', 'data', 'file=/tmp/tmpjd45me00/4wcgk58v.json', 'init=/tmp/tmpjd45me00/aeqh90m8.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model30ceywu7/prophet_model-20260803145501.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:01 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_8_dept_28

14:55:01 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9968u9dj.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pajx6xhx.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=21516', 'data', 'file=/tmp/tmpjd45me00/9968u9dj.json', 'init=/tmp/tmpjd45me00/pajx6xhx.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelurp0kmcn/prophet_model-20260803145501.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:01 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_8_dept_29

14:55:02 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8iyfeyv9.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fz87hdgt.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=78259', 'data', 'file=/tmp/tmpjd45me00/8iyfeyv9.json', 'init=/tmp/tmpjd45me00/fz87hdgt.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelasa9msbb/prophet_model-20260803145502.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:02 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:02 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_8_dept_3

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9qyvl477.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zagbi126.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=66418', 'data', 'file=/tmp/tmpjd45me00/9qyvl477.json', 'init=/tmp/tmpjd45me00/zagbi126.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model1hhsg_xk/prophet_model-20260803145502.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:02 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_8_dept_30

14:55:02 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9duzfiyb.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/yp_blgzb.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=58443', 'data', 'file=/tmp/tmpjd45me00/9duzfiyb.json', 'init=/tmp/tmpjd45me00/yp_blgzb.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelxtrjvd6m/prophet_model-20260803145502.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:02 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:02 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_8_dept_31

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6mdugiwv.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1r9scy4j.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=71828', 'data', 'file=/tmp/tmpjd45me00/6mdugiwv.json', 'init=/tmp/tmpjd45me00/1r9scy4j.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modellilua2wq/prophet_model-20260803145503.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:03 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:03 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_8_dept_32
Build prophet model for  store_8_dept_33

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/46pme22f.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3fwgfmff.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=91492', 'data', 'file=/tmp/tmpjd45me00/46pme22f.json', 'init=/tmp/tmpjd45me00/3fwgfmff.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeljwt9ho0y/prophet_model-20260803145503.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:03 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:03 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hi3kitf2.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/kioy6nw0.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=69722', 'data', 'file=/tmp/tmpjd45me00/hi3kitf2.json', 'init=/tmp/tmpjd45me00/kioy6nw0.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model6itzxiyy/prophet_model-20260803145503.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:03 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:03 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_8_dept_34
Build prophet model for  store_8_dept_35

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/be6df9ie.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/z3tmvbbp.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=40991', 'data', 'file=/tmp/tmpjd45me00/be6df9ie.json', 'init=/tmp/tmpjd45me00/z3tmvbbp.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelnkz5b_qm/prophet_model-20260803145503.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:03 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:03 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/29mwsiey.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/d8dga1ah.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=73439', 'data', 'file=/tmp/tmpjd45me00/29mwsiey.json', 'init=/tmp/tmpjd45me00/d8dga1ah.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelukwbd22d/prophet_model-20260803145503.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:03 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:03 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/25v2ujjq.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ftq9fmud.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=36183', 'data', 'file=/tmp/tmpjd45me00/25v2ujjq.json', 'init=/tmp/tmpjd45me00/ftq9fmud.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelngxdmk9r/prophet_model-20260803145503.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:03 - cmdstanpy - INFO - Chain [1] start processing

Build prophet model for  store_8_dept_36
Build prophet model for  store_8_dept_37

INFO:cmdstanpy:Chain [1] start processing
14:55:03 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zr6d25ir.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8t9x9fzz.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=12491', 'data', 'file=/tmp/tmpjd45me00/zr6d25ir.json', 'init=/tmp/tmpjd45me00/8t9x9fzz.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model6lolaav3/prophet_model-20260803145504.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:04 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:04 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pgr5hznt.json

Build prophet model for  store_8_dept_38
Build prophet model for  store_8_dept_4

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pspvs71u.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=45487', 'data', 'file=/tmp/tmpjd45me00/pgr5hznt.json', 'init=/tmp/tmpjd45me00/pspvs71u.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model166v6erf/prophet_model-20260803145504.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:04 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:04 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/x11h3mtk.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pbbdftd6.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=65952', 'data', 'file=/tmp/tmpjd45me00/x11h3mtk.json', 'init=/tmp/tmpjd45me00/pbbdftd6.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model364oojhn/prophet_model-20260803145504.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:04 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:04 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_8_dept_40

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2jszcriu.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ckn1yt3k.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=1577', 'data', 'file=/tmp/tmpjd45me00/2jszcriu.json', 'init=/tmp/tmpjd45me00/ckn1yt3k.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model00xb0mct/prophet_model-20260803145504.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:04 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:04 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/e5wjvxdj.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4vlgv_p1.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=22537', 'data', 'file=/tmp/tmpjd45me00/e5wjvxdj.json', 'init=/tmp/tmpjd45me00/4vlgv_p1.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model1vtgp5oh/prophet_model-20260803145504.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:04 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_8_dept_41
Build prophet model for  store_8_dept_42

14:55:04 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/i5x2p5x3.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5pku9no7.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=58140', 'data', 'file=/tmp/tmpjd45me00/i5x2p5x3.json', 'init=/tmp/tmpjd45me00/5pku9no7.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model9yuvr7fx/prophet_model-20260803145504.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:04 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:04 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8q16woug.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6e_pyn9_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=41570', 'data', 'file=/tmp/tmpjd45me00/8q16woug.json', 'init=/tmp/tmpjd45me00/6e_pyn9_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeloghhjaym/prophet_model-20260803145505.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:05 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_8_dept_44
Build prophet model for  store_8_dept_46

14:55:05 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/iukze086.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5pt8giwo.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=89945', 'data', 'file=/tmp/tmpjd45me00/iukze086.json', 'init=/tmp/tmpjd45me00/5pt8giwo.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modells84my15/prophet_model-20260803145505.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:05 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:05 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gpmwg9tn.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hi0jgp6n.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=37775', 'data', 'file=/tmp/tmpjd45me00/gpmwg9tn.json', 'init=/tmp/tmpjd45me00/hi0jgp6n.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelj8phunxl/prophet_model-20260803145505.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:05 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_8_dept_49
Build prophet model for  store_8_dept_5

14:55:05 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/b_qm8a1n.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vpfa6wv_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=66050', 'data', 'file=/tmp/tmpjd45me00/b_qm8a1n.json', 'init=/tmp/tmpjd45me00/vpfa6wv_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelg1pk2tq4/prophet_model-20260803145505.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:05 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:05 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_8_dept_52

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/iq6_9ahz.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/lilgxtse.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=64207', 'data', 'file=/tmp/tmpjd45me00/iq6_9ahz.json', 'init=/tmp/tmpjd45me00/lilgxtse.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelvu7gw5n8/prophet_model-20260803145505.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:05 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:05 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/sa8n2rlu.json

Build prophet model for  store_8_dept_54
Build prophet model for  store_8_dept_55

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/n2gi537y.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=76952', 'data', 'file=/tmp/tmpjd45me00/sa8n2rlu.json', 'init=/tmp/tmpjd45me00/n2gi537y.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modellr85myad/prophet_model-20260803145505.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:05 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:05 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fqekc13f.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wenjbcon.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=71552', 'data', 'file=/tmp/tmpjd45me00/fqekc13f.json', 'init=/tmp/tmpjd45me00/wenjbcon.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelzw1y5p84/prophet_model-20260803145506.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:06 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:06 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_8_dept_56

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/we3bfriy.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0jmxhtdm.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=12047', 'data', 'file=/tmp/tmpjd45me00/we3bfriy.json', 'init=/tmp/tmpjd45me00/0jmxhtdm.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelxsl1alhk/prophet_model-20260803145506.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:06 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:06 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zneaubfn.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4ygdywny.json
DEBUG:cmdstanpy:idx 0

Build prophet model for  store_8_dept_58
Build prophet model for  store_8_dept_59

DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=83548', 'data', 'file=/tmp/tmpjd45me00/zneaubfn.json', 'init=/tmp/tmpjd45me00/4ygdywny.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelayj2h6ap/prophet_model-20260803145506.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:06 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:06 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ltzge71s.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6xgsr6cz.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=15387', 'data', 'file=/tmp/tmpjd45me00/ltzge71s.json', 'init=/tmp/tmpjd45me00/6xgsr6cz.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelqc0hw592/prophet_model-20260803145506.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:06 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:06 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5dyb0kid.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bz1fsarg.json

Build prophet model for  store_8_dept_6
Build prophet model for  store_8_dept_60

DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=6435', 'data', 'file=/tmp/tmpjd45me00/5dyb0kid.json', 'init=/tmp/tmpjd45me00/bz1fsarg.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelychklhku/prophet_model-20260803145507.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:07 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:07 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gi8o90hi.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2vvcnpk2.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=85522', 'data', 'file=/tmp/tmpjd45me00/gi8o90hi.json', 'init=/tmp/tmpjd45me00/2vvcnpk2.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model8kzu644f/prophet_model-20260803145507.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:07 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:07 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6_k0_7hr.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/lm7b1a_a.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=38732', 'data', 'file=/tmp/tmpjd45me00/6_k0_7hr.json', 'init=/tmp/tmpjd45me00/lm7b1a_a.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeld7ex2db9/prophet_model-20260803145507.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:07 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_8_dept_67
Build prophet model for  store_8_dept_7

14:55:07 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/m376305q.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3_8ukgtn.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=35634', 'data', 'file=/tmp/tmpjd45me00/m376305q.json', 'init=/tmp/tmpjd45me00/3_8ukgtn.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model1eziv12a/prophet_model-20260803145507.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:07 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:07 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/p8a8qpun.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/j0nwd_x2.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=60532', 'data', 'file=/tmp/tmpjd45me00/p8a8qpun.json', 'init=/tmp/tmpjd45me00/j0nwd_x2.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelxs1stk6h/prophet_model-20260803145507.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:07 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:07 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_8_dept_71
Build prophet model for  store_8_dept_72

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/o0ldr9cd.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5pjv11dd.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=36109', 'data', 'file=/tmp/tmpjd45me00/o0ldr9cd.json', 'init=/tmp/tmpjd45me00/5pjv11dd.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeli7xxhvzd/prophet_model-20260803145507.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:07 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:07 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_8_dept_74
Build prophet model for  store_8_dept_79

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/x38l_j_z.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gwa9tju6.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=74551', 'data', 'file=/tmp/tmpjd45me00/x38l_j_z.json', 'init=/tmp/tmpjd45me00/gwa9tju6.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelk9q_te7v/prophet_model-20260803145508.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:08 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:08 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dk45mbea.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/t3cxprio.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=92794', 'data', 'file=/tmp/tmpjd45me00/dk45mbea.json', 'init=/tmp/tmpjd45me00/t3cxprio.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeltlnbxqty/prophet_model-20260803145508.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:08 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:08 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/v9o3gt47.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qcvn66fd.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=4577', 'data', 'file=/tmp/tmpjd45me00/v9o3gt47.json', 'init=/tmp/tmpjd45me00/qcvn66fd.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelwgi82io5/prophet_model-20260803145508.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:08 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_8_dept_8
Build prophet model for  store_8_dept_80

14:55:08 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/n0akoyey.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zprlt0ar.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=5956', 'data', 'file=/tmp/tmpjd45me00/n0akoyey.json', 'init=/tmp/tmpjd45me00/zprlt0ar.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelyz485hn5/prophet_model-20260803145508.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:08 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:08 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9_0nivra.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zh47o7m0.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=93655', 'data', 'file=/tmp/tmpjd45me00/9_0nivra.json', 'init=/tmp/tmpjd45me00/zh47o7m0.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelxjob2gk7/prophet_model-20260803145508.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:08 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_8_dept_81
Build prophet model for  store_8_dept_82

14:55:08 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7unncvrd.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7297rpcf.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=11681', 'data', 'file=/tmp/tmpjd45me00/7unncvrd.json', 'init=/tmp/tmpjd45me00/7297rpcf.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelqz1ui55t/prophet_model-20260803145508.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:08 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:08 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_8_dept_83
Build prophet model for  store_8_dept_85

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7rgchwzr.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pj6sns7z.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=86274', 'data', 'file=/tmp/tmpjd45me00/7rgchwzr.json', 'init=/tmp/tmpjd45me00/pj6sns7z.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model67x_1k7d/prophet_model-20260803145509.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:09 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:09 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/sfx96vtf.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/nzoyrdmx.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=42015', 'data', 'file=/tmp/tmpjd45me00/sfx96vtf.json', 'init=/tmp/tmpjd45me00/nzoyrdmx.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelc_cu7gdo/prophet_model-20260803145509.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:09 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:09 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7imvhvkf.json

Build prophet model for  store_8_dept_87
Build prophet model for  store_8_dept_9

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/y27a2w5c.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=42652', 'data', 'file=/tmp/tmpjd45me00/7imvhvkf.json', 'init=/tmp/tmpjd45me00/y27a2w5c.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelpibbzzro/prophet_model-20260803145509.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:09 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:09 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2nitpwhf.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/71w1gyxe.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=422', 'data', 'file=/tmp/tmpjd45me00/2nitpwhf.json', 'init=/tmp/tmpjd45me00/71w1gyxe.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model3bkwh1up/prophet_model-20260803145509.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:09 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:09 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fu4y7fu8.json

Build prophet model for  store_8_dept_90
Build prophet model for  store_8_dept_91

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/n56ewab5.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=57619', 'data', 'file=/tmp/tmpjd45me00/fu4y7fu8.json', 'init=/tmp/tmpjd45me00/n56ewab5.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelxutfl0el/prophet_model-20260803145509.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:09 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:09 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/71ojiamd.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8odckka5.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=6220', 'data', 'file=/tmp/tmpjd45me00/71ojiamd.json', 'init=/tmp/tmpjd45me00/8odckka5.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_p4096kq/prophet_model-20260803145509.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:09 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:09 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_8_dept_92
Build prophet model for  store_8_dept_93

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2f0yqal8.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vh5y8v74.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=19865', 'data', 'file=/tmp/tmpjd45me00/2f0yqal8.json', 'init=/tmp/tmpjd45me00/vh5y8v74.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelhfy8w9jd/prophet_model-20260803145510.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:10 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:10 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gbko8r7u.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bc8dbtpa.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=89819', 'data', 'file=/tmp/tmpjd45me00/gbko8r7u.json', 'init=/tmp/tmpjd45me00/bc8dbtpa.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modellbih6uby/prophet_model-20260803145510.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:10 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:10 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_8_dept_94
Build prophet model for  store_8_dept_95

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/cr__v251.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/tobtl5it.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=36789', 'data', 'file=/tmp/tmpjd45me00/cr__v251.json', 'init=/tmp/tmpjd45me00/tobtl5it.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model6g7aluzf/prophet_model-20260803145510.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:10 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:10 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3_x9q18u.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/f8srsh43.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=28371', 'data', 'file=/tmp/tmpjd45me00/3_x9q18u.json', 'init=/tmp/tmpjd45me00/f8srsh43.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modele4i54_x1/prophet_model-20260803145510.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:10 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:10 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/q424g8b4.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vxdzho4e.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=89833', 'data', 'file=/tmp/tmpjd45me00/q424g8b4.json', 'init=/tmp/tmpjd45me00/vxdzho4e.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model4zvucnoa/prophet_model-20260803145510.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:10 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_8_dept_97
Build prophet model for  store_8_dept_98

14:55:10 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5knnh2c2.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/85fixtbg.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=73724', 'data', 'file=/tmp/tmpjd45me00/5knnh2c2.json', 'init=/tmp/tmpjd45me00/85fixtbg.json', 'output', 'file=/tmp/tmpjd45me00/prophet_models2jednm9/prophet_model-20260803145510.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:10 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:10 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hnvuaicp.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/x75g14g0.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=17', 'data', 'file=/tmp/tmpjd45me00/hnvuaicp.json', 'init=/tmp/tmpjd45me00/x75g14g0.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model7la38zs1/prophet_model-20260803145511.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:11 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_9_dept_1
Build prophet model for  store_9_dept_10

14:55:11 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/m5x8zj59.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vwmvgq8p.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=44740', 'data', 'file=/tmp/tmpjd45me00/m5x8zj59.json', 'init=/tmp/tmpjd45me00/vwmvgq8p.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelgugket9y/prophet_model-20260803145511.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:11 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:11 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_9_dept_11
Build prophet model for  store_9_dept_12

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ss5cj0zu.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/elryk2_a.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=82174', 'data', 'file=/tmp/tmpjd45me00/ss5cj0zu.json', 'init=/tmp/tmpjd45me00/elryk2_a.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelvs9xixn_/prophet_model-20260803145511.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:11 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:11 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1s6vbw5d.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ad3mze7e.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=58530', 'data', 'file=/tmp/tmpjd45me00/1s6vbw5d.json', 'init=/tmp/tmpjd45me00/ad3mze7e.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelnkxjazi9/prophet_model-20260803145511.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:11 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:11 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7uoe_s02.json

Build prophet model for  store_9_dept_13
Build prophet model for  store_9_dept_14

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9k32ngjk.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=36407', 'data', 'file=/tmp/tmpjd45me00/7uoe_s02.json', 'init=/tmp/tmpjd45me00/9k32ngjk.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelj6rojmdx/prophet_model-20260803145511.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:11 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:11 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jm2y_1se.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/59vj3l_7.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=49080', 'data', 'file=/tmp/tmpjd45me00/jm2y_1se.json', 'init=/tmp/tmpjd45me00/59vj3l_7.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model8vszubqn/prophet_model-20260803145511.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:11 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:12 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_9_dept_16

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/h2bytlf1.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gqjkknro.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=51483', 'data', 'file=/tmp/tmpjd45me00/h2bytlf1.json', 'init=/tmp/tmpjd45me00/gqjkknro.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model5bxktk0w/prophet_model-20260803145512.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:12 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:12 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_9_dept_17
Build prophet model for  store_9_dept_18

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_m29s5h5.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1meylqh7.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=98422', 'data', 'file=/tmp/tmpjd45me00/_m29s5h5.json', 'init=/tmp/tmpjd45me00/1meylqh7.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model9tly3_a_/prophet_model-20260803145512.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:55:12 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:14 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bt2_kk9_.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pyg1pbgr.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=41914', 'data', 'file=/tmp/tmpjd45me00/bt2_kk9_.json', 'init=/tmp/tmpjd45me00/pyg1pbgr.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model05m0ql1i/prophet_model-20260803145514.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:14 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_9_dept_19

14:55:14 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ed7831cp.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2h0xs2za.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=20666', 'data', 'file=/tmp/tmpjd45me00/ed7831cp.json', 'init=/tmp/tmpjd45me00/2h0xs2za.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeluozsif3z/prophet_model-20260803145514.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:14 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:14 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_9_dept_2

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wfh7_q7h.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/olsscsrr.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=9213', 'data', 'file=/tmp/tmpjd45me00/wfh7_q7h.json', 'init=/tmp/tmpjd45me00/olsscsrr.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelp7ioqyt6/prophet_model-20260803145514.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:14 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:15 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_9_dept_20

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/75xhq8eg.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_66qaoq_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=44929', 'data', 'file=/tmp/tmpjd45me00/75xhq8eg.json', 'init=/tmp/tmpjd45me00/_66qaoq_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model26ey8n2s/prophet_model-20260803145515.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:15 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_9_dept_21

14:55:15 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/kg88s7wx.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rh16il3s.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=72743', 'data', 'file=/tmp/tmpjd45me00/kg88s7wx.json', 'init=/tmp/tmpjd45me00/rh16il3s.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelpl23iv3t/prophet_model-20260803145515.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:15 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:15 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_9_dept_22
Build prophet model for  store_9_dept_23

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/r009vxp3.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qkfdz6eu.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=40416', 'data', 'file=/tmp/tmpjd45me00/r009vxp3.json', 'init=/tmp/tmpjd45me00/qkfdz6eu.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_6b9a4p5/prophet_model-20260803145516.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:16 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:16 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rk7wmjxn.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/i9qel9_5.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=68952', 'data', 'file=/tmp/tmpjd45me00/rk7wmjxn.json', 'init=/tmp/tmpjd45me00/i9qel9_5.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelvmcd4pvo/prophet_model-20260803145516.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:16 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:16 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/u_clvx82.json

Build prophet model for  store_9_dept_24
Build prophet model for  store_9_dept_25

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/cpcmk53u.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=55056', 'data', 'file=/tmp/tmpjd45me00/u_clvx82.json', 'init=/tmp/tmpjd45me00/cpcmk53u.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model0j8rfdo5/prophet_model-20260803145516.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:16 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:16 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mzxttd7r.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/c41x1_bq.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=38766', 'data', 'file=/tmp/tmpjd45me00/mzxttd7r.json', 'init=/tmp/tmpjd45me00/c41x1_bq.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelquh0jvlo/prophet_model-20260803145516.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:16 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_9_dept_26

14:55:16 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rrtdvmue.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/lqe6att1.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=70681', 'data', 'file=/tmp/tmpjd45me00/rrtdvmue.json', 'init=/tmp/tmpjd45me00/lqe6att1.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model7jfjczu1/prophet_model-20260803145516.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:16 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:17 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_9_dept_27

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/q5l_r6m1.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dte80nau.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=21024', 'data', 'file=/tmp/tmpjd45me00/q5l_r6m1.json', 'init=/tmp/tmpjd45me00/dte80nau.json', 'output', 'file=/tmp/tmpjd45me00/prophet_models4bfrny2/prophet_model-20260803145517.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:17 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:17 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_9_dept_28
Build prophet model for  store_9_dept_29

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/lie4ufpo.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/69nxg73s.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=40206', 'data', 'file=/tmp/tmpjd45me00/lie4ufpo.json', 'init=/tmp/tmpjd45me00/69nxg73s.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelljwh_caf/prophet_model-20260803145517.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:17 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:17 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/nnfcf5wj.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/p9jd2qej.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=640', 'data', 'file=/tmp/tmpjd45me00/nnfcf5wj.json', 'init=/tmp/tmpjd45me00/p9jd2qej.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model8ww_x1iy/prophet_model-20260803145517.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:17 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:17 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_9_dept_3
Build prophet model for  store_9_dept_30

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/za06swa1.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jpp5qukh.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=87824', 'data', 'file=/tmp/tmpjd45me00/za06swa1.json', 'init=/tmp/tmpjd45me00/jpp5qukh.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modellytmtke_/prophet_model-20260803145517.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:17 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:17 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/eszrfkps.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9_v_bbrs.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=24827', 'data', 'file=/tmp/tmpjd45me00/eszrfkps.json', 'init=/tmp/tmpjd45me00/9_v_bbrs.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelo7t1l1_o/prophet_model-20260803145518.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:18 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:18 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_9_dept_31

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/x5k8j8m1.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/29_i4kku.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=20306', 'data', 'file=/tmp/tmpjd45me00/x5k8j8m1.json', 'init=/tmp/tmpjd45me00/29_i4kku.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelrpe2jkc6/prophet_model-20260803145518.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:18 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:18 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zj85y3xy.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6rsjd_h_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=75459', 'data', 'file=/tmp/tmpjd45me00/zj85y3xy.json', 'init=/tmp/tmpjd45me00/6rsjd_h_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelt8cv8qpa/prophet_model-20260803145518.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:18 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_9_dept_32
Build prophet model for  store_9_dept_33

14:55:18 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3owpg4du.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xqwvpw8k.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=80463', 'data', 'file=/tmp/tmpjd45me00/3owpg4du.json', 'init=/tmp/tmpjd45me00/xqwvpw8k.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model5xzsfhqg/prophet_model-20260803145518.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:18 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:18 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/kjrn3qho.json

Build prophet model for  store_9_dept_34
Build prophet model for  store_9_dept_35

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/q1ikx8i3.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=72738', 'data', 'file=/tmp/tmpjd45me00/kjrn3qho.json', 'init=/tmp/tmpjd45me00/q1ikx8i3.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model9y7u10_p/prophet_model-20260803145518.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:18 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:18 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8tcmo8s_.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/h73xydmp.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=97183', 'data', 'file=/tmp/tmpjd45me00/8tcmo8s_.json', 'init=/tmp/tmpjd45me00/h73xydmp.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelyzjx20c1/prophet_model-20260803145519.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:19 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:19 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3kylh0p7.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/s2nas65m.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=57743', 'data', 'file=/tmp/tmpjd45me00/3kylh0p7.json', 'init=/tmp/tmpjd45me00/s2nas65m.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelq6ksms9j/prophet_model-20260803145519.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:19 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_9_dept_36
Build prophet model for  store_9_dept_38

14:55:19 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/lj2a4oka.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7fbbf96d.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=24920', 'data', 'file=/tmp/tmpjd45me00/lj2a4oka.json', 'init=/tmp/tmpjd45me00/7fbbf96d.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelxv5swdcr/prophet_model-20260803145519.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:19 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_9_dept_4

14:55:19 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jzybyd_5.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ffdtsk3b.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=84974', 'data', 'file=/tmp/tmpjd45me00/jzybyd_5.json', 'init=/tmp/tmpjd45me00/ffdtsk3b.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model8fnu3d5j/prophet_model-20260803145519.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:19 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:19 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_9_dept_40
Build prophet model for  store_9_dept_41

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4e_1pu9f.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/58_1e7wg.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=42522', 'data', 'file=/tmp/tmpjd45me00/4e_1pu9f.json', 'init=/tmp/tmpjd45me00/58_1e7wg.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeljn0fx2rt/prophet_model-20260803145519.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:19 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:20 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qrixzc41.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_l_091if.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=11836', 'data', 'file=/tmp/tmpjd45me00/qrixzc41.json', 'init=/tmp/tmpjd45me00/_l_091if.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelbfyqqnj9/prophet_model-20260803145520.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:20 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:20 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/893_l2ce.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/byy21wyk.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=28925', 'data', 'file=/tmp/tmpjd45me00/893_l2ce.json', 'init=/tmp/tmpjd45me00/byy21wyk.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model1kxfepdf/prophet_model-20260803145520.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:20 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_9_dept_42
Build prophet model for  store_9_dept_44

14:55:20 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/k_hkli8c.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5m362sfs.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=99541', 'data', 'file=/tmp/tmpjd45me00/k_hkli8c.json', 'init=/tmp/tmpjd45me00/5m362sfs.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model7bairuaw/prophet_model-20260803145520.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:20 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:20 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7963zk37.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7g5kio9_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=72270', 'data', 'file=/tmp/tmpjd45me00/7963zk37.json', 'init=/tmp/tmpjd45me00/7g5kio9_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modela78z8q7c/prophet_model-20260803145520.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:20 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_9_dept_46
Build prophet model for  store_9_dept_5

14:55:20 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/sk1cq5dh.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/swssvo5v.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=28636', 'data', 'file=/tmp/tmpjd45me00/sk1cq5dh.json', 'init=/tmp/tmpjd45me00/swssvo5v.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeldi1ohc4t/prophet_model-20260803145521.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:21 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:21 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_9_dept_52
Build prophet model for  store_9_dept_54

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4v9_6oys.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/df5_5k7d.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=18165', 'data', 'file=/tmp/tmpjd45me00/4v9_6oys.json', 'init=/tmp/tmpjd45me00/df5_5k7d.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeltwnu47j4/prophet_model-20260803145521.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:55:21 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:22 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7ym6w85g.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_lyob6d4.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=72877', 'data', 'file=/tmp/tmpjd45me00/7ym6w85g.json', 'init=/tmp/tmpjd45me00/_lyob6d4.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelfribrkik/prophet_model-20260803145522.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:22 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:22 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xk79gbzx.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/62vqkki3.json

Build prophet model for  store_9_dept_55
Build prophet model for  store_9_dept_56

DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=8136', 'data', 'file=/tmp/tmpjd45me00/xk79gbzx.json', 'init=/tmp/tmpjd45me00/62vqkki3.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelxvnlect5/prophet_model-20260803145523.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:23 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:23 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/j9ry78v9.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vgxtbp9i.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=31351', 'data', 'file=/tmp/tmpjd45me00/j9ry78v9.json', 'init=/tmp/tmpjd45me00/vgxtbp9i.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model7pczfq_a/prophet_model-20260803145523.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:23 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:23 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/01qzz1t9.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_ezlfi7h.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=74698', 'data', 'file=/tmp/tmpjd45me00/01qzz1t9.json', 'init=/tmp/tmpjd45me00/_ezlfi7h.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model27n6gslb/prophet_model-20260803145523.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:23 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:23 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_9_dept_59
Build prophet model for  store_9_dept_6

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/srkg4s8s.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0owhmur2.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=27727', 'data', 'file=/tmp/tmpjd45me00/srkg4s8s.json', 'init=/tmp/tmpjd45me00/0owhmur2.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelcs1bksjn/prophet_model-20260803145523.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:23 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:23 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/djuv8whx.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/x8pyqbda.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=95236', 'data', 'file=/tmp/tmpjd45me00/djuv8whx.json', 'init=/tmp/tmpjd45me00/x8pyqbda.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model4v2t_z8i/prophet_model-20260803145523.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:23 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:23 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_9_dept_67
Build prophet model for  store_9_dept_7

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9jnr6y_v.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/m9c2etqi.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=38959', 'data', 'file=/tmp/tmpjd45me00/9jnr6y_v.json', 'init=/tmp/tmpjd45me00/m9c2etqi.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model0pzceer5/prophet_model-20260803145523.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:23 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:23 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4tt9i1ss.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/by25ztlb.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=47615', 'data', 'file=/tmp/tmpjd45me00/4tt9i1ss.json', 'init=/tmp/tmpjd45me00/by25ztlb.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelluap_ovf/prophet_model-20260803145523.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:23 - cmdstanpy - INFO - Chain [1] start processing

Build prophet model for  store_9_dept_71
Build prophet model for  store_9_dept_72

INFO:cmdstanpy:Chain [1] start processing
14:55:23 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2u6f1gj2.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hwgdm0nq.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=8406', 'data', 'file=/tmp/tmpjd45me00/2u6f1gj2.json', 'init=/tmp/tmpjd45me00/hwgdm0nq.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modela2n3ibi0/prophet_model-20260803145524.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:24 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:24 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5qg0hggy.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/81yqpcnb.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=78264', 'data', 'file=/tmp/tmpjd45me00/5qg0hggy.json', 'init=/tmp/tmpjd45me00/81yqpcnb.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelex5kxf5r/prophet_model-20260803145524.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:24 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_9_dept_74
Build prophet model for  store_9_dept_79

14:55:24 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qk_5yhni.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/o43a5op9.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=69610', 'data', 'file=/tmp/tmpjd45me00/qk_5yhni.json', 'init=/tmp/tmpjd45me00/o43a5op9.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeltx8i4bw5/prophet_model-20260803145524.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:24 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:24 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_9_dept_8

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zdr14rdd.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5phoy9tq.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=63936', 'data', 'file=/tmp/tmpjd45me00/zdr14rdd.json', 'init=/tmp/tmpjd45me00/5phoy9tq.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelu11d04nf/prophet_model-20260803145524.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:24 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_9_dept_81

14:55:24 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5bibdkqp.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/x47qfecc.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=25830', 'data', 'file=/tmp/tmpjd45me00/5bibdkqp.json', 'init=/tmp/tmpjd45me00/x47qfecc.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model9mu9uclt/prophet_model-20260803145525.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:25 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:25 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rbz7pyvb.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/16s4z5zv.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=46966', 'data', 'file=/tmp/tmpjd45me00/rbz7pyvb.json', 'init=/tmp/tmpjd45me00/16s4z5zv.json', 'output', 'file=/tmp/tmpjd45me00/prophet_models55qqxvd/prophet_model-20260803145525.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:25 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_9_dept_82
Build prophet model for  store_9_dept_85

14:55:25 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/w238tr_5.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jx3_4nsz.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=4950', 'data', 'file=/tmp/tmpjd45me00/w238tr_5.json', 'init=/tmp/tmpjd45me00/jx3_4nsz.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model7wfgxn5i/prophet_model-20260803145525.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:25 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:25 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0d4c67h2.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9h_hexo0.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=5978', 'data', 'file=/tmp/tmpjd45me00/0d4c67h2.json', 'init=/tmp/tmpjd45me00/9h_hexo0.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeluqqlvrc9/prophet_model-20260803145525.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:25 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_9_dept_87
Build prophet model for  store_9_dept_9

14:55:25 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/tbj71ic_.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/yiqypump.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=54730', 'data', 'file=/tmp/tmpjd45me00/tbj71ic_.json', 'init=/tmp/tmpjd45me00/yiqypump.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelew2nw7fh/prophet_model-20260803145525.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:25 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_9_dept_90

14:55:25 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/323r9zmc.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/64v_3nsc.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=25728', 'data', 'file=/tmp/tmpjd45me00/323r9zmc.json', 'init=/tmp/tmpjd45me00/64v_3nsc.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelq25xaas6/prophet_model-20260803145525.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:26 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_9_dept_91

14:55:26 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jk8d02vh.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/14w2rbim.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=41693', 'data', 'file=/tmp/tmpjd45me00/jk8d02vh.json', 'init=/tmp/tmpjd45me00/14w2rbim.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modely7t2b23a/prophet_model-20260803145526.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:26 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_9_dept_92

14:55:26 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qls5l82d.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/70czmsf6.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=6571', 'data', 'file=/tmp/tmpjd45me00/qls5l82d.json', 'init=/tmp/tmpjd45me00/70czmsf6.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelhrd9pdhn/prophet_model-20260803145526.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:26 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_9_dept_95

14:55:27 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/i0ijydew.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8jf32d8g.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=93385', 'data', 'file=/tmp/tmpjd45me00/i0ijydew.json', 'init=/tmp/tmpjd45me00/8jf32d8g.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model2w8xexbo/prophet_model-20260803145527.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:27 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_9_dept_96

14:55:27 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_9_dept_97
Skip  store_9_dept_97 due to lack of data
Build prophet model for  store_12_dept_51
Skip  store_12_dept_51 due to lack of data
Build prophet model for  store_16_dept_51
Skip  store_16_dept_51 due to lack of data
Build prophet model for  store_17_dept_45

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8h1vnl5j.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/aygw8fkc.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=44180', 'data', 'file=/tmp/tmpjd45me00/8h1vnl5j.json', 'init=/tmp/tmpjd45me00/aygw8fkc.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model781bskmy/prophet_model-20260803145527.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:55:27 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:29 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ru9eldw4.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7ai6td4f.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=13062', 'data', 'file=/tmp/tmpjd45me00/ru9eldw4.json', 'init=/tmp/tmpjd45me00/7ai6td4f.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelr0t7z1sj/prophet_model-20260803145529.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:29 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:29 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/f4ixwk_v.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/lvl8e9py.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=90901', 'data', 'file=/tmp/tmpjd45me00/f4ixwk_v.json', 'init=/tmp/tmpjd45me00/lvl8e9py.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelk_nt1rok/prophet_model-20260803145529.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:29 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_20_dept_48
Build prophet model for  store_21_dept_98

14:55:29 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qlrfocyd.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3uwfnx3y.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=59335', 'data', 'file=/tmp/tmpjd45me00/qlrfocyd.json', 'init=/tmp/tmpjd45me00/3uwfnx3y.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modellvl04hc9/prophet_model-20260803145529.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:29 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:29 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/238va3qa.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/nzqbrdn5.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=93418', 'data', 'file=/tmp/tmpjd45me00/238va3qa.json', 'init=/tmp/tmpjd45me00/nzqbrdn5.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelsgdd1u_a/prophet_model-20260803145529.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:55:29 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_22_dept_98
Build prophet model for  store_25_dept_58

14:55:30 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/o898ds8x.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zwabzfsf.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=13210', 'data', 'file=/tmp/tmpjd45me00/o898ds8x.json', 'init=/tmp/tmpjd45me00/zwabzfsf.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelx70vwymu/prophet_model-20260803145530.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:30 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:30 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_25_dept_80

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/36zktyh8.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/irw_zj8h.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=97927', 'data', 'file=/tmp/tmpjd45me00/36zktyh8.json', 'init=/tmp/tmpjd45me00/irw_zj8h.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelymflm6wf/prophet_model-20260803145530.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:30 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:30 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_26_dept_45
Skip  store_26_dept_45 due to lack of data
Build prophet model for  store_29_dept_51
Skip  store_29_dept_51 due to lack of data
Build prophet model for  store_2_dept_51
Skip  store_2_dept_51 due to lack of data
Build prophet model for  store_30_dept_31

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bknuncof.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/c2bx5ndx.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=67518', 'data', 'file=/tmp/tmpjd45me00/bknuncof.json', 'init=/tmp/tmpjd45me00/c2bx5ndx.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelho9yvpuw/prophet_model-20260803145531.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:31 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:31 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6wo4hz2i.json

Build prophet model for  store_34_dept_58
Skip  store_34_dept_58 due to lack of data
Build prophet model for  store_35_dept_98
Build prophet model for  store_36_dept_11

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/yq1yrlet.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=45625', 'data', 'file=/tmp/tmpjd45me00/6wo4hz2i.json', 'init=/tmp/tmpjd45me00/yq1yrlet.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelt7zrk1mk/prophet_model-20260803145531.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:31 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:31 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/a0prytp4.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6vkkv3l1.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=34071', 'data', 'file=/tmp/tmpjd45me00/a0prytp4.json', 'init=/tmp/tmpjd45me00/6vkkv3l1.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model7mid413q/prophet_model-20260803145531.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:31 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:31 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/nosem118.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zumrfnvi.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=87303', 'data', 'file=/tmp/tmpjd45me00/nosem118.json', 'init=/tmp/tmpjd45me00/zumrfnvi.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelhzcr57rv/prophet_model-20260803145531.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:31 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_37_dept_56
Build prophet model for  store_38_dept_31

14:55:31 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5zgb96q2.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/r6gnwqlz.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=85672', 'data', 'file=/tmp/tmpjd45me00/5zgb96q2.json', 'init=/tmp/tmpjd45me00/r6gnwqlz.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelfn1rkbpl/prophet_model-20260803145531.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:31 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:31 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_s9mends.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fayehp28.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=43616', 'data', 'file=/tmp/tmpjd45me00/_s9mends.json', 'init=/tmp/tmpjd45me00/fayehp28.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model8gj7plez/prophet_model-20260803145531.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:55:31 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_38_dept_32
Build prophet model for  store_39_dept_51

14:55:32 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zh42qix7.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vffzcsf2.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=56756', 'data', 'file=/tmp/tmpjd45me00/zh42qix7.json', 'init=/tmp/tmpjd45me00/vffzcsf2.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model2xty63of/prophet_model-20260803145532.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:32 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:32 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_3_dept_51
Skip  store_3_dept_51 due to lack of data
Build prophet model for  store_42_dept_87
Build prophet model for  store_45_dept_94

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/93fblvdi.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/au7fimfs.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=88501', 'data', 'file=/tmp/tmpjd45me00/93fblvdi.json', 'init=/tmp/tmpjd45me00/au7fimfs.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelcd0x6m2z/prophet_model-20260803145532.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:32 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:33 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9bhui98o.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8fvgpjj1.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=39820', 'data', 'file=/tmp/tmpjd45me00/9bhui98o.json', 'init=/tmp/tmpjd45me00/8fvgpjj1.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelik4gwnn2/prophet_model-20260803145533.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:55:33 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_5_dept_19

14:55:33 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/saf399nv.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8eg_0lrv.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=12523', 'data', 'file=/tmp/tmpjd45me00/saf399nv.json', 'init=/tmp/tmpjd45me00/8eg_0lrv.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_5r2tg3h/prophet_model-20260803145534.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:34 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_11_dept_45
Skip  store_11_dept_45 due to lack of data
Build prophet model for  store_12_dept_80

14:55:34 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4q54nxd9.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/np4tz38f.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=26542', 'data', 'file=/tmp/tmpjd45me00/4q54nxd9.json', 'init=/tmp/tmpjd45me00/np4tz38f.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelojncxu4o/prophet_model-20260803145534.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:55:34 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_15_dept_94

14:55:35 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qeg3qgpa.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0mio8_hz.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=15650', 'data', 'file=/tmp/tmpjd45me00/qeg3qgpa.json', 'init=/tmp/tmpjd45me00/0mio8_hz.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelk_gg6p37/prophet_model-20260803145535.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:35 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:35 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/glchc562.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/i8yuw37r.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=57073', 'data', 'file=/tmp/tmpjd45me00/glchc562.json', 'init=/tmp/tmpjd45me00/i8yuw37r.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelj3gusp6q/prophet_model-20260803145535.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:35 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_17_dept_41
Build prophet model for  store_17_dept_98

14:55:35 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/eohv8x_i.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2j5j9jlc.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=79507', 'data', 'file=/tmp/tmpjd45me00/eohv8x_i.json', 'init=/tmp/tmpjd45me00/2j5j9jlc.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modell81x03qg/prophet_model-20260803145535.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:35 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:35 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/x5qbe626.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jzrr_akr.json
DEBUG:cmdstanpy:idx 0

Build prophet model for  store_18_dept_80
Build prophet model for  store_18_dept_94

DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=69988', 'data', 'file=/tmp/tmpjd45me00/x5qbe626.json', 'init=/tmp/tmpjd45me00/jzrr_akr.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelqlfa6o5w/prophet_model-20260803145536.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:36 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:36 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jf2kqkg0.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ugp6wmo3.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=7710', 'data', 'file=/tmp/tmpjd45me00/jf2kqkg0.json', 'init=/tmp/tmpjd45me00/ugp6wmo3.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelfyt_t9ed/prophet_model-20260803145536.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:36 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:36 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_18_dept_98
Build prophet model for  store_19_dept_51
Skip  store_19_dept_51 due to lack of data
Build prophet model for  store_23_dept_98

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ml5tj288.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qvnun9r9.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=96044', 'data', 'file=/tmp/tmpjd45me00/ml5tj288.json', 'init=/tmp/tmpjd45me00/qvnun9r9.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeldf_uczd6/prophet_model-20260803145536.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:36 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:36 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/v7xxmkns.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_2b1h8eb.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=71571', 'data', 'file=/tmp/tmpjd45me00/v7xxmkns.json', 'init=/tmp/tmpjd45me00/_2b1h8eb.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelb9jusaqz/prophet_model-20260803145536.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:36 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_29_dept_98

14:55:37 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/iryojaby.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/l3zb0azz.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=4298', 'data', 'file=/tmp/tmpjd45me00/iryojaby.json', 'init=/tmp/tmpjd45me00/l3zb0azz.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model91u6xovk/prophet_model-20260803145537.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:37 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:37 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8frpvktk.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2tml5w_j.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=79205', 'data', 'file=/tmp/tmpjd45me00/8frpvktk.json', 'init=/tmp/tmpjd45me00/2tml5w_j.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelk70lkvjv/prophet_model-20260803145537.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:55:37 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_30_dept_32
Build prophet model for  store_33_dept_18

14:55:38 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/io2y71ld.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pt5h6iop.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=18335', 'data', 'file=/tmp/tmpjd45me00/io2y71ld.json', 'init=/tmp/tmpjd45me00/pt5h6iop.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelqiedv29d/prophet_model-20260803145538.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:38 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:38 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_35_dept_80
Build prophet model for  store_36_dept_20

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hkcw1n8w.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hw03f72a.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=66962', 'data', 'file=/tmp/tmpjd45me00/hkcw1n8w.json', 'init=/tmp/tmpjd45me00/hw03f72a.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeljx5iy97y/prophet_model-20260803145538.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:38 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:38 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/j_m08onn.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vb7ghtn3.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=66841', 'data', 'file=/tmp/tmpjd45me00/j_m08onn.json', 'init=/tmp/tmpjd45me00/vb7ghtn3.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelx3hxk34s/prophet_model-20260803145538.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:38 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:38 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_43_dept_87

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/itohwq1g.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/q5leu0ia.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=57849', 'data', 'file=/tmp/tmpjd45me00/itohwq1g.json', 'init=/tmp/tmpjd45me00/q5leu0ia.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeleyhvlim5/prophet_model-20260803145539.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:39 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:39 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_44_dept_85

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/uzqsbpy4.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ghrey7x2.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=67787', 'data', 'file=/tmp/tmpjd45me00/uzqsbpy4.json', 'init=/tmp/tmpjd45me00/ghrey7x2.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelo66xmttc/prophet_model-20260803145539.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:39 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:39 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_4_dept_51
Skip  store_4_dept_51 due to lack of data
Build prophet model for  store_5_dept_58

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/klu_wbr2.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/079rizz3.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=61376', 'data', 'file=/tmp/tmpjd45me00/klu_wbr2.json', 'init=/tmp/tmpjd45me00/079rizz3.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelktfj0n93/prophet_model-20260803145539.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:55:39 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_6_dept_51
Skip  store_6_dept_51 due to lack of data
Build prophet model for  store_15_dept_51
Skip  store_15_dept_51 due to lack of data
Build prophet model for  store_21_dept_94

14:55:41 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fqujmvcd.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/64ehoz3d.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=4675', 'data', 'file=/tmp/tmpjd45me00/fqujmvcd.json', 'init=/tmp/tmpjd45me00/64ehoz3d.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelokw6r4mv/prophet_model-20260803145541.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:41 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_22_dept_45
Skip  store_22_dept_45 due to lack of data
Build prophet model for  store_23_dept_80

14:55:42 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vybiwsre.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7lnfoh4k.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=17033', 'data', 'file=/tmp/tmpjd45me00/vybiwsre.json', 'init=/tmp/tmpjd45me00/7lnfoh4k.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelokko1uwl/prophet_model-20260803145542.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:55:42 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_24_dept_45
Skip  store_24_dept_45 due to lack of data
Build prophet model for  store_26_dept_51
Skip  store_26_dept_51 due to lack of data
Build prophet model for  store_33_dept_59
Skip  store_33_dept_59 due to lack of data
Build prophet model for  store_39_dept_45

14:55:42 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9812f73p.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5ljlh9eu.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=84000', 'data', 'file=/tmp/tmpjd45me00/9812f73p.json', 'init=/tmp/tmpjd45me00/5ljlh9eu.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model2gn5f7jm/prophet_model-20260803145542.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:55:42 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_40_dept_51
Skip  store_40_dept_51 due to lack of data
Build prophet model for  store_43_dept_32

14:55:43 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/313dnmi6.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pdteiv4m.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=68945', 'data', 'file=/tmp/tmpjd45me00/313dnmi6.json', 'init=/tmp/tmpjd45me00/pdteiv4m.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelqbphk1zy/prophet_model-20260803145543.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:55:43 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_44_dept_23

14:55:44 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/45z8j331.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5_csryno.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=92552', 'data', 'file=/tmp/tmpjd45me00/45z8j331.json', 'init=/tmp/tmpjd45me00/5_csryno.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelnh3kxihn/prophet_model-20260803145544.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:44 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:55:44 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/k8kqqxl4.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hlk63m2v.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=82502', 'data', 'file=/tmp/tmpjd45me00/k8kqqxl4.json', 'init=/tmp/tmpjd45me00/hlk63m2v.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelmpbm2fex/prophet_model-20260803145544.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:55:44 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_44_dept_32
Build prophet model for  store_45_dept_80

14:55:44 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9pls03k_.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gkmw3nww.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=14314', 'data', 'file=/tmp/tmpjd45me00/9pls03k_.json', 'init=/tmp/tmpjd45me00/gkmw3nww.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelw0tal4t6/prophet_model-20260803145544.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:55:44 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_16_dept_45

14:55:45 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 24.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/uptmj9cl.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/baf4c_24.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=52878', 'data', 'file=/tmp/tmpjd45me00/uptmj9cl.json', 'init=/tmp/tmpjd45me00/baf4c_24.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model6qfk2w3j/prophet_model-20260803145545.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:55:45 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_18_dept_51
Skip  store_18_dept_51 due to lack of data
Build prophet model for  store_19_dept_45
Skip  store_19_dept_45 due to lack of data
Build prophet model for  store_30_dept_41

14:56:10 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ww8homhw.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jaiclp_2.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=24591', 'data', 'file=/tmp/tmpjd45me00/ww8homhw.json', 'init=/tmp/tmpjd45me00/jaiclp_2.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelbbww79he/prophet_model-20260803145610.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:56:10 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_33_dept_25

14:56:11 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ojoo1zmr.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_6qcznmu.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=6066', 'data', 'file=/tmp/tmpjd45me00/ojoo1zmr.json', 'init=/tmp/tmpjd45me00/_6qcznmu.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelajh9n5z3/prophet_model-20260803145611.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:56:11 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_34_dept_45
Skip  store_34_dept_45 due to lack of data
Build prophet model for  store_38_dept_56

14:56:12 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/y6r0fvrg.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xvpea70z.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=99246', 'data', 'file=/tmp/tmpjd45me00/y6r0fvrg.json', 'init=/tmp/tmpjd45me00/xvpea70z.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeln8m_v61x/prophet_model-20260803145612.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:56:12 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_43_dept_31

14:56:13 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/x_an_xiq.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/y68bxh26.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=45425', 'data', 'file=/tmp/tmpjd45me00/x_an_xiq.json', 'init=/tmp/tmpjd45me00/y68bxh26.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model7w0ik906/prophet_model-20260803145613.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:56:13 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_43_dept_56

14:56:15 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/l3nz2jtg.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/z4il7u4k.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=89598', 'data', 'file=/tmp/tmpjd45me00/l3nz2jtg.json', 'init=/tmp/tmpjd45me00/z4il7u4k.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeld32t48t_/prophet_model-20260803145615.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:56:15 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_44_dept_55
Skip  store_44_dept_55 due to lack of data
Build prophet model for  store_4_dept_45

14:56:42 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/h7ywtmco.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/sxq9odyz.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=37427', 'data', 'file=/tmp/tmpjd45me00/h7ywtmco.json', 'init=/tmp/tmpjd45me00/sxq9odyz.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model6f0g5157/prophet_model-20260803145642.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:56:42 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_5_dept_45
Skip  store_5_dept_45 due to lack of data
Build prophet model for  store_7_dept_58

14:56:43 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wjgqugfg.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0c6hj6cp.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=20144', 'data', 'file=/tmp/tmpjd45me00/wjgqugfg.json', 'init=/tmp/tmpjd45me00/0c6hj6cp.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeld7vbiakr/prophet_model-20260803145643.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:56:43 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_30_dept_56

14:56:44 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/e_xw584y.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/o45bmg4l.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=11697', 'data', 'file=/tmp/tmpjd45me00/e_xw584y.json', 'init=/tmp/tmpjd45me00/o45bmg4l.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model3xb_pn4l/prophet_model-20260803145645.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:56:45 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:56:45 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_33_dept_20

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/nrl68d6s.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/cwzs87c8.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=8822', 'data', 'file=/tmp/tmpjd45me00/nrl68d6s.json', 'init=/tmp/tmpjd45me00/cwzs87c8.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelpqxnulj7/prophet_model-20260803145645.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:56:45 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_36_dept_25

14:56:47 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/z67kdagi.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ueolb1ae.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=40627', 'data', 'file=/tmp/tmpjd45me00/z67kdagi.json', 'init=/tmp/tmpjd45me00/ueolb1ae.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelofruiidg/prophet_model-20260803145647.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:56:47 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_42_dept_56

14:56:48 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8dtw5okf.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jidsxily.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=19357', 'data', 'file=/tmp/tmpjd45me00/8dtw5okf.json', 'init=/tmp/tmpjd45me00/jidsxily.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelbl0y3s78/prophet_model-20260803145648.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:56:48 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_44_dept_31

14:56:49 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ndlfp3qj.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rkv6vkho.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=12168', 'data', 'file=/tmp/tmpjd45me00/ndlfp3qj.json', 'init=/tmp/tmpjd45me00/rkv6vkho.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model2mjnlxbv/prophet_model-20260803145649.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:56:49 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_44_dept_56

14:56:51 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/q25oylhr.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1xdxb2gs.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=99109', 'data', 'file=/tmp/tmpjd45me00/q25oylhr.json', 'init=/tmp/tmpjd45me00/1xdxb2gs.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelp_yvzbek/prophet_model-20260803145651.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:56:51 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_4_dept_78
Skip  store_4_dept_78 due to lack of data
Build prophet model for  store_11_dept_19

14:56:53 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9x2gcqbt.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9r5mlm4_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=2817', 'data', 'file=/tmp/tmpjd45me00/9x2gcqbt.json', 'init=/tmp/tmpjd45me00/9r5mlm4_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model21b13owf/prophet_model-20260803145653.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:56:53 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_22_dept_19

14:56:54 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/97vdiscw.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2c0ynyvq.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=2155', 'data', 'file=/tmp/tmpjd45me00/97vdiscw.json', 'init=/tmp/tmpjd45me00/2c0ynyvq.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_l8sk_rh/prophet_model-20260803145654.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:56:54 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:56:55 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_22_dept_94
Build prophet model for  store_24_dept_78
Skip  store_24_dept_78 due to lack of data
Build prophet model for  store_29_dept_94

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2g1oj56s.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/608biwat.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=33939', 'data', 'file=/tmp/tmpjd45me00/2g1oj56s.json', 'init=/tmp/tmpjd45me00/608biwat.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelrlhe4ix9/prophet_model-20260803145655.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:56:55 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:56:55 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2txzho4j.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/50v1fgk1.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=60484', 'data', 'file=/tmp/tmpjd45me00/2txzho4j.json', 'init=/tmp/tmpjd45me00/50v1fgk1.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_f4lgajr/prophet_model-20260803145656.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:56:56 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_32_dept_45

14:56:56 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vxh44zt4.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/n_emwi90.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=45083', 'data', 'file=/tmp/tmpjd45me00/vxh44zt4.json', 'init=/tmp/tmpjd45me00/n_emwi90.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeljg9ddda3/prophet_model-20260803145657.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:56:57 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_33_dept_9

14:56:59 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/tv04rr0b.json

Build prophet model for  store_37_dept_55
Skip  store_37_dept_55 due to lack of data
Build prophet model for  store_45_dept_51
Skip  store_45_dept_51 due to lack of data
Build prophet model for  store_18_dept_45
Skip  store_18_dept_45 due to lack of data
Build prophet model for  store_18_dept_78
Skip  store_18_dept_78 due to lack of data
Build prophet model for  store_25_dept_94

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fdtxe5g8.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=92874', 'data', 'file=/tmp/tmpjd45me00/tv04rr0b.json', 'init=/tmp/tmpjd45me00/fdtxe5g8.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeln7m3awaj/prophet_model-20260803145659.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:56:59 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:56:59 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_56dpuf1.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xyrbn848.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=48017', 'data', 'file=/tmp/tmpjd45me00/_56dpuf1.json', 'init=/tmp/tmpjd45me00/xyrbn848.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelffp3n9fg/prophet_model-20260803145659.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:56:59 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:56:59 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/di_lptxn.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4woqtcm8.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=2928', 'data', 'file=/tmp/tmpjd45me00/di_lptxn.json', 'init=/tmp/tmpjd45me00/4woqtcm8.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelllhr1nvw/prophet_model-20260803145700.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:57:00 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_33_dept_55
Build prophet model for  store_5_dept_94

14:57:01 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mkdwdffe.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/z4l7cplo.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=36089', 'data', 'file=/tmp/tmpjd45me00/mkdwdffe.json', 'init=/tmp/tmpjd45me00/z4l7cplo.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model2p822phm/prophet_model-20260803145701.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:57:01 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:57:01 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_15_dept_98
Build prophet model for  store_17_dept_94

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5m1279k7.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2u9pzweg.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=90785', 'data', 'file=/tmp/tmpjd45me00/5m1279k7.json', 'init=/tmp/tmpjd45me00/2u9pzweg.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeligct4kbq/prophet_model-20260803145701.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:57:01 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:57:02 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8_c4dbft.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/omstkdzj.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=17471', 'data', 'file=/tmp/tmpjd45me00/8_c4dbft.json', 'init=/tmp/tmpjd45me00/omstkdzj.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_w1ezb4q/prophet_model-20260803145702.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:57:02 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_29_dept_19

14:57:03 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/kyd7a9jg.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hrugqmcx.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=69427', 'data', 'file=/tmp/tmpjd45me00/kyd7a9jg.json', 'init=/tmp/tmpjd45me00/hrugqmcx.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model11s3rhzg/prophet_model-20260803145703.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:57:03 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:57:03 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/yax6pn5t.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/i4y3djo5.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=74954', 'data', 'file=/tmp/tmpjd45me00/yax6pn5t.json', 'init=/tmp/tmpjd45me00/i4y3djo5.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelawzc_3bg/prophet_model-20260803145703.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:57:03 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_33_dept_12
Build prophet model for  store_36_dept_18

14:57:04 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/e5upt10c.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8sb3y5n0.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=48497', 'data', 'file=/tmp/tmpjd45me00/e5upt10c.json', 'init=/tmp/tmpjd45me00/8sb3y5n0.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelet53vhsh/prophet_model-20260803145704.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:57:04 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:57:04 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gvgh2fel.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/j9zi9qrs.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=83064', 'data', 'file=/tmp/tmpjd45me00/gvgh2fel.json', 'init=/tmp/tmpjd45me00/j9zi9qrs.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model6ngbiujh/prophet_model-20260803145705.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:57:05 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_7_dept_80
Build prophet model for  store_16_dept_80

14:57:05 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1rj906f5.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rgl5c4cl.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=78661', 'data', 'file=/tmp/tmpjd45me00/1rj906f5.json', 'init=/tmp/tmpjd45me00/rgl5c4cl.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelief_w0h9/prophet_model-20260803145705.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:57:05 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_21_dept_51
Skip  store_21_dept_51 due to lack of data
Build prophet model for  store_34_dept_19

14:57:06 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/iiafy4x0.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mfwudi8i.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=87695', 'data', 'file=/tmp/tmpjd45me00/iiafy4x0.json', 'init=/tmp/tmpjd45me00/mfwudi8i.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelo28vijvk/prophet_model-20260803145706.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:57:06 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:57:06 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_18_dept_50
Build prophet model for  store_20_dept_45

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/t2z00szu.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/z1q8ilgu.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=89638', 'data', 'file=/tmp/tmpjd45me00/t2z00szu.json', 'init=/tmp/tmpjd45me00/z1q8ilgu.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model0pvitcdb/prophet_model-20260803145706.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:57:06 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:57:06 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/eaoj0h3m.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/upvbspq0.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=33064', 'data', 'file=/tmp/tmpjd45me00/eaoj0h3m.json', 'init=/tmp/tmpjd45me00/upvbspq0.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_mi_dudw/prophet_model-20260803145706.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']

Skip  store_20_dept_45 due to lack of data
Build prophet model for  store_21_dept_60
Build prophet model for  store_29_dept_80

14:57:06 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:57:06 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jwnewg8a.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/lu7klv_a.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=85021', 'data', 'file=/tmp/tmpjd45me00/jwnewg8a.json', 'init=/tmp/tmpjd45me00/lu7klv_a.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model64b7332n/prophet_model-20260803145706.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:57:06 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:57:06 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_3_dept_47
Skip  store_3_dept_47 due to lack of data
Build prophet model for  store_14_dept_47
Skip  store_14_dept_47 due to lack of data
Build prophet model for  store_31_dept_60
Build prophet model for  store_37_dept_20

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/44tsaytd.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2_zl1p48.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=34144', 'data', 'file=/tmp/tmpjd45me00/44tsaytd.json', 'init=/tmp/tmpjd45me00/2_zl1p48.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelv6lblg7t/prophet_model-20260803145706.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:57:06 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:57:07 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ebctfrcf.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_2w9eodd.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=68492', 'data', 'file=/tmp/tmpjd45me00/ebctfrcf.json', 'init=/tmp/tmpjd45me00/_2w9eodd.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelh5yuiabt/prophet_model-20260803145707.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:57:07 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_43_dept_5

14:57:09 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/lyirxwzl.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hu8q0o3v.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=13875', 'data', 'file=/tmp/tmpjd45me00/lyirxwzl.json', 'init=/tmp/tmpjd45me00/hu8q0o3v.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model4877en9k/prophet_model-20260803145709.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:57:09 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_21_dept_80

14:57:10 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/cumn_kyu.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/aw0g5e1o.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=67748', 'data', 'file=/tmp/tmpjd45me00/cumn_kyu.json', 'init=/tmp/tmpjd45me00/aw0g5e1o.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model84chyvdi/prophet_model-20260803145710.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:57:10 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_24_dept_51
Skip  store_24_dept_51 due to lack of data
Build prophet model for  store_27_dept_60

14:57:10 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/kbxf0mwk.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/x0j0nqka.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=52142', 'data', 'file=/tmp/tmpjd45me00/kbxf0mwk.json', 'init=/tmp/tmpjd45me00/x0j0nqka.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelfcdykt7j/prophet_model-20260803145710.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:57:10 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_36_dept_9

14:57:11 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mn6wjezn.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/d1o7ye4a.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=44609', 'data', 'file=/tmp/tmpjd45me00/mn6wjezn.json', 'init=/tmp/tmpjd45me00/d1o7ye4a.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelj7yzwydy/prophet_model-20260803145712.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:57:12 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_38_dept_26

14:57:13 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/98c1602i.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/kcu159bq.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=1066', 'data', 'file=/tmp/tmpjd45me00/98c1602i.json', 'init=/tmp/tmpjd45me00/kcu159bq.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model680ljqjt/prophet_model-20260803145713.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:57:13 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_41_dept_47
Skip  store_41_dept_47 due to lack of data
Build prophet model for  store_24_dept_60

14:57:15 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ot9x8y8h.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5xpwn6rj.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=47719', 'data', 'file=/tmp/tmpjd45me00/ot9x8y8h.json', 'init=/tmp/tmpjd45me00/5xpwn6rj.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modellwm74kdz/prophet_model-20260803145715.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:57:15 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_25_dept_45
Skip  store_25_dept_45 due to lack of data
Build prophet model for  store_29_dept_60

14:57:16 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_zhbeeir.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/l70lvn2o.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=42828', 'data', 'file=/tmp/tmpjd45me00/_zhbeeir.json', 'init=/tmp/tmpjd45me00/l70lvn2o.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model3pjpn438/prophet_model-20260803145716.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:57:16 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:57:16 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pstozfue.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8wqvog9b.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=42889', 'data', 'file=/tmp/tmpjd45me00/pstozfue.json', 'init=/tmp/tmpjd45me00/8wqvog9b.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelaypa1n4x/prophet_model-20260803145717.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:57:17 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_33_dept_42
Build prophet model for  store_36_dept_42

14:57:17 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/eyy3mbpz.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4lmon6un.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=46910', 'data', 'file=/tmp/tmpjd45me00/eyy3mbpz.json', 'init=/tmp/tmpjd45me00/4lmon6un.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelkx63j73k/prophet_model-20260803145717.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:57:17 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:57:17 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/cr2exklt.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1cvrebzd.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=77926', 'data', 'file=/tmp/tmpjd45me00/cr2exklt.json', 'init=/tmp/tmpjd45me00/1cvrebzd.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model2011bbsw/prophet_model-20260803145717.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:57:17 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_36_dept_12
Build prophet model for  store_38_dept_20

14:57:18 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 11.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/f0wxy_vp.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_ujqtvaa.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=86155', 'data', 'file=/tmp/tmpjd45me00/f0wxy_vp.json', 'init=/tmp/tmpjd45me00/_ujqtvaa.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelbl3zqkoy/prophet_model-20260803145718.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:57:18 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_20_dept_51
Skip  store_20_dept_51 due to lack of data
Build prophet model for  store_27_dept_47

14:57:32 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/scu66_nf.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/u8pwt5bt.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=20557', 'data', 'file=/tmp/tmpjd45me00/scu66_nf.json', 'init=/tmp/tmpjd45me00/u8pwt5bt.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelxr1ijzxi/prophet_model-20260803145732.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:57:32 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_35_dept_94

14:57:33 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 15.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/t023cc2k.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2nlc0ubm.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=49347', 'data', 'file=/tmp/tmpjd45me00/t023cc2k.json', 'init=/tmp/tmpjd45me00/2nlc0ubm.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelz7q8t7zp/prophet_model-20260803145733.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:57:33 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_9_dept_47
Skip  store_9_dept_47 due to lack of data
Build prophet model for  store_20_dept_47

14:57:51 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/c03ms51l.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mpyh_g6o.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=61982', 'data', 'file=/tmp/tmpjd45me00/c03ms51l.json', 'init=/tmp/tmpjd45me00/mpyh_g6o.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelkt9rdc_5/prophet_model-20260803145751.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:57:51 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_28_dept_45
Skip  store_28_dept_45 due to lack of data
Build prophet model for  store_3_dept_45
Skip  store_3_dept_45 due to lack of data
Build prophet model for  store_42_dept_20

14:57:52 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/kkx58kvx.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/m2k22i64.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=8778', 'data', 'file=/tmp/tmpjd45me00/kkx58kvx.json', 'init=/tmp/tmpjd45me00/m2k22i64.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model26mjttni/prophet_model-20260803145752.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:57:52 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:57:52 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_5_dept_97
Build prophet model for  store_15_dept_47
Skip  store_15_dept_47 due to lack of data
Build prophet model for  store_30_dept_20

DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/sks04hw1.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/t51g48o0.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=38644', 'data', 'file=/tmp/tmpjd45me00/sks04hw1.json', 'init=/tmp/tmpjd45me00/t51g48o0.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelnts38skk/prophet_model-20260803145752.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:57:52 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:57:54 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xuanmvqg.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/a83zyjsk.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=76474', 'data', 'file=/tmp/tmpjd45me00/xuanmvqg.json', 'init=/tmp/tmpjd45me00/a83zyjsk.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelxv9p6x6j/prophet_model-20260803145754.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:57:54 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_38_dept_44

14:57:55 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/nh9500t7.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/u5ni1wz1.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=82861', 'data', 'file=/tmp/tmpjd45me00/nh9500t7.json', 'init=/tmp/tmpjd45me00/u5ni1wz1.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model1x__rnpt/prophet_model-20260803145755.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:57:55 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_43_dept_20

14:57:56 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/f2ec6qla.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4qcl5ggo.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=52977', 'data', 'file=/tmp/tmpjd45me00/f2ec6qla.json', 'init=/tmp/tmpjd45me00/4qcl5ggo.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelou_eopmn/prophet_model-20260803145756.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:57:56 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_6_dept_78
Skip  store_6_dept_78 due to lack of data
Build prophet model for  store_9_dept_94

14:57:57 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mqr_7xz0.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8c1mablw.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=37676', 'data', 'file=/tmp/tmpjd45me00/mqr_7xz0.json', 'init=/tmp/tmpjd45me00/8c1mablw.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model0q44bqhk/prophet_model-20260803145757.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:57:57 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_15_dept_45
Skip  store_15_dept_45 due to lack of data
Build prophet model for  store_25_dept_19
Skip  store_25_dept_19 due to lack of data
Build prophet model for  store_25_dept_47
Skip  store_25_dept_47 due to lack of data
Build prophet model for  store_2_dept_60

14:57:59 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 20.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/svudqd_j.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_pghijc0.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=4513', 'data', 'file=/tmp/tmpjd45me00/svudqd_j.json', 'init=/tmp/tmpjd45me00/_pghijc0.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model3aa9fnw_/prophet_model-20260803145759.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:57:59 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_31_dept_45
Skip  store_31_dept_45 due to lack of data
Build prophet model for  store_36_dept_52
Skip  store_36_dept_52 due to lack of data
Build prophet model for  store_8_dept_45
Skip  store_8_dept_45 due to lack of data
Build prophet model for  store_10_dept_47

14:58:21 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 22.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0i4y2xz2.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/88h0ch3p.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=62266', 'data', 'file=/tmp/tmpjd45me00/0i4y2xz2.json', 'init=/tmp/tmpjd45me00/88h0ch3p.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelywx4e5y_/prophet_model-20260803145821.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:58:21 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_27_dept_45
Skip  store_27_dept_45 due to lack of data
Build prophet model for  store_35_dept_47

14:58:45 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/w9j122fy.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ro78_9bp.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=14818', 'data', 'file=/tmp/tmpjd45me00/w9j122fy.json', 'init=/tmp/tmpjd45me00/ro78_9bp.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelxjjhmyq_/prophet_model-20260803145845.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:58:45 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_38_dept_23

14:58:46 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/thuikq_1.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hfi2gqkb.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=5143', 'data', 'file=/tmp/tmpjd45me00/thuikq_1.json', 'init=/tmp/tmpjd45me00/hfi2gqkb.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelqyugwa2g/prophet_model-20260803145846.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:58:46 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:58:46 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_9_dept_45
Skip  store_9_dept_45 due to lack of data
Build prophet model for  store_30_dept_26
Skip  store_30_dept_26 due to lack of data
Build prophet model for  store_36_dept_41
Skip  store_36_dept_41 due to lack of data
Build prophet model for  store_1_dept_96

INFO:prophet:n_changepoints greater than number of observations. Using 8.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/nqe2j9es.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/t4mi7bin.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=23239', 'data', 'file=/tmp/tmpjd45me00/nqe2j9es.json', 'init=/tmp/tmpjd45me00/t4mi7bin.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelhsea5ymx/prophet_model-20260803145846.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:58:46 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_42_dept_44

14:58:58 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 5.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/nxl5xnx0.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/o4ywkv8d.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=83847', 'data', 'file=/tmp/tmpjd45me00/nxl5xnx0.json', 'init=/tmp/tmpjd45me00/o4ywkv8d.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelu1e7p5yd/prophet_model-20260803145858.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:58:58 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_43_dept_26

14:59:07 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/64gnf8_6.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8xa3eya0.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=68467', 'data', 'file=/tmp/tmpjd45me00/64gnf8_6.json', 'init=/tmp/tmpjd45me00/8xa3eya0.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelfbfsf_ws/prophet_model-20260803145907.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:59:07 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_33_dept_52

14:59:09 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vabshegg.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/aplct_7r.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=96719', 'data', 'file=/tmp/tmpjd45me00/vabshegg.json', 'init=/tmp/tmpjd45me00/aplct_7r.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelnzp2hwns/prophet_model-20260803145909.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
14:59:09 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:59:09 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_36_dept_87
Build prophet model for  store_43_dept_44
Skip  store_43_dept_44 due to lack of data
Build prophet model for  store_22_dept_49

INFO:prophet:n_changepoints greater than number of observations. Using 19.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/x0asc2xr.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/u1e2cw_i.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=4358', 'data', 'file=/tmp/tmpjd45me00/x0asc2xr.json', 'init=/tmp/tmpjd45me00/u1e2cw_i.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelgmg4sc7p/prophet_model-20260803145909.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:59:09 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
14:59:10 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4g9oe10y.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/k8s1qsqg.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=85114', 'data', 'file=/tmp/tmpjd45me00/4g9oe10y.json', 'init=/tmp/tmpjd45me00/k8s1qsqg.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeleqahj4yx/prophet_model-20260803145910.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:59:10 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_28_dept_47
Skip  store_28_dept_47 due to lack of data
Build prophet model for  store_45_dept_78
Skip  store_45_dept_78 due to lack of data
Build prophet model for  store_18_dept_60

14:59:11 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 17.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/slg6c1f6.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/clx5_ux9.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=76337', 'data', 'file=/tmp/tmpjd45me00/slg6c1f6.json', 'init=/tmp/tmpjd45me00/clx5_ux9.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelh4b0byb2/prophet_model-20260803145911.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:59:12 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_31_dept_47
Skip  store_31_dept_47 due to lack of data
Build prophet model for  store_39_dept_19

14:59:29 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/g42j5rre.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ecklgyxp.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=53818', 'data', 'file=/tmp/tmpjd45me00/g42j5rre.json', 'init=/tmp/tmpjd45me00/ecklgyxp.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeleetyeb77/prophet_model-20260803145929.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:59:29 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_4_dept_47
Skip  store_4_dept_47 due to lack of data
Build prophet model for  store_20_dept_19

14:59:30 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/nkhou2yu.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hz7ef_d6.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=12933', 'data', 'file=/tmp/tmpjd45me00/nkhou2yu.json', 'init=/tmp/tmpjd45me00/hz7ef_d6.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeleg_7e9y9/prophet_model-20260803145930.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:59:30 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_21_dept_45
Skip  store_21_dept_45 due to lack of data
Build prophet model for  store_29_dept_47
Skip  store_29_dept_47 due to lack of data
Build prophet model for  store_3_dept_94

14:59:31 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 12.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/97ia2_b_.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/sfq44gd0.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=42018', 'data', 'file=/tmp/tmpjd45me00/97ia2_b_.json', 'init=/tmp/tmpjd45me00/sfq44gd0.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model3r19txxv/prophet_model-20260803145931.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:59:31 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_45_dept_45

14:59:45 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 4.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zf5hbwpa.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/yu58g1ue.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=70461', 'data', 'file=/tmp/tmpjd45me00/zf5hbwpa.json', 'init=/tmp/tmpjd45me00/yu58g1ue.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_lofw30c/prophet_model-20260803145946.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:59:46 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_38_dept_34

14:59:55 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dt3szvoi.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6tztqai4.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=69398', 'data', 'file=/tmp/tmpjd45me00/dt3szvoi.json', 'init=/tmp/tmpjd45me00/6tztqai4.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modela6xepfx3/prophet_model-20260803145955.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:59:55 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_36_dept_5

14:59:56 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vcrph08n.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/kecnfus8.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=4643', 'data', 'file=/tmp/tmpjd45me00/vcrph08n.json', 'init=/tmp/tmpjd45me00/kecnfus8.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelkc9mp0dg/prophet_model-20260803145956.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:59:56 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_22_dept_48
Skip  store_22_dept_48 due to lack of data
Build prophet model for  store_33_dept_6
Skip  store_33_dept_6 due to lack of data
Build prophet model for  store_35_dept_49

14:59:57 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 8.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hu2sxj1p.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ae26o4nx.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=2358', 'data', 'file=/tmp/tmpjd45me00/hu2sxj1p.json', 'init=/tmp/tmpjd45me00/ae26o4nx.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelfyfe654y/prophet_model-20260803145957.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
14:59:57 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_36_dept_6

15:00:08 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 17.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2j9197bb.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/08w9ajzb.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=10012', 'data', 'file=/tmp/tmpjd45me00/2j9197bb.json', 'init=/tmp/tmpjd45me00/08w9ajzb.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model1odfb_hm/prophet_model-20260803150008.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:00:08 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_38_dept_33

15:00:23 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/co5mhtuu.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8a7qe9xp.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=36906', 'data', 'file=/tmp/tmpjd45me00/co5mhtuu.json', 'init=/tmp/tmpjd45me00/8a7qe9xp.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelqpyasbw8/prophet_model-20260803150023.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:00:23 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_8_dept_47
Skip  store_8_dept_47 due to lack of data
Build prophet model for  store_17_dept_49

15:00:25 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 10.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/k9ayyxa2.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1v4fqj1k.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=32727', 'data', 'file=/tmp/tmpjd45me00/k9ayyxa2.json', 'init=/tmp/tmpjd45me00/1v4fqj1k.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelkamrr_95/prophet_model-20260803150025.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:00:25 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_2_dept_47
Skip  store_2_dept_47 due to lack of data
Build prophet model for  store_10_dept_78
Skip  store_10_dept_78 due to lack of data
Build prophet model for  store_1_dept_47

15:00:37 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mnko3bq6.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/s0aug6ce.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=58405', 'data', 'file=/tmp/tmpjd45me00/mnko3bq6.json', 'init=/tmp/tmpjd45me00/s0aug6ce.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeldwttvyi4/prophet_model-20260803150037.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:00:37 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_16_dept_60

15:00:40 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 7.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/b8y67244.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/40_50av9.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=75350', 'data', 'file=/tmp/tmpjd45me00/b8y67244.json', 'init=/tmp/tmpjd45me00/40_50av9.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeloqi9jtwv/prophet_model-20260803150040.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:00:40 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_16_dept_58

15:00:50 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/sfv_fppw.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/cnxmqhz4.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=56888', 'data', 'file=/tmp/tmpjd45me00/sfv_fppw.json', 'init=/tmp/tmpjd45me00/cnxmqhz4.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelju077wlk/prophet_model-20260803150050.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:00:50 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_16_dept_98

15:00:52 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 10.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vntpmm3x.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jk8i23su.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=29727', 'data', 'file=/tmp/tmpjd45me00/vntpmm3x.json', 'init=/tmp/tmpjd45me00/jk8i23su.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model6m37lo_p/prophet_model-20260803150052.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:00:52 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_33_dept_44

15:01:02 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9bgq99dg.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gdl_0001.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=4920', 'data', 'file=/tmp/tmpjd45me00/9bgq99dg.json', 'init=/tmp/tmpjd45me00/gdl_0001.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelm07be5zt/prophet_model-20260803150102.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:01:02 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_34_dept_60

15:01:03 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xnj6p0v5.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ux0wsbda.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=48903', 'data', 'file=/tmp/tmpjd45me00/xnj6p0v5.json', 'init=/tmp/tmpjd45me00/ux0wsbda.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelhfse3mn9/prophet_model-20260803150103.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:01:03 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_40_dept_58

15:01:05 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 11.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bcubnbyw.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3s2olo8n.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=777', 'data', 'file=/tmp/tmpjd45me00/bcubnbyw.json', 'init=/tmp/tmpjd45me00/3s2olo8n.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelr2ymm4t8/prophet_model-20260803150105.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:01:05 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_11_dept_47

15:01:12 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7cdkeck1.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4jqkyvvu.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=38763', 'data', 'file=/tmp/tmpjd45me00/7cdkeck1.json', 'init=/tmp/tmpjd45me00/4jqkyvvu.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelb3gzazse/prophet_model-20260803150112.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:01:12 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_25_dept_60

15:01:13 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 8.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6t429_wu.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/90565e1z.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=94712', 'data', 'file=/tmp/tmpjd45me00/6t429_wu.json', 'init=/tmp/tmpjd45me00/90565e1z.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model7go0bjhg/prophet_model-20260803150113.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:01:13 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_29_dept_45
Skip  store_29_dept_45 due to lack of data
Build prophet model for  store_3_dept_98
Skip  store_3_dept_98 due to lack of data
Build prophet model for  store_12_dept_47
Skip  store_12_dept_47 due to lack of data
Build prophet model for  store_21_dept_47

15:01:24 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 7.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vipvnn4b.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/et0e72ak.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=96473', 'data', 'file=/tmp/tmpjd45me00/vipvnn4b.json', 'init=/tmp/tmpjd45me00/et0e72ak.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelguccjnc_/prophet_model-20260803150125.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:01:25 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_26_dept_47

15:01:35 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 6.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5h2gb6h8.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/cj7spl_5.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=45687', 'data', 'file=/tmp/tmpjd45me00/5h2gb6h8.json', 'init=/tmp/tmpjd45me00/cj7spl_5.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelu1wjxik8/prophet_model-20260803150135.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:01:35 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_7_dept_47

15:01:46 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gc35kypk.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/g0yg_rvz.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=62264', 'data', 'file=/tmp/tmpjd45me00/gc35kypk.json', 'init=/tmp/tmpjd45me00/g0yg_rvz.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model7gej18y0/prophet_model-20260803150146.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:01:46 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_33_dept_56
Skip  store_33_dept_56 due to lack of data
Build prophet model for  store_41_dept_19

15:01:47 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/c4xmvi85.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/t8_34wr_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=86887', 'data', 'file=/tmp/tmpjd45me00/c4xmvi85.json', 'init=/tmp/tmpjd45me00/t8_34wr_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelt63evb4l/prophet_model-20260803150147.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:01:47 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_9_dept_60

15:01:48 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 3.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ysija2iv.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/nynpf19y.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=76854', 'data', 'file=/tmp/tmpjd45me00/ysija2iv.json', 'init=/tmp/tmpjd45me00/nynpf19y.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelvu8pz3vq/prophet_model-20260803150148.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:01:48 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_23_dept_48
Skip  store_23_dept_48 due to lack of data
Build prophet model for  store_40_dept_47

15:01:56 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/32z8wwig.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jnwpmvgf.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=43758', 'data', 'file=/tmp/tmpjd45me00/32z8wwig.json', 'init=/tmp/tmpjd45me00/jnwpmvgf.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelqh0g5770/prophet_model-20260803150156.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:01:56 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_15_dept_60

15:01:58 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 15.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_z7s1c8z.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/sqrs1sph.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=69290', 'data', 'file=/tmp/tmpjd45me00/_z7s1c8z.json', 'init=/tmp/tmpjd45me00/sqrs1sph.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelbr28pt4r/prophet_model-20260803150158.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:01:58 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_30_dept_34
Skip  store_30_dept_34 due to lack of data
Build prophet model for  store_42_dept_72

15:02:15 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 0.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/r0c1onkz.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bmhx3thd.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=20451', 'data', 'file=/tmp/tmpjd45me00/r0c1onkz.json', 'init=/tmp/tmpjd45me00/bmhx3thd.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeltq1yowxs/prophet_model-20260803150215.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:02:15 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_38_dept_24
Skip  store_38_dept_24 due to lack of data
Build prophet model for  store_44_dept_44

15:02:22 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/sg_4sapr.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/a0lu9ldg.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=90237', 'data', 'file=/tmp/tmpjd45me00/sg_4sapr.json', 'init=/tmp/tmpjd45me00/a0lu9ldg.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelsvwir0eo/prophet_model-20260803150223.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:02:23 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_44_dept_20

15:02:24 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1b5p6qd2.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/y5nuxr2q.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=86577', 'data', 'file=/tmp/tmpjd45me00/1b5p6qd2.json', 'init=/tmp/tmpjd45me00/y5nuxr2q.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelw8ijjsnp/prophet_model-20260803150224.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:02:24 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_33_dept_22

15:02:25 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 7.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3q6tb4ta.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4ndujxik.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=11111', 'data', 'file=/tmp/tmpjd45me00/3q6tb4ta.json', 'init=/tmp/tmpjd45me00/4ndujxik.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelp2oq1_id/prophet_model-20260803150225.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:02:25 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_6_dept_47

15:02:35 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 7.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9_olenec.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/v1o3s_ak.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=1111', 'data', 'file=/tmp/tmpjd45me00/9_olenec.json', 'init=/tmp/tmpjd45me00/v1o3s_ak.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model_jkxej__/prophet_model-20260803150235.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:02:35 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_16_dept_47

15:02:46 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/67h9ed5g.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4nd2zfpz.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=57750', 'data', 'file=/tmp/tmpjd45me00/67h9ed5g.json', 'init=/tmp/tmpjd45me00/4nd2zfpz.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model7ztgz5uj/prophet_model-20260803150246.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:02:46 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_36_dept_56
Skip  store_36_dept_56 due to lack of data
Build prophet model for  store_12_dept_49

15:02:47 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 11.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/oowbospy.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7ag6udos.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=57929', 'data', 'file=/tmp/tmpjd45me00/oowbospy.json', 'init=/tmp/tmpjd45me00/7ag6udos.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model8u0nk_ct/prophet_model-20260803150247.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:02:47 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_19_dept_47

15:03:01 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/x52w_mf1.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/cqo9czg1.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=98554', 'data', 'file=/tmp/tmpjd45me00/x52w_mf1.json', 'init=/tmp/tmpjd45me00/cqo9czg1.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelgdpnxt19/prophet_model-20260803150301.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:03:01 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_23_dept_60

15:03:01 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 5.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2h7kmtkl.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/tngog5e9.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=43969', 'data', 'file=/tmp/tmpjd45me00/2h7kmtkl.json', 'init=/tmp/tmpjd45me00/tngog5e9.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelwieh5chx/prophet_model-20260803150301.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:03:01 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_28_dept_51
Skip  store_28_dept_51 due to lack of data
Build prophet model for  store_37_dept_44

15:03:10 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/b5uay3a7.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/okfhwhsb.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=22529', 'data', 'file=/tmp/tmpjd45me00/b5uay3a7.json', 'init=/tmp/tmpjd45me00/okfhwhsb.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelmff2cv18/prophet_model-20260803150311.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:03:11 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_6_dept_60

15:03:12 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0na73ulg.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pxxjxkdl.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=84819', 'data', 'file=/tmp/tmpjd45me00/0na73ulg.json', 'init=/tmp/tmpjd45me00/pxxjxkdl.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model6bkyvnpk/prophet_model-20260803150312.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:03:12 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_26_dept_60

15:03:13 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5brqc_kr.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/08h3ykrz.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=51702', 'data', 'file=/tmp/tmpjd45me00/5brqc_kr.json', 'init=/tmp/tmpjd45me00/08h3ykrz.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model2pry_1vh/prophet_model-20260803150313.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:03:13 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_41_dept_48

15:03:14 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 6.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/23coo4yx.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fng93t1u.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=21362', 'data', 'file=/tmp/tmpjd45me00/23coo4yx.json', 'init=/tmp/tmpjd45me00/fng93t1u.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modely6zgw20z/prophet_model-20260803150314.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:03:14 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_18_dept_47

15:03:24 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 20.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/tkv2j1xl.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/p75mnfji.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=90042', 'data', 'file=/tmp/tmpjd45me00/tkv2j1xl.json', 'init=/tmp/tmpjd45me00/p75mnfji.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelks6syw0n/prophet_model-20260803150324.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:03:24 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_39_dept_99

15:03:45 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 3.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/onhbfwcm.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/srg35s4_.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=54917', 'data', 'file=/tmp/tmpjd45me00/onhbfwcm.json', 'init=/tmp/tmpjd45me00/srg35s4_.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelchb0ilzz/prophet_model-20260803150346.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:03:46 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_45_dept_47

15:03:54 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/nd48sq5h.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/h73q7s8k.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=23766', 'data', 'file=/tmp/tmpjd45me00/nd48sq5h.json', 'init=/tmp/tmpjd45me00/h73q7s8k.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelrlcs88m1/prophet_model-20260803150355.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:03:55 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_25_dept_51
Skip  store_25_dept_51 due to lack of data
Build prophet model for  store_37_dept_23

15:03:55 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ccrtqsbk.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1aczqk66.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=43616', 'data', 'file=/tmp/tmpjd45me00/ccrtqsbk.json', 'init=/tmp/tmpjd45me00/1aczqk66.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelfeqa1e1z/prophet_model-20260803150355.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:03:55 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_42_dept_23

15:03:56 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/v70i_p4p.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ep3feim5.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=66947', 'data', 'file=/tmp/tmpjd45me00/v70i_p4p.json', 'init=/tmp/tmpjd45me00/ep3feim5.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelolcejp88/prophet_model-20260803150357.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:03:57 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_7_dept_48

15:03:57 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/luh6kjhm.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/u2cpxo25.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=8394', 'data', 'file=/tmp/tmpjd45me00/luh6kjhm.json', 'init=/tmp/tmpjd45me00/u2cpxo25.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modele8jf9glv/prophet_model-20260803150357.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:03:57 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_30_dept_23

15:03:58 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/doo2_jem.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/weqtsz9i.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=72678', 'data', 'file=/tmp/tmpjd45me00/doo2_jem.json', 'init=/tmp/tmpjd45me00/weqtsz9i.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelk6n55xln/prophet_model-20260803150358.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:03:58 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_31_dept_99

15:03:59 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/h0q1l_zo.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xjjg1tk6.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=64491', 'data', 'file=/tmp/tmpjd45me00/h0q1l_zo.json', 'init=/tmp/tmpjd45me00/xjjg1tk6.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelnm8kd6vj/prophet_model-20260803150359.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:03:59 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_33_dept_41

15:03:59 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/latas2dp.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0813wkzb.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=2700', 'data', 'file=/tmp/tmpjd45me00/latas2dp.json', 'init=/tmp/tmpjd45me00/0813wkzb.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeluf67ro9y/prophet_model-20260803150400.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:04:00 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_37_dept_27

15:04:00 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hlb3h7u_.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8atx13li.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=88869', 'data', 'file=/tmp/tmpjd45me00/hlb3h7u_.json', 'init=/tmp/tmpjd45me00/8atx13li.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelpkkb008w/prophet_model-20260803150400.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:04:00 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_42_dept_27

15:04:01 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/agatx8je.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gm15difp.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=60194', 'data', 'file=/tmp/tmpjd45me00/agatx8je.json', 'init=/tmp/tmpjd45me00/gm15difp.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelhghrh0_5/prophet_model-20260803150401.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:04:01 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_43_dept_23
Skip  store_43_dept_23 due to lack of data
Build prophet model for  store_30_dept_27
Skip  store_30_dept_27 due to lack of data
Build prophet model for  store_38_dept_27

15:04:02 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/d18uuzsj.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/sjzjjjkz.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=20712', 'data', 'file=/tmp/tmpjd45me00/d18uuzsj.json', 'init=/tmp/tmpjd45me00/sjzjjjkz.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelu6cn69an/prophet_model-20260803150402.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:04:02 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_11_dept_60

15:04:03 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 24.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5gpfu5de.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rb7fwen0.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=31627', 'data', 'file=/tmp/tmpjd45me00/5gpfu5de.json', 'init=/tmp/tmpjd45me00/rb7fwen0.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model4qrstupz/prophet_model-20260803150403.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:04:03 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_11_dept_99

15:04:27 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 17.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/me10otc5.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/65gwy03r.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=51455', 'data', 'file=/tmp/tmpjd45me00/me10otc5.json', 'init=/tmp/tmpjd45me00/65gwy03r.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model0yfzgv2v/prophet_model-20260803150427.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:04:27 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_19_dept_19
Skip  store_19_dept_19 due to lack of data
Build prophet model for  store_34_dept_99

15:04:45 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dclhf_b9.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/iiqg2n3y.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=20168', 'data', 'file=/tmp/tmpjd45me00/dclhf_b9.json', 'init=/tmp/tmpjd45me00/iiqg2n3y.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelf2teowzt/prophet_model-20260803150445.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:04:45 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_23_dept_47
Skip  store_23_dept_47 due to lack of data
Build prophet model for  store_39_dept_60

15:04:47 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 5.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/u_qt740h.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/32l70q3k.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=98287', 'data', 'file=/tmp/tmpjd45me00/u_qt740h.json', 'init=/tmp/tmpjd45me00/32l70q3k.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model0wwlb812/prophet_model-20260803150447.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:04:47 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_9_dept_80

15:04:55 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 21.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_88cexsg.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wsv8ivfc.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=40852', 'data', 'file=/tmp/tmpjd45me00/_88cexsg.json', 'init=/tmp/tmpjd45me00/wsv8ivfc.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model1c189bg6/prophet_model-20260803150455.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:04:55 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_27_dept_51
Skip  store_27_dept_51 due to lack of data
Build prophet model for  store_43_dept_27
Skip  store_43_dept_27 due to lack of data
Build prophet model for  store_2_dept_99

15:05:16 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 7.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dnftukir.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mlmoiapv.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=65682', 'data', 'file=/tmp/tmpjd45me00/dnftukir.json', 'init=/tmp/tmpjd45me00/mlmoiapv.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelpjpb_9cl/prophet_model-20260803150516.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:05:16 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_37_dept_24

15:05:27 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/w0hls4z5.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7_159i_x.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=62284', 'data', 'file=/tmp/tmpjd45me00/w0hls4z5.json', 'init=/tmp/tmpjd45me00/7_159i_x.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeldabminyc/prophet_model-20260803150527.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:05:27 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_44_dept_27

15:05:28 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 22.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2_wyqjz9.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2tqe6mu8.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=35626', 'data', 'file=/tmp/tmpjd45me00/2_wyqjz9.json', 'init=/tmp/tmpjd45me00/2tqe6mu8.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model0moe9jdj/prophet_model-20260803150528.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:05:28 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_20_dept_99

15:05:50 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 21.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3qvprmc2.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/uwlodj7q.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=43871', 'data', 'file=/tmp/tmpjd45me00/3qvprmc2.json', 'init=/tmp/tmpjd45me00/uwlodj7q.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelm_kp_tu2/prophet_model-20260803150551.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:05:51 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_4_dept_99

15:06:12 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 19.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/imxz8z2m.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3a8ix50z.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=17384', 'data', 'file=/tmp/tmpjd45me00/imxz8z2m.json', 'init=/tmp/tmpjd45me00/3a8ix50z.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeln6185o1v/prophet_model-20260803150612.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:06:12 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_6_dept_99

15:06:33 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 22.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/732dmut2.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gsak7604.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=32396', 'data', 'file=/tmp/tmpjd45me00/732dmut2.json', 'init=/tmp/tmpjd45me00/gsak7604.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelfw3zn2_s/prophet_model-20260803150633.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:06:33 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_14_dept_99

15:06:56 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 0.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7kwg4t86.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wuy8ygop.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=76361', 'data', 'file=/tmp/tmpjd45me00/7kwg4t86.json', 'init=/tmp/tmpjd45me00/wuy8ygop.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeldyqat63i/prophet_model-20260803150656.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:06:56 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_38_dept_29

15:07:02 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/d93drmi4.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8xqj17x9.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=56543', 'data', 'file=/tmp/tmpjd45me00/d93drmi4.json', 'init=/tmp/tmpjd45me00/8xqj17x9.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelqedyab43/prophet_model-20260803150703.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:07:03 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_37_dept_26
Skip  store_37_dept_26 due to lack of data
Build prophet model for  store_12_dept_78
Skip  store_12_dept_78 due to lack of data
Build prophet model for  store_45_dept_49

15:07:03 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/levjaezx.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/71agmtwk.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=41611', 'data', 'file=/tmp/tmpjd45me00/levjaezx.json', 'init=/tmp/tmpjd45me00/71agmtwk.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model606l788s/prophet_model-20260803150704.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:07:04 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_13_dept_78
Skip  store_13_dept_78 due to lack of data
Build prophet model for  store_40_dept_49

15:07:04 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/w6mg2wb3.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/95rt19vn.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=35323', 'data', 'file=/tmp/tmpjd45me00/w6mg2wb3.json', 'init=/tmp/tmpjd45me00/95rt19vn.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelkus49wvl/prophet_model-20260803150704.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:07:04 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_5_dept_47
Skip  store_5_dept_47 due to lack of data
Build prophet model for  store_9_dept_49

15:07:05 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 15.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7_6qvlqq.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/56u8kvd1.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=55786', 'data', 'file=/tmp/tmpjd45me00/7_6qvlqq.json', 'init=/tmp/tmpjd45me00/56u8kvd1.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model0h4y575k/prophet_model-20260803150706.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:07:06 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_23_dept_78
Skip  store_23_dept_78 due to lack of data
Build prophet model for  store_30_dept_22

15:07:23 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/oty0_l5r.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/oztl2adb.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=88929', 'data', 'file=/tmp/tmpjd45me00/oty0_l5r.json', 'init=/tmp/tmpjd45me00/oztl2adb.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model7gbjnu0a/prophet_model-20260803150724.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:07:24 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_30_dept_24
Skip  store_30_dept_24 due to lack of data
Build prophet model for  store_9_dept_48

15:07:24 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 21.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/kdoa56ic.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8dhv3smm.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=70705', 'data', 'file=/tmp/tmpjd45me00/kdoa56ic.json', 'init=/tmp/tmpjd45me00/8dhv3smm.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model8ce3hzhn/prophet_model-20260803150724.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:07:24 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_13_dept_99

15:07:45 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/21_k47ne.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pqs16p_2.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=21495', 'data', 'file=/tmp/tmpjd45me00/21_k47ne.json', 'init=/tmp/tmpjd45me00/pqs16p_2.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model8tlsbrm3/prophet_model-20260803150745.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:07:45 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_15_dept_78
Skip  store_15_dept_78 due to lack of data
Build prophet model for  store_16_dept_49

15:07:46 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 17.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/g2k08ryj.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/bc12abnr.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=41082', 'data', 'file=/tmp/tmpjd45me00/g2k08ryj.json', 'init=/tmp/tmpjd45me00/bc12abnr.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeltpu13wrt/prophet_model-20260803150747.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:07:47 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_1_dept_99

15:08:05 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7vlzkmel.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qgskpp66.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=3173', 'data', 'file=/tmp/tmpjd45me00/7vlzkmel.json', 'init=/tmp/tmpjd45me00/qgskpp66.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model25es4lj_/prophet_model-20260803150805.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:08:05 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_29_dept_49

15:08:06 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 19.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4mwuv4ik.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8cdicm50.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=14441', 'data', 'file=/tmp/tmpjd45me00/4mwuv4ik.json', 'init=/tmp/tmpjd45me00/8cdicm50.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modellsjh0mxn/prophet_model-20260803150806.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:08:06 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_32_dept_99

15:08:26 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 19.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/17waf3f7.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9dtuytyj.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=75969', 'data', 'file=/tmp/tmpjd45me00/17waf3f7.json', 'init=/tmp/tmpjd45me00/9dtuytyj.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelafen2mck/prophet_model-20260803150827.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:08:27 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_36_dept_31

15:08:47 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 19.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/dgcru0vk.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ueo3fdng.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=59201', 'data', 'file=/tmp/tmpjd45me00/dgcru0vk.json', 'init=/tmp/tmpjd45me00/ueo3fdng.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelkuav56pv/prophet_model-20260803150847.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:08:47 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_19_dept_78
Skip  store_19_dept_78 due to lack of data
Build prophet model for  store_19_dept_99

15:09:08 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 18.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/p_t11hrc.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zmmjv5y4.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=61965', 'data', 'file=/tmp/tmpjd45me00/p_t11hrc.json', 'init=/tmp/tmpjd45me00/zmmjv5y4.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelayydwf1y/prophet_model-20260803150909.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:09:09 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_24_dept_99

15:09:28 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 18.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/43vx8p0h.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/3mskjxwp.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=35614', 'data', 'file=/tmp/tmpjd45me00/43vx8p0h.json', 'init=/tmp/tmpjd45me00/3mskjxwp.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model16pc4z5c/prophet_model-20260803150928.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:09:28 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_26_dept_99

15:09:47 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 17.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_svxt9uu.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qpxv3ew3.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=25334', 'data', 'file=/tmp/tmpjd45me00/_svxt9uu.json', 'init=/tmp/tmpjd45me00/qpxv3ew3.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model0dle8g8f/prophet_model-20260803150947.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:09:47 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_27_dept_99

15:10:05 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 19.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8gz9p5by.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qh8f2afa.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=88180', 'data', 'file=/tmp/tmpjd45me00/8gz9p5by.json', 'init=/tmp/tmpjd45me00/qh8f2afa.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelnlk3ouk9/prophet_model-20260803151005.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:10:05 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_28_dept_99

15:10:25 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 20.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/creerfgp.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/gou6qbwa.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=29921', 'data', 'file=/tmp/tmpjd45me00/creerfgp.json', 'init=/tmp/tmpjd45me00/gou6qbwa.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model6ql2nlbs/prophet_model-20260803151025.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:10:25 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_41_dept_99

15:10:46 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 11.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ah197e_e.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mvgtxq18.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=34338', 'data', 'file=/tmp/tmpjd45me00/ah197e_e.json', 'init=/tmp/tmpjd45me00/mvgtxq18.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelsnajowif/prophet_model-20260803151046.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:10:46 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_37_dept_22

15:11:00 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 16.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/qr73zspi.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fk5e55vr.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=32654', 'data', 'file=/tmp/tmpjd45me00/qr73zspi.json', 'init=/tmp/tmpjd45me00/fk5e55vr.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelg4f1nxtw/prophet_model-20260803151100.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:11:00 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_40_dept_99

15:11:18 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 15.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6e8ewosc.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/v2dors8w.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=1836', 'data', 'file=/tmp/tmpjd45me00/6e8ewosc.json', 'init=/tmp/tmpjd45me00/v2dors8w.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelp70stuiz/prophet_model-20260803151118.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:11:18 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_8_dept_99

15:11:34 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 15.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ohp4qjy2.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/df3c44we.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=13677', 'data', 'file=/tmp/tmpjd45me00/ohp4qjy2.json', 'init=/tmp/tmpjd45me00/df3c44we.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeloielms4e/prophet_model-20260803151134.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:11:34 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_33_dept_31

15:11:50 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 0.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/6hng2gwp.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/07zhlkpa.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=59178', 'data', 'file=/tmp/tmpjd45me00/6hng2gwp.json', 'init=/tmp/tmpjd45me00/07zhlkpa.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model1e8dnnlq/prophet_model-20260803151150.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:11:50 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_36_dept_23
Skip  store_36_dept_23 due to lack of data
Build prophet model for  store_33_dept_33
Skip  store_33_dept_33 due to lack of data
Build prophet model for  store_33_dept_24
Skip  store_33_dept_24 due to lack of data
Build prophet model for  store_37_dept_33

15:11:58 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pgmq358i.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/cu3ug3_x.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=7043', 'data', 'file=/tmp/tmpjd45me00/pgmq358i.json', 'init=/tmp/tmpjd45me00/cu3ug3_x.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelkm6l21jz/prophet_model-20260803151158.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:11:58 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_27_dept_78
Skip  store_27_dept_78 due to lack of data
Build prophet model for  store_26_dept_48

15:11:58 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 3.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/x9bodxiz.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/_8hri5tg.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=19560', 'data', 'file=/tmp/tmpjd45me00/x9bodxiz.json', 'init=/tmp/tmpjd45me00/_8hri5tg.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelwc_t9_k_/prophet_model-20260803151159.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:11:59 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_26_dept_50
Skip  store_26_dept_50 due to lack of data
Build prophet model for  store_32_dept_78
Skip  store_32_dept_78 due to lack of data
Build prophet model for  store_36_dept_44

15:12:06 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 11.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ugea2phs.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/slzzl_fy.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=93927', 'data', 'file=/tmp/tmpjd45me00/ugea2phs.json', 'init=/tmp/tmpjd45me00/slzzl_fy.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model4jucxt2j/prophet_model-20260803151207.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:12:07 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_19_dept_48
Skip  store_19_dept_48 due to lack of data
Build prophet model for  store_5_dept_98

15:12:20 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ntvbhhyp.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2o3f0d_r.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=25388', 'data', 'file=/tmp/tmpjd45me00/ntvbhhyp.json', 'init=/tmp/tmpjd45me00/2o3f0d_r.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelwot79fbb/prophet_model-20260803151220.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:12:20 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_8_dept_78
Skip  store_8_dept_78 due to lack of data
Build prophet model for  store_16_dept_83

15:12:48 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ax32j3yd.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/w1kpb6ru.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=48199', 'data', 'file=/tmp/tmpjd45me00/ax32j3yd.json', 'init=/tmp/tmpjd45me00/w1kpb6ru.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model1papmr1k/prophet_model-20260803151248.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:12:48 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_16_dept_93

15:12:48 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/byhz209n.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/h_5uctw8.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=2257', 'data', 'file=/tmp/tmpjd45me00/byhz209n.json', 'init=/tmp/tmpjd45me00/h_5uctw8.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelltyjqwpv/prophet_model-20260803151249.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:12:49 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_5_dept_49

15:12:49 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1syq1ta_.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/xzcuyj1p.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=29275', 'data', 'file=/tmp/tmpjd45me00/1syq1ta_.json', 'init=/tmp/tmpjd45me00/xzcuyj1p.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelyn29ze4k/prophet_model-20260803151249.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:12:49 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_3_dept_49

15:12:49 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 10.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/googy8v4.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/9gexliic.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=1696', 'data', 'file=/tmp/tmpjd45me00/googy8v4.json', 'init=/tmp/tmpjd45me00/9gexliic.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelg42wy82g/prophet_model-20260803151249.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:12:49 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_3_dept_80

15:13:02 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 15.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/2k13ffpm.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/4lc843bo.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=18842', 'data', 'file=/tmp/tmpjd45me00/2k13ffpm.json', 'init=/tmp/tmpjd45me00/4lc843bo.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelrj3275p_/prophet_model-20260803151302.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:13:02 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_43_dept_22

15:13:18 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 19.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/pe1angzu.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/w4_q8vbe.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=55209', 'data', 'file=/tmp/tmpjd45me00/pe1angzu.json', 'init=/tmp/tmpjd45me00/w4_q8vbe.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelbbu5xcy4/prophet_model-20260803151318.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:13:18 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_9_dept_98
Skip  store_9_dept_98 due to lack of data
Build prophet model for  store_38_dept_22

15:13:38 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 1.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/017exgal.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/savgyp4i.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=1946', 'data', 'file=/tmp/tmpjd45me00/017exgal.json', 'init=/tmp/tmpjd45me00/savgyp4i.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model3edmua5u/prophet_model-20260803151338.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:13:38 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_32_dept_48
Skip  store_32_dept_48 due to lack of data
Build prophet model for  store_39_dept_47
Skip  store_39_dept_47 due to lack of data
Build prophet model for  store_35_dept_19

15:13:45 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 6.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/1eq7q5a5.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0abxbheo.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=67026', 'data', 'file=/tmp/tmpjd45me00/1eq7q5a5.json', 'init=/tmp/tmpjd45me00/0abxbheo.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelxe71cmwi/prophet_model-20260803151346.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:13:46 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_43_dept_33
Skip  store_43_dept_33 due to lack of data
Build prophet model for  store_32_dept_47

15:13:51 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 9.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wk8mjo4x.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/24fzfge1.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=97418', 'data', 'file=/tmp/tmpjd45me00/wk8mjo4x.json', 'init=/tmp/tmpjd45me00/24fzfge1.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelx5bv61ku/prophet_model-20260803151351.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:13:51 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_42_dept_22

15:14:03 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 3.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/w1pmvpq7.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5_9zgz42.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=84548', 'data', 'file=/tmp/tmpjd45me00/w1pmvpq7.json', 'init=/tmp/tmpjd45me00/5_9zgz42.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelbd47voak/prophet_model-20260803151403.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:14:03 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_44_dept_22
Skip  store_44_dept_22 due to lack of data
Build prophet model for  store_22_dept_47

15:14:12 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 17.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/o9ujto1s.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/kst0ohxa.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=81460', 'data', 'file=/tmp/tmpjd45me00/o9ujto1s.json', 'init=/tmp/tmpjd45me00/kst0ohxa.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeldrmsz6ry/prophet_model-20260803151412.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:14:12 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_16_dept_48

15:14:29 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 23.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/in19ovbs.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5hdmlg91.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=56305', 'data', 'file=/tmp/tmpjd45me00/in19ovbs.json', 'init=/tmp/tmpjd45me00/5hdmlg91.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model2zoqs6fv/prophet_model-20260803151429.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:14:29 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_17_dept_78
Skip  store_17_dept_78 due to lack of data
Build prophet model for  store_17_dept_96

15:14:52 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 3.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/opbt13tn.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/sg18t8em.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=54297', 'data', 'file=/tmp/tmpjd45me00/opbt13tn.json', 'init=/tmp/tmpjd45me00/sg18t8em.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model5jh9vc6g/prophet_model-20260803151452.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:14:52 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_30_dept_49
Skip  store_30_dept_49 due to lack of data
Build prophet model for  store_34_dept_47

15:15:01 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 21.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fep9qk2h.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7n1g0xbg.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=11748', 'data', 'file=/tmp/tmpjd45me00/fep9qk2h.json', 'init=/tmp/tmpjd45me00/7n1g0xbg.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelzw1ioh0b/prophet_model-20260803151501.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:15:01 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_37_dept_49

15:15:02 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 11.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/wmscldzy.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/14aaabmy.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=10614', 'data', 'file=/tmp/tmpjd45me00/wmscldzy.json', 'init=/tmp/tmpjd45me00/14aaabmy.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelc__gxkxa/prophet_model-20260803151502.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:15:02 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_18_dept_96

15:15:15 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 1.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/p4_o46rb.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0hpjbuyr.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=14674', 'data', 'file=/tmp/tmpjd45me00/p4_o46rb.json', 'init=/tmp/tmpjd45me00/0hpjbuyr.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model2v1x1y6p/prophet_model-20260803151515.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:15:15 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_24_dept_47
Skip  store_24_dept_47 due to lack of data
Build prophet model for  store_28_dept_78
Skip  store_28_dept_78 due to lack of data
Build prophet model for  store_2_dept_78
Skip  store_2_dept_78 due to lack of data
Build prophet model for  store_13_dept_47

15:15:23 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 2.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jonyx5pf.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/yvldg4a7.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=70805', 'data', 'file=/tmp/tmpjd45me00/jonyx5pf.json', 'init=/tmp/tmpjd45me00/yvldg4a7.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeluxdq7j8s/prophet_model-20260803151523.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:15:23 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_31_dept_78
Skip  store_31_dept_78 due to lack of data
Build prophet model for  store_36_dept_22

15:15:28 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 0.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/5fxn4dq2.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jwdz4bdb.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=18168', 'data', 'file=/tmp/tmpjd45me00/5fxn4dq2.json', 'init=/tmp/tmpjd45me00/jwdz4bdb.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelxfafoeyn/prophet_model-20260803151528.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:15:28 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_20_dept_77

15:15:36 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 11.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/e6ny15e4.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rzwj5yfu.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=15401', 'data', 'file=/tmp/tmpjd45me00/e6ny15e4.json', 'init=/tmp/tmpjd45me00/rzwj5yfu.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modely4yprj32/prophet_model-20260803151536.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:15:36 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_38_dept_49

15:15:50 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 15.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/oniw8d34.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/zcz8repk.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=42950', 'data', 'file=/tmp/tmpjd45me00/oniw8d34.json', 'init=/tmp/tmpjd45me00/zcz8repk.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelfke6q0ql/prophet_model-20260803151550.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:15:50 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_4_dept_77
Skip  store_4_dept_77 due to lack of data
Build prophet model for  store_30_dept_55
Skip  store_30_dept_55 due to lack of data
Build prophet model for  store_42_dept_49

15:16:05 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 12.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/74i8bgxi.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/jvi10soq.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=77469', 'data', 'file=/tmp/tmpjd45me00/74i8bgxi.json', 'init=/tmp/tmpjd45me00/jvi10soq.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model2tjskdvi/prophet_model-20260803151605.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:16:05 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_45_dept_77
Skip  store_45_dept_77 due to lack of data
Build prophet model for  store_27_dept_77
Skip  store_27_dept_77 due to lack of data
Build prophet model for  store_33_dept_32

15:16:20 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 12.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7ed_wgit.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/aozt9ijl.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=55168', 'data', 'file=/tmp/tmpjd45me00/7ed_wgit.json', 'init=/tmp/tmpjd45me00/aozt9ijl.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model9hd470xf/prophet_model-20260803151620.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:16:20 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_37_dept_32

15:16:34 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 2.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8sljsqaz.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/0br6_3no.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=36320', 'data', 'file=/tmp/tmpjd45me00/8sljsqaz.json', 'init=/tmp/tmpjd45me00/0br6_3no.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelpqq64w2v/prophet_model-20260803151634.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:16:34 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_14_dept_96

15:16:43 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 2.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/nsny8ja8.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/vku_f3db.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=9956', 'data', 'file=/tmp/tmpjd45me00/nsny8ja8.json', 'init=/tmp/tmpjd45me00/vku_f3db.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelcw_wqsi0/prophet_model-20260803151643.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:16:43 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_20_dept_96

15:16:48 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 10.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/a_2a64vj.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/mdzlv2sv.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=22508', 'data', 'file=/tmp/tmpjd45me00/a_2a64vj.json', 'init=/tmp/tmpjd45me00/mdzlv2sv.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelqcio81fj/prophet_model-20260803151648.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:16:48 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_44_dept_26

15:17:00 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 6.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/uet6zof1.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/d08rydo2.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=492', 'data', 'file=/tmp/tmpjd45me00/uet6zof1.json', 'init=/tmp/tmpjd45me00/d08rydo2.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model9yyyiked/prophet_model-20260803151700.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:17:00 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_33_dept_23

15:17:11 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 5.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/q_32egxr.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/w2ohijll.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=8787', 'data', 'file=/tmp/tmpjd45me00/q_32egxr.json', 'init=/tmp/tmpjd45me00/w2ohijll.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelax_olnvj/prophet_model-20260803151711.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:17:11 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_44_dept_24

15:17:20 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 5.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/8_c37fg7.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/hrf9t6pd.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=94218', 'data', 'file=/tmp/tmpjd45me00/8_c37fg7.json', 'init=/tmp/tmpjd45me00/hrf9t6pd.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeljgqwvp6e/prophet_model-20260803151720.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:17:20 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_42_dept_71
Fail to train  store_42_dept_71 : Dataframe has less than 2 non-NaN rows.
Build prophet model for  store_43_dept_49

15:17:29 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 2.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/f6faijkk.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/47pcod65.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=7745', 'data', 'file=/tmp/tmpjd45me00/f6faijkk.json', 'init=/tmp/tmpjd45me00/47pcod65.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeloqjgfqz7/prophet_model-20260803151729.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:17:29 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_12_dept_96

15:17:37 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 1.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/cy_8x463.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/7cwz8p7t.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=7752', 'data', 'file=/tmp/tmpjd45me00/cy_8x463.json', 'init=/tmp/tmpjd45me00/7cwz8p7t.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelfbxfyjew/prophet_model-20260803151737.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:17:37 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_36_dept_72

15:17:44 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 4.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/od32x5p_.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/o6j4gsrz.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=82496', 'data', 'file=/tmp/tmpjd45me00/od32x5p_.json', 'init=/tmp/tmpjd45me00/o6j4gsrz.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modelp2zv7zv6/prophet_model-20260803151744.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:17:44 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_44_dept_33

15:17:53 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 1.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/ilmjzqvq.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/o48m56vs.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=86405', 'data', 'file=/tmp/tmpjd45me00/ilmjzqvq.json', 'init=/tmp/tmpjd45me00/o48m56vs.json', 'output', 'file=/tmp/tmpjd45me00/prophet_modeldit5dzdc/prophet_model-20260803151753.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:17:53 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_17_dept_47
Skip  store_17_dept_47 due to lack of data
Build prophet model for  store_35_dept_96

15:18:01 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:n_changepoints greater than number of observations. Using 0.
INFO:prophet:n_changepoints greater than number of observations. Using 1.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/rp9vnof1.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpjd45me00/fb9adifc.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=73342', 'data', 'file=/tmp/tmpjd45me00/rp9vnof1.json', 'init=/tmp/tmpjd45me00/fb9adifc.json', 'output', 'file=/tmp/tmpjd45me00/prophet_model0ng0ctbv/prophet_model-20260803151802.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
15:18:02 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Build prophet model for  store_30_dept_99
Build prophet model for  store_36_dept_32

15:18:06 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Build prophet model for  store_25_dept_48
Skip  store_25_dept_48 due to lack of data
Build prophet model for  store_42_dept_26
Skip  store_42_dept_26 due to lack of data
Build prophet model for  store_44_dept_49
Skip  store_44_dept_49 due to lack of data
Build prophet model for  store_22_dept_96
Skip  store_22_dept_96 due to lack of data
Build prophet model for  store_38_dept_55
Skip  store_38_dept_55 due to lack of data
Build prophet model for  store_19_dept_39
Skip  store_19_dept_39 due to lack of data

KeyError: 'rmse'

In [ ]:
print(
    f"Prophet Model Results:\nMAE: {mean_mae:.2f} | RMSE: {mean_rmse:.2f} | WAPE: {ovr_wampe:.2f}%"
)

NameError: name 'mean_mae' is not defined